### ISSUE TITLE
Multiple domains in one certificate and only first auto-renewed

### ISSUE THREAD

**Issue by ghost** [acmesh-official/acme.sh#1007]
I have 10 domains bundled into one certificate using DNS authentication. Today was the first automatic renewal. Certificate renewed without any issues, but it was installed only to the first domain name using cpanel uapi. Is there a restriction to have only one 1 domain/certificate? I guess it would have worked OK if I had created individual certs for each domain. I have the detailed log if you want to see it.

This could be my bad as well because I was coding the cpanel hook at the same time.

**Comment by Neilpang** [comment]
the cpanel_uapi  hook can only deploy to the first domain.

you can issue one cert for one domain, and deploy them one by one.

**Comment by 2globalnomads** [comment]
Does this apply to all deploy hooks or just cpanel_uapi? After you tell this I will update instructions accordingly.

**Comment by FernandoMiguel** [comment]
is there a way we can deploy the same cert to several domains?
currently it seems to fail to access the 2nd domain, cause there is only one cert.

maybe re-use the same path?

**Comment by 2globalnomads** [comment]
Nope, the only way is to manually install them through CPANEL, and in that case they will not renew automatically. Issue them one by one or append the API to support multiple deploys.

UAPI supports multiple deploying domains so there is no problems on that side.

**Comment by FernandoMiguel** [comment]
my problem with this is, if you have 21 (sub)domains, you are limited to rate limits of 20 per week
i tried to issue a cert with two domains, but ofc when deploying to cpanel, it worked with the 1st but failed with the second :( 

adding via cpanel, both work , but they wont auto renew

is any way to minimize this problem? any work around?

**Comment by 2globalnomads** [comment]
> is any way to minimize this problem? any work around?

Nope, but you are probably most welcome to help to make the api support for that. Talk to @Neilpang.

**Comment by Neilpang** [comment]
Let's reopen this issue, and wait to see what we can do better here.

**Comment by wp-networks** [comment]
This has been a thing for me as well... for now I've just sidestepped:
https://documentation.cpanel.net/display/CKB/The+SSL+Installation+and+Precedence+Logic
...working on the idea that you can get away with thinking about deploy to virtualhost
...can alias domains to addondomains, can alias subdomains to domains
https://documentation.cpanel.net/display/DD/cPanel+API+2+Functions+-+Park%3A%3Apark
...will update here when I have more time, super busy atm :)

**Comment by dannytix** [comment]
Please see pull request [4256](https://github.com/acmesh-official/acme.sh/pull/4256) for a possible solution.
