### ISSUE TITLE
cpanel_uapi SAN cert

### ISSUE THREAD

**Issue by FernandoMiguel** [acmesh-official/acme.sh#1045]
@2globalnomads
your documentation states that a SAN cert can't be deployed to multiple domains.
I tried that and got indeed an error.

but cpanel dashboard does allow to import a deployed cert to to another domain.

is there a limitation in the API or could there be something added to allow this?

having a SAN greatly reduces the number of LE issues, avoiding API limits

**Comment by 2globalnomads** [comment]
API limitation see #1007. Ask @Neilpang, I don't know why. AFAIK the same limitation applies to all deploys.

**Comment by dannytix** [comment]
Bumping an old issue to shamelessly promote pull request [4256](https://github.com/acmesh-official/acme.sh/pull/4256) which aims to address this problem.
