### ISSUE TITLE
error "Please specify at least one validation method" (2nd posting)

### ISSUE THREAD

**Issue by klausph** [acmesh-official/acme.sh#1172]
I'm very sorry, to repeat this issue. maybe also, I've stopped our discussion. 
it may be seems, that discussion was "closed" by me ;-(

And: I'm in a horrible sorrow! there someone, who can't access to the website, becvause they are coming from a https-address. 
normally my adress ist http://mysobdomain.mydomain.de. but an automated link from an httpsadress, its horrible for the browser, and more horrible to user, they don't know to react.

### okay, here again:
1. I have it installed on may 2017 with this:
machine:~/.acme.sh # ./acme.sh --issue --apache -d mysubdomain.mydomain.de -d www.mysubdomain.mydomain.de
-> here's is the declaration, it was installed with --apache !!!

2. it runs with cron until beginning or end of dec.2017:
50 23 * * * root /root/.acme.sh/acme.sh --cron --home /root/.acme.sh --log /var/log/acme.log > /dev/null

3. after beginning or end of dec.2017 I have found errors like this:
...
[So 7. Jan 17:40:00 CET 2018] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[So 7. Jan 17:40:00 CET 2018] DOMAIN_PATH='/root/.acme.sh/mysubdomain.mydomain.de'
[So 7. Jan 17:40:00 CET 2018] Renew: 'mysubdomain.mydomain.de'
Please specify at least one validation method: '--webroot', '--standalone', '--apache', '--nginx' or '--dns' etc.
[So 7. Jan 17:40:00 CET 2018] Return code: 1
[So 7. Jan 17:40:00 CET 2018] Error renew mysubdomain.mydomain.de.
[So 7. Jan 17:40:00 CET 2018] ===End cron===

4. jan.2018 I have done:
acme.sh --upgrade
upgrading vom 2.7.2 to actual version 2.7.6
no error, no problem on upgrade.

5. NeilPang wants to know: /root/.acme.sh/mysubdomain.mydomain.de/mysubdomain.mydomain.de.conf'
here's info about conf:
Le_RealFullChainPath=''
Le_RealCertPath='/etc/apache2/ssl.crt/mysubdomain.mydomain.de.crt'
Le_RealCACertPath=''
Le_RealKeyPath='/etc/apache2/ssl.key/mysubdomain.mydomain.de.key'
Le_ReloadCmd='service apache2 force-reload'
Le_CertCreateTime='1507326617'
Le_CertCreateTimeStr='Fri Oct 6 21:50:17 UTC 2017'
Le_NextRenewTimeStr='Tue Dec 5 21:50:17 UTC 2017'
Le_NextRenewTime='1512424217'

6. but everytime:
machine:~/.acme.sh # ~/.acme.sh/acme.sh --cron --log /var/log/acme.log --home /root/.acme.sh --force --debug 2
here it is:
[So 7. Jan 17:39:58 CET 2018] Lets find script dir.
[So 7. Jan 17:39:58 CET 2018] SCRIPT='/root/.acme.sh/acme.sh'
[So 7. Jan 17:39:58 CET 2018] _script='/root/.acme.sh/acme.sh'
[So 7. Jan 17:39:58 CET 2018] _script_home='/root/.acme.sh'
[So 7. Jan 17:39:58 CET 2018] Using config home:/root/.acme.sh
[So 7. Jan 17:39:58 CET 2018] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.7.6
[So 7. Jan 17:39:58 CET 2018] Using config home:/root/.acme.sh
[So 7. Jan 17:39:58 CET 2018] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[So 7. Jan 17:39:58 CET 2018] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[So 7. Jan 17:39:58 CET 2018] ===Starting cron===
[So 7. Jan 17:39:58 CET 2018] Using config home:/root/.acme.sh
[So 7. Jan 17:39:58 CET 2018] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[So 7. Jan 17:39:58 CET 2018] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[So 7. Jan 17:39:58 CET 2018] Installing from online archive.
[So 7. Jan 17:39:58 CET 2018] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[So 7. Jan 17:39:58 CET 2018] GET
[So 7. Jan 17:39:58 CET 2018] url='https://github.com/Neilpang/acme.sh/archive/master.tar.gz'
[So 7. Jan 17:39:58 CET 2018] timeout
[So 7. Jan 17:39:58 CET 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header --trace-ascii /tmp/tmp.JdjLW6ciIJ '
[So 7. Jan 17:40:00 CET 2018] ret='0'
[So 7. Jan 17:40:00 CET 2018] Extracting master.tar.gz
[So 7. Jan 17:40:00 CET 2018] Installing to /root/.acme.sh
[So 7. Jan 17:40:00 CET 2018] Installed to /root/.acme.sh/acme.sh
[So 7. Jan 17:40:00 CET 2018] Good, bash is found, so change the shebang to use bash as preferred.
[So 7. Jan 17:40:00 CET 2018] OK
[So 7. Jan 17:40:00 CET 2018] Install success!
[So 7. Jan 17:40:00 CET 2018] Upgrade success!
[So 7. Jan 17:40:00 CET 2018] Using config home:/root/.acme.sh
[So 7. Jan 17:40:00 CET 2018] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[So 7. Jan 17:40:00 CET 2018] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[So 7. Jan 17:40:00 CET 2018] Auto upgraded to: 2.7.6
[So 7. Jan 17:40:00 CET 2018] Using config home:/root/.acme.sh
[So 7. Jan 17:40:00 CET 2018] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[So 7. Jan 17:40:00 CET 2018] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[So 7. Jan 17:40:00 CET 2018] _stopRenewOnError
[So 7. Jan 17:40:00 CET 2018] di='/root/.acme.sh/mysubdomain.mydomain.de/'
[So 7. Jan 17:40:00 CET 2018] d='mysubdomain.mydomain.de'
[So 7. Jan 17:40:00 CET 2018] Using config home:/root/.acme.sh
[So 7. Jan 17:40:00 CET 2018] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[So 7. Jan 17:40:00 CET 2018] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[So 7. Jan 17:40:00 CET 2018] DOMAIN_PATH='/root/.acme.sh/mysubdomain.mydomain.de'
[So 7. Jan 17:40:00 CET 2018] Renew: 'mysubdomain.mydomain.de'
Please specify at least one validation method: '--webroot', '--standalone', '--apache', '--nginx' or '--dns' etc.
[So 7. Jan 17:40:00 CET 2018] Return code: 1
[So 7. Jan 17:40:00 CET 2018] Error renew mysubdomain.mydomain.de.
[So 7. Jan 17:40:00 CET 2018] ===End cron===

thats is to do?
where have I to specify "validation method"?
user "publicarray" has argued, that I have forgotten one option. I think, I havn't! ;-) 

thanks a lot
Yours klaus

**Comment by Neilpang** [comment]
please add a line in the file `/root/.acme.sh/mysubdomain.mydomain.de/mysubdomain.mydomain.de.conf'


```sh
Le_Webroot='apache'
```

Then try again.

**Comment by klausph** [comment]
great! 
no sorrow anymore!

it means: in *.conf must have been written:
Le_Webroot=.......  'apache' or something other.

is it a good idea: to specify the errormessage?! ;-)

thanks a lot!
yours klaus

**Comment by Neilpang** [comment]
The line `Le_Webroot='apache'`  should have been written in the conf file before automatically.
I don't know why it was missing.

**Comment by ForestJohnson** [comment]
I was still hitting this error, I was able to fix it by changing `Le_Webroot=''` to `Le_Webroot='no'`  inside the `<domain-name>/<domain-name.conf>` file.
