### ISSUE TITLE
Renew vs. Reload

### ISSUE THREAD

**Issue by tcocca** [acmesh-official/acme.sh#1321]
Hello,

I am using acme.sh to generate certs and install them for an haproxy config

I am using the following:

/home/deploy/acme.sh/acme.sh --issue -d domain.com --standalone --httpport 8080 --renew-hook '/home/deploy/.acme.sh/install-cert.sh $_main_domain'
/home/deploy/acme.sh/acme.sh --install-cert -d domain.com --reloadcmd '/home/deploy/.acme.sh/install-cert.sh $_main_domain'

The install-cert.sh basically just does the following:

```
#!/bin/bash
domain=$1
echo "Install Certificate:"
echo "Domain: $domain"

cat /home/deploy/.acme.sh/$domain/$domain.key /home/deploy/.acme.sh/$domain/fullchain.cer > /etc/haproxy/certs/$domain.pem
sudo service haproxy reload
```

So the idea being I issue the certificate and set the renew command and then I call the install which issues the same command.

My question is does the `renew` which gets run from CRON issue both the renew-hook and --reloadcmd commands for the cert?

I ran the following:
/home/deploy/acme.sh/acme.sh --renew -d domain.com --force

And I got:
```
[Fri Mar  2 13:57:46 UTC 2018] Run renew hook:'/home/deploy/.acme.sh/install-cert.sh $_main_domain'
Install Certificate:
Domain: domain.com
[Fri Mar  2 13:57:46 UTC 2018] Run reload cmd: /home/deploy/.acme.sh/install-cert.sh $_main_domain
Install Certificate:
Domain:domain.com
[Fri Mar  2 13:57:46 UTC 2018] Reload success
```

So the --renew with a force ran both.  I'm wondering if the cron renew does the same, if so I guess I need to remove the `/home/deploy/acme.sh/acme.sh --install-cert -d domain.com --reloadcmd '/home/deploy/.acme.sh/install-cert.sh $_main_domain'` and just run my /home/deploy/.acme.sh/install-cert.sh manually passing the domain to it after the issue.

**Comment by dwatrous** [comment]
I just submitted a pull request that handles the deployment of HAProxy certificates: https://github.com/Neilpang/acme.sh/pull/1584

**Comment by wedi** [comment]
From the `--help` output:

```
--reloadcmd <command>             Command to execute after issue/renew to reload the server.
--renew-hook <command>            Command to be run after each successfully renewed certificate.
```

It looks like the only difference is that the renew hook does not get executed right after issuing the certificate.
