### ISSUE TITLE
Support for extendedKeyUsage

### ISSUE THREAD

**Issue by mtehonica** [acmesh-official/acme.sh#1335]
Is there a way to get extendedKeyUsage support in acme.sh?  Specifically serverAuth.  It looks like LE does support it but acme.sh doesn't include it in the CSR.

**Comment by mtehonica** [comment]
Some applications requiring "ServerAuth" have wording like: 
- "The certificate is valid for Server Authentication"
- "The Extended Key Usage certificate extension must include the Server Authentication Object Identifier (OID): 1.3.6.1.5.5.7.3.1"

I think it just requires adding the following under the [ v3 req ] of the csr: `extendedKeyUsage=serverAuth,clientAuth`

Here are a few links with more details... 
- https://letsencrypt.org/documents/isrg-cps-v2.0/#dv-ssl-end-entity-certificate
> Extended Key Usage - TLS Server Authentication, TLS Client Authentication

- https://community.letsencrypt.org/t/using-lets-encrypt-for-virtual-mail-hosts/2358/14
> the OID 1.3.6.1.5.5.7.3.18 for this restriction is usually translated to humans as “ServerAuth” (Server Authentication)

- https://community.letsencrypt.org/t/is-this-certificates-support-to-ldap-or-it-is-only-for-websites-and-blogs/48380/6
> 1.3.6.1.5.5.7.3.1 is the OID for “TLS Server Authentication,” in Let’s Encrypt certificates.

**Comment by Neilpang** [comment]
The `TLS Server Authentication, TLS Client Authentication`  usage are already included in the cert by default.

**Comment by mtehonica** [comment]
OK, good to know.  Didn't think they were since they weren't explicitly listed in the csr.  Thanks!

**Comment by senthilkumarkj** [comment]
I used acme.sh to generate a cert from `publicca.googleapis.com` and the cert only had 
```
X509v3 Extended Key Usage:
                TLS Web Server Authentication
```

I appended `extendedKeyUsage=serverAuth,clientAuth\n` to csr conf and renewed the cert and the new cert had client auth. 
```
 X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
```
Ext key usage seems like a valid option that could be added.

**Comment by Neilpang** [comment]
fixed
