### ISSUE TITLE
如何将证书推送到阿里云的CDN？

### ISSUE THREAD

**Issue by abcfy2** [acmesh-official/acme.sh#1461]
作者你好。非常感谢这个方便的程序，可以轻松申请范域名证书。我现在期望能在申请证书或者renew证书之后，自动将新证书推送至阿里云。

阿里云的api是现成的，我自己写脚本也不成问题，我看程序配置中已经有`hook`配置，会执行脚本。能否将证书路径或证书内容以环境变量或命令行参数的形式传给hook脚本呢？

PS: 这个程序非常不错，小捐助一笔聊表心意:)

**Comment by Neilpang** [comment]
是的 目前有 deploy hook 的机制.
你可以尝试提交一个 aliyun 的hook.    你需要啥环境变量, 没有的我给你加. 你先写.

**Comment by Neilpang** [comment]
不知道这个是不是你想要的: https://github.com/Neilpang/acme.sh/pull/1099

**Comment by abcfy2** [comment]
大致就是这样，阿里云有个证书服务，可以允许自己上传证书，用于CDN,OSS,SLB等等，我觉得阿里云系列的几个脚本可以整合

**Comment by Neilpang** [comment]
是的, 我一直没有时间整合, 所以一直没有 merge 进来.

**Comment by BROBIRD** [comment]
腾讯云也有相关API

**Comment by abcfy2** [comment]
建议在执行post hook以及renew hook的时候，注入`LE_FULL_CHAIN_PATH`,`LE_FULL_CHAIN`,`LE_KEY`, `LE_KEY_PATH`四个环境变量，分别对应`fullchain内容`,`fullchain证书路径`,`私玥内容`，`私玥路径`，以便hook程序可以直接从这些环境变量拿到所需的内容进行后续自定义操作

**Comment by abcfy2** [comment]
LGTM

**Comment by dengcb** [comment]
腾讯云用户飘过，有没有可能顺便带一下腾讯云的用户呢？
腾讯云CDN的api文档在此：
https://cloud.tencent.com/document/product/228/12965

**Comment by shiny** [comment]
很需要这个功能，很多云服务都可以使用。

**Comment by shoyuf** [comment]
> @WETOOP LGTM

Why not merge?

**Comment by bestK** [comment]
Try this


https://github.com/Hill-98/aliyun-openapi-bash-sdk/blob/0d407450dc5cc062bea2a1be8970b98607650838/examples/UpdateSSLCert.sh

**Comment by HADB** [comment]
Any updates?

**Comment by anjia0532** [comment]
我自己写了个小工具（暂时不准备开源），仅做参考

![image](https://github.com/acmesh-official/acme.sh/assets/15098916/18e08a3c-622f-48ee-bd7c-04372150705d)
![image](https://github.com/acmesh-official/acme.sh/assets/15098916/c7f547fb-8074-4bb7-962a-4dbd4af2c406)

**Comment by nickfan** [comment]
> 我自己写了个小工具（暂时不准备开源），仅做参考
> 
> ![image](https://private-user-images.githubusercontent.com/15098916/334016003-18e08a3c-622f-48ee-bd7c-04372150705d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwODQxNjEsIm5iZiI6MTcxNzA4Mzg2MSwicGF0aCI6Ii8xNTA5ODkxNi8zMzQwMTYwMDMtMThlMDhhM2MtNjIyZi00OGVlLWJkN2MtMDQzNzIxNTA3MDVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDE1NDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkMDAyYzk0NWViNjZkMGVkNDI0NDRkYTk1YzI4ODNmMDkyMTA4MmUxMjVkZDgzOGYwYzYwN2FmYWU0N2UxZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t4cRYJ2LE0VcaTGbSCyuZcYTdlKMchxEFp-rMWKjqpI) ![image](https://private-user-images.githubusercontent.com/15098916/334016178-c7f547fb-8074-4bb7-962a-4dbd4af2c406.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwODQxNjEsIm5iZiI6MTcxNzA4Mzg2MSwicGF0aCI6Ii8xNTA5ODkxNi8zMzQwMTYxNzgtYzdmNTQ3ZmItODA3NC00YmI3LTk2MmEtNGRiZDRhZjJjNDA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDE1NDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZGQxZDcyMTdjNDZlMmM3YTZjYzAyZGJlMTFjYTI2MTk2NWEzNGIzODRmOWQ3ZjIwZjlkNzhkNWUxZDk3YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J-xwCPaKYVzBw0TV35JbK-5biLAJyvwGHqBz9Aqp-Ws)

然而，阿里云自己上传的证书是不能自动在具体服务中选定的，需要人工指定，小站还好，域名多了异常难搞。

**Comment by anjia0532** [comment]
这个完全看云服务的api支不支持。一般来说，正常业务不会有大量域名（一般同级域名配通配符就行了），目前我这边的都是手动创建具体业务，后续通过api自动续期新证书是没问题的。

**Comment by shellus** [comment]
> 我自己写了个小工具（暂时不准备开源），仅做参考
> 
> ![image](https://private-user-images.githubusercontent.com/15098916/334016003-18e08a3c-622f-48ee-bd7c-04372150705d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNjI5NDQsIm5iZiI6MTcyMjA2MjY0NCwicGF0aCI6Ii8xNTA5ODkxNi8zMzQwMTYwMDMtMThlMDhhM2MtNjIyZi00OGVlLWJkN2MtMDQzNzIxNTA3MDVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDA2NDQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlOGNiNjFkNzU1ZjYwN2M4YjZjMjAzNGZmMTAzZTZhMjE2ZjEwYmE3ODUwOTJlZmQ0ZDM5YWU3NDVkNThlYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DlFSvKtaKpbvb9MrcWmMiIfm6-ePYBsD6X8ZPKpigqw) ![image](https://private-user-images.githubusercontent.com/15098916/334016178-c7f547fb-8074-4bb7-962a-4dbd4af2c406.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNjI5NDQsIm5iZiI6MTcyMjA2MjY0NCwicGF0aCI6Ii8xNTA5ODkxNi8zMzQwMTYxNzgtYzdmNTQ3ZmItODA3NC00YmI3LTk2MmEtNGRiZDRhZjJjNDA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDA2NDQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1N2Q3NjJkODJhODhlMDA1ZGYxZTQ0MDc5M2NlZDQ4YWY0ODIxOWJhNGVmOWVkZmQ0YjRjZWQ3YjBkZWNkNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MguO6IiUYLcDjHl_eNdI3kXX5Xv4tO6R_pcD5xpdRfs)

阿里云的30元一次没有理解，难道说我一个oss的域名，在使用acme.sh签发和续费证书的情况下，仅仅使用脚本部署，就要为此付出每年120元以上的费用？

**Comment by anjia0532** [comment]
> > 我自己写了个小工具（暂时不准备开源），仅做参考
> > ![image](https://private-user-images.githubusercontent.com/15098916/334016003-18e08a3c-622f-48ee-bd7c-04372150705d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNjI5NDQsIm5iZiI6MTcyMjA2MjY0NCwicGF0aCI6Ii8xNTA5ODkxNi8zMzQwMTYwMDMtMThlMDhhM2MtNjIyZi00OGVlLWJkN2MtMDQzNzIxNTA3MDVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDA2NDQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlOGNiNjFkNzU1ZjYwN2M4YjZjMjAzNGZmMTAzZTZhMjE2ZjEwYmE3ODUwOTJlZmQ0ZDM5YWU3NDVkNThlYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DlFSvKtaKpbvb9MrcWmMiIfm6-ePYBsD6X8ZPKpigqw) ![image](https://private-user-images.githubusercontent.com/15098916/334016178-c7f547fb-8074-4bb7-962a-4dbd4af2c406.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNjI5NDQsIm5iZiI6MTcyMjA2MjY0NCwicGF0aCI6Ii8xNTA5ODkxNi8zMzQwMTYxNzgtYzdmNTQ3ZmItODA3NC00YmI3LTk2MmEtNGRiZDRhZjJjNDA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDA2NDQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1N2Q3NjJkODJhODhlMDA1ZGYxZTQ0MDc5M2NlZDQ4YWY0ODIxOWJhNGVmOWVkZmQ0YjRjZWQ3YjBkZWNkNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MguO6IiUYLcDjHl_eNdI3kXX5Xv4tO6R_pcD5xpdRfs)
> 
> 阿里云的30元一次没有理解，难道说我一个oss的域名，在使用acme.sh签发和续费证书的情况下，仅仅使用脚本部署，就要为此付出每年120元以上的费用？

是阿里云自己收费服务-云部署 https://help.aliyun.com/zh/ssl-certificate/user-guide/deploy-ssl-certificates-to-alibaba-cloud-services
