### ISSUE TITLE
May you increase the DNS of dns.constellix.com?

### ISSUE THREAD

**Issue by zjlx** [acmesh-official/acme.sh#1554]
May you add the DNS of dns.constellix.com?
Thanks a lot.

Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

**Comment by reedzhao** [comment]
I also need this.

**Comment by woutd** [comment]
Support for Constellix was added last year. I think this issue can be closed.
