### ISSUE TITLE
about importing existing certs to another server

### ISSUE THREAD

**Issue by baoang** [acmesh-official/acme.sh#1572]
Will such an function be available on the roadmap?

Currently I copied the installation dir entirely to the new server after the acme.sh initial setup on the new server.

It could be great if `import` or similar varibles can be introduced.

**Comment by Neilpang** [comment]
no.
Copying the entire dir is ok.

**Comment by baoang** [comment]
Thank you, @Neilpang .

But do I have to make some relevant modifications?

Under the installation dir, there is a `ca\acme-v02.api.letsencrypt.org\account.json` file containing the server IP, id and some specific info. Do I have to change, say server IP to the new server's? Or leave it as it was?
