### ISSUE TITLE
Support Freenom (DNS)

### ISSUE THREAD

**Issue by Selenuix** [acmesh-official/acme.sh#1580]
Hello :wave: 

I just looked at the list, but you don't support [freenom](freenom.com) DNS. I hope, you will in the futur :pray: 

Thanks :pray:

**Comment by kukudemajia** [comment]
+1

**Comment by Neilpang** [comment]
Freenom doesn't support adding txt records.
So, we will never be able to support it.

**Comment by finalshrey** [comment]
@Neilpang Freenom supported adding txt revords.
