### ISSUE TITLE
多域名证书cron自动更新后只有一个域名如何更正自动更新？

### ISSUE THREAD

**Issue by huye** [acmesh-official/acme.sh#1615]
我不知道是不是之前刚安装好的时候只使用了一个域名，但后来我是用了
`acme.sh -k 4096 --issue --dns dns_dp --reloadcmd "xxxxx" -d xxx -d *.xxx -d *.m.xxx --force`
命令来更新了证书的，今天忽然发现证书不对，一看，原来证书里只有 *.xxx 这一个域名，别的都不在里面了，请问，要怎么才能使用 cron 的自动更新域名正确？

**Comment by Neilpang** [comment]
请把你的域名配置文件贴出来.  或者给更详细具体的log, 否则没法帮你.

**Comment by huye** [comment]
没有配置文件啊，我都是直接命令执行的，这个要写成配置文件吗，有没有手册什么的，我写个配置再试试

**Comment by lf-zbw** [comment]
感觉上面说的配置文件应该是_~/.acme.sh/*.xxx/*.xxx.conf_吧，不过目测你现在的情况应该是因为你更新证书时第一个`-d`是`xxx`所以acme.sh当作新证书来处理了，`acme.sh -k 4096 --issue --dns dns_dp --reloadcmd "xxxxx" -d *.xxx -d xxx -d *.m.xxx --force`或者重新`acme.sh --install-cert -d xxx ...`或许可以解决你的问题。

**Comment by huye** [comment]
好的，我先试试看，实在不行我就只有自己重新写一个定时任务了

**Comment by weituotian** [comment]
@Neilpang 怎么知道acme为你添加了哪些定时任务？

**Comment by baoang** [comment]
@weituotian 
`crontab -l`
这条命令在我机器上会显示出定时任务，其中就有acme.sh设置的定时更新的任务
`11 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null`
类似这样的。
如果是（比如）CentOS 7，它可能用的就是systemd的方式了。

**Comment by jdxia** [comment]
我也有这个问题, 请问后续怎么解决的?

**Comment by huye** [comment]
> 我也有这个问题, 请问后续怎么解决的?

我目前使用的版本没有问题，这是几年前的问题了，就算那个时候有 bug 也已经早就修复了。多半还是你的使用问题
