### ISSUE TITLE
some failing unit tests

### ISSUE THREAD

**Issue by DanielRuf** [acmesh-official/acme.sh#1744]
There are some failing unit tests which we should check and try to find solutions to get them working on CI:

https://travis-ci.org/Neilpang/acme.sh/jobs/404984117

**Comment by Neilpang** [comment]
Yes, I saw.
but it looks a problem of the letsencrypt CA.  Sometimes, it returns a "service busy, invalid nonce" error.

I will check more and report bug to letsencrypt if it's proved to be a bug.
Thanks.
