### ISSUE TITLE
Account creation only shows v01 thumbprint

### ISSUE THREAD

**Issue by Krakob** [acmesh-official/acme.sh#1799]
Unless I'm misunderstanding something, acme.sh only likes to show the v01 thumbprint. This became a problem to me when trying to issue a wildcard certificate.

**Steps to reproduce**
1. Create an account -- this gives you both a v01 and v02 account
2. The thumbprint of only the former is shown -- add to nginx config per instructions for stateless mode
3. Try to issue a wildcard certificate (stateless). You'll be challenged with the v02 thumbprint, but you have the v01 in your config.

To address this, you can copy the expected v02 thumbprint from the error log to nginx config, but that seems like poor praxis to me. I propose the account registration is made to either show the thumbprint for both accounts, or an easier way to check the thumbprints is made available.

**Comment by adrian5** [comment]
Is this still an issue as of now?

**Comment by Neilpang** [comment]
@adrian5  No, we are using v2 thumbprint now.
