### ISSUE TITLE
中文域名dns无法正确添加txt记录

### ISSUE THREAD

**Issue by Sean-Snow** [acmesh-official/acme.sh#1822]
使用dns时，无法解析中文域名

比如中文域名： xn--gtva6181b.xn--fiqs8s
在向dns服务商发送请求时，上传的域名只有xn--fiqs8s部分。
```
 url='https://alidns.aliyuncs.com/?AccessKeyId=xxx&Action=DescribeDomainRecords&DomainName=xn--fiqs8s&Format=json&SignatureMethod=HMAC-SHA1&SignatureNonce=1535644623159651843&SignatureVersion=1.0&Timestamp=2018-08-30T15%3A57%3A03Z&Version=2015-01-09&Signature=EXaqlssN9f5%2FaCPwQuTW5AIWJ4g%3D'

```
阿里云云解析api中文域名使用uri encode 编码，才能正常使用。

**Comment by TheCGDF** [comment]
cloudflare同样无法添加直接通过中文添加txt记录

**Comment by TheCGDF** [comment]
@Neilpang 为什么关闭？

**Comment by Neilpang** [comment]
请使用 punnycode

**Comment by TheCGDF** [comment]
> 请使用 punnycode

既然不支持中文域名，那为什么使用中文域名时acme.sh会提示需要安装libidn？难道不是打算内置punycode转换功能的吗？

而且直接用punycode可以是可以，但是管理非常不便诶，`/root/.acme.sh/`目录下一堆`xn--`实在无法肉眼看出哪个是哪个。

**Comment by Neilpang** [comment]
@TheCGDF   每个 dns api 的支持程度不一样.   有的支持直接用中文,  有的尚未支持, 只能用.

你可以单独报一个 bug,  后面再看
