### ISSUE TITLE
Feature request: Add --dnscaa flag support when using DNS API mode

### ISSUE THREAD

**Issue by nickjj** [acmesh-official/acme.sh#1863]
It seems like a reasonable idea to set a CAA DNS record that grants letsencrypt.org. Let's Encrypt wrote a bit about it here https://letsencrypt.org/docs/caa/

The record itself would look like this for example.com:  
`example.com. CAA 3600 issue "letsencrypt.org"`

That works for both the root domain and wildcard based sub-domains.

Maybe we could add a `--dnscaa example.com` flag for setting the domain which internally defaults to granting letsencrypt.org.

It would be kind of neat because in DNS API mode we already have the user's API credentials. Maybe it could skip / update the record if it already exists to make it more robust as well.

What do you think?

**Comment by DerDanilo** [comment]
@Neilpang
It would already be useful if acme.sh fails during DNS pre-checks when CAA Records for a certain domain are set and none of them allows "letsencrypt.org". Right now it just fails and one has to look for the root cause of this error.

Thanks!

**Comment by Neilpang** [comment]
@DerDanilo 

The error message can show the real error reason.  I think it's enough.

Our dns api can only add TXT records,  it can not add CAA records.
