### ISSUE TITLE
Domain name is redundant with a wildcard domain in the same request

### ISSUE THREAD

**Issue by ooobug** [acmesh-official/acme.sh#1880]
Have been searching for solutions for a day but still don't settle yet, so I'm here looking for your help! Thanks very much!
Here's my debug log:

[root@VM_177_16_centos ~]# acme --renew -d higherloft.com --debug 2
[Sun Oct 14 17:56:43 CST 2018] Lets find script dir.
[Sun Oct 14 17:56:43 CST 2018] _SCRIPT_='/root/.acme.sh/acme.sh'
[Sun Oct 14 17:56:43 CST 2018] _script='/root/.acme.sh/acme.sh'
[Sun Oct 14 17:56:43 CST 2018] _script_home='/root/.acme.sh'
[Sun Oct 14 17:56:43 CST 2018] Using config home:/root/.acme.sh
[Sun Oct 14 17:56:43 CST 2018] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.8.0
[Sun Oct 14 17:56:43 CST 2018] Using config home:/root/.acme.sh
[Sun Oct 14 17:56:43 CST 2018] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[Sun Oct 14 17:56:43 CST 2018] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[Sun Oct 14 17:56:43 CST 2018] DOMAIN_PATH='/root/.acme.sh/higherloft.com'
[Sun Oct 14 17:56:43 CST 2018] Renew: 'higherloft.com'
[Sun Oct 14 17:56:43 CST 2018] Le_API='https://acme-v02.api.letsencrypt.org/directory'
[Sun Oct 14 17:56:43 CST 2018] Using config home:/root/.acme.sh
[Sun Oct 14 17:56:43 CST 2018] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Sun Oct 14 17:56:43 CST 2018] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Sun Oct 14 17:56:43 CST 2018] _main_domain='higherloft.com'
[Sun Oct 14 17:56:43 CST 2018] _alt_domains='www.higherloft.com,*.higherloft.com'
[Sun Oct 14 17:56:43 CST 2018] 'dns_dp' does not contain 'dns'
[Sun Oct 14 17:56:43 CST 2018] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Sun Oct 14 17:56:43 CST 2018] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Sun Oct 14 17:56:43 CST 2018] GET
[Sun Oct 14 17:56:43 CST 2018] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun Oct 14 17:56:43 CST 2018] timeout=
[Sun Oct 14 17:56:43 CST 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.vGFVPlCJNE  -g '
[Sun Oct 14 17:56:47 CST 2018] ret='0'
[Sun Oct 14 17:56:47 CST 2018] response='{
  "iKjj_1O6I9U": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}'
[Sun Oct 14 17:56:47 CST 2018] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Sun Oct 14 17:56:47 CST 2018] ACME_NEW_AUTHZ
[Sun Oct 14 17:56:47 CST 2018] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Sun Oct 14 17:56:47 CST 2018] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Sun Oct 14 17:56:47 CST 2018] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Sun Oct 14 17:56:47 CST 2018] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Sun Oct 14 17:56:47 CST 2018] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Sun Oct 14 17:56:47 CST 2018] ACME_VERSION='2'
[Sun Oct 14 17:56:47 CST 2018] Le_NextRenewTime='1536090415'
[Sun Oct 14 17:56:47 CST 2018] _on_before_issue
[Sun Oct 14 17:56:47 CST 2018] _chk_main_domain='higherloft.com'
[Sun Oct 14 17:56:47 CST 2018] _chk_alt_domains='www.higherloft.com,*.higherloft.com'
[Sun Oct 14 17:56:47 CST 2018] 'dns_dp' does not contain 'no'
[Sun Oct 14 17:56:47 CST 2018] Le_LocalAddress
[Sun Oct 14 17:56:47 CST 2018] d='higherloft.com'
[Sun Oct 14 17:56:47 CST 2018] Check for domain='higherloft.com'
[Sun Oct 14 17:56:47 CST 2018] _currentRoot='dns_dp'
[Sun Oct 14 17:56:47 CST 2018] d='www.higherloft.com'
[Sun Oct 14 17:56:47 CST 2018] Check for domain='www.higherloft.com'
[Sun Oct 14 17:56:47 CST 2018] _currentRoot='dns_dp'
[Sun Oct 14 17:56:47 CST 2018] d='*.higherloft.com'
[Sun Oct 14 17:56:47 CST 2018] Check for domain='*.higherloft.com'
[Sun Oct 14 17:56:47 CST 2018] _currentRoot='dns_dp'
[Sun Oct 14 17:56:47 CST 2018] d
[Sun Oct 14 17:56:47 CST 2018] 'dns_dp' does not contain 'apache'
[Sun Oct 14 17:56:47 CST 2018] _saved_account_key_hash='UttvtgX+ZwrHEJkx51NRQUvhDlZ7xCBaGXtIQXQNxd8='
[Sun Oct 14 17:56:47 CST 2018] _saved_account_key_hash is not changed, skip register account.
[Sun Oct 14 17:56:47 CST 2018] Read key length:
[Sun Oct 14 17:56:47 CST 2018] _createcsr
[Sun Oct 14 17:56:47 CST 2018] domain='higherloft.com'
[Sun Oct 14 17:56:47 CST 2018] domainlist='www.higherloft.com,*.higherloft.com'
[Sun Oct 14 17:56:47 CST 2018] csrkey='/root/.acme.sh/higherloft.com/higherloft.com.key'
[Sun Oct 14 17:56:47 CST 2018] csr='/root/.acme.sh/higherloft.com/higherloft.com.csr'
[Sun Oct 14 17:56:47 CST 2018] csrconf='/root/.acme.sh/higherloft.com/higherloft.com.csr.conf'
[Sun Oct 14 17:56:47 CST 2018] _is_idn_d='www.higherloft.com,*.higherloft.com'
[Sun Oct 14 17:56:47 CST 2018] _idn_temp
[Sun Oct 14 17:56:47 CST 2018] domainlist='www.higherloft.com,*.higherloft.com'
[Sun Oct 14 17:56:47 CST 2018] Multi domain='DNS:higherloft.com,DNS:www.higherloft.com,DNS:*.higherloft.com'
[Sun Oct 14 17:56:47 CST 2018] _is_idn_d='higherloft.com'
[Sun Oct 14 17:56:47 CST 2018] _idn_temp
[Sun Oct 14 17:56:47 CST 2018] _csr_cn='higherloft.com'
[Sun Oct 14 17:56:47 CST 2018] Getting domain auth token for each domain
[Sun Oct 14 17:56:47 CST 2018] d='www.higherloft.com'
[Sun Oct 14 17:56:47 CST 2018] d='*.higherloft.com'
[Sun Oct 14 17:56:48 CST 2018] d
[Sun Oct 14 17:56:48 CST 2018] _identifiers='{"type":"dns","value":"higherloft.com"},{"type":"dns","value":"www.higherloft.com"},{"type":"dns","value":"*.higherloft.com"}'
[Sun Oct 14 17:56:48 CST 2018] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Sun Oct 14 17:56:48 CST 2018] payload='{"identifiers": [{"type":"dns","value":"higherloft.com"},{"type":"dns","value":"www.higherloft.com"},{"type":"dns","value":"*.higherloft.com"}]}'
[Sun Oct 14 17:56:48 CST 2018] RSA key
[Sun Oct 14 17:56:48 CST 2018] Get nonce. ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Sun Oct 14 17:56:48 CST 2018] HEAD
[Sun Oct 14 17:56:48 CST 2018] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Sun Oct 14 17:56:48 CST 2018] body
[Sun Oct 14 17:56:48 CST 2018] _postContentType='application/jose+json'
[Sun Oct 14 17:56:48 CST 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.eEp83jH4QP  -g '
[Sun Oct 14 17:56:56 CST 2018] _ret='0'
[Sun Oct 14 17:56:56 CST 2018] _headers='HTTP/1.1 204 No Content
Server: nginx
Replay-Nonce: wDEoGypL14-5Z__OeQ_lJ2VYYtrLsXmdwHHtDoFElEE
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Sun, 14 Oct 2018 09:56:56 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Sun, 14 Oct 2018 09:56:56 GMT
Connection: keep-alive
'
[Sun Oct 14 17:56:56 CST 2018] _CACHED_NONCE='wDEoGypL14-5Z__OeQ_lJ2VYYtrLsXmdwHHtDoFElEE'
[Sun Oct 14 17:56:56 CST 2018] nonce='wDEoGypL14-5Z__OeQ_lJ2VYYtrLsXmdwHHtDoFElEE'
[Sun Oct 14 17:56:56 CST 2018] POST
[Sun Oct 14 17:56:56 CST 2018] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Sun Oct 14 17:56:56 CST 2018] body='{"protected": "eyJub25jZSI6ICJ3REVvR3lwTDE0LTVaX19PZVFfbEoyVllZdHJMc1htZHdISHREb0ZFbEVFIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIiLCAiYWxnIjogIlJTMjU2IiwgImtpZCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hY2N0LzM3OTUxNTY4In0", "payload": "eyJpZGVudGlmaWVycyI6IFt7InR5cGUiOiJkbnMiLCJ2YWx1ZSI6ImhpZ2hlcmxvZnQuY29tIn0seyJ0eXBlIjoiZG5zIiwidmFsdWUiOiJ3d3cuaGlnaGVybG9mdC5jb20ifSx7InR5cGUiOiJkbnMiLCJ2YWx1ZSI6IiouaGlnaGVybG9mdC5jb20ifV19", "signature": "RdL1QEFQQXp49Ua_8mbnfA-6Q2C_fyDWq-NLEwqYU6A4iXUuLUHbIrRvJvesEkx_MaSRmRB8y22RqVfboMo5JiVV6DEk-IC8Vwrb2OlP1u0sU74nhK3pOT7B9ZTFgbYr1v1hoWXEFL24F42fP6ncylkXAa4DpSBz0uo7-C2mWPNJId3t2DIxV952WS5bxzs3r3d4GYzfmFPWEo3q0o8-DjacEACwyKS8SbDiAg9CynftqI3TE6OiVhAXUbdNW1BLFRaYJ3uMcIxgNPK0s4hSJ7gM4OGr289gtcxShuCc-SH9fQ1IyK1q-yGVejkjOGX6WnGc0f0GzsMvMyvjP_0GzA"}'
[Sun Oct 14 17:56:56 CST 2018] _postContentType='application/jose+json'
[Sun Oct 14 17:56:56 CST 2018] Http already initialized.
[Sun Oct 14 17:56:56 CST 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.eEp83jH4QP  -g '
[Sun Oct 14 17:57:03 CST 2018] _ret='0'
[Sun Oct 14 17:57:03 CST 2018] original='{
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Error creating new order :: Domain name \"www.higherloft.com\" is redundant with a wildcard domain in the same request. Remove one or the other from the certificate request.",
  "status": 400
}'
[Sun Oct 14 17:57:03 CST 2018] responseHeaders='HTTP/1.1 400 Bad Request
Server: nginx
Content-Type: application/problem+json
Content-Length: 258
Boulder-Requester: 37951568
Replay-Nonce: XBpuXc1ppUelypQXu5r1Nfef99-kyKu4afYMHkJvc40
Expires: Sun, 14 Oct 2018 09:57:03 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Sun, 14 Oct 2018 09:57:03 GMT
Connection: close
'
[Sun Oct 14 17:57:03 CST 2018] response='{"type":"urn:ietf:params:acme:error:malformed","detail":"Error creating new order :: Domain name \"www.higherloft.com\" is redundant with a wildcard domain in the same request. Remove one or the other from the certificate request.","status": 400}'
[Sun Oct 14 17:57:03 CST 2018] code='400'
[Sun Oct 14 17:57:03 CST 2018] Le_OrderFinalize
[Sun Oct 14 17:57:03 CST 2018] Create new order error. Le_OrderFinalize not found. {"type":"urn:ietf:params:acme:error:malformed","detail":"Error creating new order :: Domain name \"www.higherloft.com\" is redundant with a wildcard domain in the same request. Remove one or the other from the certificate request.","status": 400}
[Sun Oct 14 17:57:03 CST 2018] pid
[Sun Oct 14 17:57:03 CST 2018] No need to restore nginx, skip.
[Sun Oct 14 17:57:03 CST 2018] _clearupdns
[Sun Oct 14 17:57:03 CST 2018] skip dns.
[Sun Oct 14 17:57:03 CST 2018] _on_issue_err
[Sun Oct 14 17:57:03 CST 2018] Please add '--debug' or '--log' to check more details.
[Sun Oct 14 17:57:03 CST 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

**Comment by ooobug** [comment]
> did you really requested:
> " acme --renew -d higherloft.com --debug 2 "
> OR you requested:
> "acme --renew -d .higherloft.com -d [www.higherloft.com](http://www.higherloft.com) --debug 2 "
> As by the debug it for me looks more like the second
> And in this case if you are gettting the wildcard certificate for the domain why do you need the "www." one ?
> 
> the responseyou are getting is :
> '{"type":"urn:ietf:params:acme:error:malformed","detail":"Error creating new order :: Domain name "www.higherloft.com" is redundant with a wildcard domain in the same request. Remove one or the other from the certificate request.","status": 400}'

I tried both of them that time! But both just returned the same error. Probably the "www." one was inferred by the dns server.

**Comment by ezra-obiwale** [comment]
Had the same issue and here's how I fixed it.

As part of the log on the screen is `DOMAIN_PATH='/root/.acme.sh/higherloft.com'`, so ...

1. edit `DOMAIN_PATH=/root/.acme.sh/higherloft.com/higherloft.conf`
2. remove the explicit subdomain (e.g www.higherloft.com) from the value of `Le_Alt`
3. save file
4. run the renewal command again

**Comment by Neilpang** [comment]
@greecemunky  is right.
https://github.com/acmesh-official/acme.sh/issues/1880#issuecomment-429712927
