### ISSUE TITLE
Nginx http https forward error

### ISSUE THREAD

**Issue by infod-aa** [acmesh-official/acme.sh#1955]
Steps to reproduce
------------------
Use following nginx config: 
```
server {
    listen 80;
    listen [::]:80;
    server_name example.com www.example.com;
    return 301 https://example.com$request_uri;
}
```
When I'm renewing certs I typically use:
```acme.sh --issue --nginx --debug 2 -d example.com -d www.example.com```

```return 301``` is a problem here, because *acme.sh* is using **http** only and it's not dealing with redirection to **https** as in example above. I have to delete/comment that line each time or maybe I just have wrong assumptions.

**Comment by callac** [comment]
server {
    listen 80;
    listen [::]:80;
    server_name example.com www.example.com;
   root /var/www;
   location ~ ^/.well-known/ {

   }
   location / {
     return 301 https://example.com$request_uri;
   }
    
}

**Comment by li55626437** [comment]
> server {
> listen 80;
> listen [::]:80;
> server_name example.com [www.example.com](http://www.example.com);
> root /var/www;
> location ~ ^/.well-known/ {
> 
> }
> location / {
> return 301 https://example.com$request_uri;
> }
> 
> }

Has this been verified?

**Comment by infod-aa** [comment]
> Has this been verified?
Yes, it has been, it works fine.
