### ISSUE TITLE
Report bugs to OPNsense dns API

### ISSUE THREAD

**Issue by blablup** [acmesh-official/acme.sh#2480]
This is the place to report bugs in the OPNsense  DNS API.

If you experience a bug, please report it in this issue.

Thanks!

**Comment by wwebers** [comment]
Hi,

I experience an "invalid domain" error with the latest version of the "os-bind" plugin. However, I found they added the following part to the domain query response:

```
"masterip": "",
  "allownotifyslave": {
    "": {
      "value": "",
      "selected": 1
    }
  },
"domainname": "....",
```

as such, I added the following to the pattern matching part inside the ```dns_opnsense.sh``` script:

```
\"masterip\":\"[^\"]*\",\"allownotifyslave\":{\"\":{[^}]*}},\"domainname\":\"${h}\""
```

That way it works again.

**Comment by fraenki** [comment]
There seems to be a bug in the most recent version:
https://github.com/acmesh-official/acme.sh/issues/3735

**Comment by benyamin-codez** [comment]
> I found a few more for v25.7 per PR [#6492](https://github.com/acmesh-official/acme.sh/pull/6492)...

PR #6503 replaced #6492 and has been merged into dev...
