### ISSUE TITLE
是bug吗

### ISSUE THREAD

**Issue by junsonw** [acmesh-official/acme.sh#2540]
nginx下 如果你有两个域名 www.xxx123.com 和 www.xxx123.com.cn 当你想要获取www.xxx123.com的证书 会获取到 www.xxx123.com.cn 的证书  导致www.xxx.com:Verify error:Invalid response from http://www.xxx.com/.well-known/acme-challenge/t17yQVRgoYhstSxIq_juxocvi_8wsHsbBfp_10mwM9I [47.97.102.211]:

**Comment by Neilpang** [comment]
麻烦给debug log, 否则你让我怎么猜?

```
acme.sh
 --issue ......  --debug 2
```
