### ISSUE TITLE
Fix on INWX API

### ISSUE THREAD

**Issue by Kulturserver** [acmesh-official/acme.sh#2555]
We've encountered an error with the INWX API and found out how to fix it, here is the solution, if anybody else is stumbling on this.

Inwx seems to no longer want root zones. The file dnsapi/dns_inwx.sh has to be modified like this:

`_get_root() {
  domain=$1
  _debug "get root"
  _debug "shimmed out"

  _inwx_login

  _sub_domain=${fulldomain%%.*}
  _domain=${fulldomain#*.}
  return

  function shimmed out: INWX seems to no longer want root zones

  domain=$1
  i=2
  p=1

  _inwx_login

  xml_content='<?xml version="1.0" encoding="UTF-8"?>
  <methodCall>
  <methodName>nameserver.list</methodName>
  </methodCall>'

  response="$(_post "$xml_content" "$INWX_Api" "" "POST")"
  while true; do
    h=$(printf "%s" "$domain" | cut -d . -f $i-100)
    _debug h "$h"
    if [ -z "$h" ]; then
      #not valid
      return 1
    fi

    if _contains "$response" "$h"; then
      _sub_domain=$(printf "%s" "$domain" | cut -d . -f 1-$p)
      _domain="$h"
      return 0
    fi
    p=$i
    i=$(_math "$i" + 1)
  done
  return 1

}`

**Comment by voegelas** [comment]
We've got problems with "nameserver.list" too. Our _get_root replacement splits the full domain into the sub domain and a second-level domain. Our root zones are always second-level domains.

```
_get_root() {
  domain=$1

  _inwx_login

  # Split "_acme-challenge.www.domain.com" into " _acme-challenge.www" and
  # "domain.com".
  _sub_domain=$(echo $domain | sed -E 's/(.*)\.([^.]+\.[^.]+)$/\1/')
  _domain=$(echo $domain | sed -E 's/(.*)\.([^.]+\.[^.]+)$/\2/')
  return 0
}
```

**Comment by widder** [comment]
Thanks for posting your solutions. Neither seems to work here at my raspberry pi. :(

```
[Sun  1 Dec 11:04:09 GMT 2019] Error
[Sun  1 Dec 11:04:09 GMT 2019] Error add txt for domain:_acme-challenge.domain.de
```

**Comment by perryflynn** [comment]
I was on 2.8.0. After an update to the current 2.8.3 it works again. No manual code changes necessary.

**Comment by DerDanilo** [comment]
I still have the problem with v2.8.5. Was this supposed to be fixed already?

**Comment by Kulturserver** [comment]
It works on v2.8.4. which is the version we are using.

**Comment by DerDanilo** [comment]
Just wanted to mention that this is still an issue. When is it gonna get fixed upstream? :)

**Comment by slalabs** [comment]
Same issue. Do you have any news when the fix hit the upstream?

**Comment by spaetz** [comment]
Hey there, same issue, I tracked it down to the login silently failing. The saved "COOKIE" value is "Cookie: ", that is nothing useful. When I checked the reply on the account.login call, instead of a Cookie HTTP_HEADER, it only contained the value "HTTP/2", so it seems something changed on the INWX side and it does not return usable Auth Cookies in its headers

**Comment by sebastianas** [comment]
@spaetz does https://github.com/acmesh-official/acme.sh/pull/4764 help?
