### ISSUE TITLE
Fix OCSP stapling error when OpenSSL 1.1.0 is used

### ISSUE THREAD

**Issue by christianbur** [acmesh-official/acme.sh#2608]
With OpenSSL 1.1.1d I get the following error message when deploying haproxy with oscp.

```
[Wed Nov 27 20:05:32 CET 2019] Bundle creation requested
[Wed Nov 27 20:05:32 CET 2019] ECC key type detected
[Wed Nov 27 20:05:32 CET 2019] Deploying PEM file
[Wed Nov 27 20:05:32 CET 2019] Moving new certificate into place
[Wed Nov 27 20:05:32 CET 2019] Updating .issuer file
[Wed Nov 27 20:05:32 CET 2019] Updating OCSP stapling info
[Wed Nov 27 20:05:32 CET 2019] Extracting OCSP URL
[Wed Nov 27 20:05:32 CET 2019] Extracting OCSP URL
[Wed Nov 27 20:05:32 CET 2019] Requesting OCSP response
Missing = in header key=value
ocsp: Use -help for summary.
[Wed Nov 27 20:05:32 CET 2019] Updating OCSP stapling failed with return code 1
```
[The bug can be found here ](https://github.com/Neilpang/acme.sh/blob/ef15e55947f0df966822cdbede6a1bd572970eb6/deploy/haproxy.sh#L231) 
```
not working:
 -header Host "${_ocsp_host}" \
fix:
 -header Host="${_ocsp_host}" \
```
With openssl 1.1.x you probably need a "Host=" 

Error description in other project:
- https://github.com/h2o/h2o/issues/1267
- https://github.com/h2o/h2o/commit/cc7c6ee2a4f0e2508a37a2475cc3536c65372a27
- https://github.com/h2o/h2o/pull/1270
- https://knowledge.digicert.com/generalinformation/prepare-for-ocsp-infrastructure-upgrade.html

**Comment by walkeran** [comment]
This issue could probably be closed. It appears to have been fixed in commit e184a1b9e64f9985387cc402449f459a2b1e6649.
