### ISSUE TITLE
Include init process in docker image

### ISSUE THREAD

**Issue by seoester** [acmesh-official/acme.sh#2659]
The PID 1 process has some special responsibilities in Linux regarding the reaping of zombie processes and proper signal forwarding. Both are ignored in the current version of the docker image. For images which spawn child processes, a proper init process is recommended.

 * https://docs.docker.com/config/containers/multi-service_container/
 * https://medium.com/@nagarwal/an-init-system-inside-the-docker-container-3821ee233f4b

Nowadays docker can insert a simple init process into the container by running with `docker run --init`. But that is not supported by all orchestration engines and means the docker image is not self-contained.

I would like to see a init process included with the acme.sh container. [tini][tini] is a very small init process suitable for running in Docker containers.

It is likely that #2589 will work when a init process is included.

[tini]: https://github.com/krallin/tini
[tini-using]: https://github.com/krallin/tini#using-tini

**Comment by Neilpang** [comment]
I will check https://github.com/Neilpang/acme.sh/pull/2609 as soon as I have time.
but I don't want to add any init process to the image to keep it small.

**Comment by seoester** [comment]
`tini` is a init process only in the sense of the Linux PID 1 responsibilities. It only starts a single process (as its child) and does not manage run levels or system events. The size of the binary is 24 KiB and adds close to none maintenance and development overhead.

Without a proper PID 1 process the acme.sh image is arguably incomplete and will always face issues regarding signal forwarding and zombie processes. Please at least consider adding tini (or another minimal init process) to mitigate these issues :)

**Comment by FernandoMiguel** [comment]
@seoester i never heard of this requirement in my many years doing docker containers.
And honestly of the hundreds I've built none ever failed because not having an init.

Could you expand a bit further on this requirement?

From my pov, a container runs a single process.
Once that process finishes or dies, the Docker orchestration will remove that container. There is nothing else to clean up or zombies.

Tini and other similar things feel like adding support to run multi threaded processes in a container, which is an anti pattern.
I would obviously like to learn more, if that is not the case.

Thanks

**Comment by seoester** [comment]
Containers are powered by some intricate Linux mechanisms, although Docker has simplified usage a lot. The special requirements of the PID 1 process have been part of Linux (probably POSIX or UNIX even) practically forever. When running in a full OS these hardly matter to application developers as application processes don't run as PID 1. In a container the main process runs as PID 1 and is thus treated exactly like a PID 1 in a full OS by Linux primitives (signaling, child process inheritance).

I collected some links, I think all of these will explain PID 1 better than I could:

 * https://docs.docker.com/config/containers/multi-service_container/

   The official Docker documentation explains the reaping problematic and the `--init` flag.

 * https://medium.com/@nagarwal/an-init-system-inside-the-docker-container-3821ee233f4b

   I think this post describes the practical implications of PID 1 in Docker well.

 * https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

   Linked from the previous post. The team at Phusion implemented their own PID 1 "init" program.

 * https://vagga.readthedocs.io/en/latest/pid1mode.html

   A short document, describing the practical implications of PID 1 in Docker.

> Tini and other similar things feel like adding support to run multi threaded processes in a container, which is an anti pattern.
> I would obviously like to learn more, if that is not the case.

[Tini][] is in no way a full-fledged init system like the SysV family or systemd. tini **only** deals with the PID 1 requirements.

I would also like to distinguish between:

 * multi-threading: parallelisation primitive within a single process implemented in all common OSs.
 * multi-processing: not clearly defined, most likely refers to either an OS being able to run multiple processes concurrently or the programming technique similar to multi-threading but distributing computation within a single program across multiple OS processes.
 * child processes: launching a process from within another process and often waiting for its completion. Shells do this a lot.
 * multiple services: logical separation of concerns into services, running multiple services in a container is frowned upon.

Tini is only related to the child processes term above as it reaps zombies.

Tini fits well with the UNIX philosophy: do one thing and do it well. Instead of every developer implementing PID 1 mechanisms in their own application (which is really only required when running within a Docker container)

As a rule of thumb: If the main process in your container launches another program you should probably ensure that the PID 1 requirements are fulfilled. Also if you encounter problems with signalling (docker stop / docker kill). Use tini instead of implementing it yourself.
Personally I think tini should be included in the image (instead of relying on `--init`) so that it is self-contained and simpler to use.

[tini]: https://github.com/krallin/tini

**Comment by seoester** [comment]
I believe tini should be in the acme.sh image as:

 * acme.sh is a shell script launching many other programs as child processes
 * The `daemon` entrypoint runs cron which then spawns acme.sh (a further child process in the hierarchy)
 * There has already been one documented issue I encountered (probably) solved by a proper PID 1. https://github.com/Neilpang/acme.sh/pull/2589#issuecomment-554373956 This issue in particular limits observability of the container and thus is of high interest to me as an operator.
 * tini would increase the size of the image by less than 0.05 %

**Comment by Neilpang** [comment]
@seoester 
I think acme.sh is working in a single-process manner.

our entry point script  is the PID1 process,  it handles the Signals, for graceful exit.
`crond` is just the only child process.

If PID1 process can exit gracefully, the docker engine will kill/cleanup the child process.

I don't think we need to import extra unnecessary complexity. It's not only about the image size,  but also about the complexity.

**Comment by seoester** [comment]
> I think acme.sh is working in a single-process manner.

When running `daemon` there are 3 - 5 processes running within the container: entry.sh, crond, sleep, acme.sh and the command issued by acme.sh.

> I don't think we need to import extra unnecessary complexity. It's not only about the image size, but also about the complexity.

I would argue that net complexity is lowered by including tini. Adding tini is simple and alleviates the need to implement "process management" (signal forwarding) for crond.
tini is widely used and stable enough to be shipped with your docker installation.

I've added tini and fixed #2589 here: https://github.com/Neilpang/acme.sh/compare/master...seoester:docker-tini-pid1

Aside from `daemon`, there is another problem:

> If PID1 process can exit gracefully, the docker engine will kill/cleanup the child process.

Docker SIGKILLs all processes on PID 1 exit. That is worrisome as these processes are responsible for requesting, receiving and deploying certificates. Clean shutdown avoids file corruptions.

**Comment by Neilpang** [comment]
we don't need init process any more.  see: https://github.com/acmesh-official/acme.sh/issues/992

we used the `cronie` instead of the default cron.  It can handle the signals now.
