### ISSUE TITLE
Issuing SSL cert for two domains that are on different DNS providers(DigitalOcean and CloudFlare)

### ISSUE THREAD

**Issue by PH4NTOMiki** [acmesh-official/acme.sh#2672]
Is it possible to issue SSL certificate for two domains(as a Subject Alternative Name and both should be wildcard), using DNS auth but one's DNS provider is DigitalOcean and the other's is CloudFlare. Is that possible, for now I'm doing it the manual way(put TXT DNS records myself for both domains)

**Comment by GustavGenberg** [comment]
You could probably use dns alias mode:

https://github.com/Neilpang/acme.sh/wiki/DNS-alias-mode

**Comment by Neilpang** [comment]
>> one's DNS provider is DigitalOcean and the other's is CloudFlare

Yes,  we support different dns provider for each domain.



```
acme.sh --issue  -d  aaaa.com  --dns  dns_aaa.sh \
       -d  bbb.com   --dns  dns_bbb
       -d  ccc.com    --dns  dns_ccc

```

**Comment by PH4NTOMiki** [comment]
Thank you @Neilpang that is great but I already my own solution in Node.JS(that interacts both with your acme.sh script and also with DigitalOceans' and CloudFlare's API) but anyway I think yours is much more convenient, so I'm going to use it, but this was a great learning experience for me so I don't mind, also I'm planning to make script(in Node) for one DNS provider that I use that doesn't have an API but I'll try to use HTML parsing to make and delete TXT records.
