### ISSUE TITLE
TLS-ALPN Nginx does not report the Real IP of requests

### ISSUE THREAD

**Issue by anojht** [acmesh-official/acme.sh#2673]
Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```
Hello I followed your guide on using TLS-ALPN in Nginx with Zero Downtime.
However, due to the way this is done my access logs for all proxy requests contain localhost instead of the real IP address of requests.

I've tried the following inside the stream and server directives for your configuration and none seem to produce the real IP of request. Can someone point me in the right direction to getting this resolved?

```
set_real_ip_from 127.0.0.1;
```

**Comment by fdefilippo** [comment]
to get the real ip acme.sh should first support the proxy protocol then configure nginx to use the proxy protocol and configure it accordingly.

**Comment by anojht** [comment]
Thanks this works for me.
