### ISSUE TITLE
Docker deploy mode not compatible with ecc certs

### ISSUE THREAD

**Issue by XIAZY** [acmesh-official/acme.sh#2677]
Steps to reproduce
------------------
- Issue an ECC certificate, let's say for example.com
- Use `--deploy` to deploy to docker

`acme.sh --deploy` does not take `-d example.com` (directory not found). It takes `-d example.com_ecc`, however it cannot find the actual certs in that subdirectory, because of the actual cert files are stored as `example.com.key` and so on, instead of `example.com_ecc.key`

Debug log
-----------------
root@ams:~# acme.sh --deploy --deploy-hook docker -d example.com_ecc --debug 2
[Mon Jan  6 12:46:31 EST 2020] Lets find script dir.
[Mon Jan  6 12:46:31 EST 2020] _SCRIPT_='/home/xia/.acme.sh/acme.sh'
[Mon Jan  6 12:46:31 EST 2020] _script='/home/xia/.acme.sh/acme.sh'
[Mon Jan  6 12:46:31 EST 2020] _script_home='/home/xia/.acme.sh'
[Mon Jan  6 12:46:31 EST 2020] Using default home:/home/xia/.acme.sh
[Mon Jan  6 12:46:31 EST 2020] Using config home:/home/xia/.acme.sh
[Mon Jan  6 12:46:31 EST 2020] LE_WORKING_DIR='/home/xia/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.8.4
[Mon Jan  6 12:46:31 EST 2020] Running cmd: deploy
[Mon Jan  6 12:46:31 EST 2020] Using config home:/home/xia/.acme.sh
[Mon Jan  6 12:46:31 EST 2020] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mon Jan  6 12:46:31 EST 2020] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Mon Jan  6 12:46:31 EST 2020] DOMAIN_PATH='/home/xia/.acme.sh/example.com_ecc'
[Mon Jan  6 12:46:31 EST 2020] _deployApi='/home/xia/.acme.sh/deploy/docker.sh'
[Mon Jan  6 12:46:31 EST 2020] _cdomain='example.com_ecc'
[Mon Jan  6 12:46:31 EST 2020] DEPLOY_DOCKER_CONTAINER_LABEL='sh.acme.autoload.domain=example.com'
[Mon Jan  6 12:46:32 EST 2020] Using docker command
[Mon Jan  6 12:46:32 EST 2020] DEPLOY_DOCKER_CONTAINER_KEY_FILE='/etc/nginx/ssl/example.com/key.pem'
[Mon Jan  6 12:46:32 EST 2020] DEPLOY_DOCKER_CONTAINER_CERT_FILE='/etc/nginx/ssl/example.com/cert.pem'
[Mon Jan  6 12:46:32 EST 2020] DEPLOY_DOCKER_CONTAINER_CA_FILE='/etc/nginx/ssl/example.com/ca.pem'
[Mon Jan  6 12:46:32 EST 2020] DEPLOY_DOCKER_CONTAINER_FULLCHAIN_FILE='/etc/nginx/ssl/example.com/full.pem'
[Mon Jan  6 12:46:32 EST 2020] DEPLOY_DOCKER_CONTAINER_RELOAD_CMD='service nginx force-reload'
[Mon Jan  6 12:46:32 EST 2020] Container id: 9bcab7f777ef
[Mon Jan  6 12:46:32 EST 2020] Copying file from /home/xia/.acme.sh/example.com_ecc/example.com_ecc.key to /etc/nginx/ssl/example.com/key.pem
[Mon Jan  6 12:46:32 EST 2020] _dir='/etc/nginx/ssl/example.com'
[Mon Jan  6 12:46:32 EST 2020] _docker_exec 9bcab7f777ef mkdir -p /etc/nginx/ssl/example.com
/home/xia/.acme.sh/deploy/docker.sh: line 205: /home/xia/.acme.sh/example.com_ecc/example.com_ecc.key: No such file or directory
[Mon Jan  6 12:46:33 EST 2020] Error
[Mon Jan  6 12:46:33 EST 2020] Error deploy for domain:example.com_ecc
[Mon Jan  6 12:46:33 EST 2020] Deploy error.

```
acme.sh  --issue .....   --debug 2
```

**Comment by Neilpang** [comment]
```
 acme.sh --deploy --deploy-hook docker -d example.com   --ecc
```
