### ISSUE TITLE
Using --toPkcs without password still prompts for password

### ISSUE THREAD

**Issue by patricf** [acmesh-official/acme.sh#2681]
Hi,

When using `--toPkcs ` without a password you are still prompted for a password.
This prompt is coming from OpenSSL and the only way I managed to get rid of it was to add `-passout pass:` at the end of line 1317 to look like this:

`${ACME_OPENSSL_BIN:-openssl} pkcs12 -export -out "$_cpfx" -inkey "$_ckey" -in "$_ccert" -certfile "$_cca" -passout pass:`

instead of this:

`${ACME_OPENSSL_BIN:-openssl} pkcs12 -export -out "$_cpfx" -inkey "$_ckey" -in "$_ccert" -certfile "$_cca"`

Not really sure if this is the way to go or if there is a better way?
However, a fix for this would be great since I changed this a while back and when I upgraded acme.sh couple of weeks ago all my other scripts stopped working since the .pfx-files never got created.

**Comment by Neilpang** [comment]
so you want a pfx file without a password ?
It was designed to require a password to protect the pfx file.

let me know your use case, please.

Thanks.

**Comment by patricf** [comment]
I just thought that the `--password` flag was optional so that's why I was confused.
My use case is just for some internal stuff that are not that important so that's why I decided to skip the password to make it easier to script. I could fix this for my scripts to support password of course if using no password is not a legit way of using it.

**Comment by Neilpang** [comment]
please be careful that:  the toPkcs  command  will not be called automatically when the cert is renewed.
