### ISSUE TITLE
Make an Ubuntu package or publish up-to-date PPA repo

### ISSUE THREAD

**Issue by wkoszek** [acmesh-official/acme.sh#2686]
# Feature request: Ubuntu package

After fresh AWS install I just want to do:

```
apt install acme.sh
```

Not having acme.sh in Ubuntu package repository complicates my Ansible playbooks. Separate PPA would be OK too. Additional argument: acme.sh package could depend on `socat` which would smoothen installation even more.

How much work would it be to add a script to release new versions of acme.sh to the PPA repository?

**Comment by FernandoMiguel** [comment]
Install is a simple curl.
Is that not OK?

**Comment by Qvinticom** [comment]
https://github.com/Neilpang/get.acme.sh/issues/3#issuecomment-282712759

**Comment by wkoszek** [comment]
@Qvinticom Yeah, this is one example. And all sorts of stuff like this. With Ansible 

 @FernandoMiguel The `curl` is a little bit of a ... workaround. For everything I have all software packages installed through the official Ubuntu mechanism in scripts/automation, and then I have to do some hacks to be able to pull `acme.sh` correctly. It works, but it's not very convenient.

Ubuntu doesn't seem to have a decent Acme client right now, and having acme.sh in a packages would make it win over other competitors.

**Comment by Neilpang** [comment]
I remember there is someone packaged acme.sh for ubuntu PPA,  please search for it.

However,  acme.sh was born to live without root. That means any non-privileged user can install and use acme.sh on the machine.   It's more flexible.
