### ISSUE TITLE
Excuse me, config file is empty, can not save UPGRADE_HASH = ,How to solve

### ISSUE THREAD

**Issue by oyanli** [acmesh-official/acme.sh#2693]
Excuse me, config file is empty, can not save UPGRADE_HASH = How to solve

AWS server,
System debian9
Use wget -qO- get.acme.sh | bash, this prompt appears in the command, how can I solve it, thank you

**Comment by oyanli** [comment]
Use wget -O-https://get.acme.sh | sh command is also this prompt

**Comment by Neilpang** [comment]
please try again, it should be fixed now.

**Comment by oyanli** [comment]
Is ready to use, thank you for your work
