### ISSUE TITLE
DNSAPI for ISPConfig not working correctly

### ISSUE THREAD

**Issue by SchachtnerTh** [acmesh-official/acme.sh#2705]
When trying to automatically renew certificates for our domains using a shell script, we encounter a problem that we cannot update the DNS TXT records on our ISPConfig server anymore.

After some testing, I found out, that the dns_ispconfig.sh script mixes up the values for the user id ($sys_userid) and the client id ($client_id).
For a long time, those two values used to be identical, so everything worked fine.
But now, we changed the responsible user for a domain and from that time on, updating the certifiaces failed.

Here are the modifications I made to the script and how I got the scripts working again:

    113,115c113,115
    <     client_id=$(echo "${curResult}" | _egrep_o "sys_userid.*" | cut -d ':' -f 2 | cut -d '"' -f 2)
    <     _debug "Client ID: '${client_id}'"
    <     case "${client_id}" in
    ---
    >     sys_userid=$(echo "${curResult}" | _egrep_o "sys_userid.*" | cut -d ':' -f 2 | cut -d '"' -f 2)
    >     _debug "SYS User ID: '${sys_userid}'"
    >     case "${sys_userid}" in
    117c117
    <         _err "Client ID is not numeric."
    ---
    >         _err "User ID is not numeric."
    120c120
    <       *) _info "Retrieved Client ID." ;;
    ---
    >       *) _info "Retrieved SYS User ID." ;;
    124a125,137
    >   # Need to also get client_id as it is different from sys_userid
    >     curData="{\"session_id\":\"${sessionID}\",\"sys_userid\":\"${sys_userid}\"}"
    >     curResult="$(_post "${curData}" "${ISPC_Api}?client_get_id")"
    >     client_id=$(echo "${curResult}" | _egrep_o "response.*" | cut -d ':' -f 2 | cut -d '"' -f 2 | tr -d '{}')
    >     _debug "Client ID: '${client_id}'"
    >     case "${client_id}" in
    >       '' | *[!0-9]*)
    >       _err "Client ID is not numeric."
    >       return 1
    >       ;;
    >       *) _info "Retrieved Client ID." ;;
    >     esac
    >
 
Best regards,
Thomas

**Comment by Neilpang** [comment]
Please send a PR, or give me your code.

Thanks.

**Comment by SchachtnerTh** [comment]
Hi,
I already uploaded it to guthub.

Best regards,
Thomas

Am 28. Januar 2020 01:50:53 MEZ schrieb neil <notifications@github.com>:
>Please send a PR, or give me your code.
>
>Thanks.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Neilpang/acme.sh/issues/2705#issuecomment-579027742

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by ouzo12** [comment]
This works perfectly... thanks for the fix.
But i can't see it as a pull request.

**Comment by republicus** [comment]
This problem still exists

**Comment by republicus** [comment]
@SchachtnerTh can you tell me how to apply these changes? I tried to do it manually but I believe I've placed the last section improperly since I'm still getting the same _Client ID is not numeric_ error.

**Comment by Karting06** [comment]
@republicus I had the same problem as you after manually applying these changes. 
Did you give the remote user the `Client functions`? That solved the problem for me (it's needed to request the Client ID).

**Comment by pssara** [comment]
ideed this code is not commited in the trunk

**Comment by SchachtnerTh** [comment]
Is it ok me too do that? 

Am 9. Januar 2021 09:20:19 MEZ schrieb pssara <notifications@github.com>:

**Comment by pssara** [comment]
I created a pull request https://github.com/acmesh-official/acme.sh/pull/3365 but for the DNS tes to pass it requires access to an ISP config server from github. I dont have one available over the internet.

**Comment by SchachtnerTh** [comment]
If that's the only issue, I can perform the DNS test on my side, but i don't know how to create a pull request nor what that is exactly 🙈
Any hint from your side and i'd learn about git and the change will be distributed (though i thought it would be already)

Best
Tom
