### ISSUE TITLE
While renew in ALPN mode with tlsport option there is error 'tcp port 443 is already used by'

### ISSUE THREAD

**Issue by den-ru-github-user** [acmesh-official/acme.sh#2714]
Hello!
I'm renewing certificate on the host that uses HAproxy reverse proxy with the cron command:
`
"/root/.acme.sh"/acme.sh --renew-all --alpn --tlsport 90 \
--home "/root/.acme.sh" --post-hook "create_cert.sh xxxxxx" \
--reloadcmd "/etc/rc.d/rc.haproxy restart"
`

The mode used is standalone server ALPN and the designated port for tls check is set to tcp\90. The HAproxy config allows to produce cert renew request on the port of the localhost:

...
frontend http_only
        ...
        # Let's Encrypt interaction check
        acl letsencrypt-acl path_beg /.well-known/acme-challenge/
        use_backend letsencrypt if letsencrypt-acl
        ...
frontend https_1
        ...
        acl letsencrypt-acl path_beg /.well-known/acme-challenge/
        use_backend letsencrypt if letsencrypt-acl
        ...
backend letsencrypt
        server LE_local 127.0.0.1:90

No applications are run over localhost:90 at the time of execution. While executing the command I got the error with debug messages in log:

[Mon Feb  3 10:26:16 MSK 2020] _currentRoot='alpn'
[Mon Feb  3 10:26:16 MSK 2020] Standalone alpn mode.
[Mon Feb  3 10:26:16 MSK 2020] _checkport='443'
[Mon Feb  3 10:26:16 MSK 2020] _checkaddr
[Mon Feb  3 10:26:16 MSK 2020] Using: ss
[Mon Feb  3 10:26:16 MSK 2020] LISTEN     0      128    ****:443                      *:*                   users:(("haproxy",pid=17352,fd=6))
[Mon Feb  3 10:26:16 MSK 2020] tcp port 443 is already used by (("haproxy",pid=17352,fd=6))
[Mon Feb  3 10:26:16 MSK 2020] Please stop it first
[Mon Feb  3 10:26:16 MSK 2020] _on_before_issue.
[Mon Feb  3 10:26:16 MSK 2020] Return code: 1
[Mon Feb  3 10:26:16 MSK 2020] Error renew *********.
[Mon Feb  3 10:26:16 MSK 2020] _error_level='1'
[Mon Feb  3 10:26:16 MSK 2020] _set_level='2'

So, it seems like acme.sh does not try to test designated tlsport, instead it tests common tcp\443, that is in production use.

Versions of software in use:
OS Slackware 14.2 x86, 
acme.sh v2.8.3
haproxy v.1.8.13

reproducible - everytime,

I can renew the certs with the above command only after stopping HAproxy and releasing tcp\443
By the way, the --pre-hook option set to "/etc/rc.d/rc.haproxy stop" added to the above command had no effect (may be some delay is needed?)

Thank you
Den

**Comment by Neilpang** [comment]
`--pre-hook` is only valid for `--issue` command.

https://github.com/acmesh-official/acme.sh/wiki/Using-'--pre-hook',-'--post-hook',-'--renew-hook'-and-'--reload-cmd'

please use `--issue` with `--pre-hook` again.

Otherwise,  you can try webroot mode or dns mode.
