### ISSUE TITLE
OpenWRT, Pre-hook not invoked unless in .conf

### ISSUE THREAD

**Issue by Linwood-F** [acmesh-official/acme.sh#2716]
Steps to reproduce
------------------

Running on OpenWRT 18.06 Kernel 4.14.131, I worked through the issue fine, but had crontab set up for renewal and it was not working.  I had the command at the bottom of:

[Wiki page here](https://github.com/acmesh-official/acme.sh/wiki/How-to-run-on-OpenWRT)

I ran it with debug (and =2) and finally convinced myself (after leaving out the post hook) that the hooks were not running.  I dug deeper into the files, and found that in the 

    domain.conf

file these were present (or more precisely, they had empty strings): 

    Le_PreHook=''
    Le_PostHook=''
    Le_RenewHook=''
    Le_Keylength=''

So on a whim I moved the commands in the above page into these strings and removed from the crontab job, and... it worked.

It seems as though these were saved from somewhere, something, and the crontab parameters not honored, which seems inconsistent with the page on configuring for OpenWRT.  I'm not sure if I ran it incorrectly originally (so these were not saved) or if the recommendation is just out of date? 

The result of course is a connection refused since the firewall rules normally block the outside access.

Works fine with the commands in above (though I found I needed both 80 and 443 with the redirect that page recommends).

**Comment by Neilpang** [comment]
@Linwood-F  
Sorry,   the wiki page was created by some other one.  
I didn't notice it was wrong.

Never never remove/edit the default cronjob entry, unless you know what you are doing.

The hooks are only valid for `--issue` command.

https://github.com/acmesh-official/acme.sh/wiki/Using-'--pre-hook',-'--post-hook',-'--renew-hook'-and-'--reload-cmd'

Which means, you should specify the hooks when you issue the cert.   
acme.sh can remember what you are doing. 

Once the cert is about to renew in future, acme.sh can re-do that to make sure what you are doing now can be done successfully then.

**Comment by Linwood-F** [comment]
Yeah, I think what happened is I had it right, then broke it in the firewall ages ago, fixed that and got it to renew (manually?  I don't recall) but THOUGHT I needed to change the cronjob.  Anyway... if it doesn't just work next time will wipe and redo from the beginning.

Thanks for the pointer.
