### ISSUE TITLE
TLS DEPRECATED! URGENT!

### ISSUE THREAD

**Issue by sergiomendonca** [acmesh-official/acme.sh#2718]
The connection used to load resources from https://aaaaa.tk:used TLS 1.0 or TLS 1.1, which are deprecated and will be disabled in the future. Once disabled, users will be prevented from loading these resources. The server should enable TLS 1.2 or later. See https://www.chromestatus.com/feature/5654791610957824 for more information.

See the image in console from chrome:

![image](https://user-images.githubusercontent.com/34236548/73963052-542ef000-48ee-11ea-82e4-e02dffe22ecf.png)

**Comment by sergiomendonca** [comment]
![captura](https://user-images.githubusercontent.com/34236548/73963025-44afa700-48ee-11ea-90a8-011091f92ed8.png)

**Comment by tristanbes** [comment]
This sholud be handled in your web server configuration; Not sur this issues is relevant to this repository.

**Comment by Neilpang** [comment]
it's your webserver configuration.
