### ISSUE TITLE
Bad guidelines for custom DNS API development

### ISSUE THREAD

**Issue by OItsMAK** [acmesh-official/acme.sh#2720]
I recently made a custom DNS API for a DNS provider, and I found two things that should be changed in the [DNS API Dev Guide](https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Dev-Guide) in my opinion. One is an error and the other is a pointer that should be added:

1. While the [dnsapi - Use custom API](https://github.com/acmesh-official/acme.sh/wiki/dnsapi#use-custom-api) states correctly that for an API named `myapi` the script file should be named `dns_myapi.sh`, The [DNS API Dev Guide](https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Dev-Guide#2-the-script-file-name-must-be-myapish) wrongly states that the file should be named `myapi.sh`.

2. As a habit, I put the statement `set -eu` at the beginning of my script (You can check their meanings [here](https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/)). This doesn't work with `acme.sh` as it tries to expand unbound variables and fails; And should be pointed out in the DNS API Dev Guide:
```Bash
[Time] Getting webroot for domain='[...]'
/root/.acme.sh/acme.sh: line 236: LOG_FILE: unbound variable
[Time] Please add '--debug' or '--log' to check more details.
[Timez] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
```

**Comment by Neilpang** [comment]
for the doc typo,  thanks.

we don't use `set -e`, because we will check the return code of each command.

we don't use `set -u` either,  we need undefined variables.

Thanks.

**Comment by ToJIka4** [comment]
The line about shell file name is still actual
