### ISSUE TITLE
Move to another system after crash

### ISSUE THREAD

**Issue by pnelsonsr** [acmesh-official/acme.sh#2739]
What is the recommended process to renew certs when the old system HD crashed and I need to start a new?  Is that what I do, reissue rather than renew?

**Comment by pnelsonsr** [comment]
This is so that I can create a contingency plan.

**Comment by FernandoMiguel** [comment]
@pnelsonsr issue a new cert

**Comment by Neilpang** [comment]
yes,  re-issue a new one.
