### ISSUE TITLE
Renew is asking for sudo password

### ISSUE THREAD

**Issue by nylocx** [acmesh-official/acme.sh#2752]
Hi, I have a strange problem with the reload command.

I have a sudoers.d config that allows to reload apache without a password as my user.

So `sudo /usr/bin/systemctl reload httpd` is not asking for a password if I executed as my "unprivileged" user.

But if I run, as my "unprivileged" user:
`acme.sh -r -d my.domain.tld --force`
I get the output:
> ...
> [Di 25. Feb 09:08:21 CET 2020] Run reload cmd: sudo systemctl reload httpd
> [sudo] Passwort für my-user-name:
> ...

and it is waiting for me to enter my password. I guess this will be a problem once the cronjob tries to renew the certificates.

```
Feb 25 09:08:30 host sudo[40957]:     my-user-name : TTY=pts/2 ; PWD=/home/my-user-name/.acme.sh/my.domain.tld ; USER=root ; COMMAND=/usr/bin/systemctl reload httpd
Feb 25 09:08:30 host sudo[40957]: pam_unix(sudo:session): session opened for user root by alex(uid=0)
Feb 25 09:08:30 host sudo[40957]: pam_unix(sudo:session): session closed for user root

Feb 25 09:08:58 host sudo[41183]:     my-user-name : TTY=pts/2 ; PWD=/home/alex ; USER=root ; COMMAND=/usr/bin/systemctl reload httpd
Feb 25 09:08:58 host sudo[41183]: pam_unix(sudo:session): session opened for user root by alex(uid=0)
Feb 25 09:08:58 host sudo[41183]: pam_unix(sudo:session): session closed for user root
```

The first is what my journal logs have for the acme.sh sudo that asks for a password. The second one is for the direct execution of the reload command that does NOT ask for a password.

Anyone with an idea what might go wrong here?

**Comment by Neilpang** [comment]
yes,  this will be a problem.
Nobody in the cronjob will input your password for you.

The solution is to not use `sudo`.
https://github.com/acmesh-official/acme.sh/wiki/sudo

You can configure a specified command to run by sudo without password.
Search google for that.

**Comment by nylocx** [comment]
Hi Neilpang,
Thanks for you reply, but I'm not sure I get this right.
To clarify, I do not run acme.sh with sudo, I run as an unprivileged user.
I already have a sudo rule to be able to run `/usr/bin/systemctl reload httpd` without entering a password that works fine from the shell. The corresponding line form my `/etc/sudoers.d/acme` file is:
`my-user-name ALL=NOPASSWD: /usr/bin/systemctl reload httpd.service`
This works when `systemctl reload httpd.service` run for a normal shell without any problems.

But if that command is run as part of `acme.sh -r -d my.domain.tld --force` as the same user in the same shell I get the password prompt as you can see at my first post.

I really have no idea what the script is doing to completely ignore the NOPASSWD part of my sudo config. I hope this clarifies it a bit more if you need any more debug output or information about the system please let me know.

**Comment by nylocx** [comment]
Ok, I'm sorry, but thanks for being my rubber duck... Sometimes the ones that are able to read have a clear advantage...
I allowed the systemctl reload httpd**.service** without a password but my reload command was running systemctl reload httpd, which is semantically equivalent, but sudo does not care about semantics if the syntax does not match ;).

So sorry again for the noise and thanks for trying to help.
