### ISSUE TITLE
--renew -hook parameters

### ISSUE THREAD

**Issue by chenxiccc** [acmesh-official/acme.sh#2755]
I wish to scp the certs to other servers after updating the certs . So I put the commands in a shell file ' scp.sh'
Then I install certs with --renew -hook like this:
`~/.acme.sh/acme.sh --installcert -d domain.com -d '*.domain.com' --fullchain-file /etc/ssl/cert.crt --key-file /etc/ssl/cert.key --renew-hook /root/.acme.sh/scp.sh`

Question 1:
Do I use the right grammar? or quote the parameters like : --renew-hook "/root/.acme.sh/scp.sh" ?

Question 2:
How can I ensure the renew hook is working? Maybe like 'acme.sh --renew -hook status'?

**Comment by Neilpang** [comment]
>> Question 1:

Yes

>> Question 2:

https://github.com/acmesh-official/acme.sh/wiki/Using-'--pre-hook',-'--post-hook',-'--renew-hook'-and-'--reload-cmd'


You can check the domain conf file: `~/.acme.sh/domain.com/domain.com.conf`
