### ISSUE TITLE
Let's encrypt certificate recovation

### ISSUE THREAD

**Issue by cb2206** [acmesh-official/acme.sh#2774]
Hi,
is there an easy way to check if my acme.sh instance renewed certificates during the timeframe the bug in Let's encrypt existed?
https://thehackernews.com/2020/03/lets-encrypt-certificate-revocation.html

Thanks

**Comment by FernandoMiguel** [comment]
@cb2206 just renew as you normally would.
if it has a cron setup, it probably already replaced it.
if not, you can force renew.

**Comment by FernandoMiguel** [comment]
the affected certs can be found at
https://letsencrypt.org/caaproblem/

**Comment by cb2206** [comment]
Thanks!
