### ISSUE TITLE
INWX: Error removing TXT records using --cron

### ISSUE THREAD

**Issue by Geestbiker** [acmesh-official/acme.sh#2778]
I encountered an issue when renewing my certs with mobile TAN enabled. Renewing the certs is succesfull though, but the TXT records are not removed. The username, password and shared secret is stored within /home/user/.acme.sh/account.conf. I assume this to be correcet because renewing certs finally is succesfull.

The command used was `acme.sh --cron`
The `acme.sh --version` output is `v2.8.6`

Here is an excerpt from the log:

[Sa 7. Mär 23:57:08 CET 2020] Removing DNS records.
[Sa 7. Mär 23:57:08 CET 2020] d='my.domain'
[Sa 7. Mär 23:57:08 CET 2020] txtdomain='_acme-challenge.my.domain'
[Sa 7. Mär 23:57:08 CET 2020] aliasDomain='_acme-challenge.my.domain'
[Sa 7. Mär 23:57:08 CET 2020] _currentRoot='dns_inwx'
[Sa 7. Mär 23:57:08 CET 2020] txt='Ov9rmoADfmqk_pDwy3er4o9qaRoU2STmSvEMPWdRHMg'
[Sa 7. Mär 23:57:08 CET 2020] d_api='/home/user/.acme.sh/dnsapi/dns_inwx.sh'
[Sa 7. Mär 23:57:08 CET 2020] Removing txt: Ov9rmoADfmqk_pDwy3er4o9qaRoU2STmSvEMPWdRHMg for domain: _acme-challenge.my.domain
[Sa 7. Mär 23:57:08 CET 2020] First detect the root zone
[Sa 7. Mär 23:57:08 CET 2020] get root
[Sa 7. Mär 23:57:08 CET 2020] POST
[Sa 7. Mär 23:57:08 CET 2020] _post_url='https://api.domrobot.com/xmlrpc/'
[Sa 7. Mär 23:57:08 CET 2020] _CURL='curl -L --silent --dump-header /home/user/.acme.sh/http.header  -g '
[Sa 7. Mär 23:57:09 CET 2020] _ret='0'
[Sa 7. Mär 23:57:09 CET 2020] Mobile TAN detected.
[Sa 7. Mär 23:57:09 CET 2020] Please define a shared secret.
[Sa 7. Mär 23:57:09 CET 2020] POST
[Sa 7. Mär 23:57:09 CET 2020] _post_url='https://api.domrobot.com/xmlrpc/'
[Sa 7. Mär 23:57:09 CET 2020] _CURL='curl -L --silent --dump-header /home/user/.acme.sh/http.header  -g '
[Sa 7. Mär 23:57:09 CET 2020] _ret='0'
[Sa 7. Mär 23:57:09 CET 2020] h='my.domain'
[Sa 7. Mär 23:57:09 CET 2020] h='de'
[Sa 7. Mär 23:57:09 CET 2020] _sub_domain='_acme-challenge.my.domain'
[Sa 7. Mär 23:57:09 CET 2020] _domain='de'
[Sa 7. Mär 23:57:09 CET 2020] Getting txt records
[Sa 7. Mär 23:57:09 CET 2020] POST
[Sa 7. Mär 23:57:09 CET 2020] _post_url='https://api.domrobot.com/xmlrpc/'
[Sa 7. Mär 23:57:09 CET 2020] _CURL='curl -L --silent --dump-header /home/user/.acme.sh/http.header  -g '
[Sa 7. Mär 23:57:09 CET 2020] _ret='0'
[Sa 7. Mär 23:57:09 CET 2020] Error could not get txt records
[Sa 7. Mär 23:57:09 CET 2020] Error removing txt for domain:_acme-challenge.my.domain
[Sa 7. Mär 23:57:09 CET 2020] Verify finished, start to sign.
[Sa 7. Mär 23:57:09 CET 2020] i='2'
[Sa 7. Mär 23:57:09 CET 2020] j='26'
[Sa 7. Mär 23:57:09 CET 2020] Lets finalize the order, Le_OrderFinalize: https://acme-v02.api.letsencrypt.org/acme/finalize/59591535/2572988182
[Sa 7. Mär 23:57:09 CET 2020] url='https://acme-v02.api.letsencrypt.org/acme/finalize/59591535/2572988182'
[Sa 7. Mär 23:57:09 CET 2020] payload='{"csr": "xxxxxxxxxxxxxxxxxxxxxxxxxx"}'
[Sa 7. Mär 23:57:09 CET 2020] POST
[Sa 7. Mär 23:57:09 CET 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/finalize/59591535/2572988182'
[Sa 7. Mär 23:57:09 CET 2020] _CURL='curl -L --silent --dump-header /home/user/.acme.sh/http.header  -g '
[Sa 7. Mär 23:57:10 CET 2020] _ret='0'
[Sa 7. Mär 23:57:10 CET 2020] code='200'
[Sa 7. Mär 23:57:10 CET 2020] Order status is valid.
[Sa 7. Mär 23:57:10 CET 2020] Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/035df60268350ba7a578b8ae6a1ca319cf74'
[Sa 7. Mär 23:57:10 CET 2020] Download cert, Le_LinkCert: https://acme-v02.api.letsencrypt.org/acme/cert/035df60268350ba7a578b8ae6a1ca319cf74
[Sa 7. Mär 23:57:10 CET 2020] url='https://acme-v02.api.letsencrypt.org/acme/cert/035df60268350ba7a578b8ae6a1ca319cf74'
[Sa 7. Mär 23:57:10 CET 2020] payload
[Sa 7. Mär 23:57:11 CET 2020] POST
[Sa 7. Mär 23:57:11 CET 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/cert/035df60268350ba7a578b8ae6a1ca319cf74'
[Sa 7. Mär 23:57:11 CET 2020] _CURL='curl -L --silent --dump-header /home/user/.acme.sh/http.header  -g '
[Sa 7. Mär 23:57:11 CET 2020] _ret='0'
[Sa 7. Mär 23:57:11 CET 2020] code='200'
[Sa 7. Mär 23:57:11 CET 2020] Found cert chain
[Sa 7. Mär 23:57:11 CET 2020] _end_n='37'
[Sa 7. Mär 23:57:11 CET 2020] Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/035df60268350ba7a578b8ae6a1ca319cf74'
[Sa 7. Mär 23:57:12 CET 2020] Cert success.

**Comment by Neilpang** [comment]
please upgrade to the `dev` branch, and try again.

```sh
acme.sh --upgrade -b dev
```

Thanks.

**Comment by Geestbiker** [comment]
After upgrading to the dev branch I noticed that `--cron` did a downgrade to the stable branch, though issuing new certs and removing TXT records was successfull.

`acme.sh --upgrade -b dev`
`acme.sh --cron --force`

Also, upgrading to dev branch and force-renew certificats was successfull without any errors.

`acme.sh --upgrade -b dev`
`acme.sh --renew-all --force`

Log attached.

[acme.sh.log](https://github.com/acmesh-official/acme.sh/files/4303276/acme.sh.log)

**Comment by Neilpang** [comment]
don't worry,  the dev code will be merged to master soon.
