### ISSUE TITLE
如何同时使用CloudFlare和DNSPod的两个域名？

### ISSUE THREAD

**Issue by crazynet999** [acmesh-official/acme.sh#2791]
已经使用DNSPod域名证书 b.com *.b.com成功，

想再次添加CloudFlare下的域名(a.com)获取证书，使得a.com 和b.com 都通过acme.sh获取证书，

操作：

在account.conf下添加相关的api_key等，但是运行acme.sh --issue --dns dns_dp -d a.com -d *.a.com不成功，

问题：应该如何操作不同域名提供商，如CloudFlare和DNSPod，同时申请成功？

**Comment by HanadaLee** [comment]
acme.sh --issue --dns dns_cf -d a.com -d *.a.com

**Comment by Neilpang** [comment]
```
acme.sh --issue  -d a.com       --dns  dns_dp      \
                           -d '*.a.com'   --dns  dns_dp      \
                           -d b.com       --dns  dns_cf       \
                           -d '*.b.com'   --dns  dns_cf
```
