### ISSUE TITLE
Add ARUBA DNS Api 

### ISSUE THREAD

**Issue by JTrotta** [acmesh-official/acme.sh#2805]
Hello, I created and tested ARUBA Api dns shell file.
How to merge it to acme.sh? 
Do I need to fork and PR the project? Is it possible to  use some other way?
It's useless to fork the whole project to change just a shell file.
Thank you

**Comment by Neilpang** [comment]
>> Do I need to fork and PR the project? 

yes

**Comment by JTrotta** [comment]
Done
