### ISSUE TITLE
Add native notification support for Microsoft Teams

### ISSUE THREAD

**Issue by ccommisso** [acmesh-official/acme.sh#2809]
With [Microsoft Teams becoming one of most popular](https://www.theverge.com/2019/7/11/20689143/microsoft-teams-active-daily-users-stats-slack-competition) (if not the most popular) enterprise messaging app it would be nice if there was a way to configure notifications to MS Teams in a native fashion (similar to the way you can already do with Slack).

Im sure there is a way to get Acme.sh to send notification to MS Teams using IFTTT but it would be nice if the functionally was provided out of the box.

**Comment by Neilpang** [comment]
I never used Microsoft Teams.
Can you please show me the dev doc ?  That will save a lot of me time.

**Comment by ccommisso** [comment]
[Main Webhook page](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/what-are-webhooks-and-connectors)

I assume you would nee to create an [incoming connector](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook)

More [detailed technical info](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using)

If you are not using MS Teams I would be happy to validate this for you or help out any way I can.

**Comment by Neilpang** [comment]
I never registered/used Microsoft Teams.

please do everything you can to help save time.

**Comment by melkypie** [comment]
This should be closed as #2872 has been merged for a while now.
