### ISSUE TITLE
Permission denied errors when using from within a bash script

### ISSUE THREAD

**Issue by randohinn** [acmesh-official/acme.sh#2813]
I'm trying to automate some housekeeping stuff on my server in a bash script, including setup of new certificates using acme.

When running this acme command 
`home/rando/.acme.sh/acme.sh --issue --nginx -d example.com -d www.example.com`

in the command line, everything works fine.

However, using this in a bash script file, like so:

`eval "home/rando/.acme.sh/acme.sh --issue --nginx -d example.com -d www.example.com"` gives back multiple permission denied messages and eventually fails due to not having permission for nginx open /run/nginx.pid..

What could I do to have this automation work?

**Comment by randohinn** [comment]
@Neilpang Any ideas I could look into here :) ?

**Comment by Neilpang** [comment]
check your current user. it must be root
