### ISSUE TITLE
Re-install after renew clarification

### ISSUE THREAD

**Issue by vmsh0** [acmesh-official/acme.sh#2820]
Hello,

When acme.sh renews a certificate, via `--renew` or via `--cron`, does it also repeat the related `--install-cert` command which was originally issued for the certificate?

If it does, I think it ought to be documented better.

BR,
\- Riccardo

**Comment by Neilpang** [comment]
yes

read the main readme file carefully.

**Comment by vmsh0** [comment]
Hello,

I see now that it is documented under one of the examples in the README.md file.

Just FYI, I don't think that's a very good place to put that piece of information. I spent ~30 minutes reading around and I didn't find it! Either the Wiki or the `-h` output of the script would be much better.

Just my two cents.

Thanks for the awesome project!
\- Riccardo

**Comment by Neilpang** [comment]
@vmsh0 
sorry for the trouble.
the wiki repo is publicly editable,  you can edit it.
