### ISSUE TITLE
mailto: not compliant to RFC6068 when creating an new account

### ISSUE THREAD

**Issue by olibu** [acmesh-official/acme.sh#2828]
Steps to reproduce
------------------
Just install with an account name
```
./acme.sh --install --accountemail "name.surename@mydomain.com"
```
When issuing a certificate by
```
./acme.sh --issue --standalone -d myservertest.mydomain.com --use-wget --debug 3
```
An account will be generated initially with the contact "mailto:<space>name.surename@mydomain.com".

This is not compliant to RFC6068. Which is defined in the RFC8555 as contact section.

Currently this is not an issue with Let's encrypt, but with other ACME providers which are more strict in the RFC.

Debug log
-----------------

```
[Wed Apr  1 17:39:51 UTC 2020] original='{
  "key": {
    "kty": "RSA",
    "n": "...",
    "e": "AQAB"
  },
  "contact": [
    "mailto: name.surename@mydomain.com"
  ],
  "initialIp": "x.x.x.x",
  "createdAt": "2020-04-01T17:39:50.954976126Z",
  "status": "valid"
}'
```

**Comment by Neilpang** [comment]
the PR is mergered.
