### ISSUE TITLE
2.8.5 Bug：DNSPOD.CN无法更新 & 原因

### ISSUE THREAD

**Issue by tayadwx** [acmesh-official/acme.sh#2829]
由于dnspod.cn不知道什么时候采用汉字转码的Unicode来作为返回信息（至少我这里是这样）
"message":"\u64cd\u4f5c\u5df2\u7ecf\u6210\u529f\u5b8c\u6210"
转成中文：
"message":"操作已经成功完成"

而dns_dp.sh中_get_root()、add_record()、dns_dp_rm()这几个函数采用的是判断response是否包含字符串”Action completed successful”来判断操作成功与否

所以在get_root这一步会报错导致脚本不能继续进行下去。

debug部分：

[Thu Apr  2 01:29:19 CST 2020] First detect the root zone
domain is: _acme-challenge.domain.cn
h is: domain.cn
[Thu Apr  2 01:29:19 CST 2020] Domain.Info
[Thu Apr  2 01:29:19 CST 2020] url='https://dnsapi.cn/Domain.Info'
[Thu Apr  2 01:29:19 CST 2020] data='login_token=000000,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&format=json&domain=domain.cn'
[Thu Apr  2 01:29:19 CST 2020] POST
[Thu Apr  2 01:29:19 CST 2020] _post_url='https://dnsapi.cn/Domain.Info'
[Thu Apr  2 01:29:19 CST 2020] body='login_token=000000,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&format=json&domain=domain.cn'
[Thu Apr  2 01:29:19 CST 2020] _postContentType
[Thu Apr  2 01:29:19 CST 2020] Http already initialized.
[Thu Apr  2 01:29:19 CST 2020] _CURL='curl -L --silent --dump-header /path/acme.sh/http.header  --trace-ascii /tmp/tmp.QpVOeBJLM2  -g '
[Thu Apr  2 01:29:19 CST 2020] _ret='0'
[Thu Apr  2 01:29:19 CST 2020] response='{"status":{"code":"1","message":"\u64cd\u4f5c\u5df2\u7ecf\u6210\u529f\u5b8c\u6210","created_at":"2020-04-02 01:29:23"},……………………}'
h is:cn
[Thu Apr  2 01:29:19 CST 2020] Domain.Info
[Thu Apr  2 01:29:19 CST 2020] url='https://dnsapi.cn/Domain.Info'
[Thu Apr  2 01:29:19 CST 2020] data='login_token=000000,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&format=json&domain=cn'
[Thu Apr  2 01:29:20 CST 2020] POST
[Thu Apr  2 01:29:20 CST 2020] _post_url='https://dnsapi.cn/Domain.Info'
[Thu Apr  2 01:29:20 CST 2020] body='login_token=000000,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&format=json&domain=cn'
[Thu Apr  2 01:29:20 CST 2020] _postContentType
[Thu Apr  2 01:29:20 CST 2020] Http already initialized.
[Thu Apr  2 01:29:20 CST 2020] _CURL='curl -L --silent --dump-header /path/acme.sh/http.header  --trace-ascii /tmp/tmp.QpVOeBJLM2  -g '
[Thu Apr  2 01:29:20 CST 2020] _ret='0'
[Thu Apr  2 01:29:20 CST 2020] response='{"status":{"code":"8","message":"\u57df\u540d\u4e0d\u6b63\u786e\uff0c\u8bf7\u8f93\u5165\u4e3b\u57df\u540d\uff0c\u5982 dnspod.cn","created_at":"2020-04-02 01:29:24"}}'
h is:
[Thu Apr  2 01:29:20 CST 2020] invalid domain

Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

**Comment by buxuku** [comment]
YES, the same question!

**Comment by Neilpang** [comment]
把bug 之前能不能先更新到最新版试试.
没有看到提示吗.

**Comment by stilleshan** [comment]
> 把bug 之前能不能先更新到最新版试试.
> 没有看到提示吗.

大佬,docker版本好久没更新了,是要在容器内手动更新么?
