### ISSUE TITLE
Typo in mail.sh - no subject in sendmail | ssmtp

### ISSUE THREAD

**Issue by brackenhill-mob** [acmesh-official/acme.sh#2837]
acme.sh v 2.8.6
mail.sh line 127 is missing an underscore. Should read
echo "Subject: $_subject"

I've just switched to ssmtp from mailgun and was wondering why I stopped getting a subject in my emails!

Also please can you support msmtp? ssmtp is no longer supported and is a massive security hole with clear text passwords - msmtp supports encryption.

**Comment by honzahommer** [comment]
It's possible to send me a source code / headers of incoming mail?

**Comment by honzahommer** [comment]
> acme.sh v 2.8.6
> mail.sh line 127 is missing an underscore. Should read
> echo "Subject: $_subject"

I've just tested notification via ssmtp and subject was set correctly. As you can see, referenced variable `$subject` is base64 encoded string .

https://github.com/acmesh-official/acme.sh/blob/dbf659c57584c4623fb0a23cbac2a9ea6925fa8c/notify/mail.sh#L64

Please send me received e-mail headers.

**Comment by honzahommer** [comment]
> Also please can you support msmtp? ssmtp is no longer supported and is a massive security hole with clear text passwords - msmtp supports encryption.

@Neilpang msmtp command added in PR https://github.com/acmesh-official/acme.sh/pull/2779.

**Comment by brackenhill-mob** [comment]
I was beta testing a new email client and it turns out they had a bug which didn't display base64 subjects. Just reverted to the original source and looked at it in Gmail and the subject is there so everything good.

Issue closed accordingly.
