### ISSUE TITLE
After acme.sh is updated and upgraded, the timing task of the original version and timing verification need to be changed

### ISSUE THREAD

**Issue by dmz-leon** [acmesh-official/acme.sh#2862]
acme.sh更新升级后，原来版本的定时任务，定时验证是否还有需要改动的地方？
After acme.sh is updated and upgraded, the timing task of the original version and timing verification need to be changed？

**Comment by dmz-leon** [comment]
> If this is a bug report, please upgrade to the latest code and try again:
> 如果有 bug, 请先更新到最新版试试:
> `sh acme.sh --upgrade `
> please also provide the log with `--debug 2`.
> see: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh

之前一直是用的是v1的版本，现在acme.sh升级到了v2，之前的配置是否也需要改动？比如cpoy/安装证书的动作

**Comment by Neilpang** [comment]
不需要. 所有配置都是兼容的.  acme.sh 会自动处理.

**Comment by dmz-leon** [comment]
> 不需要. 所有配置都是兼容的. acme.sh 会自动处理.

v1版本是把生成的证书安装到nginx配置文件下了，定时任务每60天会自动更新，现在升级版本了，需要生成证书，copy到nginx配置下的操作都会正常，是这个样子吗？

**Comment by Neilpang** [comment]
不需要
