### ISSUE TITLE
定时任务问题

### ISSUE THREAD

**Issue by dmz-leon** [acmesh-official/acme.sh#2875]
![微信图片_20200420111947](https://user-images.githubusercontent.com/50727710/79710885-e8f39800-82f8-11ea-8ce8-79b0b0e15f73.png)

更新证书的定时任务会将key-file和fullchain-file加载进去并且重载nginx吗？现在我想在这条定时任务加上重载nginx的命令

**Comment by Neilpang** [comment]
不要修改默认生成的任务.

https://github.com/acmesh-official/acme.sh/wiki/%E8%AF%B4%E6%98%8E
