### ISSUE TITLE
Unable to revoke cert with account key

### ISSUE THREAD

**Issue by mtis88** [acmesh-official/acme.sh#2880]
I am unable to revoke a cert (`acme.sh --revoke -d <domain>`) that was issued with `acme.sh --signcsr --csr csr.csr --dns dns_cf`. The cert makes use of SAN.

I get error:
`{
  "type": "urn:ietf:params:acme:error:unauthorized",
  "detail": "JWK embedded in revocation request must be the same public key as the cert to be revoked",
  "status": 403
}`.

A quick Google [suggests:](https://community.letsencrypt.org/t/revocation-behaviour/53223/2)

> If you want to revoke using the account key, you need to follow the “kid” style of signing rather than the “jwk” style of signing.

Is this a bug, new feature request or am I doing something wrong? I am using 2.8.6.

[Debug.log](https://github.com/acmesh-official/acme.sh/files/4518203/Debug.log)

**Update 23/04/20:**
Interestingly I have had success issuing and revoking a cert with the same CSR using the BuyPass CA (https://api.test4.buypass.no/acme/directory). So who is not conforming to spec here, acme.sh, Let's Encrypt or BuyPass?

**Comment by Neilpang** [comment]
please upgrade to the latest code 
```
acme.sh  --upgrade  -b  dev
```

**Comment by mtis88** [comment]
@Neilpang All working - thank you!
