### ISSUE TITLE
Issue with OCSP must staple

### ISSUE THREAD

**Issue by SoLoR1** [acmesh-official/acme.sh#2883]
I have bug to report. My certificates are initially created without OCSP must staple (this is also default anyway), however once they are renewed they get this specific bit, not sure if this is acme-sh client bug or maybe letsencrypts...

config for ecc cert:
```
Le_Domain='domain.net'
Le_Alt='*.domain.net,*.movies.domain.net'
Le_Webroot='dns_nsupdate'
Le_PreHook=''
Le_PostHook=''
Le_RenewHook=''
Le_ReloadCmd='__ACME_BASE64__START___ACME_BASE64__END_'
Le_ChallengeAlias='acme-challenge.domain.net,'

Le_Keylength='ec-256'
Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/xxxxxxx/xxxxxxx'
Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/xxxxxxxxxx'
Le_CertCreateTime='1583250737'
Le_CertCreateTimeStr='Tue  3 Mar 15:52:17 UTC 2020'
Le_NextRenewTimeStr='Sun 17 May 15:52:17 UTC 2020'
Le_NextRenewTime='1589644337'
Le_RealCertPath=''
Le_RealCACertPath=''
Le_RealKeyPath=''
Le_RealFullChainPath=''
Le_OCSP_Staple='0'
Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/xxxxxxx/xxxxx'
Le_DNSSleep='120'
Le_RenewalDays='75'
```

You can see there is Le_OCSP_Staple='0', that suppose to control must staple option.

And this is from ssllabs after renew (before renew that option is not supported as it should be)
![image](https://user-images.githubusercontent.com/3218757/80246426-ad482d80-866c-11ea-8b64-65cad2129efd.png)

Using latest git version all the time and geting log is kinda an issue since i guess log should be from cron job that runs every 75+ days on renew....

**Comment by SoLoR1** [comment]
Issue must be somewhere in the following:

```
  if [ "$Le_OCSP_Staple" ] || [ "$Le_OCSP_Stable" ]; then
    _savedomainconf Le_OCSP_Staple "$Le_OCSP_Staple"
    _cleardomainconf Le_OCSP_Stable
    printf -- "\nbasicConstraints = CA:FALSE\n1.3.6.1.5.5.7.1.24=DER:30:03:02:01:05" >>"$csrconf"
  fi
```

This gets added in to csrconf on renew, when it shouldnt since Le_OCSP_Staple is 0.

**Comment by SoLoR1** [comment]
OK my last post... it gets set in haproxy.sh

```
  # Update .ocsp file if certificate was requested with --ocsp/--ocsp-must-staple option
  if [ -z "${Le_OCSP_Staple}" ]; then
    Le_OCSP_Staple="0"
  fi
```

So solution is to removing it from haproxy.sh or check in acme.sh if its explicitly set to 1.

**Comment by Neilpang** [comment]
sorry, it's fixed.
please try again with dev branch.

```sh
acme.sh  --upgrade -b dev
```

**Comment by SoLoR1** [comment]
Seems to work, on a my backup domain. I created new cert and then force renewed it. Also other thing i noticed is i guess creating of .conf file got changed in last 3-4 months, because by default there are slightly less "default" variables and this includes lack of Le_OCSP_Staple=0, with this new .conf even original script would work fine, but this change doesnt hurt anyway and its sanity check anyway....

```
Le_Domain='domain.si.eu.org'
Le_Alt='no'
Le_Webroot='dns_nsupdate'
Le_PreHook=''
Le_PostHook=''
Le_RenewHook=''
Le_ChallengeAlias='acme-challenge.domain.net,'
Le_Keylength='ec-256'
Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/xxxxxxx/xxxxxxx'
Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/xxxxxx/xxxxxx'
Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/xxxxxxxxx'
Le_CertCreateTime='1587827522'
Le_CertCreateTimeStr='Sat 25 Apr 15:12:02 UTC 2020'
Le_RenewalDays='75'
Le_NextRenewTimeStr='Thu  9 Jul 15:12:02 UTC 2020'
Le_NextRenewTime='1594221122
```'

Anyway thanks for fix! Gonna recreate my certs from scratch next friday when my "ban" for main domain expires :)
