### ISSUE TITLE
Add Hetzner DNS API

### ISSUE THREAD

**Issue by Scrumplex** [acmesh-official/acme.sh#2893]
This is a feature request to implement the [Hetzner.com DNS](https://dns.hetzner.com/) API.

# Documentation

- [General Information](https://wiki.hetzner.de/index.php/Kategorie:DNS_Console)
- [API Docs](https://dns.hetzner.com/api-docs/)

**Comment by Scrumplex** [comment]
I will look if I can implement this myself.

**Comment by svenmasuhr** [comment]
Released a first usable draft here:

https://github.com/svenmasuhr/hetzner-acme.sh 

I'll create a PR when it's completely polished. :)

**Comment by xhess** [comment]
I also wrote a usable draft two days ago and just stumbled over your proposal. Nice work.
Here is my [gist](https://gist.github.com/xhess/7059f00cd71ce33c3e9a3d85497a22fc), but I think your is better, since I use _jq_ for parsing the json.

**Comment by Scrumplex** [comment]
Apart from using any of the scripts above, there also is [lexicon](https://github.com/AnalogJ/lexicon), which gained hetzner support recently. See https://github.com/acmesh-official/acme.sh/wiki/How-to-use-lexicon-DNS-API

**Comment by gassan** [comment]
a version based on dns_cf.sh was merged to dev branch  #2942

**Comment by REDLINK** [comment]
> Apart from using any of the scripts above, there also is [lexicon](https://github.com/AnalogJ/lexicon), which gained hetzner support recently. See https://github.com/acmesh-official/acme.sh/wiki/How-to-use-lexicon-DNS-API

Isn't a main point of acme.sh that you don't have to deal with Python and its dependencies? 🙄

**Comment by Scrumplex** [comment]
> Isn't a main point of acme.sh that you don't have to deal with Python and its dependencies? roll_eyes

No idea what the *point* of a FOSS project is or should be. I thought hat lexicon works pretty well for this use case.
