### ISSUE TITLE
Cloudflare doesn't support setting DNS record for domains with .cf, .ga, .gq, .ml, or .tk TLD with api.Cloudflare已经不支持通过API设置.cf, .ga, .gq, .ml, 或.tk域名的DNS记录.

### ISSUE THREAD

**Issue by RealXuChe** [acmesh-official/acme.sh#2901]
cloudflare 现在已经不支持通过API设置.cf, .ga, .gq, .ml, 或.tk域名的DNS记录
在`acme.sh`设置TXT记录时会出错.
debug信息:
```
[Sun May  3 08:08:00 UTC 2020] response='{
  "error": "You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard."
}'
[Sun May  3 08:08:00 UTC 2020] Add txt record error.
[Sun May  3 08:08:00 UTC 2020] Error add txt for domain:_acme-challenge.xxxxxxxx.tk
```
cloudflare community的相关讨论:https://community.cloudflare.com/t/unable-to-update-ddns-using-api-for-some-tlds/167228

**Comment by wzc0x0** [comment]
.ml域名，目前报这个错误
`response='{"success":false,"errors":[{"code":9109,"message":"Unauthorized to access requested resource"}],"messages":[],"result":null}'
[2020年 05月 06日 星期三 05:29:36 UTC] invalid domain
[2020年 05月 06日 星期三 05:29:36 UTC] Error add txt for domain:_acme-challenge.cankiss.ml`

**Comment by RealXuChe** [comment]
我找到了一个workaround,可以使用DNS别名模式验证,具体可以看[wiki](https://github.com/acmesh-official/acme.sh/wiki/DNS-alias-mode).亲测有效.

**Comment by wzc0x0** [comment]
没看明白

**Comment by Neilpang** [comment]
cloudflare 禁止了这些免费域名.

**Comment by KyleJKC** [comment]
怪不得我的.cf提示
```
[Sat May 16 18:44:24 CST 2020] Add txt record error.
[Sat May 16 18:44:24 CST 2020] Error add txt for domain:_acme-challenge.kylej.cf
[Sat May 16 18:44:24 CST 2020] Please add '--debug' or '--log' to check more details.
[Sat May 16 18:44:24 CST 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
```

**Comment by dotNetDR** [comment]
https://github.com/acmesh-official/acme.sh/wiki/dns-manual-mode

利用手动方式，可以生效～～～

```
/.acme.sh/acme.sh --issue --dns -d your.domain --yes-I-know-dns-manual-mode-enough-go-ahead-please --force --debug
# 去cf上手动加txt记录

# 加完再跑这条。
/.acme.sh/acme.sh --renew -d your.domain \
  --yes-I-know-dns-manual-mode-enough-go-ahead-please \
  --force --debug
```

**Comment by Wsget** [comment]
I think so.

acme.sh --issue --dns dns_cf -d aced.ga -d '*.aced.ga' --keylength ec-384 --key-file       /etc/nginx/ssl/privkey.pem  --fullchain-file /etc/nginx/ssl/fullchain.pem --cert-file /etc/nginx/ssl/chain.pem --reloadcmd     "systemctl reload nginx.service"
[Tue 02 Jun 2020 10:09:06 PM KST] Multi domain='DNS:aced.ga,DNS:*.aced.ga'
[Tue 02 Jun 2020 10:09:06 PM KST] Getting domain auth token for each domain
[Tue 02 Jun 2020 10:09:08 PM KST] Getting webroot for domain='aced.ga'
[Tue 02 Jun 2020 10:09:08 PM KST] Getting webroot for domain='*.aced.ga'
[Tue 02 Jun 2020 10:09:08 PM KST] Adding txt value: LhfxWJpGkZ1PfzHz_c5TdZuCSMoGafwznoRJdPxHVG0 for domain:  _acme-challenge.aced.ga
[Tue 02 Jun 2020 10:09:08 PM KST] Adding record
[Tue 02 Jun 2020 10:09:08 PM KST] Add txt record error.
[Tue 02 Jun 2020 10:09:08 PM KST] Error add txt for domain:_acme-challenge.aced.ga
[Tue 02 Jun 2020 10:09:09 PM KST] Please check log file for more details: /root/.acme.sh/acme.sh.log

**Comment by HkXArm** [comment]
> https://github.com/acmesh-official/acme.sh/wiki/dns-manual-mode
> 
> 利用手动方式，可以生效～～～
> 
> ```
> /.acme.sh/acme.sh --issue --dns -d your.domain --yes-I-know-dns-manual-mode-enough-go-ahead-please --force --debug
> # 去cf上手动加txt记录
> 
> # 加完再跑这条。
> /.acme.sh/acme.sh --renew -d your.domain \
>   --yes-I-know-dns-manual-mode-enough-go-ahead-please \
>   --force --debug
> ```

It works! Thank you!

**Comment by tangyue1** [comment]
I could not get it to work. Here is the log:

[Sat 20 Jun 15:06:57 BST 2020] POST
[Sat 20 Jun 15:06:57 BST 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/5365101673'
[Sat 20 Jun 15:06:57 BST 2020] _CURL='curl -L --silent --dump-header /home/acme/.acme.sh/http.header  -g '
[Sat 20 Jun 15:06:58 BST 2020] _ret='0'
[Sat 20 Jun 15:06:58 BST 2020] code='200'
[Sat 20 Jun 15:06:58 BST 2020] d='tXXXXXXX.ml'
[Sat 20 Jun 15:06:58 BST 2020] Getting webroot for domain='tXXXXXXX.ml'
[Sat 20 Jun 15:06:58 BST 2020] _w='dns'
[Sat 20 Jun 15:06:58 BST 2020] _currentRoot='dns'
[Sat 20 Jun 15:06:58 BST 2020] entry='"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/5365101673/Zz16Xw","token":"3JErs4R9R-gMkcQ8FEWuFf5_VmDxxxxxxxxD8BRoc"'
[Sat 20 Jun 15:06:58 BST 2020] token='3JErs4R9R-gMkcQ8FEWuFf5_VmDazyYoDxxxxxxxxxD8BRoc'
[Sat 20 Jun 15:06:58 BST 2020] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/5365101673/Zz16Xw'
[Sat 20 Jun 15:06:58 BST 2020] keyauthorization='3JErs4R9R-gMkcQ8FEWuFf5_VmDazyYoDlGoFD8BRoc.LeG6nlCrrDKKX_wxxxxxxxCXvAMgKtfk'
[Sat 20 Jun 15:06:58 BST 2020] dvlist='tXXXXXXX.ml#3JErs4R9R-gMkcQ8FEWuFf5_VmDazyYoDlGoFD8BRoc.LeG6nlCrrxxxxxxxxlgCXvAMgKtfk#https://acme-v02.api.letsencrypt.org/acme/chall-v3/5365101673/Zz16Xw#dns-01#dns'
[Sat 20 Jun 15:06:58 BST 2020] d
[Sat 20 Jun 15:06:58 BST 2020] vlist='tXXXXXXX.ml#3JErs4R9R-gMkcQ8FEWuFf5_VmDazyYoDlGoFD8BRoc.LeG6nlxxxxxxxkGTufmA6SlgCXvAMgKtfk#https://acme-v02.api.letsencrypt.org/acme/chall-v3/5365101673/Zz16Xw#dns-01#dns,'
[Sat 20 Jun 15:06:58 BST 2020] d='tXXXXXXX.ml'
[Sat 20 Jun 15:06:59 BST 2020] _d_alias
[Sat 20 Jun 15:06:59 BST 2020] txtdomain='_acme-challenge.tXXXXXXX.ml'
[Sat 20 Jun 15:06:59 BST 2020] txt='Ut7BTa_rSFrIEcxxxxxx0Ec7hDZKM0x6q8t04'
[Sat 20 Jun 15:06:59 BST 2020] d_api
[Sat 20 Jun 15:06:59 BST 2020] Add the following TXT record:
[Sat 20 Jun 15:06:59 BST 2020] Domain: '_acme-challenge.tXXXXXXX.ml'
[Sat 20 Jun 15:06:59 BST 2020] TXT value: 'Ut7BTa_rSFrIEcgxxxxxxxxhDZKM0x6q8t04'
[Sat 20 Jun 15:06:59 BST 2020] Please be aware that you prepend _acme-challenge. before your domain
[Sat 20 Jun 15:06:59 BST 2020] so the resulting subdomain will be: _acme-challenge.tXXXXXXX.ml
[Sat 20 Jun 15:06:59 BST 2020] Dns record not added yet, so, save to /home/acme/.acme.sh/tXXXXXXX.ml/tXXXXXXX.ml.conf and exit.
[Sat 20 Jun 15:06:59 BST 2020] Please add the TXT records to the domains, and re-run with --renew.
[Sat 20 Jun 15:06:59 BST 2020] _on_issue_err
[Sat 20 Jun 15:06:59 BST 2020] Please add '--debug' or '--log' to check more details.
[Sat 20 Jun 15:06:59 BST 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh





> https://github.com/acmesh-official/acme.sh/wiki/dns-manual-mode
> 
> 利用手动方式，可以生效～～～
> 
> ```
> /.acme.sh/acme.sh --issue --dns -d your.domain --yes-I-know-dns-manual-mode-enough-go-ahead-please --force --debug
> # 去cf上手动加txt记录
> 
> # 加完再跑这条。
> /.acme.sh/acme.sh --renew -d your.domain \
>   --yes-I-know-dns-manual-mode-enough-go-ahead-please \
>   --force --debug
> ```

**Comment by tangyue1** [comment]
请问手动怎么加？谢谢。

> https://github.com/acmesh-official/acme.sh/wiki/dns-manual-mode
> 
> 利用手动方式，可以生效～～～
> 
> ```
> /.acme.sh/acme.sh --issue --dns -d your.domain --yes-I-know-dns-manual-mode-enough-go-ahead-please --force --debug
> # 去cf上手动加txt记录
> 
> # 加完再跑这条。
> /.acme.sh/acme.sh --renew -d your.domain \
>   --yes-I-know-dns-manual-mode-enough-go-ahead-please \
>   --force --debug
> ```

**Comment by wzc0x0** [comment]
换成http://he.net/

**Comment by PHCSJC** [comment]
> 换成http://he.net/

he不支持tk域名了

**Comment by showgood163** [comment]
> https://github.com/acmesh-official/acme.sh/wiki/dns-manual-mode
> 
> 利用手动方式，可以生效～～～
> 
> ```
> /.acme.sh/acme.sh --issue --dns -d your.domain --yes-I-know-dns-manual-mode-enough-go-ahead-please --force --debug
> # 去cf上手动加txt记录
> 
> # 加完再跑这条。
> /.acme.sh/acme.sh --renew -d your.domain \
>   --yes-I-know-dns-manual-mode-enough-go-ahead-please \
>   --force --debug
> ```

Do I need to manually do the updating everytime?

**Comment by MAGICCC** [comment]
Yes, maybe read the wiki page?
Also stop hijacking old issues

**Comment by woosungchoi** [comment]
@showgood163 Yes. But you can use another DNS company.

LuaDNS support freenom domains.

www.luadns.com

https://www.wsgvet.com/home/640

**Comment by Leetroch** [comment]
> /.acme.sh/acme.sh --renew -d your.domain \
>   --yes-I-know-dns-manual-mode-enough-go-ahead-please \
>   --force --debug



> https://github.com/acmesh-official/acme.sh/wiki/dns-manual-mode
> 
> 利用手动方式，可以生效～～～
> 
> ```
> /.acme.sh/acme.sh --issue --dns -d your.domain --yes-I-know-dns-manual-mode-enough-go-ahead-please --force --debug
> # 去cf上手动加txt记录
> 
> # 加完再跑这条。
> /.acme.sh/acme.sh --renew -d your.domain \
>   --yes-I-know-dns-manual-mode-enough-go-ahead-please \
>   --force --debug
> ```

2022年我用这种方式失败了，只好买域名了。还是Error add txt for domain:_acme-challenge。
