### ISSUE TITLE
Additional external dependencies (JSON parsing)

### ISSUE THREAD

**Issue by aleho** [acmesh-official/acme.sh#2902]
Hi!

I'd like to implement (and subsequently pull-request) a new DNS API provider.

Unfortunately the JSON-REST API cannot reliably be parsed without actually parsing the JSON (grepping JSON is not the most stable solution anyway).

In my CLI projects I've come to use [`jq`](https://stedolan.github.io/jq/) as a reliable, fast and very potent tool to handle JSON data.

Do you have any plans to allow additional external tools as dependencies for DNS providers?

**Comment by zdenek-biberle** [comment]
Honestly? I think that `jq` should be mandatory for any of the DNS API providers that work with JSON (which, I suspect, is going to be quite a lof of them).

I took a quick glance at some of them and the amount of string manipulation without proper encoding & decoding is, frankly, horrifying.
