### ISSUE TITLE
feature request:wildcard verify without use DoH

### ISSUE THREAD

**Issue by joey741019** [acmesh-official/acme.sh#2904]
There no other option to do wildcard domain verify without use DoH
In some of environment the firewall block all DoH request, it'll cause verify failed.
It's any other way to verify wildcard domain without use DoH?

> _ns_lookup() {
>   if [ -z "$DOH_USE" ]; then
>     _debug "Detect dns server first."
>     if _ns_is_available_cf; then
>       _debug "Use cloudflare doh server"
>       export DOH_USE=$DOH_CLOUDFLARE
>     else
>       _debug "Use google doh server"
>       export DOH_USE=$DOH_GOOGLE
>     fi
>   fi
> 
>   if [ "$DOH_USE" = "$DOH_CLOUDFLARE" ] || [ -z "$DOH_USE" ]; then
>     _ns_lookup_cf "$@"
>   else
>     _ns_lookup_google "$@"
>   fi
> 
> }

```
[Mon May  4 14:01:48 CST 2020] Detect dns server first.
[Mon May  4 14:01:48 CST 2020] GET
[Mon May  4 14:01:48 CST 2020] url='https://cloudflare-dns.com'
[Mon May  4 14:01:48 CST 2020] timeout=
[Mon May  4 14:01:48 CST 2020] Http already initialized.
[Mon May  4 14:01:48 CST 2020] _CURL='curl -L --silent --dump-header /tmp/acme/wildcard_HIDDEN.DOMAIN//http.header  -g '
[Mon May  4 14:01:48 CST 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 35
[Mon May  4 14:01:48 CST 2020] ret='35'
[Mon May  4 14:01:48 CST 2020] Use google doh server
[Mon May  4 14:01:48 CST 2020] _ns_ep='https://dns.google/resolve'
[Mon May  4 14:01:48 CST 2020] _ns_domain='_acme-challenge.HIDDEN.DOMAIN'
[Mon May  4 14:01:48 CST 2020] _ns_type='TXT'
[Mon May  4 14:01:48 CST 2020] GET
[Mon May  4 14:01:48 CST 2020] url='https://dns.google/resolve?name=_acme-challenge.HIDDEN.DOMAIN&type=TXT'
[Mon May  4 14:01:48 CST 2020] timeout=
[Mon May  4 14:01:48 CST 2020] Http already initialized.
[Mon May  4 14:01:48 CST 2020] _CURL='curl -L --silent --dump-header /tmp/acme/wildcard_HIDDEN.DOMAIN//http.header  -g '
[Mon May  4 14:03:03 CST 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 35
[Mon May  4 14:03:03 CST 2020] ret='35'
[Mon May  4 14:03:03 CST 2020] response
[Mon May  4 14:03:03 CST 2020] Not valid yet, let's wait 10 seconds and check next one.
[Mon May  4 14:03:03 CST 2020] _p_txtdomain='_acme-challenge.HIDDEN.DOMAIN'
[Mon May  4 14:03:03 CST 2020] Cloudflare purge TXT record for domain _acme-challenge.HIDDEN.DOMAIN
[Mon May  4 14:03:03 CST 2020] POST
[Mon May  4 14:03:03 CST 2020] _post_url='https://cloudflare-dns.com/api/v1/purge?domain=_acme-challenge.HIDDEN.DOMAIN&type=TXT'
[Mon May  4 14:03:03 CST 2020] body
[Mon May  4 14:03:03 CST 2020] _postContentType
[Mon May  4 14:03:03 CST 2020] Http already initialized.
[Mon May  4 14:03:03 CST 2020] _CURL='curl -L --silent --dump-header /tmp/acme/wildcard_HIDDEN.DOMAIN//http.header  -g '
[Mon May  4 14:03:03 CST 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 35
[Mon May  4 14:03:03 CST 2020] _ret='35'
[Mon May  4 14:03:03 CST 2020] response
[Mon May  4 14:03:13 CST 2020] Let's wait 10 seconds and check again.
[Mon May  4 14:03:23 CST 2020] Timed out waiting for DNS.
[Mon May  4 14:03:23 CST 2020] check dns error.
[Mon May  4 14:03:23 CST 2020] _on_issue_err
[Mon May  4 14:03:23 CST 2020] Please check log file for more details: /tmp/acme/wildcard_HIDDEN.DOMAIN/acme_issuecert.log

```

**Comment by Neilpang** [comment]
add `--dnssleep  300`,  it will sleep for 300 seconds before the dns records propagate.
You can use a smaller value if you know how long the dns records propagate.

**Comment by joey741019** [comment]
> add --dnssleep  300,  it will sleep for 300 seconds before the dns records propagate.
> You can use a smaller value if you know how long the dns records propagate.

it's not the DNS TTL problem. It's our environment (Enterprise Policy) blocked DoH Traffic With NGFW

In example I modify the acme.sh to  try bypass the DoH (In this code still have another issue, so just example)

> _ns_lookup_impl_override() {
>   _ns_domain="$1"
>   _ns_type="$2"
>   _debug2 "_ns_domain" "$_ns_domain"
>   _debug2 "_ns_type" "$_ns_type"
> 
>   response="$(host -t $_ns_type $_ns_domain)"
>   _ret=$?
>   _debug2 "response" "$response"
>   if [ "$_ret" != "0" ]; then
>     return $_ret
>   fi
>   _answers="$(echo "$response")"
>   _debug2 "_answers" "$_answers"
>   echo "$_answers"
> }
> 
> #domain, type
> _ns_lookup() {
>   if [ -z "$DOH_USE" ]; then
>     _debug "Detect dns server first."
>     if _ns_is_available_cf; then
>       _debug "Use cloudflare doh server"
>       export DOH_USE=$DOH_CLOUDFLARE
>     else
>       _debug "Use google doh server"
>       export DOH_USE=$DOH_GOOGLE
>     fi
>   fi
> 
>   if [ "$DOH_USE" = "$DOH_CLOUDFLARE" ] || [ -z "$DOH_USE" ]; then
>     _ns_lookup_cf "$@"
>   else
>     _ns_lookup_google "$@"
>   fi
>   _debug "Override DNS lookup"
>   _ns_lookup_impl_override "$_cf_ld" "$_cf_ld_type"
> }
>

**Comment by Neilpang** [comment]
@joey741019 
I totally understand what you mean and what you want.
why not have a try on my advice?

**Comment by joey741019** [comment]
> @joey741019
> I totally understand what you mean and what you want.
> why not have a try on my advice?
Sorry I didn't mention the acme.sh it's not call by manual CLI. It's call by Pfsense acme package.
So I cannot add any parameter to acme.sh.

**Comment by Neilpang** [comment]
@joey741019 

There should be such an option( " --dnssleep") in pfsense UI.

you can install acme.sh on your pfsense server by yourself, and try if this option is working for you.

If yes,  please report a bug to the pfsense team to request such an option.
