### ISSUE TITLE
Does Acme 'automatically' renew certificates when running in API mode (Dynu)?

### ISSUE THREAD

**Issue by jzvi12** [acmesh-official/acme.sh#2909]
Almost a month ago, I have created my certs using the Dynu API through Acme:

```
export Dynu_ClientId="My-Dynu-Client-Id"
export Dynu_Secret="h4ckM3n0w"
acme.sh --issue --dns dns_dynu -d myserver.giize.com -d www.myserver.giize.com
```

Now, I need to know how the renewal will happen... Will that be automatic or I have to do it manually running the following command?

```
./acme.sh --renew --dns dns_dynu -d myserver.giize.com -d www.myserver.giize.com
[Thu Mar 12 21:49:16 EDT 2020] Renew: 'myserver.giize.com'
[Thu Mar 12 21:49:16 EDT 2020] Skip, Next renewal time is: Mon May 11 00:46:07 UTC 2020
[Thu Mar 12 21:49:16 EDT 2020] Add '--force' to force to renew.
```

Hopefully the renewal process is automatic. If not, please instruct me on how to properly set up a crontab to make automatic.

Thanks in advance!

--
https://github.com/acmesh-official/acme.sh/wiki/dnsapi

**Comment by marcoczen** [comment]
> Almost a month ago, I have created my certs using the Dynu API through Acme:
> 
> ```
> export Dynu_ClientId="My-Dynu-Client-Id"
> export Dynu_Secret="h4ckM3n0w"
> acme.sh --issue --dns dns_dynu -d myserver.giize.com -d www.myserver.giize.com
> ```
> 
> Now, I need to know how the renewal will happen... Will that be automatic or I have to do it manually running the following command?
> 
> ```
> ./acme.sh --renew --dns dns_dynu -d myserver.giize.com -d www.myserver.giize.com
> [Thu Mar 12 21:49:16 EDT 2020] Renew: 'myserver.giize.com'
> [Thu Mar 12 21:49:16 EDT 2020] Skip, Next renewal time is: Mon May 11 00:46:07 UTC 2020
> [Thu Mar 12 21:49:16 EDT 2020] Add '--force' to force to renew.
> ```
> 
> Hopefully the renewal process is automatic. If not, please instruct me on how to properly set up a crontab to make automatic.
> 
> Thanks in advance!
> 
> --
> https://github.com/acmesh-official/acme.sh/wiki/dnsapi

When u installed acme.sh, it automatically creates a crontab entry which runs the script at night once a day. The cert is renewed automatically every 60 days.

I have not found yet where we can adjus the renewal interval.

**Comment by Neilpang** [comment]
@jzvi12 

```
[Thu Mar 12 21:49:16 EDT 2020] Skip, Next renewal time is: Mon May 11 00:46:07 UTC 2020
```

let's wait until May 12, 2020.

**Comment by jzvi12** [comment]
@Neilpang Thanks, I think it automatically updated. I mean I did nothing until May 13 when I decided to run the `--renew` command to see Acme's process reaction which output showed that it renewed the certs anyway.

Note: I had the cron disable the whole time because I thought it wasn't relevant to the Dynu API.
