### ISSUE TITLE
无法更新域名

### ISSUE THREAD

**Issue by Werner9** [acmesh-official/acme.sh#2911]
Steps to reproduce
------------------
Openwrt 路由上运行
./acme.sh --renew-all --force --debug 2

Debug log
-----------------
由于log过长 前面有部分丢失
https://zerobin.net/?86e9cae94fde5be7#qJ3+7XLHslol0LTJJe6KIW+PWszyTl3c4qOPLQ3z1hc=

**Comment by Neilpang** [comment]
@Werner9 

你用的是最新版吗

```sh
acme.sh  --upgrade
```

**Comment by Werner9** [comment]
是，我升级后用试了一次 结果一样

**Comment by Neilpang** [comment]
我要看前面的 log,  把前面的发出来.

**Comment by Werner9** [comment]
https://zerobin.net/?b75dd20aa2f913a6#lqqz5Ug8YUFVi9c9IqSPChmTTKj7ZQqrVLxokmOz0vI=

hosts 修改：
207.38.69.200 api.dynu.com
2.20.254.184 ocsp.int-x3.letsencrypt.org

**Comment by Neilpang** [comment]
你这个还是用的旧版本啊:
```
[Fri May  8 22:49:51 CST 2020] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.8.2
[Fri May  8 22:49:51 CST 2020] Using config home:/root/.acme.sh
```

你试试这个版本号多少

```
/root/.acme.sh/acme.sh  --version
```

**Comment by Werner9** [comment]
root@OpenWrt:~# /root/.acme.sh/acme.sh  --version
https://github.com/acmesh-official/acme.sh
v2.8.6

**Comment by Neilpang** [comment]
@Werner9 

所以你知道怎么做了吧

**Comment by Werner9** [comment]
知道了 感谢！
