### ISSUE TITLE
Certificates are not being renewed automatically with dns cloudflare

### ISSUE THREAD

**Issue by kevdogg** [acmesh-official/acme.sh#2920]
Perhaps I don't have a bug and things aren't working but I'm really confused.
I've upgraded to latest acme.sh as recommended.

I noticed my certificates that were initially issued through cloudflare are not being renewed.  I had converted the crontab entry into a systemd timer/service unit file.  My service file appears as the following:

```
[Unit]
Description=Renew Let's Encrypt certificates using acme.sh for %I
After=network-online.target

[Service]
Type=oneshot
ExecStart="/root/.acme.sh"/acme.sh --home "/root/.acme.sh" --cron --issue --dns dns_cf -d %i --log
```

I'm noticing however the scripts are not being renewed.  I'm using Cloudflare as my DNS provider.

I checked a couple of things.  
Within /root/.acme.sh/account.conf -- I have my:
ACCOUNT_EMAIL
SAVED_CF_Token
SAVED_CF_Account_ID

So the parameters from when the initial certificate was issued seem valid

I tried to do the following on the command line:
`./acme.sh --renew --dns dns_cf -d domain.com`

However I'm getting this as an output:
```
[Wed 13 May 2020 12:59:19 AM CDT] Renew: 'domain.com'
[Wed 13 May 2020 12:59:20 AM CDT] Single domain='domain.com'
[Wed 13 May 2020 12:59:20 AM CDT] Getting domain auth token for each domain
[Wed 13 May 2020 12:59:21 AM CDT] Getting webroot for domain='domain.com'
[Wed 13 May 2020 12:59:21 AM CDT] Adding txt value: b7T9BQMJ-Ydlz6gyMTY5-JKZY_GsV6jVs-ISSDylpts for domain:  _acme-challenge.domain.com
[Wed 13 May 2020 12:59:22 AM CDT] Error
[Wed 13 May 2020 12:59:22 AM CDT] Error add txt for domain:_acme-challenge.domain.com
[Wed 13 May 2020 12:59:22 AM CDT] Please check log file for more details: /root/.acme.sh/acme.sh.log
```

So I'm scratching my head --- what's the deal.  Why is it using a webroot method when dns_cf was specified??

**Comment by protonchang** [comment]
Can you try to output more logs by adding "--debug 2" flag ?

**Comment by JimDunphy** [comment]
I can confirm this started happening recently for us also after working well for a few years. Using the current version of running acme.sh v2.8.6 ... None of my cloudflare renewals will work via --cron automatically or via the command line using --cron.   I think the problem could be in parsing the response header. Also.. this debug 2 output is the case where I am using a CNAME so I am using the --challenge-alias construct in addition to --dns dns_cf. Here is the debug output:

> [Mon May 18 10:23:22 PDT 2020] _CURL='curl -L --silent --dump-header /home/jad/.acme.sh/http.header  --trace-ascii /tmp/tmp.pVPieeLPnM  -g '
[Mon May 18 10:23:22 PDT 2020] ret='0'
[Mon May 18 10:23:22 PDT 2020] response='{"result":[{"id":"b58917aefe982d13bb33f4ac08593fed","name":"gsans.com","status":"active","paused":false,"type":"full","development_mode":-104264765,"name_servers":["art.ns.cloudflare.com","kara.ns.cloudflare.com"],"original_name_servers":["NS6.EXAMPLE.COM","NS8.EXAMPLE.COM","NS9.EXAMPLE.COM"],"original_registrar":"1 & 1 INTERNET AG","original_dnshost":null,"modified_on":"2020-05-17T18:41:26.445879Z","created_on":"2014-10-03T18:46:52.295221Z","activated_on":"2014-10-03T23:06:46.562581Z","meta":{"step":4,"wildcard_proxiable":false,"custom_certificate_quota":0,"page_rule_quota":3,"phishing_detected":false,"multiple_railguns_allowed":false},"owner":{"id":"e0a7c20882f5adea6babcda77f16ff5b","type":"user","email":"jad@example.com"},"account":{"id":"f8d30d9b5b43f7036b4838803adbe861","name":"jad@example.com"},"permissions":["#access:edit","#access:read","#analytics:read","#app:edit","#auditlogs:read","#billing:edit","#billing:read","#cache_purge:edit","#dns_records:edit","#dns_records:read","#lb:edit","#lb:read","#legal:edit","#legal:read","#logs:edit","#logs:read","#member:edit","#member:read","#organization:edit","#organization:read","#ssl:edit","#ssl:read","#stream:edit","#stream:read","#subscription:edit","#subscription:read","#teams:edit","#teams:read","#teams:report","#waf:edit","#waf:read","#webhooks:edit","#webhooks:read","#worker:edit","#worker:read","#zone:edit","#zone:read","#zone_settings:edit","#zone_settings:read"],"plan":{"id":"0feeeeeeeeeeeeeeeeeeeeeeeeeeeeee","name":"Free Website","price":0,"currency":"USD","frequency":"","is_subscribed":true,"can_subscribe":false,"legacy_id":"free","legacy_discount":false,"externally_managed":false}}],"result_info":{"page":1,"per_page":20,"total_pages":1,"count":1,"total_count":1},"success":true,"errors":[],"messages":[]}'
[Mon May 18 10:23:22 PDT 2020] _domain_id='b58917aefe982d13bb33f4ac08593fed'
[Mon May 18 10:23:22 PDT 2020] _sub_domain='_acme-challenge'
[Mon May 18 10:23:22 PDT 2020] _domain='gsans.com'
[Mon May 18 10:23:22 PDT 2020] Getting txt records
[Mon May 18 10:23:22 PDT 2020] zones/b58917aefe982d13bb33f4ac08593fed/dns_records?type=TXT&name=_acme-challenge.gsans.com
[Mon May 18 10:23:22 PDT 2020] GET
[Mon May 18 10:23:22 PDT 2020] url='https://api.cloudflare.com/client/v4/zones/b58917aefe982d13bb33f4ac08593fed/dns_records?type=TXT&name=_acme-challenge.gsans.com'
[Mon May 18 10:23:22 PDT 2020] timeout=
[Mon May 18 10:23:22 PDT 2020] Http already initialized.
[Mon May 18 10:23:22 PDT 2020] _CURL='curl -L --silent --dump-header /home/jad/.acme.sh/http.header  --trace-ascii /tmp/tmp.pVPieeLPnM  -g '
[Mon May 18 10:23:22 PDT 2020] ret='0'
[Mon May 18 10:23:22 PDT 2020] response='{
  "result": [],
  "success": true,
  "errors": [],
  "messages": [],
  "result_info": {
    "page": 1,
    "per_page": 20,
    "count": 0,
    "total_count": 0,
    "total_pages": 1
  }
}'
[Mon May 18 10:23:22 PDT 2020] Error
[Mon May 18 10:23:22 PDT 2020] Error add txt for domain:_acme-challenge.gsans.com
[Mon May 18 10:23:23 PDT 2020] _on_issue_err
[Mon May 18 10:23:23 PDT 2020] Please check log file for more details: debug

**Comment by Neilpang** [comment]
upgrade to the latest version.
```
acme.sh --upgrade
```
