### ISSUE TITLE
ASK | how add new domain to existing configuration

### ISSUE THREAD

**Issue by x09** [acmesh-official/acme.sh#2932]
HI,
I use acme.sh for domain.com,  www.domain.com. How i can add mail.domain.com and srv.domain.com to existing configuration?

**Comment by FernandoMiguel** [comment]
> HI,
> I use acme.sh for domain.com, [www.domain.com](http://www.domain.com). How i can add mail.domain.com and srv.domain.com to existing configuration?

@x09 just issue new certs with those extra domains
