### ISSUE TITLE
CF_Zone_ID is global not per domain

### ISSUE THREAD

**Issue by wojtas911** [acmesh-official/acme.sh#2951]
Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

Hi team,
I'm using the cron job among with Le_Webroot='dns_cf'
and CF_API_key.
The issue that i will probably get (that is a new server) in 3 months that cron job is not able to renew cert via CF because last used ZONE_ID is not the same as first ssl issued zone.

If i get it correctly, ZONE_ID have to be in the domain settings, since for CF 
zoneID =  domain

Please correct me if I'm wrong.

**Comment by Neilpang** [comment]
read the doc here:

https://github.com/acmesh-official/acme.sh/wiki/dnsapi#1-cloudflare-option

>> Alternatively, if the certificate only covers a single zone, you can restrict the API Token only for write access to Zone.DNS for a single domain, and then specify the CF_Zone_ID directly:
