### ISSUE TITLE
I change the wiki, thought it will create an  pull request.

### ISSUE THREAD

**Issue by swuecho** [acmesh-official/acme.sh#2956]
seems the wiki is editable by anyone. 

anyway, please check if it is reasonable. 

in page: https://github.com/acmesh-official/acme.sh/wiki/DNS-manual-mode

If your domain provider does not offer an API where you can add/edit TXT records of your domain, it is recommended to use DNS alias mode instead. 

If your domain provider does not offer an API where you can add/edit TXT records of your domain, it is recommended to use DNS alias mode instead. _Or change the dns servers of your domain to anyone that support DNS api._

my domain name is provided by namecheap and I change the ns record to digital ocean. I did not have problem to create cert for it use digital ocean api.

my another domain name is provided by huaweicloud, which does not have an api. I change the dns server to digitialocean and works fine, too.

**Comment by Neilpang** [comment]
which page did you edit?  can you show me the link?

**Comment by swuecho** [comment]
> which page did you edit? can you show me the link?

https://github.com/acmesh-official/acme.sh/wiki/DNS-manual-mode
