### ISSUE TITLE
With --test staging servers are permanent

### ISSUE THREAD

**Issue by z0rti** [acmesh-official/acme.sh#2957]
I just used acme.sh --renew [...] --test
when i use acme.sh --renew afterwards (without --test) it still uses the staging servers.

Workaround:
remove Le_API Le_OrderFinalize Le_LinkOrder Le_LinkCert lines from .conf manually
rerun acme.sh without --test

**Comment by Neilpang** [comment]
please issue a new cert.

"renew" a cert doesn't change the API endpoint.
