### ISSUE TITLE
--deploy怎么反部署?撤销定时任务

### ISSUE THREAD

**Issue by HiColinn** [acmesh-official/acme.sh#2969]
Steps to reproduce
------------------
并不是一条BUG,无需复现
Debug log
-----------------
并不是一条BUG,无需log
-----------------
我想问,通过--installcert 安装和--deploy部署证书以后,怎样回撤操作?我知道可以使用remove 命令来停止某个domain的证书续订,但是我想要的是,之前的安装/部署 操作,不再继续续期.即反部署.

比如我的泛域名部署到了一个docker容器中,我想,默认情况下,acme.sh存有一个自动续期任务,但是假如我之前--deploy的时候的目标网站删掉了,但是这个泛域名证书还用到了其它站点,我不想删除,只想将之前的某个--deploy的操作删除,告诉acme.sh,以后这个站点不用部署了.

我已经查过了过往issue和acme.sh,没有看到相关操作,希望得到您的解答.

**Comment by Neilpang** [comment]
首先, 一个证书只能deploy 一次, 如果你多次调用 deploy,  只有最后一个被记住.  证书60天后自动更新只有最后一次deploy 会自动执行.

(想一个证书 deploy 多次, 可以 在 `--deploy` 时, 传入多个`--deploy-hook`, 这是另外一个话题,此处不展开了.)

其次, 调用 remove 命令后,  证书将不再会自动更新, 也就不会再次 deploy

**Comment by HiColinn** [comment]
> 首先, 一个证书只能deploy 一次, 如果你多次调用 deploy, 只有最后一个被记住. 证书60天后自动更新只有最后一次deploy 会自动执行.
> 
> (想一个证书 deploy 多次, 可以 在 `--deploy` 时, 传入多个`--deploy-hook`, 这是另外一个话题,此处不展开了.)
> 
> 其次, 调用 remove 命令后, 证书将不再会自动更新, 也就不会再次 deploy

&nbsp;&nbsp;您好,非常感谢您的解答😆但是我还是有一些疑问.
***
&nbsp;&nbsp;1.关于一个证书多次部署到不同的nginx容器:
&nbsp;&nbsp;&nbsp;&nbsp;通常情况下,我往一个nginx容器中的站点--deploy证书是使用下面的方式:
```shell
docker exec -it \
  -e DEPLOY_DOCKER_CONTAINER_LABEL=acme.nginx.web1 \
  -e DEPLOY_DOCKER_CONTAINER_KEY_FILE="/etc/nginx/ssl/domain.com/domain.com.key" \
	... 此处省略...
  -e DEPLOY_DOCKER_CONTAINER_RELOAD_CMD="service nginx force-reload" \
  acme.sh --deploy -d domain.com --deploy-hook docker --ecc
```
&nbsp;&nbsp;&nbsp;&nbsp;最后面--deploy-hook 的参数只是一个docker,请问怎么传入多个--deploy-hook?我想,合理的方法应该是,传入多个DEPLOY_DOCKER_CONTAINER_LABEL来标记为多个docker容器部署?比如:
```shell
docker exec -it \
  -e DEPLOY_DOCKER_CONTAINER_LABEL=acme.nginx.web1 \
  -e DEPLOY_DOCKER_CONTAINER_LABEL=acme.nginx.web2 \
  -e DEPLOY_DOCKER_CONTAINER_LABEL=acme.nginx.web3 \
  -e DEPLOY_DOCKER_CONTAINER_KEY_FILE="/etc/nginx/ssl/domain.com/domain.com.key" \
	... 此处省略...
  -e DEPLOY_DOCKER_CONTAINER_RELOAD_CMD="service nginx force-reload" \
  acme.sh --deploy -d domain.com --deploy-hook docker --ecc
```
&nbsp;&nbsp;2.关于remove和revoke:
&nbsp;&nbsp;&nbsp;&nbsp;我又查看了wiki,确实看到了卸载命令,按照目前的设定,好像只能同时移除某个证书,而不能只移除某次部署.但是我还有个疑问,remove和revoke有什么区别?是不是--remove对应--installcert安装的证书,而--revoke对应--deploy的证书?

**Comment by Neilpang** [comment]
>> 最后面--deploy-hook 的参数只是一个docker,请问怎么传入多个--deploy-hook?我想,合理的方法应该是,传入多个DEPLOY_DOCKER_CONTAINER_LABEL来标记为多个docker容器部署?

目前还没有原生支持同时部署到两个container 里面. 你的想法不错, 可以参考


>> 2.关于remove和revoke:

remove 就是删除的意思,  删除后的证书相当于不存在了, 以后的自动更新就跟他没关系了.    
实际上为了安全,怕你误删,  证书文件并没有真正的删除, 而是保留在了证书目录中. 你可以手动的 rm 删除.

revoke 就是吊销证书的意思, 是指在服务端去申请吊销证书.  并不影响你本地的证书和配置.  最让证书已经被吊销, 但是本地并不在意,  在下次更新证书日期到来的时候, 证书还是会被 renew, 并deploy
