### ISSUE TITLE
Understanding the acme.sh data model wrt account email address

### ISSUE THREAD

**Issue by pini-gh** [acmesh-official/acme.sh#2970]
Hi,

This is not a bug report but a question to @Neilpang.

I'm trying to follow up on the [initial work by @buchdag](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/issues/510) to use `acme.sh` instead of `simp_le` for `letsencrypt-nginx-proxy-companion`.
As I undertand it:
* An `acme.sh` configuration directory is tied to one and only one email address
* An `acme.sh` configuration directory can hold several accounts for different ACME service providers. These accounts are configured under `<acme.sh_conf_dir>/ca/<service_provider_fqdn>`.
Then, say I want to update the email address for a given `acme.sh` configuration directory, I'd need to issue an `acme.sh --update-account` command for each configured ACME service provider. This command would look like:
```
acme.sh --update-account --server <service_provider_directory_url> --accountemail <new_email>
```
Is that correct? In this case it would be convenient to have the service provider directory url stored somewhere into the account configuration,to be able to script the above command. Would you mind me submitting a PR to this end?

In case my understanding stated above is not correct, please tell me.

Thanks in advance,

_g.

**Comment by Neilpang** [comment]
Yes, correct.
But I won't accept the PR for just the case that you want to enumerate all the  CA to update email.

**Comment by pini-gh** [comment]
Ack. Closing this issue as the question was answered.
