### ISSUE TITLE
 You didn't specify a Cloudflare api key and email yet.

### ISSUE THREAD

**Issue by MESWEB** [acmesh-official/acme.sh#2972]
[Sun May 31 00:22:24 CEST 2020] You didn't specify a Cloudflare api key and email yet.
[Sun May 31 00:22:24 CEST 2020] You can get yours from here https://dash.cloudflare.com/profile.
[Sun May 31 00:22:24 CEST 2020] Error add txt for domain:_acme-challenge.dsff.ftr
[Sun May 31 00:22:24 CEST 2020] Please check log file for more details: /root/.acme.sh/acme.sh.log

Steps to reproduce
------------------
acme.sh  --issue -d dsff.ftr  -d '*.dsff.ftr'  --dns dns_cf

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh/wiki/dnsapi#1-cloudflare-option

**Comment by MESWEB** [comment]
@Neilpang But I'm not using cloudflare. acme.sh detecting server API?
