### ISSUE TITLE
Transition to ISRG’s Root delayed until Sep 29

### ISSUE THREAD

**Issue by JimDunphy** [acmesh-official/acme.sh#2988]
Feature request.

Would it be possible to add a command line option to pull chain we prefer.

From the document link below.

"in the time between now and September 29 we plan to start serving certificates with the “alternate” link relation to allow ACME clients to programmatically select a chain they prefer."

Ref: https://community.letsencrypt.org/t/transition-to-isrgs-root-delayed-until-sep-29/125516

**Comment by JimDunphy** [comment]
A bit more detail... Downloading the Certificate

   To download the issued certificate, the client simply sends a POST-
   as-GET request to the certificate URL.

   The default format of the certificate is application/pem-certificate-
   chain (see Section 9).

   The server MAY provide one or more link relation header fields
   [RFC8288] ****with relation "alternate"****.  Each such field SHOULD express
   an alternative certificate chain starting with the same end-entity
   certificate.  This can be used to express paths to various trust
   anchors.  _**Clients can fetch these alternates**_ and use their own
   heuristics to decide which is optimal.

Ref: https://tools.ietf.org/html/rfc8555#section-7.4.2

**Comment by JimDunphy** [comment]
Reason for the request. It would allow us to debug deploy scripts and some odd server implementations before cut over and verify clients that will work and not work.

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh/wiki/Preferred-Chain
