### ISSUE TITLE
You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard.

### ISSUE THREAD

**Issue by biozzl** [acmesh-official/acme.sh#2989]
Not working by acme.sh
Any idea how to fix this? 
If this can be done manually, how to proceed, pl elaborate.
Thanks!
Output message from debug 2 is downbelow:
[acme.sh.log](https://github.com/acmesh-official/acme.sh/files/4768577/acme.sh.log)

[Fri Jun 12 00:40:26 CST 2020] _post_url='https://api.cloudflare.com/client/v4/zones/444523a6e1f5544bbcd10e864fcabbab/dns_records'
[Fri Jun 12 00:40:26 CST 2020] body='{"type":"TXT","name":"_acme-challenge.fk1.azlosec.tk","content":"PfNCdkdEpOXgoHAsXVi82lEpD8BrnwlLZqHx-Yv2Emw","ttl":120}'
[Fri Jun 12 00:40:26 CST 2020] _postContentType
[Fri Jun 12 00:40:26 CST 2020] Http already initialized.
[Fri Jun 12 00:40:26 CST 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.aOxlaHC6LA  -g '
[Fri Jun 12 00:40:26 CST 2020] _ret='0'
[Fri Jun 12 00:40:26 CST 2020] response='{
  "error": "You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard."
}'
[Fri Jun 12 00:40:26 CST 2020] Add txt record error.
[Fri Jun 12 00:40:26 CST 2020] Error add txt for domain:_acme-challenge.fk1.azlosec.tk
[Fri Jun 12 00:40:26 CST 2020] _on_issue_err
[Fri Jun 12 00:40:26 CST 2020] Please check log file for more details: /root/.acme.sh/acme.sh.log
[Fri Jun 12 00:40:26 CST 2020] _chk_vlist='fk1.azlosec.tk#pI8pIqk1s0Ph45pjYGgnbnJ56vJ3klCLc3TUhO7Qtog.ISPG7cTAl5GzjGTIB94CFaxjZYBhKIqlBgTaUnlgS5s#https://acme-v02.api.letsencrypt.org/acme/chall-v3/5165433772/u0wPUg#dns-01#dns_cf,'
[Fri Jun 12 00:40:26 CST 2020] start to deactivate authz
[Fri Jun 12 00:40:26 CST 2020] Trigger domain validation.
[Fri Jun 12 00:40:26 CST 2020] _t_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/5165433772/u0wPUg'
[Fri Jun 12 00:40:26 CST 2020] _t_key_authz='pI8pIqk1s0Ph45pjYGgnbnJ56vJ3klCLc3TUhO7Qtog.ISPG7cTAl5GzjGTIB94CFaxjZYBhKIqlBgTaUnlgS5s'
[Fri Jun 12 00:40:26 CST 2020] _t_vtype
[Fri Jun 12 00:40:26 CST 2020] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/5165433772/u0wPUg'
[Fri Jun 12 00:40:26 CST 2020] payload='{}'
[Fri Jun 12 00:40:26 CST 2020] Use cached jwk for file: /root/.acme.sh/ca/acme-v02.api.letsencrypt.org/account.key
[Fri Jun 12 00:40:26 CST 2020] Use _CACHED_NONCE='0101nJkWpR-z6KuqJAHxxQGey4TK7V7snfXroYsF4H1cw_M'
[Fri Jun 12 00:40:26 CST 2020] nonce='0101nJkWpR-z6KuqJAHxxQGey4TK7V7snfXroYsF4H1cw_M'
[Fri Jun 12 00:40:26 CST 2020] POST
[Fri Jun 12 00:40:26 CST 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/5165433772/u0wPUg'
[Fri Jun 12 00:40:26 CST 2020] body='{"protected": "eyJub25jZSI6ICIwMTAxbkprV3BSLXo2S3VxSkFIeHhRR2V5NFRLN1Y3c25mWHJvWXNGNEgxY3dfTSIsICJ1cmwiOiAiaHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvY2hhbGwtdjMvNTE2NTQzMzc3Mi91MHdQVWciLCAiYWxnIjogIlJTMjU2IiwgImtpZCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hY2N0Lzg4NTY1NzUxIn0", "payload": "e30", "signature": "AJ2fRP4XDCvT3wDVS5k90v-ZImtwXAdmAWC6KtRKafwzpGjhtCTNAE4ZC7Z_D8aE1K-2Aa3txzwqp1FTk0IW9BHxK40gE7OUTJTtZrC32HQU93YHNkOa01PRssTJOvSI205YKxTnErhJrZneAqOy87IM5HU0fLzTj8xTt-xqFhzFyPJFHbp6WqfQb_QhdIK6N8xqoNsFlDKhDCqogAgx7I1r1QYE45q2t4EE6NqZK8MV040SywcaQtkEgIyXQWRmGqqL6-n5GSNmfRTIYzFx692SiFxdiyVnOUIG2BePzW7fWLwYgML7C8lPh9w7i4VMpUJB8DJyD7R0tXSJ_HQR5w"}'
[Fri Jun 12 00:40:26 CST 2020] _postContentType='application/jose+json'
[Fri Jun 12 00:40:26 CST 2020] Http already initialized.
[Fri Jun 12 00:40:26 CST 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.aOxlaHC6LA  -g '
[Fri Jun 12 00:40:27 CST 2020] _ret='0'
[Fri Jun 12 00:40:27 CST 2020] responseHeaders='HTTP/2 200

**Comment by lucifer0114** [comment]
Met the same issue by using domains from freenom.
Change another domain provider should slove it.

**Comment by biozzl** [comment]
> Met the same issue by using domains from freenom.
> Change another domain provider should slove it.

Don't wants to change from freenom. Any suggestions to moving this forward? Any work around action can be taken?

**Comment by MAGICCC** [comment]
No, cloudflare decided to drop API support for these tlds
https://community.cloudflare.com/t/unable-to-update-ddns-using-api-for-some-tlds/167228/11

**Comment by lucifer0114** [comment]
> > Met the same issue by using domains from freenom.
> > Change another domain provider should slove it.
> 
> Don't wants to change from freenom. Any suggestions to moving this forward? Any work around action can be taken?

Just as what @MAGICCC said,  it is cloudflare who has made the change. So you have no choice.
