### ISSUE TITLE
Cron install over wrote crontab 

### ISSUE THREAD

**Issue by grx3** [acmesh-official/acme.sh#2991]
doing acme.sh --install overwrote the previous crontab that was there and for me wasn't noticed over the weekend and we lost two days of work.   Using cpanel and the latest version of acme.sh 

Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

**Comment by Neilpang** [comment]
sorry about that, can you please show me the crontabs before installing acme.sh?
```
crontab -l

```

**Comment by grx3** [comment]
Thanks for your reply.   That would of been awesome to have a backup of my crontabs, that's now part of of our backup routine because of this incident.   If it helps there where about 8 wget cron calls and about 4 bash script calls, and 3 php calls. 13 crontab lines in total.  Nothing outside calling a bash, wget, or php line.   The script overwrote everything, a confirm at the very least would of been nice.


-------- Original Message --------
Subject: Re: [acmesh-official/acme.sh] Cron install over wrote crontab 
(#2991)

**Comment by Neilpang** [comment]
@grx3  
if you can show me your cronjobs,  maybe I can fix it.

Thanks.

**Comment by grx3** [comment]
The crontab was erased when acme.sh installed itself.   There is no way to show you.   It cleared the cron jobs.


-------- Original Message --------
Subject: Re: [acmesh-official/acme.sh] Cron install over wrote crontab 
(#2991)
