### ISSUE TITLE
cPanel deploy to all subdomains

### ISSUE THREAD

**Issue by FKasa** [acmesh-official/acme.sh#2992]
Hello, this is my first time contributing to FOSS :)

Using acme.sh I have been able to get certificates and deploy them to my shared cPanel hosting via ```--deploy-hook cpanel_uapi``` . This is great. I later realised that cPanel doesn't automatically use wildcard certificates for subdomains. I wrote this script to do that. I am new to bash so I don't think I can adapt it in a plugin or PR level so I am posting it here and hopefully someone can make use of it.

```bash
#!/bin/bash

# Requirement: this script uses EXISTING wildcard certificates and
# applies them to subdomains as cPanel does not do that automatically

# this script would benefit from error and dependency checking

printf "\nScript started.\n"

# Get list of subdomains, not tested when there is no subdomains. Output (each subdomain) is saved in array.
# https://documentation.cpanel.net/display/DD/UAPI+Functions+-+DomainInfo%3A%3Alist_domains
subdomains=(`uapi DomainInfo list_domains --output=yaml 2>/dev/null | awk '/sub_domains/{f=1;next} /errors/{f=0} f' | sed 's/ *- //g'`)

# Go over each subdomain
for subdomain in "${subdomains[@]}"
do
  echo "Subdomain: $subdomain"
  # store the best certificate, private key and ca bundle for the subdomain
  # https://documentation.cpanel.net/display/DD/UAPI+Functions+-+SSL%3A%3Afetch_best_for_domain
  subdomainxml=`uapi SSL fetch_best_for_domain domain=$subdomain --output=xml 2>/dev/null`
  # extract those to their own variable
  cert=`echo "$subdomainxml" | xmllint --xpath '//crt/text()' -`
  key=`echo "$subdomainxml" | xmllint --xpath '//key/text()' -`
  cab=`echo "$subdomainxml" | xmllint --xpath '//cab/text()' -`
  
  # urlencode variables as required by the following install SSL function
  # https://stackoverflow.com/questions/11876353/url-encoding-a-string-in-bash-script/11876446#11876446
  urlcert=$(php -r "echo urlencode(\"$cert\");")
  urlkey=$(php -r "echo urlencode(\"$key\");")
  urlcab=$(php -r "echo urlencode(\"$cab\");")

  # install the best certificate for the subdomain
  # note: no action taken if best certifiate is already present
  # https://documentation.cpanel.net/display/DD/UAPI+Functions+-+SSL%3A%3Ainstall_ssl
  uapi SSL install_ssl domain=$subdomain cert=$urlcert key=$urlkey cabundle=$urlcab

  printf "\n\n\n"

done

printf "\nScript completed.\n"
```

**Comment by ahmadpi** [comment]
> Hello, this is my first time contributing to FOSS :)
> 
> Using acme.sh I have been able to get certificates and deploy them to my shared cPanel hosting via `--deploy-hook cpanel_uapi` . This is great. I later realised that cPanel doesn't automatically use wildcard certificates for subdomains. I wrote this script to do that. I am new to bash so I don't think I can adapt it in a plugin or PR level so I am posting it here and hopefully someone can make use of it.
> 
> ```shell
> #!/bin/bash
> 
> # Requirement: this script uses EXISTING wildcard certificates and
> # applies them to subdomains as cPanel does not do that automatically
> 
> # this script would benefit from error and dependency checking
> 
> printf "\nScript started.\n"
> 
> # Get list of subdomains, not tested when there is no subdomains. Output (each subdomain) is saved in array.
> # https://documentation.cpanel.net/display/DD/UAPI+Functions+-+DomainInfo%3A%3Alist_domains
> subdomains=(`uapi DomainInfo list_domains --output=yaml 2>/dev/null | awk '/sub_domains/{f=1;next} /errors/{f=0} f' | sed 's/ *- //g'`)
> 
> # Go over each subdomain
> for subdomain in "${subdomains[@]}"
> do
>   echo "Subdomain: $subdomain"
>   # store the best certificate, private key and ca bundle for the subdomain
>   # https://documentation.cpanel.net/display/DD/UAPI+Functions+-+SSL%3A%3Afetch_best_for_domain
>   subdomainxml=`uapi SSL fetch_best_for_domain domain=$subdomain --output=xml 2>/dev/null`
>   # extract those to their own variable
>   cert=`echo "$subdomainxml" | xmllint --xpath '//crt/text()' -`
>   key=`echo "$subdomainxml" | xmllint --xpath '//key/text()' -`
>   cab=`echo "$subdomainxml" | xmllint --xpath '//cab/text()' -`
>   
>   # urlencode variables as required by the following install SSL function
>   # https://stackoverflow.com/questions/11876353/url-encoding-a-string-in-bash-script/11876446#11876446
>   urlcert=$(php -r "echo urlencode(\"$cert\");")
>   urlkey=$(php -r "echo urlencode(\"$key\");")
>   urlcab=$(php -r "echo urlencode(\"$cab\");")
> 
>   # install the best certificate for the subdomain
>   # note: no action taken if best certifiate is already present
>   # https://documentation.cpanel.net/display/DD/UAPI+Functions+-+SSL%3A%3Ainstall_ssl
>   uapi SSL install_ssl domain=$subdomain cert=$urlcert key=$urlkey cabundle=$urlcab
> 
>   printf "\n\n\n"
> 
> done
> 
> printf "\nScript completed.\n"
> ```

This script works. Since I have few park domains in my cpanel. I added '| grep <domain name>' to select the domain that I want.

full syntax below:
subdomains=(`uapi DomainInfo list_domains --output=yaml 2>/dev/null | awk '/sub_domains/{f=1;next} /errors/{f=0} f' | sed 's/ *- //g' | grep <domain>`)

Thanks!

**Comment by dannytix** [comment]
This script looks great! I wish I had seen it sooner - it could have saved me some time.

I have put together a similar approach that is integrated into the cpanel_uapi deploy script with some other extras, and submitted pull request [4256](https://github.com/acmesh-official/acme.sh/pull/4256) which is pending review. Until then, I am shamelessly crosslinking it here in the hopes of attracting more feedback and maybe saving some time for others.
