### ISSUE TITLE
华为云的域名用--challenge-alias 申请证书失败，如果是阿里云的就可以。

### ISSUE THREAD

**Issue by xieke12** [acmesh-official/acme.sh#2993]
华为云的域名用--challenge-alias 申请证书失败，如果是阿里云的就可以。
gfuigfd.com 这个是华为云
odinlk2.com 这个是阿里云
root@web1:~# /root/.acme.sh/acme.sh --issue -d gfuigfd.com --challenge-alias odinlk2.com --dns dns_ali
[Wed Jun 17 12:55:05 HKT 2020] Create account key ok.
[Wed Jun 17 12:55:05 HKT 2020] Registering account
[Wed Jun 17 12:55:07 HKT 2020] Registered
[Wed Jun 17 12:55:07 HKT 2020] ACCOUNT_THUMBPRINT='5oqa_0nr7obh4ylqjXK_XTODaQn4PzzzBGrRZ8NzUgg'
[Wed Jun 17 12:55:07 HKT 2020] Creating domain key
[Wed Jun 17 12:55:07 HKT 2020] The domain key is here: /root/.acme.sh/gfuigfd.com/gfuigfd.com.key
[Wed Jun 17 12:55:07 HKT 2020] Single domain='gfuigfd.com'
[Wed Jun 17 12:55:07 HKT 2020] Getting domain auth token for each domain
[Wed Jun 17 12:55:10 HKT 2020] Getting webroot for domain='gfuigfd.com'
[Wed Jun 17 12:55:10 HKT 2020] Adding txt value: ZMYpOdD8vVdtX4vBRVRZ6t4ff4krtgb1kMuScmbB4fQ for domain:  _acme-challenge.odinlk2.com
[Wed Jun 17 12:55:14 HKT 2020] The txt record is added: Success.
[Wed Jun 17 12:55:14 HKT 2020] Let's check each dns records now. Sleep 20 seconds first.
[Wed Jun 17 12:55:35 HKT 2020] Checking gfuigfd.com for _acme-challenge.odinlk2.com
[Wed Jun 17 12:55:35 HKT 2020] Domain gfuigfd.com '_acme-challenge.odinlk2.com' success.
[Wed Jun 17 12:55:35 HKT 2020] All success, let's return
[Wed Jun 17 12:55:35 HKT 2020] Verifying: gfuigfd.com
[Wed Jun 17 12:55:39 HKT 2020] Pending
[Wed Jun 17 12:55:42 HKT 2020] Pending
[Wed Jun 17 12:55:46 HKT 2020] Pending
[Wed Jun 17 12:55:49 HKT 2020] Pending
[Wed Jun 17 12:55:52 HKT 2020] Pending
[Wed Jun 17 12:55:55 HKT 2020] Pending
[Wed Jun 17 12:55:57 HKT 2020] Pending
[Wed Jun 17 12:56:00 HKT 2020] gfuigfd.com:Verify error:DNS problem: SERVFAIL looking up CAA for gfuigfd.com - the domain's nameservers may be malfunctioning
[Wed Jun 17 12:56:00 HKT 2020] Removing DNS records.
[Wed Jun 17 12:56:00 HKT 2020] Removing txt: ZMYpOdD8vVdtX4vBRVRZ6t4ff4krtgb1kMuScmbB4fQ for domain: _acme-challenge.odinlk2.com
[Wed Jun 17 12:56:05 HKT 2020] Removed: Success
[Wed Jun 17 12:56:05 HKT 2020] Please add '--debug' or '--log' to check more details.
[Wed Jun 17 12:56:05 HKT 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
root@web1:~#

**Comment by xieke12** [comment]
使用debug 2 会特别长。我截取了一段

[Wed Jun 17 13:42:49 HKT 2020] responseHeaders='HTTP/1.1 200 OK
Server: nginx
Date: Wed, 17 Jun 2020 05:42:49 GMT
Content-Type: application/json
Content-Length: 184
Connection: keep-alive
Boulder-Requester: 89028223
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Link: <https://acme-v02.api.letsencrypt.org/acme/authz-v3/5292714148>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/5292714148/SOf52g
Replay-Nonce: 0002_NPY5vRUrxWGBSfZ8tji9Qko_MJJTV4PqyMmcIaRC7M
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
'
[Wed Jun 17 13:42:49 HKT 2020] code='200'
[Wed Jun 17 13:42:49 HKT 2020] original='{
  "type": "dns-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/5292714148/SOf52g",
  "token": "XDjWsFB9tBRYgCA5U87C9I0hDOVuDc3olOsBGSfVJQk"
}'
[Wed Jun 17 13:42:49 HKT 2020] response='{"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/5292714148/SOf52g","token":"XDjWsFB9tBRYgCA5U87C9I0hDOVuDc3olOsBGSfVJQk"}'
[Wed Jun 17 13:42:49 HKT 2020] original='{"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/5292714148/SOf52g","token":"XDjWsFB9tBRYgCA5U87C9I0hDOVuDc3olOsBGSfVJQk"}'
[Wed Jun 17 13:42:49 HKT 2020] response='{"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/5292714148/SOf52g","token":"XDjWsFB9tBRYgCA5U87C9I0hDOVuDc3olOsBGSfVJQk"}'
[Wed Jun 17 13:42:49 HKT 2020] Pending
[Wed Jun 17 13:42:49 HKT 2020] sleep 2 secs to verify
[Wed Jun 17 13:42:51 HKT 2020] checking
[Wed Jun 17 13:42:51 HKT 2020] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/5292714148/SOf52g'
[Wed Jun 17 13:42:51 HKT 2020] payload
[Wed Jun 17 13:42:51 HKT 2020] Use cached jwk for file: /root/.acme.sh/ca/acme-v02.api.letsencrypt.org/account.key
[Wed Jun 17 13:42:51 HKT 2020] Use _CACHED_NONCE='0002_NPY5vRUrxWGBSfZ8tji9Qko_MJJTV4PqyMmcIaRC7M'
[Wed Jun 17 13:42:51 HKT 2020] nonce='0002_NPY5vRUrxWGBSfZ8tji9Qko_MJJTV4PqyMmcIaRC7M'
[Wed Jun 17 13:42:51 HKT 2020] POST
[Wed Jun 17 13:42:51 HKT 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/5292714148/SOf52g'
[Wed Jun 17 13:42:51 HKT 2020] body='{"protected": "eyJub25jZSI6ICIwMDAyX05QWTV2UlVyeFdHQlNmWjh0amk5UWtvX01KSlRWNFBxeU1tY0lhUkM3TSIsICJ1cmwiOiAiaHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvY2hhbGwtdjMvNTI5MjcxNDE0OC9TT2Y1MmciLCAiYWxnIjogIlJTMjU2IiwgImtpZCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hY2N0Lzg5MDI4MjIzIn0", "payload": "", "signature": "FzNHFka3eOZH773LtpoZdyuy5IUQZgWuY-LpF_VTHYvwR53NQ6Z06T_XKXiovs7KLkrohrTM7a4x5v7biQqRUmzrmH6x_ZrdIBztfnS-ZXeNJ80BWHxSsvQtV62d6eoJKUWiHlWgCISMk7GpYDgTcCeUA5eHHOsoBaETc3rA50TPUejDeymhbxw_o0oxJZqJxPXjqFmncYW-l-nL4X-hxy9CXzEJVEV75tKF3_uP2T3eQSPeKxClOPT5QS7NKA0sVKOsIFlDPXlf0yIzUQ2Lq5-RHSLGKPLx8zJ1vO5QTWHEsuNbNGnGru7Eq1FyiH4-RyKCs0dIGADjWIAEM1rf_A"}'
[Wed Jun 17 13:42:51 HKT 2020] _postContentType='application/jose+json'
[Wed Jun 17 13:42:51 HKT 2020] Http already initialized.
[Wed Jun 17 13:42:51 HKT 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.dmTVqhutAA  -g '
[Wed Jun 17 13:42:52 HKT 2020] _ret='0'
[Wed Jun 17 13:42:52 HKT 2020] responseHeaders='HTTP/1.1 200 OK
Server: nginx
Date: Wed, 17 Jun 2020 05:42:52 GMT
Content-Type: application/json
Content-Length: 487
Connection: keep-alive
Boulder-Requester: 89028223
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Link: <https://acme-v02.api.letsencrypt.org/acme/authz-v3/5292714148>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/5292714148/SOf52g
Replay-Nonce: 010209z3BK3WD2fVt33eSd56VwwdVw9l4h6npPEiDuMKO7c
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
'
[Wed Jun 17 13:42:52 HKT 2020] code='200'
[Wed Jun 17 13:42:52 HKT 2020] original='{
  "type": "dns-01",
  "status": "invalid",
  "error": {
    "type": "urn:ietf:params:acme:error:dns",
    "detail": "During secondary validation: DNS problem: SERVFAIL looking up CAA for gfuigfd.com - the domain's nameservers may be malfunctioning",
    "status": 400
  },
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/5292714148/SOf52g",
  "token": "XDjWsFB9tBRYgCA5U87C9I0hDOVuDc3olOsBGSfVJQk",
  "validationRecord": [
    {
      "hostname": "gfuigfd.com"
    }
  ]
}'
[Wed Jun 17 13:42:52 HKT 2020] response='{"type":"dns-01","status":"invalid","error":{"type":"urn:ietf:params:acme:error:dns","detail":"During secondary validation: DNS problem: SERVFAIL looking up CAA for gfuigfd.com - the domain's nameservers may be malfunctioning","status": 400},"url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/5292714148/SOf52g","token":"XDjWsFB9tBRYgCA5U87C9I0hDOVuDc3olOsBGSfVJQk","validationRecord":[{"hostname":"gfuigfd.com"}]}'
[Wed Jun 17 13:42:52 HKT 2020] original='{"type":"dns-01","status":"invalid","error":{"type":"urn:ietf:params:acme:error:dns","detail":"During secondary validation: DNS problem: SERVFAIL looking up CAA for gfuigfd.com - the domain's nameservers may be malfunctioning","status": 400},"url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/5292714148/SOf52g","token":"XDjWsFB9tBRYgCA5U87C9I0hDOVuDc3olOsBGSfVJQk","validationRecord":[{"hostname":"gfuigfd.com"}]}'
[Wed Jun 17 13:42:52 HKT 2020] response='{"type":"dns-01","status":"invalid","error":{"type":"urn:ietf:params:acme:error:dns","detail":"During secondary validation: DNS problem: SERVFAIL looking up CAA for gfuigfd.com - the domain's nameservers may be malfunctioning","status": 400},"url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/5292714148/SOf52g","token":"XDjWsFB9tBRYgCA5U87C9I0hDOVuDc3olOsBGSfVJQk","validationRecord":[{"hostname":"gfuigfd.com"}]}'
[Wed Jun 17 13:42:52 HKT 2020] error='"error":{"type":"urn:ietf:params:acme:error:dns","detail":"During secondary validation: DNS problem: SERVFAIL looking up CAA for gfuigfd.com - the domain's nameservers maybe malfunctioning","status": 400'
[Wed Jun 17 13:42:52 HKT 2020] errordetail='During secondary validation: DNS problem: SERVFAIL looking up CAA for gfuigfd.com - the domain's nameservers may be malfunctioning'
[Wed Jun 17 13:42:52 HKT 2020] gfuigfd.com:Verify error:During secondary validation: DNS problem: SERVFAIL looking up CAA for gfuigfd.com - the domain's nameservers may be malfunctioning
[Wed Jun 17 13:42:52 HKT 2020] Skip for removelevel:
[Wed Jun 17 13:42:52 HKT 2020] pid
[Wed Jun 17 13:42:52 HKT 2020] No need to restore nginx, skip.

**Comment by XuuKoo** [comment]
之前是好的，最近同样遇到了这个问题
提示
mydomain.com:Verify error:DNS problem: SERVFAIL looking up CAA for mydomain.com - the domain's nameservers may be malfunctioning

**Comment by XuuKoo** [comment]
我这边尝试把CAA记录删除后，一切正常了，感觉不是DNS提供商的问题

**Comment by XuuKoo** [comment]
我这边尝试把CAA记录删除后，一切正常了，感觉不是DNS提供商的问题

**Comment by antsbean** [comment]
我也遇到了同样的问题 我的域名也是华为云的

**Comment by XuuKoo** [comment]
> 
> 
> 我也遇到了同样的问题 我的域名也是华为云的

后来经过反复尝试，问题应该是华为的dns在海外访问困难。
后来发现 把华为四个dns服务器全部填在域名里，大概率不会出问题。

**Comment by antsbean** [comment]
> > 我也遇到了同样的问题 我的域名也是华为云的
> 
> 后来经过反复尝试，问题应该是华为的dns在海外访问困难。
> 后来发现 把华为四个dns服务器全部填在域名里，大概率不会出问题。

NS 和 SOA 类型 华为云默认就添加了，请指教你是添加哪个类型的记录？

**Comment by antsbean** [comment]
> > 我也遇到了同样的问题 我的域名也是华为云的
> 
> 后来经过反复尝试，问题应该是华为的dns在海外访问困难。
> 后来发现 把华为四个dns服务器全部填在域名里，大概率不会出问题。

ns1.huaweicloud-dns.com
ns1.huaweicloud-dns.cn
ns1.huaweicloud-dns.net
ns1.huaweicloud-dns.org 

这个四个域名 NS 和 SOA 类型 华为云默认就添加了，请指教你是添加哪个类型的记录？

**Comment by XuuKoo** [comment]
> 
> 
> > > 我也遇到了同样的问题 我的域名也是华为云的
> > 
> > 
> > 后来经过反复尝试，问题应该是华为的dns在海外访问困难。
> > 后来发现 把华为四个dns服务器全部填在域名里，大概率不会出问题。
> 
> ns1.huaweicloud-dns.com
> ns1.huaweicloud-dns.cn
> ns1.huaweicloud-dns.net
> ns1.huaweicloud-dns.org
> 
> 这个四个域名 NS 和 SOA 类型 华为云默认就添加了，请指教你是添加哪个类型的记录？

就是把这四个加到域名提供商的nameserver里面。
另外你是不是套了cf？

**Comment by antsbean** [comment]
> > > > 我也遇到了同样的问题 我的域名也是华为云的
> > > 
> > > 
> > > 后来经过反复尝试，问题应该是华为的dns在海外访问困难。
> > > 后来发现 把华为四个dns服务器全部填在域名里，大概率不会出问题。
> > 
> > 
> > ns1.huaweicloud-dns.com
> > ns1.huaweicloud-dns.cn
> > ns1.huaweicloud-dns.net
> > ns1.huaweicloud-dns.org
> > 这个四个域名 NS 和 SOA 类型 华为云默认就添加了，请指教你是添加哪个类型的记录？
> 
> 就是把这四个加到域名提供商的nameserver里面。
> 另外你是不是套了cf？

error:During secondary validation: DNS problem: SERVFAIL looking up TXT for _acme-challenge.xxxx  - the domain's nameservers may be malfunctioning 出现了 我采用的--dns模式（要泛域名） 我使用了dig txt 验证了  都没有问题。。 我把华为云的4个dns加上都不行。。

**Comment by XuuKoo** [comment]
> 
> 
> > > > > 我也遇到了同样的问题 我的域名也是华为云的
> > > > 
> > > > 
> > > > 后来经过反复尝试，问题应该是华为的dns在海外访问困难。
> > > > 后来发现 把华为四个dns服务器全部填在域名里，大概率不会出问题。
> > > 
> > > 
> > > ns1.huaweicloud-dns.com
> > > ns1.huaweicloud-dns.cn
> > > ns1.huaweicloud-dns.net
> > > ns1.huaweicloud-dns.org
> > > 这个四个域名 NS 和 SOA 类型 华为云默认就添加了，请指教你是添加哪个类型的记录？
> > 
> > 
> > 就是把这四个加到域名提供商的nameserver里面。
> > 另外你是不是套了cf？
> 
> error:During secondary validation: DNS problem: SERVFAIL looking up TXT for _acme-challenge.xxxx - the domain's nameservers may be malfunctioning 出现了 我采用的--dns模式（要泛域名） 我使用了dig txt 验证了 都没有问题。。 我把华为云的4个dns加上都不行。。

你把你要申请证书的域名添加一下CAA记录呢：0 issuewild "letsencrypt.org"

**Comment by antsbean** [comment]
> > > > > > 我也遇到了同样的问题 我的域名也是华为云的
> > > > > 
> > > > > 
> > > > > 后来经过反复尝试，问题应该是华为的dns在海外访问困难。
> > > > > 后来发现 把华为四个dns服务器全部填在域名里，大概率不会出问题。
> > > > 
> > > > 
> > > > ns1.huaweicloud-dns.com
> > > > ns1.huaweicloud-dns.cn
> > > > ns1.huaweicloud-dns.net
> > > > ns1.huaweicloud-dns.org
> > > > 这个四个域名 NS 和 SOA 类型 华为云默认就添加了，请指教你是添加哪个类型的记录？
> > > 
> > > 
> > > 就是把这四个加到域名提供商的nameserver里面。
> > > 另外你是不是套了cf？
> > 
> > 
> > error:During secondary validation: DNS problem: SERVFAIL looking up TXT for _acme-challenge.xxxx - the domain's nameservers may be malfunctioning 出现了 我采用的--dns模式（要泛域名） 我使用了dig txt 验证了 都没有问题。。 我把华为云的4个dns加上都不行。。
> 
> 你把你要申请证书的域名添加一下CAA记录呢：0 issuewild "letsencrypt.org"

我通过 dig xxx.com caa  

显示 	3	IN	CAA	0 issuewild "letsencrypt.org" 
说明生效了，但是 我执行xxx.com  renew 的时候 出现了 caa找不到的问题 
xxx.om:Verify error:DNS problem: SERVFAIL looking up CAA for  xxx.com - the domain's nameservers may be malfunctioning

**Comment by antsbean** [comment]
我提交工单给华为云,他们反馈说的是的  产品上还需要完善下就够解决问题，  我把dns 解析切换到 dnspod就好了。 希望对各位有帮助。

**Comment by XuuKoo** [comment]
> 
> 
> 我提交工单给华为云,他们反馈说的是的 产品上还需要完善下就够解决问题， 我把dns 解析切换到 dnspod就好了。 希望对各位有帮助。

果然还是华为云那边的问题。给我的感觉就是不太稳定，时好时坏。

**Comment by Neilpang** [comment]
原因是因为华为的全球dns 刷新不及时.    letsencrypt 会在全球的不同地方校验dns, 以确保安全.
解决办法是 `--dnssleep 300`  给一个 足够长的时间等待华为刷新.

**Comment by xieke12** [comment]
我最终是将域名dns 解析切换到 阿里云，申请完证书再切回来。

**Comment by antsbean** [comment]
> 原因是因为华为的全球dns 刷新不及时. letsencrypt 会在全球的不同地方校验dns, 以确保安全.
> 解决办法是 `--dnssleep 300` 给一个 足够长的时间等待华为刷新.

不是这个问题，是大小写校验的问题。 

我起初也觉得是这样子导致的，后来 我等了很久还是不行。。

**Comment by antsbean** [comment]
> 我最终是将域名dns 解析切换到 阿里云，申请完证书再切回来。

我也是这样子玩的。。 哈哈

**Comment by xuzhzz** [comment]
> > 我最终是将域名dns 解析切换到 阿里云，申请完证书再切回来。
> 
> 我也是这样子玩的。。 哈哈

请问切换到阿里云解析的具体方式是在华为云解析ns记录上把华为那四个dns服务器改为ns1.aliyun.com ns2.aliyun.com这两个吗？还是有别的地址是需要自己去申请？
