### ISSUE TITLE
Where does acme.sh stores the parameters for certificate renewal?

### ISSUE THREAD

**Issue by Tronde** [acmesh-official/acme.sh#2995]
> No,
> 
> the parameters are saved automatically, and will be reused when renewal automatically.

Do you know the place where the parameters are saved? I grep-ed everywhere but can't find them.

_Originally posted by @liujunhui74 in https://github.com/acmesh-official/acme.sh/issues/1091#issuecomment-645917347_

**Comment by liujunhui74** [comment]
I've found the parameters. The reload command was saved in your.domain.conf with base64 encode. That's why I can't find it with grep.

**Comment by Tronde** [comment]
Ok. I guess your question is answered then and we can close this one.

**Comment by Madoshakalaka** [comment]
to anyone curious, it is stored at `/root/.acme.sh/yourdomain.com/youdomain.conf`
The field name is Le_ReloadCmd=, you should take the middle part of the encoding and decode it.

**Comment by Neilpang** [comment]
There is a new command `--info` to show the parameters:

```
acme.sh  --upgrade

acme.sh  --info  -d  yourdomain.com
```
