### ISSUE TITLE
Please an an option to disable DNS update check by acme.sh

### ISSUE THREAD

**Issue by aloopkin** [acmesh-official/acme.sh#3003]
acme.sh currently checks whether the DNS TXT record has been correctly published using either google or cloudflare.

Unfortunately, that breaks all the cases where acme.sh is used on a private network, connected to a private DNS (that is, not Let's Encrypt enrollment, obviously).

Would it be possible to add an option to disable the call to _check_dns_entries ?

**Comment by aloopkin** [comment]
Logs file will be useless for the present bug report, hence not provided.

**Comment by Neilpang** [comment]
add `--dnssleep 120` option,  it will disable dns check.

**Comment by aloopkin** [comment]
Sorry to reopen, but making the enrollment very slow is not an acceptable work-around. Especially that on a private network DNS is propagated way faster than on the internet.
