### ISSUE TITLE
--dns_cf per certificate account.conf instead of global account.conf

### ISSUE THREAD

**Issue by qnxor** [acmesh-official/acme.sh#3026]
Just used the lastest acme.sh and successfully got a wildcard cert with CF DNS. However, CF now uses API tokens and I have multiple domains. by default acme.sh saves tokens in account.conf, which would get overridden. I noticed the --accountconf option. acme.sh also tries to automate cron jobs for renewals but currently these clash with each other due to needing different API tokens. Is there an elegant way to solve this or do I need to manually create/edit the cron jobs to use correct API tokens for each?

**Comment by Neilpang** [comment]
just use `--accountconf` for every command you use.

```
acme.sh  --accountconf  /path/to/new/conf    --issue -d xxxx  ........

acme.sh --accountconf  --cron
```

**Comment by qnxor** [comment]
Yeah, that's one workaround for the moment that I'm already using (not fond of it). --cron doesn't seem like a good idea here as it would try to renew all domains but only one will go through. Might do a PR to move all this to domain.conf where it all belongs, really.
