### ISSUE TITLE
About the guide of parameter --home 

### ISSUE THREAD

**Issue by railzy** [acmesh-official/acme.sh#3027]
I found that I should set --home in all steps if I want to install and use acme.sh in a customized dir. But it is not mentioned in Wiki pages.
I think it would better to add more descriptions to notice that. Thanks.

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh/wiki/How-to-install#4-advanced-installation

>> I should set --home in all steps if I want to install

no.  just use it when your first install it.  and then close and reopen your terminal.

**Comment by railzy** [comment]
> https://github.com/acmesh-official/acme.sh/wiki/How-to-install#4-advanced-installation
> 
> > > I should set --home in all steps if I want to install
> 
> no. just use it when your first install it. and then close and reopen your terminal.

I have tried reopen my terminal. Maybe it just doesn't work in Padavan?
