### ISSUE TITLE
How to use signcsr with manual DNS?

### ISSUE THREAD

**Issue by licaon-kter** [acmesh-official/acme.sh#3030]
`./acme.sh --signcsr --csr mycsr.txt --dns --yes-I-know-dns-manual-mode-enough-go-ahead-please`
or
`./acme.sh --renew --signcsr --csr mycsr.txt --dns --yes-I-know-dns-manual-mode-enough-go-ahead-please`
yield
```
Add the following TXT record:
Domain: '_acme-challenge.sub.mydomain.tld'
TXT value: 'ThisIsMyTxtValueThisIsMyTxtValue'
Please be aware that you prepend _acme-challenge. before your domain
so the resulting subdomain will be: _acme-challenge.sub.mydomain.tld
```
...but it's there already:
```
> host -t txt _acme-challenge.sub.mydomain.tld
_acme-challenge. descriptive text "ThisIsMyTxtValueThisIsMyTxtValue"
```

**Comment by Neilpang** [comment]
dont use `acme.sh --renew --signcsr ......`.

just `acme.sh --renew ......`

**Comment by licaon-kter** [comment]
That's not an option...
```
$ ./acme.sh --renew --csr CSR.txt --dns --yes-I-know-dns-manual-mode-enough-go-ahead-please

Usage: acme.sh --renew  -d domain.com [--ecc]
```

**Comment by Neilpang** [comment]
First use `acme.sh --signcsr`

Second use `acmes.h --renew`

**Comment by licaon-kter** [comment]
Are we lost in translation?

I've already paste the output of that command.

Could you please write the full command?
