### ISSUE TITLE
letsencrypt-proxy-container?

### ISSUE THREAD

**Issue by samip5** [acmesh-official/acme.sh#3048]
Is there a proxy-companion container that has this in it already?

Similar to https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/

Related: https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/issues/216

**Comment by Neilpang** [comment]
https://github.com/Neilpang/nginx-proxy
