### ISSUE TITLE
Make the dev banch the default

### ISSUE THREAD

**Issue by szepeviktor** [acmesh-official/acme.sh#3052]
> 1. Do NOT send pull request to `master` branch.
> Please send to `dev` branch instead.
> Any PR to `master` branch will NOT be merged.

Please help contributors by making the `dev` branch the default here on GitHub.

**Comment by FernandoMiguel** [comment]
if you make the default branch dev, anyone checking out the project and not specifying a branch , will download dev, instead of a stable master .

**Comment by szepeviktor** [comment]
Yes. Developers should work on the dev branch shouldn't they?

**Comment by szepeviktor** [comment]
AFAIK auto-install script should be modified: https://github.com/acmesh-official/get.acme.sh/blob/master/index.html#L21

**Comment by FernandoMiguel** [comment]
not only devs clone this project.
many people clone just to install and run

**Comment by szepeviktor** [comment]
I see.
We have to tolerate non-professional.
