### ISSUE TITLE
求助部署双证书到docker容器中

### ISSUE THREAD

**Issue by zhuwenbing** [acmesh-official/acme.sh#3060]
最近用上了acme.sh的docker容器，使用中遇到了更新证书后需要重启nginx服务（同样docker化了）的问题，也通过以下wiki找到了解决办法：
https://github.com/Neilpang/acme.sh/wiki/deploy-to-docker-containers
但是文章中指明需要配置具体的证书文件而不是目录，如DEPLOY_DOCKER_CONTAINER_CERT_FILE="/etc/nginx/ssl/example.com/cert.pem"。
但是我使用的是双证书（ECC+RSA），找遍了所有issues也没有发现相关用法，特来求助。
谢谢！

**Comment by Neilpang** [comment]
抱歉, 目前的部署是基于证书的. 一个证书部署一次.
ECC 和 RSA 被视为两个独立的证书, 所以无法一次部署两个.

目前的解决办法是, 使用两个容易来申请/部署 证书. 一个 RSA, 一个 ECC

**Comment by zhuwenbing** [comment]
感谢回复！
下来又仔细阅读了wiki文档，为了减少容器数量（还是使用一个容器生成ECC和RSA证书，然后拷贝证书到nginx的volume下），最终还是采取了文档中设置label的方法来重启nginx容器，其中去除了证书路径设置，如下
```bash
$ docker exec \
-e DEPLOY_DOCKER_CONTAINER_LABEL=sh.acme.autoload.domain=example.com \
-e DEPLOY_DOCKER_CONTAINER_RELOAD_CMD="service nginx force-reload" \
acme.sh --deploy -d example.com -d *.example.com --deploy-hook docker
[Thu Jul 16 15:20:07 HKT 2020] Container id: de7e1f26592e3b5cdf1d07b4e4c16e1b5446019fd092a3bbac8d0b235b509366
[Thu Jul 16 15:20:07 HKT 2020] Reloading: service nginx force-reload
[Thu Jul 16 15:20:07 HKT 2020] Success
```
以上理论上就可以达到重启nginx容器而又不用复制证书到容器中的目的。
就日志输出来看似乎是成功重启了nginx容器。
再次感叹acme.sh的强大。
下来再观察看看。
