### ISSUE TITLE
"stable" branch with latest release version for --upgrade --branch

### ISSUE THREAD

**Issue by Tatsu-Kishi** [acmesh-official/acme.sh#3062]
Right now there is no way to automatically upgrade only to stable releases - the default is master branch (which at this moment has failing builds) or feature/dev branches.

A "stable" branch that is automagically updated on tagged releases would be awesome so people who are concerned about stability but want to use the latest release (but not master) don't have to manually update with each release or write their own updater based on github releases.

**Comment by chk1** [comment]
I noticed the same today, I upgraded today and received version `v3.0.0`, latest release is `v2.9.0`.

I found this duplicate bug from 2018, this is the intended behaviour: https://github.com/acmesh-official/acme.sh/issues/1162#issuecomment-355748405

One comment mentions that you could use a tag as the branch, either via `BRANCH` environment variable. The [documentation](https://github.com/acmesh-official/acme.sh/wiki/Options-and-Params) mentions a `-b / --branch` command line too. That tag has to be looked up manually every time.
