### ISSUE TITLE
设置邮件通知失败

### ISSUE THREAD

**Issue by midsmr** [acmesh-official/acme.sh#3076]
Steps to reproduce
------------------

Debug log
-----------------
已经输入过
export MAIL_FROM="midsmr@qq.com"
export MAIL_TO="midsmr@qq.com"
![1](https://user-images.githubusercontent.com/61633355/88664353-8b4cc400-d10f-11ea-89e9-0995c811d56f.png)
![2](https://user-images.githubusercontent.com/61633355/88664386-930c6880-d10f-11ea-9c56-78283a486f8b.png)

**Comment by Neilpang** [comment]
你本地的 sendmail 程序并没有正常工作.
