### ISSUE TITLE
TXT record entry not escaped properly

### ISSUE THREAD

**Issue by bviktor** [acmesh-official/acme.sh#3077]
Using latest Git version, if the TXT entry starts with something really obscure like `-K...`, it produces the following error:

```
[Thu Jul 30 14:53:51 CEST 2020] Removing txt: -KJ6lT5kz-tro2j4Lhp5q3tpPCCgYhmsJCn2e6_63H4 for domain: _acme-challenge.foobar.com
grep: invalid option -- 'K'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
[Thu Jul 30 14:53:54 CEST 2020] validation record removed
[Thu Jul 30 14:53:54 CEST 2020] Removed: Success
```

**Comment by Neilpang** [comment]
please also provide the log with --debug 2

**Comment by bviktor** [comment]
Since the records are auto-generated, I can't.

**Comment by waldner** [comment]
I don't think detailed logs are necessary here, the error message from grep is quite clear, it should be probably be invoked with `grep --` to avoid considering the leadng `-` of a challenge contents as an option to grep.

**Comment by Neilpang** [comment]
are you using dns_azure ?

**Comment by Neilpang** [comment]
please try again with latest "dev" branch.
```
acme.sh  --upgrade  -b dev
```

**Comment by waldner** [comment]
> are you using dns_azure ?

Don't know about the OP, but for me it happened with HE_dns as well. I think the fix is the right one. I updated to the latest version, but of course it can't be tried until a random TXT validation value is generated that starts with a "-". Thanks

**Comment by waldner** [comment]
This is still happening in the latest docker image `neilpang/acme.sh`.
