### ISSUE TITLE
cf,tk,gq等免费域名无法在Cloudflare上自动更新证书问题

### ISSUE THREAD

**Issue by renweikg** [acmesh-official/acme.sh#3083]
发现证书过期，于是我强制手动更新证书时，提示无法添加TXT记录，与DNS API申请证书的反馈一样。。。这说明什么问题呀？怎么解决？

**Comment by Neilpang** [comment]
cloudflare 不支持 免费域名.
这个问题我要解释一百遍吗. 每个人上来就问.
