### ISSUE TITLE
Failed to add txt info to new domain which is on CloudFlare

### ISSUE THREAD

**Issue by LeoChen008** [acmesh-official/acme.sh#3084]
I try to certify my own domain where is on CloudFlare by using acme.sh, but it failed to add txt to a new domain which is "_adme_challenge.leochen007.me" . Although i have searched the solution from issues, but nothing just disappointment.The debug info is there.
------------------
[Tue Aug  4 06:11:49 UTC 2020] Running cmd: issue
[Tue Aug  4 06:11:49 UTC 2020] _main_domain='leochen007.me'
[Tue Aug  4 06:11:49 UTC 2020] _alt_domains='no'
[Tue Aug  4 06:11:49 UTC 2020] Using config home:/root/.acme.sh
[Tue Aug  4 06:11:49 UTC 2020] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Tue Aug  4 06:11:49 UTC 2020] DOMAIN_PATH='/root/.acme.sh/leochen007.me'
[Tue Aug  4 06:11:49 UTC 2020] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Tue Aug  4 06:11:49 UTC 2020] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Tue Aug  4 06:11:49 UTC 2020] GET
[Tue Aug  4 06:11:49 UTC 2020] url='https://acme-v02.api.letsencrypt.org/directory'
[Tue Aug  4 06:11:49 UTC 2020] timeout=
[Tue Aug  4 06:11:49 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Tue Aug  4 06:11:49 UTC 2020] ret='0'
[Tue Aug  4 06:11:49 UTC 2020] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Tue Aug  4 06:11:49 UTC 2020] ACME_NEW_AUTHZ
[Tue Aug  4 06:11:49 UTC 2020] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Tue Aug  4 06:11:49 UTC 2020] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Tue Aug  4 06:11:49 UTC 2020] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Tue Aug  4 06:11:49 UTC 2020] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Tue Aug  4 06:11:49 UTC 2020] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Tue Aug  4 06:11:49 UTC 2020] ACME_VERSION='2'
[Tue Aug  4 06:11:49 UTC 2020] Le_NextRenewTime
[Tue Aug  4 06:11:49 UTC 2020] _on_before_issue
[Tue Aug  4 06:11:49 UTC 2020] _chk_main_domain='leochen007.me'
[Tue Aug  4 06:11:49 UTC 2020] _chk_alt_domains
[Tue Aug  4 06:11:49 UTC 2020] Le_LocalAddress
[Tue Aug  4 06:11:49 UTC 2020] d='leochen007.me'
[Tue Aug  4 06:11:49 UTC 2020] Check for domain='leochen007.me'
[Tue Aug  4 06:11:49 UTC 2020] _currentRoot='dns_cf'
[Tue Aug  4 06:11:49 UTC 2020] d
[Tue Aug  4 06:11:49 UTC 2020] _saved_account_key_hash is not changed, skip register account.
[Tue Aug  4 06:11:49 UTC 2020] Read key length:
[Tue Aug  4 06:11:49 UTC 2020] _createcsr
[Tue Aug  4 06:11:49 UTC 2020] Single domain='leochen007.me'
[Tue Aug  4 06:11:50 UTC 2020] Getting domain auth token for each domain
[Tue Aug  4 06:11:50 UTC 2020] d
[Tue Aug  4 06:11:50 UTC 2020] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Tue Aug  4 06:11:50 UTC 2020] payload='{"identifiers": [{"type":"dns","value":"leochen007.me"}]}'
[Tue Aug  4 06:11:50 UTC 2020] RSA key
[Tue Aug  4 06:11:50 UTC 2020] HEAD
[Tue Aug  4 06:11:50 UTC 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Tue Aug  4 06:11:50 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g  -I  '
[Tue Aug  4 06:11:50 UTC 2020] _ret='0'
[Tue Aug  4 06:11:50 UTC 2020] POST
[Tue Aug  4 06:11:50 UTC 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Tue Aug  4 06:11:50 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Tue Aug  4 06:11:50 UTC 2020] _ret='0'
[Tue Aug  4 06:11:50 UTC 2020] code='201'
[Tue Aug  4 06:11:50 UTC 2020] Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/92871170/4521725161'
[Tue Aug  4 06:11:50 UTC 2020] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/92871170/4521725161'
[Tue Aug  4 06:11:50 UTC 2020] url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/6307274600'
[Tue Aug  4 06:11:50 UTC 2020] payload
[Tue Aug  4 06:11:50 UTC 2020] POST
[Tue Aug  4 06:11:50 UTC 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/6307274600'
[Tue Aug  4 06:11:50 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Tue Aug  4 06:11:50 UTC 2020] _ret='0'
[Tue Aug  4 06:11:50 UTC 2020] code='200'
[Tue Aug  4 06:11:50 UTC 2020] d='leochen007.me'
[Tue Aug  4 06:11:50 UTC 2020] Getting webroot for domain='leochen007.me'
[Tue Aug  4 06:11:50 UTC 2020] _w='dns_cf'
[Tue Aug  4 06:11:50 UTC 2020] _currentRoot='dns_cf'
[Tue Aug  4 06:11:50 UTC 2020] entry='"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/6307274600/6S2y1g","token":"6nNR_Qnwf7u97aT4opQhK80nZsubeBCXVydPXl66iEE"'
[Tue Aug  4 06:11:50 UTC 2020] token='6nNR_Qnwf7u97aT4opQhK80nZsubeBCXVydPXl66iEE'
[Tue Aug  4 06:11:50 UTC 2020] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/6307274600/6S2y1g'
[Tue Aug  4 06:11:50 UTC 2020] keyauthorization='6nNR_Qnwf7u97aT4opQhK80nZsubeBCXVydPXl66iEE.VG_awj1kFHYPF16-G-Depr8SKMTzNy4fVVZloF23fpE'
[Tue Aug  4 06:11:50 UTC 2020] dvlist='leochen007.me#6nNR_Qnwf7u97aT4opQhK80nZsubeBCXVydPXl66iEE.VG_awj1kFHYPF16-G-Depr8SKMTzNy4fVVZloF23fpE#https://acme-v02.api.letsencrypt.org/acme/chall-v3/6307274600/6S2y1g#dns-01#dns_cf'
[Tue Aug  4 06:11:50 UTC 2020] d
[Tue Aug  4 06:11:50 UTC 2020] vlist='leochen007.me#6nNR_Qnwf7u97aT4opQhK80nZsubeBCXVydPXl66iEE.VG_awj1kFHYPF16-G-Depr8SKMTzNy4fVVZloF23fpE#https://acme-v02.api.letsencrypt.org/acme/chall-v3/6307274600/6S2y1g#dns-01#dns_cf,'
[Tue Aug  4 06:11:50 UTC 2020] d='leochen007.me'
[Tue Aug  4 06:11:50 UTC 2020] _d_alias
[Tue Aug  4 06:11:50 UTC 2020] txtdomain='_acme-challenge.leochen007.me'
[Tue Aug  4 06:11:50 UTC 2020] txt='Q23rGWJLPMxG382Myo7gfoJC8mBaP3rr4v4VpfApzZQ'
[Tue Aug  4 06:11:50 UTC 2020] d_api='/root/.acme.sh/dnsapi/dns_cf.sh'
[Tue Aug  4 06:11:50 UTC 2020] Found domain api file: /root/.acme.sh/dnsapi/dns_cf.sh
[Tue Aug  4 06:11:50 UTC 2020] Adding txt value: Q23rGWJLPMxG382Myo7gfoJC8mBaP3rr4v4VpfApzZQ for domain:  _acme-challenge.leochen007.me
[Tue Aug  4 06:11:51 UTC 2020] First detect the root zone
[Tue Aug  4 06:11:51 UTC 2020] h='_acme-challenge.leochen007.me'
[Tue Aug  4 06:11:51 UTC 2020] zones?name=_acme-challenge.leochen007.me&account.id=a382ddc7365f27b2a9556aa50738bbac
[Tue Aug  4 06:11:51 UTC 2020] GET
[Tue Aug  4 06:11:51 UTC 2020] url='https://api.cloudflare.com/client/v4/zones?name=_acme-challenge.leochen007.me&account.id=a382ddc7365f27b2a9556aa50738bbac'
[Tue Aug  4 06:11:51 UTC 2020] timeout=
[Tue Aug  4 06:11:51 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Tue Aug  4 06:11:51 UTC 2020] ret='0'
[Tue Aug  4 06:11:51 UTC 2020] h='leochen007.me'
[Tue Aug  4 06:11:51 UTC 2020] zones?name=leochen007.me&account.id=a382ddc7365f27b2a9556aa50738bbac
[Tue Aug  4 06:11:51 UTC 2020] GET
[Tue Aug  4 06:11:51 UTC 2020] url='https://api.cloudflare.com/client/v4/zones?name=leochen007.me&account.id=a382ddc7365f27b2a9556aa50738bbac'
[Tue Aug  4 06:11:51 UTC 2020] timeout=
[Tue Aug  4 06:11:51 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Tue Aug  4 06:11:51 UTC 2020] ret='0'
[Tue Aug  4 06:11:51 UTC 2020] h='me'
[Tue Aug  4 06:11:51 UTC 2020] zones?name=me&account.id=a382ddc7365f27b2a9556aa50738bbac
[Tue Aug  4 06:11:51 UTC 2020] GET
[Tue Aug  4 06:11:51 UTC 2020] url='https://api.cloudflare.com/client/v4/zones?name=me&account.id=a382ddc7365f27b2a9556aa50738bbac'
[Tue Aug  4 06:11:51 UTC 2020] timeout=
[Tue Aug  4 06:11:51 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Tue Aug  4 06:11:51 UTC 2020] ret='0'
[Tue Aug  4 06:11:51 UTC 2020] h
[Tue Aug  4 06:11:51 UTC 2020] invalid domain
[Tue Aug  4 06:11:51 UTC 2020] Error add txt for domain:_acme-challenge.leochen007.me
[Tue Aug  4 06:11:51 UTC 2020] _on_issue_err
[Tue Aug  4 06:11:51 UTC 2020] Please check log file for more details: /root/.acme.sh/acme.sh.log
[Tue Aug  4 06:11:51 UTC 2020] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/6307274600/6S2y1g'
[Tue Aug  4 06:11:51 UTC 2020] payload='{}'
[Tue Aug  4 06:11:51 UTC 2020] POST
[Tue Aug  4 06:11:51 UTC 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/6307274600/6S2y1g'
[Tue Aug  4 06:11:51 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Tue Aug  4 06:11:51 UTC 2020] _ret='0'
[Tue Aug  4 06:11:51 UTC 2020] code='200'
[Tue Aug  4 06:11:51 UTC 2020] pid
[Tue Aug  4 06:11:51 UTC 2020] No need to restore nginx, skip.
[Tue Aug  4 06:11:51 UTC 2020] _clearupdns
[Tue Aug  4 06:11:51 UTC 2020] dns_entries
[Tue Aug  4 06:11:51 UTC 2020] skip dns.

-----------------

This is my command :
```
./acme.sh --issue --dns dns_cf -d leochen007.me -d www.leochen007.me --debug 2
```

**Comment by lyc0221** [comment]
我也遇到同样的问题了

**Comment by LeoChen008** [comment]
> 我也遇到同样的问题了

你解决了吗

**Comment by ally9696** [comment]
you should specify the API keys in the acme.sh folder by going to cloudflare profile and set a custom token and verify the token generated in terminal.

use updated linux if you face issues with acme.sh

alternatively you could use the swtich 

--dns \--yes-I-know-dns-manual-mode-enough-go-ahead-please _--force_

_****to manual set the dns txt records cloudflare doesn't allow free tld domain to be accesssed using API** you have to use the dashboard to set the dns records.**_

**Comment by LeoChen008** [comment]
> you should specify the API keys in the acme.sh folder by going to cloudflare profile and set a custom token and verify the token generated in terminal.
> 
> use updated linux if you face issues with acme.sh
> 
> alternatively you could use the swtich
> 
> --dns --yes-I-know-dns-manual-mode-enough-go-ahead-please _--force_
> 
> _****to manual set the dns txt records cloudflare doesn't allow free tld domain to be accesssed using API** you have to use the dashboard to set the dns records.**_

thanks for your answer, bro. I already have figured it out.
