### ISSUE TITLE
stateless 模式使用 -d 指定两个域名但是只有一个域名被识别

### ISSUE THREAD

**Issue by unknowndev233** [acmesh-official/acme.sh#3089]
Steps to reproduce
------------------
sudo su -lc "acme.sh --issue -d mirrors.3rd.vuoidoproject.org -d direct.mirrors.3rd.vuoidoproject.org --stateless --home /etc/acme.sh --debug 2"

类似上面的命令，我更换验证方式为 --standalone 或者第一个域名后跟 --nginx 第二个域名跟随 --standalone 还是只有一个域名可以可以发证书

sudo su -lc 是为了规避不能 sudo 或者必须带 --force 才可以使用 sudo 的限制（因为 --force 会强制更新证书所以不用）

Debug log
-----------------
https://fars.ee/vYmI

**Comment by Neilpang** [comment]
你的证书没有问题, 里面包含了两个域名.

**Comment by unknowndev233** [comment]
> 你的证书没有问题, 里面包含了两个域名.

只是两个证书的域名塞进了第一个域名的文件夹？
