### ISSUE TITLE
acme.sh not respecting --webroot

### ISSUE THREAD

**Issue by JABirchall** [acmesh-official/acme.sh#3094]
On 1st this month, My certficate expired, I didnt notice untill today. But when checking logs, Acme reports that it cant verify the site and is putting the .well-known in the wrong directory, and when i specify the correct directory it still puts it in the wrong one.

Steps to reproduce
------------------
Normally acme is running on a daily cron, but the command i used to try and manually renew the cert was sudo /root/.acme.sh/acme.sh --renew -d icut.co --nginx -w /data/wwwroot/icut.co/public/ --force

/data/wwwroot/icut.co/public/ is the correct directly for the website, but acme keeps trying to put the .well-know in /data/wwwroot/icut.co/ which is not publicly accessable.

Debug log
-----------------
[acme.log](https://github.com/acmesh-official/acme.sh/files/5046501/acme.log)

**Comment by Neilpang** [comment]
remove `--nginx` option.  just using `-w` is ok.
