### ISSUE TITLE
Make doh  OPTIONAL, do not force thisd crud down our throats, plz

### ISSUE THREAD

**Issue by Ressy66** [acmesh-official/acme.sh#3102]
It would be much better to have an option to en/disable doh in acme.sh file
a *LOT* of corporates block doh.
a *lot* of ISP's block doh - and no, not all to spy to users, mostly to protect them from malware and the like

doh is evil and backwards when forced upon you in most countries since it centralizes the internet, 
yes, by all means make it optional for those who live in repressed countries whos isp's do spy on them, but come on, lets be realistic here, the only ppl benefiting from doh are cloudfare and google. WHO LOG your requests ANYWAY. cloudfares initial post on it even said so, albeit for 30 days but still, thats 30 days more than any ISP most countries

**Comment by Neilpang** [comment]
add `acme.sh --issue xxxxxx    --dnssleep  300`

**Comment by Ressy66** [comment]
But this is only a workaround - my biggest problems is when its run by cron (this is how I found out its broken), can you imagine a lot of domains needing updating on a day and having to wait 5 mins each?

Great product Neil, but really, a proper fix should be made available as soon as practicable.
an over ride switch, and even with that a fallback, ie
try cloudfare 10 sec timeout try google 10 sec timeout then try local resolver 

please reconsider adding a disable doh  AND a fallback, 

I let it go for fun of it when I was trying to get around it, and for over 20 minutes until I CTL-C'd it it just loops in timeouts.

**Comment by Neilpang** [comment]
>> But this is only a workaround 

Not really.   It's not a workaround.  It's  the way to disable doh checks.

If 300 seconds is too long for you.  you can use less: `--dnssleep 120`.   

However,  how less the sleep time can be depends on how long your dns provider can propagate the dns records.

If your dns provider is fast enough.  you can even use `--dnssleep 1`.  
Some dns providers may require 20 minutes to sleep.

Normally 120 seconds is a good time to wait.

We MUST wait for the dns records to propagate before we can continue to get the cert.

I hope this  is the last time I explain. I will never explain again.

**Comment by Ressy66** [comment]
*I* am my dns provider, I've comented in hte other thread i wont repeat myself here since im wasting my time as you dismiss out of hand my request... 

bye

**Comment by Neilpang** [comment]
For anyone who sees this thread in the future.

Using `--dnssleep 120` is the way and only way to disable doh checks.

We need to know how long we have to wait before we can continue to get the cert.

We have two ways:  1.  we check dns records by doh checks.  or 2. just use a `--dnssleep 120` time.
