### ISSUE TITLE
Command to list current domain config?

### ISSUE THREAD

**Issue by kevdogg** [acmesh-official/acme.sh#3103]
Hi I was looking for a command to list current configuration of a domain.  I'm aware there is a domain.conf file located within each domains folder.  I made a change to the reload command using base64 however I'd like to know if acme is processing my base64 encoded text correctly.  It would be great if acme.sh could just dump the current config to the terminal to check.  I'm open to any suggestions on how to do this in any other manner.

**Comment by Neilpang** [comment]
please upgrade to the latest dev branch:
```
acme.sh --upgrade -b dev
```

You can use `-d` with `--list` command now:

```
acme.sh --list  -d example.com
```
