### ISSUE TITLE
[RFE] Improve clarity & consistency of config layout

### ISSUE THREAD

**Issue by lcts** [acmesh-official/acme.sh#3115]
acme.sh's configuration layout is somewhat inconsistent right now.

1. acme.sh already does a reasonable job at separating potentially sensitive from non-sensitive data, however, credentials for dnsapi and notify hooks are stored in account.conf, which also contains basic program configuration like paths that can generally be left readable by others.
2. some hooks store their credential params as `SAVED_<param>` via `_saveaccountconf_mutable()`, some as `<param>` via `_saveaccountconf()` for no immediately obvious reason.
3. `account.conf` has nothing to do with any account data, despite being named "account".
4. less of a user perspective, but why is `_saveaccountconf_mutable()` necessary?

Fixing point (1) would be especially nice, because it would allow the user to set restrictive permissions on credentials while still allowing (read) access to the general program configuration.

I'd suggest the following changes:
- use `acme.sh.conf` instead of `account.conf` as default conf file name
- introduce a new config file for credentials & associated `CREDENTIALS_CONF_PATH` variable, defaulting to `$LE_CONFIG_HOME/credentials.conf`
- change main program & hooks to save anything credentials-related to `$CREDENTIALS_CONF_PATH`, anything related to the account with the CA to `$CA_PATH/...` and everything else to `ACCOUNT_CONF_PATH` (which should probably also be renamed to `ACME_SH_CONF_PATH` or similar).

If you're interested, I'd be happy to work on a PR for this.

**Comment by lcts** [comment]
Addendum: Obviously, one would need to take care not to break existing configs, but that's doable. Still, this might be something for a 3.x release ...

**Comment by Neilpang** [comment]
I have explained thousands of times about why and how the conf files are readable.  I don't want to explain once more.
Just for short,  all the conf files are in `~/.acme.sh` folder, which is `600` by default.  No one else can read the files.

 `_saveaccountconf_mutable` is born after `_saveaccountconf`,  many early hooks are not updated yet.  We  will always use `_saveaccountconf_mutable`.

**Comment by lcts** [comment]
OK, thanks for your answer.
