### ISSUE TITLE
Security Issue - Generated private key files are world readable

### ISSUE THREAD

**Issue by Delicates** [acmesh-official/acme.sh#3127]
Latest version of acme.sh - 2.8.7

**Current Behaviour**
* `_createkey()` function generated `*.key` files are world readable with `-rw-r--r--` (0644) permissions.
* `_installcert()` function writes new keys into a world-readable `*.key` file prior to changing its permissions to `-rw-------` (0600).
* `_create_account_key()` function writes new keys into a world-readable `*.key` file prior to changing its permissions to `-rw-------` (0600).

**Security Issues**
This exposes the private keys of certificates to all processes and all users of the system.
New CA account keys are also briefly exposed when created.
This issue may warrant a CVE report.

**Expected Behaviour**
All three functions should behave as follows when writing/copying key files:
* function creates new key files with `-rw-------` (0600) permissions prior to writing/copying keys into them.
* function does not change permissions of already existing key files when updating the keys.
* function outputs and logs a coloured Warning message if the existing key file permissions are world readable:
  * Warning that the private key file is world readable by anyone on this system,
  * Recommending that user changes file permissions to `-rw-------` (0600), and
  * Recommending that user runs acme.sh commands (depends on function) to force generation of new keys.

The above behaviour should be applied to creation of the following key types:
* RSA keys generated by `_createkey()`
* ECDSA keys generated by `_createkey()`
* keys installed by `_installcert()`
* keys backed up by `_installcert()`
* keys generated by `_create_account_key()`

**Comment by xtaran** [comment]
> everything is done in LE_CONFIG_DIR, which is 0700 and thus not accessible

Nope. `acme.sh` does not seem to verify if the permissions are 0700 in case the directory already exists or is a symlink, so it is _not_ guaranteed that `$LE_CONFIG_DIR` is not accessible.

And generally: private keys need to be 0600 by default, independent where they are to avoid disclosure due to permission mistakes elsewhere. This is not really debatable but common sense.

Look at OpenSSH how pedantic they care about the private key permissions. Take that as a pattern and you're fine.

**Comment by Neilpang** [comment]
>> Nope. acme.sh does not seem to verify if the permissions are 0700 in case the directory already exists or is a symlink, so it is not guaranteed that $LE_CONFIG_DIR is not accessible.

If the dir doesn't exist,  acme.sh will create it as 700 permissions.   If we do, we do it securely.

If the dir was already created by the administrator,  we don't change the permissions,  It's the administrator's responsibility to keep the system safe.  The administrator knows more/better his system than acme.sh.  If we change the permissions to 700, it may make his system down.


>> This is supposed to be acme.sh main purpose: security and cryptographic key management.

Not really.  acme.sh is to request/issue certs/keys  from a ACME CA.  We never want to Manage the keys on the system.   We do our best to keep the keys secret.   but if the administrator sets the permission other than 700, we will respect it.

We respect the administrator more than ourselves.

We never want to give the administrator surprises to make his system down.

I explained thousands of times.

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh/wiki/how-about-the-private-key-access-modes,--chmod,-or-chown-or-umask

**Comment by Delicates** [comment]
Hi @Neilpang 

The issue is not about changing or managing permissions of existing files or directories.
I agree, existing file/directory permissions should not be touched.
The issue is about what permissions new key files are created with.

Everyone's default expectation is for any software that creates keys to save them into files with secure permissions, not with world-readable permissions.
I agree with @xtaran - it is not really debatable but common sense.

Sometimes things need to be done quick and people don't have time to read through code to sanity check things, and have to trust the software that they are using to do the right common sense thing.

Sometimes the administrator who is not yet familiar with the software just trusts in what is presented to them.

Case in point - Gentoo distribution `acme.sh` installer:
1. Creates world-readable `/etc/acme-sh` with 755 permissions,
2. Sets the following system-wide bash alias: `alias acme.sh="/usr/bin/acme.sh --config-home '/etc/acme-sh/'"`
3. Sets the following system-wide environment variables:
```
LE_WORKING_DIR="/etc/acme-sh/"
LE_CONFIG_HOME="/etc/acme-sh/"
```

This is done on installation, before anyone starts using `acme.sh`.

When used, the resulting `--install-cert` key file permissions look sane - so everyone is happy.

I'm pretty sure neither the distribution package maintainer, nor administrator expect that `acme.sh` creates and stores world-readable key files in its working directories, as they are not intimately familiar with internal workings of `acme.sh`.

**Comment by Neilpang** [comment]
Isn't this enough?

https://github.com/acmesh-official/acme.sh/blob/master/acme.sh#L6138-L6154

**Comment by Delicates** [comment]
No.
This should be done first and foremost on the key files themselves when they are created or copied.

Don't assume that your script created the folders, or that they have been created with right permissions.
Technically if permissions on the key files are right - directory permissions are not that important (as long as they are not world-writable).

In the Gentoo example above - I've been using `acme.sh` for almost a year before I spotted this problem.

**Comment by Roy-Orbison** [comment]
@Neilpang Please reopen this issue. It's not a complicated fix and system administrators _do_ expect restrictive permissions on certificate files, because every other tool is restrictive. It affects _all_ existing keys where the containing directory is not permission restricted. In this case, unprivileged users on a system can access the private key thus potentially all encrypted communication that uses it. Given the directory is configurable, it must not be relied upon for security.

**Comment by Neilpang** [comment]
The system administrators who expect this can set the the permissions of the folder for the key files to `600` manually.  And acme.sh will respect the permissions, and will not change it automatically.

**Comment by Roy-Orbison** [comment]
The point is that there is a more secure default to use, and you're choosing not to because sysadmins are _able_ to change it, even though they are unlikely to know they should. There was also a concrete example of a version from a package manager that is insecure by default because its directory doesn't have the expected restriction. It _would_ have been secure and future certificates will be if a more sensible umask were applied before creating the sensitive files.

**Comment by Neilpang** [comment]
I just made another fix that:  if the key file is created by us, we change it to `600` before we write any key content into it.
otherwise, if the key file already exists, we don't change the permissions,  the system admin may already set it to a proper value.
