### ISSUE TITLE
Zero SSL API init failed

### ISSUE THREAD

**Issue by ally9696** [acmesh-official/acme.sh#3134]
acme.sh  --register-account  --server zerossl \
        --eab-kid  5L9lcVs24mnRsqEQRsFv2MwA  \
        --eab-hmac-key  MDEjdsyfV_TO0dbhjLUkxg9acd8sdKjxfMvbdFVxQdc7hFEvEQSQVa1axydM1Zecs4sqjeiD3WixssdTYhvNwVJ-Q
#not real API keys, the real key shows logs below
[Sun Aug 30 00:06:00 IST 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 35
[Sun Aug 30 00:06:00 IST 2020] Could not get nonce, let's try again.
[Sun Aug 30 00:06:05 IST 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 35
[Sun Aug 30 00:06:06 IST 2020] Could not get nonce, let's try again.
[Sun Aug 30 00:07:35 IST 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 35
[Sun Aug 30 00:07:35 IST 2020] Can not init api.
^C
root@kali:~/acme.sh# acme.sh --set-default-ca  --server zerossl

Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

**Comment by Neilpang** [comment]
```
[Sun Aug 30 00:06:00 IST 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 35
```

**Comment by ally9696** [comment]
solved installed new linux mint instead of kali linux
