### ISSUE TITLE
URL malformed Only with Zero SSL

### ISSUE THREAD

**Issue by ally9696** [acmesh-official/acme.sh#3140]
0

**Comment by Neilpang** [comment]
please paste the log with `--debug 2`

**Comment by ally9696** [comment]
[Wednesday 02 September 2020 02:19:51 PM IST] code='200'
[Wednesday 02 September 2020 02:19:51 PM IST] original='{"type":"dns-01","url":"https://acme.zerossl.com/v2/DV90/chall/aqukQMDGqsjkeT-dCYyGrg","status":"processing","token":"-sOQhJADPwl0F4RK3MSD964WD7XVv73WcdRByYVT0UQ"}'
[Wednesday 02 September 2020 02:19:51 PM IST] response='{"type":"dns-01","url":"https://acme.zerossl.com/v2/DV90/chall/aqukQMDGqsjkeT-dCYyGrg","status":"processing","token":"-sOQhJADPwl0F4RK3MSD964WD7XVv73WcdRByYVT0UQ"}'
[Wednesday 02 September 2020 02:19:52 PM IST] trigger validation code: 200
[Wednesday 02 September 2020 02:19:52 PM IST] sleep 2 secs to verify
[Wednesday 02 September 2020 02:19:54 PM IST] checking
[Wednesday 02 September 2020 02:19:54 PM IST] url='https://acme.zerossl.com/v2/DV90/chall/aqukQMDGqsjkeT-dCYyGrg'
[Wednesday 02 September 2020 02:19:54 PM IST] payload
[Wednesday 02 September 2020 02:19:54 PM IST] Use cached jwk for file: /home/server/.acme.sh/ca/acme.zerossl.com/account.key
[Wednesday 02 September 2020 02:19:55 PM IST] Use _CACHED_NONCE='Li4a5Axi1DLDKnu4v1B16Rkn_qj7DZFSdSYYFU9Q16E'
[Wednesday 02 September 2020 02:19:55 PM IST] nonce='Li4a5Axi1DLDKnu4v1B16Rkn_qj7DZFSdSYYFU9Q16E'
[Wednesday 02 September 2020 02:19:56 PM IST] POST
[Wednesday 02 September 2020 02:19:56 PM IST] _post_url='https://acme.zerossl.com/v2/DV90/chall/aqukQMDGqsjkeT-dCYyGrg'
[Wednesday 02 September 2020 02:19:56 PM IST] body='{"protected": "eyJub25jZSI6ICJMaTRhNUF4aTFETERLbnU0djFCMTZSa25fcWo3RFpGU2RTWVlGVTlRMTZFIiwgInVybCI6ICJodHRwczovL2FjbWUuemVyb3NzbC5jb20vdjIvRFY5MC9jaGFsbC9hcXVrUU1ER3FzamtlVC1kQ1l5R3JnIiwgImFsZyI6ICJSUzI1NiIsICJraWQiOiAiaHR0cHM6Ly9hY21lLnplcm9zc2wuY29tL3YyL0RWOTAvYWNjb3VudC81TDlsY1YyNG1uUnRxRVFSRnYyTXdBIn0", "payload": "", "signature": "iWK0qUdMJcwfYPG3FZZI4glgh2o_tijoAyzUHUPR5zIBvniDG5jBCv6JFZv4yxY6tT0PsWdinS3-DCZWylKYEYcGN0MTjfZV39Vj2lnCgMdmLWt93rc-rKmsNTcGtiP7U4O2kr0KyOUMqffnto4INXwAVw55l5NgzPm5K_A67_Yb4rw7A0pS-NynyEd4TAF_t0US8b6_npAaMjDVDhjmsMzOZVitWHL7ypNGFzjKDEND87pSqBuJsyf56s3XjMdIvKeBWreORdVumqv7nPs53_lxrQW3MxXZ204RO1-NoDaiPuZTgwYGAx14vN0ax3EaV8G-aTtLORenSC20O9jjyg"}'
[Wednesday 02 September 2020 02:19:56 PM IST] _postContentType='application/jose+json'
[Wednesday 02 September 2020 02:19:56 PM IST] Http already initialized.
[Wednesday 02 September 2020 02:19:56 PM IST] _CURL='curl -L --silent --dump-header /home/server/.acme.sh/http.header  --trace-ascii /tmp/tmp.ZGXc0rmUNe  -g '
[Wednesday 02 September 2020 02:19:57 PM IST] _ret='0'
[Wednesday 02 September 2020 02:19:58 PM IST] responseHeaders='HTTP/2 200 
server: nginx
date: Wed, 02 Sep 2020 08:49:57 GMT
content-type: application/json
content-length: 193
replay-nonce: _r_ZpZhu-54dxp64Y_WKriCl52_2SwnXRZhVoNviw0A
cache-control: max-age=-1
access-control-allow-origin: *
link: <https://acme.zerossl.com/v2/DV90>;rel="index"
link: <https://acme.zerossl.com/v2/DV90/authz/7yOQit4fNlgOr10suva0tQ>;rel="up"
retry-after: 10
strict-transport-security: max-age=15552000
'
[Wednesday 02 September 2020 02:19:58 PM IST] code='200'
[Wednesday 02 September 2020 02:19:58 PM IST] original='{"type":"dns-01","url":"https://acme.zerossl.com/v2/DV90/chall/aqukQMDGqsjkeT-dCYyGrg","status":"valid","validated":"2020-09-02T08:49:50Z","token":"-sOQhJADPwl0F4RK3MSD964WD7XVv73WcdRByYVT0UQ"}'
[Wednesday 02 September 2020 02:19:59 PM IST] response='{"type":"dns-01","url":"https://acme.zerossl.com/v2/DV90/chall/aqukQMDGqsjkeT-dCYyGrg","status":"valid","validated":"2020-09-02T08:49:50Z","token":"-sOQhJADPwl0F4RK3MSD964WD7XVv73WcdRByYVT0UQ"}'
[Wednesday 02 September 2020 02:19:59 PM IST] original='{"type":"dns-01","url":"https://acme.zerossl.com/v2/DV90/chall/aqukQMDGqsjkeT-dCYyGrg","status":"valid","validated":"2020-09-02T08:49:50Z","token":"-sOQhJADPwl0F4RK3MSD964WD7XVv73WcdRByYVT0UQ"}'
[Wednesday 02 September 2020 02:19:59 PM IST] response='{"type":"dns-01","url":"https://acme.zerossl.com/v2/DV90/chall/aqukQMDGqsjkeT-dCYyGrg","status":"valid","validated":"2020-09-02T08:49:50Z","token":"-sOQhJADPwl0F4RK3MSD964WD7XVv73WcdRByYVT0UQ"}'
[Wednesday 02 September 2020 02:20:00 PM IST] Success
[Wednesday 02 September 2020 02:20:00 PM IST] pid
[Wednesday 02 September 2020 02:20:00 PM IST] Skip for removelevel:
[Wednesday 02 September 2020 02:20:00 PM IST] Verifying: *.alister.ml
[Wednesday 02 September 2020 02:20:01 PM IST] d='*.alister.ml'
[Wednesday 02 September 2020 02:20:01 PM IST] keyauthorization='VdQ7vXQWqMW-vZXD8QFEgMis5iiOGGyqsyDC1-BwVGA.DOg0os3Uq76ylELILaSVH_hAFvmQAyNp9P8-FUCBA_I'
[Wednesday 02 September 2020 02:20:01 PM IST] uri='https://acme.zerossl.com/v2/DV90/chall/7RztTS9mGG9B94BnQE_tyg'
[Wednesday 02 September 2020 02:20:01 PM IST] _currentRoot='dns'
[Wednesday 02 September 2020 02:20:01 PM IST] Trigger domain validation.
[Wednesday 02 September 2020 02:20:01 PM IST] _t_url='https://acme.zerossl.com/v2/DV90/chall/7RztTS9mGG9B94BnQE_tyg'
[Wednesday 02 September 2020 02:20:01 PM IST] _t_key_authz='VdQ7vXQWqMW-vZXD8QFEgMis5iiOGGyqsyDC1-BwVGA.DOg0os3Uq76ylELILaSVH_hAFvmQAyNp9P8-FUCBA_I'
[Wednesday 02 September 2020 02:20:01 PM IST] _t_vtype='dns-01'
[Wednesday 02 September 2020 02:20:02 PM IST] url='https://acme.zerossl.com/v2/DV90/chall/7RztTS9mGG9B94BnQE_tyg'
[Wednesday 02 September 2020 02:20:02 PM IST] payload='{}'
[Wednesday 02 September 2020 02:20:02 PM IST] Use cached jwk for file: /home/server/.acme.sh/ca/acme.zerossl.com/account.key
[Wednesday 02 September 2020 02:20:02 PM IST] Use _CACHED_NONCE='_r_ZpZhu-54dxp64Y_WKriCl52_2SwnXRZhVoNviw0A'
[Wednesday 02 September 2020 02:20:02 PM IST] nonce='_r_ZpZhu-54dxp64Y_WKriCl52_2SwnXRZhVoNviw0A'
[Wednesday 02 September 2020 02:20:03 PM IST] POST
[Wednesday 02 September 2020 02:20:03 PM IST] _post_url='https://acme.zerossl.com/v2/DV90/chall/7RztTS9mGG9B94BnQE_tyg'
[Wednesday 02 September 2020 02:20:03 PM IST] body='{"protected": "eyJub25jZSI6ICJfcl9acFpodS01NGR4cDY0WV9XS3JpQ2w1Ml8yU3duWFJaaFZvTnZpdzBBIiwgInVybCI6ICJodHRwczovL2FjbWUuemVyb3NzbC5jb20vdjIvRFY5MC9jaGFsbC83Unp0VFM5bUdHOUI5NEJuUUVfdHlnIiwgImFsZyI6ICJSUzI1NiIsICJraWQiOiAiaHR0cHM6Ly9hY21lLnplcm9zc2wuY29tL3YyL0RWOTAvYWNjb3VudC81TDlsY1YyNG1uUnRxRVFSRnYyTXdBIn0", "payload": "e30", "signature": "pWxbAlzHMXa9KtVJQhRWXTCzhVqAXcmF1IVo2o0CZd_PJ1dm1VvFQmrcDWV_2qRZEesC-PMcfbLA_8l3oct0C7O5Vvk0zMxn6KAUqqWV1z-uVhbgs4EbAFiVTwSmlSe2BrXrH-pHgRdK8wfgCCjgsQVmWl-5U4Fbk87kU_EE9CCZ0R6-Tva_wzx4uheq5nkHZBKmTmDFp7q378hCG8LPH3_2n5otEf0XbgKG2l5O9Q4UeUxe2MzRQZDmA3pZyeYpwErBqB1zNy81ajnCSMQCPyH5ZT8Kw5rmUW71VvoJd3yuZwemqpZapnJFoKDL5vpmEqwWIYrwPRPbUHW1hocsDw"}'
[Wednesday 02 September 2020 02:20:04 PM IST] _postContentType='application/jose+json'
[Wednesday 02 September 2020 02:20:04 PM IST] Http already initialized.
[Wednesday 02 September 2020 02:20:04 PM IST] _CURL='curl -L --silent --dump-header /home/server/.acme.sh/http.header  --trace-ascii /tmp/tmp.ZGXc0rmUNe  -g '
[Wednesday 02 September 2020 02:20:05 PM IST] _ret='0'
[Wednesday 02 September 2020 02:20:05 PM IST] responseHeaders='HTTP/2 200 
server: nginx
date: Wed, 02 Sep 2020 08:50:05 GMT
content-type: application/json
content-length: 163
replay-nonce: 9MEY4dUww0VL9lJPsySAi7yFe36znFW89rX1DRhoAyE
cache-control: max-age=-1
access-control-allow-origin: *
link: <https://acme.zerossl.com/v2/DV90>;rel="index"
link: <https://acme.zerossl.com/v2/DV90/authz/zByZWw6VXo1-1W9F6fm2Rg>;rel="up"
retry-after: 10
strict-transport-security: max-age=15552000
'
[Wednesday 02 September 2020 02:20:05 PM IST] code='200'
[Wednesday 02 September 2020 02:20:05 PM IST] original='{"type":"dns-01","url":"https://acme.zerossl.com/v2/DV90/chall/7RztTS9mGG9B94BnQE_tyg","status":"processing","token":"VdQ7vXQWqMW-vZXD8QFEgMis5iiOGGyqsyDC1-BwVGA"}'
[Wednesday 02 September 2020 02:20:06 PM IST] response='{"type":"dns-01","url":"https://acme.zerossl.com/v2/DV90/chall/7RztTS9mGG9B94BnQE_tyg","status":"processing","token":"VdQ7vXQWqMW-vZXD8QFEgMis5iiOGGyqsyDC1-BwVGA"}'
[Wednesday 02 September 2020 02:20:06 PM IST] trigger validation code: 200
[Wednesday 02 September 2020 02:20:06 PM IST] sleep 2 secs to verify
[Wednesday 02 September 2020 02:20:09 PM IST] checking
[Wednesday 02 September 2020 02:20:09 PM IST] url='https://acme.zerossl.com/v2/DV90/chall/7RztTS9mGG9B94BnQE_tyg'
[Wednesday 02 September 2020 02:20:09 PM IST] payload
[Wednesday 02 September 2020 02:20:09 PM IST] Use cached jwk for file: /home/server/.acme.sh/ca/acme.zerossl.com/account.key
[Wednesday 02 September 2020 02:20:09 PM IST] Use _CACHED_NONCE='9MEY4dUww0VL9lJPsySAi7yFe36znFW89rX1DRhoAyE'
[Wednesday 02 September 2020 02:20:10 PM IST] nonce='9MEY4dUww0VL9lJPsySAi7yFe36znFW89rX1DRhoAyE'
[Wednesday 02 September 2020 02:20:10 PM IST] POST
[Wednesday 02 September 2020 02:20:10 PM IST] _post_url='https://acme.zerossl.com/v2/DV90/chall/7RztTS9mGG9B94BnQE_tyg'
[Wednesday 02 September 2020 02:20:11 PM IST] body='{"protected": "eyJub25jZSI6ICI5TUVZNGRVd3cwVkw5bEpQc3lTQWk3eUZlMzZ6bkZXODlyWDFEUmhvQXlFIiwgInVybCI6ICJodHRwczovL2FjbWUuemVyb3NzbC5jb20vdjIvRFY5MC9jaGFsbC83Unp0VFM5bUdHOUI5NEJuUUVfdHlnIiwgImFsZyI6ICJSUzI1NiIsICJraWQiOiAiaHR0cHM6Ly9hY21lLnplcm9zc2wuY29tL3YyL0RWOTAvYWNjb3VudC81TDlsY1YyNG1uUnRxRVFSRnYyTXdBIn0", "payload": "", "signature": "fMklcRZLKN41FvV4xxcQWgKQUbT4D7hWG3Lyd35YRHy-CgfoFlYFlVrBkySpQIYqaIyOIfzokZGaThMhFYKXM0iGIQyoy1ff8Q61UGCCdVlgUb8D1yBBiOpDdeeijEiuup4G0LwlYAtqXpKVBNo5W8TA2sGB1AT8I1pEGq350DFPpMR7QPPvwP25iTr_PsZl3k5W55wWUcE5s0BOwD_8NaKiMS4HrsZRrBhfbB3S-mD5u0KfRntcANGWLwcAJ2Wn3wLHBesZTg3dLNFtPUAIHkgmL4e824H7kto3MC2F-WfINbfATC02moFJp9Llh4IaE6y1bB3rFneqHGfEp72ICg"}'
[Wednesday 02 September 2020 02:20:11 PM IST] _postContentType='application/jose+json'
[Wednesday 02 September 2020 02:20:11 PM IST] Http already initialized.
[Wednesday 02 September 2020 02:20:11 PM IST] _CURL='curl -L --silent --dump-header /home/server/.acme.sh/http.header  --trace-ascii /tmp/tmp.ZGXc0rmUNe  -g '
[Wednesday 02 September 2020 02:20:12 PM IST] _ret='0'
[Wednesday 02 September 2020 02:20:12 PM IST] responseHeaders='HTTP/2 200 
server: nginx
date: Wed, 02 Sep 2020 08:50:12 GMT
content-type: application/json
content-length: 193
replay-nonce: QqQT02LJVS8yvZOiCQ6z1AJG_TwimKAQLnF-NgSpnUI
cache-control: max-age=-1
access-control-allow-origin: *
link: <https://acme.zerossl.com/v2/DV90>;rel="index"
link: <https://acme.zerossl.com/v2/DV90/authz/zByZWw6VXo1-1W9F6fm2Rg>;rel="up"
retry-after: 10
strict-transport-security: max-age=15552000
'
[Wednesday 02 September 2020 02:20:13 PM IST] code='200'
[Wednesday 02 September 2020 02:20:13 PM IST] original='{"type":"dns-01","url":"https://acme.zerossl.com/v2/DV90/chall/7RztTS9mGG9B94BnQE_tyg","status":"valid","validated":"2020-09-02T08:50:05Z","token":"VdQ7vXQWqMW-vZXD8QFEgMis5iiOGGyqsyDC1-BwVGA"}'
[Wednesday 02 September 2020 02:20:13 PM IST] response='{"type":"dns-01","url":"https://acme.zerossl.com/v2/DV90/chall/7RztTS9mGG9B94BnQE_tyg","status":"valid","validated":"2020-09-02T08:50:05Z","token":"VdQ7vXQWqMW-vZXD8QFEgMis5iiOGGyqsyDC1-BwVGA"}'
[Wednesday 02 September 2020 02:20:14 PM IST] original='{"type":"dns-01","url":"https://acme.zerossl.com/v2/DV90/chall/7RztTS9mGG9B94BnQE_tyg","status":"valid","validated":"2020-09-02T08:50:05Z","token":"VdQ7vXQWqMW-vZXD8QFEgMis5iiOGGyqsyDC1-BwVGA"}'
[Wednesday 02 September 2020 02:20:14 PM IST] response='{"type":"dns-01","url":"https://acme.zerossl.com/v2/DV90/chall/7RztTS9mGG9B94BnQE_tyg","status":"valid","validated":"2020-09-02T08:50:05Z","token":"VdQ7vXQWqMW-vZXD8QFEgMis5iiOGGyqsyDC1-BwVGA"}'
[Wednesday 02 September 2020 02:20:14 PM IST] Success
[Wednesday 02 September 2020 02:20:14 PM IST] pid
[Wednesday 02 September 2020 02:20:14 PM IST] Skip for removelevel:
[Wednesday 02 September 2020 02:20:15 PM IST] pid
[Wednesday 02 September 2020 02:20:15 PM IST] No need to restore nginx, skip.
[Wednesday 02 September 2020 02:20:15 PM IST] _clearupdns
[Wednesday 02 September 2020 02:20:15 PM IST] dns_entries
[Wednesday 02 September 2020 02:20:15 PM IST] skip dns.
[Wednesday 02 September 2020 02:20:15 PM IST] Verify finished, start to sign.
[Wednesday 02 September 2020 02:20:16 PM IST] i='2'
[Wednesday 02 September 2020 02:20:16 PM IST] j='8'
[Wednesday 02 September 2020 02:20:16 PM IST] Lets finalize the order.
[Wednesday 02 September 2020 02:20:16 PM IST] Le_OrderFinalize='https://acme.zerossl.com/v2/DV90/order/8sRVMKC9MeT9gjHWyeoGPw/finalize'
[Wednesday 02 September 2020 02:20:16 PM IST] url='https://acme.zerossl.com/v2/DV90/order/8sRVMKC9MeT9gjHWyeoGPw/finalize'
[Wednesday 02 September 2020 02:20:16 PM IST] payload='{"csr": "MIIBLzCB1wIBADAWMRQwEgYDVQQDDAthbGx5OTY5Ni5tbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABNpU-R_lk3bTOtBsKGUXpA5VjyGAFzFJD1yMRs4FSAAnDHIb4oIvUASCMUw9mfFt7DyH1OeMIUTR01ic2BGPgT-gXzBdBgkqhkiG9w0BCQ4xUDBOMAsGA1UdDwQEAwIF4DA_BgNVHREEODA2ggthbGx5OTY5Ni5tbIINKi5hbGx5OTY5Ni5tbIIKYWxpc3Rlci5tbIIMKi5hbGlzdGVyLm1sMAoGCCqGSM49BAMCA0cAMEQCIHkLbOHHN5UixgPOUPYNXAT8kS-VR08TSccjxNfYgiReAiBGcPhyiRTezaNvTzaD2wYUeku_AyRgz_RK8ck_L0gxFw"}'
[Wednesday 02 September 2020 02:20:16 PM IST] Use cached jwk for file: /home/server/.acme.sh/ca/acme.zerossl.com/account.key
[Wednesday 02 September 2020 02:20:17 PM IST] Use _CACHED_NONCE='QqQT02LJVS8yvZOiCQ6z1AJG_TwimKAQLnF-NgSpnUI'
[Wednesday 02 September 2020 02:20:17 PM IST] nonce='QqQT02LJVS8yvZOiCQ6z1AJG_TwimKAQLnF-NgSpnUI'
[Wednesday 02 September 2020 02:20:18 PM IST] POST
[Wednesday 02 September 2020 02:20:18 PM IST] _post_url='https://acme.zerossl.com/v2/DV90/order/8sRVMKC9MeT9gjHWyeoGPw/finalize'
[Wednesday 02 September 2020 02:20:18 PM IST] body='{"protected": "eyJub25jZSI6ICJRcVFUMDJMSlZTOHl2Wk9pQ1E2ejFBSkdfVHdpbUtBUUxuRi1OZ1NwblVJIiwgInVybCI6ICJodHRwczovL2FjbWUuemVyb3NzbC5jb20vdjIvRFY5MC9vcmRlci84c1JWTUtDOU1lVDlnakhXeWVvR1B3L2ZpbmFsaXplIiwgImFsZyI6ICJSUzI1NiIsICJraWQiOiAiaHR0cHM6Ly9hY21lLnplcm9zc2wuY29tL3YyL0RWOTAvYWNjb3VudC81TDlsY1YyNG1uUnRxRVFSRnYyTXdBIn0", "payload": "eyJjc3IiOiAiTUlJQkx6Q0Ixd0lCQURBV01SUXdFZ1lEVlFRRERBdGhiR3g1T1RZNU5pNXRiREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCTnBVLVJfbGszYlRPdEJzS0dVWHBBNVZqeUdBRnpGSkQxeU1SczRGU0FBbkRISWI0b0l2VUFTQ01VdzltZkZ0N0R5SDFPZU1JVVRSMDFpYzJCR1BnVC1nWHpCZEJna3Foa2lHOXcwQkNRNHhVREJPTUFzR0ExVWREd1FFQXdJRjREQV9CZ05WSFJFRU9EQTJnZ3RoYkd4NU9UWTVOaTV0YklJTktpNWhiR3g1T1RZNU5pNXRiSUlLWVd4cGMzUmxjaTV0YklJTUtpNWhiR2x6ZEdWeUxtMXNNQW9HQ0NxR1NNNDlCQU1DQTBjQU1FUUNJSGtMYk9ISE41VWl4Z1BPVVBZTlhBVDhrUy1WUjA4VFNjY2p4TmZZZ2lSZUFpQkdjUGh5aVJUZXphTnZUemFEMndZVWVrdV9BeVJnel9SSzhja19MMGd4RncifQ", "signature": "ZG98lEo4N3zqtIXXi2Vy65h-T6kaN6SZ45y1u5IjMOL-k2ErCX-U3DmfCqQvQPKGNtd-2NdPJGxva13pIK3B9gGht0yBgtpVIcJqwYYNXicuds4Q2IFHxeu4uLB9TvJdn-aPKgmBMkMG7VHfmCmVPwiuoPhCzpqhqOck4v49e5VQxS5dH_Xoc_CPNHmi3F-XzdrXYBdOdHet7km5AyPIIRQCn1JMZ0Bt2nmZwzAHQP9d72Zi298MxaSI_5cwk573oZ8-TQ6GLDANpS8INDp0BLOHbVJzs-HkTNxm2XY0jOESn0sY1TnnV8MGw_k4TNt3fmbW4MHiBSjXr7E4M_6Fcg"}'
[Wednesday 02 September 2020 02:20:18 PM IST] _postContentType='application/jose+json'
[Wednesday 02 September 2020 02:20:18 PM IST] Http already initialized.
[Wednesday 02 September 2020 02:20:18 PM IST] _CURL='curl -L --silent --dump-header /home/server/.acme.sh/http.header  --trace-ascii /tmp/tmp.ZGXc0rmUNe  -g '
[Wednesday 02 September 2020 02:20:20 PM IST] _ret='0'
[Wednesday 02 September 2020 02:20:20 PM IST] responseHeaders='HTTP/2 200 
server: nginx
date: Wed, 02 Sep 2020 08:50:19 GMT
content-type: application/json
content-length: 581
status: 
replay-nonce: 75ERFDKfoKoQQHM5IgnNgIdau_2Qhm1dtJSFQBb2mEM
cache-control: max-age=-1
access-control-allow-origin: *
location: https://acme.zerossl.com/v2/DV90/order/8sRVMKC9MeT9gjHWyeoGPw
retry-after: 15
strict-transport-security: max-age=15552000
'
[Wednesday 02 September 2020 02:20:20 PM IST] code='200'
[Wednesday 02 September 2020 02:20:20 PM IST] original='{"status":"processing","expires":"2020-12-01T08:42:52Z","identifiers":[{"type":"dns","value":"ally9696.ml"},{"type":"dns","value":"*.ally9696.ml"},{"type":"dns","value":"alister.ml"},{"type":"dns","value":"*.alister.ml"}],"authorizations":["https://acme.zerossl.com/v2/DV90/authz/XgfGy_vCpn7dPDvUpRPzpQ","https://acme.zerossl.com/v2/DV90/authz/XKF7SKCelFPvHD9VhiB1VA","https://acme.zerossl.com/v2/DV90/authz/7yOQit4fNlgOr10suva0tQ","https://acme.zerossl.com/v2/DV90/authz/zByZWw6VXo1-1W9F6fm2Rg"],"finalize":"https://acme.zerossl.com/v2/DV90/order/8sRVMKC9MeT9gjHWyeoGPw/finalize"}'
[Wednesday 02 September 2020 02:20:21 PM IST] response='{"status":"processing","expires":"2020-12-01T08:42:52Z","identifiers":[{"type":"dns","value":"ally9696.ml"},{"type":"dns","value":"*.ally9696.ml"},{"type":"dns","value":"alister.ml"},{"type":"dns","value":"*.alister.ml"}],"authorizations":["https://acme.zerossl.com/v2/DV90/authz/XgfGy_vCpn7dPDvUpRPzpQ","https://acme.zerossl.com/v2/DV90/authz/XKF7SKCelFPvHD9VhiB1VA","https://acme.zerossl.com/v2/DV90/authz/7yOQit4fNlgOr10suva0tQ","https://acme.zerossl.com/v2/DV90/authz/zByZWw6VXo1-1W9F6fm2Rg"],"finalize":"https://acme.zerossl.com/v2/DV90/order/8sRVMKC9MeT9gjHWyeoGPw/finalize"}'
[Wednesday 02 September 2020 02:20:21 PM IST] Order status is processing, lets sleep and retry.
[Wednesday 02 September 2020 02:20:22 PM IST] _retryafter='15'
[Wednesday 02 September 2020 02:20:22 PM IST] Retry after: 15
[Wednesday 02 September 2020 02:20:39 PM IST] Polling order status:  https://acme.zerossl.com/v2/DV90/order/mjP2ixlWw3Jp9NN78pTgaQ
[Wednesday 02 September 2020 02:20:39 PM IST] url=' https://acme.zerossl.com/v2/DV90/order/mjP2ixlWw3Jp9NN78pTgaQ'
[Wednesday 02 September 2020 02:20:40 PM IST] payload
[Wednesday 02 September 2020 02:20:40 PM IST] Use cached jwk for file: /home/server/.acme.sh/ca/acme.zerossl.com/account.key
[Wednesday 02 September 2020 02:20:40 PM IST] Use _CACHED_NONCE='75ERFDKfoKoQQHM5IgnNgIdau_2Qhm1dtJSFQBb2mEM'
[Wednesday 02 September 2020 02:20:40 PM IST] nonce='75ERFDKfoKoQQHM5IgnNgIdau_2Qhm1dtJSFQBb2mEM'
[Wednesday 02 September 2020 02:20:41 PM IST] POST
[Wednesday 02 September 2020 02:20:41 PM IST] _post_url=' https://acme.zerossl.com/v2/DV90/order/mjP2ixlWw3Jp9NN78pTgaQ'
[Wednesday 02 September 2020 02:20:41 PM IST] body='{"protected": "eyJub25jZSI6ICI3NUVSRkRLZm9Lb1FRSE01SWduTmdJZGF1XzJRaG0xZHRKU0ZRQmIybUVNIiwgInVybCI6ICIgaHR0cHM6Ly9hY21lLnplcm9zc2wuY29tL3YyL0RWOTAvb3JkZXIvbWpQMml4bFd3M0pwOU5ONzhwVGdhUSIsICJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS56ZXJvc3NsLmNvbS92Mi9EVjkwL2FjY291bnQvNUw5bGNWMjRtblJ0cUVRUkZ2Mk13QSJ9", "payload": "", "signature": "CQtl_MK_Z2QAbw65nygzNvCKBh-KiJ86DOaYEZD-MNAb3cDCl33lLR5cwJXg9sdu3xUSLeWEK9vOoU_V-rEVKWyvfL13NDSaoKH08igWXb9UdBSZMfJTqaJ6Yv3JTc8DGMAOogCyLoWs4Fd7S7CyiRodL2uZWhbh6NP37lZ-VFGpL18FNwq2mussvXcK-p8YKRmqsBOOLrhAocW8mtzew-SHbe-88QijUu4wRyigCalPEtM5Zo2qPUfNRjS-U41PoN7kc_SHTXDPenT31nNdiMHKf8mT6B1AuX3wuHQdI83SICrfzbWWAtXfp5KrsgNCfzstkyuy3u9v4PNfj3G7qQ"}'
[Wednesday 02 September 2020 02:20:41 PM IST] _postContentType='application/jose+json'
[Wednesday 02 September 2020 02:20:42 PM IST] Http already initialized.
[Wednesday 02 September 2020 02:20:42 PM IST] _CURL='curl -L --silent --dump-header /home/server/.acme.sh/http.header  --trace-ascii /tmp/tmp.ZGXc0rmUNe  -g '
[Wednesday 02 September 2020 02:20:42 PM IST] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 3
[Wednesday 02 September 2020 02:20:42 PM IST] Here is the curl dump log:
[Wednesday 02 September 2020 02:20:42 PM IST] == Info: Closing connection -1
[Wednesday 02 September 2020 02:20:42 PM IST] _ret='3'
[Wednesday 02 September 2020 02:20:42 PM IST] responseHeaders
[Wednesday 02 September 2020 02:20:43 PM IST] code
[Wednesday 02 September 2020 02:20:43 PM IST] original
[Wednesday 02 September 2020 02:20:43 PM IST] response
[Wednesday 02 September 2020 02:20:44 PM IST] Sign error, wrong status
[Wednesday 02 September 2020 02:20:44 PM IST] 
[Wednesday 02 September 2020 02:20:44 PM IST] _on_issue_err
[Wednesday 02 September 2020 02:20:44 PM IST] Please add '--debug' or '--log' to check more details.
[Wednesday 02 September 2020 02:20:44 PM IST] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Wednesday 02 September 2020 02:20:44 PM IST] _chk_vlist
[Wednesday 02 September 2020 02:20:44 PM IST] 'dns' contains 'dns'
[Wednesday 02 September 2020 02:20:45 PM IST] The dns manual mode can not renew automatically, you must issue it again manually. You'd better use the other modes instead.
[Wednesday 02 September 2020 02:20:45 PM IST] socat doesn't exist.
[Wednesday 02 September 2020 02:20:45 PM IST] Diagnosis versions: 
openssl:openssl
OpenSSL 1.1.1f  31 Mar 2020
apache:
apache doesn't exist.
nginx:
nginx doesn't exist.
socat:

**Comment by Neilpang** [comment]
please try  again with `dev` branch.

```
acme.sh  --upgrade  -b dev
```

**Comment by ally9696** [comment]
**_It worked the Dev branch_**

**Comment by ally9696** [comment]
the default CA --server once changed it doesnt change with other CA

I have to delete the config files in the install dir and then use the --server change the CA

it happens when the --server CA change and sign csr then it uses the previous CA instead of new default CA

**Comment by Neilpang** [comment]
>> when i change the CA stagging to Prod then it still uses the stagging CA insead of prod CA.

how did you do that?

**Comment by ally9696** [comment]
no i'm was initially using lets encrypt and reached rate limit, later switched to stagging, Currently i'm using ZeroSSL its unlimited and free if using their ACME partner.

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh/wiki/Server
https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA
