### ISSUE TITLE
#Preferred Chain is Not Working

### ISSUE THREAD

**Issue by ishidakannan** [acmesh-official/acme.sh#3142]
Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --preferred-chain
```
I couldn't change my certificate with using the --preferrred-chain
acme.sh  --issue -d .... -w ....    --server letsencrypt --preferred-chain  "Fake LE Root X1" --force
When i'm tying to update the certificate with the above command, I'm getting the certificate renewal message instead of changing.

**Comment by ally9696** [comment]
change the Default CA to these any one values below
LetsEncrypt.org_test
,letsencrypt_test
,letsencrypttest

**Comment by Neilpang** [comment]
```
acme.sh --issue -d .... -w .... --server       letsencrypttest              --preferred-chain "Fake LE Root X1" --force
```

**Comment by ishidakannan** [comment]
Hi All,
Still, I'm facing the same issue, I couldnt change the certificate as "Fake LE Root X1". I have attached the screenshot here for your reference.

1. acme.sh --issue -d .... -w ....  --server letsencrypttest  --preferred-chain "Fake LE Root X1" --force --log "/home/.../file.log"

2. acme.sh --issue -d .... -w ....  --server LetsEncrypt.org_test  --preferred-chain "Fake LE Root X1" --force --log "/home/.../file.log"

![image](https://user-images.githubusercontent.com/69942845/92076242-2ca4f500-edf5-11ea-9351-c31d3c566fbf.png)

**Comment by ally9696** [comment]
goto the /.acme.sh/ DIR and delete the Config files that were created and copy the CSR and Private key, and try again it will definately work!

Reuse the Already CSR by Sign CSR switch to prevent new CSR/private key being generated.

**Comment by ishidakannan** [comment]
@ally9696 Thanks, 
I could find the ca file but not config file inside .acme.sh folder
![image](https://user-images.githubusercontent.com/69942845/92202100-27a97980-eeb9-11ea-8e5d-5c49f316258d.png)

**Comment by ishidakannan** [comment]
Hi All,
I've deleted the config files and then generate it again but still I'm facing the same issue.

**Comment by ishidakannan** [comment]
Hi All,
Finally i found the issue and done it. Thanks for helping.
Actually i didnt installed the downloaded certificates in my root Dir. Now its working fine.
