### ISSUE TITLE
部分域名强制更新之后无法完成copy这个步骤

### ISSUE THREAD

**Issue by chaihongjun** [acmesh-official/acme.sh#3144]
一台服务器有N个域名网站，由于，昨天发现其中一个网站的证书刚好到期了，而其他的还有效，为了统一更新就：

` 
"/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" --force
`
更新是完成了。然后再去刷新页面，发现那个网站依然是证书过期。
于是，我去证书目录看文件的修改时间，发现生成的证书时间是最新的，而使用证书的目录里面的证书文件修改时间是旧的，也就是说生成的新文件没有复制过去，于是，我手动复制过去。然后重启了nginx。
最后再刷新页面发现证书已经OK了。
想问一问，为什么会发生这样的问题，怎么排障？

**Comment by Neilpang** [comment]
首先你不用全部更行， 只需要更新指定一个就可以le 。

先看 cronjob

```
crontab -l
```

然后再检查过期的证书的配置文件：

```
cat   ~/.acme.sh/domain.tld/domain.tld.conf
```

然后执行更新证书并输出log

```
acme.sh  --renew  -d  domain.tld      --debug 2   --force
```

**Comment by chaihongjun** [comment]
> domain.tld

好的，如果下次再遇到这个情况，我试一试。谢谢！！！！
