### ISSUE TITLE
Verification on exit codes needed

### ISSUE THREAD

**Issue by UlfbertWusel** [acmesh-official/acme.sh#3145]
Hi everybody,

I am using your fabulous script as part of an automated certificate request and deployment system and I would like to get some verification on existing exit coded and their meaning.
Through testing I have encountered the following exit codes, please let me know if I missed any or if my interpretation is lacking or wrong:

Exit code 0:    certificate request successful
Exit code 1:    certificate request unsuccessful
Exit code 2:    certificate still valid, request skipped

May I also suggest that you add an entry about existing exit codes to your documentation, in case they ever change?

Thank you in advance.

**Comment by Neilpang** [comment]
Yes, you are totally correct.
We currently have three exit codes: 0, 1 and 2.

You can add a wik page here: 
https://github.com/acmesh-official/acme.sh/wiki

**Comment by UlfbertWusel** [comment]
Thank you for your confirmation.
I created a short wiki entry for anyone else who wants to use exit codes:
https://github.com/acmesh-official/acme.sh/wiki/Exit-Codes
