### ISSUE TITLE
That --cert-home, --config-home and --home are honoured and used in that order for placement for certificates.

### ISSUE THREAD

**Issue by samkatakouzinos** [acmesh-official/acme.sh#3153]
# ISSUE: 
That even after command-line install specifications, domains and certificates are still placed under ~/.acme.sh.

# EXPECTATION: 
That domains and certificates configs are located under --config-home, --cert-home and --home respectively.

# STEPS:

```sh
# change folder
cd /jffs/addons

# git project
git clone https://github.com/acmesh-official/acme.sh.git

# install project and options explicitly to different folders
cd acme.sh
./acme.sh --install --home /jffs/addons/.acme.sh --config-home /jffs/addons/.acme.sh/conf
ig --cert-home /jffs/addons/.acme.sh/cert

# Cloudflare API credentials used by Certbot
export CF_Email="xxxx@yyyy.com"
export CF_Key="xxxx"

# acme issue cert
acme.sh --issue --dns dns_cf -d xxxx.yyyy.zzzz
```
Output: 

[Sat Sep  5 15:46:02 UTC 2020] Single domain='xxxx.yyyy.zzzz'
[Sat Sep  5 15:46:03 UTC 2020] Getting domain auth token for each domain
[Sat Sep  5 15:46:10 UTC 2020] Getting webroot for domain='xxxx.yyyy.zzzz'
[Sat Sep  5 15:46:12 UTC 2020] Can not find dns api hook for: dns_cf
[Sat Sep  5 15:46:12 UTC 2020] You need to add the txt record manually.
[Sat Sep  5 15:46:12 UTC 2020] Add the following TXT record:
[Sat Sep  5 15:46:12 UTC 2020] Domain: '_acme-challenge.xxxx.yyyy.zzzz'
[Sat Sep  5 15:46:12 UTC 2020] TXT value: 'quertyytrewq'
[Sat Sep  5 15:46:12 UTC 2020] Please be aware that you prepend _acme-challenge. before your domain
[Sat Sep  5 15:46:12 UTC 2020] so the resulting subdomain will be: _acme-challenge.xxxx.yyyy.zzzz
[Sat Sep  5 15:46:12 UTC 2020] Please add the TXT records to the domains, and re-run with --renew.
[Sat Sep  5 15:46:12 UTC 2020] Please add '--debug' or '--log' to check more details.
[Sat Sep  5 15:46:12 UTC 2020] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

Reissue after correction: 

acme.sh --renew --dns dns_cf -d xxxx.yyyy.zzzz
[Sat Sep  5 16:16:49 UTC 2020] Renew: 'xxxx.yyyy.zzzz'
[Sat Sep  5 16:16:54 UTC 2020] Single domain='xxxx.yyyy.zzzz'
[Sat Sep  5 16:16:54 UTC 2020] Getting domain auth token for each domain
[Sat Sep  5 16:16:55 UTC 2020] Verifying: xxxx.yyyy.zzzz
[Sat Sep  5 16:17:04 UTC 2020] Success
[Sat Sep  5 16:17:04 UTC 2020] Verify finished, start to sign.
[Sat Sep  5 16:17:04 UTC 2020] Lets finalize the order, Le_OrderFinalize: https://acme-v02.api.letsencrypt.org/acme/finalize/qwertyytrewq
[Sat Sep  5 16:17:07 UTC 2020] Download cert, Le_LinkCert: https://acme-v02.api.letsencrypt.org/acme/cert/qwertyytrewq
[Sat Sep  5 16:17:09 UTC 2020] Cert success.
-----BEGIN CERTIFICATE-----
quertyytrewq
-----END CERTIFICATE-----
[Sat Sep  5 16:17:09 UTC 2020] Your cert is in  /root/.acme.sh/xxxx.yyyy.zzzz/xxxx.yyyy.zzzz.cer
[Sat Sep  5 16:17:10 UTC 2020] Your cert key is in  /root/.acme.sh/xxxx.yyyy.zzzz/xxxx.yyyy.zzzz.key
[Sat Sep  5 16:17:10 UTC 2020] The intermediate CA cert is in  /root/.acme.sh/xxxx.yyyy.zzzz/ca.cer
[Sat Sep  5 16:17:10 UTC 2020] And the full chain certs is there:  /root/.acme.sh/xxxx.yyyy.zzzz/fullchain.cer

# RESULTS:

New content resides under /jffs/addons/.acme.sh/config
File: account.conf, with content;
#LOG_FILE="/jffs/addons/.acme.sh/config/acme.sh.log"
#LOG_LEVEL=1
#AUTO_UPGRADE="1"
#NO_TIMESTAMP=1    
CERT_HOME='/jffs/addons/.acme.sh/cert'

New content resides under ~/.acme.sh;
Folder: xxxx.yyyy.zzzz
Folder: ca
File: account.conf
File: http.header

No content at /jffs/addons/.acme.sh/cert
No such folder exists

# OBSERVATIONS:

It seems that --cert-home is not honoured, that it is ignored. 
Certificates are still places under the ~/.acme.sh folder.

# REQUESTS:

That --cert-home and --config-home and --home are honoured for placement for certificates.
That --cert-home, --config-home and --home are used in that order for placement for certificates.
  
  
  
— Regards, Sam Katakouzinos

**Comment by ally9696** [comment]
`Certificates are generated once, Its not necessary to point out minor issue. tool is made with hardwork by the developer. You could donate to developer to support minor work.`

**Comment by Neilpang** [comment]
It seems that you are running on a Router, right?
If you specified a customized --cert-home, and you are not using bash,  you need to add `--cert-home` paramter to `--issue` command.
example:

```
acme.sh  --issue  --cert-home xxxxxx   -d xxxxxx
```

**Comment by samkatakouzinos** [comment]
My router = ASUS RT-AC68U. 
It has bash. 
It runs scripts daily. 

/jffs/addons/.acme.sh/config/account.conf contains the correct --cert-home folder path.
CERT_HOME='/jffs/addons/.acme.sh/cert'

Your response claims the ```--cert-home``` parameter applies to the --issue command. 
The command line does not do so
> --cert-home                       Specifies the home dir to save all the certs, only valid for '--install' command.

May you use the account.conf CERT_HOME value for future issue commands?

In other news; 
Typing acme.sh -h have me a proper listing
Typing acme.sh --help gave me this;

```
BusyBox v1.25.1 (2020-08-14 15:17:43 EDT) multi-call binary.

Usage: echo [-neE] [ARG]...

Print the specified ARGs to stdout

        -n      Suppress trailing newline
        -e      Interpret backslash escapes (i.e., \t=tab)
        -E      Don't interpret backslash escapes (default)
/usr/sbin/acme.sh: line 6987: --help: not found 
```

Is there a dependency I'm missing?

Is this possibly related?

**Comment by Neilpang** [comment]
I'm using ASUS RT-AX88u

I know you have bash on your router, but your default shell is not bash.

The CERT_HOME in account.conf is only used for bash.
Otherwise, you need to provide cert home by commandline parameter.

**Comment by 424778940z** [comment]
```
--home is a customized dir to install acme.sh in. By default, it installs into ~/.acme.sh
--config-home is a writable folder, acme.sh will write all the files(including cert/keys, configs) there. By default, it's in --home
--cert-home is a customized dir to save the certs you issue. By default, it's saved in --config-home.
--accountemail is the email used to register an account to Let's Encrypt, you will receive a renewal notice email here.
--accountkey is the file saving your account private key. By default, it's saved in --config-home.
--user-agent is the user-agent header value used to send to Let's Encrypt.
```

Above are from official wiki page https://github.com/acmesh-official/acme.sh/wiki/How-to-install
Which is clearly NOT working as descripted.
Wasted hours to figure out why my export var not working, turns out it has TWO copy of the account.conf at --home pointed location and default .acme.sh folder, and the var was stored in account.conf that is in the DEFAULT folder, which confused me for a while...

Fix this please....

**Comment by cidrbl0ck** [comment]
Was there any update to this issue?

**Comment by hamadodene** [comment]
Hi, i encured the same issue.
I solved it editing the file acme.sh.env and adding --cert-home to alias:

`alias acme.sh="/etc/acme/acme.sh --config-home '/etc/acme/conf' --home '/etc/acme' --cert-home '/etc/acme'"
`

Make sure you have this line:

`. "/acme_install_path/acme.sh.env"` in .bashrc

and finally you can do:
```
source acme.sh.env 
source .bashrc
```
