### ISSUE TITLE
DNS_OVH not working on root domain (empty subdomain)

### ISSUE THREAD

**Issue by toxic0berliner** [acmesh-official/acme.sh#3159]
Steps to reproduce
------------------

Trying to get a certificate for example.com with alternative name *.example.com
The ovh script will fail since it will try to access the url https://eu.api.ovh.com/1.0/domain/zone/com instead of https://eu.api.ovh.com/1.0/domain/zone/example.com

I managed to get certificate validation by commenting out this part and setting domain and subdomain properly : 
```
[... around line 145 ...]
#  _debug "First detect the root zone"
#  if ! _get_root "$fulldomain"; then
#    _err "invalid domain"
#    return 1
#  fi
_sub_domain=""
_domain="example.com"
  _debug _sub_domain "$_sub_domain"
  _debug _domain "$_domain"
[...]
```
So the `_get_root` function does not return properly if a root domain is passed...
Could we get that fixed ? 
I'm using this inside the acme plugin for opnSense, so I know it'll take ages to get it deployed, but I'm still interested in some help, I'm good enough to debug shell scripts, but writing clean code is something else entirely...

Thanks in advance for your kind help.

**Comment by Neilpang** [comment]
fixed.

please try with the latest `dev` branch.

```
acme.sh --upgrade -b dev
```

**Comment by toxic0berliner** [comment]
Well thanks a lot @Neilpang ! That did fix part of my issue !

It was a hassle to get it working on opnSense though, the `--upgrade` thing downloaded the latest `acme.sh` but put it in `/root/.acme.sh/`
Where as opnSense stores the main script in `/usr/local/sbin/acme.sh` and just for the lolz they keep the other scripts in `/usr/local/share/examples/acme.sh/dnsapi/dns_ovh.sh`

after a few manual file copied from /root to /usr/.... I had it working !

Now I'm up against another issue, but maybe I'm just not understanding acme quite as good as I thought.

I have my config in opnSense requesting a certificate for `example.com` with an altName `*.example.com`
acme.sh does sucessfully push 2 TXT records onto my OVH dns and waits for 120 seconds.

But after that, acme validation fails : 
`Verify error:No TXT record found at _acme-challenge.example.com`

I cannot add a subdomain `_acme-challenge` to my alt-names otherwise it fails.

I was expecting that acme.sh would play with my DNS OVH API to create whatever subdomain acme needs, put whatever txt on it... Well, do all the heavy lifting ;)
Am I missing something ?

**Comment by toxic0berliner** [comment]
To clarify, I do have a record that says *.example.com is a CNAME for example.com
I checked, and with acme-staging, it does pass validation by putting 2 TXT records on example.com and nothing on _acme-challenge.example.com.

I guess that with a CNAME in place for *.example.com. to example.com. it messes with the auto detection of the DNS Alias mode...
OpnSense offers me several choices for "DNS Alias mode" : "not using dns alias mode", or "automatic mode (uses DNS lookups)", "Domain alias mode" or "Challenge alias mode".
I have it setup on automatic...

Any input is welcome here, I'm getting lost as to why staging passes, and then validation fails in prod even though I see both TXT records beeing applied to my OVH DNS the same way in the 2 cases... I'm not changing any of my manual CNAME entires inbetween... 

Somehow when I move to prod instead of staging, the validation does not pass...

**Comment by toxic0berliner** [comment]
Well, I solved my issue, I needed to tell opnSense to use Domain alias for validation and set the domain to the root example.com since everything including _acme-challenge.example.com is a CNAME of example.com

But that sadly shows that there's stil an issue with the dns_ovh script

This time my fix is here : 
```
_get_root() {
_sub_domain=""
_domain=$1
return 0 
```

without that I had the same issue, tripping the "invalid domain" thing since it tried to acces /zone/com on my DNS OVH API.

If that helps, here is the command used by opnSense 
```
/usr/local/bin/bash /usr/local/sbin/acme.sh --force --debug --debug 2 --debug 3 --log-level 1 --dnssleep 120 --issue --days 60 --domain example.com --domain-alias example.com. --domain *.example.com --domain-alias example.com. --dns dns_ovh --home /var/etc/acme-client/home --keylength 4096 --accountconf /var/etc/acme-client/accounts/something_prod/account.conf --certpath /var/etc/acme-client/certs/something/cert.pem --keypath /var/etc/acme-client/keys/something/private.key --capath /var/etc/acme-client/certs/something/chain.pem --fullchainpath /var/etc/acme-client/certs/something/fullchain.
pem
```
As I told earlier, I did do the update -d thing you tole me to and replaced the main acme.sh script and the dns_ovh script with the one it downloaded in my /root folder.
