### ISSUE TITLE
Upgrading to api version 2

### ISSUE THREAD

**Issue by rekire** [acmesh-official/acme.sh#3172]
I'm using "le.sh" since 2016 (which is called now acme.sh). Since I had a bug in a apache config file my ssl certificate outdated. Now I tried to update the certificate and got this error:

     new-authz error: {"type":"urn:acme:error:unauthorized","detail":"Error creating new authz :: Validations for new domains are disabled in the V1 API (https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430)","status": 403}

Okay sounds easy so I made a git pull and tried it again, but it is still trying to use the api v1. How can I upgrade to v2?

**Comment by Neilpang** [comment]
please  use the latest acme.sh

I don't think le.sh can process the new API.

**Comment by rekire** [comment]
Thank you for your work at first! As said I made already a git pull, but that didn't fix the problem for me. I also run the install command. That doesn't change the config.

When I run:
```
# acme.sh -r -d my.example.tld
[Mo 14. Sep 16:08:28 CEST 2020] Renew: 'my.example.tld'
[Mo 14. Sep 16:08:33 CEST 2020] Using CA: https://acme-v01.api.letsencrypt.org
```

I guess that is still using the v1.
When I check `/root/.acme.sh/my.example.tld/my.example.tld.conf` I see there this line:

    Le_API='https://acme-v01.api.letsencrypt.org'

Which is likely the reason why v1 is used. I tried to write 2 instead of 1 but that didn't work too.

**Comment by Neilpang** [comment]
remove the conf file `/root/.acme.sh/my.example.tld/my.example.tld.conf`
and try issue again.

**Comment by rekire** [comment]
Great, that is the solution! That should be mentioned in the documentation, that the old config files should be removed.

**Comment by ProBackup-nl** [comment]
@Neilpang After remove the conf file /root/.acme.sh/my.example.tld/my.example.tld.conf
and try issue again, the result is: `'my.example.tld' is not an issued domain, skip.`
