### ISSUE TITLE
Cron syntax

### ISSUE THREAD

**Issue by kevdogg** [acmesh-official/acme.sh#3219]
I've converted the crontab entries over to systemd timer units/service files but I'm struggling on the syntax for the "cron command".

Typically the cronjob is something like:
`0 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh/" >> /var/log/letsencrypt.log`

However for some reason this command doesn't seem to be working.  What's fundamentally the difference of the syntax of the above command compared to:

`0 0 * * * "/root/.acme.sh"/acme.sh --renew -d <domain_name> >> /var/log/letsencrypt.log`

At least the way I've configured things -- which could be totally wrong -- the second command always seems to attempt a renewal whereas the first does not. 

Here is my systemd service file:
acme_letsencrypt@.service

```
[Unit]
Description=Renew Let's Encrypt certificates using acme.sh for %I
After=network-online.target

[Service]
Type=oneshot
Environment="HOME=/root/.acme.sh/"
ExecStart="/root/.acme.sh"/acme.sh --home "/root/.acme.sh" --renew --dns dns_cf -d %i --log
SuccessExitStatus=0 2
```

**Comment by Neilpang** [comment]
the syntext should be `"/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh/"`

You should only use `--cron` command in the cronjob.   Never, never use any other command as `--renew/--issue` etc.

**Comment by kevdogg** [comment]
This doesn't really answer the question however -- I'm talking specifically about the use of systemd timers, not cron.  I thought systemd timers and cron -- although similar functioned differently.

**Comment by Neilpang** [comment]
No matter it's crontab or timers,  just call the `--cron` command at lease once a day.
