### ISSUE TITLE
Syntax for systemd timers

### ISSUE THREAD

**Issue by kevdogg** [acmesh-official/acme.sh#3222]
I'm referencing the following ticket: https://github.com/acmesh-official/acme.sh/issues/3219 regarding syntax for systemd timers (not cronjobs).

> the syntax should be `"/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh/"`
> 
> You should only use `--cron` command in the cronjob.   Never, never use any other command as `--renew/--issue` etc.
> 
> _Originally posted by @Neilpang in https://github.com/acmesh-official/acme.sh/issue_comments/709966833_

Does this hold for systemd timers as well?  Using this syntax I couldn't get my systemd timer and associated system file to try to automatically renew the certificates.  

The above synxtax for my ....--cron --home would function specifically if it was implemented within a crontab file.

**Comment by Neilpang** [comment]
No matter it's crontab or timers, just call the --cron command at lease once a day.
