### ISSUE TITLE
sed: -e expression #1, char 53: Invalid preceding regular expression

### ISSUE THREAD

**Issue by LOVEChen** [acmesh-official/acme.sh#3225]
Ubuntu 20.04.1 LTS
Linux xxx 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
./acme.sh --issue --dns dns_linode_v4 --dnssleep 900 -d xxx
[Sun 18 Oct 2020 11:56:22 PM UTC] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sun 18 Oct 2020 11:56:22 PM UTC] Single domain='xxx'
[Sun 18 Oct 2020 11:56:23 PM UTC] Getting domain auth token for each domain
[Sun 18 Oct 2020 11:56:25 PM UTC] Getting webroot for domain='xxx'
[Sun 18 Oct 2020 11:56:25 PM UTC] Adding txt value:xxx for domain:  _acme-challenge.xxx
[Sun 18 Oct 2020 11:56:25 PM UTC] Using Linode
sed: -e expression #1, char 53: Invalid preceding regular expression
[Sun 18 Oct 2020 11:56:26 PM UTC] Domain resource successfully added.
[Sun 18 Oct 2020 11:56:26 PM UTC] The txt record is added: Success.
[Sun 18 Oct 2020 11:56:26 PM UTC] Sleep 900 seconds for the txt records to take effect

**Comment by dlhenke** [comment]
I have same issue here.. 

acme.sh --issue --dns dns_linode_v4 -d removed-sensitive --force --dnssleep 900
[Tue Jul 27 01:59:16 UTC 2021] Using Linode
sed: -e expression #1, char 54: Invalid preceding regular expression
[Tue Jul 27 01:59:18 UTC 2021] Domain resource successfully deleted.
[Tue Jul 27 01:59:18 UTC 2021] Removed: Success
[Tue Jul 27 01:59:18 UTC 2021] Verify finished, start to sign.
[Tue Jul 27 01:59:18 UTC 2021] Lets finalize the order.
[Tue Jul 27 01:59:18 UTC 2021] Le_OrderFinalize='https://acme.zerossl.com/v2/DV90/order-removed/finalize'
[Tue Jul 27 01:59:18 UTC 2021] Order status is processing, lets sleep and retry.
[Tue Jul 27 01:59:18 UTC 2021] Retry after: 15
[Tue Jul 27 01:59:34 UTC 2021] Polling order status: https://acme.zerossl.com/v2/DV90/order/order-removed
[Tue Jul 27 01:59:35 UTC 2021] Sign error, wrong status
[Tue Jul 27 01:59:35 UTC 2021] {"status":"invalid","expires":"2021-10-25T01:55:08Z","identifiers":[{"type":"dns","value":"domain-removed-bxxx"}],"authorizations":["https://acme.zerossl.com/v2/DV90/authz/5Tremoved-8I_1ZaMR7w"],"finalize":"https://acme.zerossl.com/v2/DV90/order/iZvg3removedg0l900Fw0A/finalize"}
[Tue Jul 27 01:59:35 UTC 2021] Please add '--debug' or '--log' to check more details.
[Tue Jul 27 01:59:35 UTC 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh

I've removed sensitive data ..

**Comment by dlhenke** [comment]
it works flawlessly with dns.he.net 
Using ubuntu 21.04

**Comment by LOVEChen** [comment]
> it works flawlessly with dns.he.net
> Using ubuntu 21.04

thanks
