### ISSUE TITLE
DNS记录已经添加，但是无法通过验证

### ISSUE THREAD

**Issue by anniextra** [acmesh-official/acme.sh#3233]
使用Namesilo作为域名服务商，已经获取API
通过acem调用之后，在后台看到相关txt信息已经注入到DNS服务器中
前台界面一直显示：Not valid yet, let's wait 10 seconds and check next one

这个是不是什么地方配置没做好？之前我用godaddy的时候，没有出现过类似情况，一次就搞定了。
是不是还是DNS服务商方面的问题？

**Comment by anniextra** [comment]
已经通过 -- upgrade升级到最新版本。

**Comment by anniextra** [comment]
问题已经解决，因为是今天刚迁移的域名，估计互联网域上的解析还没有全部刷新过来，我把域名信息全部清理之后，重新注册一次，然后等待一段时间刷新好之后。用同样的脚本就全部通过验证了。

**Comment by Neilpang** [comment]
namesilo dns 刷新比较慢, 需要等待15分钟:
https://github.com/acmesh-official/acme.sh/wiki/dnsapi#35-use-namesilocom-api

```
 --dns dns_namesilo --dnssleep 900 
```
