### ISSUE TITLE
internal domain with smallstep, using external DNS servers issue

### ISSUE THREAD

**Issue by nforceroh** [acmesh-official/acme.sh#3234]
Not so much a bug as not working as expected
I'm trying to use acme.sh to request internal domain only certs to my internal CA, smallstep, https://smallstep.com/
it does create the DNS TXT record in my internal powerdns server but it tries to use google and cloudflare DNS to verify the record instead of my internal DNS servers. Is there a DNS override that could be passed that can query my internal DNS instead?
Here's my set up,
domain: nf.lab
CA: smallstep with acme plugin
using instruction from https://smallstep.com/docs/tutorials/acme-protocol-acme-clients#acmesh
acme.sh --issue --dns dns_pdns -d esx01m.v101.nf.lab   --server https://ca.nf.lab:8443/acme/acme/directory  --ca-bundle /etc/pki/ca-trust/source/anchors/nf.lab.pem  --fullchain-file foo.crt  --key-file foo.key --debug 3

relevant outputs
DNS create record
[Mon 26 Oct 2020 10:30:26 AM EDT] acme.sh:issue:4361                       vlist='esx01m.v101.nf.lab#Z0dLTXrERoIl2PwMwfg9i5sE0zK4zfcZ.w43GI6FUKODc0nVR9zZGXGHl1VTvJtSx3U7PS2iHsCQ#https://ca.nf.lab:8443/acme/acme/challenge/02begVaSsuxapHAn9rMOq4kXebZbSG4P#dns-01#dns_pdns,'
[Mon 26 Oct 2020 10:30:26 AM EDT] acme.sh:issue:4372                       d='esx01m.v101.nf.lab'
[Mon 26 Oct 2020 10:30:26 AM EDT] acme.sh:issue:4387                       _d_alias
[Mon 26 Oct 2020 10:30:26 AM EDT] acme.sh:issue:4400                       txtdomain='_acme-challenge.esx01m.v101.nf.lab'
[Mon 26 Oct 2020 10:30:26 AM EDT] acme.sh:_base64:941                      base64 single line.
[Mon 26 Oct 2020 10:30:26 AM EDT] acme.sh:issue:4402                       txt='KCzkaSla5KMtWrlXfsJDxoNIXCNz9nBtDPaHkBR5DDE'
[Mon 26 Oct 2020 10:30:26 AM EDT] acme.sh:issue:4405                       d_api='/home/sylvain/.acme.sh/dnsapi/dns_pdns.sh'
[Mon 26 Oct 2020 10:30:26 AM EDT] acme.sh:issue:4408                       dns_entry='esx01m.v101.nf.lab,_acme-challenge.esx01m.v101.nf.lab,,dns_pdns,KCzkaSla5KMtWrlXfsJDxoNIXCNz9nBtDPaHkBR5DDE,/home/sylvain/.acme.sh/dnsapi/dns_pdns.sh'
[Mon 26 Oct 2020 10:30:26 AM EDT] acme.sh:issue:4410                       Found domain api file: /home/sylvain/.acme.sh/dnsapi/dns_pdns.sh

DNS check record
[Mon 26 Oct 2020 10:30:48 AM EDT] Checking esx01m.v101.nf.lab for _acme-challenge.esx01m.v101.nf.lab
[Mon 26 Oct 2020 10:30:48 AM EDT] acme.sh:__check_txt:3919                 _c_txtdomain='_acme-challenge.esx01m.v101.nf.lab'
[Mon 26 Oct 2020 10:30:48 AM EDT] acme.sh:__check_txt:3920                 _c_aliasdomain='_acme-challenge.esx01m.v101.nf.lab'
[Mon 26 Oct 2020 10:30:48 AM EDT] acme.sh:__check_txt:3921                 _c_txt='KCzkaSla5KMtWrlXfsJDxoNIXCNz9nBtDPaHkBR5DDE'
[Mon 26 Oct 2020 10:30:48 AM EDT] acme.sh:_ns_lookup:3896                  Detect dns server first.
[Mon 26 Oct 2020 10:30:48 AM EDT] acme.sh:_ns_lookup:3901                  Use google doh server
[Mon 26 Oct 2020 10:30:48 AM EDT] acme.sh:_ns_lookup_impl:3843             _ns_ep='https://dns.google/resolve'
[Mon 26 Oct 2020 10:30:48 AM EDT] acme.sh:_ns_lookup_impl:3844             _ns_domain='_acme-challenge.esx01m.v101.nf.lab'
[Mon 26 Oct 2020 10:30:48 AM EDT] acme.sh:_ns_lookup_impl:3845             _ns_type='TXT'
[Mon 26 Oct 2020 10:30:48 AM EDT] acme.sh:_get:1906                        GET
[Mon 26 Oct 2020 10:30:48 AM EDT] acme.sh:_get:1910                        url='https://dns.google/resolve?name=_acme-challenge.esx01m.v101.nf.lab&type=TXT'
[Mon 26 Oct 2020 10:30:48 AM EDT] acme.sh:_get:1911                        timeout=
[Mon 26 Oct 2020 10:30:48 AM EDT] acme.sh:_inithttp:1734                   Http already initialized.
[Mon 26 Oct 2020 10:30:48 AM EDT] acme.sh:_get:1923                        _CURL='curl -L --silent --dump-header /home/sylvain/.acme.sh/http.header  --trace-ascii /tmp/tmp.fyfJX2paAW  --cacert /etc/pki/ca-trust/source/anchors/nf.lab.pem  -g '
[Mon 26 Oct 2020 10:30:48 AM EDT] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 60
[Mon 26 Oct 2020 10:30:48 AM EDT] Here is the curl dump log:
[Mon 26 Oct 2020 10:30:48 AM EDT] == Info:   Trying 2001:4860:4860::8888:443...
== Info: Connected to dns.google (2001:4860:4860::8888) port 443 (#0)

**Comment by Neilpang** [comment]
>>  Is there a DNS override that could be passed that can query my internal DNS instead?

Yes,  use `--dnssleep` to disable doh checking.

```
--issue -d xxxxx  --dns xxxx     --dnssleep  10
```

**Comment by nforceroh** [comment]
thank you!! that works as expected now
