### ISSUE TITLE
How to see which domains are part of Auto Renew?

### ISSUE THREAD

**Issue by Raul-7-7** [acmesh-official/acme.sh#3254]
Hey Guys,
over the years, I have removed some domains out of AutoRenew, however I cant recall which ones, is there anyway to see which domains are part of AutoRenew? I removed the domains using this command "acme.sh --remove -d example.com" basically I am looking for a command to tell me which domains are still part of AutoRenew. Is this possible? 

Thank you,

**Comment by Neilpang** [comment]
```
acme.sh  --list
```
