### ISSUE TITLE
dns_dpi.sh update request

### ISSUE THREAD

**Issue by mnihyc** [acmesh-official/acme.sh#3259]
For dnspod international has just changed their API behaviour, the string in dns_dpi.sh "Action completed successful" should be replaced with "Operation successful" ensuring normal operation.

**Comment by Neilpang** [comment]
try again with the dev branch:

```
acme.sh  --upgrade -b dev
```

**Comment by mnihyc** [comment]
I had modified that string manually before and then it did work. Therefore I think there would be no problem with the commit.
