### ISSUE TITLE
An option to disable DOH or automatically fallback to regular DNS on 4xx DOH errors

### ISSUE THREAD

**Issue by silverwind** [acmesh-official/acme.sh#3266]
When using the DNS challenge in an environment with a HTTP proxy which blocks both`https://dns.google` and `https://cloudflare-dns.com`, acme.sh will fail to verify DNS records (curl will see 403 responses to the DOH queries). Setting `DOH_USE=0` seems to work sometimes but it can apparently not always prevent DOH queries from being attempted.

I'd suggest either automatically falling back to regular DNS if DOH queries fails with 4xx error codes or even better, have an option to disable attempting DOH in first place for environments where it will not work and just use regular DNS.

What may also work for some users would be that a user could specify a custom DOH server, or if the operating system is configured to use DOH, just obtain the DOH server to use from there instead.

````
[Tue 24 Nov 2020 09:13:10 AM CET] Detect dns server first.
[Tue 24 Nov 2020 09:13:10 AM CET] Use google doh server
[Tue 24 Nov 2020 09:13:10 AM CET] GET
[Tue 24 Nov 2020 09:13:10 AM CET] url='https://dns.google/resolve?name=_acme-challenge.domain&type=TXT'
[Tue 24 Nov 2020 09:13:10 AM CET] timeout=
[Tue 24 Nov 2020 09:13:10 AM CET] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Tue 24 Nov 2020 09:13:11 AM CET] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 56
[Tue 24 Nov 2020 09:13:11 AM CET] ret='56'
[Tue 24 Nov 2020 09:13:11 AM CET] Not valid yet, let's wait 10 seconds and check next one.
[Tue 24 Nov 2020 09:13:11 AM CET] _p_txtdomain='_acme-challenge.domain'
[Tue 24 Nov 2020 09:13:11 AM CET] Cloudflare purge TXT record for domain _acme-challenge.domain
[Tue 24 Nov 2020 09:13:11 AM CET] POST
[Tue 24 Nov 2020 09:13:11 AM CET] _post_url='https://cloudflare-dns.com/api/v1/purge?domain=_acme-challenge.domain&type=TXT'
[Tue 24 Nov 2020 09:13:11 AM CET] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Tue 24 Nov 2020 09:13:11 AM CET] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 56
[Tue 24 Nov 2020 09:13:11 AM CET] _ret='56'
[Tue 24 Nov 2020 09:13:22 AM CET] Let's wait 10 seconds and check again.
````

Also the `Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 56` that happens in this case is not really helpful, only when running with `--debug` I was able to see the actual curl URLs that were failing. Suggestion to print the failing URL in the error message too.

**Comment by Neilpang** [comment]
please use `--dns-sleep 300` to disable the doh checks.

**Comment by silverwind** [comment]
Yeah, I'm using that but I only consider it a workaround. I think acme.sh is lacking some configurability in regards to this DNS check. It should be possible to disable the check, configure destination servers and protocol used.

BTW: To my knowledge LetEncrypt's Boulder will always perform directed DNS queries to the authorative server for the zone without any cache involved in which case it is not necessary to perform this DNS check in first place and acme.sh could just assume DNS is up to date as soon as the API request completes.
