### ISSUE TITLE
Migration path from Letsencrypt to ZeroSSL

### ISSUE THREAD

**Issue by vkukk** [acmesh-official/acme.sh#3267]
We are planning to migrate from Letsencrypt to ZeroSSL due to the https://letsencrypt.org/2020/11/06/own-two-feet.html
Currently we have existing Letsencrypt certificates for many domains created with acme.sh.

What are suggested steps to renew or re-issue all existing Letsencrypt certificates into ZeroSSL certificates?

**Comment by Neilpang** [comment]
Sorry, there is not a very simple way to do that.
I wat planing to make the `--renew` command support `--server` option. so you can renew the cert aginst a new CA.

```
acme.sh --renew -d examaple.com  --server  zerossl
```

what do you think?

**Comment by StrangePeanut** [comment]
What is currently the best way to go about this? Delete and reissue/reinstall every single letsencrypt certificate?

**Comment by Neilpang** [comment]
```
acme.sh --renew -d examaple.com  --server  zerossl
```

**Comment by StrangePeanut** [comment]
Worked flawlessly 👍
