### ISSUE TITLE
HEADSUP: short-lived intermediate Let's Encrypt R3 is provided by the default preferred chain 'DST Root CA X3'

### ISSUE THREAD

**Issue by gnanet** [acmesh-official/acme.sh#3312]
In case you faced any warnings, or alerts from any SSL-monitoring service you may be using, where the alert states that your certificate chain has a short lived intermediary, please read on.
------------------

The process of transitioning to the new intermediate R3 at Let's Encrypt resulted in two different certificates, where the certificate signed by 'DST Root CA X3' expires in short time (currently Sep 29 19:21:40 2021 GMT ). You can read about it in the question linked below:
https://community.letsencrypt.org/t/questions-re-beginning-issuance-from-r3/139026/6

Actually **in acme.sh the default preferred chain is the above mentioned 'DST Root CA X3'**, and **the suggested longer-life R3 intermediate is available if you manualy set the preferred chain to 'ISRG Root X1'**.

BEWARE: it's not encouraged to edit the conf file by hand. You can re-issue your cert, with `--preferred-chain` to accomplish the same
------------------

### To switch to the longer-living R3 intermediate you may need to re-issue the certificates where you face problems based on the expiry date of R3

~~forcefully renew your certificates~~  I did my tests with acme.sh version 2.8.8, and noticed that using the `--preferred-chain ` parameter is only supported by the `--issue` command. ( See line 7348 )

A small tweak to the domain's config, that tells acme.sh to use the preferred chain is detailed below
------------------

To enable the alternate chain, one could write the `Le_Preferred_Chain` setting manually into the configs of the affected domains:

```
_sdvalue="ISRG Root X1"
B64CONF_START="__ACME_BASE64__START_"
B64CONF_END="__ACME_BASE64__END_"
Le_Preferred_Chain="${B64CONF_START}$(printf "%s" "${_sdvalue}" | ${ACME_OPENSSL_BIN:-openssl} base64 -e | tr -d '\r\n')${B64CONF_END}"
echo "Le_Preferred_Chain='${Le_Preferred_Chain}'"
```

Above snippet returns:
```
Le_Preferred_Chain='__ACME_BASE64__START_SVNSRyBSb290IFgx__ACME_BASE64__END_'
```

Copy and paste the resulting `Le_Preferred_Chain=` line into all of the domains you want to switch to the alternate chain, and renew them one by one to be sure:

```
acme.sh --renew --force -d THEDOMAIN
```

The messages orthe log of the renew process should contain similar to this if you succeeded to switch the chain:

```
...
Verify finished, start to sign.
Lets finalize the order.
Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/NNNNNNNN/NNNNNNNNNN'
Downloading cert.
Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/LINKHASH_OF_YOUR_CERT'
Try rel: https://acme-v02.api.letsencrypt.org/acme/cert/LINKHASH_OF_YOUR_CERT/1
Matched issuer in: https://acme-v02.api.letsencrypt.org/acme/cert/LINKHASH_OF_YOUR_CERT/1
Cert success.
...
```

@Neilpang this info may belong into the wiki, or somwhere other, but since the official transition to ISRG's Root has been delayed until Jan 11 2021, the best would be to keep this open to help users understand why the normal renewal procedure saving a soon-expiring CA for Let's Encrypt.

**Comment by djschilling** [comment]
is there already a new version available with this active, or do i have to change my config manually as suggested by @gnanet

**Comment by Neilpang** [comment]
please use the `preferred-chain` option to select the chan you like:
https://github.com/acmesh-official/acme.sh/wiki/Preferred-Chain

**Comment by DerDanilo** [comment]
> 
> 
> please use the `preferred-chain` option to select the chan you like:
> https://github.com/acmesh-official/acme.sh/wiki/Preferred-Chain

This option doesn't seem to be supported by the renewal process. Is the above manual config file edit the only way to update existing config files?

**Comment by Neilpang** [comment]
Yes,  but it's not encouraged to edit the conf file by hand.

you just `issue` the cert again with `--preferred-chain`

**Comment by gnanet** [comment]
@Neilpang I question, if this is still an issue at all ? OR have the folks over at LE already solved the chains issue ?

**Comment by Neilpang** [comment]
@gnanet   It's LE's problems.  but it does't matter at all.

There are 2 chains they provided:

```
LeafCert <- R3 <- ISRG X1(self-signed)


And:

LeafCert  <- R3 <- DST Root (short lived by 2021)

```


They will change the second chain soon to:

```
LeafCert  <- R3 <- ISRG X1 <- DST Root(short lived by 2021)
```
But this doesn't matter with your question.  let's just focus on the first 2 chains.



See here:  https://letsencrypt.org/2020/12/21/extending-android-compatibility.html

```
But isn’t DST Root CA X3 expiring? 

The self-signed certificate which represents the DST Root CA X3 keypair is expiring. But browser and OS root stores don’t contain certificates per se, they contain “trust anchors”, and the standards for verifying certificates allow implementations to choose whether or not to use fields on trust anchors. Android has intentionally chosen not to use the notAfter field of trust anchors. Just as our ISRG Root X1 hasn’t been added to older Android trust stores, DST Root CA X3 hasn’t been removed. So it can issue a cross-sign whose validity extends beyond the expiration of its own self-signed certificate without any issues.

```

**Comment by gnanet** [comment]
@Neilpang reading the last part,do i understand right?

on one hand there is a concern about short lived root certs, which may raise warnings for example in some monitoring solutions like i use (which checks the chain, and does not rely on trustanchors) which can be silenced by re-issuing certs with the alternate chain switch

on the other hand, OS and browser root stores contain the trust anchors, and that way systems,and software that rely on those root stores should not complain, even if root cert expiration happens

**Comment by Neilpang** [comment]
@gnanet   Correct.

But you can select the alternative chain to avoid warnings.

```
LeafCert <- R3 <- ISRG X1(self-signed)
```

**Comment by Neilpang** [comment]
@yangkenneth   Sorry, it was a missing.

please try again with the latest dev branch.


```
acme.sh --upgrade  -b dev
```
