### ISSUE TITLE
acme.sh validation failing with dns-01 challenge with global dns set to OpenDns on Gateway. 

### ISSUE THREAD

**Issue by petrus9** [acmesh-official/acme.sh#3314]
Steps to reproduce
------------------
attempt install of Let's Encrypt with  command  `acme.sh --force --issue -- --dns dns_provider -d `sub.mydomain.com`

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```
The part of the debug 2 log which shows the issue is here:

[Sun Dec 20 13:46:46 EST 2020] Let's check each DNS record now. Sleep 20 seconds first.
[Sun Dec 20 13:47:08 EST 2020] _is_idn_d='_acme-challenge.mysubdomain.com'
[Sun Dec 20 13:47:08 EST 2020] _idn_temp
[Sun Dec 20 13:47:08 EST 2020] _is_idn_d='_acme-challenge.mysubdomain.com'
[Sun Dec 20 13:47:08 EST 2020] _idn_temp
[Sun Dec 20 13:47:08 EST 2020] d='mysubdomain.com'
[Sun Dec 20 13:47:08 EST 2020] txtdomain='_acme-challenge.mysubdomain.com'
[Sun Dec 20 13:47:08 EST 2020] aliasDomain='_acme-challenge.mysubdomain.com'
[Sun Dec 20 13:47:08 EST 2020] txt='LOky380zsmZWRSPn57skuGWNsVxCNS1HE7d_xtNUaSM'
[Sun Dec 20 13:47:08 EST 2020] d_api='/root/.acme.sh/dnsapi/dns_dynu.sh'
[Sun Dec 20 13:47:08 EST 2020] Checking mysubdomain.com for _acme-challenge.mysubdomain.com
[Sun Dec 20 13:47:08 EST 2020] _c_txtdomain='_acme-challenge.mysubdomain.com'
[Sun Dec 20 13:47:08 EST 2020] _c_aliasdomain='_acme-challenge.mysubdomain.com'
[Sun Dec 20 13:47:08 EST 2020] _c_txt='LOky380zsmZWRSPn57skuGWNsVxCNS1HE7d_xtNUaSM'
[Sun Dec 20 13:47:08 EST 2020] Detect dns server first.
[Sun Dec 20 13:47:09 EST 2020] Use google doh server
[Sun Dec 20 13:47:09 EST 2020] _ns_ep='https://dns.google/resolve'
[Sun Dec 20 13:47:09 EST 2020] _ns_domain='_acme-challenge.mysubdomain.com'
[Sun Dec 20 13:47:09 EST 2020] _ns_type='TXT'
[Sun Dec 20 13:47:09 EST 2020] GET
[Sun Dec 20 13:47:09 EST 2020] url='https://dns.google/resolve?name=_acme-challenge.mysubdomain.com&type=TXT'
[Sun Dec 20 13:47:09 EST 2020] timeout=
[Sun Dec 20 13:47:09 EST 2020] Http already initialized.
[Sun Dec 20 13:47:09 EST 2020] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.N3tLWqXJTm  -g '
[Sun Dec 20 13:47:09 EST 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 60
[Sun Dec 20 13:47:09 EST 2020] Here is the curl dump log:
[Sun Dec 20 13:47:09 EST 2020] == Info: Hostname was NOT found in DNS cache
== Info:   Trying 146.112.61.106...
== Info: Connected to dns.google (146.112.61.106) port 443 (#0)
== Info: successfully set certificate verify locations:
== Info:   CAfile: none
  CApath: /etc/ssl/certs
== Info: SSLv3, TLS Unknown, Unknown (22):
=> Send SSL data, 5 bytes (0x5)
0000: .....
== Info: SSLv3, TLS handshake, Client hello (1):
=> Send SSL data, 512 bytes (0x200)
0000: ..........|..f'.0.^.NL..P11.j|...r68.....0.,.(.$.............k.
0040: j.i.h.9.8.7.6.........2...*.&.......=.5.../.+.'.#.............g.
0080: @.?.>.3.2.1.0.........E.D.C.B.1.-.).%.......<./...A.....G.......
00c0: ..dns.google........................................... ........
0100: ................................................................
0140: ................................................................
0180: ................................................................
01c0: ................................................................
== Info: SSLv2, Unknown (22):
<= Recv SSL data, 5 bytes (0x5)
0000: ....Z
== Info: SSLv3, TLS handshake, Server hello (2):
<= Recv SSL data, 90 bytes (0x5a)
0000: ...V..~..hih.0...|O.....e....v...z.L ...$_.,B.7E.......R\..hk
0040: t.P...W...................
== Info: SSLv2, Unknown (22):
<= Recv SSL data, 5 bytes (0x5)
0000: ....K
== Info: SSLv3, TLS handshake, CERT (11):
<= Recv SSL data, 3147 bytes (0xc4b)
0000: ...G..D..B0..>0..&......._.Z.0...*.H........0@1.0...U....Cisco1.
0040: 0,..U...%Cisco Umbrella Secondary SubCA nyc-SG0...201218140818Z.
0080: .201223140818Z0g1.0...U....US1.0...U....California1.0...U....San
00c0:  Francisco1.0...U....OpenDNS, Inc.1.0...U....dns.google0.."0...*
0100: .H.............0............tX_....0v...9~..1|...i^....'...ZZnP
0140: .`...2.9#.d....V....i..H.+.p.B~....*\.W...<...W.....l|"..|I....
0180: ..o.....TNf>...eQ....~T..1...t.3B.......3yXgFUK....Y...Fx..*..).
01c0: ..M....u..A..&...Hi9...z.a74..._.i..n.....6O..u.g;.].W......N\..
0200: ...}L.T.............Z..........0.0...U....0...dns.google0...*.H.
0240: ................0,....b ...`T..@S..t*.r.r..Z..[....m.i..D.P....Q
0280: ..gU...-........}$<N..$.IW.Z2.m%.3^...p......4.^......f......@..
02c0: .%.....y.VeR.K.l..........#.s........../.....r@...1B.!.$..vw..07
0300: ..L..`.gj.a2 :....>..a...@.M..8.x.p.*.2i..xa.....9L[UR.(.&%^bz"
0340: ......y..qUc..:0..60.............Q.|.C}.;/V..s.0...*.H........0q
0380: 1.0...U....US1.0...U....California1.0...U....San Francisco1.0...
03c0: U....Cisco1%0#..U....Cisco Umbrella Primary SubCA0...20121819534
0400: 3Z..201229195343Z0@1.0...U....Cisco1.0,..U...%Cisco Umbrella Sec
0440: ondary SubCA nyc-SG0.."0...*.H.............0............tX_....0
0480: v...9~..1|...i^....'...ZZnP.`...2.9#.d....V....i..H.+.p.B~....*
04c0: \.W...<...W.....l|"..|I......o.....TNf>...eQ....~T..1...t.3B...
0500: ....3yXgFUK....Y...Fx..*..)...M....u..A..&...Hi9...z.a74..._.i..
0540: n.....6O..u.g;.].W......N\.....}L.T.............Z...........0..0
0580: ...U.......0.......0...U...........0...U.......... u'.;:\.$o.Y=.
05c0: ;$0...U.#..0...E_..q3%..N<.D.<.F...0L..+........@0>0<..+.....0..
0600: 0http://crl.prod.cagenerator.pki.strln.net/ca.pem0B..U...;0907.5
0640: .3.1http://crl.prod.cagenerator.pki.strln.net/crl.pem0...*.H....
0680: .........;d>.....p/..k...a.E\~.G.7C..#...V..A"....~&..%.. 3.....
06c0: ....[%Hma.g.......&b.)...-..........,)"'.nJw4`. .w..a%.N..p.CM..
0700: a'xB....q.Bv.1&I..._....^_H.Y..r...M.L..#.ah.A9..U.%. 8....=.j..
0740: hq..7.h-......$..#.~N..~....Q..`R..t..N.C...v.r.g>...S...<.B(.n+
0780: t.Q..s\.E...0...0............7.W....0...*.H........011.0...U....
07c0: Cisco1.0...U....Cisco Umbrella Root CA0...190521195318Z..2405211
0800: 95318Z0q1.0...U....US1.0...U....California1.0...U....San Francis
0840: co1.0...U....Cisco1%0#..U....Cisco Umbrella Primary SubCA0.."0..
0880: .*.H.............0.........Q!...7...e.^6.n..Sn..I-..V.E..f..y...
08c0: ....[.Kb$.@~.j.........0.'..V7.4.QtM.q@.I....,..v.Z..d..n.^1?.l.
0900: .VO.I.L...Z......}...CZ.....\h.z..........j.1...W.....o....c.hJ.
0940: .=.6....o]..<..#...8p.,.qG+..u.8...........AK......:..HwD......
0980: .F%I....x.~d...U....h...._.........0...0...U...........0...U....
09c0: ...0.......0R..U. .K0I0G..+.........0907..+........+http://www.c
0a00: isco.com/security/pki/policies/0...U......E_..q3%..N<.D.<.F...0L
0a40: ..U...E0C0A.?.=.;http://www.cisco.com/security/pki/crl/ciscoumbr
0a80: ellaroot.crl0....+........{0y0I..+.....0..=http://www.cisco.com/
0ac0: security/pki/certs/ciscoumbrellaroot.cer0,..+.....0.. http://pki
0b00: cvs.cisco.com/pki/ocsp0...U.#..0...Cs..$.@.@T,}|..H..p.0...*.H..
0b40: ............?.......k..Y3C]...j..E....L...>^.....{.e>......t1H..
0b80: ..Lw...iu).1.G|).Ic......q..:..D.&I..*.......0..........J.gn...g
0bc0: ..C.1..;.T.XV.8.R...<.V....X...eT......by2-...`......?...%.\.l.+
0c00: ...7...r......=...mr.n_.....]}..w...........'!......"...........
0c40: C.`O.fa".x.
== Info: SSLv2, Unknown (21):
=> Send SSL data, 5 bytes (0x5)
0000: .....
== Info: SSLv3, TLS alert, Server hello (2):
=> Send SSL data, 2 bytes (0x2)
0000: .0
== Info: SSL certificate problem: unable to get local issuer certificate
== Info: Closing connection 0
== Info: SSLv2, Unknown (21):
=> Send SSL data, 5 bytes (0x5)
0000: .....
== Info: SSLv3, TLS alert, Client hello (1):
=> Send SSL data, 2 bytes (0x2)
0000: ..
[Sun Dec 20 13:47:09 EST 2020] ret='60'
[Sun Dec 20 13:47:09 EST 2020] response
[Sun Dec 20 13:47:09 EST 2020] Not valid yet, let's wait 10 seconds and check next one.
[Sun Dec 20 13:47:09 EST 2020] _p_txtdomain='_acme-challenge.mysubdomain.com'
[Sun Dec 20 13:47:09 EST 2020] Cloudflare purge TXT record for domain _acme-challenge.mysubdomain.com
[Sun Dec 20 13:47:09 EST 2020] POST
[Sun Dec 20 13:47:09 EST 2020] _post_url='https://cloudflare-dns.com/api/v1/purge?domain=_acme-challenge.mysubdomain.com&type=TXT'
[Sun Dec 20 13:47:09 EST 2020] body
[Sun Dec 20 13:47:09 EST 2020] _postContentType
[Sun Dec 20 13:47:09 EST 2020] Http already initialized.
[Sun Dec 20 13:47:09 EST 2020] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.N3tLWqXJTm  -g '
[Sun Dec 20 13:47:10 EST 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 60
[Sun Dec 20 13:47:10 EST 2020] Here is the curl dump log:
[Sun Dec 20 13:47:10 EST 2020] == Info: Hostname was NOT found in DNS cache
== Info:   Trying 146.112.61.106...
== Info: Connected to cloudflare-dns.com (146.112.61.106) port 443 (#0)
== Info: successfully set certificate verify locations:
== Info:   CAfile: none
  CApath: /etc/ssl/certs
== Info: SSLv3, TLS Unknown, Unknown (22):
=> Send SSL data, 5 bytes (0x5)
0000: .....
== Info: SSLv3, TLS handshake, Client hello (1):
=> Send SSL data, 512 bytes (0x200)
0000: ......z...#.fk...`...psz!..\GZ..t..L.....0.,.(.$.............k.
0040: j.i.h.9.8.7.6.........2...*.&.......=.5.../.+.'.#.............g.
0080: @.?.>.3.2.1.0.........E.D.C.B.1.-.).%.......<./...A.....G.......
00c0: ..cloudflare-dns.com........................................... 
0100: ................................................................
0140: ................................................................
0180: ................................................................
01c0: ................................................................
== Info: SSLv2, Unknown (22):
<= Recv SSL data, 5 bytes (0x5)
0000: ....Z
== Info: SSLv3, TLS handshake, Server hello (2):
<= Recv SSL data, 90 bytes (0x5a)
0000: ...V..|w.Vb.oig...G.9.x.g}..%.j...&..I .B/..}.ie..g..W...#..6..:
0040: \..5.X....................
== Info: SSLv2, Unknown (22):
<= Recv SSL data, 5 bytes (0x5)
0000: ....[
== Info: SSLv3, TLS handshake, CERT (11):
<= Recv SSL data, 3163 bytes (0xc5b)
0000: ...W..T..R0..N0..6......._.Og0...*.H........0@1.0...U....Cisco1.
0040: 0,..U...%Cisco Umbrella Secondary SubCA nyc-SG0...201218131909Z.
0080: .201223131909Z0o1.0...U....US1.0...U....California1.0...U....San
00c0:  Francisco1.0...U....OpenDNS, Inc.1.0...U....cloudflare-dns.com0
0100: .."0...*.H.............0............tX_....0v...9~..1|...i^....'
0140: ...ZZnP.`...2.9#.d....V....i..H.+.p.B~....*\.W...<...W.....l|"
0180: ..|I......o.....TNf>...eQ....~T..1...t.3B.......3yXgFUK....Y...F
01c0: x..*..)...M....u..A..&...Hi9...z.a74..._.i..n.....6O..u.g;.].W..
0200: ....N\.....}L.T.............Z.........!0.0...U....0...cloudflare
0240: -dns.com0...*.H..............:.'.Y..Z.@..0.....a87.7.-G...jMa...
0280: .5+.........3...7......7...{.,....).(Z!&........w.-.....).._.:.W
02c0: .4k.|M?..N..9?...Xs..k........;...`k.|.nE...x.B..W....`s.A......
0300: Q.M......iu.J........
[Sun Dec 20 13:47:10 EST 2020] _ret='60'
[Sun Dec 20 13:47:10 EST 2020] response
[Sun Dec 20 13:47:21 EST 2020] Let's wait 10 seconds and check again.
[Sun Dec 20 13:47:32 EST 2020] _is_idn_d='_acme-challenge.mysubdomain.com'
[Sun Dec 20 13:47:32 EST 2020] _idn_temp
[Sun Dec 20 13:47:32 EST 2020] _is_idn_d='_acme-challenge.mysubdomain.com'
[Sun Dec 20 13:47:32 EST 2020] _idn_temp
[Sun Dec 20 13:47:32 EST 2020] d='mysubdomain.com'
[Sun Dec 20 13:47:32 EST 2020] txtdomain='_acme-challenge.mysubdomain.com'
[Sun Dec 20 13:47:32 EST 2020] aliasDomain='_acme-challenge.mysubdomain.com'
[Sun Dec 20 13:47:32 EST 2020] txt='LOky380zsmZWRSPn57skuGWNsVxCNS1HE7d_xtNUaSM'
[Sun Dec 20 13:47:32 EST 2020] d_api='/root/.acme.sh/dnsapi/dns_dynu.sh'
[Sun Dec 20 13:47:33 EST 2020] Checking mysubdomain.com for _acme-challenge.mysubdomain.com
[Sun Dec 20 13:47:33 EST 2020] _c_txtdomain='_acme-challenge.mysubdomain.com'
[Sun Dec 20 13:47:33 EST 2020] _c_aliasdomain='_acme-challenge.mysubdomain.com'
[Sun Dec 20 13:47:33 EST 2020] _c_txt='LOky380zsmZWRSPn57skuGWNsVxCNS1HE7d_xtNUaSM'
[Sun Dec 20 13:47:33 EST 2020] Detect dns server first.
[Sun Dec 20 13:47:33 EST 2020] Use google doh server
[Sun Dec 20 13:47:33 EST 2020] _ns_ep='https://dns.google/resolve'
[Sun Dec 20 13:47:33 EST 2020] _ns_domain='_acme-challenge.mysubdomain.com'
[Sun Dec 20 13:47:33 EST 2020] _ns_type='TXT'
[Sun Dec 20 13:47:33 EST 2020] GET
[Sun Dec 20 13:47:33 EST 2020] url='https://dns.google/resolve?name=_acme-challenge.mysubdomain.com&type=TXT'
[Sun Dec 20 13:47:33 EST 2020] timeout=
[Sun Dec 20 13:47:33 EST 2020] Http already initialized.
[Sun Dec 20 13:47:33 EST 2020] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.N3tLWqXJTm  -g '
[Sun Dec 20 13:47:33 EST 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 60
[Sun Dec 20 13:47:33 EST 2020] Here is the curl dump log:
[Sun Dec 20 13:47:34 EST 2020] == Info: Hostname was NOT found in DNS cache
== Info:   Trying 146.112.61.106...
== Info: Connected to dns.google (146.112.61.106) port 443 (#0)
== Info: successfully set certificate verify locations:
== Info:   CAfile: none
  CApath: /etc/ssl/certs
== Info: SSLv3, TLS Unknown, Unknown (22):
=> Send SSL data, 5 bytes (0x5)
0000: .....
== Info: SSLv3, TLS handshake, Client hello (1):
=> Send SSL data, 512 bytes (0x200)
0000: ........h.e.;.&.p.2....d.0..M...[.........0.,.(.$.............k.
0040: j.i.h.9.8.7.6.........2...*.&.......=.5.../.+.'.#.............g.
0080: @.?.>.3.2.1.0.........E.D.C.B.1.-.).%.......<./...A.....G.......
00c0: ..dns.google........................................... ........
0100: ................................................................
0140: ................................................................
0180: ................................................................
01c0: ................................................................
== Info: SSLv2, Unknown (22):
<= Recv SSL data, 5 bytes (0x5)
0000: ....Z
== Info: SSLv3, TLS handshake, Server hello (2):
<= Recv SSL data, 90 bytes (0x5a)
0000: ...V...fd...... *.V..x.V.../...p.Oxj.. D.=+.Mm0,k{....kN.N.@W.r.
0040: ...FI.....................
== Info: SSLv2, Unknown (22):
<= Recv SSL data, 5 bytes (0x5)
0000: ....K
== Info: SSLv3, TLS handshake, CERT (11):
<= Recv SSL data, 3147 bytes (0xc4b)
0000: ...G..D..B0..>0..&......._.Z.0...*.H........0@1.0...U....Cisco1.
0040: 0,..U...%Cisco Umbrella Secondary SubCA nyc-SG0...201218140818Z.
0080: .201223140818Z0g1.0...U....US1.0...U....California1.0...U....San
00c0:  Francisco1.0...U....OpenDNS, Inc.1.0...U....dns.google0.."0...*
0100: .H.............0............tX_....0v...9~..1|...i^....'...ZZnP
0140: .`...2.9#.d....V....i..H.+.p.B~....*\.W...<...W.....l|"..|I....
0180: ..o.....TNf>...eQ....~T..1...t.3B.......3yXgFUK....Y...Fx..*..).
01c0: ..M....u..A..&...Hi9...z.a74..._.i..n.....6O..u.g;.].W......N\..
0200: ...}L.T.............Z..........0.0...U....0...dns.google0...*.H.
0240: ................0,....b ...`T..@S..t*.r.r..Z..[....m.i..D.P....Q
0280: ..gU...-........}$<N..$.IW.Z2.m%.3^...p......4.^......f......@..
02c0: .%.....y.VeR.K.l..........#.s........../.....r@...1B.!.$..vw..07
0300: ..L..`.gj.a2 :....>..a...@.M..8.x.p.*.2i..xa.....9L[UR.(.&%^bz"
0340: ......y..qUc..:0..60.............Q.|.C}.;/V..s.0...*.H........0q
0380: 1.0...U....US1.0...U....California1.0...U....San Francisco1.0...
03c0: U....Cisco1%0#..U....Cisco Umbrella Primary SubCA0...20121819534
0400: 3Z..201229195343Z0@1.0...U....Cisco1.0,..U...%Cisco Umbrella Sec
0440: ondary SubCA nyc-SG0.."0...*.H.............0............tX_....0
0480: v...9~..1|...i^....'...ZZnP.`...2.9#.d....V....i..H.+.p.B~....*
04c0: \.W...<...W.....l|"..|I......o.....TNf>...eQ....~T..1...t.3B...
0500: ....3yXgFUK....Y...Fx..*..)...M....u..A..&...Hi9...z.a74..._.i..
0540: n.....6O..u.g;.].W......N\.....}L.T.............Z...........0..0
0580: ...U.......0.......0...U...........0...U.......... u'.;:\.$o.Y=.
05c0: ;$0...U.#..0...E_..q3%..N<.D.<.F...0L..+........@0>0<..+.....0..
0600: 0http://crl.prod.cagenerator.pki.strln.net/ca.pem0B..U...;0907.5
0640: .3.1http://crl.prod.cagenerator.pki.strln.net/crl.pem0...*.H....
0680: .........;d>.....p/..k...a.E\~.G.7C..#...V..A"....~&..%.. 3.....
06c0: ....[%Hma.g.......&b.)...-..........,)"'.nJw4`. .w..a%.N..p.CM..
0700: a'xB....q.Bv.1&I..._....^_H.Y..r...M.L..#.ah.A9..U.%. 8....=.j..
0740: hq..7.h-......$..#.~N..~....Q..`R..t..N.C...v.r.g>...S...<.B(.n+
0780: t.Q..s\.E...0...0............7.W....0...*.H........011.0...U....
07c0: Cisco1.0...U....Cisco Umbrella Root CA0...190521195318Z..2405211
0800: 95318Z0q1.0...U....US1.0...U....California1.0...U....San Francis
0840: co1.0...U....Cisco1%0#..U....Cisco Umbrella Primary SubCA0.."0..
0880: .*.H.............0.........Q!...7...e.^6.n..Sn..I-..V.E..f..y...
08c0: ....[.Kb$.@~.j.........0.'..V7.4.QtM.q@.I....,..v.Z..d..n.^1?.l.
0900: .VO.I.L...Z......}...CZ.....\h.z..........j.1...W.....o....c.hJ.
0940: .=.6....o]..<..#...8p.,.qG+..u.8...........AK......:..HwD......
0980: .F%I....x.~d...U....h...._.........0...0...U...........0...U....
09c0: ...0.......0R..U. .K0I0G..+.........0907..+........+http://www.c
0a00: isco.com/security/pki/policies/0...U......E_..q3%..N<.D.<.F...0L
0a40: ..U...E0C0A.?.=.;http://www.cisco.com/security/pki/crl/ciscoumbr
0a80: ellaroot.crl0....+........{0y0I..+.....0..=http://www.cisco.com/
0ac0: security/pki/certs/ciscoumbrellaroot.cer0,..+.....0.. http://pki
0b00: cvs.cisco.com/pki/ocsp0...U.#..0...Cs..$.@.@T,}|..H..p.0...*.H..
0b40: ............?.......k..Y3C]...j..E....L...>^.....{.e>......t1H..
0b80: ..Lw...iu).1.G|).Ic......q..:..D.&I..*.......0..........J.gn...g
0bc0: ..C.1..;.T.XV.8.R...<.V....X...eT......by2-...`......?...%.\.l.+
0c00: ...7...r......=...mr.n_.....]}..w...........'!......"...........
0c40: C.`O.fa".x.
== Info: SSLv2, Unknown (21):
=> Send SSL data, 5 bytes (0x5)
0000: .....
== Info: SSLv3, TLS alert, Server hello (2):
=> Send SSL data, 2 bytes (0x2)
0000: .0
== Info: SSL certificate problem: unable to get local issuer certificate
== Info: Closing connection 0
== Info: SSLv2, Unknown (21):
=> Send SSL data, 5 bytes (0x5)
0000: .....
== Info: SSLv3, TLS alert, Client hello (1):
=> Send SSL data, 2 bytes (0x2)
0000: ..
[Sun Dec 20 13:47:34 EST 2020] ret='60'
[Sun Dec 20 13:47:34 EST 2020] response
[Sun Dec 20 13:47:34 EST 2020] Not valid yet, let's wait 10 seconds and check next one.

**Comment by Neilpang** [comment]
```
[Sun Dec 20 13:47:33 EST 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 60
```

**Comment by petrus9** [comment]
@Neilpang thank you,  I looked at this and determined that when dns.google  or cloudflare-dns.com are accessed the certificate for opendns is returned and causes an error so the txt record can't be verified.   Is there another workaround apart from not using OpenDNS as my content filtering system?  If I change my global dns settings to something other than OpenDNS the script runs with out any issues.

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh/wiki/dnscheck

**Comment by petrus9** [comment]
ok thank @Neilpang that worked.
