### ISSUE TITLE
Why are these lines commented out? 

### ISSUE THREAD

**Issue by mkkeffeler** [acmesh-official/acme.sh#3315]
History search shows these lines are commented out for long time. Without these lines, I am unable to set a default home directory, certs directory, without specifying --accountconf every single time. I would prefer to set the default account conf somewhere and then not have to specify it each time. Just trying to understand the architecture so I don't follow a bad pattern.
![2020-12-21_18-30-58](https://user-images.githubusercontent.com/12587979/102834920-edf27500-43ba-11eb-8a0b-1c754ed2f07a.png)

These lines enable the use an account.conf file in the same folder as acme.sh. It makes sense that one would use this by default I think but want to understand why the decision was made.

**Comment by Neilpang** [comment]
sometimes,  acme.sh may be put in `/usr/bin/` folder.  so, we can not use the current dir.

**Comment by mkkeffeler** [comment]
That makes sense.

So how do people manage when they do that? I want to do the same thing so that I have 1 install of the script that any can use,  and account configuration in a shared directory. Is there a pattern for that or am I missing a fundamental?

**Comment by Neilpang** [comment]
you can define env `LE_CONFIG_HOME` for acme.sh to save the conf files.
Or you can use `--config-home ` parameter.

**Comment by mkkeffeler** [comment]
That's super helpful. Worth adding to docs, and solved my issue.
