### ISSUE TITLE
after add TXT record, I can't renew 

### ISSUE THREAD

**Issue by codeoflin** [acmesh-official/acme.sh#3316]
![image](https://user-images.githubusercontent.com/45932283/102962960-e9e16700-4522-11eb-84b2-251e3d917fac.png)

**Comment by codeoflin** [comment]
![image](https://user-images.githubusercontent.com/45932283/102963189-75f38e80-4523-11eb-9f0d-3d8dfb21633a.png)

**Comment by Neilpang** [comment]
use `--renew`  for    the second time.
