### ISSUE TITLE
More flexibility when deploying cert to multiple hosts

### ISSUE THREAD

**Issue by jakelamotta** [acmesh-official/acme.sh#3319]
It is already possible to deploy to multiple hosts but the flexibility limits the usefulness of this feature. For our purposes the most important thing would be to use different users for the different hosts, also using different reload commands would be good though we have solved that by implementing a generic script on each host. 

Maybe the best way to do this would be to have a complete configuration for each individual host? Or maybe a solution similar to the current solution DEPLOY_SSH_SERVER for the given fields (quickly gets messy though)?

**Comment by marcoczen** [comment]
Hi ... How did you deploy to multiple hosts ? I would like to know ...

**Comment by jakelamotta** [comment]
> Hi ... How did you deploy to multiple hosts ? Is there a wiki page on this ?
> I would like to know ...

When deploying with the ssh deploy hook you can set the parameter DEPLOY_SSH_SERVER to a space separated list of hosts if I remember correctly. In the conf-file for the domain the host parameter would then be Le_Deploy_ssh_server="host1 host2 host3"

**Comment by marcoczen** [comment]
Hi,

> > Hi ... How did you deploy to multiple hosts ? Is there a wiki page on this ?
> > I would like to know ...
> 
> When deploying with the ssh deploy hook you can set the parameter DEPLOY_SSH_SERVER to a space separated list of hosts if I 
> remember correctly. In the conf-file for the domain the host parameter would then be Le_Deploy_ssh_server="host1 host2 host3"

Just for the next noob, with term ' DEPLOY_SSH_SERVER   ' , I  couldnt find anything at https://github.com/acmesh-official/acme.sh/wiki but however came across https://github.com/acmesh-official/acme.sh/issues/1406
and https://github.com/acmesh-official/acme.sh/wiki/Using-pre-hook-post-hook-renew-hook-reloadcmd

**Comment by jakelamotta** [comment]
> Hi,
> 
> > > Hi ... How did you deploy to multiple hosts ? Is there a wiki page on this ?
> > > I would like to know ...
> > 
> > 
> > When deploying with the ssh deploy hook you can set the parameter DEPLOY_SSH_SERVER to a space separated list of hosts if I
> > remember correctly. In the conf-file for the domain the host parameter would then be Le_Deploy_ssh_server="host1 host2 host3"
> 
> Just for the next noob, with term ' DEPLOY_SSH_SERVER ' , I couldnt find anything at https://github.com/acmesh-official/acme.sh/wiki but however came across;
> 
> https://github.com/acmesh-official/acme.sh/ issues/ 1406 ( #1406 )
> https://github.com/acmesh-official/acme.sh/wiki/Using-pre-hook-post-hook-renew-hook-reloadcmd
> https://github.com/acmesh-official/acme.sh/wiki/deployhooks
> 
> These links/potential solutions are above my threshold for the moment. I think will just run acme.sh separately on each host when i need certs for additional servers seeing that zerossl has no rate limits ?

Yes, it's under the deployhooks wiki, you can use 3. Deploy the cert to remote server through SSH access. to deploy to multiple servers. However they need to share user, destination file path and reload cmd. That's where the flexibility issue is imo.

**Comment by carmineyiu** [comment]
if i need update certification in openvpn, proxomox, and synology. and acme.sh renew task is in synology. So I need create 2 user-define script for SSH to openvpn and proxmox? schedule just after renewal?

**Comment by movy** [comment]
For those coming here from Google: 

To deploy acme.sh ssl certificates to multiple servers via SSH you'll need:

- same username, certificates location and remote cmd on all servers
- in your `~/.acme.sh/DOMAIN.NAME/DOMAIN.NAME.conf` add all servers addresses separated by space into `Le_Deploy_ssh_server` var, i.e:

```
Le_Deploy_ssh_user='ubuntu'
Le_Deploy_ssh_server='SUB1.DOMAIN.NAME SUB2.DOMAIN.NAME SUB3.DOMAIN.NAME'
Le_Deploy_ssh_backup='yes'
```

**Comment by Neilpang** [comment]
@gmccauley  write your own `mydeploy.sh`, and use `acme.sh --installcert -d example.com   --reloadcmd  /path/to/mydeploy.sh`

**Comment by mclovin-2k** [comment]
I got here from Google.
Is there a easy way to execute a command (for example: run "mkdir" to create a directory) before the copying of certificates?
