### ISSUE TITLE
Synology problem after updating to DSM 6.2.3-25426 Update 3

### ISSUE THREAD

**Issue by Marco4223** [acmesh-official/acme.sh#3321]
Hi,
after I updates my NAS to the latest version I get the following error when  try to update my certificate:
[Fri Dec 25 08:50:43 CET 2020] Your cert is in  /usr/local/share/acme.sh//*.huhu.info/*.huhu.info.cer
[Fri Dec 25 08:50:43 CET 2020] Your cert key is in  /usr/local/share/acme.sh//*.huhu.info/*.huhu.info.key
[Fri Dec 25 08:50:43 CET 2020] The intermediate CA cert is in  /usr/local/share/acme.sh//*.huhu.info/ca.cer
[Fri Dec 25 08:50:43 CET 2020] And the full chain certs is there:  /usr/local/share/acme.sh//*.huhu.info/fullchain.cer
[Fri Dec 25 08:50:43 CET 2020] Logging into localhost:5000
[Fri Dec 25 08:50:50 CET 2020] Unable to authenticate to localhost:5000 using http.
[Fri Dec 25 08:50:50 CET 2020] Check your username and password.
[Fri Dec 25 08:50:50 CET 2020] Error deploy for domain:*.huhu.info
[Fri Dec 25 08:50:50 CET 2020] Deploy error.
[Fri Dec 25 08:50:50 CET 2020] Error renew *.huhu.info.
[Fri Dec 25 08:50:50 CET 2020] ===End cron===

I trtied to update acme 
./acme.sh --force --upgrade --nocron --home /usr/local/share/acme.sh
and export the variables again with no success.

Did anyone facing the same issue?
Cheers
MarcO

Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

**Comment by Marco4223** [comment]
Found the issue. 
The exported password was broken.
For anyone who hit this: You can check this by using this:
./acme.sh --home [patch to acme.sh] --deploy --domain "yourdomain" --deploy-hook synology_dsm  --output-insecure --debug 3

Then you will find something like:
[Sun Jan  3 11:10:27 CET 2021] deploy/synology_dsm.sh:synology_dsm_deploy:47 SYNO_Username='admin'
[Sun Jan  3 11:10:27 CET 2021] SYNO_Password='[PASSWORD]'

Cheers

**Comment by Stan-Gobien** [comment]
I had the same error. 
In my case the password was still correct.
However that specific account has 2FA configured, maybe this is the reason this now fails.
I made a seperate account specifically for this purpose, without 2FA, and it worked fine again.
