### ISSUE TITLE
how to keep all info of subject name in CSR

### ISSUE THREAD

**Issue by AVOnMe** [acmesh-official/acme.sh#3325]
C  ST  and L  info are dropped in signed cert file.
I sign it with https://github.com/acmesh-official/acme.sh/wiki/Issue-a-cert-from-existing-CSR
![Capture3](https://user-images.githubusercontent.com/923519/103239988-5effd280-494f-11eb-8d37-18d603f24d92.PNG)

**Comment by AVOnMe** [comment]
problem solved. just figured it out in 5 minutes. I think,
line 1235 should be 
    ${ACME_OPENSSL_BIN:-openssl} req -new -sha256 -key "$csrkey" -config "$csrconf" -out "$csr"
then put  $domain.csr.conf in $DOMAIN_PATH, which is default to /home/$user/.acme.sh/$domain.
am I missing some part?

**Comment by Neilpang** [comment]
不对.

根本上讲,  letsencrypt 只提供了 DV 证书,   实际上它也仅仅之验证了 你的域名.  至于其它的字段ST, L 等等, letsencrypt 没有, 也无法验证, 所以它不被允许签署这些字段.

因此, 就算你在csr 中放了再多的字段, 最终的 cert 中, 也只会包含 cn 和域名. 其他的所有字段都会被丢弃.

**Comment by AVOnMe** [comment]
你生成的证书只有CN， 其他的可以有很多信息。按照我说的办法做的localhost的级联证书可以有其他字段

![Capture4](https://user-images.githubusercontent.com/923519/103254381-5e822e80-4985-11eb-9ac6-089d84aa3dba.PNG)

**Comment by Neilpang** [comment]
其实我本可以简单回答：    无论你在csr 里面放了多少信息，  letsencyrpt 返回的证书里面只有 cn

**Comment by AVOnMe** [comment]
https://github.com/diafygi/acme-tiny/    做的证书用的也是 letsencrypt    就能保留所有字段。你这个程序的毛病在于重新生成一次私钥和新的CSR。你为什么不提供办法用已有的私钥和CSR生成证书？ https://github.com/diafygi/acme-tiny/ 做的就是用我说的办法。

**Comment by Neilpang** [comment]
如果你用的这个方法： https://github.com/acmesh-official/acme.sh/wiki/Issue-a-cert-from-existing-CSR

CSR 就是使用的你提供的csr ，不会自动生成。

如果 letsencrypt 能签其他的字段， 麻烦提供已经签好的证书给我看看。

**Comment by AVOnMe** [comment]
刚查了几个过期的，是没有。所以问题不在你这个程序。谢谢答疑
