### ISSUE TITLE
Feature request: combined file option

### ISSUE THREAD

**Issue by bpwebnet** [acmesh-official/acme.sh#3341]
The Apache SSLCertificateFile directive allows a single file to contain the certificate, ca bundle and key, reducing the number of files opened when reading its configuration and improving performance. Please consider a '--combined-file' option that combines the key and full-chain files into one.

**Comment by Neilpang** [comment]
you can specify the same file for key-file and cert-file or ca-file.
acme.sh is smart enough to use the same file.
