### ISSUE TITLE
Revert from staging

### ISSUE THREAD

**Issue by lampaczcz** [acmesh-official/acme.sh#3344]
Hello,

is not possible to revert from staging to real. I deleted Le_LinkCert, Le_OrderFinalize, Le_LinkOrder, Le_API a then works, but without that staging was issued

acme.sh --renew --force -d mail.domain1.org 
[Čt led  7 09:11:08 CET 2021] Renew: 'mail.domain1.org'
[Čt led  7 09:11:09 CET 2021] Using CA: https://acme-staging-v02.api.letsencrypt.org/directory
[Čt led  7 09:11:09 CET 2021] Standalone mode.
[Čt led  7 09:11:09 CET 2021] Standalone mode.
[Čt led  7 09:11:09 CET 2021] Multi domain='DNS:mail.domain1.org,DNS:mail.domain2.org'
[Čt led  7 09:11:09 CET 2021] Getting domain auth token for each domain
[Čt led  7 09:11:12 CET 2021] Getting webroot for domain='mail.domain1.org'
[Čt led  7 09:11:13 CET 2021] Getting webroot for domain='mail.domain2.org'
[Čt led  7 09:11:13 CET 2021] mail.domain1.org is already verified, skip http-01.
[Čt led  7 09:11:13 CET 2021] mail.domain2.org is already verified, skip http-01.
[Čt led  7 09:11:13 CET 2021] Verify finished, start to sign.
[Čt led  7 09:11:13 CET 2021] Lets finalize the order.
[Čt led  7 09:11:13 CET 2021] Le_OrderFinalize='https://acme-staging-v02.api.letsencrypt.org/acme/finalize/13169497/215777921'
[Čt led  7 09:11:14 CET 2021] Downloading cert.
[Čt led  7 09:11:14 CET 2021] Le_LinkCert='https://acme-staging-v02.api.letsencrypt.org/acme/cert/fa08827721fbac598f85d62b387a39bbd599'
[Čt led  7 09:11:15 CET 2021] Cert success.

**Comment by Neilpang** [comment]
actually from the ACME protocol level, there is not a `Staging` server at all.
Letsencrypt just provided 2 endpoints: one for production and one for staging.

So, when you renew a cert,  acme.sh only knows how to renew it from the recorded endpoint, from which the cert was issued previously.   It can not tell whether it's a "Staging" endpoint at all.

If you want to change the endpoint, please use `--issue` command to issue the cert again with the production endpoint.
Don't use `--renew`
