### ISSUE TITLE
ECDSA cert to PKcs

### ISSUE THREAD

**Issue by JMC-PK** [acmesh-official/acme.sh#3346]
Is there a way to export an ECDSA cert to PKcs?

I have both RSA-4096 and ECC-384 certs generated. 

The --toPKcs command makes a pfx file for the RSA-4096 cert by default.
I tried adding a '-k ec-384' to the --toPKcs command but that still just used the RSA-4096 cert instead (at least I assume so the path displayed by the success message is the non-ecc path).

**Comment by JMC-PK** [comment]
Note you can manually generate this with:


openssl pkcs12 -export \\
	-out /home/deploy/.acme.sh/performancekeys.com_ecc/performancekeys.com.pfx \\
	-inkey /home/deploy/.acme.sh/performancekeys.com_ecc/performancekeys.com.key \\
	-in /home/deploy/.acme.sh/performancekeys.com_ecc/fullchain.cer

**Comment by Neilpang** [comment]
please add `--ecc` options

```
acme.sh --topkcs ......   --ecc
```
