### ISSUE TITLE
ACME trying to verify "com" as a domain

### ISSUE THREAD

**Issue by Tequenikality** [acmesh-official/acme.sh#3348]
Steps to reproduce
Issue a multi-domain cert while using Dynu DNS. The script calls "https://api.dynu.com/v2/dns/getroot/com" for some reason.

Debug log
-----------------
[Sat  9 Jan 07:31:10 GMT 2021] Running cmd: issue
[Sat  9 Jan 07:31:10 GMT 2021] _main_domain='luxoticlingerieandswimwear.com'
[Sat  9 Jan 07:31:10 GMT 2021] _alt_domains='webmail.luxoticlingerieandswimwear.com'
[Sat  9 Jan 07:31:10 GMT 2021] Using config home:/home/brandon/.acme.sh
[Sat  9 Jan 07:31:10 GMT 2021] default_acme_server
[Sat  9 Jan 07:31:10 GMT 2021] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Sat  9 Jan 07:31:10 GMT 2021] DOMAIN_PATH='/home/brandon/.acme.sh/luxoticlingerieandswimwear.com'
[Sat  9 Jan 07:31:10 GMT 2021] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Sat  9 Jan 07:31:10 GMT 2021] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Sat  9 Jan 07:31:10 GMT 2021] GET
[Sat  9 Jan 07:31:10 GMT 2021] url='https://acme-v02.api.letsencrypt.org/directory'
[Sat  9 Jan 07:31:10 GMT 2021] timeout=
[Sat  9 Jan 07:31:10 GMT 2021] _CURL='curl --silent --dump-header /home/brandon/.acme.sh/http.header  -L  -g '
[Sat  9 Jan 07:31:11 GMT 2021] ret='0'
[Sat  9 Jan 07:31:11 GMT 2021] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Sat  9 Jan 07:31:11 GMT 2021] ACME_NEW_AUTHZ
[Sat  9 Jan 07:31:11 GMT 2021] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Sat  9 Jan 07:31:11 GMT 2021] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Sat  9 Jan 07:31:11 GMT 2021] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Sat  9 Jan 07:31:11 GMT 2021] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Sat  9 Jan 07:31:11 GMT 2021] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Sat  9 Jan 07:31:11 GMT 2021] ACME_VERSION='2'
[Sat  9 Jan 07:31:11 GMT 2021] Le_NextRenewTime
[Sat  9 Jan 07:31:11 GMT 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sat  9 Jan 07:31:11 GMT 2021] _on_before_issue
[Sat  9 Jan 07:31:11 GMT 2021] _chk_main_domain='luxoticlingerieandswimwear.com'
[Sat  9 Jan 07:31:11 GMT 2021] _chk_alt_domains='webmail.luxoticlingerieandswimwear.com'
[Sat  9 Jan 07:31:11 GMT 2021] Le_LocalAddress
[Sat  9 Jan 07:31:11 GMT 2021] d='luxoticlingerieandswimwear.com'
[Sat  9 Jan 07:31:11 GMT 2021] Check for domain='luxoticlingerieandswimwear.com'
[Sat  9 Jan 07:31:11 GMT 2021] _currentRoot='dns_dynu'
[Sat  9 Jan 07:31:11 GMT 2021] d='webmail.luxoticlingerieandswimwear.com'
[Sat  9 Jan 07:31:11 GMT 2021] Check for domain='webmail.luxoticlingerieandswimwear.com'
[Sat  9 Jan 07:31:11 GMT 2021] _currentRoot='dns_dynu'
[Sat  9 Jan 07:31:11 GMT 2021] d
[Sat  9 Jan 07:31:11 GMT 2021] _saved_account_key_hash is not changed, skip register account.
[Sat  9 Jan 07:31:11 GMT 2021] Read key length:
[Sat  9 Jan 07:31:11 GMT 2021] _createcsr
[Sat  9 Jan 07:31:11 GMT 2021] Multi domain='DNS:luxoticlingerieandswimwear.com,DNS:webmail.luxoticlingerieandswimwear.com'
[Sat  9 Jan 07:31:11 GMT 2021] Getting domain auth token for each domain
[Sat  9 Jan 07:31:11 GMT 2021] d='webmail.luxoticlingerieandswimwear.com'
[Sat  9 Jan 07:31:11 GMT 2021] d
[Sat  9 Jan 07:31:11 GMT 2021] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Sat  9 Jan 07:31:11 GMT 2021] payload='{"identifiers": [{"type":"dns","value":"luxoticlingerieandswimwear.com"},{"type":"dns","value":"webmail.luxoticlingerieandswimwear.com"}]}'
[Sat  9 Jan 07:31:11 GMT 2021] RSA key
[Sat  9 Jan 07:31:11 GMT 2021] HEAD
[Sat  9 Jan 07:31:11 GMT 2021] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Sat  9 Jan 07:31:11 GMT 2021] _CURL='curl --silent --dump-header /home/brandon/.acme.sh/http.header  -L  -g  -I  '
[Sat  9 Jan 07:31:12 GMT 2021] _ret='0'
[Sat  9 Jan 07:31:12 GMT 2021] POST
[Sat  9 Jan 07:31:12 GMT 2021] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Sat  9 Jan 07:31:12 GMT 2021] _CURL='curl --silent --dump-header /home/brandon/.acme.sh/http.header  -L  -g '
[Sat  9 Jan 07:31:12 GMT 2021] _ret='0'
[Sat  9 Jan 07:31:12 GMT 2021] code='201'
[Sat  9 Jan 07:31:12 GMT 2021] Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/103320095/7210213262'
[Sat  9 Jan 07:31:12 GMT 2021] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/103320095/7210213262'
[Sat  9 Jan 07:31:12 GMT 2021] url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/9937871704'
[Sat  9 Jan 07:31:12 GMT 2021] payload
[Sat  9 Jan 07:31:12 GMT 2021] POST
[Sat  9 Jan 07:31:12 GMT 2021] _post_url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/9937871704'
[Sat  9 Jan 07:31:12 GMT 2021] _CURL='curl --silent --dump-header /home/brandon/.acme.sh/http.header  -L  -g '
[Sat  9 Jan 07:31:13 GMT 2021] _ret='0'
[Sat  9 Jan 07:31:13 GMT 2021] code='200'
[Sat  9 Jan 07:31:13 GMT 2021] url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/9937871708'
[Sat  9 Jan 07:31:13 GMT 2021] payload
[Sat  9 Jan 07:31:13 GMT 2021] POST
[Sat  9 Jan 07:31:13 GMT 2021] _post_url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/9937871708'
[Sat  9 Jan 07:31:13 GMT 2021] _CURL='curl --silent --dump-header /home/brandon/.acme.sh/http.header  -L  -g '
[Sat  9 Jan 07:31:14 GMT 2021] _ret='0'
[Sat  9 Jan 07:31:14 GMT 2021] code='200'
[Sat  9 Jan 07:31:14 GMT 2021] d='luxoticlingerieandswimwear.com'
[Sat  9 Jan 07:31:14 GMT 2021] Getting webroot for domain='luxoticlingerieandswimwear.com'
[Sat  9 Jan 07:31:14 GMT 2021] _w='dns_dynu'
[Sat  9 Jan 07:31:14 GMT 2021] _currentRoot='dns_dynu'
[Sat  9 Jan 07:31:14 GMT 2021] entry='"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/9937871704/ZDOhuw","token":"qe9YRv5f8lTerrpPvFNyywRsH-0920fMYURukbK_SMU"'
[Sat  9 Jan 07:31:14 GMT 2021] token='qe9YRv5f8lTerrpPvFNyywRsH-0920fMYURukbK_SMU'
[Sat  9 Jan 07:31:14 GMT 2021] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/9937871704/ZDOhuw'
[Sat  9 Jan 07:31:14 GMT 2021] keyauthorization='qe9YRv5f8lTerrpPvFNyywRsH-0920fMYURukbK_SMU.9eauLQN5VXGWJmDAl5baSzEHzAJ1UvzhV5pNP5WxZls'
[Sat  9 Jan 07:31:14 GMT 2021] dvlist='luxoticlingerieandswimwear.com#qe9YRv5f8lTerrpPvFNyywRsH-0920fMYURukbK_SMU.9eauLQN5VXGWJmDAl5baSzEHzAJ1UvzhV5pNP5WxZls#https://acme-v02.api.letsencrypt.org/acme/chall-v3/9937871704/ZDOhuw#dns-01#dns_dynu'
[Sat  9 Jan 07:31:14 GMT 2021] d='webmail.luxoticlingerieandswimwear.com'
[Sat  9 Jan 07:31:14 GMT 2021] Getting webroot for domain='webmail.luxoticlingerieandswimwear.com'
[Sat  9 Jan 07:31:14 GMT 2021] _w='dns_dynu'
[Sat  9 Jan 07:31:14 GMT 2021] _currentRoot='dns_dynu'
[Sat  9 Jan 07:31:14 GMT 2021] entry='"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/9937871708/vEHzgw","token":"N4C7vXGsFaJygmHMw0lRQRzxfUUJhf7aZNfavSkAB7M"'
[Sat  9 Jan 07:31:14 GMT 2021] token='N4C7vXGsFaJygmHMw0lRQRzxfUUJhf7aZNfavSkAB7M'
[Sat  9 Jan 07:31:14 GMT 2021] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/9937871708/vEHzgw'
[Sat  9 Jan 07:31:14 GMT 2021] keyauthorization='N4C7vXGsFaJygmHMw0lRQRzxfUUJhf7aZNfavSkAB7M.9eauLQN5VXGWJmDAl5baSzEHzAJ1UvzhV5pNP5WxZls'
[Sat  9 Jan 07:31:14 GMT 2021] dvlist='webmail.luxoticlingerieandswimwear.com#N4C7vXGsFaJygmHMw0lRQRzxfUUJhf7aZNfavSkAB7M.9eauLQN5VXGWJmDAl5baSzEHzAJ1UvzhV5pNP5WxZls#https://acme-v02.api.letsencrypt.org/acme/chall-v3/9937871708/vEHzgw#dns-01#dns_dynu'
[Sat  9 Jan 07:31:14 GMT 2021] d
[Sat  9 Jan 07:31:14 GMT 2021] vlist='luxoticlingerieandswimwear.com#qe9YRv5f8lTerrpPvFNyywRsH-0920fMYURukbK_SMU.9eauLQN5VXGWJmDAl5baSzEHzAJ1UvzhV5pNP5WxZls#https://acme-v02.api.letsencrypt.org/acme/chall-v3/9937871704/ZDOhuw#dns-01#dns_dynu,webmail.luxoticlingerieandswimwear.com#N4C7vXGsFaJygmHMw0lRQRzxfUUJhf7aZNfavSkAB7M.9eauLQN5VXGWJmDAl5baSzEHzAJ1UvzhV5pNP5WxZls#https://acme-v02.api.letsencrypt.org/acme/chall-v3/9937871708/vEHzgw#dns-01#dns_dynu,'
[Sat  9 Jan 07:31:14 GMT 2021] d='luxoticlingerieandswimwear.com'
[Sat  9 Jan 07:31:14 GMT 2021] _d_alias
[Sat  9 Jan 07:31:14 GMT 2021] txtdomain='_acme-challenge.luxoticlingerieandswimwear.com'
[Sat  9 Jan 07:31:14 GMT 2021] txt='NfcuD7HYd76gqj98iEkcWRm3mtgXpX7NlJduoWVdbm4'
[Sat  9 Jan 07:31:14 GMT 2021] d_api='/home/brandon/.acme.sh/dnsapi/dns_dynu.sh'
[Sat  9 Jan 07:31:14 GMT 2021] Found domain api file: /home/brandon/.acme.sh/dnsapi/dns_dynu.sh
[Sat  9 Jan 07:31:14 GMT 2021] Adding txt value: NfcuD7HYd76gqj98iEkcWRm3mtgXpX7NlJduoWVdbm4 for domain:  _acme-challenge.luxoticlingerieandswimwear.com
[Sat  9 Jan 07:31:14 GMT 2021] Detect root zone
[Sat  9 Jan 07:31:14 GMT 2021] h='luxoticlingerieandswimwear.com'
[Sat  9 Jan 07:31:14 GMT 2021] dns/getroot/luxoticlingerieandswimwear.com
[Sat  9 Jan 07:31:14 GMT 2021] Getting https://api.dynu.com/v2/dns/getroot/luxoticlingerieandswimwear.com
[Sat  9 Jan 07:31:14 GMT 2021] GET
[Sat  9 Jan 07:31:14 GMT 2021] url='https://api.dynu.com/v2/dns/getroot/luxoticlingerieandswimwear.com'
[Sat  9 Jan 07:31:14 GMT 2021] timeout=
[Sat  9 Jan 07:31:14 GMT 2021] _CURL='curl --silent --dump-header /home/brandon/.acme.sh/http.header  -L  -g '
[Sat  9 Jan 07:31:15 GMT 2021] ret='0'
[Sat  9 Jan 07:31:15 GMT 2021] h='com'
[Sat  9 Jan 07:31:15 GMT 2021] dns/getroot/com
[Sat  9 Jan 07:31:15 GMT 2021] Getting https://api.dynu.com/v2/dns/getroot/com
[Sat  9 Jan 07:31:15 GMT 2021] GET
[Sat  9 Jan 07:31:15 GMT 2021] url='https://api.dynu.com/v2/dns/getroot/com'
[Sat  9 Jan 07:31:15 GMT 2021] timeout=
[Sat  9 Jan 07:31:15 GMT 2021] _CURL='curl --silent --dump-header /home/brandon/.acme.sh/http.header  -L  -g '
[Sat  9 Jan 07:31:15 GMT 2021] ret='0'
[Sat  9 Jan 07:31:15 GMT 2021] h
[Sat  9 Jan 07:31:15 GMT 2021] Invalid domain.
[Sat  9 Jan 07:31:15 GMT 2021] Error add txt for domain:_acme-challenge.luxoticlingerieandswimwear.com
[Sat  9 Jan 07:31:15 GMT 2021] _on_issue_err
[Sat  9 Jan 07:31:15 GMT 2021] Please check log file for more details: /home/brandon/.acme.sh/acme.sh.log
[Sat  9 Jan 07:31:15 GMT 2021] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/9937871704/ZDOhuw'
[Sat  9 Jan 07:31:15 GMT 2021] payload='{}'
[Sat  9 Jan 07:31:15 GMT 2021] POST
[Sat  9 Jan 07:31:15 GMT 2021] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/9937871704/ZDOhuw'
[Sat  9 Jan 07:31:15 GMT 2021] _CURL='curl --silent --dump-header /home/brandon/.acme.sh/http.header  -L  -g '
[Sat  9 Jan 07:31:16 GMT 2021] _ret='0'
[Sat  9 Jan 07:31:16 GMT 2021] code='200'
[Sat  9 Jan 07:31:16 GMT 2021] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/9937871708/vEHzgw'
[Sat  9 Jan 07:31:16 GMT 2021] payload='{}'
[Sat  9 Jan 07:31:16 GMT 2021] POST
[Sat  9 Jan 07:31:16 GMT 2021] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/9937871708/vEHzgw'
[Sat  9 Jan 07:31:16 GMT 2021] _CURL='curl --silent --dump-header /home/brandon/.acme.sh/http.header  -L  -g '
[Sat  9 Jan 07:31:17 GMT 2021] _ret='0'
[Sat  9 Jan 07:31:17 GMT 2021] code='200'
[Sat  9 Jan 07:31:17 GMT 2021] pid
[Sat  9 Jan 07:31:17 GMT 2021] No need to restore nginx, skip.
[Sat  9 Jan 07:31:17 GMT 2021] _clearupdns
[Sat  9 Jan 07:31:17 GMT 2021] dns_entries
[Sat  9 Jan 07:31:17 GMT 2021] skip dns.

**Comment by Neilpang** [comment]
please give me the log with `--debug 2`
