### ISSUE TITLE
support for using dns.he.net ddns keys

### ISSUE THREAD

**Issue by coreybrett** [acmesh-official/acme.sh#3355]
is it possible to use the ddns record keys instead of the account username/password?

**Comment by bcsanford** [comment]
I'm going to go out on a limb here and say No.
This is based on the fact that acme.sh wants to be able to create the record and then remove it when done, See DNSAPI requirements.
DDNS Keys only allow you to update an existing Record this means you will need to manually create the record in advance for it to even function.

**Comment by coreybrett** [comment]
Seems like the DNS alias mode could be used to work around this.

**Comment by pmarks-net** [comment]
Pull request: https://github.com/acmesh-official/acme.sh/pull/4318
