### ISSUE TITLE
Acme.sh doesn't use the ISRG x1 root certificate by default

### ISSUE THREAD

**Issue by sich97** [acmesh-official/acme.sh#3362]
On Jan 11, letsencrypt made their 2016 registered ISRG x1 root certificate the default root certificate for new letsencrypt certificates. Certbot has apparently changed to reflect this decision, and should now serve the new root certificate.
Yesterday I tried using acme.sh for a new certificate. But it turned out to use the DST x3 cross-signed certificate.

**Comment by Neilpang** [comment]
I don't think so.

I just tried.  the default chain letsencrypt sent is the DST chain,  not the ISRG chain.

you can use this `--preferred-chain` option to select the chain you like:

https://github.com/acmesh-official/acme.sh/wiki/Preferred-Chain
