### ISSUE TITLE
Why do all DNS API use _*accountconf_mutable instead of _*accountconf?

### ISSUE THREAD

**Issue by Eagle3386** [acmesh-official/acme.sh#3371]
Currently, I'm developing a new 3rd party DNS API for ACME.sh & while doing so, I came across two questions which sadly neither DuckDuckGo.com, nor the existing issues, nor this repo's Wiki do answer:

1. Virtually _every_ 3rd party DNS API use `_readaccountconf_mutable` & `_saveaccountconf_mutable` instead of the also existing (& also ultimately called by them anyway) `_readaccountconf` & `_saveaccountconf` - why is that?
Especially since the [Wiki](https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Dev-Guide#2-you-must-save-your-username-and-password-in-the-add-function) suggests to use the former while looking at the code https://github.com/acmesh-official/acme.sh/blob/b7a3fe05a4d8a9041159b4a773b35003166f0af0/acme.sh#L2260-L2264 suggests that doing so, clears the data right after saving as `#remove later` hints at kinda "workaround solution" regarding its follow-up line.

2. Since I'm kinda Linux/Unix "Padawan", I strongly obey the DNS API dev guide's rule of being a [`unix shell script, not just a bash script`](https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Dev-Guide#4-the-file-shebang-must-be-sh-not-bash), i. e. forbids usages of `${parameter#*.}` as such parameter expansion is a `BASH` feature.
Yet the "blueprint" I initially chose for development, `ISPConfig`, does https://github.com/acmesh-official/acme.sh/blob/b7a3fe05a4d8a9041159b4a773b35003166f0af0/dnsapi/dns_ispconfig.sh#L73-L74 which is exactly such usage, isn't it?

Any clarification and/or help would be greatly appreciated!

**Comment by Neilpang** [comment]
>> Virtually every 3rd party DNS API use _readaccountconf_mutable & _saveaccountconf_mutable

Take a look at the word `mutable`.     If your dns password is changed in the future,  how to change it for acme.sh ?



>> Since I'm kinda Linux/Unix "Padawan", I strongly obey the DNS API dev guide's rule of being 

Good.  please keep following this rule.  
There can be missings when reviewing code.

Thanks.

**Comment by Eagle3386** [comment]
> Take a look at the word `mutable`. If your dns password is changed in the future, how to change it for acme.sh ?

I do understand that meaning. Though, that doesn't clarify my question regarding `#remove later` & its follow-up line `_clearaccountconf "$1"` (see quoted lines 2260-2264 in my OP for context).
In other words: where can I find saved username/password as line 2262/2263 seem to delete stored username/password right after saving it just 1 line before, in line 2261? 😕

> Good. please keep following this rule.
> There can be missings when reviewing code.

Sure, but just to be 100% sure: can I use `${parameter#*.}` in my 3rd party API plugin, just like the ISPConfig plugin does with `curZone="${curZone#*.}"`?

> Thanks.

My pleasure. 😃

**Comment by Neilpang** [comment]
>> I do understand that meaning. Though, that doesn't clarify my question reg

Take a look at `~/.acme.sh/account.conf`,  it's saved here.

>> ${parameter#*.}

Yes.

**Comment by Eagle3386** [comment]
> Take a look at `~/.acme.sh/account.conf`, it's saved here.

Found a mistake in script, hence no saved username/password. Thanks!

> > ${parameter#*.}
> 
> Yes.

Sorry to bother you yet again, but it's still unclear:
"Yes, `${parameter#*.}` can be used."
or
"Yes, `${parameter#*.}` is forbidden"?

**Comment by Neilpang** [comment]
"Yes, ${parameter#*.} can be used."
