### ISSUE TITLE
 multi domain use diffrent DNS api cannot issue

### ISSUE THREAD

**Issue by 10664** [acmesh-official/acme.sh#3372]
/root/.acme.sh/acme.sh --force --issue -d zixia.com -d '*.zixia.com' -d '*.game.zixia.com' -d alibaby.net -d '*.alibaby.net' -d xigu.com -d '*.xigu.com'  -d 71dm.com -d '*.71dm.com' -d paipaitxt.com -d '*.paipaitxt.com' --dns dns_dp  -d paipai.fm -d '*.paipai.fm' -d houdao.com -d '*.houdao.com' -d 51zixia.com -d '*.51zixia.com' --dns dns_ali 

but only zixia.com use dns_dp, the other domains all use dns_ali

**Comment by 10664** [comment]
@Neilpang can you help me

**Comment by Neilpang** [comment]
如果你想使用不同的 dns api.   你必须为 每一个域名指定一个 api.   即使是重复指定.  
所以, 你有几个域名, 就要指定几个  --dns api.   如果是相同的, 就指定一样的.

**Comment by 10664** [comment]
还是一样的问题
it's also problem , if I use command as this
/root/.acme.sh/acme.sh --force --issue -d zixia.com --dns dns_dp -d '*.zixia.com' --dns dns_dp -d '*.game.zixia.com' --dns dns_dp -d alibaby.net --dns dns_dp -d '*.alibaby.net' --dns dns_dp -d xigu.com --dns dns_dp -d '*.xigu.com'  --dns dns_dp -d 71dm.com --dns dns_dp -d '*.71dm.com' --dns dns_dp -d paipaitxt.com --dns dns_dp -d '*.paipaitxt.com' --dns dns_dp  -d paipai.fm --dns dns_ali -d '*.paipai.fm' --dns dns_ali -d houdao.com --dns dns_ali -d '*.houdao.com' --dns dns_ali -d 51zixia.com --dns dns_ali -d '*.51zixia.com' --dns dns_ali

**Comment by 10664** [comment]
@Neilpang 老大再看看，我尝试过这样运行，还是一样，只有zixia.com 使用了dnspod，其它全部用了ali

**Comment by 10664** [comment]
上个月都没问题，用/root/.acme.sh/acme.sh --force --issue -d zixia.com -d '.zixia.com' -d '.game.zixia.com' -d alibaby.net -d '.alibaby.net' -d xigu.com -d '.xigu.com' -d 71dm.com -d '.71dm.com' -d paipaitxt.com -d '.paipaitxt.com' --dns dns_dp -d paipai.fm -d '.paipai.fm' -d houdao.com -d '.houdao.com' -d 51zixia.com -d '*.51zixia.com' --dns dns_ali
但今天出问题了。
就算用
/root/.acme.sh/acme.sh --force --issue -d zixia.com --dns dns_dp -d '.zixia.com' --dns dns_dp -d '.game.zixia.com' --dns dns_dp -d alibaby.net --dns dns_dp -d '.alibaby.net' --dns dns_dp -d xigu.com --dns dns_dp -d '.xigu.com' --dns dns_dp -d 71dm.com --dns dns_dp -d '.71dm.com' --dns dns_dp -d paipaitxt.com --dns dns_dp -d '.paipaitxt.com' --dns dns_dp -d paipai.fm --dns dns_ali -d '.paipai.fm' --dns dns_ali -d houdao.com --dns dns_ali -d '.houdao.com' --dns dns_ali -d 51zixia.com --dns dns_ali -d '*.51zixia.com' --dns dns_ali
一样还是不行

**Comment by Neilpang** [comment]
你可以先缩短.  少几个域名,  然后一个一个晚上加.

**Comment by 10664** [comment]
老大，加个微信吧。我不太懂你的意思。这些域名我想用一个证书啊，不想分开

**Comment by 10664** [comment]
如果是
/root/.acme.sh/acme.sh --force --issue -d zixia.com --dns dns_dp 
/root/.acme.sh/acme.sh --force --issue -d '.game.zixia.com' --dns dns_dp
这样一行行运行，最后发布的时候，只能发布最后1个域名的证书，而不是全部

**Comment by Neilpang** [comment]
我知道你想用一个证书.

```
acme.sh  --issue  -d  a.com  --dns dns_dp

acme.sh  --issue  -d  a.com  --dns dns_dp  -d b.com  --dns dns_dp

acme.sh  --issue  -d  a.com  --dns dns_dp  -d b.com  --dns dns_dp  -d c.com   --dns dns_dp


```

**Comment by Neilpang** [comment]
每次 逐个添加. 确保你没把 命令行写错了.
