### ISSUE TITLE
Regarding --preferred-chain and upcoming Let's Encrypt root CA changes

### ISSUE THREAD

**Issue by sahsanu** [acmesh-official/acme.sh#3384]
Let's Encrypt [will change the default chain](https://community.letsencrypt.org/t/openssl-client-compatibility-changes-for-let-s-encrypt-certificates/143816) to extend Android's compatibility using a long chain (`Subscriber Certificate <– R3 <– ISRG Root X1 <– DST Root CA X3`) but in my case I must use only the alternate and short chain (`Subscriber Certificate <– R3 <– ISRG Root X1`) because I manage some old systems using openssl 1.0.1 and this version is not compatible with the long chain (well, I'll also use it on systems that manage the long chain because I don't need to support old Android devices).

So when this change happens (**ISRG Root X1 will appear on both chains**) so I'm wondering whether acme.sh will select the right chain using option `--preferred-chain "ISRG Root X1"`. I'm asking because other clients like certbot have [fixed the way they iterated the chains](https://github.com/certbot/certbot/pull/8596) to find the right one checking only the root name.

Thank you in advance.

**Comment by Neilpang** [comment]
I will fix it soon.

**Comment by Neilpang** [comment]
fixed  please give it a try with the `chain` branch.

```
acme.sh --upgrade -b chain
```

The preferred chain will only match the  ROOT CA subject name(the last CA cert),   any intermediate CA subject will not be used.

Thanks.

**Comment by sahsanu** [comment]
Hello,

I've tested it using `--preferred-chain  "ISRG Root X1"` and now it creates several `.alt` files:

```
-rw-r--r-- 1 root root 1587 feb 12 18:21 ca.cer
-rw-r--r-- 1 root root 1827 feb 12 18:21 ca.cer.alt
-rw-r--r-- 1 root root 1846 feb 12 18:21 sub.domain.tld.cer
-rw-r--r-- 1 root root 1846 feb 12 18:21 sub.domain.tld.cer.alt
-rw-r--r-- 1 root root  732 feb 12 18:21 sub.domain.tld.conf
-rw-r--r-- 1 root root  980 feb 12 18:21 sub.domain.tld.csr
-rw-r--r-- 1 root root  211 feb 12 18:21 sub.domain.tld.csr.conf
-rw-r--r-- 1 root root 1679 feb 12 18:21 sub.domain.tld.key
-rw-r--r-- 1 root root 3433 feb 12 18:21 fullchain.cer
-rw-r--r-- 1 root root 3673 feb 12 18:21 fullchain.cer.alt
```
As I'm using `--preferred-chain  "ISRG Root X1"` I expected `ca.cer` was the intermediate cert signed by ISRG but it is the one signed by DST. The one signed by ISRG is the alternate one `ca.cer.alt`

```
$ openssl x509 -in ca.cer -noout  -issuer
issuer=O = Digital Signature Trust Co., CN = DST Root CA X3

$ openssl x509 -in ca.cer.alt -noout  -issuer
issuer=C = US, O = Internet Security Research Group, CN = ISRG Root X1
```

Thank you.

**Comment by Neilpang** [comment]
fixed, please try again.

```
acme.sh  --upgrade -b chain
```

**Comment by sahsanu** [comment]
I've tested it with the new version and `ca.cer` is now the one signed by **ISRG** but `ca.cer.alt` is the same certificate, it is also signed by **ISRG** instead of **DST**.

```
$ openssl x509 -in ca.cer -noout -issuer
issuer=C = US, O = Internet Security Research Group, CN = ISRG Root X1
$ openssl x509 -in ca.cer.alt -noout -issuer
issuer=C = US, O = Internet Security Research Group, CN = ISRG Root X1
```

Thanks for your work.
