### ISSUE TITLE
Question - AWS creds per certificate

### ISSUE THREAD

**Issue by thalios1973** [acmesh-official/acme.sh#3389]
Hi. Not a bug. I've dug around a bit in the wiki and issues, but I haven't found anything. I feel I'm missing something quite obvious. At the risk of look stupid...

With acme.sh and the aws dnsapi as the keystones, I've built a simple management engine for the various certs we use on our network. They're issued/renewed and automagically updated to our vault where further automation can occur. It's all working well. acme.sh is simple and easy to work with.

But we've run into a problem. We now need to account for different AWS creds in this system. Prior to this, all of our DNS zones were hosted in the same AWS account, so the single set of AWS credentials sufficed. Now we will have 3 - 5 other AWS accounts in the mix. I'm trying to figure out if there is a way to specify AWS creds as part of the cert config or some other similar mechanism.

I thought maybe an `Le_` variable in the <certificate>.conf file might exist, but I can't seem to find anything. Not sure.

Any insight would be helpful. Thank you.

**Comment by Neilpang** [comment]
There are many ways to provide multiple creds for the same api.

The creds are stored in the `~/.acme.sh/account.conf`.
 
1. The simplest way is to create different linux user,  and install/run acme.sh as different users.
    ```
    For userA:
    su userA
    curl https://get.acme.sh | sh

    export AWSA_credxxxxxx=xxxxxx
    export AWSA_dddddd=dddddd
     acme.sh --issue .......  --dns dns_aws

    Do the same as userB.

    ```
2. you can specify different `account.conf` files.

    if you don't want to use multiple users,  you can specify different `account.conf`
    
    ```
    export AWSA_credxxxxx=xxxxx
    export AWSA_xxxxx=ddddd
    acme.sh. --issue ............  --dns dns_aws     --accountconf   ~/.acme.sh/accountA.conf

    export AWSB_xxxxx=xxxxx
    export AWSB_dddd=dddddd
    acme.sh. --issue ............  --dns dns_aws     --accountconf   ~/.acme.sh/accountB.conf


    You will also need to create 2 new crontab entries with the `--accountconf` parameter:

    19 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh"  --account /root/.acme.sh/accountA.conf  > /dev/null
    19 1 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh"  --account /root/.acme.sh/accountA.conf   > /dev/null

    ```
3. you can specify different `--config-home`.
    
    This is almost same as the above, just use `--config-home`
    ```
    ```
    export AWSA_credxxxxx=xxxxx
    export AWSA_xxxxx=ddddd
    acme.sh. --issue ............  --dns dns_aws     --accountconf   ~/.acme.sh/configA

    export AWSB_xxxxx=xxxxx
    export AWSB_dddd=dddddd
    acme.sh. --issue ............  --dns dns_aws     --accountconf   ~/.acme.sh/configB


    You will also need to create 2 new crontab entries with the `--accountconf` parameter:

    19 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh"  --account /root/.acme.sh/configA  > /dev/null
    19 1 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh"  --account /root/.acme.sh/configB  > /dev/null

    ```
    ```

**Comment by thalios1973** [comment]
I was thinking something like this would be the way to go. It's good to see your view on this before I begin. Thank you Neil.
