### ISSUE TITLE
Required  Outgoing Hosts/Proxies For ACME to Work

### ISSUE THREAD

**Issue by marcoczen** [acmesh-official/acme.sh#3404]
Hi guys,    

Certbot was problematic for me but Acme  saved my bum as I wanted to get a wildcard cert via DNS Challenge  on a non standard https port. Acme has done few renewals successfully as well and i made a small donation recently to support this developer's fine work !

The issue i  am currently having is that once I moved my home server into a DMZ ( behind a pfsense firewall where outgoing connections need to be defined specifically ) and I  alllowed connections to github.com,    

acme upgrade  (  ./acme.sh --upgrade  ) failed with message:     

Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 7
( Failed to connect() to host or proxy )

I was suprised as i had already allowed github.com.    
Do i need to allow access to other sites as well beside github for acme to upgrade?

Can i run './acme.sh --upgrade' in debug mode so that i can see what  host/proxy  its trying to connect to ?

And later, when acme does the next cert renewal, what sites/hosts/proxies  do i have to allow ?

Kindly advice pls.

**Comment by Neilpang** [comment]
>> Can i run './acme.sh --upgrade' in debug mode so that i can see what host/proxy its trying to connect to ?

Yes, sure


>> And later, when acme does the next cert renewal, what sites/hosts/proxies do i have to allow ?

I will only need the hosts that the `--issue` command needs.

**Comment by marcoczen** [comment]
Hi ... So how do i run the ./acme.sh --upgrade in debug mode ?

I have tried './acme.sh --upgrade debug' but unsuccessful....wait...
found the page at https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh

So its  ' ./acme.sh --upgrade --debug  '  actually

Looks like we need;

acme-v02.api.letsencrypt.org
api.github.com
github.com

**Comment by marcoczen** [comment]
Hmmm ... did not work ... so i ran  ' ./acme.sh --upgrade --debug 3' for more output...
and saw codeload.github.com, cacerts.digicert.com, crl3.digicert.com,   crl4.digicert.com,  ocsp.digicert.com,   www.digicert.com and few more ...

I think i better KIV this for now ... hehehehe ...

**Comment by marcoczen** [comment]
Hi .. wondering if anyone has figured out all the external hosts that we need to allow ( outbound )
to ensure that cert issueance / renewals work properly ?

**Comment by marcoczen** [comment]
Closing. Just cant get the neeeded info. Thanks anyway.
