### ISSUE TITLE
Can't request  a wildcard certificate

### ISSUE THREAD

**Issue by onlyJinx** [acmesh-official/acme.sh#3405]
Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```
现在还可以申请通配符证书吗? 我用通配符后提示参数有问题, 是操作问题试试脚本不再支持通配符, 谢谢.

![mo](https://user-images.githubusercontent.com/21324835/107737605-bb705300-6d3f-11eb-8abe-8175d36c1cbd.png)

**Comment by sahsanu** [comment]
Your shell is expanding the wildcard, quote your domain: `-d '*.yourdomain.tld'`

**Comment by onlyJinx** [comment]
Yes, you are right. This problem has been solved. Thank you very much
