### ISSUE TITLE
Intermediate Cert For Apache

### ISSUE THREAD

**Issue by marcoczen** [acmesh-official/acme.sh#3407]
Hi, I have just used acme to install a zerossl cert on a OpenSuse Leap 15.x box with Apache 2.4.46.   
All is ok. 
Https runs well and site is browseable.

I used the command below to install the certs as per  https://github.com/acmesh-official/acme.sh/wiki/Deploy-ssl-certs-to-apache-server

    ./acme.sh --install-cert -d my_domain.com   -d *.my_domain.com     \
           --cert-file      /etc/apache2/ssl_certs/my_domain.com.cer  \
           --key-file       /etc/apache2/ssl_certs/my_domain.com.key  \
           --fullchain-file /etc/apache2/ssl_certs/fullchain.cer      \
          --reloadcmd      "systemctl restart apache2"

In Apache VHosts;

        SSLCertificateFile      /etc/apache2/ssl_certs/my_domain.com.cer
        SSLCertificateKeyFile   /etc/apache2/ssl_certs/my_domain.com.key
        SSLCertificateChainFile /etc/apache2/ssl_certs/fullchain.cer

So i am just wondering about the Intermediate Cert ? The above just loads the Full Chain Cert but not the Intermediate Cert ?
So how can we modify the acme command above / apache vhost  to include the Intermediate Cert ?

Note - I used the online SSL Checker at https://decoder.link/sslchecker/  which indicated an issue

    Chain Issues:   The order of certificates is invalid or certificates cannot build certification path

Thanks.

**Comment by sahsanu** [comment]
You are using Apache 2.4.46 so you shouldn't use directive `SSLCertificateChainFile` (it is deprecated) and `SSLCertificateFile` should point to `fullchain.cer`(this file contains your cert and the intermediate cert) instead of `my_domain.com.cer`
```
SSLCertificateFile      /etc/apache2/ssl_certs/fullchain.cer
SSLCertificateKeyFile   /etc/apache2/ssl_certs/my_domain.com.key
```

Once you have modified your conf file, remember to reload/restart your Apache server.

**Comment by marcoczen** [comment]
Hi,

> You are using Apache 2.4.46 so you shouldn't use directive `SSLCertificateChainFile` (it is deprecated) 

Noted.

>and `SSLCertificateFile` should >point to `fullchain.cer`(this file contains your cert and the intermediate cert) instead of 
> `my_domain.com.cer`

Ok

> 
> ```
> SSLCertificateFile      /etc/apache2/ssl_certs/fullchain.cer
> SSLCertificateKeyFile   /etc/apache2/ssl_certs/my_domain.com.key
> ```
> 
> Once you have modified your conf file, remember to reload/restart your Apache server.

WORKING!!!!

The  online SSL Checker at https://decoder.link/sslchecker/ gives an all green now !!! 
THANKS !!!

So do i need to modify the command below or use it as it is ?

    ./acme.sh --install-cert -d my_domain.com   -d *.my_domain.com     \
           --cert-file      /etc/apache2/ssl_certs/my_domain.com.cer  \
           --key-file       /etc/apache2/ssl_certs/my_domain.com.key  \
           --fullchain-file /etc/apache2/ssl_certs/fullchain.cer      \
           --reloadcmd      "systemctl restart apache2"

**Comment by sahsanu** [comment]
Great, I'm glad it is working fine.

Regarding the command:

**1.-** When using `--install-cert` you only need to specify one -d parameter, and use as domain the one that gives the name to your cert. 

**2.-** It is ok to keep all the other `--xxx-file` parameters, it won't hurt. Well, you could remove the parameter `--cert-file` because you won't use that file but as I said, there is no problem if you use it.

**3.-** In your reloadcmd I would use **reload** instead of restart because a reload keeps your web server up and running so no downtime.

**Comment by marcoczen** [comment]
Hi ... 

Point no 3 is noted. Did not know that.
Point no 2 - I rather just keep all if there are no issues.
Point no 1 - Since i have multiple vhosts in my homeserver ( non standard https port ), i have to  keep  -d *.my_domain.com ?
Any negative impact of keeping -d my_domain.com  ?

**Comment by sahsanu** [comment]
> Point no 1 - Since i have multiple vhosts in my homeserver ( non standard https port ), i have to keep -d *.my_domain.com ?
> Any negative impact of keeping -d my_domain.com ?

When using `--install-cert` you should use only one `-d` parameter and the domain there should be the name of your cert. The name of your cert is the name you get in the first column (Main_Domain) when issuing this command `acme.sh --list`

**Comment by marcoczen** [comment]
Hi,
I ran the command  './acme.sh --list'

    Main_Domain      KeyLength    SAN_Domains       CA                      Created                                        Renew
    my_domain.com  ""                  *.my_domain.com  LetsEncrypt.org  Sat Feb 13 12:58:27 UTC 2021  Wed Apr 14 12:58:27 UTC 2021
