### ISSUE TITLE
dns_ovh.sh wrong end point?

### ISSUE THREAD

**Issue by paynor** [acmesh-official/acme.sh#3415]
With latest version acme.sh installed on debian 8 VPS on OVH in Canada.
API keys obtained from the canadian side : https://ca.api.ovh.com/createToken/

On attempt to issue certs with the script, txt records are not written to OHV dns zone - see transcript below.
Apparently becasue the EU endpoint is selected instead of the CA endpoint.
Error in OVH API? In script or in dns.ovh.sh ? 

Workaround: edited dns_ovh.sh so that also the EU endpoint points to the ca.api.
>      #'ovh-eu'
 >     OVH_EU='https://ca.api.ovh.com/1.0'

With this workaround the txt records (acme_challenge) are written correctly to the dns zone and the certs issue correctly.

Terminal transcript before editing  dns_ovh.sh:
> acme.sh --issue -d test.mydomain.ca -d meet.mydomain.ca -d *.test.mydomain.ca --dns dns_ovh --log
> [Wed Feb 17 13:07:42 EST 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
> [Wed Feb 17 13:07:42 EST 2021] Multi domain='DNS:test.mydomain.ca,DNS:meet.mydomain.ca,DNS:*.test.mydomain.ca'
> [Wed Feb 17 13:07:42 EST 2021] Getting domain auth token for each domain
> [Wed Feb 17 13:07:44 EST 2021] Getting webroot for domain='test.mydomain.ca'
> [Wed Feb 17 13:07:44 EST 2021] Getting webroot for domain='meet.mydomain.ca'
> [Wed Feb 17 13:07:44 EST 2021] Getting webroot for domain='*.test.mydomain.ca'
> [Wed Feb 17 13:07:44 EST 2021] Adding txt value: gY-XadvSbNIR9FaMsKk8Olqd63jVIwIEewQAV_6Sv1A for domain:  _acme-> > challenge.test.mydomain.ca
> [Wed Feb 17 13:07:44 EST 2021] Using OVH endpoint: ovh-eu
> [Wed Feb 17 13:07:44 EST 2021] Checking authentication
> [Wed Feb 17 13:07:45 EST 2021] Consumer key is ok.
> [Wed Feb 17 13:07:46 EST 2021] Adding record
> [Wed Feb 17 13:07:46 EST 2021] Add txt record error.
> [Wed Feb 17 13:07:46 EST 2021] Error add txt for domain:_acme-challenge.test.mydomain.ca

The log does not give much further information about the reason for the add txt record error, so not pasted here.

**Comment by sahsanu** [comment]
Did you export variable `OVH_END_POINT=ovh-ca` before issuing the cert?

https://github.com/acmesh-official/acme.sh/wiki/How-to-use-OVH-domain-api#5-ovh-api-support-ovh-kimsufi-soyoustart-and-runabove

**Comment by paynor** [comment]
Yes, I had forgotten to declare the OVH_END_POINT.
When declared it works correctly.
So no issue. Thanks and closing now.
