### ISSUE TITLE
Is it possible to not save sensitive information for deployment hooks?

### ISSUE THREAD

**Issue by leepfrog-ger** [acmesh-official/acme.sh#3417]
Thanks for your great work on this tool!

I have a somewhat specific question/use case: For several systems I'd like to request certificates centrally using acme.sh and then push them out via deployment hooks to several sensitive systems. 

Default seems to be that deploy configuration that was set via the EXPORT directives (e.g. credentials to deploy to specific systems) is persisted in the .conf files, so that the cronjob can do all in once (renews and deploying). 
However in my case I'd prefer to have some external process trigger the deploy which will then add the exports with all the sensitive information directly before the deployment is executed. Is there any flag to prevent acme.sh from writing the deploy configuration to the .conf files, or do I have to remove those after deployments by editing the .conf file?

**Comment by Neilpang** [comment]
which deploy hook do you use?

I would suggest you copy and rename the deploy hook, and then edit the code not to save the sensitive info.

Thanks.
