### ISSUE TITLE
Is the certificate storage location stable? 证书存放目录是稳定的吗?

### ISSUE THREAD

**Issue by RealXuChe** [acmesh-official/acme.sh#3420]
I noticed that cert files will be stored in `.acme.sh/firest.com(_ecc)/` when issuing cert for multiple domains like:

```
acme.sh --issue --dns -d first.com -d second.com
```

I consulted the documentation but found no relevant records. Is the certificate storage location stable? If not, will you make it stable in the future?

我发现在用下面的命令申请多域名证书时,证书的存放目录会是`.acme.sh/firest.com(_ecc)/`

```
acme.sh --issue --dns -d first.com -d second.com
```

我看了下文档,里面并没有记载这个行为,这是一个稳定的行为吗?或者说,存放目录之后会稳定吗?

**Comment by Neilpang** [comment]
不保证.
应该在 issue 之后, 再调用 `--install-cert` 把 证书文件拷贝到你指定的位置.   每次 自动renew之后, 都会重复这个 copy 操作.
 
https://github.com/acmesh-official/acme.sh#3-install-the-cert-to-apachenginx-etc
