### ISSUE TITLE
ZeroSSL - Certificate Issueance Failed - Terms Of Service Have Changed

### ISSUE THREAD

**Issue by marcoczen** [acmesh-official/acme.sh#3424]
Guys, I have previously used acme.sh/zerossl to issue cert on a server. with NO problems via DNS challenge.

I had gotten a new domain and so I just retried issuing  new certs 
(  newdomain.com, *.newdomain.com ) and got this error message :

Create new order error. Le_OrderFinalize not found.   
 {"type":"urn:ietf:params:acme:error:userActionRequired","status":403,"detail":"Terms of service have changed"}

Any idea what is "Terms Of Service Have Changed" ?  
What is the user action required of me ?
Is this because, i have tried for a new domain ? 
But i also revoked the previous cert for the olddomain ?
I did try with a different email account ( -m  newemail ) but the error message persists.

**Comment by rgeraskin** [comment]
I have the same issue with zerossl

**Comment by Neilpang** [comment]
can you guys please show me the full log with `--debug 2`?

Thanks.

**Comment by marcoczen** [comment]
@Neilpang  - let me run it again and i will revert

**Comment by marcoczen** [comment]
> I have the same issue with zerossl today
> 
> Workaround: delete account RSA key and register a new one. Maybe you should delete something else in addition, I've just cleaned up all acme.sh files.
> 
> Also, I've registered with newly generated credential (eab-kid, eab-hmac-key) because my creds were expired.

SO just delete the entire folder ? Better start with clean slate ?

**Comment by rgeraskin** [comment]
I reported the issue to the ZeroSSL customer service, and they said:

> In regards to the recent issues with the ACME terms of service, please note that this issue has been resolved by our CA

**Comment by marcoczen** [comment]
Ohhh ... let me retry and revert ... Nice ......

**Comment by marcoczen** [comment]
> Ohhh ... let me retry and revert ... Nice ......

Dear - IT WORKS !!!! So looks like the issue was with ZeroSSL. There were NO differences in commands used. 
I did wipe out the folder and restarted from fresh as i was issuing  wild card certs  for multiple domains.

Thanks !!!!
