### ISSUE TITLE
Certificate not renewed automatically 

### ISSUE THREAD

**Issue by aivl2018** [acmesh-official/acme.sh#3425]
Hi Team,

We are using below command to renew certificate. After 60 days of time internal its not renewed automatically. Please let know what are the causes/things to be considered for auto renewable of certificate.

Acme version : 2.8.6
OS :  linux rhel7

./acme.sh --install-cert -d "*.dns-aws" --cert-file "/etc/httpd/ssl/*.dns-aws.cer" --key-file "/etc/httpd/ssl/*.dns-aws.key" --fullchain-file "/etc/httpd/ssl/dns-awsfullchain.cer" --reloadcmd "service httpd restart"  

Thanks in Advance !!

**Comment by Neilpang** [comment]
Is the crontab installed ?
please check:
```
crontab. -l
```

**Comment by marcoczen** [comment]
> Hi Team,
> 
> We are using below command to renew certificate. After 60 days of time internal its not renewed automatically. Please let know what are the causes/things to be considered for auto renewable of certificate.
> 
> Acme version : 2.8.6
> OS : linux rhel7
> 
> ./acme.sh --install-cert -d "_.dns-aws" --cert-file "/etc/httpd/ssl/_.dns-aws.cer" --key-file "/etc/httpd/ssl/*.dns-aws.key" --fullchain-file "/etc/httpd/ssl/dns-awsfullchain.cer" --reloadcmd "service httpd restart"
> 
> Thanks in Advance !!

crontab -l ( as root ) should show you something like;

     19 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null

**Comment by DDusky** [comment]
I have same problem

**Comment by apxeonTepukc** [comment]
Absolutely same thing! Any news on that issue?

**Comment by wbeckle** [comment]
Check the httpd error log to see if the well-known url is getting an error when accessed.

**Comment by Chematronix** [comment]
Thanks wbeckle.  Nginx was blocking access to .well-known (as directed):
`access forbidden by rule, request: "GET /.well-known/security.txt HTTP/1.1"`

Had to add to my cfg:
```
location ~ /\.well-known {
  allow all;
}
```
Hopefully this was the only problem.

**Comment by mangelozzi** [comment]
> Check the httpd error log to see if the well-known url is getting an error when accessed.

Where is the error log?
