### ISSUE TITLE
关于deploy到docker容器的两个问题

### ISSUE THREAD

**Issue by HiColinn** [acmesh-official/acme.sh#3429]
Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```
并没有BUG,只是对deploy的两个问题,
Q1:一个acme.sh容器多次执行deploy命令.可以将一个域名的证书部署到多个其它容器中吗?  如果可以,证书更新的时候,reloadcmd命令会分别对不同的容器执行命令吗?
Q2:怎么样取消一个deploy任务?比如我有一个证书,开始部署到了两个容器中,但是后来有一个容器用不到了,deploy命令还会对已经删除的容器执行部署任务吗?

**Comment by Neilpang** [comment]
只能 deploy 到一个容器中.

你可以让多个容器共享 mount 文件. 也可以直接运行多个 acme.sh 的容器, 每个容器部署一个.

**Comment by HiColinn** [comment]
> 只能 deploy 到一个容器中.
> 
> 你可以让多个容器共享 mount 文件. 也可以直接运行多个 acme.sh 的容器, 每个容器部署一个.

但是如果一个域名,被两个acme.sh容器签发,证书是一样的吗?会不会后签发的把前面容器签发的证书搞失效

**Comment by Neilpang** [comment]
不会.  只要你不主动 revoke,  所有能签发下来的证书在有效期结束前都是有效的.

但是, Letsencrypt 为了防止用户误操作, 好像域名列表完全相同的证书只能签发 5个. 具体限制请参看官方的说明.

一般也够用的. 如果这个限制达到了,  你可以 试试 用 zerossl 签发. 它没有任何数量限制.

https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA

**Comment by HiColinn** [comment]
> 不会. 只要你不主动 revoke, 所有能签发下来的证书在有效期结束前都是有效的.
> 
> 但是, Letsencrypt 为了防止用户误操作, 好像域名列表完全相同的证书只能签发 5个. 具体限制请参看官方的说明.
> 
> 一般也够用的. 如果这个限制达到了, 你可以 试试 用 zerossl 签发. 它没有任何数量限制.
> 
> https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA

非常感谢您的耐心解答,谢谢
