### ISSUE TITLE
Where do I find fullchain.pem?

### ISSUE THREAD

**Issue by sergio-ns** [acmesh-official/acme.sh#3432]
Hello,
I have to issue a certificate for my domain and using the latest version of acme.sh.
The certificate file will be handled by Traefik.
I did issue the certificate most three months ago and worked perferctly but now it is about to expire, as I don't remember the procedure I followed, I decided to restart from scratch following the documentation.
Trafik needs the following files
```
certFile = "/path/to/certificate_file"
keyFile = "/path/to/private_key"
```
At the moment "certificate_file" points to a file named "fullchain.cer".
For the life of me, I can't recall where that file is coming from.

I installed acme.sh with the following instruction:
./acme.sh --install --home $HOME/myacme \
--cert-home $HOME/myacme/mycerts \
--accountemail "myemail" \
--accountkey $HOME/myacme/myaccount.key

and issued a wildcard certificate with:
acme.sh --issue --dns dns_namesilo -dnssleep 900 -d "*.MYDOMAIN.COM"
(the Namesilo API key is available an exported env variable)

The output is:
```
[Sat Feb 27 12:13:03 CET 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sat Feb 27 12:13:03 CET 2021] Create account key ok.
[Sat Feb 27 12:13:03 CET 2021] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Sat Feb 27 12:13:05 CET 2021] Registered
[Sat Feb 27 12:13:05 CET 2021] ACCOUNT_THUMBPRINT='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
[Sat Feb 27 12:13:05 CET 2021] Creating domain key
[Sat Feb 27 12:13:05 CET 2021] The domain key is here: /share/homes/admin/myacme/mycerts/*.MYDOMAIN.COM/*.MYDOMAIN.COM.key
[Sat Feb 27 12:13:05 CET 2021] Single domain='*.MYDOMAIN.COM'
[Sat Feb 27 12:13:05 CET 2021] Getting domain auth token for each domain
[Sat Feb 27 12:13:07 CET 2021] Getting webroot for domain='*.MYDOMAIN.COM'
[Sat Feb 27 12:13:07 CET 2021] Adding txt value: zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz for domain:  _acme-challenge.MYDOMAIN.COM
[Sat Feb 27 12:13:10 CET 2021] Successfully added TXT record, ready for validation.
[Sat Feb 27 12:13:10 CET 2021] The txt record is added: Success.
[Sat Feb 27 12:13:10 CET 2021] Sleep 900 seconds for the txt records to take effect
[Sat Feb 27 12:28:16 CET 2021] Verifying: *.MYDOMAIN.COM
[Sat Feb 27 12:28:17 CET 2021] **It seems the CA server is busy now, let's wait and retry. Sleeping 1 seconds.**
[Sat Feb 27 12:28:23 CET 2021] *.MYDOMAIN.COM:Verify error:Incorrect TXT record
[Sat Feb 27 12:28:23 CET 2021] Removing DNS records.
[Sat Feb 27 12:28:23 CET 2021] Removing txt: zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz for domain: _acme-challenge.MYDOMAIN.COM
[Sat Feb 27 12:28:25 CET 2021] Successfully retrieved the record id for ACME challenge.
[Sat Feb 27 12:28:26 CET 2021] Successfully removed the TXT record.
[Sat Feb 27 12:28:26 CET 2021] Removed: Success
[Sat Feb 27 12:28:26 CET 2021] Please add '--debug' or '--log' to check more details.
[Sat Feb 27 12:28:26 CET 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
```
The acme_challenge was correctly added as TXT record so I'm not sure if the log file means that there was an issue with the challenge.

Anyway, in folder $HOME/mycerts/*.MYDOMAIN.COM I find the following files:
```
*.MYDOMAIN.COM.conf
*.MYDOMAIN.COM.csr
*.MYDOMAIN.COM.csr.conf
*.MYDOMAIN.COM.key
```

In folder $HOME/mycerts/ca I find:
```
account.json
ca.conf
```

Where can I find the fullchain.pem that Traefik needs?

Thanks

**Comment by sahsanu** [comment]
Hello @sergio-ns,

You can't find the file because you didn't issue the certificate, something failed trying to verify the txt record.

Once you issue the certificate you will get three more files in `$HOME/mycerts/`:
```
ca.cer
*.MYDOMAIN.COM.cer
fullchain.cer
```

Note: Just in case you don't know it, a wildcard certificate `*.mydomain.com` covers `a.mydomain.com`, `b.mydomain.com` etc. but doesn't cover neither the apex domain `mydomain.com` nor another subdomain level like `a.b.mydomain.com`.

**Comment by sergio-ns** [comment]
You are correct, the process did not finalize successfully, I will open an issue about the verification with Namesilo and close this one
