### ISSUE TITLE
Replay Nonce is not recognized

### ISSUE THREAD

**Issue by tgrelka** [acmesh-official/acme.sh#3433]
Steps to reproduce
------------------
Try to issue a cert using netcup DNS api. I’m using the following command: 
`acme.sh --issue --dns dns_netcup -d tim-grelka.de`, for the debug log with the additions `--debug 2 --log log.txt`

Debug log
------------
[log.txt](https://github.com/acmesh-official/acme.sh/files/6057900/log.txt)

```
acme.sh --issue --dns dns_netcup -d tim-grelka.de  --debug 2
```

I’m getting a `tim-grelka.de:Challenge error: {"type":"urn:ietf:params:acme:error:badNonce","status":400,"detail":"The Replay Nonce is not recognized"}` badNonce error. I’ve tried all kinds of things during the day, even switched SSL providers, now using zerossl. Originally I was trying to issue a certificate for multiple TLDs and wildcard subdomains, that is still my use case and the reason why I need DNS verification.

**Comment by Neilpang** [comment]
fixed.  please try again with the latest `dev` branch.

```
acme.sh  --upgrade -b dev
```

**Comment by tgrelka** [comment]
I can test this in about five hours from now, will let you know of the results.

**Comment by tgrelka** [comment]
Fixed! I’ll leave this issue open to have it closed automatically as soon as the commit is merged into master.
