### ISSUE TITLE
cloudflare-dns.com is too slow

### ISSUE THREAD

**Issue by VityaSchel** [acmesh-official/acme.sh#3437]
When I issue new certificate, acme.sh request `https://cloudflare-dns.com/dns-query?name=_acme-challenge.my.domain&type=TXT` with curl. It takes about 15 minutes to get done for only 1 domain and after that acmesh throws some error in curl. I also tried to go to the cloudflare-dns.com manually from my PC browser and it won't load. [Cloudflare Status](https://www.cloudflarestatus.com/) says DNS lookup is operational in my region. Maybe switch to another dns lookup?

**Comment by Spinestars** [comment]
表示阿里云的国内服务器，这个地址现在不可访问了，导致证书check，一直报curl代理错误

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh/wiki/dnscheck

**Comment by rr307** [comment]
Not slow . Just failed.
`[Tue Mar 16 11:42:39 CST 2021] _post_url='https://cloudflare-dns.com/api/v1/purge?domain=_acme-challenge.support.99xs.com&type=TXT'
[Tue Mar 16 11:42:39 CST 2021] _WGET='wget -q --content-on-error '
[Tue Mar 16 11:42:39 CST 2021] Please refer to https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html for error code: 4
[Tue Mar 16 11:42:39 CST 2021] Using sed  -i
[Tue Mar 16 11:42:39 CST 2021] _ret='4'`

Try curl manually. Like this:
`# curl -v 'https://cloudflare-dns.com/api/v1/purge?domain=_acme-challenge.99xs.com&type=TXT'
* About to connect() to cloudflare-dns.com port 443 (#0)
*   Trying 104.16.248.249...
* Connected to cloudflare-dns.com (104.16.248.249) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -5961 (PR_CONNECT_RESET_ERROR)
* TCP connection reset by peer
* Closing connection 0
curl: (35) TCP connection reset by peer`

OR 301 jump to Home page
`# curl -v 'https://cloudflare-dns.com/api/v1/purge?domain=_acme-challenge.99xs.com&type=TXT'
* About to connect() to cloudflare-dns.com port 443 (#0)
*   Trying 104.16.248.249...
* Connected to cloudflare-dns.com (104.16.248.249) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -5961 (PR_CONNECT_RESET_ERROR)
* TCP connection reset by peer
* Closing connection 0
curl: (35) TCP connection reset by peer`

**Comment by rr307** [comment]
> 表示阿里云的国内服务器，这个地址现在不可访问了，导致证书check，一直报curl代理错误

解决了，编辑 acme.sh

替换这两个地方的代码
`
#domain, type
_ns_lookup_google() {
  _cf_ld="$1"
  _cf_ld_type="$2"
  #_cf_ep="https://dns.google/resolve"
  _cf_ep="https://dns.alidns.com/resolve"
  _ns_lookup_impl "$_cf_ep" "$_cf_ld" "$_cf_ld_type"
}

_ns_lookup_cf() {
  _cf_ld="$1"
  _cf_ld_type="$2"
  #_cf_ep="https://cloudflare-dns.com/dns-query"
  _cf_ep="https://doh.pub/dns-query"
  _ns_lookup_impl "$_cf_ep" "$_cf_ld" "$_cf_ld_type"
}
`

**Comment by NullYing** [comment]
> > 表示阿里云的国内服务器，这个地址现在不可访问了，导致证书check，一直报curl代理错误
> 
> 解决了，编辑 acme.sh
> 
> 替换这两个地方的代码
> `
> #domain, type
> _ns_lookup_google() {
> _cf_ld="$1"
> _cf_ld_type="$2"
> #_cf_ep="https://dns.google/resolve"
> _cf_ep="https://dns.alidns.com/resolve"
> _ns_lookup_impl "$_cf_ep" "$_cf_ld" "$_cf_ld_type"
> }
> 
> _ns_lookup_cf() {
> _cf_ld="$1"
> _cf_ld_type="$2"
> #_cf_ep="https://cloudflare-dns.com/dns-query"
> _cf_ep="https://doh.pub/dns-query"
> _ns_lookup_impl "$_cf_ep" "$_cf_ld" "$_cf_ld_type"
> }
> `

寻求更加优雅的方法，docker的表示好麻烦

**Comment by marcoczen** [comment]
Hi ... in cron, where do we add  option --dnssleep 300

In crontab ( crontab -l ) i have ;

**Comment by marcoczen** [comment]
Partial answer recived at ;

https://github.com/acmesh-official/acme.sh/issues/3484

**Comment by jwomackgsa** [comment]
Possible to add a command line override to point to the DNS server of your choice.  I currently have to use the dnssleep option when we run acme.sh against our internal ACME RA and internal dns as the public DNS is unaware and usually the server running the client can't even reach the internet.  If we could add like --dnscheck-server mydns.internal then I could still get the benefit of the client side validation / propagation with internal DNS.

**Comment by Neilpang** [comment]
@jwomackgsa 

>> If we could add like --dnscheck-server mydns.internal then I could still get the benefit o

No,  please use `--dnssleep`, it's the best for you.

**Comment by Neilpang** [comment]
请查看这个 issue:  
https://github.com/acmesh-official/acme.sh/issues/3487
