### ISSUE TITLE
tls-alpn mode is forcing openssl server to use port 1001 for some reason

### ISSUE THREAD

**Issue by acmesh7653** [acmesh-official/acme.sh#3453]
Hi,

I am using standalone alpn mode to renew certificates with the simple command:

`acme.sh --listen-v4 --alpn --renew --domain example.org --debug --force`

But for some reason, `acme.sh` is forcing the openssl server to use port 1001, while the Let's Encrypt robot is still expecting to connect to port 443.

I have tried options like `--tlsport 443`, but openssl is still listening on port 1001.

My workaround was to manually change the line `port="$3"` in `_starttlsserver()` to `port=443`, and everything works as it should, i.e. certificates were renewed successfully.

The last time I tried successfully to renew certificates was February 13, 2021, with the then-current version of `acme.sh` (2.8.8). But I tried rolling back to that version and still experience the same problem, so I'm not sure what is causing this to happen.

Thanks

Steps to reproduce
------------------

`acme.sh --listen-v4 --alpn --renew --domain example.org --debug --force`

Debug log
-----------------

Here is the relevant sanitized debug output from `acme.sh`:

```
[Sat Mar 20 06:41:53 AM EDT 2021] Using config home:/home/user/.acme.sh
https://github.com/acmesh-official/acme.sh
v2.8.9
...
[Sat Mar 20 06:41:53 AM EDT 2021] Standalone alpn mode.
[Sat Mar 20 06:41:54 AM EDT 2021] _checkport='1001'
...
[Sat Mar 20 06:41:55 AM EDT 2021] Starting tls server.
[Sat Mar 20 06:41:55 AM EDT 2021] san_a='example.org'
[Sat Mar 20 06:41:55 AM EDT 2021] san_b
[Sat Mar 20 06:41:55 AM EDT 2021] port='1001'
...
[Sat Mar 20 06:41:55 AM EDT 2021] Le_Listen_V4='1'
[Sat Mar 20 06:41:55 AM EDT 2021] Le_Listen_V6
[Sat Mar 20 06:41:55 AM EDT 2021] openssl s_server -www -cert /home/user/.acme.sh/example.org/tls.validation.cert -key /home/user/.acme.sh/example.org/tls.validation.key -accept 1001 -4 -alpn acme-tls/1
...
[Sat Mar 20 06:41:59 AM EDT 2021] example.org:Verify error:Connection refused
```

Here is the sanitized web output from `https://acme-v02.api.letsencrypt.org/acme/chall-v3/97229379255/94cfb6`:

```
{
  "type": "tls-alpn-01",
  "status": "invalid",
  "error": {
    "type": "urn:ietf:params:acme:error:connection",
    "detail": "Connection refused",
    "status": 400
  },
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/97229379255/94cfb6",
  "token": "26a9995abe6e4ea4b85b569ee4a7e970394e84c4a6a",
  "validationRecord": [
    {
      "hostname": "example.org",
      "port": "443",
      "addressesResolved": [
        "WW.XX.YY.ZZ"
      ],
      "addressUsed": "WW.XX.YY.ZZ"
    }
  ],
  "validated": "2021-03-20T10:41:56Z"
}
```

**Comment by Neilpang** [comment]
when you use `--renew`,  only the `--domain` is valid.   The `--tlsport` and `--listen-v4` is only valid for `-issue`.

So, try to `--issue` a new one.
