### ISSUE TITLE
Docker deploy hook - Why not restart container to reload certificate?

### ISSUE THREAD

**Issue by buxm** [acmesh-official/acme.sh#3461]
According to the Wiki instructions to deploy a certificate to a docker container, in order to have whatever service is running in the container load the newly deployed certificate you have to specify `export DEPLOY_DOCKER_CONTAINER_RELOAD_CMD="The command to reload the service in the container"`.

However my understanding is that the "universal" and most practical way to reload/re-initialize services in a container is just to restart the container itself.
As far as I can see, most docker images do not even document how to reload a service within the container. And in some cases loading a new certificate may require additional steps than just restarting the service.

For instance here is how to load a new certificate to a UniFi Controller: https://lazyadmin.nl/home-network/unifi-controller-ssl-certificate/ and https://raw.githubusercontent.com/stevejenkins/unifi-linux-utils/master/unifi_ssl_import.sh
Before restarting the service you have to export the certificate to a PCKS12 file, import the file to the UniFi keystore,... and do some cleanup. Quite convoluted.
This docker container https://hub.docker.com/r/jacobalberty/unifi does all of that automatically when it (re)starts, as long as it finds the certificate in a specific directory.

So what should I do to deploy a certificate to a jacobalberty/unifi container? I could look for the script within the container that it uses to load the certificate upon startup, then put it into the `DEPLOY_DOCKER_CONTAINER_RELOAD_CMD` variable. However there is no documentation on that script, so I would have to do some treasure hunting. And then in one future version jacobalberty could change its location or UniFi could totally reengineer how certificates are loaded. Or I could just restart the target container, which is much simpler, more robust against future changes and essentially universal to most (well made) containers. But this doesn't seem to be doable using the docker deploy hook.

So I had to make my own script to identify and restart the running containers labeled with sh.acme.autoload.domain=mydomain.com and use it as a `--reloadcmd` for `--install-cert` instead of using the docker deploy hook, which would have been much cleaner.

**Comment by Neilpang** [comment]
>> most practical way to reload/re-initialize services in a container is just to restart the container itself.

No.


>> use it as a --reloadcmd for --install-cert instead of using the docker deploy hook, 

Yes, this is the better solution for your case.

**Comment by logopk** [comment]
I ran into this issue when deploying to a mysql container.

MySQLd will only reload config when restarting the demon - that is pid 0 and will kill the container - and thus fail the acme.sh docker-deploy-hook (return code 1). The rest of the script is still perfectly fine.
The container is set to auto restart, so that will not affect my environment.

I would suggest to have an option to restart the container from outside and not DEPLOY_DOCKER_CONTAINER_RELOAD_CMD.
Alternatively ignore the error and finish acme.sh --deploy.

Makes sense?

Thanks.

Peter

**Comment by Neilpang** [comment]
Not every container is prepared to be restarted any time.  There may be working process, and the data can be corrupted.
So, one should never restart a container forcibly.
A graceful reload should be used.

**Comment by Neilpang** [comment]
@logopk 

https://bugs.mysql.com/bug.php?id=75404

https://dev.mysql.com/doc/refman/8.0/en/alter-instance.html#alter-instance-reload-tls

**Comment by buxm** [comment]
> Not every container is prepared to be restarted any time. There may be working process, and the data can be corrupted.
> So, one should never restart a container forcibly.
> A graceful reload should be used.

However a `docker stop` or `docker restart` does not normally stop the container _forcibly_. It first attempts sending a `SIGTERM` to the main process, which should allow it to complete work in progress before shutting down. See [https://docs.docker.com/engine/reference/commandline/stop/](url).

[linuxserver.io](https://www.linuxserver.io/) recommends stopping and recreating a container to upgrade to a new version for all the images they maintain [https://fleet.linuxserver.io/](url). See for instance [https://hub.docker.com/r/linuxserver/mariadb](url) at the _Updating Info_ section. And they are not the only one suggesting this approach.
I'd struggle thinking that they are suggesting an update approach that risks data corruption.

It should be similar to _rebooting your machine != pulling the plug_. Ok, you don't normally reboot your machine just to reload a service. But considering that a container is very lightweight and typically runs only 1 service, restarting the container is almost as efficient as reloading the service and it enables a much wider standardisation (all services are reloaded differently vs. all containers are restarted the same way), which is actually one of the benefits of using containers.

**Comment by Neilpang** [comment]
@buxm 

I knew what a restart means.

but this is not a MUST rule that every container must follow.  Most of the maintainers didn't even take care of SIGTERM yet.

>> It should be similar to rebooting your machine

No, it's not as easy as you thought.

A container may be originally started with many args, like:

```sh
docker  run --rm --it    \
    --net=host \
    -e xxx=bbbb  \
    -e yyy=zzz  \
     -p x:y \
    -v  aaa:bbbb \
    --label  xxxxxxx
   ubuntu  bash
```

It's not easy to safely re-start it as it was.


One of the biggest goal of acme.sh's  is to keep the user's machine safe,  we don't want to damage it.

**Comment by logopk** [comment]
I agree with that.

nevertheless it could be my choice to use this optional method if there os no better solution - as explained above.

acme.sh fails when I bounce process 0 in the container…

**Comment by ngehrsitz** [comment]
For people looking for a solution to restart [jacobalberty/unifi-docker](https://github.com/jacobalberty/unifi-docker) like @buxm:
You can just use `DEPLOY_DOCKER_CONTAINER_RELOAD_CMD="kill -s 2 1"`. This sends SIGINT to [docker-entrypoint.sh](https://github.com/jacobalberty/unifi-docker/blob/master/docker-entrypoint.sh) which then causes the container to shut down gracefully.
