### ISSUE TITLE
namecheap dns

### ISSUE THREAD

**Issue by bigalownz** [acmesh-official/acme.sh#3462]
Hi when i renew or deploy a new cert with namecheap dns
i get this error

```
CAA record with tag "issuewild" has incorrect value.
Error add txt for domain:_acme-challenge.mysite.com
Please check log file for more details: /root/.acme.sh/acme.sh.log
```

i have looked on here and notice the same problem after its install

1 tip is to install recode and i still get the problem

even happens if i do a new install of acme.sh

any tips to fix this 

thanks

**Comment by jwomackgsa** [comment]
I am looking at using Namecheap for this purpose as well.  I read that you have to meet certain requirements for API access.  Can you confirm you enabled the API access?  I see you also posted about the CAA record.  Was that an issue or did you just copy that by mistake?

**Comment by greecemunky** [comment]
Does your domain's zone record have any CAA entries defined?  If so, you could be restricting which CAs can be used to generate certificates for your domain.  If you define the CAA DNS type but don't include Let’s Encrypt in the list, LE won't allow you to generate certs.

Let's Encrypt's value is ```letsencrypt.org```

https://letsencrypt.org/docs/caa/
https://www.namecheap.com/support/knowledgebase/article.aspx/9991/38/caa-record-and-why-it-is-needed-ssl-related/

**Comment by bigalownz** [comment]
only fix i have found is this

`https://github.com/acmesh-official/acme.sh/issues/3019#issuecomment-652081036`

and it works
