### ISSUE TITLE
Best practices for a hook (--reloadcmd?) only once after successful --cron?

### ISSUE THREAD

**Issue by djbelly** [acmesh-official/acme.sh#3469]
If I'm renewing a bajillion certs with --cron, I want it to run a hook exactly once if any of the certificates renew—not once per renewal. To clarify, I don't want it to run the hook 10 times for 10 certs. Is there an option for my use case? Here's exactly my issue/cron commands:

```
acme.sh --issue -d origin.someplace --standalone --httpport 8080 --reloadcmd 'sudo /Scripts/hitchcert'
acme.sh --issue -d thisguy.wtvr www.thisguy.wtvr--standalone --httpport 8080 --reloadcmd 'sudo /Scripts/hitchcert'
acme.sh --issue -d ineedmyown.cert --standalone --httpport 8080 --reloadcmd 'sudo /Scripts/hitchcert'
```

All of those work beautifully, but I only need the reloadcmd once no matter how many renewals occur. I don't see reloadcmd show up in the conf files, so I'd guess the right thing to do based on the doc and intuition is something like this in acme's crontab:

`acme.sh --cron --reloadcmd 'sudo /Scripts/hitchcert'`

But this doesn't do anything. Of course, I can make my script run later and check to see if the acme cert dirs updated, but that seems like a kludge since acme.sh already knows how to fire something after a renewal. 

What are the best practices for a setup like this?

**Comment by Neilpang** [comment]
you can use the nodify hook approach.

https://github.com/acmesh-official/acme.sh/wiki/notify

The notification is schechued once for the cron.

you can write your own notify hook, in which you can run the reload cmd.
