### ISSUE TITLE
Unable to create TXT on CF via dns_cf - Invalid Headers

### ISSUE THREAD

**Issue by mauvehed** [acmesh-official/acme.sh#3470]
Error
------------------
[Sat 03 Apr 2021 10:39:50 AM CDT] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.dPyVYCpKhm  -g '
[Sat 03 Apr 2021 10:39:50 AM CDT] ret='0'
[Sat 03 Apr 2021 10:39:50 AM CDT] response='{"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}'
[Sat 03 Apr 2021 10:39:50 AM CDT] h

Steps to reproduce
------------------
acme.sh --issue --dns dns_cf -d mydomain.com -d marvin.mydomain.com --log --debug 2

```
# acme.sh -v
https://github.com/acmesh-official/acme.sh
v2.8.9
```

**Comment by yecine06** [comment]
I'm having the same issue.

`
[Sat Apr 10 15:34:42 CEST 2021] h='fr'
[Sat Apr 10 15:34:42 CEST 2021] zones?name=fr
[Sat Apr 10 15:34:42 CEST 2021] GET
[Sat Apr 10 15:34:42 CEST 2021] url='https://api.cloudflare.com/client/v4/zones?name=fr'
[Sat Apr 10 15:34:42 CEST 2021] timeout=
[Sat Apr 10 15:34:42 CEST 2021] Http already initialized.
[Sat Apr 10 15:34:42 CEST 2021] _CURL='curl --silent --dump-header /home/user/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.qjbZOezdR2  -g '
[Sat Apr 10 15:34:43 CEST 2021] ret='0'
[Sat Apr 10 15:34:43 CEST 2021] response='{"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}'
`

**Comment by ldekamps** [comment]
I ran into the same issues and for me it was caused by `^M` encoding issues in the `account.conf` caused by DOS. Please check your config file for any weird encoding characters (by using `vim` for example) and see if that solves the problem.
