### ISSUE TITLE
PFX File deploy

### ISSUE THREAD

**Issue by logopk** [acmesh-official/acme.sh#3474]
Hello,

Basically this is a question how to install the pfx file upon renewal. I know how to create it, but I haven't found a way to --install-cert it to a tomcat installation.

There is no hook to add in install-cert. (I need an additional install-cert, as the same cert is by default added to an apache on the same machine)

Any hints?

Thanks

Peter

**Comment by Neilpang** [comment]
this can be a feature to support later.

Thanks.

**Comment by ChrisPates** [comment]
I'm also interested in this for installing the pfx cert for use by plex media server. especially useful when running you container.

**Comment by zuluion** [comment]
Support this proposal, I'm also looking for a way to auto install the pfx certificate to tomcat
