### ISSUE TITLE
Errors when using installOnline with user-supplied home directories

### ISSUE THREAD

**Issue by Scaum** [acmesh-official/acme.sh#3477]
Explanation
------------------
I'm in the process of automatic the installation of acme.sh using a bash script that will be run on different CentOS machines. I'm doing the installation using the get.acme.sh script with specific `--home` and `--cert-home` arguments and I think I've run into a logical bug in the `installOnline` function. Basically, the installation is properly done using my supplied arguments, but the script tries to save the `UPGRADE_HASH` in the default installation folder that does not exist.

Steps to reproduce
------------------
1. Download get.acme.sh (in the following it has been renamed to acme-install.sh)
2. Run it with user-supplied `--home` and `--cert-home` arguments
3. Observe the errors
![image](https://user-images.githubusercontent.com/9824789/113867245-95e74f00-97ae-11eb-8929-5d613592b1b9.png)

Root cause
-----------------
I'm not sure about this, but I think the issue comes from this part of the `installOnline` function:
![image](https://user-images.githubusercontent.com/9824789/113867610-0bebb600-97af-11eb-9d6d-8bb111316e1c.png)
It calls the install function with the correct flags at line 6646 and then calls the `_initpath` and `_saveaccountconf` functions; however in the current context these functions still use the default parameters as these are only overwritten during the install process. However, in this case the install happened in a subprocess and thus the variables were are not shared between the two

Disclaimer
----------------
As stated before I'm far from being a bash expert, so my understanding of the issue might be completely wrong

**Comment by Neilpang** [comment]
you can use this command to change the install cert home:

```
curl https://get.acme.sh  | sh -s   --    --install-online -m  my@example.com  --cert-home /path/to/certhome
```

BTW,  don't set the `--cert-home` to `/etc/httpd/conf/ssl`.

Never, Never use that path.

`--cert-home` is a private folder for acme.sh to use only.    The folder structure is not guaranteed.

**Comment by Scaum** [comment]
Thanks for your input, I'll see about changing the cert home path to something else.

However, this doesn't explain why the path specified in `--home` is not properly used to save the `"UPGRADE_HASH"`
