### ISSUE TITLE
REQUEST: use acme.sh to install pre-existing .pem cert from letsencrypt/nginx container

### ISSUE THREAD

**Issue by landcraft** [acmesh-official/acme.sh#3482]
I have let's encrypt service running in an niginx docker container that already handles the issuing and renewal of my domain certs with DNS challenge. I was wondering if there was a way to use acme.sh to copy said .pem into DSM?

Currently I am managing this manually (download the pem file, then re-upload in certificate section of control panel in DSM WebUI to replace the current default cert) but I'd like to find a way to do this automatically.

Is this something that acme.sh could manage?

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh/wiki/deployhooks#20-deploy-the-cert-into-synology-dsm

**Comment by landcraft** [comment]
thanks for the link. I might be a bit simple, but I'm struggling to figure out where I am to place the .pem file for acme.sh to pick it up.
Also, I will be running acme.sh on the DSM itself - do I still need to export the DSM username and passwords?

**Comment by landcraft** [comment]
Anything?
