### ISSUE TITLE
Usage of --dnssleep in existing  cron

### ISSUE THREAD

**Issue by marcoczen** [acmesh-official/acme.sh#3484]
Hi ... 

1. Say we already  have a  cron, where do we add option --dnssleep 300

In crontab ( crontab -l ) i have ;

    19 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null

Can we add --dnssleep into this cron Or do we have to re-request the certs manually and follow through ?

2. Also what does dnssleep do ?  The wiki is not clear ? It  just delays checking public dns checking  right ? 
3. Not do away with it ?

Thanks.

**Comment by Neilpang** [comment]
>>  It just delays checking public dns checking right ?

Yes.

Don't edit the default cronjob, unless you know 100% what it is.
The `--cron` command will ignore any parameters you added.

**Comment by marcoczen** [comment]
Hi ... So  how do we use this --dnssleep 300 ?

Do we have to re-request the certs manually and  --cron will pick up this option ? 
      ./acme.sh --issue --dns dns_cloudns  -d  customdomain.com    -d *.customedomain.com  --dnssleep 300  --log


The above works but when it runs by cron next time, will the dnssleep option work ?

Thanks.

**Comment by Neilpang** [comment]
>> The above works but when it runs by cron next time, will the --dnssleep option work ?

Yes

**Comment by marcoczen** [comment]
@Neilpang 

Thanks. Just wondering how the --cron will will pickup that  i used --dnssleep ? Is my command agruments kept in some file ? Or it reads the log ? Sorry, that i ask .. I am just trying to understand this better ....

**Comment by jwomackgsa** [comment]
> Just wondering how the --cron will will pickup that i used --dnssleep ?
> Is my command arguments kept in some file ? accounts.conf file ?
> Or it reads the log ?
> 
> Sorry, that i ask .. I am just trying to understand this better ....

The parameter is stored in ~/.acme.sh/<domain>/<domain.>.conf using the variable

Le_DNSSleep='###'

When it goes to renewal any previously issued domain it pulls all the original parameters used on the original issuance to do the renewal.
