### ISSUE TITLE
use ali dns resolve in china

### ISSUE THREAD

**Issue by zhangchunsheng** [acmesh-official/acme.sh#3487]
use ali dns resolve in china

**Comment by recolic** [comment]
alidns is vulnerable to dns pollution attacks. Is it better to use cloudflare DNS or microsoft DNS? They're also available in china.

**Comment by zhangchunsheng** [comment]
I just want to resolve question quickly. It need more to do and design about easy to use in China.

**Comment by sidny** [comment]
cloudflare dns has been blocked in china。。。 
and i need renew my cert 
what can i do？

**Comment by Neilpang** [comment]
请更新到最新的 dev banch试试.

```
acme.sh --upgrade -b dev
```

**Comment by Ansen** [comment]
export DOH_USE=3
```
1 DOH_CLOUDFLARE
2 DOH_GOOGLE
3 DOH_ALI  aliyun
4 DOH_DP  dnspod
```

**Comment by jearton** [comment]
修改acme.sh的环境变量，指定使用阿里云DNS。

```bash
cd .acme.sh

echo "export DOH_USE=3" >> acme.sh.env

source acme.sh.env
```
