### ISSUE TITLE
Order's status (\"invalid\") is not acceptable for finalization 

### ISSUE THREAD

**Issue by HackerBoy856** [acmesh-official/acme.sh#3504]
[root@centos-s-1vcpu-2gb-nyc1-01 home]# acme.sh  --version
https://github.com/acmesh-official/acme.sh
v2.9.0

[root@centos-s-1vcpu-2gb-nyc1-01 home]#  acme.sh --issue -d www.4itool.com -w /home/www/4itool/ --debug
[Thu May  6 11:50:43 CST 2021] Lets find script dir.
[Thu May  6 11:50:43 CST 2021] _SCRIPT_='/root/.acme.sh/acme.sh'
[Thu May  6 11:50:43 CST 2021] _script='/root/.acme.sh/acme.sh'
[Thu May  6 11:50:43 CST 2021] _script_home='/root/.acme.sh'
[Thu May  6 11:50:43 CST 2021] Using config home:/root/.acme.sh
https://github.com/acmesh-official/acme.sh
v2.9.0
[Thu May  6 11:50:43 CST 2021] Running cmd: issue
[Thu May  6 11:50:43 CST 2021] _main_domain='www.4itool.com'
[Thu May  6 11:50:43 CST 2021] _alt_domains='no'
[Thu May  6 11:50:43 CST 2021] Using config home:/root/.acme.sh
[Thu May  6 11:50:43 CST 2021] default_acme_server
[Thu May  6 11:50:43 CST 2021] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Thu May  6 11:50:43 CST 2021] DOMAIN_PATH='/root/.acme.sh/www.4itool.com'
[Thu May  6 11:50:43 CST 2021] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Thu May  6 11:50:43 CST 2021] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Thu May  6 11:50:43 CST 2021] GET
[Thu May  6 11:50:43 CST 2021] url='https://acme-v02.api.letsencrypt.org/directory'
[Thu May  6 11:50:43 CST 2021] timeout=
[Thu May  6 11:50:43 CST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[Thu May  6 11:50:43 CST 2021] ret='0'
[Thu May  6 11:50:43 CST 2021] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Thu May  6 11:50:43 CST 2021] ACME_NEW_AUTHZ
[Thu May  6 11:50:43 CST 2021] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Thu May  6 11:50:43 CST 2021] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Thu May  6 11:50:43 CST 2021] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Thu May  6 11:50:43 CST 2021] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Thu May  6 11:50:43 CST 2021] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Thu May  6 11:50:43 CST 2021] ACME_VERSION='2'
[Thu May  6 11:50:43 CST 2021] Le_NextRenewTime
[Thu May  6 11:50:43 CST 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Thu May  6 11:50:43 CST 2021] _on_before_issue
[Thu May  6 11:50:43 CST 2021] _chk_main_domain='www.4itool.com'
[Thu May  6 11:50:43 CST 2021] _chk_alt_domains
[Thu May  6 11:50:43 CST 2021] Le_LocalAddress
[Thu May  6 11:50:43 CST 2021] d='www.4itool.com'
[Thu May  6 11:50:43 CST 2021] Check for domain='www.4itool.com'
[Thu May  6 11:50:43 CST 2021] _currentRoot='/home/www/4itool/'
[Thu May  6 11:50:43 CST 2021] d
[Thu May  6 11:50:43 CST 2021] _saved_account_key_hash is not changed, skip register account.
[Thu May  6 11:50:43 CST 2021] Read key length:
[Thu May  6 11:50:43 CST 2021] _createcsr
[Thu May  6 11:50:43 CST 2021] Single domain='www.4itool.com'
[Thu May  6 11:50:43 CST 2021] Getting domain auth token for each domain
[Thu May  6 11:50:43 CST 2021] d
[Thu May  6 11:50:43 CST 2021] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Thu May  6 11:50:43 CST 2021] payload='{"identifiers": [{"type":"dns","value":"www.4itool.com"}]}'
[Thu May  6 11:50:43 CST 2021] RSA key
[Thu May  6 11:50:43 CST 2021] HEAD
[Thu May  6 11:50:43 CST 2021] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Thu May  6 11:50:43 CST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g  -I  '
[Thu May  6 11:50:43 CST 2021] _ret='0'
[Thu May  6 11:50:43 CST 2021] POST
[Thu May  6 11:50:43 CST 2021] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Thu May  6 11:50:43 CST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[Thu May  6 11:50:44 CST 2021] _ret='0'
[Thu May  6 11:50:44 CST 2021] code='201'
[Thu May  6 11:50:44 CST 2021] Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/122457878/9512267135'
[Thu May  6 11:50:44 CST 2021] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/122457878/9512267135'
[Thu May  6 11:50:44 CST 2021] url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/12888919774'
[Thu May  6 11:50:44 CST 2021] payload
[Thu May  6 11:50:44 CST 2021] POST
[Thu May  6 11:50:44 CST 2021] _post_url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/12888919774'
[Thu May  6 11:50:44 CST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[Thu May  6 11:50:44 CST 2021] _ret='0'
[Thu May  6 11:50:44 CST 2021] code='200'
[Thu May  6 11:50:44 CST 2021] d='www.4itool.com'
[Thu May  6 11:50:44 CST 2021] Getting webroot for domain='www.4itool.com'
[Thu May  6 11:50:44 CST 2021] _w='/home/www/4itool/'
[Thu May  6 11:50:44 CST 2021] _currentRoot='/home/www/4itool/'
[Thu May  6 11:50:44 CST 2021] entry='"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/12888919774/UNccHA","token":"QO4gFWioH1XufnjeC3mxTDNapPfSjpSC3BBYZltxlno"'
[Thu May  6 11:50:44 CST 2021] token='QO4gFWioH1XufnjeC3mxTDNapPfSjpSC3BBYZltxlno'
[Thu May  6 11:50:44 CST 2021] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/12888919774/UNccHA'
[Thu May  6 11:50:44 CST 2021] keyauthorization='QO4gFWioH1XufnjeC3mxTDNapPfSjpSC3BBYZltxlno.UaybHaVeA8OQcfW2y7JDnZl3Bv3-IETiwgKVzwP_cU4'
[Thu May  6 11:50:44 CST 2021] dvlist='www.4itool.com#QO4gFWioH1XufnjeC3mxTDNapPfSjpSC3BBYZltxlno.UaybHaVeA8OQcfW2y7JDnZl3Bv3-IETiwgKVzwP_cU4#https://acme-v02.api.letsencrypt.org/acme/chall-v3/12888919774/UNccHA#http-01#/home/www/4itool/'
[Thu May  6 11:50:44 CST 2021] d
[Thu May  6 11:50:44 CST 2021] vlist='www.4itool.com#QO4gFWioH1XufnjeC3mxTDNapPfSjpSC3BBYZltxlno.UaybHaVeA8OQcfW2y7JDnZl3Bv3-IETiwgKVzwP_cU4#https://acme-v02.api.letsencrypt.org/acme/chall-v3/12888919774/UNccHA#http-01#/home/www/4itool/,'
[Thu May  6 11:50:44 CST 2021] d='www.4itool.com'
[Thu May  6 11:50:44 CST 2021] ok, let's start to verify
[Thu May  6 11:50:44 CST 2021] Verifying: www.4itool.com
[Thu May  6 11:50:44 CST 2021] d='www.4itool.com'
[Thu May  6 11:50:44 CST 2021] keyauthorization='QO4gFWioH1XufnjeC3mxTDNapPfSjpSC3BBYZltxlno.UaybHaVeA8OQcfW2y7JDnZl3Bv3-IETiwgKVzwP_cU4'
[Thu May  6 11:50:44 CST 2021] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/12888919774/UNccHA'
[Thu May  6 11:50:44 CST 2021] _currentRoot='/home/www/4itool/'
[Thu May  6 11:50:44 CST 2021] wellknown_path='/home/www/4itool//.well-known/acme-challenge'
[Thu May  6 11:50:44 CST 2021] writing token:QO4gFWioH1XufnjeC3mxTDNapPfSjpSC3BBYZltxlno to /home/www/4itool//.well-known/acme-challenge/QO4gFWioH1XufnjeC3mxTDNapPfSjpSC3BBYZltxlno
[Thu May  6 11:50:44 CST 2021] Changing owner/group of .well-known to root:root
[Thu May  6 11:50:44 CST 2021] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/12888919774/UNccHA'
[Thu May  6 11:50:44 CST 2021] payload='{}'
[Thu May  6 11:50:44 CST 2021] POST
[Thu May  6 11:50:44 CST 2021] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/12888919774/UNccHA'
[Thu May  6 11:50:44 CST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[Thu May  6 11:50:45 CST 2021] _ret='0'
[Thu May  6 11:50:45 CST 2021] code='200'
[Thu May  6 11:50:45 CST 2021] trigger validation code: 200
[Thu May  6 11:50:45 CST 2021] sleep 2 secs to verify
[Thu May  6 11:50:47 CST 2021] checking
[Thu May  6 11:50:47 CST 2021] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/12888919774/UNccHA'
[Thu May  6 11:50:47 CST 2021] payload
[Thu May  6 11:50:47 CST 2021] POST
[Thu May  6 11:50:47 CST 2021] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/12888919774/UNccHA'
[Thu May  6 11:50:47 CST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[Thu May  6 11:50:47 CST 2021] _ret='0'
[Thu May  6 11:50:47 CST 2021] code='200'
[Thu May  6 11:50:47 CST 2021] Success
[Thu May  6 11:50:47 CST 2021] pid
[Thu May  6 11:50:47 CST 2021] Debugging, skip removing: /home/www/4itool//.well-known/acme-challenge/QO4gFWioH1XufnjeC3mxTDNapPfSjpSC3BBYZltxlno
[Thu May  6 11:50:47 CST 2021] pid
[Thu May  6 11:50:47 CST 2021] No need to restore nginx, skip.
[Thu May  6 11:50:47 CST 2021] _clearupdns
[Thu May  6 11:50:47 CST 2021] dns_entries
[Thu May  6 11:50:47 CST 2021] skip dns.
[Thu May  6 11:50:47 CST 2021] Verify finished, start to sign.
[Thu May  6 11:50:47 CST 2021] i='2'
[Thu May  6 11:50:47 CST 2021] j='15'
[Thu May  6 11:50:47 CST 2021] Lets finalize the order.
[Thu May  6 11:50:47 CST 2021] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/122457878/9512267135'
[Thu May  6 11:50:47 CST 2021] url='https://acme-v02.api.letsencrypt.org/acme/finalize/122457878/9512267135'
[Thu May  6 11:50:47 CST 2021] payload='{"csr": "MIIClzCCAX8CAQAwGTEXMBUGA1UEAwwOd3d3LjRpdG9vbC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDkTb85xpS-nglYB070fCMHJwOVe7LzIaET0ZuIkoofGmLrd_1qi3AnTejpnPp2HC8Up-LdkMN463QA2DGUqMe77O2WbzMeuQOmDbPkvbgUUNUDfInRiQQBScHfa5oYwMpM3gSFyrKDl-z9GesC1QFR4QrbFeRUWYCh1OV28Ud1b__3k6AmMzcQOJQvtZuo60ON0vfaVEoiPFb4vZvP8eD0t24I-H_pHupMIMf5LxRWhsA-7W1Ci6JkMCdOV86cPJWs7BvB-9sw1YNmWxJk9psVlg9R35hC-oNmXQKGsrX4HNI-g84rafQmdv022ELthSMFbik7iYJFzLbDEwzG9tQlAgMBAAGgOTA3BgkqhkiG9w0BCQ4xKjAoMAsGA1UdDwQEAwIF4DAZBgNVHREEEjAQgg53d3cuNGl0b29sLmNvbTANBgkqhkiG9w0BAQsFAAOCAQEAGCDHFlSHHYoJN-5ViTClBHgGD8kbpS5ulO1LBf3nYWrFQ7J-mfFChoNtMoIlX5KTRJBM5G5Tnc9x6yjsT-saLhaFexBgqmK-wkInTHbY6TtN4AR2wtAw7LvGgJDReEt6Kwi1k_NkhPnRcau_tlsJ_E0AZiMfNlcnVsLuXb1E8iWTDa1RAkN3I19Gw01Uoa6wv3aiZmN253XVZda6IksTFuk_rGO1EE6kaBom1KIM0K4EdDtR0U-72qzFizTEurXaQzJT0RQTE5eb_Dz9KixzjgnJfh4JXburl7POjUMsPd0KyIqs2WocIIKiJgfD28PVuhinoFZ3BBPUcZMTVYpHag"}'
[Thu May  6 11:50:47 CST 2021] POST
[Thu May  6 11:50:47 CST 2021] _post_url='https://acme-v02.api.letsencrypt.org/acme/finalize/122457878/9512267135'
[Thu May  6 11:50:47 CST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[Thu May  6 11:50:47 CST 2021] _ret='0'
[Thu May  6 11:50:47 CST 2021] code='403'
[Thu May  6 11:50:47 CST 2021] Sign failed, finalize code is not 200.
[Thu May  6 11:50:47 CST 2021] {
  "type": "urn:ietf:params:acme:error:orderNotReady",
  "detail": "Order's status (\"invalid\") is not acceptable for finalization",
  "status": 403
}
[Thu May  6 11:50:47 CST 2021] _on_issue_err
[Thu May  6 11:50:47 CST 2021] Please add '--debug' or '--log' to check more details.
[Thu May  6 11:50:47 CST 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Thu May  6 11:50:47 CST 2021] Diagnosis versions: 
openssl:openssl
OpenSSL 1.1.1g FIPS  21 Apr 2020
apache:
apache doesn't exist.
nginx:
nginx version: nginx/1.18.0
built by gcc 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC) 
built with OpenSSL 1.1.1g  21 Apr 2020
TLS SNI support enabled
configure arguments: --user=www --group=www --prefix=/usr/local/nginx --with-http_stub_status_module --with-http_ssl_module --with-http_v2_module --with-http_gzip_static_module --with-http_sub_module --with-stream --with-stream_ssl_module --with-openssl=/opt/lnmp1.7/src/openssl-1.1.1g --with-openssl-opt='enable-weak-ssl-ciphers'
socat:
socat by Gerhard Rieger and contributors - see www.dest-unreach.org
socat version 1.7.3.3 on Apr  7 2020 01:53:21
   running on Linux version #1 SMP Thu Nov 19 17:20:08 UTC 2020, release 4.18.0-240.1.1.el8_3.x86_64, machine x86_64
features:
  #define WITH_STDIO 1
  #define WITH_FDNUM 1
  #define WITH_FILE 1
  #define WITH_CREAT 1
  #define WITH_GOPEN 1
  #define WITH_TERMIOS 1
  #define WITH_PIPE 1
  #define WITH_UNIX 1
  #define WITH_ABSTRACT_UNIXSOCKET 1
  #define WITH_IP4 1
  #define WITH_IP6 1
  #define WITH_RAWIP 1
  #define WITH_GENERICSOCKET 1
  #define WITH_INTERFACE 1
  #define WITH_TCP 1
  #define WITH_UDP 1
  #define WITH_SCTP 1
  #define WITH_LISTEN 1
  #define WITH_SOCKS4 1
  #define WITH_SOCKS4A 1
  #define WITH_PROXY 1
  #define WITH_SYSTEM 1
  #define WITH_EXEC 1
  #define WITH_READLINE 1
  #define WITH_TUN 1
  #define WITH_PTY 1
  #define WITH_OPENSSL 1
  #undef WITH_FIPS
  #undef WITH_LIBWRAP
  #define WITH_SYCLS 1
  #define WITH_FILAN 1
  #define WITH_RETRY 1
  #define WITH_MSGLEVEL 0 /*debug*/

**Comment by HackerBoy856** [comment]
Can you help me if I have problems with it?

**Comment by K-Akechi** [comment]
Same issue for me.

**Comment by kerus1024** [comment]
Same issue.

**Comment by duanxg** [comment]
Same issue.

**Comment by CalmLong** [comment]
Same issue.

**Comment by zevilz** [comment]
Same issue.

**Comment by zevilz** [comment]
```
[Sat 08 May 2021 08:58:39 AM MSK] _CURL='curl --silent --dump-header /var/scripts/letsencrypt_acme/acme.sh/http.header  -L  --trace-ascii /tmp/tmp.7McSXQnIGi  -g '
[Sat 08 May 2021 08:58:40 AM MSK] _ret='0'
[Sat 08 May 2021 08:58:40 AM MSK] responseHeaders='HTTP/2 403 
server: nginx
date: Sat, 08 May 2021 05:58:40 GMT
content-type: application/problem+json
content-length: 152
boulder-requester: 112620207
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
replay-nonce: 00032Ejik-LnArLyTwi_WKTcgHup8Xt52vZ1LKmPJfDVKkk
'
[Sat 08 May 2021 08:58:40 AM MSK] code='403'
[Sat 08 May 2021 08:58:40 AM MSK] original='{
  "type": "urn:ietf:params:acme:error:orderNotReady",
  "detail": "Order's status (\"invalid\") is not acceptable for finalization",
  "status": 403
}'
[Sat 08 May 2021 08:58:40 AM MSK] response='{
  "type": "urn:ietf:params:acme:error:orderNotReady",
  "detail": "Order's status (\"invalid\") is not acceptable for finalization",
  "status": 403
}'
[Sat 08 May 2021 08:58:40 AM MSK] Sign failed, finalize code is not 200.
[Sat 08 May 2021 08:58:40 AM MSK] {
  "type": "urn:ietf:params:acme:error:orderNotReady",
  "detail": "Order's status (\"invalid\") is not acceptable for finalization",
  "status": 403
}
[Sat 08 May 2021 08:58:40 AM MSK] _on_issue_err
[Sat 08 May 2021 08:58:40 AM MSK] Please add '--debug' or '--log' to check more details.
[Sat 08 May 2021 08:58:40 AM MSK] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Sat 08 May 2021 08:58:40 AM MSK] _chk_vlist
[Sat 08 May 2021 08:58:40 AM MSK] Diagnosis versions: 
openssl:openssl
OpenSSL 1.1.1d  10 Sep 2019
apache:
apache doesn't exist.
nginx:
nginx version: nginx/1.18.0
built with OpenSSL 1.1.1d  10 Sep 2019
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-1.18.0=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-compat --with-debug --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_sub_module
socat:
socat by Gerhard Rieger and contributors - see www.dest-unreach.org
socat version 1.7.3.2 on Nov 19 2017 13:56:10
   running on Linux version #1 SMP Debian 4.19.160-2 (2020-11-28), release 4.19.0-13-amd64, machine x86_64
features:
  #define WITH_STDIO 1
  #define WITH_FDNUM 1
  #define WITH_FILE 1
  #define WITH_CREAT 1
  #define WITH_GOPEN 1
  #define WITH_TERMIOS 1
  #define WITH_PIPE 1
  #define WITH_UNIX 1
  #define WITH_ABSTRACT_UNIXSOCKET 1
  #define WITH_IP4 1
  #define WITH_IP6 1
  #define WITH_RAWIP 1
  #define WITH_GENERICSOCKET 1
  #define WITH_INTERFACE 1
  #define WITH_TCP 1
  #define WITH_UDP 1
  #define WITH_SCTP 1
  #define WITH_LISTEN 1
  #define WITH_SOCKS4 1
  #define WITH_SOCKS4A 1
  #define WITH_PROXY 1
  #define WITH_SYSTEM 1
  #define WITH_EXEC 1
  #undef WITH_READLINE
  #define WITH_TUN 1
  #define WITH_PTY 1
  #define WITH_OPENSSL 1
  #undef WITH_FIPS
  #define WITH_LIBWRAP 1
  #define WITH_SYCLS 1
  #define WITH_FILAN 1
  #define WITH_RETRY 1
  #define WITH_MSGLEVEL 0 /*debug*/
```

**Comment by Neilpang** [comment]
upgrade to the last version:

```
acme.sh  --upgrade
```

**Comment by Thalooka** [comment]
@Neilpang with the new version, the error does not appear anymore but also there is no cert generated

**Comment by Neilpang** [comment]
@Thalooka  because you have other errors.

show the log.

**Comment by Thalooka** [comment]
@Neilpang i tried it today again to give you the logs, i gave an error about acme challange failed (it said already valid no txt added)
So i deleted the keys and account configs and tried again, now it works perfectly!

thanks for your great script and have a nice day!
