### ISSUE TITLE
Let's Encrypt E1 issuance

### ISSUE THREAD

**Issue by FozzieHi** [acmesh-official/acme.sh#3510]
How do I get a certificate issued by the E1 intermediate? Looking at https://letsencrypt.org/certificates/ it seems like E1 has been active since at least April 29th 2021. I have had an ECDSA precertificate issued by R3 with acme.sh on May 5th 2021 (https://crt.sh/?id=4479852437). Is there a setting to enable issuance by E1 or is it just not supported yet? Thanks.

**Comment by Neilpang** [comment]
https://community.letsencrypt.org/t/ecdsa-availability-in-production-environment/150679
