### ISSUE TITLE
ecc with hitch renew hook script

### ISSUE THREAD

**Issue by iammeken** [acmesh-official/acme.sh#3513]
Maybe it is not very specific to acme.sh.

I am using hitch.  I want to turn to get ecc certificate.

So I am using this command:
acme.sh --issue  --keylength ec-256 --debug --force  \
   -d  domain.com -d  *.domain.com --challenge-alias sampledomainforvalidation.com --dns dns_gd --renew-hook '/usr/local/bin/hitch-renew-hook' --post-hook 'service hitch reload'

So I get ECC at
 Your cert key is in  /root/.acme.sh/domain.com_ecc/domain.com.key

It is /domain.com_ecc/domain.com.key.

When renew:
acme.sh --renew --force --ecc -d domain.com -d *.domain.com

The current script of hitch-renew-hook will only look in /domain.com_ecc/domain.com_ecc.key, not /domain.com_ecc/domain.com.key:
cat: /root/.acme.sh/domain.com_ecc/domain.com_ecc.key: No such file or directory

/usr/local/bin/hitch-renew-hook:
#!/bin/bash
dhparams=/etc/hitch/dhparams.pem
acmehome=/root/.acme.sh
domain=$(basename $(pwd))
set noglob

umask 077

cat "${acmehome}/${domain}/${domain}.key" \
"${acmehome}/${domain}/fullchain.cer" \
"${dhparams}" > "${acmehome}/${domain}/hitch-bundle.pem"

Please advise, thank you.

# UPDATE: Maybe it is better for acme.sh to also use file structure /root/.acme.sh/domain.com/domain.com.key for ecc? No need to produce a separate  domain.com_ecc directory.

**Comment by Neilpang** [comment]
```
cat: /root/.acme.sh/domain.com_ecc/domain.com_ecc.key: No such file or directory
```

There is no such file.

please use `/root/.acme.sh/domain.com_ecc/domain.com.key:`
