### ISSUE TITLE
Docker版更新证书，如何同步更新nginx

### ISSUE THREAD

**Issue by ryiann** [acmesh-official/acme.sh#3515]
外置nginx，docker容器acme，当ssl证书更新，如何触发`nginx reload`呢？

## 1.安装运行

```
yum install nginx
```

```
docker run --name=acme.sh \
--restart always \
--net=host \
-e Ali_Key="xxxxxx" \
-e Ali_Secret="xxxxxx" \
-v /usr/local/.acme:/acme.sh \
-d neilpang/acme.sh daemon
```

## 2. 生成证书

```
docker exec acme.sh --issue -d *.example.com --dns dns_ali
```

问题：当证书更新，怎么去触发nginx去重新读取配置文件更新证书呢？

**Comment by Neilpang** [comment]
把 nginx 也放到 docker 里面去.

这里可以重新加载docker:
https://github.com/acmesh-official/acme.sh/wiki/deploy-to-docker-containers
