### ISSUE TITLE
Can't install wildcard for VPS

### ISSUE THREAD

**Issue by MESWEB** [acmesh-official/acme.sh#3524]
My hosting using SolusVM. As client I have only API for basic function of server like reboot, shutdown, boot, etc. But I can't add, delete or modify DNS records and I can do it manually by hosting website. It's exist any way to do that automatically? I have enough doing it every 3 months.

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh/wiki/DNS-manual-mode

**Comment by MESWEB** [comment]
@Neilpang Thank you for help but this method is manually:
**Warning: DNS manual mode can not renew automatically.**

**Comment by Neilpang** [comment]
Yes, you must do it manually every 3 months.

If you have another domain, you can use dns alias mode.

https://github.com/acmesh-official/acme.sh/wiki/DNS-alias-mode
