### ISSUE TITLE
[非脚本问题] dns 加 txt 认证的方式有办法解决多级域名限制问题吗？

### ISSUE THREAD

**Issue by yorks** [acmesh-official/acme.sh#3526]
用的是dnspod，但是有限制了 个人只能用 3 级 域名，即 a.b.a.com. 而我刚好有个泛域名解析 *.b.a.com
其中有几个域名是 e.d.c.b.a.com 这么长的，用 txt 认证的时候增加 记录的时候 由于dnspod这个限制导致无法进行。

来这里跟大伙讨教个解决方法。

**Comment by Neilpang** [comment]
加一个 三级域名做别名

https://github.com/acmesh-official/acme.sh/wiki/DNS-alias-mode

**Comment by yorks** [comment]
谢谢，貌似有bug。搜了一下，跟 issue #3339 类似，最后一步失败。

_acme-challenge.sslproxy.yorks.gq. 300 IN CNAME	_acme-challenge.yorks.gq.



<pre>acme.sh --issue -d yorks.gq -d *.yorks.gq   -d *.weixin.qq.com.sslproxy.yorks.gq --challenge-alias yorks.gq   --dns dns_dp  
[Tue Jun  1 10:22:38 UTC 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Tue Jun  1 10:22:38 UTC 2021] Creating domain key
[Tue Jun  1 10:22:38 UTC 2021] The domain key is here: <font color="#55FF55"><b>/home/yorks/.acme.sh/yorks.gq/yorks.gq.key</b></font>
[Tue Jun  1 10:22:38 UTC 2021] Multi domain=&apos;DNS:yorks.gq,DNS:*.yorks.gq,DNS:*.weixin.qq.com.sslproxy.yorks.gq&apos;
[Tue Jun  1 10:22:38 UTC 2021] Getting domain auth token for each domain
[Tue Jun  1 10:22:44 UTC 2021] Getting webroot for domain=&apos;yorks.gq&apos;
[Tue Jun  1 10:22:44 UTC 2021] Getting webroot for domain=&apos;*.yorks.gq&apos;
[Tue Jun  1 10:22:44 UTC 2021] Getting webroot for domain=&apos;*.weixin.qq.com.sslproxy.yorks.gq&apos;
[Tue Jun  1 10:22:44 UTC 2021] Adding txt value: mm893H9PNF9VhvJPUz-L08NdGsLut6dIQtB13mzKjkY for domain:  _acme-challenge.yorks.gq
[Tue Jun  1 10:22:44 UTC 2021] Adding record
[Tue Jun  1 10:22:45 UTC 2021] The txt record is added: Success.
[Tue Jun  1 10:22:45 UTC 2021] Adding txt value: xOckwbB8SB1KY1qWvsT3TQw7beRk-Jc79SzIe6dCmnU for domain:  _acme-challenge.yorks.gq
[Tue Jun  1 10:22:45 UTC 2021] Adding record
[Tue Jun  1 10:22:46 UTC 2021] The txt record is added: Success.
[Tue Jun  1 10:22:46 UTC 2021] Adding txt value: KHMpFAPaKM5zFStzPTMl0-cnuO53ulGeK7aCzw624fM for domain:  _acme-challenge.yorks.gq
[Tue Jun  1 10:22:46 UTC 2021] Adding record
[Tue Jun  1 10:22:46 UTC 2021] The txt record is added: Success.
[Tue Jun  1 10:22:46 UTC 2021] Let&apos;s check each DNS record now. Sleep 20 seconds first.
[Tue Jun  1 10:23:07 UTC 2021] You can use &apos;--dnssleep&apos; to disable public dns checks.
[Tue Jun  1 10:23:07 UTC 2021] See: https://github.com/acmesh-official/acme.sh/wiki/dnscheck
[Tue Jun  1 10:23:07 UTC 2021] Checking yorks.gq for _acme-challenge.yorks.gq
[Tue Jun  1 10:23:08 UTC 2021] Domain yorks.gq &apos;_acme-challenge.yorks.gq&apos; success.
[Tue Jun  1 10:23:08 UTC 2021] Checking yorks.gq for _acme-challenge.yorks.gq
[Tue Jun  1 10:23:08 UTC 2021] Domain yorks.gq &apos;_acme-challenge.yorks.gq&apos; success.
[Tue Jun  1 10:23:08 UTC 2021] Checking weixin.qq.com.sslproxy.yorks.gq for _acme-challenge.yorks.gq
[Tue Jun  1 10:23:08 UTC 2021] Domain weixin.qq.com.sslproxy.yorks.gq &apos;_acme-challenge.yorks.gq&apos; success.
[Tue Jun  1 10:23:08 UTC 2021] All success, let&apos;s return
[Tue Jun  1 10:23:08 UTC 2021] Verifying: yorks.gq
[Tue Jun  1 10:23:12 UTC 2021] <font color="#55FF55"><b>Success</b></font>
[Tue Jun  1 10:23:13 UTC 2021] Verifying: *.yorks.gq
[Tue Jun  1 10:23:17 UTC 2021] <font color="#55FF55"><b>Success</b></font>
[Tue Jun  1 10:23:17 UTC 2021] Verifying: *.weixin.qq.com.sslproxy.yorks.gq
[Tue Jun  1 10:23:21 UTC 2021] <font color="#FF5555"><b>*.weixin.qq.com.sslproxy.yorks.gq:Verify error:No TXT record found at _acme-challenge.weixin.qq.com.sslproxy.yorks.gq</b></font>
[Tue Jun  1 10:23:21 UTC 2021] Removing DNS records.
[Tue Jun  1 10:23:21 UTC 2021] Removing txt: mm893H9PNF9VhvJPUz-L08NdGsLut6dIQtB13mzKjkY for domain: _acme-challenge.yorks.gq
[Tue Jun  1 10:23:22 UTC 2021] Removed: Success
[Tue Jun  1 10:23:22 UTC 2021] Removing txt: xOckwbB8SB1KY1qWvsT3TQw7beRk-Jc79SzIe6dCmnU for domain: _acme-challenge.yorks.gq
[Tue Jun  1 10:23:23 UTC 2021] Removed: Success
[Tue Jun  1 10:23:23 UTC 2021] Removing txt: KHMpFAPaKM5zFStzPTMl0-cnuO53ulGeK7aCzw624fM for domain: _acme-challenge.yorks.gq
[Tue Jun  1 10:23:25 UTC 2021] Removed: Success
[Tue Jun  1 10:23:25 UTC 2021] <font color="#FF5555"><b>Please check log file for more details: /home/yorks/.acme.sh/acme.sh.log</b></font>
</pre>

**Comment by Neilpang** [comment]
前面的域名都验证过了, 只有最后一个没过:  _acme-challenge.weixin.qq.com.sslproxy.yorks.gq
跟那个bug 没关系.

仔细检查一下你的配置.

**Comment by yorks** [comment]
谢谢，是我dns配置问题吗？
我就几条记录。

_acme-challenge.sslproxy.yorks.gq. 600 IN CNAME	_acme-challenge.yorks.gq.
*.sslproxy.yorks.gq.	600	IN	CNAME	proxy.yorks.gq.
proxy.yorks.gq.		600	IN	A	192.168.1.1

去认证 _acme-challenge.weixin.qq.com.sslproxy.yorks.gq 这个 txt 记录 不是应该去检查 _acme-challenge.yorks.gq 的txt记录吗？
_acme-challenge.yorks.gq 的txt记录执行的时候自动加上了的。
