### ISSUE TITLE
zerossl证书申请不成功

### ISSUE THREAD

**Issue by allen12921** [acmesh-official/acme.sh#3527]
Steps to reproduce
------------------
acme.sh --issue --standalone --server  zerossl -d mydomain.com
![image](https://user-images.githubusercontent.com/11305195/119962867-102b9700-bfda-11eb-924c-d8d59d956efa.png)

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

**Comment by Neilpang** [comment]
你再多等2分钟.

**Comment by gkl1368** [comment]
> 你再多等2分钟.

一样的问题 到最后提示invalid。

**Comment by gkl1368** [comment]
> ## Steps to reproduce
> acme.sh --issue --standalone --server zerossl -d mydomain.com
> ![image](https://user-images.githubusercontent.com/11305195/119962867-102b9700-bfda-11eb-924c-d8d59d956efa.png)
> 
> ## Debug log
> ```
> acme.sh  --issue .....   --debug 2
> ```

请问这个问题解决了吗？

**Comment by allen12921** [comment]
没有解决，一直不成功的

**Comment by gkl1368** [comment]
> 没有解决，一直不成功的

我也是这个错误 到最后报invaild。但是在gfw外运行就没有问题。
