### ISSUE TITLE
How to auto update https certs by port 443

### ISSUE THREAD

**Issue by joon612** [acmesh-official/acme.sh#3528]
我现在网站可以使用443端口访问了，并且有了证书，我想关闭80以及其他HTTP协议端口，如何使用HTTPS协议更新证书呢，需要修改脚本参数吗？

**Comment by Neilpang** [comment]
可以试试这个, https://github.com/acmesh-official/acme.sh/wiki/TLS-ALPN-without-downtime

不过,我个人建议你直接放弃.

**Comment by joon612** [comment]
@Neilpang  那是只能通过HTTP协议更新证书吗？
