### ISSUE TITLE
[Question] Will cronjob, when installed, copy the certs-file, key-file, ca-file and fullchain-file as specified in the initial command

### ISSUE THREAD

**Issue by dnk8n** [acmesh-official/acme.sh#3533]
I couldn't see in the documentation where you prefer questions to be asked. I hope I am not breaking any rules.

An example initial command I use:

```
acme.sh \
  --issue \
  --dns ${ACME_DNS} \
  -d ${ACME_DOMAIN} -d "*.${ACME_DOMAIN}" \
  --cert-file ${ACME_CERTS_DIR}/${ACME_DOMAIN}.cer \
  --key-file ${ACME_CERTS_DIR}/${ACME_DOMAIN}.key \
  --ca-file ${ACME_CERTS_DIR}/ca.cer \
  --fullchain-file ${ACME_CERTS_DIR}/fullchain.cer
```

where:

```
ACME_DNS=dns_namecheap
ACME_DOMAIN=some.network
ACME_CERTS_DIR=/media/certs
```

As I understand, renewing is taken care automatically by cron?

I use the certs from ${ACME_CERTS_DIR} location and need to be sure that the cronjob will continue to copy the renewed files here (overwriting the old ones is fine).

Could this fact, if true, be made more explicit in the docs?

**Comment by Neilpang** [comment]
>> renewing is taken care automatically by cron?

Yes.
