### ISSUE TITLE
Announcing the reissue of ZeroSSL is required

### ISSUE THREAD

**Issue by fu-sen** [acmesh-official/acme.sh#3536]
This is not directly related to acme.sh, but since acme.sh issues ZeroSSL using ACME, it is affected by the issued ZeroSSL certificate.

https://help.zerossl.com/hc/en-us/articles/900006733066

Some ZeroSSL certificates may be revoked.
acme.sh will need to inform the user of the ZeroSSL certificate reissue procedure in this regard.
The command level of acme.sh should be able to handle it.

**Comment by Neilpang** [comment]
I received this email too.
I think all the zerossl users will receive the email.

There is nothing we can do here.

**Comment by fu-sen** [comment]
It seems that some users have chosen acme.sh to publish ZeroSSL, so most of these users will be notified by email as well.
I hope they get here.

As long as the certificate is issued and working normally, it seems useless to reissue or renew it.
If the certificate is revoked, it will be automatically reissued by cron, or we will be aware of this and can reissue it.

On the ZeroSSL website, ZeroSSL has announced maintenance in a few hours, so maybe we will receive a change in the certificate.

**Comment by fu-sen** [comment]
Certificate revocation took place from June 10th to 11th. 
Chrome and Edge will continue to display the revocation certificate, and Firefox will receive it and display an error.
You may receive a related issue. It looks like acme.sh (cron) is not updating this automatically.

**Comment by fu-sen** [comment]
This was resolved by forcing a certificate to be issued, For example:
```
acme.sh --issue -d (example.net.eu.org) -w ~/public_html --server zerossl --force
```

**Comment by fu-sen** [comment]
Chrome now returns an ERR_CERT_REVOKED error one day later. However, some domains still return a normal response.
(Probably confirmed at the domain level, which is normal if you are using a subdomain)
Therefore, some people may be aware of this problem in the future.
(ZeroSSL GitHub issue reports users who have not received the email: https://github.com/zerossl/zerossl/issues/10#issuecomment-860046215 )
But we already have a solution to this.
