### ISSUE TITLE
请考虑添为安装脚本提供中国大陆Gitee的镜像以改善网络访问

### ISSUE THREAD

**Issue by 1e101** [acmesh-official/acme.sh#3537]
因为一些原因，在中国大陆连接github会受阻。为了保证软件正常安装升级，可以提供一个官方认可的镜像仓库来加速下载。

使用方法：
```bash
curl https://get.acme.sh | sh -s mirror=gitee
```

**Comment by Neilpang** [comment]
你可以用这个仓库:  https://gitee.com/neilpang/acme.sh

可能同步不是很及时, 而且,不能自动更新.
