### ISSUE TITLE
line 3059: !_startswith: command not found

### ISSUE THREAD

**Issue by Chilinot** [acmesh-official/acme.sh#3548]
In the latest version (commit 9293bcfb1cd5a56c6cede3f5f46af8529ee99624) the nginx mode is broken. Trying to issue a certificate results in the error in the title of this issue.

There was a similar issue created earlier, and it seems the fix is the same for this one. Adding an extra space on line 3059 between the exclamation point and the `_startswith` command.

Namely changing this:
```
if !_startswith "$included" "/" && _exists dirname; then
```
to this:
```
if ! _startswith "$included" "/" && _exists dirname; then
```

**Comment by Neilpang** [comment]
it's fixed.  try latest dev branch:

```
acme.sh  --upgrade -b dev
```
