### ISSUE TITLE
请问支持ip证书了吗

### ISSUE THREAD

**Issue by yuu2lee4** [acmesh-official/acme.sh#3558]
我看去年lts encrypt计划支持IP地址证书（https://letsencrypt.org/zh-cn/upcoming-features），最新的 https://letsencrypt.org/upcoming-features 已经没有这个feature了，不知道支持了没有

**Comment by Neilpang** [comment]
acme.sh  可以支持 ip 证书.  但是 目前没有 ca 开放(通过 acme 协议) 申请ip 证书.

**Comment by yuu2lee4** [comment]
好像lts encrypt支持ip证书了，你的意思是只是没有开发acme 协议申请？

**Comment by stevenzhu25** [comment]
@yuu2lee4 抱歉， Let's Encrypt现在还没有支持IP证书（英版已经更新， 中文版……我最近更新去）。 ZeroSSL CA支持IP证书 但是不支持通过ACME协议申请。

**Comment by youyiqin** [comment]
说一句，ZeroSSL 支持裸 IP SSL。

**Comment by ttimasdf** [comment]
Step-CA 已经支持了对于 IP 地址的 HTTP-01 和 TLS-ALPN-01 验证（ https://github.com/smallstep/certificates/issues/410 ）。可以自建 CA 嘛。
