### ISSUE TITLE
sed -i: needs an argument on FreeBSD

### ISSUE THREAD

**Issue by dlangille** [acmesh-official/acme.sh#3563]
No action required here. It's just an FYI.

I wanted to let you know about a patch we just applied on FreeBSD for [dnsapi/dns_nsd.sh](https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_nsd.sh#L54)

"sed -"i is different on FreeBSD (probably on BSD in general). It needs an argument.

[This PR](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=256664) mentioned it, and I applied the patch today.  I'm not sure if it's useful upstream to you or not.

The line we have now is:

```
sed -i bak "/$fulldomain. $ttlvalue IN TXT \"$txtvalue\"/d" "$Nsd_ZoneFile"
```

**Comment by Neilpang** [comment]
Thanks for reporting.

I will check it.

**Comment by Neilpang** [comment]
fixed.  please try again with the `dev` branch.

```
acme.sh --upgrade -b dev
```

It will be in the next release.
