### ISSUE TITLE
acme.sh via Docker container on custom port

### ISSUE THREAD

**Issue by kees-closed** [acmesh-official/acme.sh#3566]
# Introduction
I'm running a Jitsi Meet instance in Docker. Due to the way connections are multiplexed, it's not possible to use a reverse proxy with Nginx or Traefik. It can be used, but the quality of the calls will be heavily affected. Therefore, I use the custom port 8443 and 8080 to allow direct connections to the host. This custom port is needed because Nginx already uses port 80 and 443. Nginx on the host also manages the well-known ACME directory.

# The problem
acme.sh is [run by the Jitsi Docker instance](https://github.com/jitsi/docker-jitsi-meet/blob/d6fac8e0c38294463a535442bba3dd27327b966c/web/rootfs/etc/cont-init.d/10-config#L15), but fails due to the ports already being in use by Nginx on the Docker host.

# Quick fix
A quick fix I applied was by generating the ACME keys on the Docker host itself and then bind the directory with the keys to the directory which acme.sh expects to find [these keys](https://github.com/jitsi/docker-jitsi-meet/blob/d6fac8e0c38294463a535442bba3dd27327b966c/web/rootfs/defaults/ssl.conf#L8-L9). 

This did work, and my Jitsi setup was using the Docker host's key. But now the acme.sh setup inside the container wants to renew the certificates, probably based on old certificate data inside the container. Due to that the container fails and is stuck in loop of trying to create a new certificate, while the certificate provided via the Docker host is already valid.

# Question
Is there a way to fix this in an acme.sh friendly way? Of course I can fork the Jitsi repo and create an extra Docker overlay with some changes to [this](https://github.com/jitsi/docker-jitsi-meet/blob/d6fac8e0c38294463a535442bba3dd27327b966c/web/rootfs/etc/cont-init.d/10-config#L15) file and simply use the already present certificate.

But maybe some advice can be given here to use acme.sh with a non-default port, or some other solution I missed or not thought about.

**Comment by Neilpang** [comment]
check the parameter:  `--httpport`

https://github.com/acmesh-official/acme.sh/wiki/Options-and-Params

**Comment by kees-closed** [comment]
> check the parameter: `--httpport`
> 
> https://github.com/acmesh-official/acme.sh/wiki/Options-and-Params

Interesting. I'll create a pull request for the Jitsi project to use that in the .env file of their docker-compose setup and then implement that parameter in their script. That should indeed fix it.
