### ISSUE TITLE
How to migrate to acme.sh

### ISSUE THREAD

**Issue by pts** [acmesh-official/acme.sh#3575]
This is not a bug, I'm just asking for guidance. I've never used *acme.sh* before, all I did was looking at the GitHub project page and staring at the source code for a few minutes.

I'm trying to migrate to acme.sh from another ACME software. I have a copy of the fullchain.pem (used by nginx as *ssl_certificate*), privkey.pem (used by nginx as *ssl_certificate_key*), cert.pem and chain.pem files. How do I use acme.sh to renew these? Where should I put these files so that acme.sh will find them? I prefer reloading nginx manually (by running *service nginx reload*).

**Comment by Neilpang** [comment]
Sorry, there is no way to migrate.
Read our docs a few more minutes, you will find it's super easy to use.
