### ISSUE TITLE
verify timeout 

### ISSUE THREAD

**Issue by goodboyMa** [acmesh-official/acme.sh#3583]
[Tue Jun 29 08:03:58 UTC 2021] The txt record is added: Success.
[Tue Jun 29 08:03:58 UTC 2021] Sleep 600 seconds for the txt records to take effect
[Tue Jun 29 08:13:58 UTC 2021] ok, let's start to verify
[Tue Jun 29 08:13:58 UTC 2021] Verifying: aax.com
[Tue Jun 29 08:13:58 UTC 2021] d='aax.com'
[Tue Jun 29 08:13:58 UTC 2021] keyauthorization='NISyViEsZlSF1CF-rRihshRIFX5TnCppIsI2hXpmCZw.6yzZ2Ezska1RuH-inYQ7eVYoqtbvMCuqQM8nKRfiB7A'
[Tue Jun 29 08:13:58 UTC 2021] uri='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:13:58 UTC 2021] _currentRoot='dns_ali'
[Tue Jun 29 08:13:59 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:13:59 UTC 2021] payload='{}'
[Tue Jun 29 08:13:59 UTC 2021] POST
[Tue Jun 29 08:13:59 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:13:59 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:14:00 UTC 2021] _ret='0'
[Tue Jun 29 08:14:00 UTC 2021] code='400'
[Tue Jun 29 08:14:00 UTC 2021] The replay Nonce is not valid, let's get a new one, Sleeping 1 seconds.
[Tue Jun 29 08:14:01 UTC 2021] HEAD
[Tue Jun 29 08:14:01 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/newNonce'
[Tue Jun 29 08:14:01 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g  -I  '
[Tue Jun 29 08:14:02 UTC 2021] _ret='0'
[Tue Jun 29 08:14:02 UTC 2021] POST
[Tue Jun 29 08:14:02 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:02 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:14:03 UTC 2021] _ret='0'
[Tue Jun 29 08:14:03 UTC 2021] code='200'
[Tue Jun 29 08:14:03 UTC 2021] trigger validation code: 200
[Tue Jun 29 08:14:03 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:14:05 UTC 2021] checking
[Tue Jun 29 08:14:05 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:05 UTC 2021] payload
[Tue Jun 29 08:14:05 UTC 2021] POST
[Tue Jun 29 08:14:05 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:05 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:14:06 UTC 2021] _ret='0'
[Tue Jun 29 08:14:06 UTC 2021] code='200'
[Tue Jun 29 08:14:06 UTC 2021] Processing
[Tue Jun 29 08:14:06 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:14:08 UTC 2021] checking
[Tue Jun 29 08:14:08 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:08 UTC 2021] payload
[Tue Jun 29 08:14:08 UTC 2021] POST
[Tue Jun 29 08:14:08 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:08 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:14:09 UTC 2021] _ret='0'
[Tue Jun 29 08:14:09 UTC 2021] code='200'
[Tue Jun 29 08:14:09 UTC 2021] Processing
[Tue Jun 29 08:14:09 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:14:11 UTC 2021] checking
[Tue Jun 29 08:14:11 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:11 UTC 2021] payload
[Tue Jun 29 08:14:11 UTC 2021] POST
[Tue Jun 29 08:14:11 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:11 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:14:12 UTC 2021] _ret='0'
[Tue Jun 29 08:14:12 UTC 2021] code='200'
[Tue Jun 29 08:14:12 UTC 2021] Processing
[Tue Jun 29 08:14:12 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:14:14 UTC 2021] checking
[Tue Jun 29 08:14:14 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:14 UTC 2021] payload
[Tue Jun 29 08:14:14 UTC 2021] POST
[Tue Jun 29 08:14:14 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:14 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:14:15 UTC 2021] _ret='0'
[Tue Jun 29 08:14:15 UTC 2021] code='200'
[Tue Jun 29 08:14:15 UTC 2021] Processing
[Tue Jun 29 08:14:15 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:14:17 UTC 2021] checking
[Tue Jun 29 08:14:17 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:17 UTC 2021] payload
[Tue Jun 29 08:14:17 UTC 2021] POST
[Tue Jun 29 08:14:18 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:18 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:14:19 UTC 2021] _ret='0'
[Tue Jun 29 08:14:19 UTC 2021] code='200'
[Tue Jun 29 08:14:19 UTC 2021] Processing
[Tue Jun 29 08:14:19 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:14:21 UTC 2021] checking
[Tue Jun 29 08:14:21 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:21 UTC 2021] payload
[Tue Jun 29 08:14:21 UTC 2021] POST
[Tue Jun 29 08:14:21 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:21 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:14:22 UTC 2021] _ret='0'
[Tue Jun 29 08:14:22 UTC 2021] code='200'
[Tue Jun 29 08:14:22 UTC 2021] Processing
[Tue Jun 29 08:14:22 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:14:24 UTC 2021] checking
[Tue Jun 29 08:14:24 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:24 UTC 2021] payload
[Tue Jun 29 08:14:24 UTC 2021] POST
[Tue Jun 29 08:14:24 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:24 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:14:25 UTC 2021] _ret='0'
[Tue Jun 29 08:14:25 UTC 2021] code='200'
[Tue Jun 29 08:14:25 UTC 2021] Processing
[Tue Jun 29 08:14:25 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:14:27 UTC 2021] checking
[Tue Jun 29 08:14:27 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:27 UTC 2021] payload
[Tue Jun 29 08:14:27 UTC 2021] POST
[Tue Jun 29 08:14:27 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:27 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:14:28 UTC 2021] _ret='0'
[Tue Jun 29 08:14:28 UTC 2021] code='200'
[Tue Jun 29 08:14:28 UTC 2021] Processing
[Tue Jun 29 08:14:28 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:14:30 UTC 2021] checking
[Tue Jun 29 08:14:30 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:30 UTC 2021] payload
[Tue Jun 29 08:14:30 UTC 2021] POST
[Tue Jun 29 08:14:30 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:30 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:14:31 UTC 2021] _ret='0'
[Tue Jun 29 08:14:31 UTC 2021] code='200'
[Tue Jun 29 08:14:31 UTC 2021] Processing
[Tue Jun 29 08:14:31 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:14:33 UTC 2021] checking
[Tue Jun 29 08:14:33 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:33 UTC 2021] payload
[Tue Jun 29 08:14:33 UTC 2021] POST
[Tue Jun 29 08:14:33 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:33 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:14:34 UTC 2021] _ret='0'
[Tue Jun 29 08:14:34 UTC 2021] code='200'
[Tue Jun 29 08:14:34 UTC 2021] Processing
[Tue Jun 29 08:14:34 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:14:36 UTC 2021] checking
[Tue Jun 29 08:14:36 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:36 UTC 2021] payload
[Tue Jun 29 08:14:36 UTC 2021] POST
[Tue Jun 29 08:14:36 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:36 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:14:37 UTC 2021] _ret='0'
[Tue Jun 29 08:14:37 UTC 2021] code='200'
[Tue Jun 29 08:14:38 UTC 2021] Processing
[Tue Jun 29 08:14:38 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:14:40 UTC 2021] checking
[Tue Jun 29 08:14:40 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:40 UTC 2021] payload
[Tue Jun 29 08:14:40 UTC 2021] POST
[Tue Jun 29 08:14:40 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:40 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:14:41 UTC 2021] _ret='0'
[Tue Jun 29 08:14:41 UTC 2021] code='200'
[Tue Jun 29 08:14:41 UTC 2021] Processing
[Tue Jun 29 08:14:41 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:14:43 UTC 2021] checking
[Tue Jun 29 08:14:43 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:43 UTC 2021] payload
[Tue Jun 29 08:14:43 UTC 2021] POST
[Tue Jun 29 08:14:43 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:43 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:14:44 UTC 2021] _ret='0'
[Tue Jun 29 08:14:44 UTC 2021] code='200'
[Tue Jun 29 08:14:44 UTC 2021] Processing
[Tue Jun 29 08:14:44 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:14:46 UTC 2021] checking
[Tue Jun 29 08:14:46 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:46 UTC 2021] payload
[Tue Jun 29 08:14:46 UTC 2021] POST
[Tue Jun 29 08:14:46 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:46 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:14:47 UTC 2021] _ret='0'
[Tue Jun 29 08:14:47 UTC 2021] code='200'
[Tue Jun 29 08:14:47 UTC 2021] Processing
[Tue Jun 29 08:14:47 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:14:49 UTC 2021] checking
[Tue Jun 29 08:14:49 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:49 UTC 2021] payload
[Tue Jun 29 08:14:49 UTC 2021] POST
[Tue Jun 29 08:14:49 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:49 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:14:50 UTC 2021] _ret='0'
[Tue Jun 29 08:14:50 UTC 2021] code='200'
[Tue Jun 29 08:14:50 UTC 2021] Processing
[Tue Jun 29 08:14:50 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:14:52 UTC 2021] checking
[Tue Jun 29 08:14:52 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:52 UTC 2021] payload
[Tue Jun 29 08:14:52 UTC 2021] POST
[Tue Jun 29 08:14:52 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:52 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:14:54 UTC 2021] _ret='0'
[Tue Jun 29 08:14:54 UTC 2021] code='200'
[Tue Jun 29 08:14:54 UTC 2021] Processing
[Tue Jun 29 08:14:54 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:14:56 UTC 2021] checking
[Tue Jun 29 08:14:56 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:56 UTC 2021] payload
[Tue Jun 29 08:14:56 UTC 2021] POST
[Tue Jun 29 08:14:56 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:56 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:14:57 UTC 2021] _ret='0'
[Tue Jun 29 08:14:57 UTC 2021] code='200'
[Tue Jun 29 08:14:57 UTC 2021] Processing
[Tue Jun 29 08:14:57 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:14:59 UTC 2021] checking
[Tue Jun 29 08:14:59 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:59 UTC 2021] payload
[Tue Jun 29 08:14:59 UTC 2021] POST
[Tue Jun 29 08:14:59 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:14:59 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:15:00 UTC 2021] _ret='0'
[Tue Jun 29 08:15:00 UTC 2021] code='200'
[Tue Jun 29 08:15:00 UTC 2021] Processing
[Tue Jun 29 08:15:00 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:15:02 UTC 2021] checking
[Tue Jun 29 08:15:02 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:15:02 UTC 2021] payload
[Tue Jun 29 08:15:02 UTC 2021] POST
[Tue Jun 29 08:15:02 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:15:02 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:15:04 UTC 2021] _ret='0'
[Tue Jun 29 08:15:04 UTC 2021] code='200'
[Tue Jun 29 08:15:04 UTC 2021] Processing
[Tue Jun 29 08:15:04 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:15:06 UTC 2021] checking
[Tue Jun 29 08:15:06 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:15:06 UTC 2021] payload
[Tue Jun 29 08:15:06 UTC 2021] POST
[Tue Jun 29 08:15:06 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:15:06 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:15:07 UTC 2021] _ret='0'
[Tue Jun 29 08:15:07 UTC 2021] code='200'
[Tue Jun 29 08:15:07 UTC 2021] Processing
[Tue Jun 29 08:15:07 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:15:09 UTC 2021] checking
[Tue Jun 29 08:15:09 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:15:09 UTC 2021] payload
[Tue Jun 29 08:15:09 UTC 2021] POST
[Tue Jun 29 08:15:09 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:15:09 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:15:10 UTC 2021] _ret='0'
[Tue Jun 29 08:15:10 UTC 2021] code='200'
[Tue Jun 29 08:15:10 UTC 2021] Processing
[Tue Jun 29 08:15:10 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:15:12 UTC 2021] checking
[Tue Jun 29 08:15:12 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:15:12 UTC 2021] payload
[Tue Jun 29 08:15:12 UTC 2021] POST
[Tue Jun 29 08:15:12 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:15:12 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:15:13 UTC 2021] _ret='0'
[Tue Jun 29 08:15:13 UTC 2021] code='200'
[Tue Jun 29 08:15:13 UTC 2021] Processing
[Tue Jun 29 08:15:13 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:15:15 UTC 2021] checking
[Tue Jun 29 08:15:15 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:15:15 UTC 2021] payload
[Tue Jun 29 08:15:15 UTC 2021] POST
[Tue Jun 29 08:15:15 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:15:15 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:15:16 UTC 2021] _ret='0'
[Tue Jun 29 08:15:16 UTC 2021] code='200'
[Tue Jun 29 08:15:16 UTC 2021] Processing
[Tue Jun 29 08:15:16 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:15:19 UTC 2021] checking
[Tue Jun 29 08:15:19 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:15:19 UTC 2021] payload
[Tue Jun 29 08:15:19 UTC 2021] POST
[Tue Jun 29 08:15:19 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:15:19 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:15:20 UTC 2021] _ret='0'
[Tue Jun 29 08:15:20 UTC 2021] code='200'
[Tue Jun 29 08:15:20 UTC 2021] Processing
[Tue Jun 29 08:15:20 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:15:22 UTC 2021] checking
[Tue Jun 29 08:15:22 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:15:22 UTC 2021] payload
[Tue Jun 29 08:15:22 UTC 2021] POST
[Tue Jun 29 08:15:22 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:15:22 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:15:23 UTC 2021] _ret='0'
[Tue Jun 29 08:15:23 UTC 2021] code='200'
[Tue Jun 29 08:15:23 UTC 2021] Processing
[Tue Jun 29 08:15:23 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:15:25 UTC 2021] checking
[Tue Jun 29 08:15:25 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:15:25 UTC 2021] payload
[Tue Jun 29 08:15:25 UTC 2021] POST
[Tue Jun 29 08:15:25 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:15:25 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:15:26 UTC 2021] _ret='0'
[Tue Jun 29 08:15:26 UTC 2021] code='200'
[Tue Jun 29 08:15:26 UTC 2021] Processing
[Tue Jun 29 08:15:26 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:15:28 UTC 2021] checking
[Tue Jun 29 08:15:28 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:15:28 UTC 2021] payload
[Tue Jun 29 08:15:28 UTC 2021] POST
[Tue Jun 29 08:15:28 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:15:28 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:15:29 UTC 2021] _ret='0'
[Tue Jun 29 08:15:29 UTC 2021] code='200'
[Tue Jun 29 08:15:29 UTC 2021] Processing
[Tue Jun 29 08:15:29 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:15:31 UTC 2021] checking
[Tue Jun 29 08:15:31 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:15:31 UTC 2021] payload
[Tue Jun 29 08:15:31 UTC 2021] POST
[Tue Jun 29 08:15:31 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:15:31 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:15:32 UTC 2021] _ret='0'
[Tue Jun 29 08:15:32 UTC 2021] code='200'
[Tue Jun 29 08:15:32 UTC 2021] Processing
[Tue Jun 29 08:15:32 UTC 2021] sleep 2 secs to verify
[Tue Jun 29 08:15:34 UTC 2021] checking
[Tue Jun 29 08:15:34 UTC 2021] url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:15:34 UTC 2021] payload
[Tue Jun 29 08:15:34 UTC 2021] POST
[Tue Jun 29 08:15:34 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HYgqN1l23PEFjvEk4cWXUw'
[Tue Jun 29 08:15:34 UTC 2021] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9Qzto3Ior  -g '
[Tue Jun 29 08:15:35 UTC 2021] _ret='0'
[Tue Jun 29 08:15:35 UTC 2021] code='200'
[Tue Jun 29 08:15:35 UTC 2021] Processing
[Tue Jun 29 08:15:35 UTC 2021] aax.com:Timeout                    **ERROR**
[Tue Jun 29 08:15:35 UTC 2021] Skip for removelevel:
[Tue Jun 29 08:15:35 UTC 2021] pid
[Tue Jun 29 08:15:35 UTC 2021] No need to restore nginx, skip.
[Tue Jun 29 08:15:35 UTC 2021] _clearupdns

**Comment by goodboyMa** [comment]
Hello,
    When I create a certificate through "DNS alias mode", it will always time out at verify domain,then clearupdns. timeout is 2 minutes. I have 16 domains.
    when I create the certificate through test, it's fine.
    The full debug log is in the following file.
    can you help me?
 Thanks very much!!! 
[acme.sh.log](https://github.com/acmesh-official/acme.sh/files/6731934/acme.sh.log)

**Comment by goodboyMa** [comment]
Supplement：
     acme.sh Ver:  v3.0.0

**Comment by Neilpang** [comment]
please try again later.

**Comment by goodboyMa** [comment]
> 请稍后再试。

Is there any other way? I have tried for 3 days.😣

**Comment by Neilpang** [comment]
set default ca to use letsencrypt

https://github.com/acmesh-official/acme.sh/wiki/Change-default-CA-to-ZeroSSL
