### ISSUE TITLE
New error on cert renewal on synology

### ISSUE THREAD

**Issue by roachkv** [acmesh-official/acme.sh#3590]
I'm getting an "unexpected EOF" error.  I've upgraded Acme.sh and that did not help.

Below is an excerpt of my log. 

Any thoughts?

[Fri Jul  2 11:26:32 EDT 2021] ===Starting cron===
[Fri Jul  2 11:26:32 EDT 2021] Renew: '*.mydomain.com'
/usr/local/share/acme.sh//*.mydomain.com/*.mydomain.com: line 29: unexpected EOF while looking for matching `''
/usr/local/share/acme.sh//*.mydomain.coms/*.mydomain.com.conf: line 30: syntax error: unexpected end of file
[Fri Jul  2 11:26:33 EDT 2021] Skip, Next renewal time is: Mon Aug 30 04:00:56 UTC 2021
[Fri Jul  2 11:26:33 EDT 2021] Add '--force' to force to renew.
[Fri Jul  2 11:26:33 EDT 2021] Skipped *.mydomain.com
[Fri Jul  2 11:26:33 EDT 2021] ===End cron===
ash-4.3# /usr/local/share/acme.sh/acme.sh --force --cron --home /usr/local/share/acme.sh/
[Fri Jul  2 11:26:57 EDT 2021] ===Starting cron===
[Fri Jul  2 11:26:57 EDT 2021] Renew: '*.mydomain.com'
/usr/local/share/acme.sh//*.mydomain.com/*.mydomain.com.conf: line 29: unexpected EOF while looking for matching `''
/usr/local/share/acme.sh//*.mydomain.com/*.mydomain.com.conf: line 30: syntax error: unexpected end of file
...
/usr/local/share/acme.sh/acme.sh: eval: line 2228: unexpected EOF while looking for matching `''
/usr/local/share/acme.sh/acme.sh: eval: line 2229: syntax error: unexpected end of file
[Fri Jul  2 11:27:10 EDT 2021] Logging into localhost:5000
[Fri Jul  2 11:27:12 EDT 2021] Getting certificates in Synology DSM
[Fri Jul  2 11:27:13 EDT 2021] Unable to find certificate:  and $SYNO_Create is not set
[Fri Jul  2 11:27:13 EDT 2021] Error deploy for domain:*.mydomain.com
[Fri Jul  2 11:27:13 EDT 2021] Deploy error.
[Fri Jul  2 11:27:13 EDT 2021] Error renew *.mydomain.com.
[Fri Jul  2 11:27:13 EDT 2021] ===End cron===

**Comment by Neilpang** [comment]
please show me the content of `/usr/local/share/acme.sh//*.mydomain.coms/*.mydomain.com.conf`

**Comment by roachkv** [comment]
In line 30, is the extra space at the end of the word Encrypt causing the error?
====================================================================

Le_Domain='*.mydomain.com'
Le_Alt='no'
Le_Webroot='dns_gd'
Le_PreHook=''
Le_PostHook=''
Le_RenewHook=''

Le_Keylength=''
Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/38242119/10800108181'
Le_DNSSleep='20'
Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/03225939d3f1f7575ebfbb394f823a09562a'
Le_CertCreateTime='1625239626'
Le_CertCreateTimeStr='Fri Jul  2 15:27:06 UTC 2021'
Le_NextRenewTimeStr='Tue Aug 31 15:27:06 UTC 2021'
Le_NextRenewTime='1630337226'
Le_RealCertPath='/usr/syno/etc/certificate/_archive/ABCDEFG/cert.pem'
Le_RealCACertPath='/usr/syno/etc/certificate/_archive/ABCDEFG/chain.pem'
Le_RealKeyPath='/usr/syno/etc/certificate/_archive/ABCDEFG/privkey.pem'
Le_ReloadCmd='__ACME_BASE64__START_L3Vzci9zeW5vL3NiaW4vc3lub3NlcnZpY2VjdGwgLS1yZWxvYWQgbmdpbng=__ACME_BASE64__END_'
Le_RealFullChainPath='/usr/syno/etc/certificate/_archive/ABCDEFG/fullchain.pem'
Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/38242119/10800108181'
Le_DeployHook='synology_dsm,'
SAVED_SYNO_Scheme='http'
SAVED_SYNO_Hostname='localhost'
SAVED_SYNO_Port='5000'
SAVED_SYNO_Username='MYADMINACCTNAME'
SAVED_SYNO_Password='MYPASSWORD'
SAVED_SYNO_DID=''
SAVED_SYNO_Certificate='mydomain.com Let's Encrypt '
Le_API='https://acme-v02.api.letsencrypt.org/directory'

**Comment by Neilpang** [comment]
please remove the single quotation mark `'` in the `SAVED_SYNO_Certificate` value. `Letsencrypt`.

**Comment by roachkv** [comment]
I greatly appreciate your help on all of this.

I removed the single quotation from "Let's".  I also had to change the certificate name in DSM on my Synology to reflect that change.  

I ran the cron job and got an error.  Possibly because the certificate did not need to be renewed?  At any rate, I ran it again from the command line using --force.  I still got an error but the cert expiration date changed from 9/30/2021 to 10/3/2021.  So, presumably the renewal worked, but I'm still getting an error.  

Below is the log from those two attempts at renewal:

[Mon Jul  5 12:55:27 EDT 2021] Running cmd: cron
[Mon Jul  5 12:55:27 EDT 2021] Using config home:/usr/local/share/acme.sh/
[Mon Jul  5 12:55:27 EDT 2021] default_acme_server
[Mon Jul  5 12:55:27 EDT 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Mon Jul  5 12:55:28 EDT 2021] ===Starting cron===
[Mon Jul  5 12:55:28 EDT 2021] Using config home:/usr/local/share/acme.sh/
[Mon Jul  5 12:55:28 EDT 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Mon Jul  5 12:55:28 EDT 2021] _stopRenewOnError
[Mon Jul  5 12:55:28 EDT 2021] _set_level='2'
[Mon Jul  5 12:55:28 EDT 2021] di='/usr/local/share/acme.sh//*.mydomain.com/'
[Mon Jul  5 12:55:28 EDT 2021] d='*.mydomain.com'
[Mon Jul  5 12:55:28 EDT 2021] Using config home:/usr/local/share/acme.sh/
[Mon Jul  5 12:55:28 EDT 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Mon Jul  5 12:55:28 EDT 2021] DOMAIN_PATH='/usr/local/share/acme.sh//*.mydomain.com'
[Mon Jul  5 12:55:28 EDT 2021] Renew: '*.mydomain.com'
[Mon Jul  5 12:55:28 EDT 2021] Le_API='https://acme-v02.api.letsencrypt.org/directory'
[Mon Jul  5 12:55:28 EDT 2021] Using config home:/usr/local/share/acme.sh/
[Mon Jul  5 12:55:28 EDT 2021] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mon Jul  5 12:55:28 EDT 2021] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Mon Jul  5 12:55:28 EDT 2021] GET
[Mon Jul  5 12:55:28 EDT 2021] url='https://acme-v02.api.letsencrypt.org/directory'
[Mon Jul  5 12:55:28 EDT 2021] timeout=
[Mon Jul  5 12:55:28 EDT 2021] _CURL='curl --silent --dump-header /usr/local/share/acme.sh//http.header  -L  -g '
[Mon Jul  5 12:55:28 EDT 2021] ret='0'
[Mon Jul  5 12:55:29 EDT 2021] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Mon Jul  5 12:55:29 EDT 2021] ACME_NEW_AUTHZ
[Mon Jul  5 12:55:29 EDT 2021] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Mon Jul  5 12:55:29 EDT 2021] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Mon Jul  5 12:55:29 EDT 2021] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Mon Jul  5 12:55:29 EDT 2021] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Mon Jul  5 12:55:29 EDT 2021] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Mon Jul  5 12:55:29 EDT 2021] Skip, Next renewal time is: Tue Aug 31 15:27:06 UTC 2021
[Mon Jul  5 12:55:29 EDT 2021] Add '--force' to force to renew.
[Mon Jul  5 12:55:29 EDT 2021] Return code: 2
[Mon Jul  5 12:55:29 EDT 2021] Skipped *.mydomain.com
[Mon Jul  5 12:55:29 EDT 2021] _error_level='3'
[Mon Jul  5 12:55:29 EDT 2021] _set_level='2'
[Mon Jul  5 12:55:29 EDT 2021] ===End cron===
[Mon Jul  5 12:59:18 EDT 2021] Running cmd: cron
[Mon Jul  5 12:59:18 EDT 2021] Using config home:/usr/local/share/acme.sh/
[Mon Jul  5 12:59:18 EDT 2021] default_acme_server
[Mon Jul  5 12:59:18 EDT 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Mon Jul  5 12:59:18 EDT 2021] ===Starting cron===
[Mon Jul  5 12:59:18 EDT 2021] Using config home:/usr/local/share/acme.sh/
[Mon Jul  5 12:59:18 EDT 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Mon Jul  5 12:59:18 EDT 2021] _stopRenewOnError
[Mon Jul  5 12:59:18 EDT 2021] _set_level='2'
[Mon Jul  5 12:59:18 EDT 2021] di='/usr/local/share/acme.sh//*.mydomain.com/'
[Mon Jul  5 12:59:18 EDT 2021] d='*.mydomain.com'
[Mon Jul  5 12:59:18 EDT 2021] Using config home:/usr/local/share/acme.sh/
[Mon Jul  5 12:59:18 EDT 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Mon Jul  5 12:59:18 EDT 2021] DOMAIN_PATH='/usr/local/share/acme.sh//*.mydomain.com'
[Mon Jul  5 12:59:18 EDT 2021] Renew: '*.mydomain.com'
[Mon Jul  5 12:59:18 EDT 2021] Le_API='https://acme-v02.api.letsencrypt.org/directory'
[Mon Jul  5 12:59:18 EDT 2021] Using config home:/usr/local/share/acme.sh/
[Mon Jul  5 12:59:18 EDT 2021] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mon Jul  5 12:59:18 EDT 2021] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Mon Jul  5 12:59:18 EDT 2021] GET
[Mon Jul  5 12:59:18 EDT 2021] url='https://acme-v02.api.letsencrypt.org/directory'
[Mon Jul  5 12:59:18 EDT 2021] timeout=
[Mon Jul  5 12:59:18 EDT 2021] _CURL='curl --silent --dump-header /usr/local/share/acme.sh//http.header  -L  -g '
[Mon Jul  5 12:59:18 EDT 2021] ret='0'
[Mon Jul  5 12:59:19 EDT 2021] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Mon Jul  5 12:59:19 EDT 2021] ACME_NEW_AUTHZ
[Mon Jul  5 12:59:19 EDT 2021] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Mon Jul  5 12:59:19 EDT 2021] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Mon Jul  5 12:59:19 EDT 2021] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Mon Jul  5 12:59:19 EDT 2021] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Mon Jul  5 12:59:19 EDT 2021] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Mon Jul  5 12:59:19 EDT 2021] _main_domain='*.mydomain.com'
[Mon Jul  5 12:59:19 EDT 2021] _alt_domains='no'
[Mon Jul  5 12:59:19 EDT 2021] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Mon Jul  5 12:59:19 EDT 2021] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Mon Jul  5 12:59:19 EDT 2021] Le_NextRenewTime='1630337226'
[Mon Jul  5 12:59:20 EDT 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Mon Jul  5 12:59:20 EDT 2021] _on_before_issue
[Mon Jul  5 12:59:20 EDT 2021] _chk_main_domain='*.mydomain.com'
[Mon Jul  5 12:59:20 EDT 2021] _chk_alt_domains
[Mon Jul  5 12:59:20 EDT 2021] Le_LocalAddress
[Mon Jul  5 12:59:20 EDT 2021] d='*.mydomain.com'
[Mon Jul  5 12:59:20 EDT 2021] Check for domain='*.mydomain.com'
[Mon Jul  5 12:59:20 EDT 2021] _currentRoot='dns_gd'
[Mon Jul  5 12:59:20 EDT 2021] d
[Mon Jul  5 12:59:20 EDT 2021] _saved_account_key_hash is not changed, skip register account.
[Mon Jul  5 12:59:20 EDT 2021] Read key length:
[Mon Jul  5 12:59:20 EDT 2021] _createcsr
[Mon Jul  5 12:59:20 EDT 2021] Single domain='*.mydomain.com'
[Mon Jul  5 12:59:20 EDT 2021] Getting domain auth token for each domain
[Mon Jul  5 12:59:20 EDT 2021] d
[Mon Jul  5 12:59:20 EDT 2021] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Mon Jul  5 12:59:20 EDT 2021] payload='{"identifiers": [{"type":"dns","value":"*.mydomain.com"}]}'
[Mon Jul  5 12:59:20 EDT 2021] RSA key
[Mon Jul  5 12:59:21 EDT 2021] HEAD
[Mon Jul  5 12:59:21 EDT 2021] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Mon Jul  5 12:59:21 EDT 2021] _CURL='curl --silent --dump-header /usr/local/share/acme.sh//http.header  -L  -g  -I  '
[Mon Jul  5 12:59:21 EDT 2021] _ret='0'
[Mon Jul  5 12:59:22 EDT 2021] POST
[Mon Jul  5 12:59:22 EDT 2021] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Mon Jul  5 12:59:22 EDT 2021] _CURL='curl --silent --dump-header /usr/local/share/acme.sh//http.header  -L  -g '
[Mon Jul  5 12:59:22 EDT 2021] _ret='0'
[Mon Jul  5 12:59:22 EDT 2021] code='201'
[Mon Jul  5 12:59:22 EDT 2021] Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/38242119/10868942924'
[Mon Jul  5 12:59:22 EDT 2021] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/38242119/10868942924'
[Mon Jul  5 12:59:22 EDT 2021] url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/14438463765'
[Mon Jul  5 12:59:22 EDT 2021] payload
[Mon Jul  5 12:59:23 EDT 2021] POST
[Mon Jul  5 12:59:23 EDT 2021] _post_url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/14438463765'
[Mon Jul  5 12:59:23 EDT 2021] _CURL='curl --silent --dump-header /usr/local/share/acme.sh//http.header  -L  -g '
[Mon Jul  5 12:59:23 EDT 2021] _ret='0'
[Mon Jul  5 12:59:23 EDT 2021] code='200'
[Mon Jul  5 12:59:24 EDT 2021] d='*.mydomain.com'
[Mon Jul  5 12:59:24 EDT 2021] Getting webroot for domain='*.mydomain.com'
[Mon Jul  5 12:59:24 EDT 2021] _w='dns_gd'
[Mon Jul  5 12:59:24 EDT 2021] _currentRoot='dns_gd'
[Mon Jul  5 12:59:24 EDT 2021] entry='"type":"dns-01","status":"valid","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/14438463765/p6g3Fg","token":"8T8E_DYlqOVSWv0KjHyainhRUXpFPki4QdRSxIF8NBY","validationRecord":[{"hostname":"mydomain.com"'
[Mon Jul  5 12:59:24 EDT 2021] token='8T8E_DYlqOVSWv0KjHyainhRUXpFPki4QdRSxIF8NBY'
[Mon Jul  5 12:59:24 EDT 2021] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/14438463765/p6g3Fg'
[Mon Jul  5 12:59:24 EDT 2021] keyauthorization='8T8E_DYlqOVSWv0KjHyainhRUXpFPki4QdRSxIF8NBY.jQUeu1IBlqUXeKQ2l0Y6daWuYIDQ4mSwzZ35bg_C-lc'
[Mon Jul  5 12:59:24 EDT 2021] *.mydomain.com is already verified.
[Mon Jul  5 12:59:24 EDT 2021] keyauthorization='verified_ok'
[Mon Jul  5 12:59:24 EDT 2021] dvlist='*.mydomain.com#verified_ok#https://acme-v02.api.letsencrypt.org/acme/chall-v3/14438463765/p6g3Fg#dns-01#dns_gd'
[Mon Jul  5 12:59:24 EDT 2021] d
[Mon Jul  5 12:59:24 EDT 2021] vlist='*.mydomain.com#verified_ok#https://acme-v02.api.letsencrypt.org/acme/chall-v3/14438463765/p6g3Fg#dns-01#dns_gd,'
[Mon Jul  5 12:59:24 EDT 2021] d='*.mydomain.com'
[Mon Jul  5 12:59:24 EDT 2021] *.mydomain.com is already verified, skip dns-01.
[Mon Jul  5 12:59:24 EDT 2021] ok, let's start to verify
[Mon Jul  5 12:59:24 EDT 2021] *.mydomain.com is already verified, skip dns-01.
[Mon Jul  5 12:59:24 EDT 2021] pid
[Mon Jul  5 12:59:24 EDT 2021] No need to restore nginx, skip.
[Mon Jul  5 12:59:24 EDT 2021] _clearupdns
[Mon Jul  5 12:59:24 EDT 2021] dns_entries
[Mon Jul  5 12:59:24 EDT 2021] skip dns.
[Mon Jul  5 12:59:24 EDT 2021] Verify finished, start to sign.
[Mon Jul  5 12:59:24 EDT 2021] i='2'
[Mon Jul  5 12:59:24 EDT 2021] j='15'
[Mon Jul  5 12:59:24 EDT 2021] Lets finalize the order.
[Mon Jul  5 12:59:24 EDT 2021] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/38242119/10868942924'
[Mon Jul  5 12:59:24 EDT 2021] url='https://acme-v02.api.letsencrypt.org/acme/finalize/38242119/10868942924'
[Mon Jul  5 12:59:24 EDT 2021] payload='{"csr": "MIICgjCCA{blah, blah, blah}J5OkdL9g"}'
[Mon Jul  5 12:59:24 EDT 2021] POST
[Mon Jul  5 12:59:24 EDT 2021] _post_url='https://acme-v02.api.letsencrypt.org/acme/finalize/38242119/10868942924'
[Mon Jul  5 12:59:24 EDT 2021] _CURL='curl --silent --dump-header /usr/local/share/acme.sh//http.header  -L  -g '
[Mon Jul  5 12:59:26 EDT 2021] _ret='0'
[Mon Jul  5 12:59:26 EDT 2021] code='200'
[Mon Jul  5 12:59:26 EDT 2021] Order status is valid.
[Mon Jul  5 12:59:26 EDT 2021] Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/03ac6e8a69951b8b15264adca33ad0eea05d'
[Mon Jul  5 12:59:26 EDT 2021] Downloading cert.
[Mon Jul  5 12:59:26 EDT 2021] Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/03ac6e8a69951b8b15264adca33ad0eea05d'
[Mon Jul  5 12:59:26 EDT 2021] url='https://acme-v02.api.letsencrypt.org/acme/cert/03ac6e8a69951b8b15264adca33ad0eea05d'
[Mon Jul  5 12:59:26 EDT 2021] payload
[Mon Jul  5 12:59:26 EDT 2021] POST
[Mon Jul  5 12:59:26 EDT 2021] _post_url='https://acme-v02.api.letsencrypt.org/acme/cert/03ac6e8a69951b8b15264adca33ad0eea05d'
[Mon Jul  5 12:59:26 EDT 2021] _CURL='curl --silent --dump-header /usr/local/share/acme.sh//http.header  -L  -g '
[Mon Jul  5 12:59:27 EDT 2021] _ret='0'
[Mon Jul  5 12:59:27 EDT 2021] code='200'
[Mon Jul  5 12:59:27 EDT 2021] Found cert chain
[Mon Jul  5 12:59:27 EDT 2021] _end_n='30'
[Mon Jul  5 12:59:27 EDT 2021] Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/03ac6e8a69951b8b15264adca33ad0eea05d'
[Mon Jul  5 12:59:27 EDT 2021] Cert success.
[Mon Jul  5 12:59:27 EDT 2021] Your cert is in  /usr/local/share/acme.sh//*.mydomain.com/*.mydomain.com.cer 
[Mon Jul  5 12:59:27 EDT 2021] Your cert key is in  /usr/local/share/acme.sh//*.mydomain.com/*.mydomain.com.key 
[Mon Jul  5 12:59:27 EDT 2021] The intermediate CA cert is in  /usr/local/share/acme.sh//*.mydomain.com/ca.cer 
[Mon Jul  5 12:59:27 EDT 2021] And the full chain certs is there:  /usr/local/share/acme.sh//*.mydomain.com/fullchain.cer 
[Mon Jul  5 12:59:28 EDT 2021] Installing cert to:/usr/syno/etc/certificate/_archive/ABCDEFGH/cert.pem
[Mon Jul  5 12:59:28 EDT 2021] Installing CA to:/usr/syno/etc/certificate/_archive/ABCDEFGH/chain.pem
[Mon Jul  5 12:59:28 EDT 2021] Installing key to:/usr/syno/etc/certificate/_archive/ABCDEFGH/privkey.pem
[Mon Jul  5 12:59:28 EDT 2021] Installing full chain to:/usr/syno/etc/certificate/_archive/ABCDEFGH/fullchain.pem
[Mon Jul  5 12:59:28 EDT 2021] Run reload cmd: /usr/syno/sbin/synoservicectl --reload nginx
[Mon Jul  5 12:59:29 EDT 2021] Reload success
[Mon Jul  5 12:59:29 EDT 2021] _on_issue_success
[Mon Jul  5 12:59:29 EDT 2021] _deployApi='/usr/local/share/acme.sh/deploy/synology_dsm.sh'
[Mon Jul  5 12:59:29 EDT 2021] _cdomain='*.mydomain.com'
[Mon Jul  5 12:59:29 EDT 2021] SYNO_Certificate='mydomain.com Lets Encrypt'
[Mon Jul  5 12:59:29 EDT 2021] _base_url='http://localhost:5000'
[Mon Jul  5 12:59:29 EDT 2021] Getting API version
[Mon Jul  5 12:59:29 EDT 2021] GET
[Mon Jul  5 12:59:29 EDT 2021] url='http://localhost:5000/webapi/query.cgi?api=SYNO.API.Info&version=1&method=query&query=SYNO.API.Auth'
[Mon Jul  5 12:59:29 EDT 2021] timeout=
[Mon Jul  5 12:59:29 EDT 2021] _CURL='curl --silent --dump-header /usr/local/share/acme.sh//http.header  -L  -g '
[Mon Jul  5 12:59:31 EDT 2021] ret='0'
[Mon Jul  5 12:59:31 EDT 2021] Logging into localhost:5000
[Mon Jul  5 12:59:31 EDT 2021] POST
[Mon Jul  5 12:59:31 EDT 2021] _post_url='http://localhost:5000/webapi/auth.cgi?enable_syno_token=yes'
[Mon Jul  5 12:59:31 EDT 2021] _CURL='curl --silent --dump-header /usr/local/share/acme.sh//http.header  -L  -g '
[Mon Jul  5 12:59:32 EDT 2021] _ret='0'
[Mon Jul  5 12:59:32 EDT 2021] token
[Mon Jul  5 12:59:32 EDT 2021] Unable to authenticate to localhost:5000 using http.
[Mon Jul  5 12:59:32 EDT 2021] Check your username and password.
[Mon Jul  5 12:59:32 EDT 2021] Error deploy for domain:*.mydomain.com
[Mon Jul  5 12:59:32 EDT 2021] Deploy error.
[Mon Jul  5 12:59:32 EDT 2021] Return code: 1
[Mon Jul  5 12:59:32 EDT 2021] Error renew *.mydomain.com.
[Mon Jul  5 12:59:32 EDT 2021] _error_level='1'
[Mon Jul  5 12:59:32 EDT 2021] _set_level='2'
[Mon Jul  5 12:59:32 EDT 2021] The NOTIFY_HOOK is empty, just return.
[Mon Jul  5 12:59:32 EDT 2021] ===End cron===
