### ISSUE TITLE
DNS API remove function failing due to open edits on zone

### ISSUE THREAD

**Issue by StuHare** [acmesh-official/acme.sh#3594]
Using the DNS API we need to wait before trying to remove the TXT record, instead of continuing if there is an open edit in progress, else the record is never removed and the subsequent renewals fail.

What is the best way to add 'sleep for 20 secs' to the DNS record removal step?

Want to try and replicate what the _check_dns_entries() function performs for the txt remove.

For example - if the response from the POST contains **"code":"OPEN_ZONE_EDITS"** sleep until the API is ready, or if 15 mins pass then error.

Adding a while loop in the dns_rm() function seems sensible but not sure if this is the best approach.

Any suggestions / recommendations gratefully received.

If this could be added to acme.sh functionality that would be useful too.

**Comment by Neilpang** [comment]
what is the dns api you are using ?

**Comment by StuHare** [comment]
I have had to create a new dns api script for CSC Global / Netnames, based on your recommended template approach.

This is all now resolved and working but there may be room for improvement for the script itself. 
As stated i added a while loop to the function, which sleeps until ready.

I could provide a copy if you think it would be useful to include in the repo.
