### ISSUE TITLE
[Question] What if I want to use reloadcmd but NOT "install" the cert somewhere else?

### ISSUE THREAD

**Issue by tekkitan** [acmesh-official/acme.sh#3597]
I want to issue a cert and keep it where it is generated. I point any services to the default place it is issued/generated. I want to restart services after the cert is renewed, but I don't want to copy the cert anywhere else. Is that a possibility or no?

**Comment by Neilpang** [comment]
```
acme.sh  --install-cert  -d example.com  --reloadcmd "xxxxxxxx  restart"
```
