### ISSUE TITLE
How to define source for installing certificates

### ISSUE THREAD

**Issue by ank0m** [acmesh-official/acme.sh#3604]
I've obtained two sets of certificates (RSA and ECDSA (ec-384)) using the following commands:

## RSA certificates:
```acme.sh --issue -d yakk.xyz -d conference.yakk.xyz -d proxy.yakk.xyz -d pubsub.yakk.xyz -d upload.yakk.xyz --server letsencrypt --keylength 4096 --standalone```

Obtained certificate files are located at ***/home/user/.ame.sh/yakk.xyz***

## ECDSA certificates:
```acme.sh --issue -d yakk.xyz -d conference.yakk.xyz -d proxy.yakk.xyz -d pubsub.yakk.xyz -d upload.yakk.xyz --server letsencrypt --keylength ec-384 --standalone```

Obtained certificate files are located at ***/home/user/.acme.sh/yakk.xyz_ecc***

## Installing certificates:
Now I want to install them using ```acme.sh --install-cert -d yakk.xyz -d conference.yakk.xyz -d proxy.yakk.xyz -d pubsub.yakk.xyz -d upload.yakk.xyz --key-file /output/path/privkey.pem --ca-file /output/path/chain.pem --cert-file /output/path/cert.pem --fullchain-file /output/path/fullchain.pem```

But the question is, how do I specify RSA and ECDSA within installation task?

**Comment by Neilpang** [comment]
it defaults to install the RSA cert.  if you want to install ECC cert, please add `--ecc`

```
acme.sh --install-cert -d xxxxx  ....   --key-file xxxxx    .....       ......       --ecc

```
