### ISSUE TITLE
 acme.sh --issue -d www.kaixinduole.com.com --nginx  --force --days 1 ,测试”--days 1“失败

### ISSUE THREAD

**Issue by ShawnBian** [acmesh-official/acme.sh#3606]
Steps to reproduce
------------------
之前已经成功基于acme.sh去部署了证书，但是是默认的90天自动更新，尝试修改这个时间间隔为1天或者7天。
运行命令：acme.sh --issue -d www.kaixinduole.com --nginx --force --days 1 ，但是报错，https://curl.se/libcurl/c/libcurl-errors.html 的error 35 ，大概是将tls 握手失败。
Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```
[root@nginx2 .acme.sh]#  acme.sh --issue -d www.kaixinduole.com --nginx  --force --days 1 --debug 2
[Thu Jul 15 11:09:38 CST 2021] Lets find script dir.
[Thu Jul 15 11:09:38 CST 2021] _SCRIPT_='/root/.acme.sh/acme.sh'
[Thu Jul 15 11:09:38 CST 2021] _script='/root/.acme.sh/acme.sh'
[Thu Jul 15 11:09:38 CST 2021] _script_home='/root/.acme.sh'
[Thu Jul 15 11:09:38 CST 2021] Using config home:/root/.acme.sh
[Thu Jul 15 11:09:38 CST 2021] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.0
[Thu Jul 15 11:09:38 CST 2021] Running cmd: issue
[Thu Jul 15 11:09:38 CST 2021] _main_domain='www.kaixinduole.com'
[Thu Jul 15 11:09:38 CST 2021] _alt_domains='no'
[Thu Jul 15 11:09:38 CST 2021] Using config home:/root/.acme.sh
[Thu Jul 15 11:09:38 CST 2021] default_acme_server
[Thu Jul 15 11:09:38 CST 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Thu Jul 15 11:09:38 CST 2021] _ACME_SERVER_HOST='acme.zerossl.com'
[Thu Jul 15 11:09:38 CST 2021] _ACME_SERVER_PATH='v2/DV90'
[Thu Jul 15 11:09:38 CST 2021] DOMAIN_PATH='/root/.acme.sh/www.kaixinduole.com'
[Thu Jul 15 11:09:38 CST 2021] 'nginx:' does not contain 'dns'
[Thu Jul 15 11:09:38 CST 2021] Using ACME_DIRECTORY: https://acme.zerossl.com/v2/DV90
[Thu Jul 15 11:09:38 CST 2021] _init api for server: https://acme.zerossl.com/v2/DV90
[Thu Jul 15 11:09:38 CST 2021] GET
[Thu Jul 15 11:09:38 CST 2021] url='https://acme.zerossl.com/v2/DV90'
[Thu Jul 15 11:09:38 CST 2021] timeout=
[Thu Jul 15 11:09:38 CST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.XrRggQu5ps  -g '
[Thu Jul 15 11:09:39 CST 2021] ret='0'
[Thu Jul 15 11:09:39 CST 2021] response='{
  "newNonce": "https://acme.zerossl.com/v2/DV90/newNonce",
  "newAccount": "https://acme.zerossl.com/v2/DV90/newAccount",
  "newOrder": "https://acme.zerossl.com/v2/DV90/newOrder",
  "revokeCert": "https://acme.zerossl.com/v2/DV90/revokeCert",
  "keyChange": "https://acme.zerossl.com/v2/DV90/keyChange",
  "meta": {
    "termsOfService": "https://secure.trust-provider.com/repository/docs/Legacy/20201020_Certificate_Subscriber_Agreement_v_2_4_click.pdf",
    "website": "https://zerossl.com",
    "caaIdentities": ["sectigo.com", "trust-provider.com", "usertrust.com", "comodoca.com", "comodo.com"],
    "externalAccountRequired": true
  }
}'
[Thu Jul 15 11:09:39 CST 2021] ACME_KEY_CHANGE='https://acme.zerossl.com/v2/DV90/keyChange'
[Thu Jul 15 11:09:39 CST 2021] ACME_NEW_AUTHZ
[Thu Jul 15 11:09:39 CST 2021] ACME_NEW_ORDER='https://acme.zerossl.com/v2/DV90/newOrder'
[Thu Jul 15 11:09:39 CST 2021] ACME_NEW_ACCOUNT='https://acme.zerossl.com/v2/DV90/newAccount'
[Thu Jul 15 11:09:39 CST 2021] ACME_REVOKE_CERT='https://acme.zerossl.com/v2/DV90/revokeCert'
[Thu Jul 15 11:09:39 CST 2021] ACME_AGREEMENT='https://secure.trust-provider.com/repository/docs/Legacy/20201020_Certificate_Subscriber_Agreement_v_2_4_click.pdf'
[Thu Jul 15 11:09:39 CST 2021] ACME_NEW_NONCE='https://acme.zerossl.com/v2/DV90/newNonce'
[Thu Jul 15 11:09:39 CST 2021] Le_NextRenewTime
[Thu Jul 15 11:09:39 CST 2021] Using CA: https://acme.zerossl.com/v2/DV90
[Thu Jul 15 11:09:39 CST 2021] _on_before_issue
[Thu Jul 15 11:09:39 CST 2021] _chk_main_domain='www.kaixinduole.com'
[Thu Jul 15 11:09:39 CST 2021] _chk_alt_domains
[Thu Jul 15 11:09:39 CST 2021] 'nginx:' does not contain 'no'
[Thu Jul 15 11:09:39 CST 2021] Le_LocalAddress
[Thu Jul 15 11:09:39 CST 2021] d='www.kaixinduole.com'
[Thu Jul 15 11:09:39 CST 2021] Check for domain='www.kaixinduole.com'
[Thu Jul 15 11:09:39 CST 2021] _currentRoot='nginx:'
[Thu Jul 15 11:09:39 CST 2021] d
[Thu Jul 15 11:09:39 CST 2021] 'nginx:' does not contain 'apache'
[Thu Jul 15 11:09:39 CST 2021] _saved_account_key_hash='EtM6g1DKQR4sr++0Y86c9/6PEJQcWjc6oPGE3d/Z86U='
[Thu Jul 15 11:09:39 CST 2021] _saved_account_key_hash is not changed, skip register account.
[Thu Jul 15 11:09:39 CST 2021] Read key length:
[Thu Jul 15 11:09:39 CST 2021] _createcsr
[Thu Jul 15 11:09:39 CST 2021] domain='www.kaixinduole.com'
[Thu Jul 15 11:09:39 CST 2021] domainlist
[Thu Jul 15 11:09:39 CST 2021] csrkey='/root/.acme.sh/www.kaixinduole.com/www.kaixinduole.com.key'
[Thu Jul 15 11:09:39 CST 2021] csr='/root/.acme.sh/www.kaixinduole.com/www.kaixinduole.com.csr'
[Thu Jul 15 11:09:39 CST 2021] csrconf='/root/.acme.sh/www.kaixinduole.com/www.kaixinduole.com.csr.conf'
[Thu Jul 15 11:09:39 CST 2021] Single domain='www.kaixinduole.com'
[Thu Jul 15 11:09:39 CST 2021] _is_idn_d='www.kaixinduole.com'
[Thu Jul 15 11:09:39 CST 2021] _idn_temp
[Thu Jul 15 11:09:39 CST 2021] _is_idn_d='www.kaixinduole.com'
[Thu Jul 15 11:09:39 CST 2021] _idn_temp
[Thu Jul 15 11:09:39 CST 2021] _csr_cn='www.kaixinduole.com'
[Thu Jul 15 11:09:40 CST 2021] Getting domain auth token for each domain
[Thu Jul 15 11:09:40 CST 2021] _is_idn_d='www.kaixinduole.com'
[Thu Jul 15 11:09:40 CST 2021] _idn_temp
[Thu Jul 15 11:09:40 CST 2021] d
[Thu Jul 15 11:09:40 CST 2021] _identifiers='{"type":"dns","value":"www.kaixinduole.com"}'
[Thu Jul 15 11:09:40 CST 2021] url='https://acme.zerossl.com/v2/DV90/newOrder'
[Thu Jul 15 11:09:40 CST 2021] payload='{"identifiers": [{"type":"dns","value":"www.kaixinduole.com"}]}'
[Thu Jul 15 11:09:40 CST 2021] RSA key
[Thu Jul 15 11:09:40 CST 2021] Get nonce with HEAD. ACME_NEW_NONCE='https://acme.zerossl.com/v2/DV90/newNonce'
[Thu Jul 15 11:09:40 CST 2021] HEAD
[Thu Jul 15 11:09:40 CST 2021] _post_url='https://acme.zerossl.com/v2/DV90/newNonce'
[Thu Jul 15 11:09:40 CST 2021] body
[Thu Jul 15 11:09:40 CST 2021] _postContentType='application/jose+json'
[Thu Jul 15 11:09:40 CST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.sX9ggo4FXs  -g  -I  '
[Thu Jul 15 11:09:41 CST 2021] _ret='0'
[Thu Jul 15 11:09:41 CST 2021] _headers='HTTP/1.1 200 OK
Server: nginx
Date: Thu, 15 Jul 2021 03:09:41 GMT
Content-Type: application/octet-stream
Connection: keep-alive
Replay-Nonce: 8GxE3ELqqNpHSEKPm4yBSgqPBxlw1ygrIKXq7n98RcQ
Cache-Control: max-age=-1
Access-Control-Allow-Origin: *
Link: <https://acme.zerossl.com/v2/DV90>;rel="index"
Strict-Transport-Security: max-age=15552000
'
[Thu Jul 15 11:09:41 CST 2021] _CACHED_NONCE='8GxE3ELqqNpHSEKPm4yBSgqPBxlw1ygrIKXq7n98RcQ'
[Thu Jul 15 11:09:41 CST 2021] nonce='8GxE3ELqqNpHSEKPm4yBSgqPBxlw1ygrIKXq7n98RcQ'
[Thu Jul 15 11:09:41 CST 2021] POST
[Thu Jul 15 11:09:41 CST 2021] _post_url='https://acme.zerossl.com/v2/DV90/newOrder'
[Thu Jul 15 11:09:41 CST 2021] body='{"protected": "eyJub25jZSI6ICI4R3hFM0VMcXFOcEhTRUtQbTR5QlNncVBCeGx3MXlncklLWHE3bjk4UmNRIiwgInVybCI6ICJodHRwczovL2FjbWUuemVyb3NzbC5jb20vdjIvRFY5MC9uZXdPcmRlciIsICJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS56ZXJvc3NsLmNvbS92Mi9EVjkwL2FjY291bnQvTy1fMm9VSVd2TnBTRVhEdTVwT2tLUSJ9", "payload": "eyJpZGVudGlmaWVycyI6IFt7InR5cGUiOiJkbnMiLCJ2YWx1ZSI6Ind3dy5rYWl4aW5kdW9sZS5jb20ifV19", "signature": "lUL_5c_ivJASaZ8MI40fOJA1urfd6315DN_hMlZc3i1rH8J13s7Lu20_kMLxLpjYQJh3DW9hVJYtRKv5UhOBQGbu7UDw-D77HSfuz9CLN_Emakpk1-uKyIIlW8wfqO11cVxHJ4CwYQzGNHLFnrk12NDkXm8lkGmjoVPNhpqKZjL_ibbvkgRCsB_FnjXZH1Kz9tnY8L_67upgGbFJBsisn9zLCLIYjuzTwUI5wRithguDrQM12RmhXJH3MxP6NvmagxmKg2Btd20xWVATtnL51mfLMrXJE7B5_oCVHPtY5fzYogu4cTCUBs3VrYyHYwPYitPJ2XqiJGbIDJyuPSboxg"}'
[Thu Jul 15 11:09:41 CST 2021] _postContentType='application/jose+json'
[Thu Jul 15 11:09:41 CST 2021] Http already initialized.
[Thu Jul 15 11:09:41 CST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.sX9ggo4FXs  -g '
[Thu Jul 15 11:09:41 CST 2021] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 35
[Thu Jul 15 11:09:41 CST 2021] Here is the curl dump log:
[Thu Jul 15 11:09:41 CST 2021] == Info:   Trying 91.199.212.80:443...
== Info:   Trying 2a0e:ac00:c7:d450::5bc7:d450:443...
== Info: Immediate connect fail for 2a0e:ac00:c7:d450::5bc7:d450: Network is unreachable
== Info: Connected to acme.zerossl.com (91.199.212.80) port 443 (#0)
== Info: ALPN, offering http/1.1
== Info: Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
== Info: successfully set certificate verify locations:
== Info:   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
== Info: TLSv1.2 (OUT), TLS header, Certificate Status (22):
=> Send SSL data, 5 bytes (0x5)
0000: .....
== Info: TLSv1.2 (OUT), TLS handshake, Client hello (1):
=> Send SSL data, 512 bytes (0x200)
0000: ..........8cJ.......9{.~6..F......c..Q....0.,.(.$.............k.
0040: j.i.h.9.8.7.6.........2...*.&.......=.5.../.+.'.#.............g.
0080: @.?.>.3.2.1.0.........E.D.C.B.1.-.).%.......<./...A.............
00c0: ............3.........acme.zerossl.com......................... 
0100: .....................................3t.........http/1.1........
0140: ................................................................
0180: ................................................................
01c0: ................................................................
== Info: OpenSSL SSL_connect: Connection reset by peer in connection to acme.zerossl.com:443 
== Info: Closing connection 0
[Thu Jul 15 11:09:41 CST 2021] _ret='35'
[Thu Jul 15 11:09:41 CST 2021] responseHeaders
[Thu Jul 15 11:09:41 CST 2021] code
[Thu Jul 15 11:09:41 CST 2021] original
[Thu Jul 15 11:09:41 CST 2021] response
[Thu Jul 15 11:09:41 CST 2021] Le_LinkOrder
[Thu Jul 15 11:09:41 CST 2021] Le_OrderFinalize
[Thu Jul 15 11:09:41 CST 2021] Create new order error. Le_OrderFinalize not found. 
[Thu Jul 15 11:09:41 CST 2021] pid
[Thu Jul 15 11:09:41 CST 2021] No need to restore nginx, skip.
[Thu Jul 15 11:09:41 CST 2021] _clearupdns
[Thu Jul 15 11:09:41 CST 2021] dns_entries
[Thu Jul 15 11:09:41 CST 2021] skip dns.
[Thu Jul 15 11:09:41 CST 2021] _on_issue_err
[Thu Jul 15 11:09:41 CST 2021] Please add '--debug' or '--log' to check more details.
[Thu Jul 15 11:09:41 CST 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Thu Jul 15 11:09:41 CST 2021] _chk_vlist
[Thu Jul 15 11:09:41 CST 2021] socat doesn't exist.
[Thu Jul 15 11:09:41 CST 2021] Diagnosis versions: 
openssl:openssl
OpenSSL 1.0.2k-fips  26 Jan 2017
apache:
apache doesn't exist.
nginx:
nginx version: nginx/1.15.12
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) 
built with OpenSSL 1.1.1  11 Sep 2018
TLS SNI support enabled
configure arguments: --prefix=/webapps/nginx --sbin-path=/webapps/nginx/sbin/nginx --conf-path=/webapps/nginx/config/nginx.conf --error-log-path=/webapps/nginx/logs/nginx_error.log --http-log-path=/webapps/nginx/logs/nginx_access.log --pid-path=/webapps/nginx/logs/nginx.pid --user=nginx --group=nginx --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-mail --with-mail_ssl_module --with-http_v2_module --with-openssl=/usr/local/src/openssl --with-openssl-opt='enable-tls1_3 enable-weak-ssl-ciphers' --with-http_ssl_module --with-http_gzip_static_module
socat:

问题：
1.请问我这么直接运行命令可以么？
2.如果不可以的话，我该怎么修改更新证书时间间隔为7天或者1天呢？
3.上述报错是否由于访问acme.zerossl.com:443报错呢？如果是的话，是不是解决掉访问acme.zerossl.com:443报错后，就可以了呢？

非常感谢。

**Comment by Neilpang** [comment]
1. 可以
2.  NA
3. 是

**Comment by ShawnBian** [comment]
感谢Neil的解答，第二答复：NA，是说不可以修改吗。多谢。
