### ISSUE TITLE
BUG: /root/.acme.sh/acme.sh: line 5507: /etc/letsencrypt/xxx.com/key.pem: No such file or directory

### ISSUE THREAD

**Issue by iammeken** [acmesh-official/acme.sh#3607]
Why look for /etc/letsencrypt, non-existent directory?

[Sat Jul 17 08:07:50 CST 2021] Your cert is in  /root/.acme.sh/xxx.com/xxx.com.cer
[Sat Jul 17 08:07:50 CST 2021] Your cert key is in  /root/.acme.sh/xxx.com/xxx.com.key
[Sat Jul 17 08:07:50 CST 2021] The intermediate CA cert is in  /root/.acme.sh/xxx.com/ca.cer
[Sat Jul 17 08:07:50 CST 2021] And the full chain certs is there:  /root/.acme.sh/xxx.com/fullchain.cer
[Sat Jul 17 08:07:50 CST 2021] Installing key to:/etc/letsencrypt/xxx.com/key.pem
/root/.acme.sh/acme.sh: line 5507: /etc/letsencrypt/xxx.com/key.pem: No such file or directory

acme.sh --issue  --force --dns dns_gd --server letsencrypt  --dnssleep 30 -d xxx.com -d  *.xxx.com --challenge-alias domainforvalidation.com --renew-hook  '/usr/local/bin/hitch-renew-hook' --post-hook 'service hitch reload'

**Comment by Neilpang** [comment]
```
mkdir -p  /etc/letsencrypt/xxx.com/
```

**Comment by godlikejoke** [comment]
acme.sh --install-cert -d xxxxx.co --key-file       /etc/nginx/ssl/key.key  --fullchain-file /etc/nginx/ssl/cert.crt --reloadcmd     "service nginx force-reload" --debug 2
Lets find script dir.
 _SCRIPT_='/root/.acme.sh/acme.sh'
 _script='/root/.acme.sh/acme.sh'
 _script_home='/root/.acme.sh'
 Using config home:/root/.acme.sh
 LE_WORKING_DIR='/root/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.0
 Running cmd: installcert
 Using config home:/root/.acme.sh
 default_acme_server
 ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
 _ACME_SERVER_HOST='acme.zerossl.com'
 _ACME_SERVER_PATH='v2/DV90'
 DOMAIN_PATH='/root/.acme.sh/xxxxx.co'
 Installing key to:/etc/nginx/ssl/key.key
cat: /root/.acme.sh/xxxxx.co/xxxxx.co.key: Is a directory
