### ISSUE TITLE
Changed DSM credentials and enabled 2FA.  Manual insecure deploy ok, but cron job fails.

### ISSUE THREAD

**Issue by chrispontiga** [acmesh-official/acme.sh#3608]
Steps to reproduce
------------------

I recently changed my credentials and enabled 2FA on my Synology DSM, and then found my cron cert renewal failing. I manually reissued the cert and redeployed with:

```
export SYNO_DID='YOUR VALUE'
$ ./acme.sh --insecure --deploy --home . -d "$CERT_DOMAIN" --deploy-hook synology_dsm
```

This deployment was successful when performed manually.  However, when I force triggered the cron job from Task Scheduler I received the following error in the log:

Debug log
-----------------

```
[Sat Jul 17 18:00:13 PDT 2021] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 51
[Sat Jul 17 18:00:13 PDT 2021] Logging into localhost:5001
[Sat Jul 17 18:00:13 PDT 2021] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 51
[Sat Jul 17 18:00:13 PDT 2021] Unable to authenticate to localhost:5001 using https.
[Sat Jul 17 18:00:13 PDT 2021] Check your username and password.
[Sat Jul 17 18:00:13 PDT 2021] Error deploy for domain: *.domain.com.
```
I have tried this several times and the result is the same.  It's almost as if the new credential or the SYNO_DID are not being applied to the cron deployment.

**Comment by Neilpang** [comment]
what is the cronjob entry:
```
crontab -l
```


It must have the same `--home . `

**Comment by chrispontiga** [comment]
Using Task Scheduler: 
`/usr/local/share/acme.sh/acme.sh --cron --home /usr/local/share/acme.sh/`

**Comment by chrispontiga** [comment]
@Neilpang 
Using Task Scheduler:
/usr/local/share/acme.sh/acme.sh --cron --home /usr/local/share/acme.sh/

**Comment by Saxfusion** [comment]
Same here. Seems that the DID is invalid at every renewal.
If i create a new one deploy does work again.

No matter if cronjob or running as cert-user on the console.
