### ISSUE TITLE
posthook and installcert which runs first after renew cert?

### ISSUE THREAD

**Issue by xqdoo00o** [acmesh-official/acme.sh#3609]
## Steps to reproduce
As I know, `posthook` and `installcert` command would all runs after renew cert.
 
Which command runs first?  They may affect each other in my case, so I need to know the order.

Thanks!

**Comment by xqdoo00o** [comment]
> ## Steps to reproduce
> As I know, `posthook` and `installcert` command would all runs after renew cert.
> 
> Which command runs first?  They may affect each other in my case, so I need to know the order.

Thanks!

**Comment by Neilpang** [comment]
reloadcmd is first.
