### ISSUE TITLE
verifying or processing CA timeout is too short, exists after 30 times

### ISSUE THREAD

**Issue by berrytsakala** [acmesh-official/acme.sh#3622]
the problem:
when trying to issue a cert using ACME.SH, getting these errors:

```
Processing, The CA is processing your order, please just wait. (1/30)
Processing, The CA is processing your order, please just wait. (2/30)
Processing, The CA is processing your order, please just wait. (3/30)
...
ivn.org.il:Timeout
[Sun Jul 25 12:52:10 EDT 2021] Please add '--debug' or '--log' to check more details.
```
(from 1 to 30...) and then the script exists.

I tried at least 6 times, and failed the same every time.

I'm using the same steps for several years, without a problem, until now.

My host is NAMECHEAP, standard hosting, ssh allowed.
The only thing changes is my hosting server site, but I can't see the relevance to this problem...

Steps to reproduce
------------------
```
domain=ivn.org.il
wwwdir=~/$domain
email=hidden@email.com
curl https://get.acme.sh | sh
source ~/.bashrc
acme.sh --register-account --accountemail $email
acme.sh --issue --webroot $wwwdir -d $domain --force
~/.acme.sh/$domain/

acme.sh --upgrade
[Sun Jul 25 12:49:24 EDT 2021] Already uptodate!
[Sun Jul 25 12:49:24 EDT 2021] Upgrade success!
```

Debug log
-----------------
here:

https://pastebin.com/Gk50D61y

What can I do?

**Comment by Neilpang** [comment]
```
acme.sh  --set-default-ca  --server letsencrypt
```
