### ISSUE TITLE
Invocation with '--staging' does not seem to target staging environment for pre-configured domains

### ISSUE THREAD

**Issue by JeroenVogelpoel** [acmesh-official/acme.sh#3623]
Steps to reproduce
------------------

1. Setup and issue a certificate for a domain using the stateless method.
2. Assert that the domain in configured within acme.sh. (dir exists; <domainname>.conf exists within that dir)
3. Assert that the `Le_API` value is set tot a non-staging environment.
4. Issue commands using the "--staging" or "--testing" flag that exceed the rate limits of the production environment.
5. Assert that the production rate limits have been exceeded despite targeting the staging environment.

I have also tried this by manually editing the `Le_API` value in the config to `https://acme-staging-v02.api.letsencrypt.org/directory` which suddenly goes to the staging environment.

Thus it seems that the command line arguments regarding the use of the target environment do not override the used target environment specified in the existing configuration.

Debug log
-----------------

(only the relevant chunk)
```
[Sun Jul 25 20:07:31 UTC 2021] Running cmd: renew
[Sun Jul 25 20:07:31 UTC 2021] Using config home:/home/ec2-user/.acme.sh
[Sun Jul 25 20:07:31 UTC 2021] Using ACME_DIRECTORY: https://acme-staging-v02.api.letsencrypt.org/directory
[Sun Jul 25 20:07:31 UTC 2021] ACME_DIRECTORY='https://acme-staging-v02.api.letsencrypt.org/directory'
[Sun Jul 25 20:07:31 UTC 2021] _ACME_SERVER_HOST='acme-staging-v02.api.letsencrypt.org'
[Sun Jul 25 20:07:31 UTC 2021] _ACME_SERVER_PATH='directory'
[Sun Jul 25 20:07:31 UTC 2021] DOMAIN_PATH='/home/ec2-user/.acme.sh/chinaplus.eu'
[Sun Jul 25 20:07:31 UTC 2021] Renew: 'chinaplus.eu'
[Sun Jul 25 20:07:31 UTC 2021] Le_API='https://acme-v02.api.letsencrypt.org/directory'
[Sun Jul 25 20:07:31 UTC 2021] Using config home:/home/ec2-user/.acme.sh
[Sun Jul 25 20:07:31 UTC 2021] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Sun Jul 25 20:07:31 UTC 2021] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Sun Jul 25 20:07:31 UTC 2021] _ACME_SERVER_PATH='directory'
[Sun Jul 25 20:07:31 UTC 2021] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Sun Jul 25 20:07:31 UTC 2021] Retrying GET
[Sun Jul 25 20:07:31 UTC 2021] GET
[Sun Jul 25 20:07:31 UTC 2021] url='https://acme-v02.api.letsencrypt.org/directory'
```

Notice the `ACME_DIRECTORY=` lines.

**Comment by Neilpang** [comment]
If you are using  `--renew` command, it will always use the previous CA stored in the config file(Le_API).

**Comment by vitahall** [comment]
I think there's a use case for this, though. Consider a domain that at first was set up correctly and worked, and at some point later is misconfigured or backend changes make the configuration invalid. If the admin has to adjust the configuration, they may want to use `--renew` and `--staging` together to avoid reaching production during configuration trial-and-error.

If not this way, would you recommend another way of temporarily switching from prod to test (and then back again)?
