### ISSUE TITLE
Could I register Zerossl account on other machine with same email?

### ISSUE THREAD

**Issue by xqdoo00o** [acmesh-official/acme.sh#3630]
Steps to reproduce
------------------

I have register a new account of zerossl on my own machine and issued some certs.

Could I register zerossl account with same email on other machine. 

If I couldn't, how could I use the same account in other machine?

**Comment by Neilpang** [comment]
yes, I guess.

**Comment by rr307** [comment]
> ## Steps to reproduce
> I have register a new account of zerossl on my own machine and issued some certs.
> 
> Could I register zerossl account with same email on other machine.
> 
> If I couldn't, how could I use the same account in other machine?

try copy ~/.acme.sh/ca/acme.zerossl.com to your new machine
