### ISSUE TITLE
Why default CA changed from letsencrypt to ZeroSSL from 3.0.0?

### ISSUE THREAD

**Issue by aminvakil** [acmesh-official/acme.sh#3639]
Starting from https://github.com/acmesh-official/acme.sh/releases/tag/3.0.0 default CA has been changed from letsencrypt to ZeroSSL.

**I don't (and can't) have any objection to what maintainers decide to do, I'm just grateful for your project.**

But I would be very thankful if you could list some reasons why default CA has been changed and what's the pros of ZeroSSL which led to becoming the default CA instead of letsencrypt which many big companies back it and it's used by many users (definitely more than ZeroSSL).

**Comment by Neilpang** [comment]
Sorry for the confusion, but I had a details post here:

https://community.letsencrypt.org/t/the-acme-sh-will-change-default-ca-to-zerossl-on-august-1st-2021/144052

**Comment by aminvakil** [comment]
This is same as https://github.com/acmesh-official/acme.sh/wiki/Change-default-CA-to-ZeroSSL which has already been mentioned in release notes, reason has not been mentioned here.

Maybe worth mentioning https://community.letsencrypt.org/t/the-acme-sh-will-change-default-ca-to-zerossl-on-august-1st-2021/144052/7 in wiki.

Thanks for your project again!
