### ISSUE TITLE
Upgrading from a git-based installation

### ISSUE THREAD

**Issue by lwg-galuise** [acmesh-official/acme.sh#3642]
Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

Forgive me if this has already been documented / covered.  I did search both the WIKI as well as the other Issues for an answer and came up unable to find an answer to my question.

I have acme.sh installed by first cloning from git.  I installed to /opt/acme.sh and at this point I would like to upgrade to the latest tagged version.  I prefer to be "involved" in the update process to grab only tagged versions vs. pulling master.  I have checked out the latest 3.0.0 tag and the current install is 2.8.9.  Would I just run the same ```./acme.sh --install``` option from where I have acme.sh cloned (/home/myaccount/src/acme.sh)?

Thank you for both acme.sh and for reading this question.

Greg

**Comment by Neilpang** [comment]
>> Would I just run the same ./acme.sh --install option

yes

**Comment by lwg-galuise** [comment]
Thank you!  (Many months later).  I just realized I never replied.  Closing now.  Sorry to leave this open so long.  Thank you!
