### ISSUE TITLE
Retry after: 15

### ISSUE THREAD

**Issue by libea18** [acmesh-official/acme.sh#3661]
i see : 
[Sat Aug 14 17:26:02 UTC 2021] Order status is processing, lets sleep and retry.
[Sat Aug 14 17:26:02 UTC 2021] Retry after: 15

i wanna reduce 15 sec to 2-3 sec
How can I do that? Where should the source and script change? Can you help?

**Comment by Neilpang** [comment]
no, you can not do that.
The server requests that we wait for 15 seconds.
