### ISSUE TITLE
Are exported `_H1`, ... variables safe? Possible header leak of dns api credentials to external systems (generic code flaw)

### ISSUE THREAD

**Issue by dionysius** [acmesh-official/acme.sh#3662]
**So far I can't prove this assumption as I haven't `tcpdump`ed the communication yet**

There is - according to my understanding - a *possible* credentials leak with how the code is written. The code does **not** make sure, that **set headers are reset before the next request**. All those `_H1`, `_H2`, ... variables are in the global scope of the script.

Almost every plugin which uses REST is supposed to use _get() _post and those type of functions. As described by the [DNS-API-Dev-Guide: Additional HTTP headers](https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Dev-Guide#5-additional-http-headers) the _Hx are the only way to set headers and **must be exported** for the code to work.

That means, [everyone who sets such a header](https://github.com/search?q=%22export+_H1%3D%22+repo%3Aacmesh-official%2Facme.sh&type=code) (103 code results as of now) is prone to credentials leak to foreign systems since nobody [resets it](https://github.com/acmesh-official/acme.sh/search?q=%22unset+_H1%22) (0 code results as of now) or [sets it back to empty](https://github.com/search?l=&q=%22export+_H1%3D%22%22%22+repo%3Aacmesh-official%2Facme.sh&type=code) (0 code results as of now). There might be other ways to make sure those variables are emptied, but I couldn't find it at a glance.

As an example the `issue()` function with using a DNS registration type:
- background info: [`_post`](https://github.com/acmesh-official/acme.sh/blob/d96cca382274c7595785a94816ef586e452b7f27/acme.sh#L1872) sends those `_H1`,... variables as headers in various configuration to whatever is defined in `_post_url`
- around [here](https://github.com/acmesh-official/acme.sh/blob/d96cca382274c7595785a94816ef586e452b7f27/acme.sh#L4586) it seems the dns plugin is in action and thus setting the header variables for authentication
  - summary: `_H1`, ..., **possibly set** and one/some `_post`/`_get`/... called to the dns api (depends on plugin)
- around [here](https://github.com/acmesh-official/acme.sh/blob/d96cca382274c7595785a94816ef586e452b7f27/acme.sh#L4746) the validation is triggered, where [here](https://github.com/acmesh-official/acme.sh/blob/d96cca382274c7595785a94816ef586e452b7f27/acme.sh#L2166) the `_post()` is sent, while nothing changed those header variables
  - summary: `_H1`, ..., **not changed**, and once more `_post` called to `$url`, which **now sends the previous set headers again to a foreign system**
 - Whichever request happens after those as well

Tell me if you like that an external CA receives your internal credentials to your dns api.

**Comment by Neilpang** [comment]
>>  All those _H1, _H2, ... variables are in the global scope of the script.

Not true.

Every DNS API call is in a dedicated sub-shell,  it's not in global space.  That was designed to protect the dns api script and the main acme.sh. 

https://github.com/acmesh-official/acme.sh/blob/d96cca382274c7595785a94816ef586e452b7f27/acme.sh#L4574

**Comment by dionysius** [comment]
Wow - so true, how did I miss that... Thank you!
