### ISSUE TITLE
Sign CSR --preferred-chain Override Falls Back to DST Root CA X3 

### ISSUE THREAD

**Issue by yangkenneth** [acmesh-official/acme.sh#3663]
Hey Neil, hope you're doing well! There was previously a thread on this, but looks like an issue has come back where if we are using acme.sh to sign a CSR the --preferred-chain does not work and is still defaulting to DST Root CA X3 even when we define --preferred-chain "ISRG Root X1".

A concern that we have is that DST Root CA X3 is expected to expire September 30 2021 and in both instances where we upgrade to the --dev branch as well as using the production branch we cannot get the X1 Root Certificate. Question is are you able to adjust acme.sh to default to using ISRG Root X1 since the expiration is coming up very shortly? Otherwise would you be able to work with me to pinpoint where this issue is failing? Thanks again!  

Steps to reproduce
------------------
       subprocess.call('{directory}/acme.sh/acme.sh --set-default-ca --server letsencrypt --signcsr --csr {csr} --dns dns_aws --dnssleep 20 --challenge-alias {domain_validation} --preferred-chain "ISRG Root X1" --force'.format(
            directory=os.getenv('HOME'), csr=f'{csr}', domain_validation=XXX), shell=True)

Debug log
-----------------
[Mon Aug 16 11:45:13 PDT 2021] _fissuers='R3
ISRG Root X1'
[Mon Aug 16 11:45:13 PDT 2021] _rootissuer='isrg root x1'
[Mon Aug 16 11:45:13 PDT 2021] Matched issuer in: https://acme-v02.api.letsencrypt.org/acme/cert/[REDACTED]
[Mon Aug 16 11:45:13 PDT 2021] Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/[REDACTED]'
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            03:49:b2:ce:53:ef:a2:83:b9:9c:45:4b:f7:53:8a:4f:6c:49
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, O=Let's Encrypt, CN=R3
        Validity
            Not Before: Aug 16 17:45:09 2021 GMT
            Not After : Nov 14 17:45:07 2021 GMT
```
acme.sh  --issue .....   --debug 2
```

**Comment by Neilpang** [comment]
I don't think you understood correctly.

Here is the letsencrypt chain:
https://letsencrypt.org/2020/12/21/extending-android-compatibility.html


please show me the `ca.cer` in the domain cert path: `~/.acme.sh/domain.com/ca.cer`

**Comment by yangkenneth** [comment]
Sorry I mistyped the issue, what I meant is that the chain is still going from DST Root CA X3 -> R3 even though I'm using the --preferred-chain "ISRG Root X1" overwrite. I have an example of one of the chain for one of the hosts below. Also as far as ca.cer goes this is what is shown:

-----BEGIN CERTIFICATE-----
MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
/kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
nLRbwHOoq7hHwg==
-----END CERTIFICATE-----

![R3](https://user-images.githubusercontent.com/25240077/130330588-f7a03b9f-33c9-4a6c-a66c-9680fb7cd559.png)

When I decoded ca.cer I did notice that the issuer was from ISRG Root X1 but for some reason that's not getting shown in the trust chain in Chrome even though a few months ago it had been.

**Comment by Neilpang** [comment]
if it shows wrong chain in the Chrome address bar,  you probably used a wrong R3 cert.
https://letsencrypt.org/certificates/#intermediate-certificates

There are 2 versions of R3, one is signed by DST, the other is signed by ISRG.

Letsencrypt used to use the DST version, which is shown above,  but they switched to the ISRG vesion.

please update your configuration to use the ca certs in  the `ca.cer`,  don't hardcode any ca cert.

The `ca.cer` is guaranteed to be the correct ca certs.
