### ISSUE TITLE
Mattermost notify

### ISSUE THREAD

**Issue by Ahton89** [acmesh-official/acme.sh#3666]
I apologize, maybe a stupid question, but I'm wondering if there is a notification plugin for the Mattermost? Or is the slack plug-in suitable for notifications in the matermost? Does anyone have experience running notifications on Matthermost?

**Comment by Neilpang** [comment]
Sorry, I can not answer your questions.
Maybe anybody else?

**Comment by Ahton89** [comment]
Sorry, I test notify plugin slack with Mattermost - he is working good! Thank you
