### ISSUE TITLE
Do you support multiple certificate updates?

### ISSUE THREAD

**Issue by ant-songlin** [acmesh-official/acme.sh#3668]
Hi, 
After acme.sh is installed on a server(one server), I will apply for separate certificates for different domain names, such as 10000 domain names. Will the 10000 certificates be automatically renewed before they expire? 

Thank you very much.
----------------------------------------------------------------------------------------------
在同一台服务器上，安装acme.sh后，我会为不同的域名独立申请证书，比如10000个域名，这10000张证书到期前都会自动更新吗？

非常感谢。

**Comment by Neilpang** [comment]
会

**Comment by ant-songlin** [comment]
> 会

好的，谢谢！
