### ISSUE TITLE
Sleep for 10 seconds on renew with DNS - website 404

### ISSUE THREAD

**Issue by JeffSlattery** [acmesh-official/acme.sh#3672]
I issued certificates many months ago using DreamHost DNS.  They have always updated successfully.   This time the log is showing many `Let's wait 10 seconds and check again.`.  It always creates the TXT record for `_acme-challenge.mydomain.tld` successfully then:

```
[Mon Aug 23 12:19:45 EST 2021] Use cloudflare doh server
[Mon Aug 23 12:19:45 EST 2021] Retrying GET
[Mon Aug 23 12:19:45 EST 2021] GET
[Mon Aug 23 12:19:45 EST 2021] url='https://cloudflare-dns.com/dns-query?name=_acme-challenge.mydomain.tld&type=TXT'
[Mon Aug 23 12:19:45 EST 2021] timeout=
[Mon Aug 23 12:19:45 EST 2021] displayError='1'
[Mon Aug 23 12:19:45 EST 2021] _WGET='wget -q'
[Mon Aug 23 12:19:45 EST 2021] ret='0'
[Mon Aug 23 12:19:45 EST 2021] _hcode='0'
[Mon Aug 23 12:19:45 EST 2021] Not valid yet, let's wait 10 seconds and check next one.
```

When I open a browser and enter https://cloudflare-dns.com/dns-query I get a 404.  My guess is Cloudflare isn't supporting this dns-query any more.

If I add `Le_DNSSleep='60'` to ~/.acme.sh/<domain>/<domain>.conf (which bypasses the DNS check by simply waiting 60 seconds) then it works.

Confirmed I've upgraded this morning to 3.0.1

**Comment by nosilver4u** [comment]
According to https://developers.cloudflare.com/1.1.1.1/encrypted-dns/dns-over-https/make-api-requests
that endpoint should still be supported. I don't believe you can load the query in your browser, because you have to send specific HTTP request headers--which is why one gets a 400 error (bad request) in the browser.
