### ISSUE TITLE
Passing --server letsencrypt ignores --staging

### ISSUE THREAD

**Issue by xadhoom** [acmesh-official/acme.sh#3678]
Seems that when issuing a new certificate by passing the `--server letsencrypt` ignores the `--staging` flag, and always calls LE production servers.

Steps to reproduce
------------------
Generate a new cert with something like: (using pdns here, but is not involved in the issue)
`acme.sh --staging --server letsencrypt --issue --debug --dns dns_pdns -d redacted -d *.redacted`

Debug log
-----------------
Using simple debug flag here, not `2` level:

```
[Thu Aug 26 10:52:53 CEST 2021] Selected server: https://acme-v02.api.letsencrypt.org/directory
[Thu Aug 26 10:52:53 CEST 2021] Lets find script dir.
[Thu Aug 26 10:52:53 CEST 2021] _SCRIPT_=;/var/lib/acme/acme.sh;
[Thu Aug 26 10:52:53 CEST 2021] _script=;/var/lib/acme/acme.sh;
[Thu Aug 26 10:52:53 CEST 2021] _script_home=;/var/lib/acme;
[Thu Aug 26 10:52:53 CEST 2021] Using default home:/var/lib/acme/.acme.sh
[Thu Aug 26 10:52:53 CEST 2021] Using config home:/var/lib/acme/.acme.sh
[Thu Aug 26 10:52:53 CEST 2021] Using server: letsencrypt
[Thu Aug 26 10:52:53 CEST 2021] Running cmd: issue
[Thu Aug 26 10:52:53 CEST 2021] _main_domain=;redacted;
[Thu Aug 26 10:52:53 CEST 2021] _alt_domains=;*.redacted;
[Thu Aug 26 10:52:53 CEST 2021] Using config home:/var/lib/acme/.acme.sh
[Thu Aug 26 10:52:53 CEST 2021] ACME_DIRECTORY=;https://acme-v02.api.letsencrypt.org/directory;
[Thu Aug 26 10:52:53 CEST 2021] DOMAIN_PATH=;/var/lib/acme/.acme.sh/staging.holocom.cloud;
[Thu Aug 26 10:52:53 CEST 2021] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Thu Aug 26 10:52:53 CEST 2021] _init api for server: https://acme-v02.api.letsencrypt.org/directory
```

Looking into the code seems that if `--server` is given,  `--staging` is ignored, and something like `letsencrypt_test` must be used for `--server` flag. 
Maybe is worth clarify in the `--staging` help output or make it select `letsencrypt_test` automatically?

**Comment by retoo** [comment]
ffs, I just stumbled over this! @Neilpang

**Comment by Neilpang** [comment]
you can use only `--staging`,

or:  put the `--staging` after the `--server`,   the last one will take effect:
```
acme.sh --issue  --server letsencrypt  --staging .....
```

**Comment by retoo** [comment]
@Neilpang ffs! I stumbled over this again – with the correct order!

it appears like the order doesn't matter, "--staging" appears to have no effect when "--server" is specified

```
# THIS will issue a non-staging cert!
acme.sh --issue --debug 2 --dnssleep 180 --dns dns_gcloud \
   --domain uat.REDACTED \
   --domain internal.uat.REDACTED \
   --challenge-alias REDACTED-letsencrypt-acme-delegation.REDACTED \
   --server letsencrypt \
   --staging 
```

**Comment by Neilpang** [comment]
`--staging/--test` is just a shortcut for `--server letsencrypttest`.
So, don't use  it with any other `--server xxxx`,  the  second one will overwrite the first one.
