### ISSUE TITLE
ACME.sh issues an invalid certificate

### ISSUE THREAD

**Issue by riparise** [acmesh-official/acme.sh#3681]
Steps to reproduce
------------------
I am using namecheap host with cpanel.

Log in with SSH and then:

```
curl https://get.acme.sh | sh
acme.sh --register-account --accountemail XXXXX@XXXX.TLD
acme.sh --issue --webroot ~/www -d www.XXXXX.TLD -d XXXXXX.TLD --force
acme.sh --deploy --deploy-hook cpanel_uapi --domain XXXXX.TLD
```

The certificates are generated and sucessfully installed in the cpanel.

However, the certificates are invalid (tested on chrome and edge).
Looks like the DNS is wrong, my domain is not web-hosting.com.

![image](https://user-images.githubusercontent.com/33234089/131166160-7376ffe3-6b19-4377-9ae0-e586a3f2cf8e.png)

![image](https://user-images.githubusercontent.com/33234089/131166195-cb59789d-9237-4705-a55c-3d99942b2800.png)

![image](https://user-images.githubusercontent.com/33234089/131166216-c9a50c19-46ac-47cf-914a-4c728439f03a.png)

![image](https://user-images.githubusercontent.com/33234089/131166238-bdf0ae92-2724-48ed-994f-4a4e2b8bccdc.png)

**Comment by ysguy** [comment]
Thats not a Letsencrypt cert, are you using an alternate provider to generate?
