### ISSUE TITLE
部署到kong的时候，如何自定义kong的地址

### ISSUE THREAD

**Issue by nookery** [acmesh-official/acme.sh#3690]
```
acme.sh --deploy -d ftp.example.com --deploy-hook kong
```

会自动向127.0.0.1:8001发起请求，但是如果kong API的地址不是127.0.0.1:8001的时候，该如何自定义呢？

**Comment by Neilpang** [comment]
我更新了帮助文档:
https://github.com/acmesh-official/acme.sh/wiki/deployhooks#2-deploy-ssl-cert-on-kong-proxy-engine-based-on-api
