### ISSUE TITLE
clean up all _acme-challange dns records

### ISSUE THREAD

**Issue by feraldruid22** [acmesh-official/acme.sh#3693]
Version affected all incl latest:
v3.0.1

With the dynamic dns update method normally there should be 1 or 2 (in case of star) dns entries for this. The problem is if there are more the script misbehaves, make sure the script cleans out ALL _acme-challange dns entries both before the run and after the run for smooth execution...

**Comment by Neilpang** [comment]
No,  the script is designed to delete only the txt records added by itself.

It's for safety reason.
