### ISSUE TITLE
Verify error: DNS problem: NXDOMAIN looking up A for challenge -  check that a DNS record exists

### ISSUE THREAD

**Issue by hello55555** [acmesh-official/acme.sh#3695]
I have used this script successfully on several domains on the same host. 

But for some reason one won't pass the challenge test. I have compared the DNS entries for my domain to the others that worked well, and they have the same entries, so I am unsure what kind of DNS entry it wants me to add as it seems to be an automated process and the challenge DNS entry it checks for is different every time, so I can't even add it manually.  

`
...
Pending, The CA is processing your order, please just wait. (1/30)
my.domain:Verify error:Fetching http://challenge.my.domain/acme-challenge/C1IHokt82g9lh5FruAw9eNG1AZZt0l-XoPqBF8VCrJ8: DNS problem: NXDOMAIN looking up A for challenge.my.domain - check that a DNS record exists for this domain
`

debug log

`
[Sun Sep  5 14:54:00 EDT 2021] _CURL='curl --silent --dump-header /home/myroot/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.49A9pKS96O  -g  --connect-timeout 1'
[Sun Sep  5 14:54:00 EDT 2021] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Sun Sep  5 14:54:00 EDT 2021] Here is the curl dump log:
[Sun Sep  5 14:54:00 EDT 2021] == Info: About to connect() to my.domain port 80 (#0)
== Info:   Trying 162.0.235.xxx... == Info: connected
== Info: Connected to my.domain (162.0.235.xxx) port 80 (#0)
=> Send header, 190 bytes (0xbe)
0000: GET /.well-known/acme-challenge/hHJmicYzBOt2pntITrGNX8Ov9Ud4ALmO
0040: 9DF22kNPtVY HTTP/1.1
0056: User-Agent: acme.sh/3.0.1 (https://github.com/acmesh-official/ac
0096: me.sh)
009e: Host: my.domain
00af: Accept: */*
00bc:
<= Recv header, 20 bytes (0x14)
0000: HTTP/1.1 302 Found
<= Recv header, 25 bytes (0x19)
0000: content-type: text/html
<= Recv header, 21 bytes (0x15)
0000: content-length: 682
<= Recv header, 37 bytes (0x25)
0000: date: Sun, 05 Sep 2021 18:54:00 GMT
<= Recv header, 19 bytes (0x13)
0000: server: LiteSpeed
<= Recv header, 63 bytes (0x3f)
0000: cache-control: no-cache, no-store, must-revalidate, max-age=0
<= Recv header, 97 bytes (0x61)
0000: location: http://challenge.my.domain/acme-challenge/hHJmicYzBOt2
0040: pntITrGNX8Ov9Ud4ALmO9DF22kNPtVY
<= Recv header, 29 bytes (0x1d)
0000: x-frame-options: SAMEORIGIN
<= Recv header, 2 bytes (0x2)
0000:
== Info: Ignoring the response-body
<= Recv data, 682 bytes (0x2aa)
0000: <!DOCTYPE html>.<html style="height:100%">.<head>.<meta name="vi
0040: ewport" content="width=device-width, initial-scale=1, shrink-to-
0080: fit=no" >.<title> 302 Found
009d: </title></head>.<body style="color: #444; margin:0;font: normal
00dd: 14px/20px Arial, Helvetica, sans-serif; height:100%; background-
011d: color: #fff;">.<div style="height:auto; min-height:100%; ">
015d: <div style="text-align: center; width:800px; margin-left: -400px
019d: ; position:absolute; top: 30%; left:50%;">.        <h1 style="ma
01dd: rgin:0; font-size:150px; line-height:150px; font-weight:bold;">3
021d: 02</h1>.<h2 style="margin-top:20px;font-size: 30px;">Found
0259: </h2>.<p>The document has been temporarily moved.</p>.</div></di
0299: v></body></html>.
== Info: Connection #0 to host my.domain left intact
== Info: Issue another request to this URL: 'http://challenge.my.domain/acme-challenge/hHJmicYzBOt2pntITrGNX8Ov9Ud4ALmO9DF22kNPtVY'
== Info: getaddrinfo(3) failed for challenge.my.domain:80
== Info: Couldn't resolve host 'challenge.my.domain'
== Info: Closing connection #1
== Info: Closing connection #0
[Sun Sep  5 14:54:00 EDT 2021] ret='6'
[Sun Sep  5 14:54:00 EDT 2021] _hcode='6'
`

Any thoughts on the solution? 

Very strange that it worked on about four different domains on the same host, and this one won't work. All the same DNS entries. 

Thanks

**Comment by Neilpang** [comment]
paste the full log with `--debug 2`
