### ISSUE TITLE
Renewed cert is expired.

### ISSUE THREAD

**Issue by mluker** [acmesh-official/acme.sh#3700]
I have been using this scrip for a long time wit no issues, thanks!. But today, I ran it to renew a wildcard cert and the cert that it downloads is expired. It looks to be the old cert actually. 

The encoded cert it prints to the terminal looks to be my current expired cert. When I check https://crt.sh/?q=*.foo.bar, it does show a cert generated that has NOT BEFORE today and NOT after three months from now so thats correct.

**Comment by mluker** [comment]
I added the --server letsencrypt and it worked this morning. Not sure if it was a fluke or what but its working now.

**Comment by Neilpang** [comment]
upgrade to the latest version first:  acme.sh --upgrade
