### ISSUE TITLE
 Sign error, wrong status

### ISSUE THREAD

**Issue by feraldruid22** [acmesh-official/acme.sh#3701]
I'm using the DNS update method. I have tried both the PROD and DEV release of acme.sh.

 /root/.acme.sh/acme.sh -v
https://github.com/acmesh-official/acme.sh
v3.0.1

I have a wildcard domain to update.

I use this command line:
`/root/.acme.sh/acme.sh --issue --force --dns dns_nsupdate -d mycompany.com -d *.mycompany.com`

At the end of the process I always get:
`[Fri Sep 17 07:39:42 CEST 2021] {"status":"invalid","expires":"2021-12-16T07:37:39Z","identifiers":[{"type":"dns","value":"mycompany.com"},{"type":"dns","value":"*.mycompany.com"}],"authorizations":
`

During the process I can successfully verify that it does update the TXT records in the DNS.

I have uploaded the logfile to:

https://pastebin.com/fhPc4L51

Can you please help? Thank you.

**Comment by Neilpang** [comment]
try again with ` --server  letsencrypt`

**Comment by feraldruid22** [comment]
Worked thx! pls make this default in next version.

**Comment by deflorator1980** [comment]
In my case works `--set-default-ca --server letsencrypt`
