### ISSUE TITLE
preferred-chain does not work

### ISSUE THREAD

**Issue by FrankFeng009** [acmesh-official/acme.sh#3711]
I use the following command to apply for a certificate.
 ./acme.sh --issue --force --dns -d "demo.mydomain.com" --yes-I-know-dns-manual-mode-enough-go-ahead-please --server letsencrypt   --preferred-chain  "ISRG Root X1"

In the end I found that the issuer was not X1, but X3.
Does the parameter preferred-chain do not take effect, or is it the wrong way to use it?

**Comment by DatAres37** [comment]
I seem to have the same problem. According to [this post](https://community.letsencrypt.org/t/android-devices-with-dot-configured-interaction-with-new-default-chain/161020/14) the preferred-chain flag should solve this particular problem, but it still doesn't work for me.

**Comment by curby** [comment]
I've tried issuing letsencrypt certs on different systems using v3.0.1, and have gotten different CA chains depending on which system I'm on. On the system that got the X3-signed cert, I then tried setting the preferred chain and re-issuing the cert, but it still comes with an X3 signature. I'm surprised that it's even possible to get an X3-signed cert now that it's expired.
