### ISSUE TITLE
Setting Preferred Chain system wide?

### ISSUE THREAD

**Issue by centminmod** [acmesh-official/acme.sh#3717]
Reading https://github.com/acmesh-official/acme.sh/wiki/Preferred-Chain you can setup preferred chain on the acme.sh command line `--preferred-chain  "ISRG Root X1"`. But is there any way to set it at a config/system wide level similar to how the default CA provider is setup `--set-default-ca --server letsencrypt`?

**Comment by Neilpang** [comment]
good idea.
I will check it soon.

**Comment by Neilpang** [comment]
The default chain should be set as CA related value.
How about like this ?


```
acme.sh  --set-default-chain  --server  letsencrypt  --preferred-chain  'ISRG'
```

**Comment by centminmod** [comment]
That looks good to me

so setting `acme.sh --set-default-ca --server zerossl` will automatically ignore the `--preferred-chain` ?

**Comment by Neilpang** [comment]
Yes, if the `--preferred-chain` value is not a valid chain provided by the `--server`, it will be ignored.

However, zerossl also can provide multiple chains to select.

**Comment by centminmod** [comment]
Oh didn't know zerossl had multiple chains that can be configurable! Nice to have them listed at https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA too :)

**Comment by Neilpang** [comment]
please try with the latest dev code:
Usage is here:
https://github.com/acmesh-official/acme.sh/wiki/Preferred-Chain

**Comment by Neilpang** [comment]
for anyone who wants to updates the exising certs' chain:

```
acme.sh --set-default-chain  isrg  --server letsencrypt
acme.sh  --renewAll --force
```

**Comment by centminmod** [comment]
Thanks @Neilpang moving so fast I need to keep up 👍

**Comment by paede81** [comment]
Thanks for the enhancement.
This fixes my issue I had with unbound DoT and letsEncrypt 

For others struggling with the same issue and same setup. That was the message I saw in unbound:
_ssl handshake failed crypto error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired_

**Comment by gabri-ns** [comment]
> However, zerossl also can provide multiple chains to select.

Hi @Neilpang... just want to ask about this
i've try to search the net and hadn't found any info
