### ISSUE TITLE
Validation issue with fullchain file (nginx server / windows client)

### ISSUE THREAD

**Issue by nitrotm** [acmesh-official/acme.sh#3724]
Steps to reproduce
------------------

Note: unsure if that could happen for newly issued certificate. In our case, this happened on an existing certificate we just renewed (`--renew --force ...`)

Deploy a Let's Encrypt certificate, eg:

```
acme.sh --install-cert -d mydomain.com \
--cert-file /etc/nginx/certs/mydomain.crt \
--key-file /etc/nginx/certs/mydomain.key \
--fullchain-file /etc/nginx/certs/mydomain-full.crt \
--reloadcmd "systemctl reload nginx.service"
```

where nginx is provided the fullchain:

```
server {
    listen              443 ssl;
    server_name         mydomain.com;

    ssl_certificate     /etc/nginx/certs/mydomain-full.crt;
    ssl_certificate_key /etc/nginx/certs/mydomain.key;

    ...
}
```

Issue
-----------------

The problem is that the fullchain contains an obsolete root certificate (`ISRG Root X1`), which means nginx emit the following certificates to the client:

1. the domain's certificate
2. the `R3` intermediate certificate
3. the `ISRG Root X1` certificate (old one, signed by `DST Root CA X3`)

On Windows clients (and maybe other platforms), when nginx sends the `ISRG Root X1` to the client, the Windows validation procedure evaluate it could be an intermediate certificate signed by `DST Root CA X3` which is now expired. There is an alternative path using the newer `ISRG Root X1` in store but it seems Windows strategy is to fail first.

![image](https://user-images.githubusercontent.com/805632/135583313-79ca5f59-d280-49d2-96bd-e8fd5fd2bb99.png)

Solution
-----------------

Manually remove the `ISRG Root X1` from the fullchain file and restart nginx server. In this case, the `R3` validation is done against the correct / up-to-date / trusted `ISRG Root X1` and it succeed. So the chain file for nginx should only contain:

1. the domain's certificate
2. the `R3` intermediate certificate

![image](https://user-images.githubusercontent.com/805632/135583620-2bc49b60-b168-44f5-b1fb-35234123d381.png)

The problem is there is no way to call `acme.sh` to generate a file with just the domain certificate followed by *only* intermediate certificate(s). Or at least a way to generate a file with the intermediate certificate(s) - without the root ca.

Alternatively, `acme.sh` should append the correct root certificate.

**Comment by nitrotm** [comment]
PS. Looking carefully at the content of fullchain, I realized that acme.sh appended an obsolete `ISRG Root X1` signed by `DST Root CA X3` instead of the new one (different fingerprints and the new one is self-signed). But how is this possible? How acme.sh fetches and append intermediates / root certs?

**Comment by Neilpang** [comment]
The  chain is not appended by acme.sh,  it was returned by letsencrypt CA.

you can select the chain by `--preferred-chain`.
https://github.com/acmesh-official/acme.sh/wiki/Preferred-Chain

**Comment by jow-** [comment]
@Neilpang - I am facing the very same issue. I've also seen the suggestion to select another preferred chain in various places all over the web but it does not appear to have any effect in my case, both using `--preferred-chain "ISRG Root X1"` or `--preferred-chain "DST Root CA X3"` will produce a full chain .pem file which contains a trailing ISRG Root X1 which is cross-signed with the expired DST Root CA X3. What preferred chain value do I need to request *exactly* to obtain a non-cross-signed chain from Letsencrypt? I couldn't find any clear and specific answer to this anywhere yet.

**Comment by RichardVine** [comment]
I'm struggling with this too; my full chain is coming back with intermediate 'C=US, O=Internet Security Research Group, CN=ISRG Root X1'  issued by 'O=Digital Signature Trust Co., CN=DST Root CA X3' root.

The generated 'conf' file for my most recent certificate includes the following line which looks curious. This was after specifying --preferred-chain X1.

Le_Preferred_Chain='__ACME_BASE64__START_SVNSRw==__ACME_BASE64__END_'

Is that intentional or should it more obviously be something that represents 'X1'?

(acme.sh 2.2.8)

**Comment by Neilpang** [comment]
There is no bug for `--preferred-chain`, it works as expected.

I just tried :

```
acme.sh --issue -d   mydomain.com  --standalone --preferred-chain  "isrg"
```

I got a fullchain.pem,  including 2 certs:  one for the leaf cert, the other is R3

```
-----BEGIN CERTIFICATE-----
MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
/kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
nLRbwHOoq7hHwg==
-----END CERTIFICATE-----
```

There is no ISRG X1 included.

when find bugs, please make sure to upgrad to the latest code first.

**Comment by jow-** [comment]
It works for me too now. My mistake was simply adding `--preferred-chain` to the update command taken from the crontab. I had to re-issue (`--issue`) the certificate to update the `*.conf` file with `Le_Preferred_Chain=...`

**Comment by Neilpang** [comment]
@jow-   
You don't need to edit the  `*.conf` file,  it's not safe.
And you never have to do so.   just use the `--issue` command with correct parameters.

**Comment by jow-** [comment]
Which is exactly what I did, called `acme.sh --issue --force --preferred-chain ...`

**Comment by RichardVine** [comment]
I've retried successfully too using '--issue' (force); it seems it doesn't work (perhaps intentionally) as a renewal. The conf file still looks odd, but the results are correct.
