### ISSUE TITLE
群晖使用acme.sh更新letsencrypt证书出现错误”error code: 60“的解决方法

### ISSUE THREAD

**Issue by GDrain** [acmesh-official/acme.sh#3729]
在acme.sh中搜索`curl --silent`，将其修改为`curl -k --silent`，其他保持不变即可。

**Comment by Neilpang** [comment]
如果是因为证书信任问题, 不需要改源码, 直接 加上 `--insecure`

**Comment by leey0818** [comment]
Check out issue #3727.

**Comment by leezicai** [comment]
> 如果是因为证书信任问题, 不需要改源码, 直接 加上 `--insecure`

还是改了源码, 不改源码, 定时任务里也都要加上 --insecure, 多少有点不方便

**Comment by leezicai** [comment]
> @leezicai
> 
> > > 定时任务里也都要加上 --insecure, 多少有点不方便
> 
> 不需要, 如果你用过 `--insecure` 参数, 那么 acme.sh 就会记住你需要这个参数, 在 cron 中就会自动应用.

测试了下, 
1. 恢复原码
2. 在acme.sh 命令和curl 命令各自加上 --insecure, 执行一次. 
3. 然后 acme.sh --cron 没有自动应用 --insecure 参数, 仍然有 
 `Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 60`

**Comment by hezudao13** [comment]
> 

可以具体说一下是怎样操作解决的吗

**Comment by hezudao13** [comment]
> > > 在acme.sh 命令和curl 命令各自加上 --insecure, 执行一次.
> 
> 必须用 `--issue --insecure .....` 这个命令成功申请一次证书.

可以具体说一下是怎样操作解决的吗

**Comment by qwe231cvb** [comment]
> 在acme.sh中搜索`curl --silent`，将其修改为`curl -k --silent`，其他保持不变即可。

在acme.sh中搜索`curl --silent`，如何打开acme.sh?

**Comment by chenxuan353** [comment]
搜索发现可能是群晖根证书的原因。
详情可参见
[群晖更新Let's Encrypt域名证书出现code:60错误的根源，及解决方法](https://github.com/andyzhshg/syno-acme/issues/80)

**Comment by trry071** [comment]
curl 的锅，三条命令解决

**Comment by trry071** [comment]
curl 的锅，三条命令解决
update-ca-trust
yum -y update ca-certificates
yum update
