### ISSUE TITLE
DNS challenge verification timeout with multi-domain certs against ZeroSSL

### ISSUE THREAD

**Issue by kralewitz** [acmesh-official/acme.sh#3741]
Hello,

I'm having problems when issuing multi-domain certificates using DNS challenge against ZeroSSL CA. With a certain number of domains (I'm trying with 15), the ACME order seems to be stuck in the `Processing, The CA is processing your order, please just wait.` state and the operation times out.

When the number of requested domains for the multi-domain cert is smaller (most of my certs have 3 domains), the order completes successfully.

I have tried to set `MAX_RETRY_TIMES` to higher value and also increased the interval between polls from 2s to 10s, but the order still doesn't complete even after more than an hour wait.

The same request against LE API completes without issues, which leads me to believe there might be some sort of limit on the number of domains in one request for the ZeroSSL API, but I couldn't find any info on that. Do you have any idea if that is the case?

**Comment by Neilpang** [comment]
I don't know any of such limitations yet.

The Zerossl can timeout if the validation fails.

**Comment by kralewitz** [comment]
I have switched to a paid plan to get to ZeroSSL support and tried to ask them. I will let you know what I find out.
