### ISSUE TITLE
Issue using DNS dns_he works on LE fails on Zero SSL

### ISSUE THREAD

**Issue by K2IE** [acmesh-official/acme.sh#3742]
Subject says it all.  I upgraded today to the latest acme version.  I tried to issue a cert using ZeroSSL and receive the following failure:

[Tue  5 Oct 09:10:57 EDT 2021] code='200'
[Tue  5 Oct 09:10:57 EDT 2021] original='{"status":"invalid","expires":"2022-01-03T13:10:03Z","identifiers":[{"type":"dns","value":"somehost.com"}],"authorizations":["https://acme.zerossl.com/v2/DV90/authz/uc5gp2K2-jlra_tcwieePg"],"finalize":"https://acme.zerossl.com/v2/DV90/order/PuaW-X7YEbVAFxtNXXCrlg/finalize"}'
[Tue  5 Oct 09:10:57 EDT 2021] response='{"status":"invalid","expires":"2022-01-03T13:10:03Z","identifiers":[{"type":"dns","value":"somehost.com"}],"authorizations":["https://acme.zerossl.com/v2/DV90/authz/uc5gp2K2-jlra_tcwieePg"],"finalize":"https://acme.zerossl.com/v2/DV90/order/PuaW-X7YEbVAFxtNXXCrlg/finalize"}'
[Tue  5 Oct 09:10:57 EDT 2021] Sign error, wrong status
[Tue  5 Oct 09:10:57 EDT 2021] {"status":"invalid","expires":"2022-01-03T13:10:03Z","identifiers":[{"type":"dns","value":"somehost.com"}],"authorizations":["https://acme.zerossl.com/v2/DV90/authz/uc5gp2K2-jlra_tcwieePg"],"finalize":"https://acme.zerossl.com/v2/DV90/order/PuaW-X7YEbVAFxtNXXCrlg/finalize"}
[Tue  5 Oct 09:10:57 EDT 2021] _on_issue_err
[Tue  5 Oct 09:10:57 EDT 2021] Please add '--debug' or '--log' to check more details.
[Tue  5 Oct 09:10:57 EDT 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Tue  5 Oct 09:10:57 EDT 2021] _chk_vlist
[Tue  5 Oct 09:10:57 EDT 2021] socat doesn't exist.
[Tue  5 Oct 09:10:57 EDT 2021] Diagnosis versions: 
openssl:openssl
OpenSSL 1.1.1d  10 Sep 2019
apache:
apache doesn't exist.
nginx:
nginx version: nginx/1.14.2
built with OpenSSL 1.1.1d  10 Sep 2019
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-VsO1nf/nginx-1.14.2=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_sub_module --with-http_xslt_module=dynamic --with-stream=dynamic --with-stream_ssl_module --with-stream_ssl_preread_module --with-mail=dynamic --with-mail_ssl_module --add-dynamic-module=/build/nginx-VsO1nf/nginx-1.14.2/debian/modules/http-auth-pam --add-dynamic-module=/build/nginx-VsO1nf/nginx-1.14.2/debian/modules/http-dav-ext --add-dynamic-module=/build/nginx-VsO1nf/nginx-1.14.2/debian/modules/http-echo --add-dynamic-module=/build/nginx-VsO1nf/nginx-1.14.2/debian/modules/http-upstream-fair --add-dynamic-module=/build/nginx-VsO1nf/nginx-1.14.2/debian/modules/http-subs-filter
socat:

If I change the server to LE it works fine as it always has.

**Comment by Neilpang** [comment]
please report this to Zerossl.com  support.

**Comment by K2IE** [comment]
Reported, with a link to this issue.

**Comment by K2IE** [comment]
Zerossl support determined two things...there is some bug that they saw that they are looking at, but the reason that the certificate could not be issued was because I had not updated a DNS CAA record.

After updating the CAA record I was able to issue the certificate, so I will close and trust that whatever other issue they found in my logs will be otherwise addressed as a separate issue.
