### ISSUE TITLE
acme.sh attempts to create /home/,acme on macOS Catalina

### ISSUE THREAD

**Issue by tetsuo29** [acmesh-official/acme.sh#3758]
Steps to reproduce
------------------
On macOS Catalina:
- become root
- Install acme.sh
- Run it in apache mode
- Get the errors:
    mkdir: /home/.acme: Operation not supported
    chmod: /home/.acme: No such file or directory

/home on macOS Catalina is a symlink to /System/Volumes/Data/home which is read only

acme.sh should probably be trying to create /Users/.acme or when run by root, /var/root/.acme (which does get created during install)

Debug log
-----------------

martinatl:~ root# .acme.sh/acme.sh --issue --config-home /var/root/acme -d martinsub.dyndns.org -d martinnav.dyndns.org -m russell_martin@yahoo.com --apache -w /Library/WebServer/Documents/ --debug
[Wed Oct 13 08:50:05 EDT 2021] Lets find script dir.
[Wed Oct 13 08:50:05 EDT 2021] _SCRIPT_='.acme.sh/acme.sh'
[Wed Oct 13 08:50:05 EDT 2021] _script='/var/root/.acme.sh/acme.sh'
[Wed Oct 13 08:50:05 EDT 2021] _script_home='/var/root/.acme.sh'
[Wed Oct 13 08:50:05 EDT 2021] Using default home:/var/root/.acme.sh
[Wed Oct 13 08:50:05 EDT 2021] Using config home:/var/root/acme
https://github.com/acmesh-official/acme.sh
v3.0.1
[Wed Oct 13 08:50:05 EDT 2021] Running cmd: issue
[Wed Oct 13 08:50:05 EDT 2021] _main_domain='martinsub.dyndns.org'
[Wed Oct 13 08:50:05 EDT 2021] _alt_domains='martinnav.dyndns.org'
[Wed Oct 13 08:50:05 EDT 2021] Using config home:/var/root/acme
[Wed Oct 13 08:50:05 EDT 2021] config file is empty, can not read DEFAULT_ACME_SERVER
[Wed Oct 13 08:50:05 EDT 2021] default_acme_server
[Wed Oct 13 08:50:05 EDT 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Wed Oct 13 08:50:05 EDT 2021] DOMAIN_PATH='/var/root/acme/martinsub.dyndns.org'
[Wed Oct 13 08:50:05 EDT 2021] Using ACME_DIRECTORY: https://acme.zerossl.com/v2/DV90
[Wed Oct 13 08:50:05 EDT 2021] _init api for server: https://acme.zerossl.com/v2/DV90
[Wed Oct 13 08:50:05 EDT 2021] Retrying GET
[Wed Oct 13 08:50:05 EDT 2021] GET
[Wed Oct 13 08:50:05 EDT 2021] url='https://acme.zerossl.com/v2/DV90'
[Wed Oct 13 08:50:05 EDT 2021] timeout=
[Wed Oct 13 08:50:05 EDT 2021] displayError='1'
[Wed Oct 13 08:50:05 EDT 2021] _CURL='curl --silent --dump-header /var/root/acme/http.header  -L  -g '
[Wed Oct 13 08:50:05 EDT 2021] ret='0'
[Wed Oct 13 08:50:05 EDT 2021] _hcode='0'
[Wed Oct 13 08:50:05 EDT 2021] ACME_KEY_CHANGE='https://acme.zerossl.com/v2/DV90/keyChange'
[Wed Oct 13 08:50:05 EDT 2021] ACME_NEW_AUTHZ
[Wed Oct 13 08:50:05 EDT 2021] ACME_NEW_ORDER='https://acme.zerossl.com/v2/DV90/newOrder'
[Wed Oct 13 08:50:05 EDT 2021] ACME_NEW_ACCOUNT='https://acme.zerossl.com/v2/DV90/newAccount'
[Wed Oct 13 08:50:05 EDT 2021] ACME_REVOKE_CERT='https://acme.zerossl.com/v2/DV90/revokeCert'
[Wed Oct 13 08:50:05 EDT 2021] ACME_AGREEMENT='https://secure.trust-provider.com/repository/docs/Legacy/20201020_Certificate_Subscriber_Agreement_v_2_4_click.pdf'
[Wed Oct 13 08:50:05 EDT 2021] ACME_NEW_NONCE='https://acme.zerossl.com/v2/DV90/newNonce'
[Wed Oct 13 08:50:05 EDT 2021] Le_NextRenewTime
[Wed Oct 13 08:50:06 EDT 2021] Using CA: https://acme.zerossl.com/v2/DV90
[Wed Oct 13 08:50:06 EDT 2021] _on_before_issue
[Wed Oct 13 08:50:06 EDT 2021] _chk_main_domain='martinsub.dyndns.org'
[Wed Oct 13 08:50:06 EDT 2021] _chk_alt_domains='martinnav.dyndns.org'
[Wed Oct 13 08:50:06 EDT 2021] Le_LocalAddress
[Wed Oct 13 08:50:06 EDT 2021] d='martinsub.dyndns.org'
[Wed Oct 13 08:50:06 EDT 2021] Check for domain='martinsub.dyndns.org'
[Wed Oct 13 08:50:06 EDT 2021] _currentRoot='apache'
[Wed Oct 13 08:50:06 EDT 2021] d='martinnav.dyndns.org'
[Wed Oct 13 08:50:06 EDT 2021] Check for domain='martinnav.dyndns.org'
[Wed Oct 13 08:50:06 EDT 2021] _currentRoot='/Library/WebServer/Documents/'
[Wed Oct 13 08:50:06 EDT 2021] d
[Wed Oct 13 08:50:06 EDT 2021] Using config home:/var/root/acme
[Wed Oct 13 08:50:06 EDT 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Wed Oct 13 08:50:06 EDT 2021] httpdconfname='/private/etc/apache2/httpd.conf'
[Wed Oct 13 08:50:06 EDT 2021] httpdconf='/private/etc/apache2/httpd.conf'
[Wed Oct 13 08:50:06 EDT 2021] httpdconfname='httpd.conf'
[Wed Oct 13 08:50:06 EDT 2021] Checking if there is an error in the apache config file before starting.
[Wed Oct 13 08:50:07 EDT 2021] OK
[Wed Oct 13 08:50:07 EDT 2021] Backup apache config file='/private/etc/apache2/httpd.conf'
[Wed Oct 13 08:50:07 EDT 2021] JFYI, Config file /private/etc/apache2/httpd.conf is backuped to /var/root/acme/httpd.conf
[Wed Oct 13 08:50:07 EDT 2021] In case there is an error that can not be restored automatically, you may try restore it yourself.
[Wed Oct 13 08:50:07 EDT 2021] The backup file will be deleted on success, just forget it.
[Wed Oct 13 08:50:07 EDT 2021] apacheVer='2.4.41'
mkdir: /home/.acme: Operation not supported
chmod: /home/.acme: No such file or directory
[Wed Oct 13 08:50:08 EDT 2021] _saved_account_key_hash is not changed, skip register account.
[Wed Oct 13 08:50:08 EDT 2021] Read key length:
[Wed Oct 13 08:50:08 EDT 2021] _createcsr
[Wed Oct 13 08:50:08 EDT 2021] Multi domain='DNS:martinsub.dyndns.org,DNS:martinnav.dyndns.org'
[Wed Oct 13 08:50:08 EDT 2021] Getting domain auth token for each domain
[Wed Oct 13 08:50:08 EDT 2021] d='martinnav.dyndns.org'
[Wed Oct 13 08:50:08 EDT 2021] d
[Wed Oct 13 08:50:08 EDT 2021] url='https://acme.zerossl.com/v2/DV90/newOrder'
[Wed Oct 13 08:50:08 EDT 2021] payload='{"identifiers": [{"type":"dns","value":"martinsub.dyndns.org"},{"type":"dns","value":"martinnav.dyndns.org"}]}'
[Wed Oct 13 08:50:08 EDT 2021] RSA key
[Wed Oct 13 08:50:08 EDT 2021] Retrying post
[Wed Oct 13 08:50:08 EDT 2021] HEAD
[Wed Oct 13 08:50:08 EDT 2021] _post_url='https://acme.zerossl.com/v2/DV90/newNonce'
[Wed Oct 13 08:50:08 EDT 2021] _CURL='curl --silent --dump-header /var/root/acme/http.header  -L  -g  -I  '
[Wed Oct 13 08:50:08 EDT 2021] _ret='0'
[Wed Oct 13 08:50:08 EDT 2021] _hcode='0'
[Wed Oct 13 08:50:09 EDT 2021] Retrying post
[Wed Oct 13 08:50:09 EDT 2021] POST
[Wed Oct 13 08:50:09 EDT 2021] _post_url='https://acme.zerossl.com/v2/DV90/newOrder'
[Wed Oct 13 08:50:09 EDT 2021] _CURL='curl --silent --dump-header /var/root/acme/http.header  -L  -g '
[Wed Oct 13 08:50:09 EDT 2021] _ret='0'
[Wed Oct 13 08:50:09 EDT 2021] _hcode='0'
[Wed Oct 13 08:50:09 EDT 2021] code='201'
[Wed Oct 13 08:50:09 EDT 2021] Le_LinkOrder='https://acme.zerossl.com/v2/DV90/order/EUlXPfIoHBoauT8VCUM5Dg'
[Wed Oct 13 08:50:09 EDT 2021] Le_OrderFinalize='https://acme.zerossl.com/v2/DV90/order/EUlXPfIoHBoauT8VCUM5Dg/finalize'
[Wed Oct 13 08:50:09 EDT 2021] url='https://acme.zerossl.com/v2/DV90/authz/YSHjAbycf3Lb02wgPsc8JA'
[Wed Oct 13 08:50:09 EDT 2021] payload
[Wed Oct 13 08:50:09 EDT 2021] Retrying post
[Wed Oct 13 08:50:09 EDT 2021] POST
[Wed Oct 13 08:50:09 EDT 2021] _post_url='https://acme.zerossl.com/v2/DV90/authz/YSHjAbycf3Lb02wgPsc8JA'
[Wed Oct 13 08:50:09 EDT 2021] _CURL='curl --silent --dump-header /var/root/acme/http.header  -L  -g '
[Wed Oct 13 08:50:10 EDT 2021] _ret='0'
[Wed Oct 13 08:50:10 EDT 2021] _hcode='0'
[Wed Oct 13 08:50:10 EDT 2021] code='200'
[Wed Oct 13 08:50:10 EDT 2021] url='https://acme.zerossl.com/v2/DV90/authz/DQ1jwO4OfX6R6tw4XiyY8Q'
[Wed Oct 13 08:50:10 EDT 2021] payload
[Wed Oct 13 08:50:10 EDT 2021] Retrying post
[Wed Oct 13 08:50:10 EDT 2021] POST
[Wed Oct 13 08:50:10 EDT 2021] _post_url='https://acme.zerossl.com/v2/DV90/authz/DQ1jwO4OfX6R6tw4XiyY8Q'
[Wed Oct 13 08:50:10 EDT 2021] _CURL='curl --silent --dump-header /var/root/acme/http.header  -L  -g '
[Wed Oct 13 08:50:10 EDT 2021] _ret='0'
[Wed Oct 13 08:50:10 EDT 2021] _hcode='0'
[Wed Oct 13 08:50:10 EDT 2021] code='200'
[Wed Oct 13 08:50:10 EDT 2021] d='martinsub.dyndns.org'
[Wed Oct 13 08:50:10 EDT 2021] Getting webroot for domain='martinsub.dyndns.org'
[Wed Oct 13 08:50:10 EDT 2021] _w='apache'
[Wed Oct 13 08:50:10 EDT 2021] _currentRoot='apache'
[Wed Oct 13 08:50:10 EDT 2021] entry='"type":"http-01","url":"https://acme.zerossl.com/v2/DV90/chall/zbP7IygG2DlgdyTHjs7RWQ","status":"pending","token":"8ddJlEQrz0-v6AZQmBKXsJsklzJIMWuaNKcrs7vKQs8"'
[Wed Oct 13 08:50:11 EDT 2021] token='8ddJlEQrz0-v6AZQmBKXsJsklzJIMWuaNKcrs7vKQs8'
[Wed Oct 13 08:50:11 EDT 2021] uri='https://acme.zerossl.com/v2/DV90/chall/zbP7IygG2DlgdyTHjs7RWQ'
[Wed Oct 13 08:50:11 EDT 2021] keyauthorization='8ddJlEQrz0-v6AZQmBKXsJsklzJIMWuaNKcrs7vKQs8.VUKaGqIG1j6NxNlBkQ0bmW02l7mJaAwZ6jSd9T-RtrQ'
[Wed Oct 13 08:50:11 EDT 2021] dvlist='martinsub.dyndns.org#8ddJlEQrz0-v6AZQmBKXsJsklzJIMWuaNKcrs7vKQs8.VUKaGqIG1j6NxNlBkQ0bmW02l7mJaAwZ6jSd9T-RtrQ#https://acme.zerossl.com/v2/DV90/chall/zbP7IygG2DlgdyTHjs7RWQ#http-01#apache'
[Wed Oct 13 08:50:11 EDT 2021] d='martinnav.dyndns.org'
[Wed Oct 13 08:50:11 EDT 2021] Getting webroot for domain='martinnav.dyndns.org'
[Wed Oct 13 08:50:11 EDT 2021] _w='/Library/WebServer/Documents/'
[Wed Oct 13 08:50:11 EDT 2021] _currentRoot='/Library/WebServer/Documents/'
[Wed Oct 13 08:50:11 EDT 2021] entry='"type":"http-01","url":"https://acme.zerossl.com/v2/DV90/chall/HeUj-GUqOO7FT_Ahy-mPcw","status":"pending","token":"mwb0cLvwYBX9HzbV0y5IJHBFt5EWd5Szid4w2EXkgaQ"'
[Wed Oct 13 08:50:11 EDT 2021] token='mwb0cLvwYBX9HzbV0y5IJHBFt5EWd5Szid4w2EXkgaQ'
[Wed Oct 13 08:50:11 EDT 2021] uri='https://acme.zerossl.com/v2/DV90/chall/HeUj-GUqOO7FT_Ahy-mPcw'
[Wed Oct 13 08:50:11 EDT 2021] keyauthorization='mwb0cLvwYBX9HzbV0y5IJHBFt5EWd5Szid4w2EXkgaQ.VUKaGqIG1j6NxNlBkQ0bmW02l7mJaAwZ6jSd9T-RtrQ'
[Wed Oct 13 08:50:11 EDT 2021] dvlist='martinnav.dyndns.org#mwb0cLvwYBX9HzbV0y5IJHBFt5EWd5Szid4w2EXkgaQ.VUKaGqIG1j6NxNlBkQ0bmW02l7mJaAwZ6jSd9T-RtrQ#https://acme.zerossl.com/v2/DV90/chall/HeUj-GUqOO7FT_Ahy-mPcw#http-01#/Library/WebServer/Documents/'
[Wed Oct 13 08:50:11 EDT 2021] d
[Wed Oct 13 08:50:11 EDT 2021] vlist='martinsub.dyndns.org#8ddJlEQrz0-v6AZQmBKXsJsklzJIMWuaNKcrs7vKQs8.VUKaGqIG1j6NxNlBkQ0bmW02l7mJaAwZ6jSd9T-RtrQ#https://acme.zerossl.com/v2/DV90/chall/zbP7IygG2DlgdyTHjs7RWQ#http-01#apache,martinnav.dyndns.org#mwb0cLvwYBX9HzbV0y5IJHBFt5EWd5Szid4w2EXkgaQ.VUKaGqIG1j6NxNlBkQ0bmW02l7mJaAwZ6jSd9T-RtrQ#https://acme.zerossl.com/v2/DV90/chall/HeUj-GUqOO7FT_Ahy-mPcw#http-01#/Library/WebServer/Documents/,'
[Wed Oct 13 08:50:11 EDT 2021] d='martinsub.dyndns.org'
[Wed Oct 13 08:50:11 EDT 2021] d='martinnav.dyndns.org'
[Wed Oct 13 08:50:11 EDT 2021] ok, let's start to verify
[Wed Oct 13 08:50:11 EDT 2021] Verifying: martinsub.dyndns.org
[Wed Oct 13 08:50:11 EDT 2021] d='martinsub.dyndns.org'
[Wed Oct 13 08:50:11 EDT 2021] keyauthorization='8ddJlEQrz0-v6AZQmBKXsJsklzJIMWuaNKcrs7vKQs8.VUKaGqIG1j6NxNlBkQ0bmW02l7mJaAwZ6jSd9T-RtrQ'
[Wed Oct 13 08:50:11 EDT 2021] uri='https://acme.zerossl.com/v2/DV90/chall/zbP7IygG2DlgdyTHjs7RWQ'
[Wed Oct 13 08:50:11 EDT 2021] _currentRoot='apache'
[Wed Oct 13 08:50:11 EDT 2021] wellknown_path='/home/.acme'
[Wed Oct 13 08:50:11 EDT 2021] writing token:8ddJlEQrz0-v6AZQmBKXsJsklzJIMWuaNKcrs7vKQs8 to /home/.acme/8ddJlEQrz0-v6AZQmBKXsJsklzJIMWuaNKcrs7vKQs8
mkdir: /home/.acme: Operation not supported
.acme.sh/acme.sh: line 4717: /home/.acme/8ddJlEQrz0-v6AZQmBKXsJsklzJIMWuaNKcrs7vKQs8: No such file or directory
[Wed Oct 13 08:50:11 EDT 2021] martinsub.dyndns.org:Can not write token to file : /home/.acme/8ddJlEQrz0-v6AZQmBKXsJsklzJIMWuaNKcrs7vKQs8
[Wed Oct 13 08:50:11 EDT 2021] Skip for removelevel:
[Wed Oct 13 08:50:11 EDT 2021] pid
[Wed Oct 13 08:50:11 EDT 2021] Using config home:/var/root/acme
[Wed Oct 13 08:50:11 EDT 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Wed Oct 13 08:50:12 EDT 2021] httpdconfname='/private/etc/apache2/httpd.conf'
[Wed Oct 13 08:50:12 EDT 2021] httpdconf='/private/etc/apache2/httpd.conf'
[Wed Oct 13 08:50:12 EDT 2021] httpdconfname='httpd.conf'
[Wed Oct 13 08:50:12 EDT 2021] Restored: /private/etc/apache2/httpd.conf.
[Wed Oct 13 08:50:12 EDT 2021] Restored successfully.
[Wed Oct 13 08:50:12 EDT 2021] No need to restore nginx, skip.
[Wed Oct 13 08:50:12 EDT 2021] _clearupdns
[Wed Oct 13 08:50:12 EDT 2021] dns_entries
[Wed Oct 13 08:50:12 EDT 2021] skip dns.
[Wed Oct 13 08:50:12 EDT 2021] _on_issue_err
[Wed Oct 13 08:50:12 EDT 2021] Please add '--debug' or '--log' to check more details.
[Wed Oct 13 08:50:12 EDT 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Wed Oct 13 08:50:12 EDT 2021] url='https://acme.zerossl.com/v2/DV90/chall/zbP7IygG2DlgdyTHjs7RWQ'
[Wed Oct 13 08:50:12 EDT 2021] payload='{}'
[Wed Oct 13 08:50:12 EDT 2021] Retrying post
[Wed Oct 13 08:50:12 EDT 2021] POST
[Wed Oct 13 08:50:12 EDT 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/zbP7IygG2DlgdyTHjs7RWQ'
[Wed Oct 13 08:50:12 EDT 2021] _CURL='curl --silent --dump-header /var/root/acme/http.header  -L  -g '
[Wed Oct 13 08:50:13 EDT 2021] _ret='0'
[Wed Oct 13 08:50:13 EDT 2021] _hcode='0'
[Wed Oct 13 08:50:13 EDT 2021] code='200'
[Wed Oct 13 08:50:13 EDT 2021] url='https://acme.zerossl.com/v2/DV90/chall/HeUj-GUqOO7FT_Ahy-mPcw'
[Wed Oct 13 08:50:13 EDT 2021] payload='{}'
[Wed Oct 13 08:50:13 EDT 2021] Retrying post
[Wed Oct 13 08:50:13 EDT 2021] POST
[Wed Oct 13 08:50:13 EDT 2021] _post_url='https://acme.zerossl.com/v2/DV90/chall/HeUj-GUqOO7FT_Ahy-mPcw'
[Wed Oct 13 08:50:13 EDT 2021] _CURL='curl --silent --dump-header /var/root/acme/http.header  -L  -g '
[Wed Oct 13 08:50:13 EDT 2021] _ret='0'
[Wed Oct 13 08:50:13 EDT 2021] _hcode='0'
[Wed Oct 13 08:50:13 EDT 2021] code='200'
[Wed Oct 13 08:50:14 EDT 2021] Diagnosis versions: 
openssl:openssl
LibreSSL 2.8.3
apache:
Server version: Apache/2.4.41 (Unix)
Server built:   Jun  5 2020 23:42:06
Server's Module Magic Number: 20120211:88
Server loaded:  APR 1.5.2, APR-UTIL 1.5.4
Compiled using: APR 1.5.2, APR-UTIL 1.5.4
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_FLOCK_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/usr"
 -D SUEXEC_BIN="/usr/bin/suexec"
 -D DEFAULT_PIDLOG="/private/var/run/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="/private/etc/apache2/mime.types"
 -D SERVER_CONFIG_FILE="/private/etc/apache2/httpd.conf"
nginx:
nginx doesn't exist.
socat:
socat by Gerhard Rieger and contributors - see www.dest-unreach.org
socat version 1.7.4.1 on Jan 11 2021 18:23:10
   running on Darwin version Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64, release 19.6.0, machine x86_64
features:
  #define WITH_STDIO 1
  #define WITH_FDNUM 1
  #define WITH_FILE 1
  #define WITH_CREAT 1
  #define WITH_GOPEN 1
  #define WITH_TERMIOS 1
  #define WITH_PIPE 1
  #define WITH_UNIX 1
  #undef WITH_ABSTRACT_UNIXSOCKET
  #define WITH_IP4 1
  #define WITH_IP6 1
  #define WITH_RAWIP 1
  #define WITH_GENERICSOCKET 1
  #undef WITH_INTERFACE
  #define WITH_TCP 1
  #define WITH_UDP 1
  #define WITH_SCTP 1
  #define WITH_LISTEN 1
  #define WITH_SOCKS4 1
  #define WITH_SOCKS4A 1
  #undef WITH_VSOCK
  #define WITH_PROXY 1
  #define WITH_SYSTEM 1
  #define WITH_EXEC 1
  #define WITH_READLINE 1
  #undef WITH_TUN
  #define WITH_PTY 1
  #define WITH_OPENSSL 1
  #undef WITH_FIPS
  #undef WITH_LIBWRAP
  #define WITH_SYCLS 1
  #define WITH_FILAN 1
  #define WITH_RETRY 1
  #define WITH_MSGLEVEL 0 /*debug*/

**Comment by Neilpang** [comment]
don't use `--apache`.  just using `-w ....`  is enough
