### ISSUE TITLE
DNS alias mode - CNAME record question

### ISSUE THREAD

**Issue by mq2195** [acmesh-official/acme.sh#3773]
I am issuing certs:
host1.intranet.example.org
host2.intranet.example.org
...
hostN.intranet.example.org

And for each host I have to create CNAME record:
_acme-challenge.host1.intranet.example.org	IN	CNAME	_acme-challenge.aliasDomainForValidationOnly.com.
_acme-challenge.host2.intranet.example.org	IN	CNAME	_acme-challenge.aliasDomainForValidationOnly.com.
_acme-challenge.host3.intranet.example.org	IN	CNAME	_acme-challenge.aliasDomainForValidationOnly.com.
...

Is there a way to set one CNAME record for all hosts in a subdomain?

**Comment by anp135** [comment]
> Wildcard certificate is very impractical and insecure...

About insecure). When you got specific fqdn cert, in the same hour botnets comes to your fqdns with checks -).
LE and other CA cert logs monitored by botnets. The very easy to part of issue "dump dns zone" with monitoring CA logs with specific fqdn's cert requiests.
