### ISSUE TITLE
自动更新多个域名通配符证书到另外二台服务器的解决方案咨询

### ISSUE THREAD

**Issue by wuwentao** [acmesh-official/acme.sh#3774]
Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

### 背景情况说明：
1. 现有3个域名，分别为：
a.com
b.com
c.cn

2. 三台vps服务器：
都有这三个域名的nginx服务，分别是www/hk/xxx/yyy等，不同服务器做不同域名的www主服务器和xxx/yyy的子域名，组合有所不同。

3.证书： 
因此直接在其中一台服务器上用acme.sh申请签发了三个域名的通配符证书*.a.com/*.b.com/*.c.cn，因为没台服务器都是有这3个域名的web服务。

### 目前临时的解决方案：
已经手工把三个域名的通配符证书scp同步到了另外2台服务器中，并手工重启了nginx服务

### 期望解决的问题：
后面证书到期以后怎么处理自动更新更合适？
1. scp复制证书到另外的2台服务器，可以ssh key免密登录直接执行复制
2. 分别在另外2台服务器上ssh远程执行nginx服务重启任务
3. 重点就是证书更新并同步/重启服务的触发条件，目前不好确定，好像还得acme.sh的crontab来处理或触发更合适，因此想咨询一下，目前应该怎么处理跨服务器的自动更新更合理一点。

初次使用acme.sh，相关参数使用和复杂任务处理还不大熟悉，感谢！

**Comment by hd10180** [comment]
请问各位前辈，复制到其他主机的话，是不是只需要复制domain.key和fullchain.cer就可以了？我用的dns api生成的*.domain.com证书，用的nginx
