### ISSUE TITLE
在windows 7 系统中证书提示过期

### ISSUE THREAD

**Issue by crazyfd** [acmesh-official/acme.sh#3785]
生成的证书，在windows 7 系统中谷歌浏览器提示证书过期，mac，windows 10上面都是显示正常，这个要怎么处理

![image](https://user-images.githubusercontent.com/5456580/139181086-657586ed-d793-494a-9f70-d7322c854a2a.png)

https://test.edm.zaobang.com/

**Comment by Neilpang** [comment]
这是兼容性问题.
切换到zerossl:

https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA
