### ISSUE TITLE
Certs created with IP addresses against internal CA have flawed SAN

### ISSUE THREAD

**Issue by Jon1760** [acmesh-official/acme.sh#3792]
acme.sh 3.0.1
Running against an internal step-ca server

acme.sh --issue --days 5 -d 172.16.200.200 --nginx

Issues a cert, but despite the claim in https://github.com/acmesh-official/acme.sh/wiki/ipcert it appears that the CSR is created with a flaw:
            X509v3 Subject Alternative Name:
                DNS:172.16.200.200
            X509v3 Step Provisioner:
                Type: ACME
                Name: rc

Where the IP address is tagged as a FQDN in the SAN.  In contrast, using the same CA with a CSR created through other channels, I get things like:
            X509v3 Subject Alternative Name:
                DNS:fwcsva1.bo.example.com
                IP Address:192.168.9.1
            X509v3 Step Provisioner:
                Type: JWK
                Name: End Elements

I strongly suspect that this is why various browsers are reacting rather badly to the first cert.

**Comment by Neilpang** [comment]
Can you please give the full log with `--debug 2` and give me your CSR ?

**Comment by Jon1760** [comment]
`acme.sh --issue --days 5 -d 172.16.200.200 --nginx --debug 2 --force > acme.sh.debug.txt 2>&1`
[acme.sh.debug.txt](https://github.com/acmesh-official/acme.sh/files/7470272/acme.sh.debug.txt)

`-----BEGIN CERTIFICATE REQUEST-----
MIICijCCAXICAQAwGTEXMBUGA1UEAwwOMTcyLjE2LjIwMC4yMDAwggEiMA0GCSqG
SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDzI1oQXdRHXR3tEefr3elW6VSs/YlUEi2R
DCYfwcbyZX4wxOApvO90mR51YxCybp0awW5UV5+B/xiFN9iXr7h/XIXDeHpiAVxa
pOL/T8RWWkB95gndBcH80o1xctxwpRbPWgc5s5D8NaDnjlt2Hux0FKNjEfj+GlmI
4715ydBTUC3dhP6cWa50/bOy2adP5+v/Lo1m97V+e0jsHRghHU9O5Sas57K3cbVK
OK17l8eY5jWiQJxWvedEMN6QTsMf27boV2eIThcrgk3aAoClP82ZuK3puyTCR6R4
C0CgxNucsYmZXHl3IZkV0bIDeKbvlxLlxd4gurKS8v+cBDAp2NS7AgMBAAGgLDAq
BgkqhkiG9w0BCQ4xHTAbMBkGA1UdEQQSMBCCDjE3Mi4xNi4yMDAuMjAwMA0GCSqG
SIb3DQEBCwUAA4IBAQAB3xwIBIU+WLQ7lD9upw8ozFVGPAwqvokJ5IZXkWw0cBRh
GYCbFPLa1OPy1tpsM9124BMU/JlSDmneneG/Usn5NJHqgP1Mr+sOVzOyPgIvLuj0
mgOsoBM78yYrjzZ3j9+U3OLeBdk3PosYBTv9XuEO1RV3G9dIrvI9rNCjRpHnegY1
Ts4i9D++Aoslep4SJqHsfs/5UxNOEcKXwz8+axyVK0OQCS6hBJj8cwo/90uNUW8+
ah0CoqnNbGScx0bri7qaPflG9e6scwj4Larj08zXiNOsZDjaCmSSHjrZWToec0cn
qE1ENxrpxdBn4apTczR/dwepttd537KqVSXmUzI4
-----END CERTIFICATE REQUEST-----`

**Comment by Jon1760** [comment]
Not sure why that CSR wrapped funny.  Try this:
[172.16.200.200.csr.txt](https://github.com/acmesh-official/acme.sh/files/7470303/172.16.200.200.csr.txt)

**Comment by Neilpang** [comment]
sorry,  please try again with the `dev` branch.

```
acme.sh --upgrade -b dev
```

**Comment by SomeOne55468** [comment]
@Neilpang :
# acme.sh --issue -d $IP$ --webroot /var/www/_letsencrypt 
[Sun Nov  7 19:52:49 CET 2021] Using CA: https://acme.zerossl.com/v2/DV90
[Sun Nov  7 19:52:49 CET 2021] Single domain='$IP$'
[Sun Nov  7 19:52:49 CET 2021] Getting domain auth token for each domain
[Sun Nov  7 19:52:50 CET 2021] Create new order error. Le_OrderFinalize not found. {"type":"urn:ietf:params:acme:error:unsupportedIdentifier","status":400,"detail":"IPv4 and IPv6 identifier types are not yet supported"}
[Sun Nov  7 19:52:50 CET 2021] Please check log file for more details: /root/.acme.sh/acme.sh.log

**Comment by Neilpang** [comment]
```
IPv4 and IPv6 identifier types are not yet supported
```

**Comment by SomeOne55468** [comment]
@Neilpang Yeah, but on site i can get it! Just API not working?

**Comment by Jon1760** [comment]
> sorry, please try again with the `dev` branch.
> 
> ```
> acme.sh --upgrade -b dev
> ```

I can confirm that the CSR generated by the dev branch looks fine.  Alas, it turns out that the CA server code I'm using does not yet support IP Addresses in the SAN when doing ACME, even though it supports them fine when using other cert signing channels.  

Many thanks for getting acme.sh ready for the day when the CAs catch up with the changes in the RFCs.

**Comment by Jon1760** [comment]
I should have mentioned; I took the CSR as created by acme.sh and supplied it to my internal CA.  It was signed just fine with the IP Address in the SAN.   It's just that I can't do that using ACME yet due to limitation in support on the server side.
