### ISSUE TITLE
ZeroSSL  revoke does not revoke cert in ZeroSSL GUI

### ISSUE THREAD

**Issue by petrus9** [acmesh-official/acme.sh#3795]
Hello, 

Steps to reproduce
------------------

When I issue a ZeroSSL cert with acme.sh  on Debian 10  the cert shows up in the ZeroSSL webgui.    When I try to revoke it from the webgui it says I cannot do it from there and must use the acme.sh client.  

When I issue the the command `acme.sh  --revoke --domain  mydomain.com`  the cert gets revoked but it still shows up in the ZeroSSL webgui as "issued"  

I have also tried the following command with a different cert and the cert still shows up as "Issued"  in the ZeroSSL GUI

`acme.sh --revoke --server https://acme.zerossl.com/v2/DV90 -d mydomain.com`

Debug log
-----------------

```
acme.sh --revoke --domain mydomain.com --debug 2
```
acme.sh --revoke --domain mydomain.com --debug 2
[Fri Nov  5 15:59:08 UTC 2021] Lets find script dir.
[Fri Nov  5 15:59:08 UTC 2021] _SCRIPT_='/root/.acme.sh/acme.sh'
[Fri Nov  5 15:59:08 UTC 2021] _script='/root/.acme.sh/acme.sh'
[Fri Nov  5 15:59:08 UTC 2021] _script_home='/root/.acme.sh'
[Fri Nov  5 15:59:08 UTC 2021] Using config home:/root/.acme.sh
[Fri Nov  5 15:59:08 UTC 2021] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.1
[Fri Nov  5 15:59:08 UTC 2021] Running cmd: revoke
[Fri Nov  5 15:59:08 UTC 2021] Using config home:/root/.acme.sh
[Fri Nov  5 15:59:08 UTC 2021] default_acme_server
[Fri Nov  5 15:59:08 UTC 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Fri Nov  5 15:59:08 UTC 2021] _ACME_SERVER_HOST='acme.zerossl.com'
[Fri Nov  5 15:59:08 UTC 2021] _ACME_SERVER_PATH='v2/DV90'
[Fri Nov  5 15:59:08 UTC 2021] DOMAIN_PATH='/root/.acme.sh/energywithinsight.com                                                                             '
[Fri Nov  5 15:59:08 UTC 2021] Le_API='https://acme.zerossl.com/v2/DV90'
[Fri Nov  5 15:59:08 UTC 2021] Using config home:/root/.acme.sh
[Fri Nov  5 15:59:08 UTC 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Fri Nov  5 15:59:08 UTC 2021] _ACME_SERVER_HOST='acme.zerossl.com'
[Fri Nov  5 15:59:08 UTC 2021] _ACME_SERVER_PATH='v2/DV90'
[Fri Nov  5 15:59:08 UTC 2021] _init api for server: https://acme.zerossl.com/v2                                                                             /DV90
[Fri Nov  5 15:59:08 UTC 2021] Retrying GET
[Fri Nov  5 15:59:08 UTC 2021] GET
[Fri Nov  5 15:59:08 UTC 2021] url='https://acme.zerossl.com/v2/DV90'
[Fri Nov  5 15:59:08 UTC 2021] timeout=
[Fri Nov  5 15:59:08 UTC 2021] displayError='1'
[Fri Nov  5 15:59:08 UTC 2021] _CURL='curl --silent --dump-header /root/.acme.sh                                                                             /http.header  -L  --trace-ascii /tmp/tmp.gXWo58YUUY  -g '
[Fri Nov  5 15:59:08 UTC 2021] ret='0'
[Fri Nov  5 15:59:08 UTC 2021] _hcode='0'
[Fri Nov  5 15:59:08 UTC 2021] response='{
  "newNonce": "https://acme.zerossl.com/v2/DV90/newNonce",
  "newAccount": "https://acme.zerossl.com/v2/DV90/newAccount",
  "newOrder": "https://acme.zerossl.com/v2/DV90/newOrder",
  "revokeCert": "https://acme.zerossl.com/v2/DV90/revokeCert",
  "keyChange": "https://acme.zerossl.com/v2/DV90/keyChange",
  "meta": {
    "termsOfService": "https://secure.trust-provider.com/repository/docs/Legacy/                                                                             20201020_Certificate_Subscriber_Agreement_v_2_4_click.pdf",
    "website": "https://zerossl.com",
    "caaIdentities": ["sectigo.com", "trust-provider.com", "usertrust.com", "com                                                                             odoca.com", "comodo.com"],
    "externalAccountRequired": true
  }
}'
[Fri Nov  5 15:59:08 UTC 2021] ACME_KEY_CHANGE='https://acme.zerossl.com/v2/DV90                                                                             /keyChange'
[Fri Nov  5 15:59:08 UTC 2021] ACME_NEW_AUTHZ
[Fri Nov  5 15:59:08 UTC 2021] ACME_NEW_ORDER='https://acme.zerossl.com/v2/DV90/                                                                             newOrder'
[Fri Nov  5 15:59:08 UTC 2021] ACME_NEW_ACCOUNT='https://acme.zerossl.com/v2/DV9                                                                             0/newAccount'
[Fri Nov  5 15:59:08 UTC 2021] ACME_REVOKE_CERT='https://acme.zerossl.com/v2/DV9                                                                             0/revokeCert'
[Fri Nov  5 15:59:08 UTC 2021] ACME_AGREEMENT='https://secure.trust-provider.com                                                                             /repository/docs/Legacy/20201020_Certificate_Subscriber_Agreement_v_2_4_click.pd                                                                             f'
[Fri Nov  5 15:59:08 UTC 2021] ACME_NEW_NONCE='https://acme.zerossl.com/v2/DV90/                                                                             newNonce'
[Fri Nov  5 15:59:08 UTC 2021] i='2'
[Fri Nov  5 15:59:08 UTC 2021] j='36'
[Fri Nov  5 15:59:08 UTC 2021] _init api for server: https://acme.zerossl.com/v2                                                                             /DV90
[Fri Nov  5 15:59:08 UTC 2021] Try domain key first.
[Fri Nov  5 15:59:08 UTC 2021] url='https://acme.zerossl.com/v2/DV90/revokeCert'
[Fri Nov  5 15:59:08 UTC 2021] payload='{"certificate": "REMOVED","reason":0}'
[Fri Nov  5 15:59:08 UTC 2021] RSA key
[Fri Nov  5 15:59:08 UTC 2021] Get nonce with HEAD. ACME_NEW_NONCE='https://acme                                                                             .zerossl.com/v2/DV90/newNonce'
[Fri Nov  5 15:59:08 UTC 2021] Retrying post
[Fri Nov  5 15:59:08 UTC 2021] HEAD
[Fri Nov  5 15:59:08 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/newNo                                                                             nce'
[Fri Nov  5 15:59:08 UTC 2021] body
[Fri Nov  5 15:59:08 UTC 2021] _postContentType='application/jose+json'
[Fri Nov  5 15:59:08 UTC 2021] _CURL='curl --silent --dump-header /root/.acme.sh                                                                             /http.header  -L  --trace-ascii /tmp/tmp.u698Ap11sD  -g  -I  '
[Fri Nov  5 15:59:08 UTC 2021] _ret='0'
[Fri Nov  5 15:59:08 UTC 2021] _hcode='0'
[Fri Nov  5 15:59:08 UTC 2021] _headers='HTTP/2 200
server: nginx
date: Fri, 05 Nov 2021 15:59:08 GMT
content-type: application/octet-stream
replay-nonce: REMOVED
cache-control: max-age=-1
access-control-allow-origin: *
link: <https://acme.zerossl.com/v2/DV90>;rel="index"
strict-transport-security: max-age=15552000
'
[Fri Nov  5 15:59:08 UTC 2021] _CACHED_NONCE='REMOVED'
[Fri Nov  5 15:59:08 UTC 2021] nonce='REMOVED'
[Fri Nov  5 15:59:09 UTC 2021] Retrying post
[Fri Nov  5 15:59:09 UTC 2021] POST
[Fri Nov  5 15:59:09 UTC 2021] _post_url='https://acme.zerossl.com/v2/DV90/revok                                                                             eCert'
[Fri Nov  5 15:59:09 UTC 2021] body='{"protected": " REMOVED}'
[Fri Nov  5 15:59:09 UTC 2021] _postContentType='application/jose+json'
[Fri Nov  5 15:59:09 UTC 2021] Http already initialized.
[Fri Nov  5 15:59:09 UTC 2021] _CURL='curl --silent --dump-header /root/.acme.sh                                                                             /http.header  -L  --trace-ascii /tmp/tmp.u698Ap11sD  -g '
[Fri Nov  5 15:59:09 UTC 2021] _ret='0'
[Fri Nov  5 15:59:09 UTC 2021] _hcode='0'
[Fri Nov  5 15:59:09 UTC 2021] responseHeaders='HTTP/2 200
server: nginx
date: Fri, 05 Nov 2021 15:59:09 GMT
content-type: application/octet-stream
content-length: 0
replay-nonce: REMOVED
cache-control: max-age=-1
access-control-allow-origin: *
link: <https://acme.zerossl.com/v2/DV90>;rel="index"
strict-transport-security: max-age=15552000
'
[Fri Nov  5 15:59:09 UTC 2021] code='200'
[Fri Nov  5 15:59:09 UTC 2021] original
[Fri Nov  5 15:59:09 UTC 2021] response
[Fri Nov  5 15:59:09 UTC 2021] Revoke success.

**Comment by Neilpang** [comment]
you can contact zerossl support for the gui issues.
