### ISSUE TITLE
upper/lowercase with tr fails with busybox

### ISSUE THREAD

**Issue by pc-coholic** [acmesh-official/acme.sh#3806]
Steps to reproduce
------------------

Throughout the codebase, `_upper_case` and `_lower_case` are being used - for example when creating the CSR.

Unfortunately, e488220bfc7ebeef56a0406011fec17b9bd02e5d breaks the capitalization for systems using the busybox-provided `tr` like OpenWRT/Turris.

This is particularly bad, as `subjectAltName=dns:foobar.com` instead of `subjectAltName=DNS:foobar.com` will break the CSR:

```
[Fri Nov 12 00:06:52 CET 2021] _createcsr
[Fri Nov 12 00:06:52 CET 2021] Single domain='foobar.com'
Error Loading request extension section v3_req
3069863264:error:22075075:X509 V3 routines:v2i_GENERAL_NAME_ex:unsupported option:crypto/x509v3/v3_alt.c:552:name=dns
3069863264:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:crypto/x509v3/v3_conf.c:47:name=subjectAltName, value=dns:foobar.com
[Fri Nov 12 00:06:52 CET 2021] Create CSR error.
```

Debug log
-----------------

```
root@turris:~# echo foo | tr '[:lower:]' '[:upper:]'
fpp

root@turris:~# echo FOO | tr '[:upper:]' '[:lower:]'
FOO

root@turris:~# tr
BusyBox v1.30.1 () multi-call binary.

Usage: tr [-cds] STRING1 [STRING2]

Translate, squeeze, or delete characters from stdin, writing to stdout

	-c	Take complement of STRING1
	-d	Delete input characters coded STRING1
	-s	Squeeze multiple output characters of STRING2 into one character
```

**Comment by avengermsoft** [comment]
similar problem 

echo foo | tr '[:lower:]' '[:upper:]'
fpp

` tr
BusyBox v1.34.1 (2021-10-12 12:45:09 UTC) multi-call binary.

Usage: tr [-cds] STRING1 [STRING2]

Translate, squeeze, or delete characters from stdin, writing to stdout

        -c      Take complement of STRING1
        -d      Delete input characters coded STRING1
        -s      Squeeze multiple output characters of STRING2 into one character
`

**Comment by Neilpang** [comment]
```
~ # echo foo | tr '[:lower:]' '[:upper:]'
FOO
~ # tr
BusyBox v1.34.1 (2021-11-11 01:55:05 UTC) multi-call binary.

Usage: tr [-cds] STRING1 [STRING2]

Translate, squeeze, or delete characters from stdin, writing to stdout

        -c      Take complement of STRING1
        -d      Delete input characters coded STRING1
        -s      Squeeze multiple output characters of STRING2 into one character
```

**Comment by pc-coholic** [comment]
Oh well - seems like it hit a snakenest with this one ;-)

So contrary to my original statement, this is not purely a "doesn't work with busybox" - it is actually a compilation feature flag: https://git.busybox.net/busybox/tree/coreutils/tr.c#n28

I found [this comment on SE](https://unix.stackexchange.com/questions/136118/convert-all-text-from-uppercase-to-lowercase-and-vice-versa/136132#136132) which says something along the lines that there are at least three common `tr` available, all behaving slightly different.

One proposal was to use `echo foo | sed -e 'y/abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz/'` - but I don't even want to know on how many more systems this will break...

**Comment by Neilpang** [comment]
fixed.  try again:

```
acme.sh  --upgrade -b dev
```

**Comment by pc-coholic** [comment]
LGTM!

Thanks for the fix :-)

**Comment by avengermsoft** [comment]
All perfectly! Thanks for the quick fix.
