### ISSUE TITLE
An error occurred while renew (Can not init api for: https://acme-v02.api.letsencrypt.org/directory)

### ISSUE THREAD

**Issue by qingfengtaizi** [acmesh-official/acme.sh#3808]
acme.sh --renew --force --dns dns_ali -d webcsn.com -d *.webcsn.com -d *.smartwx.info  --debug 2
[Sat Nov 13 21:36:25 CST 2021] Lets find script dir.
[Sat Nov 13 21:36:25 CST 2021] _SCRIPT_='/root/.acme.sh/acme.sh'
[Sat Nov 13 21:36:25 CST 2021] _script='/root/.acme.sh/acme.sh'
[Sat Nov 13 21:36:25 CST 2021] _script_home='/root/.acme.sh'
[Sat Nov 13 21:36:25 CST 2021] Using config home:/root/.acme.sh
[Sat Nov 13 21:36:25 CST 2021] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.2
[Sat Nov 13 21:36:25 CST 2021] Running cmd: renew
[Sat Nov 13 21:36:25 CST 2021] Using config home:/root/.acme.sh
[Sat Nov 13 21:36:25 CST 2021] default_acme_server
[Sat Nov 13 21:36:25 CST 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Sat Nov 13 21:36:25 CST 2021] _ACME_SERVER_HOST='acme.zerossl.com'
[Sat Nov 13 21:36:25 CST 2021] _ACME_SERVER_PATH='v2/DV90'
[Sat Nov 13 21:36:25 CST 2021] DOMAIN_PATH='/root/.acme.sh/webcsn.com'
[Sat Nov 13 21:36:25 CST 2021] Renew: 'webcsn.com'
[Sat Nov 13 21:36:25 CST 2021] Le_API='https://acme-v02.api.letsencrypt.org/directory'
[Sat Nov 13 21:36:25 CST 2021] Using config home:/root/.acme.sh
[Sat Nov 13 21:36:25 CST 2021] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Sat Nov 13 21:36:25 CST 2021] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Sat Nov 13 21:36:25 CST 2021] _ACME_SERVER_PATH='directory'
[Sat Nov 13 21:36:25 CST 2021] _main_domain='webcsn.com'
[Sat Nov 13 21:36:25 CST 2021] _alt_domains='*.webcsn.com,smartwx.info,*.smartwx.info'
[Sat Nov 13 21:36:25 CST 2021] 'dns_ali' does not contain 'dns'
[Sat Nov 13 21:36:25 CST 2021] 'dns_ali' does not contain 'dns'
[Sat Nov 13 21:36:25 CST 2021] Le_NextRenewTime='1633848924'
[Sat Nov 13 21:36:25 CST 2021] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Sat Nov 13 21:36:25 CST 2021] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Sat Nov 13 21:36:25 CST 2021] Retrying GET
[Sat Nov 13 21:36:25 CST 2021] GET
[Sat Nov 13 21:36:25 CST 2021] url='https://acme-v02.api.letsencrypt.org/directory'
[Sat Nov 13 21:36:25 CST 2021] timeout=
[Sat Nov 13 21:36:25 CST 2021] displayError='1'
[Sat Nov 13 21:36:25 CST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.qisCWoU9uZ  -g '
[Sat Nov 13 21:36:26 CST 2021] Here is the curl dump log:
[Sat Nov 13 21:36:26 CST 2021] == Info: About to connect() to acme-v02.api.letsencrypt.org port 443 (#0)
== Info:   Trying 172.65.32.248... == Info: connected
== Info: Connected to acme-v02.api.letsencrypt.org (172.65.32.248) port 443 (#0)
== Info: Initializing NSS with certpath: sql:/etc/pki/nssdb
== Info:   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
== Info: Peer's certificate issuer is not recognized: 'CN=R3,O=Let's Encrypt,C=US'
== Info: NSS error -8179
== Info: Closing connection #0
== Info: Peer certificate cannot be authenticated with known CA certificates
[Sat Nov 13 21:36:26 CST 2021] ret='60'
[Sat Nov 13 21:36:26 CST 2021] _hcode='60'
[Sat Nov 13 21:36:28 CST 2021] Retrying GET
[Sat Nov 13 21:36:28 CST 2021] GET
[Sat Nov 13 21:36:28 CST 2021] url='https://acme-v02.api.letsencrypt.org/directory'
[Sat Nov 13 21:36:28 CST 2021] timeout=
[Sat Nov 13 21:36:28 CST 2021] displayError='1'
[Sat Nov 13 21:36:28 CST 2021] Http already initialized.
[Sat Nov 13 21:36:28 CST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.qisCWoU9uZ  -g '
[Sat Nov 13 21:36:28 CST 2021] Here is the curl dump log:
[Sat Nov 13 21:36:28 CST 2021] == Info: About to connect() to acme-v02.api.letsencrypt.org port 443 (#0)
== Info:   Trying 172.65.32.248... == Info: connected
== Info: Connected to acme-v02.api.letsencrypt.org (172.65.32.248) port 443 (#0)
== Info: Initializing NSS with certpath: sql:/etc/pki/nssdb
== Info:   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
== Info: Peer's certificate issuer is not recognized: 'CN=R3,O=Let's Encrypt,C=US'
== Info: NSS error -8179
== Info: Closing connection #0
== Info: Peer certificate cannot be authenticated with known CA certificates
[Sat Nov 13 21:36:28 CST 2021] ret='60'
[Sat Nov 13 21:36:28 CST 2021] _hcode='60'
[Sat Nov 13 21:36:30 CST 2021] Retrying GET
[Sat Nov 13 21:36:30 CST 2021] GET
[Sat Nov 13 21:36:30 CST 2021] url='https://acme-v02.api.letsencrypt.org/directory'
[Sat Nov 13 21:36:30 CST 2021] timeout=
[Sat Nov 13 21:36:30 CST 2021] displayError='1'
[Sat Nov 13 21:36:30 CST 2021] Http already initialized.
[Sat Nov 13 21:36:30 CST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.qisCWoU9uZ  -g '
[Sat Nov 13 21:36:32 CST 2021] Here is the curl dump log:
[Sat Nov 13 21:36:32 CST 2021] == Info: About to connect() to acme-v02.api.letsencrypt.org port 443 (#0)
== Info:   Trying 172.65.32.248... == Info: connected
== Info: Connected to acme-v02.api.letsencrypt.org (172.65.32.248) port 443 (#0)
== Info: Initializing NSS with certpath: sql:/etc/pki/nssdb
== Info:   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
== Info: Peer's certificate issuer is not recognized: 'CN=R3,O=Let's Encrypt,C=US'
== Info: NSS error -8179
== Info: Closing connection #0
== Info: Peer certificate cannot be authenticated with known CA certificates
[Sat Nov 13 21:36:32 CST 2021] ret='60'
[Sat Nov 13 21:36:32 CST 2021] _hcode='60'
[Sat Nov 13 21:36:34 CST 2021] Retrying GET
[Sat Nov 13 21:36:34 CST 2021] GET
[Sat Nov 13 21:36:34 CST 2021] url='https://acme-v02.api.letsencrypt.org/directory'
[Sat Nov 13 21:36:34 CST 2021] timeout=
[Sat Nov 13 21:36:34 CST 2021] displayError='1'
[Sat Nov 13 21:36:34 CST 2021] Http already initialized.
[Sat Nov 13 21:36:34 CST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.qisCWoU9uZ  -g '
[Sat Nov 13 21:36:35 CST 2021] Here is the curl dump log:
[Sat Nov 13 21:36:35 CST 2021] == Info: About to connect() to acme-v02.api.letsencrypt.org port 443 (#0)
== Info:   Trying 172.65.32.248... == Info: connected
== Info: Connected to acme-v02.api.letsencrypt.org (172.65.32.248) port 443 (#0)
== Info: Initializing NSS with certpath: sql:/etc/pki/nssdb
== Info:   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
== Info: Peer's certificate issuer is not recognized: 'CN=R3,O=Let's Encrypt,C=US'
== Info: NSS error -8179
== Info: Closing connection #0
== Info: Peer certificate cannot be authenticated with known CA certificates
[Sat Nov 13 21:36:35 CST 2021] ret='60'
[Sat Nov 13 21:36:35 CST 2021] _hcode='60'
[Sat Nov 13 21:36:37 CST 2021] Retrying GET
[Sat Nov 13 21:36:37 CST 2021] GET
[Sat Nov 13 21:36:37 CST 2021] url='https://acme-v02.api.letsencrypt.org/directory'
[Sat Nov 13 21:36:37 CST 2021] timeout=
[Sat Nov 13 21:36:37 CST 2021] displayError='1'
[Sat Nov 13 21:36:37 CST 2021] Http already initialized.
[Sat Nov 13 21:36:37 CST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.qisCWoU9uZ  -g '
[Sat Nov 13 21:36:40 CST 2021] Here is the curl dump log:
[Sat Nov 13 21:36:40 CST 2021] == Info: About to connect() to acme-v02.api.letsencrypt.org port 443 (#0)
== Info:   Trying 172.65.32.248... == Info: connected
== Info: Connected to acme-v02.api.letsencrypt.org (172.65.32.248) port 443 (#0)
== Info: Initializing NSS with certpath: sql:/etc/pki/nssdb
== Info:   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
== Info: Peer's certificate issuer is not recognized: 'CN=R3,O=Let's Encrypt,C=US'
== Info: NSS error -8179
== Info: Closing connection #0
== Info: Peer certificate cannot be authenticated with known CA certificates
[Sat Nov 13 21:36:40 CST 2021] ret='60'
[Sat Nov 13 21:36:40 CST 2021] _hcode='60'
[Sat Nov 13 21:36:42 CST 2021] Retrying GET
[Sat Nov 13 21:36:42 CST 2021] GET
[Sat Nov 13 21:36:42 CST 2021] url='https://acme-v02.api.letsencrypt.org/directory'
[Sat Nov 13 21:36:42 CST 2021] timeout=
[Sat Nov 13 21:36:42 CST 2021] displayError='1'
[Sat Nov 13 21:36:42 CST 2021] Http already initialized.
[Sat Nov 13 21:36:42 CST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.qisCWoU9uZ  -g '
[Sat Nov 13 21:36:45 CST 2021] Here is the curl dump log:
[Sat Nov 13 21:36:45 CST 2021] == Info: About to connect() to acme-v02.api.letsencrypt.org port 443 (#0)
== Info:   Trying 172.65.32.248... == Info: connected
== Info: Connected to acme-v02.api.letsencrypt.org (172.65.32.248) port 443 (#0)
== Info: Initializing NSS with certpath: sql:/etc/pki/nssdb
== Info:   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
== Info: Peer's certificate issuer is not recognized: 'CN=R3,O=Let's Encrypt,C=US'
== Info: NSS error -8179
== Info: Closing connection #0
== Info: Peer certificate cannot be authenticated with known CA certificates
[Sat Nov 13 21:36:45 CST 2021] ret='60'
[Sat Nov 13 21:36:45 CST 2021] _hcode='60'
[Sat Nov 13 21:36:47 CST 2021] Retrying GET
[Sat Nov 13 21:36:47 CST 2021] GET
[Sat Nov 13 21:36:47 CST 2021] url='https://acme-v02.api.letsencrypt.org/directory'
[Sat Nov 13 21:36:47 CST 2021] timeout=
[Sat Nov 13 21:36:47 CST 2021] displayError='1'
[Sat Nov 13 21:36:47 CST 2021] Http already initialized.
[Sat Nov 13 21:36:47 CST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.qisCWoU9uZ  -g '
[Sat Nov 13 21:36:48 CST 2021] Here is the curl dump log:
[Sat Nov 13 21:36:48 CST 2021] == Info: About to connect() to acme-v02.api.letsencrypt.org port 443 (#0)
== Info:   Trying 172.65.32.248... == Info: connected
== Info: Connected to acme-v02.api.letsencrypt.org (172.65.32.248) port 443 (#0)
== Info: Initializing NSS with certpath: sql:/etc/pki/nssdb
== Info:   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
== Info: Peer's certificate issuer is not recognized: 'CN=R3,O=Let's Encrypt,C=US'
== Info: NSS error -8179
== Info: Closing connection #0
== Info: Peer certificate cannot be authenticated with known CA certificates
[Sat Nov 13 21:36:48 CST 2021] ret='60'
[Sat Nov 13 21:36:48 CST 2021] _hcode='60'
[Sat Nov 13 21:36:50 CST 2021] Retrying GET
[Sat Nov 13 21:36:50 CST 2021] GET
[Sat Nov 13 21:36:50 CST 2021] url='https://acme-v02.api.letsencrypt.org/directory'
[Sat Nov 13 21:36:50 CST 2021] timeout=
[Sat Nov 13 21:36:50 CST 2021] displayError='1'
[Sat Nov 13 21:36:50 CST 2021] Http already initialized.
[Sat Nov 13 21:36:50 CST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.qisCWoU9uZ  -g '
[Sat Nov 13 21:36:52 CST 2021] Here is the curl dump log:
[Sat Nov 13 21:36:52 CST 2021] == Info: About to connect() to acme-v02.api.letsencrypt.org port 443 (#0)
== Info:   Trying 172.65.32.248... == Info: connected
== Info: Connected to acme-v02.api.letsencrypt.org (172.65.32.248) port 443 (#0)
== Info: Initializing NSS with certpath: sql:/etc/pki/nssdb
== Info:   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
== Info: Peer's certificate issuer is not recognized: 'CN=R3,O=Let's Encrypt,C=US'
== Info: NSS error -8179
== Info: Closing connection #0
== Info: Peer certificate cannot be authenticated with known CA certificates
[Sat Nov 13 21:36:52 CST 2021] ret='60'
[Sat Nov 13 21:36:52 CST 2021] _hcode='60'
[Sat Nov 13 21:36:54 CST 2021] Retrying GET
[Sat Nov 13 21:36:54 CST 2021] GET
[Sat Nov 13 21:36:54 CST 2021] url='https://acme-v02.api.letsencrypt.org/directory'
[Sat Nov 13 21:36:54 CST 2021] timeout=
[Sat Nov 13 21:36:54 CST 2021] displayError='0'
[Sat Nov 13 21:36:54 CST 2021] Http already initialized.
[Sat Nov 13 21:36:54 CST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.qisCWoU9uZ  -g '
[Sat Nov 13 21:36:55 CST 2021] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 60
[Sat Nov 13 21:36:55 CST 2021] Here is the curl dump log:
[Sat Nov 13 21:36:55 CST 2021] == Info: About to connect() to acme-v02.api.letsencrypt.org port 443 (#0)
== Info:   Trying 172.65.32.248... == Info: connected
== Info: Connected to acme-v02.api.letsencrypt.org (172.65.32.248) port 443 (#0)
== Info: Initializing NSS with certpath: sql:/etc/pki/nssdb
== Info:   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
== Info: Peer's certificate issuer is not recognized: 'CN=R3,O=Let's Encrypt,C=US'
== Info: NSS error -8179
== Info: Closing connection #0
== Info: Peer certificate cannot be authenticated with known CA certificates
[Sat Nov 13 21:36:55 CST 2021] ret='60'
[Sat Nov 13 21:36:55 CST 2021] _hcode='60'
'     ov 13 21:36:57 CST 2021] response='
[Sat Nov 13 21:36:57 CST 2021] Can not init api for: https://acme-v02.api.letsencrypt.org/directory.
[Sat Nov 13 21:36:57 CST 2021] Sleep 10 and retry.

**Comment by rr307** [comment]
try this: (CentOS)

yum update ca-certificates

**Comment by qingfengtaizi** [comment]
> try this: (CentOS)
> 
> yum update ca-certificates

yes. It worked. Thank you for reply.

**Comment by sknair123** [comment]
> yum update ca-certificates

what about ubuntu ?

**Comment by randomnt** [comment]
> 
apt-get update
apt-get install ca-certificates

**Comment by dongliangde** [comment]
> 

ok

**Comment by teaRRe** [comment]
就这么一句，我TM找了无数种方法，机器重装了N次，该死的ca-certificates
