### ISSUE TITLE
tr uppercase problem on OpenWRT

### ISSUE THREAD

**Issue by tranzitwww** [acmesh-official/acme.sh#3811]
acme.sh ver=3.0.2

I had a issue with this script on OpenWRT devices.
The tr syntax tr '[:lower:]' '[:upper:]' doesn't uppercase anything and openssl required to have "DNS: aaa.bbb.cc" and complains about "dns: aaa.bbb.cc".

This tr program is part of BusyBox and is very rudimentary
```
tr --help
BusyBox v1.23.2 (2016-01-02 05:45:02 CET) multi-call binary.
```

Solution:
I had to replace 
`tr '[:lower:]' '[:upper:]'`
with
`tr a-z A-Z`

Also check https://linuxhint.com/bash_tr_command/

Cheers!

**Comment by Neilpang** [comment]
same: https://github.com/acmesh-official/acme.sh/issues/3806

upgrade to latest version:

```
acme.sh ---upgrade
```

**Comment by tranzitwww** [comment]
Thanks!
