### ISSUE TITLE
Create CSR error.

### ISSUE THREAD

**Issue by qq20029988** [acmesh-official/acme.sh#3812]
环境：Openwrt X86，保留OPENWRT设置后更新了固件
再更新或者重新签发的时候提示Create CSR error.

使用过--renew-all  --renew ，百度谷歌了一下都没有什么解决

用的是阿里的AccessKey，上次更新是8月，再一直没动过设置。

root@OpenWrt:~/.acme.sh# ./acme.sh --issue --dns dns_ali -d myopenwrt.X86.com -f --debug 2
[Fri Nov 19 13:06:03 CST 2021] Lets find script dir.
[Fri Nov 19 13:06:03 CST 2021] _SCRIPT_='./acme.sh'
[Fri Nov 19 13:06:03 CST 2021] _script='/root/.acme.sh/acme.sh'
[Fri Nov 19 13:06:03 CST 2021] _script_home='/root/.acme.sh'
[Fri Nov 19 13:06:03 CST 2021] Using default home:/root/.acme.sh
[Fri Nov 19 13:06:03 CST 2021] Using config home:/root/.acme.sh
[Fri Nov 19 13:06:03 CST 2021] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.2
[Fri Nov 19 13:06:03 CST 2021] Running cmd: issue
[Fri Nov 19 13:06:03 CST 2021] _main_domain='myopenwrt.X86.com'
[Fri Nov 19 13:06:03 CST 2021] _alt_domains='no'
[Fri Nov 19 13:06:03 CST 2021] Using config home:/root/.acme.sh
[Fri Nov 19 13:06:03 CST 2021] default_acme_server
[Fri Nov 19 13:06:03 CST 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Fri Nov 19 13:06:03 CST 2021] _ACME_SERVER_HOST='acme.zerossl.com'
[Fri Nov 19 13:06:03 CST 2021] _ACME_SERVER_PATH='v2/DV90'
[Fri Nov 19 13:06:03 CST 2021] DOMAIN_PATH='/root/.acme.sh/myopenwrt.X86.com'
[Fri Nov 19 13:06:03 CST 2021] 'dns_ali' does not contain 'dns'
[Fri Nov 19 13:06:03 CST 2021] Le_NextRenewTime
[Fri Nov 19 13:06:03 CST 2021] Using ACME_DIRECTORY: https://acme.zerossl.com/v2/DV90
[Fri Nov 19 13:06:03 CST 2021] _init api for server: https://acme.zerossl.com/v2/DV90
[Fri Nov 19 13:06:03 CST 2021] Retrying GET
[Fri Nov 19 13:06:03 CST 2021] GET
[Fri Nov 19 13:06:03 CST 2021] url='https://acme.zerossl.com/v2/DV90'
[Fri Nov 19 13:06:03 CST 2021] timeout=
[Fri Nov 19 13:06:03 CST 2021] displayError='1'
[Fri Nov 19 13:06:04 CST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.hdKjaO '
[Fri Nov 19 13:06:05 CST 2021] ret='0'
[Fri Nov 19 13:06:05 CST 2021] _hcode='0'
[Fri Nov 19 13:06:05 CST 2021] response='{
  "newNonce": "https://acme.zerossl.com/v2/DV90/newNonce",
  "newAccount": "https://acme.zerossl.com/v2/DV90/newAccount",
  "newOrder": "https://acme.zerossl.com/v2/DV90/newOrder",
  "revokeCert": "https://acme.zerossl.com/v2/DV90/revokeCert",
  "keyChange": "https://acme.zerossl.com/v2/DV90/keyChange",
  "meta": {
    "termsOfService": "https://secure.trust-provider.com/repository/docs/Legacy/20201020_Certificate_Subscriber_Agreement_v_2_4_click.pdf",
    "website": "https://zerossl.com",
    "caaIdentities": ["sectigo.com", "trust-provider.com", "usertrust.com", "comodoca.com", "comodo.com"],
    "externalAccountRequired": true
  }
}'
[Fri Nov 19 13:06:05 CST 2021] ACME_KEY_CHANGE='https://acme.zerossl.com/v2/DV90/keyChange'
[Fri Nov 19 13:06:05 CST 2021] ACME_NEW_AUTHZ
[Fri Nov 19 13:06:05 CST 2021] ACME_NEW_ORDER='https://acme.zerossl.com/v2/DV90/newOrder'
[Fri Nov 19 13:06:05 CST 2021] ACME_NEW_ACCOUNT='https://acme.zerossl.com/v2/DV90/newAccount'
[Fri Nov 19 13:06:05 CST 2021] ACME_REVOKE_CERT='https://acme.zerossl.com/v2/DV90/revokeCert'
[Fri Nov 19 13:06:05 CST 2021] ACME_AGREEMENT='https://secure.trust-provider.com/repository/docs/Legacy/20201020_Certificate_Subscriber_Agreement_v_2_4_click.pdf'
[Fri Nov 19 13:06:05 CST 2021] ACME_NEW_NONCE='https://acme.zerossl.com/v2/DV90/newNonce'
[Fri Nov 19 13:06:05 CST 2021] Using CA: https://acme.zerossl.com/v2/DV90
[Fri Nov 19 13:06:05 CST 2021] _on_before_issue
[Fri Nov 19 13:06:05 CST 2021] _chk_main_domain='myopenwrt.X86.com'
[Fri Nov 19 13:06:05 CST 2021] _chk_alt_domains
[Fri Nov 19 13:06:05 CST 2021] 'dns_ali' does not contain 'no'
[Fri Nov 19 13:06:05 CST 2021] Le_LocalAddress
[Fri Nov 19 13:06:05 CST 2021] d='myopenwrt.X86.com'
[Fri Nov 19 13:06:05 CST 2021] Check for domain='myopenwrt.X86.com'
[Fri Nov 19 13:06:05 CST 2021] _currentRoot='dns_ali'
[Fri Nov 19 13:06:05 CST 2021] d
[Fri Nov 19 13:06:05 CST 2021] 'dns_ali' does not contain 'apache'
[Fri Nov 19 13:06:05 CST 2021] _saved_account_key_hash='oYN6TcNoj/0BQQmjzdFnwMzI4q1rXTooxudBafcMp+k='
[Fri Nov 19 13:06:06 CST 2021] _saved_account_key_hash is not changed, skip register account.
[Fri Nov 19 13:06:06 CST 2021] Read key length:2048
[Fri Nov 19 13:06:06 CST 2021] Creating domain key
[Fri Nov 19 13:06:06 CST 2021] Use DEFAULT_DOMAIN_KEY_LENGTH=2048
[Fri Nov 19 13:06:06 CST 2021] Using config home:/root/.acme.sh
[Fri Nov 19 13:06:06 CST 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Fri Nov 19 13:06:06 CST 2021] _ACME_SERVER_HOST='acme.zerossl.com'
[Fri Nov 19 13:06:06 CST 2021] _ACME_SERVER_PATH='v2/DV90'
[Fri Nov 19 13:06:06 CST 2021] _createkey for file:/root/.acme.sh/myopenwrt.X86.com/myopenwrt.X86.com.key
[Fri Nov 19 13:06:06 CST 2021] Use length 2048
[Fri Nov 19 13:06:06 CST 2021] Using RSA: 2048
[Fri Nov 19 13:06:07 CST 2021] The domain key is here: /root/.acme.sh/myopenwrt.X86.com/myopenwrt.X86.com.key
[Fri Nov 19 13:06:07 CST 2021] _createcsr
[Fri Nov 19 13:06:07 CST 2021] domain='myopenwrt.X86.com'
[Fri Nov 19 13:06:07 CST 2021] domainlist
[Fri Nov 19 13:06:07 CST 2021] csrkey='/root/.acme.sh/myopenwrt.X86.com/myopenwrt.X86.com.key'
[Fri Nov 19 13:06:07 CST 2021] csr='/root/.acme.sh/myopenwrt.X86.com/myopenwrt.X86.com.csr'
[Fri Nov 19 13:06:07 CST 2021] csrconf='/root/.acme.sh/myopenwrt.X86.com/myopenwrt.X86.com.csr.conf'
[Fri Nov 19 13:06:07 CST 2021] Single domain='myopenwrt.X86.com'
[Fri Nov 19 13:06:07 CST 2021] _is_idn_d='myopenwrt.X86.com'
[Fri Nov 19 13:06:07 CST 2021] _idn_temp
[Fri Nov 19 13:06:07 CST 2021] _is_idn_d='myopenwrt.X86.com'
[Fri Nov 19 13:06:07 CST 2021] _idn_temp
[Fri Nov 19 13:06:07 CST 2021] _csr_cn='myopenwrt.X86.com'
Error Loading request extension section v3_req
140703411288776:error:22075075:X509 V3 routines:v2i_GENERAL_NAME_ex:unsupported option:crypto/x509v3/v3_alt.c:552:name=dns
140703411288776:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:crypto/x509v3/v3_conf.c:47:name=subjectAltName, value=dns:myopenwrt.X86.com
[Fri Nov 19 13:06:07 CST 2021] Create CSR error.
[Fri Nov 19 13:06:07 CST 2021] pid
[Fri Nov 19 13:06:07 CST 2021] No need to restore nginx, skip.
[Fri Nov 19 13:06:07 CST 2021] _clearupdns
[Fri Nov 19 13:06:07 CST 2021] dns_entries
[Fri Nov 19 13:06:07 CST 2021] skip dns.
[Fri Nov 19 13:06:07 CST 2021] _on_issue_err
[Fri Nov 19 13:06:07 CST 2021] Please add '--debug' or '--log' to check more details.
[Fri Nov 19 13:06:07 CST 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Fri Nov 19 13:06:07 CST 2021] _chk_vlist
[Fri Nov 19 13:06:07 CST 2021] Diagnosis versions: 
openssl:openssl
OpenSSL 1.1.1l  24 Aug 2021
apache:
apache doesn't exist.
nginx:
nginx doesn't exist.
socat:
socat by Gerhard Rieger and contributors - see www.dest-unreach.org
socat version 1.7.3.4 on 1636737430
   running on Linux version #0 SMP Fri Nov 12 17:17:10 2021, release 5.4.158, machine x86_64
features:
  #define WITH_STDIO 1
  #define WITH_FDNUM 1
  #define WITH_FILE 1
  #define WITH_CREAT 1
  #define WITH_GOPEN 1
  #define WITH_TERMIOS 1
  #define WITH_PIPE 1
  #define WITH_UNIX 1
  #define WITH_ABSTRACT_UNIXSOCKET 1
  #define WITH_IP4 1
  #define WITH_IP6 1
  #define WITH_RAWIP 1
  #define WITH_GENERICSOCKET 1
  #define WITH_INTERFACE 1
  #define WITH_TCP 1
  #define WITH_UDP 1
  #define WITH_SCTP 1
  #define WITH_LISTEN 1
  #define WITH_SOCKS4 1
  #define WITH_SOCKS4A 1
  #define WITH_PROXY 1
  #define WITH_SYSTEM 1
  #define WITH_EXEC 1
  #undef WITH_READLINE
  #define WITH_TUN 1
  #define WITH_PTY 1
  #undef WITH_OPENSSL
  #undef WITH_FIPS
  #undef WITH_LIBWRAP
  #define WITH_SYCLS 1
  #define WITH_FILAN 1
  #define WITH_RETRY 1
  #define WITH_MSGLEVEL 0 /*debug*/
root@OpenWrt:~/.acme.sh#

**Comment by qq20029988** [comment]
不知道为什么上面都是删除线，为了隐私已经将自己的域名替换成：myopenwrt.x86.com


root@OpenWrt:~/.acme.sh# ./acme.sh --issue --dns dns_ali -d myopenwrt.X86.com -f --debug 2
[Fri Nov 19 13:06:03 CST 2021] Lets find script dir.
[Fri Nov 19 13:06:03 CST 2021] _SCRIPT_='./acme.sh'
[Fri Nov 19 13:06:03 CST 2021] _script='/root/.acme.sh/acme.sh'
[Fri Nov 19 13:06:03 CST 2021] _script_home='/root/.acme.sh'
[Fri Nov 19 13:06:03 CST 2021] Using default home:/root/.acme.sh
[Fri Nov 19 13:06:03 CST 2021] Using config home:/root/.acme.sh
[Fri Nov 19 13:06:03 CST 2021] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.2
[Fri Nov 19 13:06:03 CST 2021] Running cmd: issue
[Fri Nov 19 13:06:03 CST 2021] _main_domain='myopenwrt.X86.com'
[Fri Nov 19 13:06:03 CST 2021] _alt_domains='no'
[Fri Nov 19 13:06:03 CST 2021] Using config home:/root/.acme.sh
[Fri Nov 19 13:06:03 CST 2021] default_acme_server
[Fri Nov 19 13:06:03 CST 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Fri Nov 19 13:06:03 CST 2021] _ACME_SERVER_HOST='acme.zerossl.com'
[Fri Nov 19 13:06:03 CST 2021] _ACME_SERVER_PATH='v2/DV90'
[Fri Nov 19 13:06:03 CST 2021] DOMAIN_PATH='/root/.acme.sh/myopenwrt.X86.com'
[Fri Nov 19 13:06:03 CST 2021] 'dns_ali' does not contain 'dns'
[Fri Nov 19 13:06:03 CST 2021] Le_NextRenewTime
[Fri Nov 19 13:06:03 CST 2021] Using ACME_DIRECTORY: https://acme.zerossl.com/v2/DV90
[Fri Nov 19 13:06:03 CST 2021] _init api for server: https://acme.zerossl.com/v2/DV90
[Fri Nov 19 13:06:03 CST 2021] Retrying GET
[Fri Nov 19 13:06:03 CST 2021] GET
[Fri Nov 19 13:06:03 CST 2021] url='https://acme.zerossl.com/v2/DV90'
[Fri Nov 19 13:06:03 CST 2021] timeout=
[Fri Nov 19 13:06:03 CST 2021] displayError='1'
[Fri Nov 19 13:06:04 CST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.hdKjaO '
[Fri Nov 19 13:06:05 CST 2021] ret='0'
[Fri Nov 19 13:06:05 CST 2021] _hcode='0'
[Fri Nov 19 13:06:05 CST 2021] response='{
  "newNonce": "https://acme.zerossl.com/v2/DV90/newNonce",
  "newAccount": "https://acme.zerossl.com/v2/DV90/newAccount",
  "newOrder": "https://acme.zerossl.com/v2/DV90/newOrder",
  "revokeCert": "https://acme.zerossl.com/v2/DV90/revokeCert",
  "keyChange": "https://acme.zerossl.com/v2/DV90/keyChange",
  "meta": {
    "termsOfService": "https://secure.trust-provider.com/repository/docs/Legacy/20201020_Certificate_Subscriber_Agreement_v_2_4_click.pdf",
    "website": "https://zerossl.com",
    "caaIdentities": ["sectigo.com", "trust-provider.com", "usertrust.com", "comodoca.com", "comodo.com"],
    "externalAccountRequired": true
  }
}'
[Fri Nov 19 13:06:05 CST 2021] ACME_KEY_CHANGE='https://acme.zerossl.com/v2/DV90/keyChange'
[Fri Nov 19 13:06:05 CST 2021] ACME_NEW_AUTHZ
[Fri Nov 19 13:06:05 CST 2021] ACME_NEW_ORDER='https://acme.zerossl.com/v2/DV90/newOrder'
[Fri Nov 19 13:06:05 CST 2021] ACME_NEW_ACCOUNT='https://acme.zerossl.com/v2/DV90/newAccount'
[Fri Nov 19 13:06:05 CST 2021] ACME_REVOKE_CERT='https://acme.zerossl.com/v2/DV90/revokeCert'
[Fri Nov 19 13:06:05 CST 2021] ACME_AGREEMENT='https://secure.trust-provider.com/repository/docs/Legacy/20201020_Certificate_Subscriber_Agreement_v_2_4_click.pdf'
[Fri Nov 19 13:06:05 CST 2021] ACME_NEW_NONCE='https://acme.zerossl.com/v2/DV90/newNonce'
[Fri Nov 19 13:06:05 CST 2021] Using CA: https://acme.zerossl.com/v2/DV90
[Fri Nov 19 13:06:05 CST 2021] _on_before_issue
[Fri Nov 19 13:06:05 CST 2021] _chk_main_domain='myopenwrt.X86.com'
[Fri Nov 19 13:06:05 CST 2021] _chk_alt_domains
[Fri Nov 19 13:06:05 CST 2021] 'dns_ali' does not contain 'no'
[Fri Nov 19 13:06:05 CST 2021] Le_LocalAddress
[Fri Nov 19 13:06:05 CST 2021] d='myopenwrt.X86.com'
[Fri Nov 19 13:06:05 CST 2021] Check for domain='myopenwrt.X86.com'
[Fri Nov 19 13:06:05 CST 2021] _currentRoot='dns_ali'
[Fri Nov 19 13:06:05 CST 2021] d
[Fri Nov 19 13:06:05 CST 2021] 'dns_ali' does not contain 'apache'
[Fri Nov 19 13:06:05 CST 2021] _saved_account_key_hash='oYN6TcNoj/0BQQmjzdFnwMzI4q1rXTooxudBafcMp+k='
[Fri Nov 19 13:06:06 CST 2021] _saved_account_key_hash is not changed, skip register account.
[Fri Nov 19 13:06:06 CST 2021] Read key length:2048
[Fri Nov 19 13:06:06 CST 2021] Creating domain key
[Fri Nov 19 13:06:06 CST 2021] Use DEFAULT_DOMAIN_KEY_LENGTH=2048
[Fri Nov 19 13:06:06 CST 2021] Using config home:/root/.acme.sh
[Fri Nov 19 13:06:06 CST 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Fri Nov 19 13:06:06 CST 2021] _ACME_SERVER_HOST='acme.zerossl.com'
[Fri Nov 19 13:06:06 CST 2021] _ACME_SERVER_PATH='v2/DV90'
[Fri Nov 19 13:06:06 CST 2021] _createkey for file:/root/.acme.sh/myopenwrt.X86.com/myopenwrt.X86.com.key
[Fri Nov 19 13:06:06 CST 2021] Use length 2048
[Fri Nov 19 13:06:06 CST 2021] Using RSA: 2048
[Fri Nov 19 13:06:07 CST 2021] The domain key is here: /root/.acme.sh/myopenwrt.X86.com/myopenwrt.X86.com.key
[Fri Nov 19 13:06:07 CST 2021] _createcsr
[Fri Nov 19 13:06:07 CST 2021] domain='myopenwrt.X86.com'
[Fri Nov 19 13:06:07 CST 2021] domainlist
[Fri Nov 19 13:06:07 CST 2021] csrkey='/root/.acme.sh/myopenwrt.X86.com/myopenwrt.X86.com.key'
[Fri Nov 19 13:06:07 CST 2021] csr='/root/.acme.sh/myopenwrt.X86.com/myopenwrt.X86.com.csr'
[Fri Nov 19 13:06:07 CST 2021] csrconf='/root/.acme.sh/myopenwrt.X86.com/myopenwrt.X86.com.csr.conf'
[Fri Nov 19 13:06:07 CST 2021] Single domain='myopenwrt.X86.com'
[Fri Nov 19 13:06:07 CST 2021] _is_idn_d='myopenwrt.X86.com'
[Fri Nov 19 13:06:07 CST 2021] _idn_temp
[Fri Nov 19 13:06:07 CST 2021] _is_idn_d='myopenwrt.X86.com'
[Fri Nov 19 13:06:07 CST 2021] _idn_temp
[Fri Nov 19 13:06:07 CST 2021] _csr_cn='myopenwrt.X86.com'
Error Loading request extension section v3_req
140703411288776:error:22075075:X509 V3 routines:v2i_GENERAL_NAME_ex:unsupported option:crypto/x509v3/v3_alt.c:552:name=dns
140703411288776:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:crypto/x509v3/v3_conf.c:47:name=subjectAltName, value=dns:myopenwrt.X86.com
[Fri Nov 19 13:06:07 CST 2021] Create CSR error.
[Fri Nov 19 13:06:07 CST 2021] pid
[Fri Nov 19 13:06:07 CST 2021] No need to restore nginx, skip.
[Fri Nov 19 13:06:07 CST 2021] _clearupdns
[Fri Nov 19 13:06:07 CST 2021] dns_entries
[Fri Nov 19 13:06:07 CST 2021] skip dns.
[Fri Nov 19 13:06:07 CST 2021] _on_issue_err
[Fri Nov 19 13:06:07 CST 2021] Please add '--debug' or '--log' to check more details.
[Fri Nov 19 13:06:07 CST 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Fri Nov 19 13:06:07 CST 2021] _chk_vlist
[Fri Nov 19 13:06:07 CST 2021] Diagnosis versions: 
openssl:openssl
OpenSSL 1.1.1l  24 Aug 2021
apache:
apache doesn't exist.
nginx:
nginx doesn't exist.
socat:
socat by Gerhard Rieger and contributors - see www.dest-unreach.org
socat version 1.7.3.4 on 1636737430
   running on Linux version #0 SMP Fri Nov 12 17:17:10 2021, release 5.4.158, machine x86_64
features:
  #define WITH_STDIO 1
  #define WITH_FDNUM 1
  #define WITH_FILE 1
  #define WITH_CREAT 1
  #define WITH_GOPEN 1
  #define WITH_TERMIOS 1
  #define WITH_PIPE 1
  #define WITH_UNIX 1
  #define WITH_ABSTRACT_UNIXSOCKET 1
  #define WITH_IP4 1
  #define WITH_IP6 1
  #define WITH_RAWIP 1
  #define WITH_GENERICSOCKET 1
  #define WITH_INTERFACE 1
  #define WITH_TCP 1
  #define WITH_UDP 1
  #define WITH_SCTP 1
  #define WITH_LISTEN 1
  #define WITH_SOCKS4 1
  #define WITH_SOCKS4A 1
  #define WITH_PROXY 1
  #define WITH_SYSTEM 1
  #define WITH_EXEC 1
  #undef WITH_READLINE
  #define WITH_TUN 1
  #define WITH_PTY 1
  #undef WITH_OPENSSL
  #undef WITH_FIPS
  #undef WITH_LIBWRAP
  #define WITH_SYCLS 1
  #define WITH_FILAN 1
  #define WITH_RETRY 1
  #define WITH_MSGLEVEL 0 /*debug*/
root@OpenWrt:~/.acme.sh#

**Comment by Neilpang** [comment]
更新到最新版
acme.sh --upgrade

**Comment by qq20029988** [comment]
> 更新到最新版 acme.sh --upgrade
你好，就是最新版的出现这个问题，然后我又在google上搜索，
https://giters.com/acmesh-official/acme.sh/issues/3806

提示acme.sh  --upgrade -b dev，解决了
