### ISSUE TITLE
'' does not contain 'dns' 

### ISSUE THREAD

**Issue by iammeken** [acmesh-official/acme.sh#3816]
'' does not contain 'dns'

**Comment by dmitrydonskih** [comment]
Same behavior. By the way, possibly this is the reason why cert is successfully reissued, but reloadcmd does not get called?

#/root/acme.sh/acme.sh --home "/root/acme.sh" --force --debug 2 --renew --dns dns_nic -d some.domain.tld --dnssleep 200 --cron --reloadcmd "/root/.acme.sh/renew-hook.sh"
....
```
[Mon Nov 22 16:09:18 MSK 2021] Your cert is in: /etc/letsencrypt/cert/...
[Mon Nov 22 16:09:18 MSK 2021] Your cert key is in: /etc/letsencrypt/cert/...
[Mon Nov 22 16:09:18 MSK 2021] The intermediate CA cert is in: /etc/letsencrypt/cert/...
[Mon Nov 22 16:09:18 MSK 2021] And the full chain certs is there: /etc/letsencrypt/cert/...
[Mon Nov 22 16:09:18 MSK 2021] _on_issue_success
[Mon Nov 22 16:09:18 MSK 2021] 'dns_nic' does not contain 'dns'
[Mon Nov 22 16:09:18 MSK 2021] Return code: 0
[Mon Nov 22 16:09:18 MSK 2021] _error_level='2'
[Mon Nov 22 16:09:18 MSK 2021] _set_level='2'
[Mon Nov 22 16:09:18 MSK 2021] The NOTIFY_HOOK is empty, just return.

```

**Comment by ierye** [comment]
> Same behavior. By the way, possibly this is the reason why cert is successfully reissued, but reloadcmd does not get called?
> 
> #/root/acme.sh/acme.sh --home "/root/acme.sh" --force --debug 2 --renew --dns dns_nic -d some.domain.tld --dnssleep 200 --cron --reloadcmd "/root/.acme.sh/renew-hook.sh" ....
> 
> ```
> [Mon Nov 22 16:09:18 MSK 2021] Your cert is in: /etc/letsencrypt/cert/...
> [Mon Nov 22 16:09:18 MSK 2021] Your cert key is in: /etc/letsencrypt/cert/...
> [Mon Nov 22 16:09:18 MSK 2021] The intermediate CA cert is in: /etc/letsencrypt/cert/...
> [Mon Nov 22 16:09:18 MSK 2021] And the full chain certs is there: /etc/letsencrypt/cert/...
> [Mon Nov 22 16:09:18 MSK 2021] _on_issue_success
> [Mon Nov 22 16:09:18 MSK 2021] 'dns_nic' does not contain 'dns'
> [Mon Nov 22 16:09:18 MSK 2021] Return code: 0
> [Mon Nov 22 16:09:18 MSK 2021] _error_level='2'
> [Mon Nov 22 16:09:18 MSK 2021] _set_level='2'
> [Mon Nov 22 16:09:18 MSK 2021] The NOTIFY_HOOK is empty, just return.
> ```

`--reloadcmd` won't excute after `--renew`.
You should run `--issue ... --reloadcmd ...`, then the reloadcmd will get called when excute `--renew`.

**Comment by link89** [comment]
I have the same issue. In my case the reason is I have a `return 301` rule in my nginx config, which redirect the access to another domain.
