### ISSUE TITLE
SSL: couldn't get X509 subject!

### ISSUE THREAD

**Issue by arcasys** [acmesh-official/acme.sh#3824]
Steps to reproduce
------------------

Running
acme.sh --issue -w /var/www/letsencrypt -d backoffice-demo.arcasys.de --debug 4 --test 
finishes without error and creates the certificates  in the defined folder
Running in production (after deleting the staging certificates)
acme.sh --issue -w /var/www/letsencrypt -d backoffice-demo.arcasys.de --debug 4 
produces the following error

Note the line "== Info: SSL: couldn't get X509-subject!"  near the end.
The output from "Retrying GET" to the end will be repeated multiple times. No certificates are being created.

Debug log
-----------------

<pre>
[Mo 22. Nov 15:47:55 CET 2021] ACCOUNT_CONF_PATH='/root/.acme.sh/account.conf'
[Mo 22. Nov 15:47:55 CET 2021] OK
[Mo 22. Nov 15:47:55 CET 2021] 3:AUTO_UPGRADE='1'
[Mo 22. Nov 15:47:56 CET 2021] LE_WORKING_DIR='/root/.acme.sh'
[Mo 22. Nov 15:47:56 CET 2021] Running cmd: issue
[Mo 22. Nov 15:47:56 CET 2021] _main_domain='backoffice-demo.arcasys.de'
[Mo 22. Nov 15:47:56 CET 2021] _alt_domains='no'
[Mo 22. Nov 15:47:56 CET 2021] Using config home:/root/.acme.sh
[Mo 22. Nov 15:47:56 CET 2021] ACCOUNT_CONF_PATH='/root/.acme.sh/account.conf'
[Mo 22. Nov 15:47:56 CET 2021] default_acme_server
[Mo 22. Nov 15:47:56 CET 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Mo 22. Nov 15:47:56 CET 2021] _ACME_SERVER_HOST='acme.zerossl.com'
[Mo 22. Nov 15:47:56 CET 2021] _ACME_SERVER_PATH='v2/DV90'
[Mo 22. Nov 15:47:56 CET 2021] CA_CONF='/root/.acme.sh/ca/acme.zerossl.com/v2/DV90/ca.conf'
[Mo 22. Nov 15:47:56 CET 2021] DOMAIN_PATH='/etc/ssl/letsencrypt/backoffice-demo.arcasys.de'
[Mo 22. Nov 15:47:56 CET 2021] '/var/www/letsencrypt' does not contain 'dns'
[Mo 22. Nov 15:47:56 CET 2021] Using ACME_DIRECTORY: https://acme.zerossl.com/v2/DV90
[Mo 22. Nov 15:47:56 CET 2021] _init api for server: https://acme.zerossl.com/v2/DV90
[Mo 22. Nov 15:47:56 CET 2021] Retrying GET
[Mo 22. Nov 15:47:56 CET 2021] GET
[Mo 22. Nov 15:47:56 CET 2021] url='https://acme.zerossl.com/v2/DV90'
[Mo 22. Nov 15:47:56 CET 2021] timeout=
[Mo 22. Nov 15:47:56 CET 2021] displayError='1'
[Mo 22. Nov 15:47:56 CET 2021] curl exists=0
[Mo 22. Nov 15:47:56 CET 2021] mktemp exists=0
[Mo 22. Nov 15:47:56 CET 2021] wget exists=0
[Mo 22. Nov 15:47:56 CET 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.kEVvZdoKVg  -g '
[Mo 22. Nov 15:48:01 CET 2021] Here is the curl dump log:
[Mo 22. Nov 15:48:01 CET 2021] == Info: About to connect() to acme.zerossl.com port 443 (#0)
== Info:   Trying 91.199.212.80...
== Info: connected
== Info: Connected to acme.zerossl.com (91.199.212.80) port 443 (#0)
== Info: successfully set certificate verify locations:
== Info:   CAfile: none
  CApath: /etc/ssl/certs
== Info: SSLv3, TLS handshake, Client hello (1):
=> Send SSL data, 306 bytes (0x132)
0000: ......a..........\U...C....uI . .(.ds.....0.,.(.$.........k.j.9.
0040: 8.....2...*.&.......=.5................./.+.'.#.........g.@.3.2.
0080: ....E.D.1.-.).%.......<./...A............................acme.ze
00c0: rossl.com...........4.2.........................................
0100: ............ .....................................
== Info: SSLv3, TLS handshake, Server hello (2):
<= Recv SSL data, 93 bytes (0x5d)
0000: ...Y...M...{..p.e....bg~......z#..M?.j #....ss.\L......m'$7.....
0040: ".#.f.../....................
== Info: SSLv3, TLS handshake, CERT (11):
<= Recv SSL data, 4588 bytes (0x11ec)
0000: .........@0..<0..$.......:Mx..N..(....}..0...*.H........0..1.0..
0040: .U....GB1.0...U....Greater Manchester1.0...U....Salford1.0...U..
0080: ..Sectigo Limited1705..U....Sectigo RSA Domain Validation Secure
00c0:  Server CA0...210730000000Z..220828235959Z0.0.."0...*.H.........
0100: ....0.........:`.1.z0.r...n/..[`2.....V....;....3s.~.+....n.C.pM
0140: [....CR...*.....c-s,h...R.s.o.H............t'4.*........5,..:*.
0180: %.....F....!.....8S...S./".B_3=..........>Z.w.S..0...>..]......
01c0: .T...&..a.Q...<....S.:...+Z.7Dp..6....Gb..1...(.I.r0d....[.....
0200: G......7yI)&......... 0...0...U.#..0.....^.T...w.........a.0...U
0240: ......`YH.....K...+u....0.0...U...........0...U.......0.0...U.%.
0280: .0...+.........+.......0I..U. .B0@04..+.....1....0%0#..+........
02c0: .https://sectigo.com/CPS0...g.....0....+........x0v0O..+.....0..
0300: Chttp://crt.sectigo.com/SectigoRSADomainValidationSecureServerCA
0340: .crt0#..+.....0...http://ocsp.sectigo.com0..~..+.....y......n...
0380: j.h.v.F.U.u.. 0...i..}.,At..I.....p.mG...z...0.....G0E. W.....{.
03c0: .V,....B*Zf........T....!...!.g._........[..?..dM.y.......v.A.
0400: ..."FJ...:.B.^N1.....K.h..b......z...C.....G0E.!..|..b?.7.,*..,.
0440: ..."...B."c*...... =.r.........$...$8...@tf.%nlWm.M.v.)y...99!.V
0480: s.c.w..W}.`...M]&\%].....z.........G0E.!......7LB$_......}.4.O?.
04c0: .....>@.x. .[n..Q.....2.W&B..fr'...Br5..,..0I..U......?0=..acme.
0500: sectigo.com..acme.trust-provider.com..acme.zerossl.com0...*.H...
0540: ...........fD6@...24}.v..I..AN...;.....-.\..W.'.Rs.....C^5..ne).
0580: A|.x`..X0t4..,"..UA6..].m'..........]......<o%....P..Bn....=*..
05c0: A...@.F....N.....>.\.Rq..g...b...p.G.r-./T!.N]. ..,L...s..OW.>U.
0600: ..Z&r.d..&....%....rl.4..t..'M6.:.u.,?...........e..].sHU.e,....
0640: 6=...........0...0..........}[Q&.v...t...S..0...*.H........0..1.
0680: 0...U....US1.0...U....New Jersey1.0...U....Jersey City1.0...U...
06c0: .The USERTRUST Network1.0,..U...%USERTrust RSA Certification Aut
0700: hority0...181102000000Z..301231235959Z0..1.0...U....GB1.0...U...
0740: .Greater Manchester1.0...U....Salford1.0...U....Sectigo Limited1
0780: 705..U....Sectigo RSA Domain Validation Secure Server CA0.."0...
07c0: *.H.............0.........s3..< ....E..>..?.A.20..l.......-?.M..
0800: ...b...Hy...N..2%.....P?.L.@*.9......2A..&.#z. ... .<.Do.u..@.2
0840: .....#>....o]Q.j.i.O.ri...Lm.....~.......7x...4.V.X....d[.7...(h
0880: .V...\......$..0......z...B......J......@..o.BJd..0.....'Z..X...
08c0: ...c.oV...`4.t........._.........n0..j0...U.#..0...Sy.Z.+J.T....
0900: .....f.0...U........^.T...w.........a.0...U...........0...U.....
0940: ..0.......0...U.%..0...+.........+.......0...U. ..0.0...U. .0...
0980: g.....0P..U...I0G0E.C.A.?http://crl.usertrust.com/USERTrustRSACe
09c0: rtificationAuthority.crl0v..+........j0h0?..+.....0..3http://crt
0a00: .usertrust.com/USERTrustRSAAddTrustCA.crt0%..+.....0...http://oc
0a40: sp.usertrust.com0...*.H.............2.a..H.O..GM..x......o..p.R.
0a80: 13.WR.1.k..T...@.h...|....U....6...9Q.F......~I.*6...h9z..NVo.{;
0ac0: ......w...8..._~...FH.h......4.g.8f.^....(:.@'.rN).!<|....,.1D..
0b00: ....ihw|.....68.S9..4.......$7.#.x.....Gdb9"....."..fD$&..2.....
0b40: ..>/...F.c.......!.......&.....WBm..3.9...A8..X..[..}.x.......i.
0b80: &.....[.... ...E......7.).....8@.B....{...hb.......O..i..`.d*.1.
0bc0: ...:..&..{......8.Y6..t...^..d.....n..-.....X-..%d.^u.8..ZF..Q.
0c00: ....5k.j{......d.......Q....y...@..[..<.`*....B...F..i......rKGn
0c40: ...2(c.C..2>..K.#..)A+....-..9H<.Z....0...0..i.......9rD:.".Q..
0c80: l..15.0...*.H........0{1.0...U....GB1.0...U....Greater Mancheste
0cc0: r1.0...U....Salford1.0...U....Comodo CA Limited1!0...U....AAA Ce
0d00: rtificate Services0...190312000000Z..281231235959Z0..1.0...U....
0d40: US1.0...U....New Jersey1.0...U....Jersey City1.0...U....The USER
0d80: TRUST Network1.0,..U...%USERTrust RSA Certification Authority0..
0dc0: "0...*.H.............0..........e.6.......W.v..'.L.P.a.. M.-d...
0e00: ...=..........{7(.+G.9..:.._..}..cB.v..;+...o... ..>..t.....bd.
0e40: .....j."<......{......Q..gF.Q...T?.3.~l......Q.5..f.rg.!f...x..P
0e80: :......L....5.WZ....=.,..T....:M.L..\... =."4.~;hf.D..NFS.3`...
0ec0: S7.sC.2.S....tNi.k.`.......2...;Qx.g..=V...i....%&k3m.nG.sC.~..f
0f00: .)|2.cU.....T0....}7..]:l5\.A....I.......b..f.%.....?.9......L.|
0f40: .k..^....g.....[..L..[...s.#;-..5Ut.I.IX..6.Q...&}.M....C&..A_@
0f80: .DD...W..P.WT.>.tc/.Pe..XB.C.L..%GY.....&FJP....x..g...W...c..b.
0fc0: ._U..\.(..%9..+..L...?.R.../..........0..0...U.#..0......#>.....
1000: .)....0..0...U......Sy.Z.+J.T.........f.0...U...........0...U..
1040: .....0....0...U. ..0.0...U. .0C..U...<0:08.6.4.2http://crl.comod
1080: oca.com/AAACertificateServices.crl04..+........(0&0$..+.....0...
10c0: http://ocsp.comodoca.com0...*.H...............Q.t!=...'.3.......
1100: ^.."o.u..r........-..J~...or<C;.?...\.........{C..6|.....?......
1140: ....Cd~.....}}....B+..X....f.v..N.....M.2......q.[.A....".......
1180: .7..;..:..E.&u....?{w;....=....\9.?{..E..../].Y.O?Q..E.?.J...at#
11c0: ...Ps'DG.].*k.1....jL..jx...vr.........._.
== Info: SSLv3, TLS handshake, Server key exchange (12):
<= Recv SSL data, 333 bytes (0x14d)
0000: ...I...A.$.t....M.9bu..#*.&Oi>U..+.q.....9....+.$.K..f~.!.C.+.R.
0040: )7...V..s.....]BL.{.6#4@/...i6...Z.-...f0.vQ2.-....4..N...R;.~..
0080: ..W..~:<.......E..J}...Y2.u..JY..wy..#'.<.Q..4......fQ.uC...J.HQ
00c0: ....?._.q..=...e...s*.4....9.B-]..c.N.p5..nXI9.=........\ch.....
0100: .}...dP.$t0........K........2"f.{..Id.."...#%.?d).wC.)NN..@.!..q
0140: P.n0lL....<..
== Info: SSLv3, TLS handshake, Server finished (14):
<= Recv SSL data, 4 bytes (0x4)
0000: ....
== Info: SSLv3, TLS handshake, Client key exchange (16):
=> Send SSL data, 70 bytes (0x46)
0000: ...BA.,.`F...z...q....]2..?.9Qa.....Q.GH.P..'..*..F.../.a....,.U
0040: #.....
== Info: SSLv3, TLS change cipher, Client hello (1):
=> Send SSL data, 1 bytes (0x1)
0000: .
== Info: SSLv3, TLS handshake, Finished (20):
=> Send SSL data, 16 bytes (0x10)
0000: ....`O..U..W6Nmp
== Info: SSLv3, TLS change cipher, Client hello (1):
<= Recv SSL data, 1 bytes (0x1)
0000: .
== Info: SSLv3, TLS handshake, Finished (20):
<= Recv SSL data, 16 bytes (0x10)
0000: .......h......ks
== Info: SSL connection using ECDHE-RSA-AES128-GCM-SHA256
== Info: Server certificate:
<strong>== Info: SSL: couldn't get X509-subject!</strong>
== Info: Closing connection #0
== Info: SSLv3, TLS alert, Client hello (1):
=> Send SSL data, 2 bytes (0x2)
0000: ..
[Mo 22. Nov 15:48:01 CET 2021] ret='35'
[Mo 22. Nov 15:48:01 CET 2021] _hcode='35'
</pre>

**Comment by arcasys** [comment]
### Update

This error appears to be due to DEFAULT_CA being set to $CA_ZEROSSL which will not work and produce the error described above.

As  a workaround make the following change in the **acme.sh** procedure :
<pre>
#DEFAULT_CA=$CA_ZEROSSL
DEFAULT_CA=$CA_LETSENCRYPT_V2
</pre>

**Comment by Neilpang** [comment]
use  `--set-default-ca`
https://github.com/acmesh-official/acme.sh/wiki/Server

**Comment by shiny** [comment]
same problem.
And i can't visit letsencrypt server on a beijing server too
