### ISSUE TITLE
--staging/--test are ignored when also specifying --server

### ISSUE THREAD

**Issue by CTaeumel** [acmesh-official/acme.sh#3827]
We found a bug while trying to use acme.sh to generate Let's Encrypt Staging Certificates:

**Bug:**
When you pass --staging/--test **and** --server, the --server-argument takes precedence

Example:
acme.sh --issue --server letsencrypt --staging
Expected behavior: lets encrypt staging certificate
Real behavior: regular non-staging lets-encrypt certificate

Reason:

Line 7095 --> declares _server
Line 7465 --> [ "$_server" ] is true --> 7466 _selectServer
Line 7831 --> declares ACME_DIRECTORY
Line 2715/2716 --> ACME_DIRECTORY is never empty --> STAGE is never used

Possible fixes:
1. Remove --test/--staging and replace it in your help with a reference to server
2. Make it smart: When both arguments are passed, _selectServer tries to find the corresponding test server. If it doesn't find one, it exists with an error
3. Keep everything as it is but add a big warning when both things are passed that the server takes precedence and --staging is ignored when the server is not a test server

Honestly, I think option 2 is the most intuitive. If you want, I still have quite some time this weekend to create a pull request.

**Comment by Neilpang** [comment]
It was  by design.
Don't use the `--test` and `--server` at the same time.
