### ISSUE TITLE
如何在ZeroSSL控制台上看到自己的证书？

### ISSUE THREAD

**Issue by jearton** [acmesh-official/acme.sh#3829]
Steps to reproduce
------------------

我先执行了以下命令：
```bash
$ acme.sh --register-account --server zerossl --eab-kid ***** --eab-hmac-key **** --debug
```

然后签发了一个证书：

```bash
$ export Ali_Key="*******" && export Ali_Secret="******"
$ acme.sh --issue --dns dns_ali -d example.com -d *.example.com --ocsp
```

而且日志也显示签发成功了：
![image](https://user-images.githubusercontent.com/10370433/143772417-c020adf8-f226-498e-90d0-abec60f75dc6.png)

但是我去ZeroSSL控制台上并没有看到已经签发的证书，是哪里出错了呢？

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

**Comment by Neilpang** [comment]
只要是同一个邮箱账号下的 eab key,  就能自动看到.

你检查一下邮箱 和 eabkey

**Comment by jearton** [comment]
> key

我检查了邮箱和eabkey是一致的，还是没看到。是不是因为我的证书时之前签发过，后面再续签没法关联上吗？

我在这个目录下检查的：/root/.acme.sh/ca/acme.zerossl.com/v2/DV90，里面的CA_EMAIL，CA_EAB_KEY_ID，CA_EAB_HMAC_KEY，都和我的zerossl账号能对上。但是zerossl里就是没看到

![image](https://user-images.githubusercontent.com/10370433/143912168-1144dcdc-434b-4bc0-829e-73345bb52d55.png)
