### ISSUE TITLE
"The CSR's public key uses an unsupported key size or curve" when trying to issue ECDSA 521 cert

### ISSUE THREAD

**Issue by richardpowellus** [acmesh-official/acme.sh#3840]
Steps to reproduce
------------------

I'm simply trying to issue a pretty standard ec-521 cert using the ZeroSSL default CA:

./acme.sh --issue --dns dns_azure -d unifi.powellhouse.net -k ec-521 --debug

If I issue an RSA cert everything works fine.

Debug log
-----------------

file attached
[acme.sh.log](https://github.com/acmesh-official/acme.sh/files/7654101/acme.sh.log)

**Comment by richardpowellus** [comment]
I just tried again using -k ec-384 and it worked. I'm thinking maybe the issue is that ZeroSSL just doesn't support ec-521?

**Comment by Ressy66** [comment]
I don't beleive lets encrypt supports it yet either, so your thinking is likely the reason :)
