### ISSUE TITLE
ZeroSSL is terrible - Timeout: The CA is processing your order, please just wait.

### ISSUE THREAD

**Issue by edrozenberg** [acmesh-official/acme.sh#3842]
However much ZeroSSL paid Acme.sh to become the default cert server, it's not worth it.

ZeroSSL has been buying up sites and turning them into crap, such as https://www.sslforfree.com. They bought out this site and introduced fees for "premium" services such as issuing wildcard certs. Super Super Premium!

For now workaround is to switch to the better servers via:
`acme.sh --server letsencrypt rest-of-the-command-here`

**Comment by ShepardEG** [comment]
Thank you for this answer!

**Comment by Superjd10** [comment]
[According to the forums](https://community.letsencrypt.org/t/the-acme-sh-will-change-default-ca-to-zerossl-on-august-1st-2021/144052) you can change your default CA using this simple command:

`acme.sh --set-default-ca  --server  letsencrypt`

**Comment by lucapan** [comment]
Same problem here but we need to use zerossl and today it's not working anymore! Any suggestion?

**Comment by Neilpang** [comment]
you can change the default ca back to letsencrypt easily.
https://github.com/acmesh-official/acme.sh/wiki/Change-default-CA-to-ZeroSSL

**Comment by axl89** [comment]
We had a horrible experience with ZeroSSL; their API keep returning 504 every time we had to issue some certificates, even though we were on the premium plan.

The customer support experience was also "as good" as their API, unfortunately. They kept closing the issues even though they were still broken.

**Comment by mrez-ir** [comment]
In my case there was unremoved/remaining _acme-challange DNS records from previous requests. I removed them manually then it worked.

**Comment by matthewbloch** [comment]
> In my case there was unremoved/remaining _acme-challange DNS records from previous requests. I removed them manually then it worked.

Yes! The exact same happened to me - it feels like acme.sh ought to delete the record at a different point in the process, so it feels like an integration bug. As soon as I deleted the challenge manually, the request finished and I got my certificate. But I assume not everyone has the same experience.

**Comment by kocoler** [comment]
> > In my case there was unremoved/remaining _acme-challange DNS records from previous requests. I removed them manually then it worked.
> 
> Yes! The exact same happened to me - it feels like acme.sh ought to delete the record at a different point in the process, so it feels like an integration bug. As soon as I deleted the challenge manually, the request finished and I got my certificate. But I assume not everyone has the same experience.

Yeah, I am using HTTP-01 mode, and I found that acme.sh does not delete the old Token, and uses the previous Token every time, instead of refreshing or judging whether the previous Token has expired.

I'm here to remind anyone who encounters this problem later to check the Token at the same time, if HTTP-01 mode is being used.

**Comment by jampy** [comment]
> I'm here to remind anyone who encounters this problem later to check the Token at the same time, if HTTP-01 mode is being used.

@kocoler how can I check / invalidate the token?

**Comment by toddbu** [comment]
Like many others here, I became very frustrated with the ZeroSSL cert renewals timing out. I found this thread and a few others that suggested running `acme.sh --set-default-ca  --server  letsencrypt` but it didn't seem to work, even on a fresh installation of `acme.sh`. My script was still calling ZeroSSL. What I finally realized is that you can either set the default CA as described or you can pass `--server letsencrypt` **when issuing the cert**. The OP states this in his post but it didn't register in my little peabrain. So if you've tried setting the default CA and it's not working then try add the `--server letsencrypt` parameter at the time when you issue the cert. BTW, after this change my cert renewed on this first attempt

**Comment by gareththered** [comment]
Just in-case it helps someone...

I found that I was getting time-outs with ZeroSSL after I switched acme.sh to use it instead of Let's Encrypt.  It then dawned on me that I had a CAA record for the domain still pointing to Let's Encrypt.  After changing it to "sectigo.com", acme.sh enrolled straight away.

**Comment by CharlieR-o-o-t** [comment]
Oh, first message here is from 2021:) nothing changes with ZeroSSL. 
Have a lot of bad experience, is there any "premium" alternatives with the same price?

**Comment by Superjd10** [comment]
@CharlieR-o-o-t Use Letsencrypt, it's free.

`acme.sh --set-default-ca  --server  letsencrypt`

**Comment by CharlieR-o-o-t** [comment]
@Superjd10 thank you. 
Sorry for misunderstood, I'm not using acme.sh. Just tried to find feedback on ZeroSSL and have found this discussion:)
We use letsencrypt as "backup" ssl provider, but it can't cover our needs even with Business plan.

**Comment by webprofusion-chrisc** [comment]
@CharlieR-o-o-t you can also use Google Trust Services as an ACME certificate provider. They can probably cover your business needs. Digicert also offer commercial ACME services.

**Comment by psy0rz** [comment]
we also have trouble with zerossl this month:
```
[Wed Aug 28 11:43:45 UTC 2024] Pending, The CA is processing your order, please just wait. (521/3600)
```
i wonder if it ever completes.

**Comment by Gaibhne** [comment]
@psy0rz ignoring the horribleness of ZeroSSL, how did you manage to raise the max tries to 3600 ?

**Comment by psy0rz** [comment]
uuh i forgot , or maybe its fixed idk (also i use Traefik now for my newer servers, and that handle acme stuff internally)

**Comment by john-washington** [comment]
adding " -DNS sleep 200 -force" in the acme.sh command call is the trick that works for me
