### ISSUE TITLE
Switching issuer of actually deployed certs

### ISSUE THREAD

**Issue by acsfer** [acmesh-official/acme.sh#3857]
I know we can switch issuer (and set the default one) for NEW certs, but is it possible to switch the issuer of actually deployed certs so at the next renewal process, it will be deployed from the new issuer?

I have certs from LE and from ZeroSSL, and would like to switch them all to one or another.

Thanks 👍

**Comment by Neilpang** [comment]
No,  you have to manually issue the certs again with the new issuer.
