### ISSUE TITLE
Acme renew + revoke and (zerossl) expiry notifications

### ISSUE THREAD

**Issue by bago** [acmesh-official/acme.sh#3860]
We use acme.sh with default zerossl issuers since almost 3 months, so our certificates are being renewed and the previous ones are near to expiration. Zerossl flood us for the expiring certificates while we thought this is an expected condition to have older certs expiring when you renewed them and obtained new certs.

Should we use revoke to revoke the older certificates after they have been renewed? I can't find documentation about this, if this is expected and how this can be done only when we are sure the certificate have been successfully renewed.

Otherwise maybe those notifications are simply a bug in zerossl (since we have no option to stop receiving them) and I should report to them?

**Comment by Neilpang** [comment]
>> Should we use revoke to revoke the older certificates after they have been renewed? I

No, you don't have to revoke them.  they will expire later.


>>  I should report to them?

Yes.

**Comment by bago** [comment]
Thank you and sorry for the "false issue", then.

**Comment by Neilpang** [comment]
@Cap-JaTu   There is no way to "renew" a cert in the ACME protocol.

**Comment by Cap-JaTu** [comment]
Oh.
As Let's E won't send any emails about expiry, this fact isn't as clearly visible as in ZeroSSL. Also `acme.sh` command-line arguments for `--issue`and `--renew`will hide this fact very effectively.

Alternatively, ZeroSSL could easily interpret a request for a certificate based on a private key they already know and have issued certificate earlier, as a request for renewal. I guess they have a good reason for not to doing so. Instead flooding my mailbox with unwarranted expiry notifications is something they're happy with. Still, this is not something this project can address.

Thanks for explanation.

**Comment by porsager** [comment]
Even though it's not related to this project, it's very likely the main cause of the notifications appearing is when using ZeroSSL with achme.sh (due to re issue instead of renewal), so if anyone has found a way to avoid the notifications it'd be great if they would share it here.

**Comment by Cap-JaTu** [comment]
> if anyone has found a way to avoid the notifications it'd be great if they would share it here, as this issue also pops up in google searches.

Yes. Major annoyance.
I'd love to see any stakeholder taking action to reduce the unnecessary noise. There is enough noise in the World already.
