### ISSUE TITLE
[Documentation] acme.sh deamon

### ISSUE THREAD

**Issue by nbrugger-tgm** [acmesh-official/acme.sh#3864]
In the wiki the command 
```sh
docker run --rm  -itd  \
  -v "$(pwd)/out":/acme.sh  \
  --net=host \
  --name=acme.sh \
  -v /var/run/docker.sock:/var/run/docker.sock \
  neilpang/acme.sh daemon
```
is stated where deamon seems to be resolved to `acme.sh deamon` inside docker.

The problem i am having is: there is no documentation what the deamon command does. Also `./acme.sh --help` does not mentions this command.

If you point me to the source code location of 
1. the --help command
2. the deamon command

i could open a PR adding the regarding documentation

**Comment by Neilpang** [comment]
you can add the documentation here:
https://github.com/acmesh-official/acme.sh/wiki/deploy-to-docker-containers

**Comment by nbrugger-tgm** [comment]
To write documentation i would need code to read. I have no idea what it does, and no source to learn it from

**Comment by Neilpang** [comment]
`daemon` is not a command in acme.sh file, it's just an entry for docker file.

https://github.com/acmesh-official/acme.sh/blob/master/Dockerfile#L63
