### ISSUE TITLE
invalid domain

### ISSUE THREAD

**Issue by viponedream** [acmesh-official/acme.sh#3866]
invalid domain
export CF_Email="
export CF_Token="
export CF_Zone_ID=
export CF_Account_ID=

我已经把这四个值都导进了。
还是出现这个错误 invalid domain
还要改哪里呢

**Comment by daonghiemanhduc1** [comment]
same with me. 
I've been getting this error for the last 2 weeks and I don't understand why

**Comment by hylyq** [comment]
Just need 
export CF_Email=
export CF_Token=

https://dash.cloudflare.com/profile/api-tokens

Make sure you have the correct CF_Token.

**Comment by daonghiemanhduc** [comment]
> Just need export CF_Email= export CF_Token=
> 
> https://dash.cloudflare.com/profile/api-tokens
> 
> Make sure you have the correct CF_Token.

Impossible. like i said before i can still use this method and i've only had it for the last 2 weeks. i tried changing my cf token but it doesn't seem to work

**Comment by benzBrake** [comment]
是不是也是这个错误？
```
Register account Error: {
  "type": "urn:ietf:params:acme:error:invalidEmail",
  "detail": "Error creating new account :: invalid contact domain. Contact emails @example.com are forbidden",
  "status": 400
}
```

**Comment by Neilpang** [comment]
只需要导前两个值.
