### ISSUE TITLE
acme.sh does not work with smallstep (step-ca)

### ISSUE THREAD

**Issue by ddscentral** [acmesh-official/acme.sh#3870]
Cannot issue certificate for an internal IP address.

smallstep/step-ca installed using docker on Rocky Linux 8.5. Both server and client distro is the same.
I can provide smallstep configuration if required.

Last error reported by smallstep:
"error finalizing order: CSR names do not match identifiers exactly: CSR names = [172.16.8.133], Order names = []"
Not sure why "Order names" is empty and whether it should be empty.

Command used:
/root/.acme.sh/acme.sh --issue --days 365 -d 172.16.8.133 -w /var/www/html --server https://172.16.8.132:9000/acme/acme-provisioner/directory --ca-bundle /usr/local/share/root_ca.cer --debug 2

acme.sh Debug log 
[debug.log](https://github.com/acmesh-official/acme.sh/files/7810608/debug.log)

Smallstep debug log
[smallstep.log](https://github.com/acmesh-official/acme.sh/files/7810633/smallstep.log)

Not sure if the problem is with smallstep or acme.sh.
I will try another ACME client and update this post if it works.

**Comment by Neilpang** [comment]
can you please show me the csr in the domain folder: `~/.acme.sh/172.16.8.133/172.16.8.133.csr` ?

Thanks

**Comment by ddscentral** [comment]
OK.
[172.16.8.133.csr.txt](https://github.com/acmesh-official/acme.sh/files/7813029/172.16.8.133.csr.txt)

**Comment by Neilpang** [comment]
can you please show me the csr that is created by your modified certbot ?

**Comment by Neilpang** [comment]
It seems like a bug on the step-ca server end,  but I can fix it from the client end. but I need to check the csr created by certbot first.

**Comment by ddscentral** [comment]
Thanks for the fix. I will try getting a CSR from certbot.

**Comment by ddscentral** [comment]
CSR generated by Certbot.

[0000_csr-certbot.pem.txt](https://github.com/acmesh-official/acme.sh/files/7837509/0000_csr-certbot.pem.txt)

**Comment by Neilpang** [comment]
thanks,  the fix is merged into dev now. and will be in master soon.
Thanks
