### ISSUE TITLE
please distribute example systemd timer, document how to use it, and maybe ship a Makefile with install target?

### ISSUE THREAD

**Issue by sten0** [acmesh-official/acme.sh#3874]
Hi,

This is a reasonably easy newcomer/first issue:

1. Write and distribute an example systemd timer
2. Document how to use it, ideally for the following two cases:
    * Dedicated user managed by system-level systemd
    * Arbitrary user (with enable-linger) using the "--user" namespace
3. A Makefile with an install target might be nice to have.

I'm not sure how soon I'll be able to find free time to do this, but yes, I am willing to do the work if nobody else wants to.

Happy New Year!
Nicholas

**Comment by Neilpang** [comment]
here is an example:
https://github.com/acmesh-official/acme.sh/wiki/Using-systemd-units-instead-of-cron

**Comment by sten0** [comment]
For the record, are the contents of the wiki also © you, and are they also GPL-3+ ?

**Comment by Neilpang** [comment]
good question.  It was created by someone else,  not by me.  
Honestly,  I'm not sure if the license of the main project is also applied to its wiki pages.  Maybe someone else can answer you.

However, it's just an example code.
