### ISSUE TITLE
acme.sh -i -d 只记录了最后的证书安装任务？

### ISSUE THREAD

**Issue by ilamy** [acmesh-official/acme.sh#3878]
你好，我在某个服务器上有2个不同的应用Nginx和另外一个APP，我对2个不同的应用分别执行了证书安装，Nginx先执行，在初次执行的时候证书是生效了，但是自动更新后发现Nginx使用的证书没有更新，证书安装只更新了第二个APP的证书
安装命令形如：
`acme.sh -i -d *.domain.cn --key-file /etc/nginx/ssl/domain.cn.key --fullchain-file /etc/nginx/ssl/domain.cn.cer --reloadcmd "systemctl restart nginx"
`
我查看这个配置信息，发现也只记录了最后一个证书安装的信息
"/root/.acme.sh/*.domain.cn/*.domain.cn.conf"

**Comment by Neilpang** [comment]
`installcert` 只能记录一个
