### ISSUE TITLE
Infinity "Processing, The CA is processing your order, please just wait" when issuing wildcard cert

### ISSUE THREAD

**Issue by up9cloud** [acmesh-official/acme.sh#3880]
Well, because of this:

<img width="1155" alt="Screen Shot 2022-01-09 at 00 51 30" src="https://user-images.githubusercontent.com/8325632/148676202-2bbe788b-5094-4d3c-a09d-9dea4910d94f.png">

Should we change the default-ca back to letsencrypt?

Steps to reproduce
------------------

- issue a wildcard cert, e.q. `./acme.sh --issue --debug 2 --dns dns_cf -d *.3cm.app -d 3cm.app`

Debug log
-----------------

```txt
...
... (29/30) ...
...
```

more log: https://github.com/acmesh-official/acme.sh/issues/3809

**Comment by Neilpang** [comment]
I have explained thousands of times,  there is no limit to the certs count, including wildcard certs, at the ACME endpoint.

If the user is using ACME to issue certs from zerossl, there is no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit, no limit.

https://zerossl.com/letsencrypt-alternative/

The error "Processing, The CA is processing your order, please just wait" just means what it says.  The CA is busy at the moment.  you can try again later.
