### ISSUE TITLE
How do I reactivate an account

### ISSUE THREAD

**Issue by ytk929** [acmesh-official/acme.sh#3889]
Steps to reproduce
------------------
deactivate-account

Debug log
-----------------
[Fri 14 Jan 2022 11:05:37 AM CST] Create new order error. Le_OrderFinalize not found. {"type":"urn:ietf:params:acme:error:unauthorized","status":401,"detail":"The account has been deactivated"}

```
./acme.sh --deactivate-account
./acme.sh --issue --dns dns_ali -d example.com -d '*.example'
```

**Comment by ytk929** [comment]
https://acme.zerossl.com

**Comment by jerryc05** [comment]
the link is broken and I am not facing the same issue

**Comment by oscarcoghlan** [comment]
@jerryc05 @pijng Wondering if you were ever able to figure it out, I'm now facing the same issue.

**Comment by oscarcoghlan** [comment]
Thanks for the help. For anyone else, I ended up uninstalling acme.sh with acme.sh --uninstall, then deleted the .acme.sh folder, restarted the session, then registered a new account.
