### ISSUE TITLE
Problem after successful installation in other folder

### ISSUE THREAD

**Issue by JustHoldMyBack** [acmesh-official/acme.sh#3902]
Hi,

i've just cloned acmesh and installed it (according to [this](https://github.com/acmesh-official/acme.sh/wiki/How-to-install#4-advanced-installation)) with the following options:

./acme.sh
--install
--home /test/acme
--config-home /test/acme/data
--cert-home /test/acme/cert
--accountemail "myemail..."
--accountkey /test/acme/account.key
--accountconf /test/acme/account.conf
--useragent "this is my client"

The installation output:

> [Thu Jan 20 22:20:15 CET 2022] It is recommended to install socat first.
> [Thu Jan 20 22:20:15 CET 2022] We use socat for standalone server if you use standalone mode.
> [Thu Jan 20 22:20:15 CET 2022] If you don't use standalone mode, just ignore this warning.
> [Thu Jan 20 22:20:15 CET 2022] Installing to /test/acme
> [Thu Jan 20 22:20:16 CET 2022] Installed to /test/acme/acme.sh
> [Thu Jan 20 22:20:16 CET 2022] No profile is found, you will need to go into /test/acme to use acme.sh
> [Thu Jan 20 22:20:16 CET 2022] Installing cron job
> 53 0 * * * "/test/acme"/acme.sh --cron --home "/test/acme" --config-home "/test/acme/data" > /dev/null
> [Thu Jan 20 22:20:16 CET 2022] Good, bash is found, so change the shebang to use bash as preferred.
> [Thu Jan 20 22:20:17 CET 2022] OK

Then cd to /test/acme.
But when i try to just issue a cert with for example:

`./acme.sh --issue --dns -d example.com --yes-I-know-dns-manual-mode-enough-go-ahead-please`

i get output like:

> mkdir: cannot create directory ‘/home/master’: Permission denied
> touch: cannot touch '/home/master/.acme.sh/http.header': No such file or directory
> touch: cannot touch '/home/master/.acme.sh/example.com/example.conf': No such file or directory
> grep: /home/master/.acme.sh/example.com/example.com.conf: No such file or directory
> grep: /home/master/.acme.sh/example.com/example.com.conf: No such file or directory
> ./acme.sh: 2234: cannot create /home/master/.acme.sh/example.com/example.com.conf: Directory nonexistent
> ...

and the creation aborts ("master" is the username i use...).

I don't get it. The installation-directory is "/test/acme", the installation was successful and even the content of acme.sh.env

> export LE_WORKING_DIR="/test/acme"
> export LE_CONFIG_HOME="/test/acme/data"
> alias acme.sh="/test/acme/acme.sh --config-home '/test/acme/data'"

set it right!

Can anyone tell me where the problem is?

Thanks!

**Comment by Neilpang** [comment]
import the `acme.sh.env` to your current shell.

```
source  acme.sh.env
```
