### ISSUE TITLE
更新证书超时

### ISSUE THREAD

**Issue by c-y-q** [acmesh-official/acme.sh#3903]
当我执行更新证书时，执行acme.sh --cron -f  --debug 2，总是出现如下错误，，更新不成功

![image](https://user-images.githubusercontent.com/24750024/150466167-d2c3fc7f-b3e7-4740-a919-95412718aace.png)

**Comment by kettly1260** [comment]
不要用zerossl，切换回acme.sh --set-default-ca --server letsencryp

**Comment by c-y-q** [comment]
> 不要用zerossl，切换回acme.sh --set-default-ca --server letsencryp
当执行：acme.sh --set-default-ca --server letsencryp，报错同上；

当执行acme.sh --set-default-ca --server letsencrypt  --cron -f --debug 2，报错如下

![image](https://user-images.githubusercontent.com/24750024/150484738-06136357-a7be-4e7b-bffe-8ad582132ae2.png)

**Comment by Neilpang** [comment]
你发issue 的时候没看到模版里面的中文吗.
你这样不提供`--debug 2` 的完整内容,是没有人能帮你的.

**Comment by Wagnerxyz** [comment]
检查下 域名解析的ip和运行sh的机器ip是否相同？我是这个问题导致。
