### ISSUE TITLE
Unable to create wildcard certificate with ZeroSSL!

### ISSUE THREAD

**Issue by maplesky** [acmesh-official/acme.sh#3904]
```
https://github.com/acmesh-official/acme.sh
v3.0.2
```
Steps to reproduce
------------------
acme.sh \
--dns dns_he \
--issue \
--force \
--debug 2 \
--server zerossl \
--domain 'uevan.com,*.uevan.com' \
--use-wget \
--keylength ec-256

Repeat loop "Order status is processing, lets sleep and retry.", then "Sign failed, can not get Le_LinkCert, retry time limit."

Debug log
-----------------
```
download link: https://uevan.com/acme.log
```

**Comment by LuciferSam86** [comment]
FWIW I had always problems with ZeroSSL with wildcard certificates and DNS challenges.
If you don't have particular reasons to not switch to Let's Encrypt servers, use Let's Encrypt.
