### ISSUE TITLE
timeout 超时

### ISSUE THREAD

**Issue by ccboot80** [acmesh-official/acme.sh#3905]
[Sat Jan 22 23:26:41 CST 2022] Using CA: https://acme.zerossl.com/v2/DV90
[Sat Jan 22 23:26:41 CST 2022] Standalone mode.
[Sat Jan 22 23:26:41 CST 2022] Creating domain key
[Sat Jan 22 23:26:42 CST 2022] The domain key is here: /root/.acme.sh/eth0.pub/eth0.pub.key
[Sat Jan 22 23:26:42 CST 2022] Single domain='eth0.pub'
[Sat Jan 22 23:26:42 CST 2022] Getting domain auth token for each domain
[Sat Jan 22 23:27:00 CST 2022] Getting webroot for domain='eth0.pub'
[Sat Jan 22 23:27:00 CST 2022] Verifying: eth0.pub
[Sat Jan 22 23:27:00 CST 2022] Standalone mode server
[Sat Jan 22 23:27:08 CST 2022] Processing, The CA is processing your order, please just wait. (1/30)
[Sat Jan 22 23:27:15 CST 2022] Processing, The CA is processing your order, please just wait. (2/30)
[Sat Jan 22 23:27:23 CST 2022] Processing, The CA is processing your order, please just wait. (3/30)
[Sat Jan 22 23:27:31 CST 2022] Processing, The CA is processing your order, please just wait. (4/30)
[Sat Jan 22 23:27:40 CST 2022] Processing, The CA is processing your order, please just wait. (5/30)
[Sat Jan 22 23:27:49 CST 2022] Processing, The CA is processing your order, please just wait. (6/30)
[Sat Jan 22 23:27:59 CST 2022] Processing, The CA is processing your order, please just wait. (7/30)
[Sat Jan 22 23:28:09 CST 2022] Processing, The CA is processing your order, please just wait. (8/30)
[Sat Jan 22 23:28:19 CST 2022] Processing, The CA is processing your order, please just wait. (9/30)
[Sat Jan 22 23:28:29 CST 2022] Processing, The CA is processing your order, please just wait. (10/30)
[Sat Jan 22 23:28:39 CST 2022] Processing, The CA is processing your order, please just wait. (11/30)
[Sat Jan 22 23:28:50 CST 2022] Processing, The CA is processing your order, please just wait. (12/30)
[Sat Jan 22 23:29:05 CST 2022] Processing, The CA is processing your order, please just wait. (13/30)
[Sat Jan 22 23:29:09 CST 2022] Processing, The CA is processing your order, please just wait. (14/30)
[Sat Jan 22 23:29:17 CST 2022] Processing, The CA is processing your order, please just wait. (15/30)
[Sat Jan 22 23:29:26 CST 2022] Processing, The CA is processing your order, please just wait. (16/30)
[Sat Jan 22 23:29:37 CST 2022] Processing, The CA is processing your order, please just wait. (17/30)
[Sat Jan 22 23:29:41 CST 2022] Processing, The CA is processing your order, please just wait. (18/30)
[Sat Jan 22 23:29:52 CST 2022] Processing, The CA is processing your order, please just wait. (19/30)
[Sat Jan 22 23:29:58 CST 2022] Processing, The CA is processing your order, please just wait. (20/30)
[Sat Jan 22 23:30:04 CST 2022] Processing, The CA is processing your order, please just wait. (21/30)
[Sat Jan 22 23:30:10 CST 2022] Processing, The CA is processing your order, please just wait. (22/30)
[Sat Jan 22 23:30:17 CST 2022] Processing, The CA is processing your order, please just wait. (23/30)
[Sat Jan 22 23:30:20 CST 2022] Processing, The CA is processing your order, please just wait. (24/30)
[Sat Jan 22 23:30:27 CST 2022] Processing, The CA is processing your order, please just wait. (25/30)
[Sat Jan 22 23:30:34 CST 2022] Processing, The CA is processing your order, please just wait. (26/30)
[Sat Jan 22 23:30:40 CST 2022] Processing, The CA is processing your order, please just wait. (27/30)
[Sat Jan 22 23:30:48 CST 2022] Processing, The CA is processing your order, please just wait. (28/30)
[Sat Jan 22 23:30:56 CST 2022] Processing, The CA is processing your order, please just wait. (29/30)
**[Sat Jan 22 23:31:04 CST 2022] eth0.pub:Timeout
[Sat Jan 22 23:31:05 CST 2022] Please add '--debug' or '--log' to check more details.
[Sat Jan 22 23:31:05 CST 2022] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh**

---------------------------------------------------------------------------------------------------------------------------------------------------

[Sat Jan 22 23:37:05 CST 2022] code='200'
[Sat Jan 22 23:37:05 CST 2022] original='{"type":"http-01","url":"https://acme.zerossl.com/v2/DV90/chall/iHHcYqHzcgv5OoZDfmjWnw                                                                               ","status":"processing","token":"YJLL-6DISIZXTyVdP-6ezTzKF0gJbICB6KMh3omxuq8"}'
[Sat Jan 22 23:37:05 CST 2022] response='{"type":"http-01","url":"https://acme.zerossl.com/v2/DV90/chall/iHHcYqHzcgv5OoZDfmjWnw                                                                               ","status":"processing","token":"YJLL-6DISIZXTyVdP-6ezTzKF0gJbICB6KMh3omxuq8"}'
[Sat Jan 22 23:37:05 CST 2022] eth0.pub:Timeout
[Sat Jan 22 23:37:05 CST 2022] Skip for removelevel:
[Sat Jan 22 23:37:05 CST 2022] pid='8251'
2022/01/22 23:37:05 socat[8251] N socat_signal(): handling signal 15
2022/01/22 23:37:05 socat[8251] W exiting on signal 15
2022/01/22 23:37:05 socat[8251] N socat_signal(): finishing signal 15
2022/01/22 23:37:05 socat[8251] N exit(143)
[Sat Jan 22 23:37:05 CST 2022] No need to restore nginx, skip.
[Sat Jan 22 23:37:05 CST 2022] _clearupdns
[Sat Jan 22 23:37:05 CST 2022] dns_entries
[Sat Jan 22 23:37:05 CST 2022] skip dns.
[Sat Jan 22 23:37:05 CST 2022] _on_issue_err
[Sat Jan 22 23:37:05 CST 2022] Please add '--debug' or '--log' to check more details.
[Sat Jan 22 23:37:05 CST 2022] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Sat Jan 22 23:37:05 CST 2022] _chk_vlist='eth0.pub#YJLL-6DISIZXTyVdP-6ezTzKF0gJbICB6KMh3omxuq8.006uvo5soD1fbOJWGtuBFS8NCdIPlPC                                                                               LXkw9Dl61CW0#https://acme.zerossl.com/v2/DV90/chall/iHHcYqHzcgv5OoZDfmjWnw#http-01#no,'
[Sat Jan 22 23:37:05 CST 2022] start to deactivate authz
[Sat Jan 22 23:37:05 CST 2022] Trigger domain validation.
[Sat Jan 22 23:37:05 CST 2022] _t_url='https://acme.zerossl.com/v2/DV90/chall/iHHcYqHzcgv5OoZDfmjWnw'
[Sat Jan 22 23:37:05 CST 2022] _t_key_authz='YJLL-6DISIZXTyVdP-6ezTzKF0gJbICB6KMh3omxuq8.006uvo5soD1fbOJWGtuBFS8NCdIPlPCLXkw9Dl                                                                               61CW0'
[Sat Jan 22 23:37:05 CST 2022] _t_vtype
[Sat Jan 22 23:37:05 CST 2022] url='https://acme.zerossl.com/v2/DV90/chall/iHHcYqHzcgv5OoZDfmjWnw'
[Sat Jan 22 23:37:05 CST 2022] payload='{}'
[Sat Jan 22 23:37:05 CST 2022] Use cached jwk for file: /root/.acme.sh/ca/acme.zerossl.com/v2/DV90/account.key
[Sat Jan 22 23:37:05 CST 2022] Use _CACHED_NONCE='cVdWC94iesQpxRbIk6v2SRAqh8oVPWbaHodF7zQC4Q8'
[Sat Jan 22 23:37:05 CST 2022] nonce='cVdWC94iesQpxRbIk6v2SRAqh8oVPWbaHodF7zQC4Q8'
[Sat Jan 22 23:37:05 CST 2022] POST
[Sat Jan 22 23:37:05 CST 2022] _post_url='https://acme.zerossl.com/v2/DV90/chall/iHHcYqHzcgv5OoZDfmjWnw'
[Sat Jan 22 23:37:05 CST 2022] body='{"protected": "eyJub25jZSI6ICJjVmRXQzk0aWVzUXB4UmJJazZ2MlNSQXFoOG9WUFdiYUhvZEY3elFDNFE4Iiw                                                                               gInVybCI6ICJodHRwczovL2FjbWUuemVyb3NzbC5jb20vdjIvRFY5MC9jaGFsbC9pSEhjWXFIemNndjVPb1pEZm1qV253IiwgImFsZyI6ICJSUzI1NiIsICJraWQiOi                                                                               AiaHR0cHM6Ly9hY21lLnplcm9zc2wuY29tL3YyL0RWOTAvYWNjb3VudC9rcjYtanJGSm1pek1iVmJaWU50LW9BIn0", "payload": "e30", "signature": "omb                                                                               X_ssPvn6xuPfbGsuYnTvQY5XUnTbBQaOIqAhF0jAcwSgneQunp9QXob0ttyfdn_gk3LmUZX1ymgMbYjZuPj0uWi4kDfnubxvQDZj5o4KZZ6MIRY9yjcKLvO6cs3JvNE                                                                               v2zhSCbzzIRy-f2wdC4EcNXsv-dG1nRxWHhlgAb1uQUHhE4hPi6uzpzu6k2Auy8Yst7z1sX9DzQolPup5uPRqazQW3mru8EsWWecRwLRbN54mPWhZTMGQSs6haRN4L_                                                                               t2mRcer-sHJYvlkfioBl8KOZCKWfqc9znoEwrchPPxZqvbmA2IGD3HcWvB_zSKOsqTou4tO7u3ZQEWk0iyEBA"}'
[Sat Jan 22 23:37:05 CST 2022] _postContentType='application/jose+json'
[Sat Jan 22 23:37:05 CST 2022] Http already initialized.
[Sat Jan 22 23:37:05 CST 2022] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.gBMHEU                                                                               ba29  -g '
[Sat Jan 22 23:37:08 CST 2022] _ret='0'
[Sat Jan 22 23:37:08 CST 2022] responseHeaders='HTTP/1.1 200 OK
Server: nginx
Date: Sat, 22 Jan 2022 15:37:08 GMT
Content-Type: application/json
Content-Length: 164
Connection: keep-alive
Replay-Nonce: LS8uu32Q3lYbd9w9sWtnbrKDbqFQTfyEZ4i3ugoRF5U
Cache-Control: max-age=-1
Access-Control-Allow-Origin: *
Link: <https://acme.zerossl.com/v2/DV90>;rel="index"
Link: <https://acme.zerossl.com/v2/DV90/authz/TuNIcD-xjyfytTsfJE58FQ>;rel="up"
Retry-After: 10
Strict-Transport-Security: max-age=15552000
'
[Sat Jan 22 23:37:08 CST 2022] code='200'
[Sat Jan 22 23:37:08 CST 2022] original='{"type":"http-01","url":"https://acme.zerossl.com/v2/DV90/chall/iHHcYqHzcgv5OoZDfmjWnw                                                                               ","status":"processing","token":"YJLL-6DISIZXTyVdP-6ezTzKF0gJbICB6KMh3omxuq8"}'
[Sat Jan 22 23:37:08 CST 2022] response='{"type":"http-01","url":"https://acme.zerossl.com/v2/DV90/chall/iHHcYqHzcgv5OoZDfmjWnw                                                                               ","status":"processing","token":"YJLL-6DISIZXTyVdP-6ezTzKF0gJbICB6KMh3omxuq8"}'
[Sat Jan 22 23:37:08 CST 2022] Diagnosis versions:
openssl:openssl
OpenSSL 1.0.2k-fips  26 Jan 2017
apache:
apache doesn't exist.
nginx:
nginx version: nginx/1.20.1
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
built with OpenSSL 1.1.1g FIPS  21 Apr 2020 (running with OpenSSL 1.1.1k  FIPS 25 Mar 2021)
TLS SNI support enabled
configure arguments: --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=                                                                               /etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-te                                                                               mp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/                                                                               tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --pid-path=/run/nginx                                                                               .pid --lock-path=/run/lock/subsys/nginx --user=nginx --group=nginx --with-compat --with-debug --with-file-aio --with-google_per                                                                               ftools_module --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_degradation_module                                                                                --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with                                                                               -http_mp4_module --with-http_perl_module=dynamic --with-http_random_index_module --with-http_realip_module --with-http_secure_l                                                                               ink_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2                                                                               _module --with-http_xslt_module=dynamic --with-mail=dynamic --with-mail_ssl_module --with-pcre --with-pcre-jit --with-stream=dy                                                                               namic --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY                                                                               _SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redh                                                                               at-hardened-cc1 -m64 -mtune=generic' --with-ld-opt='-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-E'
socat:
socat by Gerhard Rieger and contributors - see www.dest-unreach.org
socat version 1.7.3.2 on Aug  4 2017 04:57:10
   running on Linux version #1 SMP Fri Jan 14 13:59:45 UTC 2022, release 3.10.0-1160.53.1.el7.x86_64, machine x86_64
features:
  #define WITH_STDIO 1
  #define WITH_FDNUM 1
  #define WITH_FILE 1
  #define WITH_CREAT 1
  #define WITH_GOPEN 1
  #define WITH_TERMIOS 1
  #define WITH_PIPE 1
  #define WITH_UNIX 1
  #define WITH_ABSTRACT_UNIXSOCKET 1
  #define WITH_IP4 1
  #define WITH_IP6 1
  #define WITH_RAWIP 1
  #define WITH_GENERICSOCKET 1
  #define WITH_INTERFACE 1
  #define WITH_TCP 1
  #define WITH_UDP 1
  #define WITH_SCTP 1
  #define WITH_LISTEN 1
  #define WITH_SOCKS4 1
  #define WITH_SOCKS4A 1
  #define WITH_PROXY 1
  #define WITH_SYSTEM 1
  #define WITH_EXEC 1
  #define WITH_READLINE 1
  #define WITH_TUN 1
  #define WITH_PTY 1
  #define WITH_OPENSSL 1
  #undef WITH_FIPS
  #define WITH_LIBWRAP 1
  #define WITH_SYCLS 1
  #define WITH_FILAN 1
  #define WITH_RETRY 1
  #define WITH_MSGLEVEL 0 /*debug*/

**Comment by dguenther677** [comment]
i had the same timeout problem, but for just the main domain, all subdomains could be verified without any problems.
it was because i had set a redirect to the ssl protocol in the virtual host for the domains on port 80. 
after i disabled this permanent redirect for a short time, the verification worked. after that i could enable the ssl redirect again.

**Comment by Wagnerxyz** [comment]
检查下 域名解析的ip和运行sh的机器ip是否相同？我是这个问题导致。

**Comment by nicbou** [comment]
As @dguenther677,  the issue only happens with one of two domains. Same description as #3882
