### ISSUE TITLE
acme.sh command not found 

### ISSUE THREAD

**Issue by Leetroch** [acmesh-official/acme.sh#3907]
我在我的VPS上分别用CENTOS 7和 ubuntu 18.04 系统装了2次acme.sh，但都无法运行，今天我再从ubuntu 18.04上安装，使用的方式是用**apt install -y curl**后输入curl https://get.acme.sh | sh后还是command not found,   此外我使用过source ~/.bashrc和 ~/.acme.sh/acme.sh * 命令，但还是没用，我不知道怎么办了。请求教QAQ。

I installed acme.sh twice on my VPS with CENTOS 7 and ubuntu 18.04, but they couldn't run. Today I  installed it again from ubuntu 18.04, using **apt install -y curl** After adding curl https://get.acme.sh | sh, but it didn't work. in addition, I used source ~/.bashrc **and** ~/.acme.sh/acme.sh * command, but acme.sh still not found , I don't know what to do,help me, please.

**[root /]# apt install -y curl**
Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version (7.58.0-2ubuntu3.16).
0 upgraded, 0 newly installed, 0 to remove and 163 not upgraded.
==========================[STDERR]==========================
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
===========================[END]============================

**[root /]# curl https://get.acme.sh | sh**
[Tue Jan 25 04:20:49 EST 2022] Installing from online archive.
[Tue Jan 25 04:20:49 EST 2022] Downloading https://github.com/acmesh-official/acme.sh/archive/master.tar.gz
[Tue Jan 25 04:20:50 EST 2022] Extracting master.tar.gz
[Tue Jan 25 04:20:50 EST 2022] Installing to /.acme.sh
[Tue Jan 25 04:20:50 EST 2022] Installed to /.acme.sh/acme.sh
[Tue Jan 25 04:20:50 EST 2022] No profile is found, you will need to go into /.acme.sh to use acme.sh
[Tue Jan 25 04:20:50 EST 2022] Installing cron job
40 0 * * * "/.acme.sh"/acme.sh --cron --home "/.acme.sh" > /dev/null
[Tue Jan 25 04:20:50 EST 2022] Good, bash is found, so change the shebang to use bash as preferred.
[Tue Jan 25 04:20:50 EST 2022] OK
[Tue Jan 25 04:20:50 EST 2022] Install success!
==========================[STDERR]==========================
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   937    0   937    0     0   5511      0 --:--:-- --:--:-- --:--:--  5511
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 40  205k   40 84250    0     0  65158      0  0:00:03  0:00:01  0:00:02 65108
100  205k  100  205k    0     0   131k      0  0:00:01  0:00:01 --:--:--  131k
[Tue Jan 25 04:20:50 EST 2022] It is recommended to install socat first.
[Tue Jan 25 04:20:50 EST 2022] We use socat for standalone server if you use standalone mode.
[Tue Jan 25 04:20:50 EST 2022] If you don't use standalone mode, just ignore this warning.
===========================[END]============================

**[root /]# crontab -l**
40 0 * * * "/.acme.sh"/acme.sh --cron --home "/.acme.sh" > /dev/null

**[root /]# ~/.acme.sh/acme.sh  --upgrade  --auto-upgrade**
==========================[STDERR]==========================
bash: line 1: /root/.acme.sh/acme.sh: No such file or directory
===========================[END]============================

Exit code: 127
**[root /]# acme.sh --issue --dns dns_cf -d www.mutecn.tk**
==========================[STDERR]==========================
bash: line 1: acme.sh: command not found
===========================[END]============================

Exit code: 127
**[root /]# acme.sh --issue --dns dns_cf -d www.mutecn.tk --debug**
==========================[STDERR]==========================
bash: line 1: acme.sh: command not found

**Comment by maplesky** [comment]
要是 ssh 环境的话，安装完把 SSH 客户端关闭后重新打开一次。

**Comment by Leetroch** [comment]
> 要是 ssh 环境的话，安装完把 SSH 客户端关闭后重新打开一次。

我用的是KiwiVM的 basic shell，我用./ acme.sh解决问题，最基本执行脚本的方法，但每次要先用CD命令找路径。QAQ

**Comment by mcdullmedia** [comment]
I have the same question.
Noted the acme was installed under /
"Installing to /.acme.sh/acme.sh"
But most scripts are calling from home, i.e.
"# ~/.acme.sh/acme.sh"

How to properly address the issue? except to change all "~/" to "/".  Thank you.
