### ISSUE TITLE
How to copy Intermediate certificate

### ISSUE THREAD

**Issue by Zeni241** [acmesh-official/acme.sh#3916]
I have successfully installed SSL certificate using acme.sh and copied those to location for use with my nginx server. I used bellow commands:
acme.sh --install-cert -d example.com \
--cert-file      file /etc/nginx/ssl/cert.pem  \
--key-file /etc/nginx/ssl/key.pem  \
--fullchain-file /etc/nginx/ssl/cert.pem \
--reloadcmd     "service nginx force-reload"
Everything went smooth. My question is how can I copy the intermediate certificate?
I used bellow command without success. 
**acme.sh --install-cert -d roborne.com ‎--intermediate-file /etc/nginx/ssl/intemediate.pem**
**The error is " Unknown parameter : ‎--intermediate-file"**

**Comment by Neilpang** [comment]
use `--ca-file`

```
--cert-file <file>                Path to copy the cert file to after issue/renew..
  --key-file <file>                 Path to copy the key file to after issue/renew.
  --ca-file <file>                  Path to copy the intermediate cert file to after issue/renew.
  --fullchain-file <file>           Path to copy the fullchain cert file to after issue/renew.
  --reloadcmd <command>             Command to execute after issue/renew to reload the server.
```

**Comment by user8446** [comment]
Thank you, could not find in the docs and found it here.
