### ISSUE TITLE
Export to PFX format with blank or null password

### ISSUE THREAD

**Issue by plittlefield** [acmesh-official/acme.sh#3931]
What is the correct syntax for using a blank password during an export to PFX format?

`./acme.sh --to-pkcs12 --password '' --domain sub.domain.uk.com
`

**Comment by Neilpang** [comment]
NO,

**Comment by plittlefield** [comment]
> NO,

Can you qualify that please? :-)

Do I use the word NO after the `--password` command line option or do you mean NO there is no option for a blank password?!

**Comment by Neilpang** [comment]
there is no way to export pfx without password.

**Comment by lightnear** [comment]
you can use openssl:

```shell
openssl pkcs12 -export \
  -in /data/acme.sh/example.com/fullchain.cer \
  -inkey /data/acme.sh/example.com/example.com.key \
  -out /data/acme.sh/example.com/example.com.pfx \
  -passout pass:
```
