### ISSUE TITLE
is it possible to let acme.sh output pem format 

### ISSUE THREAD

**Issue by jiangxiaoqiang** [acmesh-official/acme.sh#3941]
I am using this command to renew the certificate:

`acme.sh --renew -d example.com
`

the output format in `*.cer`, is it possible to output `.pem` format?

https://unix.stackexchange.com/questions/690559/is-it-possible-to-custom-the-acme-sh-output-certificate-format

**Comment by Neilpang** [comment]
```
cer === pem
```
