### ISSUE TITLE
Issue Generating Acme Certificate with Google Cloud DNS

### ISSUE THREAD

**Issue by hatakora62** [acmesh-official/acme.sh#3945]
I have followed the docs and instructions and everything. Setup gcloud on my truenas box and connected my account. When i run the script to generate the cert i am getting the error below

WARNING: The following filter keys were not present in any resource : dnsName, visibility
[Wed Feb 16 23:39:56 PST 2022] _dns_gcloud_find_zone: Can't find a matching managed zone! Perhaps wrong project or gcloud credentials?
[Wed Feb 16 23:39:56 PST 2022] Error add txt for domain:_acme-challenge.mydomain.co

But i can see in my Gcloud account APi monitoring that the calls are coming through so it is not a credential issue. What am i doing wrong?

**Comment by hatakora62** [comment]
I fixed this. For any one else having the issue. I needed to grant my gcloud account DNS administrator role

**Comment by litvinovandrew** [comment]
In my case except of the granting DNS administrator role , I needed to add managed zone manually with the command 
`gcloud dns managed-zones create temp  --description="temp"     --dns-name=example.com     --visibility=public`
