### ISSUE TITLE
oathtool tool used in deploy/synonoly_dsm.sh does not exist on NAS Synology DSM system

### ISSUE THREAD

**Issue by ashkii7** [acmesh-official/acme.sh#3953]
The Certificate Deployment Script (synology_dsm.sh) for a NAS Synology uses the "oathtool" tool to generate OTP code when the 2FA is enabled on the NAS.
**Problem**: The "oathtool" tool does not exist on the NAS DSM system and does not sample itself in the acme.sh basic package (unless you use a Docker image but Docker is not compatible with all NAS Syology).
In the end, if the 2fa is enabled for the user account, the deployment of the certificate Let'sEncrypt fails because it does not find the 'oathtool' tool to generate the correct OTP code and therefore be able to validate the connection to the account.

**Comment by ashkii7** [comment]
The Certificate Deployment Script (Synology_DSM.SH) for a NAS Synology uses the "OATTool" tool to generate OTP code when the 2FA is enabled on the NAS.
Problem: The "OATTool" tool does not exist on the NAS DSM system and does not sample itself in the acme.sh basic package (unless you use a Docker image but Docker is not compatible with all NAS Syology).
In the end, if the 2fa is enabled for the user account, the deployment of the certificate fails because it does not find the OATTool tool to generate the correct OTP code and therefore be able to validate the connection to the account.

**Comment by Eagle3386** [comment]
1. Wrong issue, your feedback belongs to #2727.
2. Known issue, see my comment [over there](https://github.com/acmesh-official/acme.sh/issues/2727#issuecomment-1039308674).

@Neilpang IMHO, should be closed.
