### ISSUE TITLE
does not generate certificates

### ISSUE THREAD

**Issue by staffnetDev** [acmesh-official/acme.sh#3957]
![image](https://user-images.githubusercontent.com/34721370/155865394-642a6184-30d9-4e46-abcd-963e090d7fe4.png)
what am I doing wrong?

**Comment by Neilpang** [comment]
paste log with `--debug 2`

**Comment by staffnetDev** [comment]
Thanks . but the problem is when I use * as subdomain . in manual dns1 validation. my solution was to use automatic dns1 validation .

**Comment by Neilpang** [comment]
If you want to get help faster,  please paste the log first next time.

**Comment by staffnetDev** [comment]
I'll send the problem log as manual validation doesn't work for me
