### ISSUE TITLE
Fail action fails due to hard-coded check for a secret named "TokenName1" in CheckToken

### ISSUE THREAD

**Issue by Eagle3386** [acmesh-official/acme.sh#3958]
Steps to reproduce
------------------
1. Fork the official ACME.sh repo.
2. Add all required GitHub Actions secrets as explained at the [DNS API Test](https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test).
3. Trigger DNS.yml action.

Debug log
-----------------
```sh
echo "Read this:   https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test"
  if [ "Eagle3386" != "acmesh-official" ]; then
    false
  fi
  shell: /usr/bin/bash -e {0}
Read this:   https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test
Error: Process completed with exit code 1.
```

@Neilpang As you can see, my fork's repo name is compared to the official repo's name which obviously fails & in turn breaks the whole DNS.yml CI workflow, i. e. breaks testing the CI workflow as a whole.

This is due to the `CheckToken`'s action having a hard-coded check for a secret named `TokenName1` while the DNS API Test docs over at your wiki suggest that you _can_ name your secret like that ("_Let's assume the usage of your api is like below_").
I for one chose to follow the DNS API guide's rules & named my secrets just like the actual DNS API plugin does require them to be named, i. e. `AF_API_USERNAME` & `AF_API_PASSWORD`.

Any chance you can fix this (DNS.yml & wiki) in the future?

**Comment by Neilpang** [comment]
read the guide again, word by word.
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test

```
TokenName1= AF_API_USERNAME
TokenValue1=youapiName


TokenName2= AF_API_PASSWORD
TokenValue2=youapiPassword

```

**Comment by Eagle3386** [comment]
I did read it & of course, got it working.
Still, it's misleading as it _suggests_ something different is possible where it should state what is _required_ regarding secrets & their naming.
