### ISSUE TITLE
请求CA机构时，是否能支持走HTTP代理？

### ISSUE THREAD

**Issue by jearton** [acmesh-official/acme.sh#3960]
因为我的大陆VPS访问acme.zerossl.com实在太慢了，丢包率也很高，如果能走HTTP代理，那么我就可以通过VPN进行转发了，更稳定。

**Comment by Neilpang** [comment]
可以.  因为请求使用的是 curl.  所以可以用 `.curlrc`  文件来配置 代理.

具体请 自行谷歌.
