### ISSUE TITLE
关于ZeroSSL邮箱的问题

### ISSUE THREAD

**Issue by jearton** [acmesh-official/acme.sh#3962]
我发现，只要使用注册过ZeroSSL的邮箱账号来颁发证书，这个证书就会自动显示到这个邮箱注册的ZeroSSL管理后台上。只要一个邮箱地址就能往这个帐号的后台写东西了，都不需要输入密码认证啥的吗？邮箱地址是公开信息呀，万一别人用我的邮箱来颁发证书，那我的管理后台里岂不是要经常多出来莫名其妙的域名证书？

**Comment by Neilpang** [comment]
用 letsencrypt 也是一样啊.  区别只是 letsencrypt 没有后台UI 你看不见而已.
