### ISSUE TITLE
LoopiaAPI changed

### ISSUE THREAD

**Issue by Fridman87** [acmesh-official/acme.sh#3963]
Loopia recently changed their API, addZoneRecord function MUST include customer_number. Loopia DNS integration needs to be updated to reflect new changes. Also they have not updated their own documentation or published any change log. 

From Loopia:
On February 23, 2022, we will upgrade our servers and improve LoopiaAPI

From Loopia second line support:
`Hey!

The old documentation should not be needed as the calls are very similar to the ones we have now, the API page with us has not changed since the update.

What should be included should be the following: addZoneRecord (username, password, [customer_number,] domain, subdomain, record_obj)

Customer number is a requirement nowadays for it to work, if you have blocked your login to the customer zone by turning on "Bankid Only" then it needs to be turned off.`

Doc: 
https://www.loopia.com/api/addzonerecord/

**Comment by gabbe** [comment]
This turned out to be false information. "customer_number" is NOT mandatory for addZoneRecord. However, there were a few issues with the update. I believe they fixed some issues yesterday evening since some of my tests magically started working this morning... The second issue is that the new API is less tolerant about the XML-structure so the dns_loopia.sh needed a small update. I opened a Pull Request here:
https://github.com/acmesh-official/acme.sh/pull/3964

**Comment by Fridman87** [comment]
Thank you for figuring out the issue. Just tested your PR and it worked perfectly :)

**Comment by cthart** [comment]
> This turned out to be false information. "customer_number" is NOT mandatory for addZoneRecord. However, there were a few issues with the update. I believe they fixed some issues yesterday evening since some of my tests magically started working this morning... The second issue is that the new API is less tolerant about the XML-structure so the dns_loopia.sh needed a small update. I opened a Pull Request here: #3964

Thanks for fixing this! I was out of town for a few days and was preparing to delve into this myself today.

**Comment by gabbe** [comment]
This patch is now merged into master
https://github.com/acmesh-official/acme.sh/commit/9ebb2ac2e4e0e5489700721c1ec9729ac27de5cd
@Fridman87 - maybe you can close the issue after verifying.
