### ISSUE TITLE
请问是否支持DNS CNAME方式验证域名？

### ISSUE THREAD

**Issue by jearton** [acmesh-official/acme.sh#3967]
我想使用统一的服务器来验证各种域名，在使用DNS API验证时，通过CNAME来转发到同一个域名上来验证。这个可以实现吗？我看letsencrypt里有介绍这种方案。

https://letsencrypt.org/zh-cn/docs/challenge-types/#dns-01-%E9%AA%8C%E8%AF%81%E6%96%B9%E5%BC%8F

![image](https://user-images.githubusercontent.com/10370433/156883202-85522f72-2d58-4bf8-a7ed-5c81437b125e.png)

**Comment by Neilpang** [comment]
可以, 
使用别名模式:
https://github.com/acmesh-official/acme.sh/wiki/DNS-alias-mode
