### ISSUE TITLE
Tried over 10 times. zerossl keeps Timeout. Processing, The CA is processing your order, please just wait. (29/30)

### ISSUE THREAD

**Issue by ShawnYou1** [acmesh-official/acme.sh#3995]
Tried more than 10 times over different time periods.

**acme.sh version : 3.0.3.**  

Github comment do not support too long text(maximum is 65536 characters). 
Please check the attached log file [acme.log.txt](https://github.com/acmesh-official/acme.sh/files/8312742/acme.log.txt)

Thank you for your work.

**Comment by FelixDobler** [comment]
I also had problems with zerossl (long certificate creation times), Letsencrypt worked fine though.
You can use another certificate authority (e.g. letsencrypt), by using the `--server letsencrypt` option.
This is a one time change, `acme.sh --set-default-ca --server letsencrypt` sets the server to be used by default.

**Comment by ShawnYou1** [comment]
Hi, thank you for your reply. 

It still using zerossl after exec the command `acme.sh --set-default-ca --server letsencrypt`

![image](https://user-images.githubusercontent.com/44994356/159488504-9a2cadc6-c973-453b-bf82-3f0d820878f3.png)

**Comment by FelixDobler** [comment]
I don't know too much about the process itself, but maybe it is using zerossl again because you are renewing your certificate and it used zerossl initially?
Can you test if issuing a new one will use letsencrypt?

Also, make sure the webserver is reachable for the ca.

**Comment by ShawnYou1** [comment]
Your analysis may be correct, and cool direction. 

I will try to issue a new one using letsencrypt.

**Comment by ShawnYou1** [comment]
> I don't know too much about the process itself, but maybe it is using zerossl again because you are renewing your certificate and it used zerossl initially? Can you test if issuing a new one will use letsencrypt?
> 
> Also, make sure the webserver is reachable for the ca.

**Comment by ShawnYou1** [comment]
> I don't know too much about the process itself, but maybe it is using zerossl again because you are renewing your certificate and it used zerossl initially? Can you test if issuing a new one will use letsencrypt?
> 
> Also, make sure the webserver is reachable for the ca.

It works well by issuing a new one after switching to letsencrypt.  

Thank you FelixDobler for your analysis.

The issue will keep open before the zerossl timeout will be solved.

**Comment by ShawnYou1** [comment]
It works well by issuing a new one after switching to letsencrypt.

Thank you FelixDobler for your analysis.

The issue will keep open before the zerossl timeout will be solved.

**Comment by Jefffish09** [comment]
Same timeout issue. Using letsencrypt is normal.

**Comment by KainanSu** [comment]
`./acme.sh  --set-default-ca --server zerossl`
solved.
