### ISSUE TITLE
困扰好久的问题感谢能指导一二的人

### ISSUE THREAD

**Issue by gyflonely** [acmesh-official/acme.sh#3996]
我有个openwrt路由 运营商封锁了80和443端口 我的域名是很久前申请的免费域名 不支持添加dns记录之类的操作所以我想用acme脚本命令行申请证书 我的命令是acme.sh --issue  -d abc.net -w /www --httpport 9980 因为80端口不能用所以路由器映射域名9980端口到内网路由器ip的80端口 可以正常访问/www目录下的文件 但就是不能通过验证 那个.wellknow文件夹及里面的文件都在手动输入网址也能访问到可以看到网页是一串字符就是不能通过验证 看了debug还是访问的域名而不是域名加端口 但下面有记录现实httpport是9980  我已经加了--httpport 参数了还是不行，是不是没有dns api或者手动dns验证 就是在域名提供商那里添加txt记录就不能使用acme获取到证书了？事情就是这样子 希望有人能帮助我困扰了好久的问题

**Comment by xiaohuilam** [comment]
依據 `CA/B Forum` 關於文件應答挑戰核驗模式之規定，證書簽發機構不允許非 `443`、`80` 埠。
所以你的問題無解。

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh/wiki/DNS-alias-mode
