### ISSUE TITLE
Give me an error

### ISSUE THREAD

**Issue by fivestar9105** [acmesh-official/acme.sh#4003]
i have installed ubuntu 20.04, i clone the repository and give me thath error, with any domain that i put

./acme.sh --issue --deploy -d srv99201-206152.vps.etecsa.cu --deploy-hook routeros

[Tue Mar 29 11:17:50 CDT 2022] The domain 'srv99201-206152.vps.etecsa.cu' is not a cert name. You must use the cert name to specify the cert to install.
[Tue Mar 29 11:17:50 CDT 2022] Can not find path:'/root/.acme.sh/srv99201-206152.vps.etecsa.cu'

**Comment by Neilpang** [comment]
you must `--issue` a cert first,
And then "--deploy" it.
