### ISSUE TITLE
After the ZeroSSL certificate is successfully updated, the certificate is still expired

### ISSUE THREAD

**Issue by annizal** [acmesh-official/acme.sh#4004]
Certificate Type: ZeroSSL
Recently, I updated the ZeroSSL certificate by adding a txt record in manual DNS, and the whole process showed success. But after I restarted nginx, I found that the date of the certificate still expired.
After investigation, I found that except for the .key file, the rest of the files were the latest date.
After many retries, the result is the same. I'm sure that the files I call are up-to-date and have no issues with the configuration.
Finally I switched to the Let's Encrypt certificate and the certificate was successfully renewed.
My acme.sh version is V3.0.2

**Comment by Neilpang** [comment]
check your configuration pointing at the latest file.

**Comment by annizal** [comment]
Today is 2022-10-16, and my acme.sh version is V3.0.5. I tested the problem and found that it is still not resolved. So, I have to execute the following command every time before renew.
sed -i '/\(Le_OrderFinalize\|Le_LinkOrder\|Le_LinkCert\|Le_CertCreateTime\|Le_CertCreateTimeStr\|Le_NextRenewTimeStr\|Le_NextRenewTime\)/d' /cert/*.xxx.xxx_ecc/*.xxx.xxx.conf
