### ISSUE TITLE
Using acme.sh for multiple CA fallback issuance?

### ISSUE THREAD

**Issue by centminmod** [acmesh-official/acme.sh#4009]
Just saw the news for Google CA added support https://github.com/acmesh-official/acme.sh/wiki/Google-public-CA so was thinking it would be a good time to code multiple CA fallback issuance into my LEMP stack's acme.sh integration. But I thought I'd ask a few clarifying questions.

When I mean multiple CA fallback, I mean if my LEMP stack creates a new Nginx HTTPS site, it first tries using Letsncrypt CA and if that fails, try ZeroSSL CA and if that fails try Google CA.

1. Verifying ZeroSSL and Google CA's respective ca.conf and EAB Key ID and HMAC Key credentials. Is there any built in acme.sh command line to verify that ZeroSSL and/or Google CA's credentials are a) set and b) correct?  

i.e. something like

```
acme.sh --check --server zerossl --credentials
acme.sh --check --server google --credentials
```

Which would check the current `/root/.acme.sh/ca/acme.zerossl.com/ca.conf ` and `/root/.acme.sh/ca/dv.acme-v02.api.pki.goog/directory/ca.conf` files.

2. I am thinking of verifying by scripting checks for `/root/.acme.sh/ca/acme.zerossl.com/ca.conf ` and `/root/.acme.sh/ca/dv.acme-v02.api.pki.goog/directory/ca.conf` files' existence and that the `CA_EAB_KEY_ID` and `CA_EAB_HMAC_KEY` are set. But that only goes to verify they exist but not if they're correct. Also if you later change the location of the ca.conf file, then it would break my checks. So is there any inbuilt acme.sh command to check they're correct without actually issuing a SSL certificate? 

3. To clarify, if I initially issued a SSL cert using Letsencrypt but on renewal it had to fallback to ZeroSSL, that would override the domains .conf file so auto renewal subsequent time will be ZeroSSL when there's no other intervention by me right?

Cheers

**Comment by Neilpang** [comment]
>> You can call acme.sh --update-account --server zerossl, and check the exit code of the command.

please use the latest `dev` branch to try:

```
acme.sh  --upgrade -b dev
```

**Comment by centminmod** [comment]
> You can call `acme.sh --update-account --server zerossl`, and check the exit code of the command.

sweet

> Maybe it's time to add built-in support for CA fallback. Let me think about it.

Yes that would be nice to have natively in acme.sh - maybe it could be a global + user overridable array of CA providers that can control the order of fallback CAs `array=letsencrypt zerossl google`

`acme.sh  --upgrade -b dev`

And to switch back to production the command would be `acme.sh  --upgrade` ?

**Comment by Neilpang** [comment]
>> And to switch back to production the command would be acme.sh --upgrade ?

Yes.


>> Yes that would be nice to have natively in acme.sh -

It's not easy, and will take time.  don't rely on it for now. you can implement it in your wrapper for now.


>>  maybe it could be a global + user overridable array of CA providers that can control the order of fallback CAs array=letsencrypt zerossl google

I don't have good idea for now.   Any suggestion is welcome.    Different CAs support differen features, like: domains count,  wildcard domains,  and Ecc support etc.  It's not easy to fallback.

**Comment by centminmod** [comment]
Cheers Neil. Yeah implementing fallback CA has many variables to consider. Still thinking about how I'd implement it in my wrapper too :) Getting CA credential verification sorted first though :)

**Comment by centminmod** [comment]
@Neilpang just tried `acme.sh --update-account --server zerossl` to check but it seems it removes `/root/.acme.sh/ca/acme.zerossl.com/ca.conf` file?

```
acme.sh --upgrade -b dev

cat /root/.acme.sh/ca/acme.zerossl.com/ca.conf 
cat: /root/.acme.sh/ca/acme.zerossl.com/ca.conf: No such file or directory
```

**Comment by Neilpang** [comment]
no,  it seems you never registered zerossl account on your machine.

**Comment by Neilpang** [comment]
this is the latest correct location:
/root/.acme.sh/ca/acme.zerossl.com/v2/DV90/ca.conf

**Comment by centminmod** [comment]
I actually did with acme.sh v3.0.3 registered and the credentials were saved to `/root/.acme.sh/ca/acme.zerossl.com/ca.conf`

then switched dev branch and ran 

`acme.sh --upgrade -b dev`

and now location is at `/root/.acme.sh/ca/acme.zerossl.com/v2/DV90/ca.conf`

**Comment by Neilpang** [comment]
yes,   the ca conf folder has changed and moved automatically.

It should process it without any errors automatically.  

what was your version before this  upgrade ?

**Comment by centminmod** [comment]
I see. Version was latest v3.0.3.

Also noticed if I modified an incorrect credential in `/root/.acme.sh/ca/acme.zerossl.com/v2/DV90/ca.conf` and ran

```
acme.sh --update-account --server zerossl
```

It will still result in exist status = 0 and

```
acme.sh --update-account --server zerossl
[Thu Mar 31 03:09:16 UTC 2022] account update success for https://acme.zerossl.com/v2/DV90/account/akj_b******

echo $?
0
```

So `acme.sh --update-account --server zerossl` only checks for the ca.conf but not if the credentials are correct right?

**Comment by Neilpang** [comment]
The  eabkid/hmackey recorded in the ca.conf is not always reliable. 

For the Google public CA,  the given  eabkid/hmackey is only valid for 7 days. 

https://cloud.google.com/public-certificate-authority/docs/quickstart

>> You must use an EAB secret within 7 days of obtaining it. The EAB secret is invalidated if you don't use it within 7 days. The ACME account registered using an EAB secret has no expiration.


The only reliable thing is the account private key.


As for the `--update-account` command,  it only uses the account key to update the account object through ACME protocol, which dosn't  rely on  EAB secrets.

**Comment by centminmod** [comment]
I see. The https://cloud.google.com/public-certificate-authority/docs/quickstart for me gives 404 not found. Guess need to wait for email approval to see it?

> The eabkid/hmackey recorded in the ca.conf is not always reliable.
> For the Google public CA, the given eabkid/hmackey is only valid for 7 days

hmm tricky to do verification for credentials then, guess would need to rely on a CA fallback cycling through CAs if cert issuance failed due to incorrect/missing credentials then.

**Comment by Neilpang** [comment]
>>  Guess need to wait for email approval to see it?

Yes, I just noticed it's not open to anyone yet.

**Comment by Neilpang** [comment]
but all the steps in that page can be found in the blog:
https://cloud.google.com/blog/products/identity-security/automate-public-certificate-lifecycle-management-via--acme-client-api

**Comment by centminmod** [comment]
Thanks Neil much appreciated ^_^

**Comment by Neilpang** [comment]
>> hmm tricky to do verification for credentials then, guess would need to rely on a CA fallback cycling through CAs

If you need to make sure the  eab secrets are valid,  please use `--register-account`.

```
acme.sh  --register-account  --server zerossl
```

It will  pickup the  email and eab secrets to register the acount again.  
Don't worry,  the CA should be able process this case.

**Comment by Neilpang** [comment]
But for google CA after 7 days,   the `--register-account` can fail, but  `--update-acount` can success.

**Comment by centminmod** [comment]
Tried with bad credentials and still reported ok for ZeroSSL heh

```
acme.sh --register-account --server zerossl --eab-kid badkid --eab-hmac-key badkey
[Thu Mar 31 03:37:02 UTC 2022] Registering account: https://acme.zerossl.com/v2/DV90
[Thu Mar 31 03:37:05 UTC 2022] Already registered
[Thu Mar 31 03:37:05 UTC 2022] ACCOUNT_THUMBPRINT='**********-i-****************'

echo $?
0

cat /root/.acme.sh/ca/acme.zerossl.com/v2/DV90/ca.conf 
CA_EAB_KEY_ID='badkid'
CA_EAB_HMAC_KEY='badkey'
ACCOUNT_URL='https://acme.zerossl.com/v2/DV90/account/*******************'
CA_KEY_HASH='xxxxxxxx='
```

> But for google CA after 7 days, the --register-account can fail, but --update-acount can success.

Interesting way of doing things with Google CA

**Comment by Neilpang** [comment]
>> where is it picking up the already registered info? The CA_KEY_HASH ?

No,  the CA just returns us a valid object:

```
[Thu 31 Mar 2022 04:42:24 AM BST] response='{"status":"valid","contact":["mailto:a@a.com"],"termsOfServiceAgreed":true,"externalAccountBinding":
```


It's possible that the Zerossl CA just validates the account key signature,  and ignores the eab secrets in this case.

**Comment by centminmod** [comment]
I see. It does indeed

```
[Thu Mar 31 03:45:58 UTC 2022] Use cached jwk for file: /root/.acme.sh/ca/acme.zerossl.com/v2/DV90/account.key
```
Lots to think about for planning CA fallback!
