### ISSUE TITLE
How does the renewal of certificates work?

### ISSUE THREAD

**Issue by warcayac** [acmesh-official/acme.sh#4016]
I've followed steps mentioned by [ACME.SH](https://github.com/acmesh-official/acme.sh). 

I've emitted certificates with this:

```
$ acme.sh --issue --dns dns_linode_v4 --dnssleep 90 -d mycompany.org -d chesu.mycompany.org
```

And I've installed those certificates with:
```
$ acme.sh --install-cert -d mycompany.org --cert-file /etc/opt/certs/mycompany.org/cert.pem --key-file /etc/opt/certs/mycompany.org/key.pem --fullchain-file /etc/opt/certs/mycompany.org/fullchain.pem
```
Finally I've configured my Apache server and restarted my *httpd* service. My web server is working by using SSL now.

For final step, I should run these commands:

```
$ acme.sh --renew -d mycompany.org --force
$ acme.sh --upgrade --auto-upgrade
```

So my questions are:

- For renewal, are the new certificates automatically copied to `/etc/opt/certs/mycompany.org`? or does it need to be manually done?

- For upgrade, is it advisable to set `auto-upgrade`?

**Comment by Neilpang** [comment]
>> Finally I've configured my Apache server and restarted my httpd service.

Did you read the wiki page: 
https://github.com/acmesh-official/acme.sh#3-install-the-cert-to-apachenginx-etc

>> For renewal, are the new certificates automatically copied to /etc/opt/certs/mycompany.org

yes

>> For upgrade, is it advisable to set auto-upgrade?

yes

Those anwsers are all in the wiki page.

**Comment by warcayac** [comment]
I did read the wiki page, but I wasn't sure if this renewal was for files located at `.acme.sh` only or it also included certificates where they installed. 

Then it is important for `acme.sh --install-cert` to set `--reloadcmd` option too.

Thanks @Neilpang.

**Comment by warcayac** [comment]
Last question @Neilpang ,

I've been doing these task with a not-root user (a sudoer), so this command for my example:

```
$ acme.sh --install-cert -d mycompany.org \
--cert-file /etc/opt/certs/mycompany.org/cert.pem \
--key-file /etc/opt/certs/mycompany.org/key.pem \
--fullchain-file /etc/opt/certs/mycompany.org/fullchain.pem \
--reloadcmd "systemctl restart httpd"
```
or using `"service httpd force-reload"`

does it not require authentication by password? because when trying to run this command `systemctl restart httpd` the OS requires root password, and if I use `sudo systemctl restart httpd` the OS requires my password.

**Comment by wulph111** [comment]
> Those anwsers are all in the wiki page.

The wiki page is not clear on the answers to these questions.
