### ISSUE TITLE
my web server is showing Testing 123 page after renewal

### ISSUE THREAD

**Issue by warcayac** [acmesh-official/acme.sh#4019]
I have acme.sh installed with user (sudoer) **myuser**, the details are in [this issue](https://github.com/acmesh-official/acme.sh/issues/4016), then I did this in **sudoers** file.

```
myuser ALL=(ALL) NOPASSWD: /bin/systemctl restart httpd
```

After that I re-run:

```
$ acme.sh --install-cert -d mycompany.org --cert-file /etc/opt/certs/mycompany.org/cert.pem --key-file /etc/opt/certs/mycompany.org/key.pem --fullchain-file /etc/opt/certs/mycompany.org/fullchain.pem --reloadcmd "sudo systemctl restart httpd"
```
I got thhis message:

```
[Wed Apr  6 11:36:28 PET 2022] Installing cert to: /etc/opt/certs/sisrev-edar/cert.pem
[Wed Apr  6 11:36:28 PET 2022] Installing key to: /etc/opt/certs/sisrev-edar/key.pem
[Wed Apr  6 11:36:28 PET 2022] Installing full chain to: /etc/opt/certs/sisrev-edar/fullchain.pem
[Wed Apr  6 11:36:28 PET 2022] Run reload cmd: sudo systemctl restart httpd
[Wed Apr  6 11:36:29 PET 2022] Reload success
```
Then I did this (my fail):

```
$ acme.sh --renew -d mycompany.org --force
```
[Wed Apr  6 11:40:16 PET 2022] Renew: 'mycompany.org'
[Wed Apr  6 11:40:22 PET 2022] Using CA: https://acme.zerossl.com/v2/DV90
[Wed Apr  6 11:40:22 PET 2022] Multi domain='DNS:mycompany.org,DNS:mysubdomain.mycompany.org'
[Wed Apr  6 11:40:22 PET 2022] Getting domain auth token for each domain
[Wed Apr  6 11:40:39 PET 2022] Getting webroot for domain='mycompany.org'
[Wed Apr  6 11:40:39 PET 2022] Getting webroot for domain='mysubdomain.mycompany.org'
[Wed Apr  6 11:40:39 PET 2022] Adding txt value: OMyJGiTX8W4omIC4Bws1wlRpbm6Eg5QUzcmKj5Bq9wg for domain:  _acme-challenge.mycompany.org
[Wed Apr  6 11:40:39 PET 2022] Using Linode
[Wed Apr  6 11:40:40 PET 2022] Domain resource successfully added.
[Wed Apr  6 11:40:40 PET 2022] The txt record is added: Success.
[Wed Apr  6 11:40:40 PET 2022] Adding txt value: baLd_ZAIWv3XojsIDxiw88GlSGxO4I6XNCp_7MOoCno for domain:  _acme-challenge.mysubdomain.mycompany.org
[Wed Apr  6 11:40:40 PET 2022] Using Linode
sed: -e expression #1, char 69: Invalid preceding regular expression
[Wed Apr  6 11:40:40 PET 2022] Domain resource successfully added.
[Wed Apr  6 11:40:40 PET 2022] The txt record is added: Success.
[Wed Apr  6 11:40:41 PET 2022] Sleep 90 seconds for the txt records to take effect
[Wed Apr  6 11:42:12 PET 2022] Verifying: mycompany.org
[Wed Apr  6 11:42:12 PET 2022] Processing, The CA is processing your order, please just wait. (1/30)
....
```
I lost the subsequent messages.

But after that my webserver is a mess, it is only showing a page with text "Testing 123...", my `vhost.conf` file is not modified. I don't know what happened. So I uninstalled acme.sh and returned my current `vhost.conf` file to old version which listen port 80 only, but even so there are some files no located when browsing on Internet, no files were deleted. So strange.

My questions:

1. What happened after manually renewing?
2. This event will happen when renewing after 60 days?

**Comment by Neilpang** [comment]
acme.sh doens't modify your  webserver conf at all.   please check other reasons.
