### ISSUE TITLE
Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 60

### ISSUE THREAD

**Issue by qwe231cvb** [acmesh-official/acme.sh#4023]
When i apply for ssl certificate i get this error:：
Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 60
How to resolve?

**Comment by cypa** [comment]
I've got same error on CentOS 6 old server - I guess need to update ca-certificates list
