### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by prettyCoders** [acmesh-official/acme.sh#4028]
root@YB04-A27:~# acme.sh --issue  -d www.starswap.cn   --nginx
[Sun Apr 10 16:40:45 UTC 2022] Sleep 10 and retry.
[Sun Apr 10 16:41:01 UTC 2022] Using CA: https://acme.zerossl.com/v2/DV90
[Sun Apr 10 16:41:01 UTC 2022] Single domain='www.starswap.cn'
[Sun Apr 10 16:41:01 UTC 2022] Getting domain auth token for each domain
[Sun Apr 10 16:41:17 UTC 2022] Getting webroot for domain='www.starswap.cn'
[Sun Apr 10 16:41:17 UTC 2022] Verifying: www.starswap.cn
[Sun Apr 10 16:41:17 UTC 2022] Nginx mode for domain:www.starswap.cn
[Sun Apr 10 16:41:17 UTC 2022] Found conf file: /etc/nginx/conf.d/starswap.conf
[Sun Apr 10 16:41:17 UTC 2022] Backup /etc/nginx/conf.d/starswap.conf to /root/.acme.sh/www.starswap.cn/backup/www.starswap.cn.nginx.conf
[Sun Apr 10 16:41:17 UTC 2022] Check the nginx conf before setting up.
[Sun Apr 10 16:41:17 UTC 2022] OK, Set up nginx config file
[Sun Apr 10 16:41:17 UTC 2022] nginx conf is done, let's check it again.
[Sun Apr 10 16:41:17 UTC 2022] Reload nginx
[Sun Apr 10 16:41:24 UTC 2022] Processing, The CA is processing your order, please just wait. (1/30)
[Sun Apr 10 16:41:30 UTC 2022] Success
[Sun Apr 10 16:41:30 UTC 2022] Restoring from /root/.acme.sh/www.starswap.cn/backup/www.starswap.cn.nginx.conf to /etc/nginx/conf.d/starswap.conf
[Sun Apr 10 16:41:30 UTC 2022] Reload nginx
[Sun Apr 10 16:41:30 UTC 2022] Verify finished, start to sign.
[Sun Apr 10 16:41:30 UTC 2022] Lets finalize the order.
[Sun Apr 10 16:41:30 UTC 2022] Le_OrderFinalize='https://acme.zerossl.com/v2/DV90/order/jKYrKeJWeqM_GYIVK1DpAA/finalize'
[Sun Apr 10 16:41:35 UTC 2022] Order status is processing, lets sleep and retry.
[Sun Apr 10 16:41:35 UTC 2022] Retry after: 15
[Sun Apr 10 16:41:51 UTC 2022] Polling order status: https://acme.zerossl.com/v2/DV90/order/jKYrKeJWeqM_GYIVK1DpAA
[Sun Apr 10 16:41:57 UTC 2022] Order status is processing, lets sleep and retry.
[Sun Apr 10 16:41:57 UTC 2022] Retry after: 15
[Sun Apr 10 16:42:13 UTC 2022] Polling order status: https://acme.zerossl.com/v2/DV90/order/jKYrKeJWeqM_GYIVK1DpAA
[Sun Apr 10 16:42:21 UTC 2022] Order status is processing, lets sleep and retry.
[Sun Apr 10 16:42:21 UTC 2022] Retry after: 15
[Sun Apr 10 16:42:37 UTC 2022] Polling order status: https://acme.zerossl.com/v2/DV90/order/jKYrKeJWeqM_GYIVK1DpAA
[Sun Apr 10 16:42:46 UTC 2022] Order status is processing, lets sleep and retry.
[Sun Apr 10 16:42:46 UTC 2022] Retry after: 15
[Sun Apr 10 16:43:02 UTC 2022] Polling order status: https://acme.zerossl.com/v2/DV90/order/jKYrKeJWeqM_GYIVK1DpAA
[Sun Apr 10 16:43:09 UTC 2022] Order status is processing, lets sleep and retry.
[Sun Apr 10 16:43:09 UTC 2022] Retry after: 15
[Sun Apr 10 16:43:25 UTC 2022] Polling order status: https://acme.zerossl.com/v2/DV90/order/jKYrKeJWeqM_GYIVK1DpAA
[Sun Apr 10 16:43:29 UTC 2022] Order status is processing, lets sleep and retry.
[Sun Apr 10 16:43:29 UTC 2022] Retry after: 15
[Sun Apr 10 16:43:45 UTC 2022] Polling order status: https://acme.zerossl.com/v2/DV90/order/jKYrKeJWeqM_GYIVK1DpAA
[Sun Apr 10 16:43:50 UTC 2022] Order status is processing, lets sleep and retry.
[Sun Apr 10 16:43:50 UTC 2022] Retry after: 15
[Sun Apr 10 16:44:06 UTC 2022] Polling order status: https://acme.zerossl.com/v2/DV90/order/jKYrKeJWeqM_GYIVK1DpAA
[Sun Apr 10 16:44:11 UTC 2022] Order status is processing, lets sleep and retry.
[Sun Apr 10 16:44:11 UTC 2022] Retry after: 15
[Sun Apr 10 16:44:27 UTC 2022] Polling order status: https://acme.zerossl.com/v2/DV90/order/jKYrKeJWeqM_GYIVK1DpAA
[Sun Apr 10 16:44:33 UTC 2022] Order status is processing, lets sleep and retry.
[Sun Apr 10 16:44:33 UTC 2022] Retry after: 15
[Sun Apr 10 16:44:49 UTC 2022] Polling order status: https://acme.zerossl.com/v2/DV90/order/jKYrKeJWeqM_GYIVK1DpAA
[Sun Apr 10 16:44:57 UTC 2022] Order status is processing, lets sleep and retry.
[Sun Apr 10 16:44:57 UTC 2022] Retry after: 15
[Sun Apr 10 16:45:13 UTC 2022] Polling order status: https://acme.zerossl.com/v2/DV90/order/jKYrKeJWeqM_GYIVK1DpAA
[Sun Apr 10 16:45:21 UTC 2022] Order status is processing, lets sleep and retry.
[Sun Apr 10 16:45:21 UTC 2022] Retry after: 15
[Sun Apr 10 16:45:37 UTC 2022] Polling order status: https://acme.zerossl.com/v2/DV90/order/jKYrKeJWeqM_GYIVK1DpAA
[Sun Apr 10 16:45:44 UTC 2022] Order status is processing, lets sleep and retry.
[Sun Apr 10 16:45:44 UTC 2022] Retry after: 15
[Sun Apr 10 16:46:00 UTC 2022] Polling order status: https://acme.zerossl.com/v2/DV90/order/jKYrKeJWeqM_GYIVK1DpAA
^[[B[Sun Apr 10 16:46:04 UTC 2022] Order status is processing, lets sleep and retry.
[Sun Apr 10 16:46:04 UTC 2022] Retry after: 15

**Comment by Neilpang** [comment]
```
acme.sh --set-default-ca  --server  letsencrypt

```

**Comment by prettyCoders** [comment]
@Neilpang  
root@YB04-A27:~# acme.sh --set-default-ca  --server  letsencrypt
[Mon Apr 11 05:17:47 UTC 2022] Changed default CA to: https://acme-v02.api.letsencrypt.org/directory
root@YB04-A27:~# acme.sh --issue  -d www.starswap.cn   --nginx
[Mon Apr 11 05:17:59 UTC 2022] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Mon Apr 11 05:17:59 UTC 2022] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Mon Apr 11 05:18:01 UTC 2022] Register account Error: {
  "type": "urn:ietf:params:acme:error:invalidEmail",
  "detail": "Error creating new account :: invalid contact domain. Contact emails @example.com are forbidden",
  "status": 400
}
[Mon Apr 11 05:18:01 UTC 2022] Please add '--debug' or '--log' to check more details.
[Mon Apr 11 05:18:01 UTC 2022] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh

**Comment by Neilpang** [comment]
@prettyCoders 
register your account with a real and valid email address:

```
acme.sh  --regsiter-account  --server letsencrypt  -m  your-real-email@domain.com

```
