### ISSUE TITLE
not working after upgrade to Ubuntu 22.04

### ISSUE THREAD

**Issue by iammeken** [acmesh-official/acme.sh#4048]
OpenSSL 1.1.1n  15 Mar 2022
built on: Sat Apr 23 00:11:12 2022 UTC
platform: linux-x86_64
options:  bn(64,64) rc4(8x,int) des(int) idea(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DZLIB -DNDEBUG
OPENSSLDIR: "/usr/local/ssl"
ENGINESDIR: "/usr/local/lib/engines-1.1"
Seeding source: os-specific

DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:118:filename(libproviders.so): libproviders.so: cannot open shared object file: No such file or directory
140666570000192:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:162:
140666570000192:error:0E07506E:configuration file routines:module_load_dso:error loading dso:crypto/conf/conf_mod.c:224:module=providers, path=providers
140666570000192:error:0E076071:configuration file routines:module_run:unknown module name:crypto/conf/conf_mod.c:165:module=providers
[Sat Apr 23 08:03:26 CST 2022] Using CA: https://acme-v02.api.letsencrypt.org/directory
140229979559744:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:118:filename(libproviders.so): libproviders.so: cannot open shared object file: No such file or directory
140229979559744:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:162:

**Comment by joekerna** [comment]
It appears, as if it has something to do with Ubuntu 22.04 upgrading to openssl 3.
If I run `apt list openssl` I get
`openssl/now 3.0.2-0ubuntu1.2 amd64  [Installed,locally]`

However `openssl version` says
`OpenSSL 1.1.1d  10 Sep 2019`

Which version do I have now?

**Comment by joekerna** [comment]
I figured it out:

I have two versions of openssl installed at the same time:
1.1.1d in /usr/local/bin/openssl
3.0.2 in /usr/bin/openssl

After deleting the 1.1.1d version, acme now uses openssl 3 and it's working just fine

**Comment by iammeken** [comment]
Thank you!

I confirm:
rm -r  /usr/local/bin/openssl
will do the trick!

**Comment by Neilpang** [comment]
you don't have to delete the old openssl.  you can specify which version to use:

```
acme.sh  --issue -d example.com    ..............            --openssl-bin  /usr/bin/openssl
```


you only need to specify onece,  acme.sh will remember your choice and use the selected one in future automatically.

**Comment by joekerna** [comment]
Good to know, thanks.

But is there a reason, why there are two versions? Especially such an old one?

**Comment by bektigalan** [comment]
Go to `/etc/ssl/openssl.cnf`
and comment this one too
`#openssl_conf = default_conf`
