### ISSUE TITLE
ssh deploy doesn't work if remote dir nonexistent

### ISSUE THREAD

**Issue by erikahlen** [acmesh-official/acme.sh#4050]
The ssh deploy-hook doesn't throws an error if the specified directory on the remote machine doesn't exist.

Steps to reproduce
------------------
1. issue and install a cert
2. export all needed environment variables to deploy the cert to another machine via ssh deploy-hook
3. try to deploy the cert without creating the destination directory beforehand

Exported variables as stored in config file
------------------
Le_DeployHook='ssh,'
Le_Deploy_ssh_user='acmesh'
Le_Deploy_ssh_server='10.1.0.54'
Le_Deploy_ssh_backup='yes'
Le_Deploy_ssh_backup_path='/home/acmesh/.acme.sh_deploy_backup'
Le_Deploy_ssh_cmd='ssh -i /home/acmesh/.ssh/id_rsa'
Le_Deploy_ssh_certfile='/etc/acme-certificates/bitbucket-test.DOMAIN.de/cert.pem'
Le_Deploy_ssh_keyfile='/etc/acme-certificates/bitbucket-test.DOMAIN.de/privkey.pem'
Le_Deploy_ssh_cafile='/etc/acme-certificates/bitbucket-test.DOMAIN.de/chain.pem'
Le_Deploy_ssh_fullchain='/etc/acme-certificates/bitbucket-test.DOMAIN.de/fullchain.pem'

Command Output
------------------
$ acme.sh --deploy -d bitbucket-test.DOMAIN.de --deploy-hook ssh
[Mon 25 Apr 2022 12:15:49 PM CEST] Deploy certificates to remote server acmesh@10.1.0.54
[Mon 25 Apr 2022 12:15:49 PM CEST] Required commands batched and sent in single call to remote host
[Mon 25 Apr 2022 12:15:49 PM CEST] Backup of old certificate files will be placed in remote directory /home/acmesh/.acme.sh_deploy_backup/bitbucket-test.DOMAIN.de-backup-2022-04-25-10:15:49
[Mon 25 Apr 2022 12:15:49 PM CEST] Backup directories erased after 180 days.
[Mon 25 Apr 2022 12:15:49 PM CEST] will copy private key to remote file /etc/acme-certificates/bitbucket-test.DOMAIN.de/privkey.pem
[Mon 25 Apr 2022 12:15:49 PM CEST] will copy certificate to remote file /etc/acme-certificates/bitbucket-test.DOMAIN.de/cert.pem
[Mon 25 Apr 2022 12:15:49 PM CEST] will copy CA file to remote file /etc/acme-certificates/bitbucket-test.DOMAIN.de/chain.pem
[Mon 25 Apr 2022 12:15:49 PM CEST] will copy fullchain to remote file /etc/acme-certificates/bitbucket-test.DOMAIN.de/fullchain.pem
[Mon 25 Apr 2022 12:15:49 PM CEST] Submitting sequence of commands to remote server by ssh
cp: cannot stat '/etc/acme-certificates/bitbucket-test.DOMAIN.de/privkey.pem': No such file or directory
sh: 1: cannot create /etc/acme-certificates/bitbucket-test.DOMAIN.de/privkey.pem: Directory nonexistent
cp: cannot stat '/etc/acme-certificates/bitbucket-test.DOMAIN.de/cert.pem': No such file or directory
sh: 51: cannot create /etc/acme-certificates/bitbucket-test.DOMAIN.de/cert.pem: Directory nonexistent
cp: cannot stat '/etc/acme-certificates/bitbucket-test.DOMAIN.de/chain.pem': No such file or directory
sh: 93: cannot create /etc/acme-certificates/bitbucket-test.DOMAIN.de/chain.pem: Directory nonexistent
cp: cannot stat '/etc/acme-certificates/bitbucket-test.DOMAIN.de/fullchain.pem': No such file or directory
sh: 163: cannot create /etc/acme-certificates/bitbucket-test.DOMAIN.de/fullchain.pem: Directory nonexistent
[Mon 25 Apr 2022 12:15:49 PM CEST] Error code 2 returned from ssh
[Mon 25 Apr 2022 12:15:49 PM CEST] Error deploy for domain:bitbucket-test.pixsoftware.de
[Mon 25 Apr 2022 12:15:49 PM CEST] Deploy error.

Wanted / expected behaviour
------------------
On the remote machine the directory /etc/acme-certificates exists. 
However, /etc/acme-certificates/bitbucket-test.DOMAIN.de doesn't exist. 
The wanted / expected behaviour would be that acme.sh would create the needed directory if it doesn't exist.
If I create the directory and try to deploy again, everything works fine.

**Comment by Neilpang** [comment]
please create the dir yourself.
