### ISSUE TITLE
dnsapi wiki gone

### ISSUE THREAD

**Issue by trinib** [acmesh-official/acme.sh#4072]
Hi where did this page moved to ? 

https://github.com/acmesh-official/acme.sh/wiki/dnsapi

**Comment by trinib** [comment]
it had info on dns api credentials for various sites 
```
export Dynu_ClientId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
export Dynu_Secret=yyyyyyyyyyyyyyyyyyyyyyyyy
```

**Comment by danb35** [comment]
Seems to have disappeared completely.

**Comment by trinib** [comment]
> Seems to have disappeared completely.

I think this has to be by accident 😪 .. I feel their pain if no backup

**Comment by Neilpang** [comment]
restored.
