### ISSUE TITLE
3.0.4 change breaks reneweal due to wrongly setting to default CA (overriding --server)

### ISSUE THREAD

**Issue by dtugend** [acmesh-official/acme.sh#4073]
## Source of problem

Commit in question: https://github.com/acmesh-official/acme.sh/commit/e6959f093c4e147b4a206f0b5d027ff3d0a59b80
Issue related to commit: https://github.com/acmesh-official/acme.sh/issues/4069

## Problem:

ACME_DIRECTORY is set by the command line option --server:
https://github.com/acmesh-official/acme.sh/blob/e6959f093c4e147b4a206f0b5d027ff3d0a59b80/acme.sh#L7284-L7287
https://github.com/acmesh-official/acme.sh/blob/e6959f093c4e147b4a206f0b5d027ff3d0a59b80/acme.sh#L6993-L7019

Due to the change ACME_DIRECTORY is unset:
https://github.com/acmesh-official/acme.sh/blob/e6959f093c4e147b4a206f0b5d027ff3d0a59b80/acme.sh#L2694-L2699

This causes it to select the default CA instead of the one give by --server:
https://github.com/acmesh-official/acme.sh/blob/e6959f093c4e147b4a206f0b5d027ff3d0a59b80/acme.sh#L2723-L2736

This effectively breaks renewal for use, since ZeroSSL doesn't work if no account email is set.

**Comment by dtugend** [comment]
sorry I was wrong

**Comment by mphilipps** [comment]
hi @dtugend 
Can you please explain why you think you are wrong? I am seeing the same behavior here. Something in the last ~30 days broke and now all Certificates that were created using --server letsencrypt are being renewed as ZeroSSL, which fails due to the missing email account.

Could you please reopen this?

**Comment by Neilpang** [comment]
@mphilipps   sorry, there was a bug in last 30 days that wrongly use zerossl to renew all the certs.  but it was fixed in 3.0.4

>> which fails due to the missing email account.

The simplest solution would be : registering an zerossl account with an email.  then all your cert can be renewed at zerossl.

```
acme.sh --register-account --server zerossl  --email  youemail@example.com

```

**Comment by Neilpang** [comment]
@mphilipps  I'm sorry about the problem. but that was my fault.

another solution would be renew each cert with `--server letsencrypt`:

```
acme.sh  --renew -d  example.com --server letsencrypt
```

you can do this for each cert.

**Comment by mphilipps** [comment]
I just tried 
```
/opt/acme/install/acme.sh \
   --cron \
   --home '/opt/acme/install' \
   --config-home '/opt/acme/config' \
   --server 'letsencrypt'
``` 
with the `--server` line being new, somehow this made it succeed at renewing it as ZeroSSL without an account. I am not sure whether it would prevent changing the CA in first place, but it certainly didn't change it back.

**Comment by Neilpang** [comment]
`--cron` doesn't use `--server`

please use `--renew` for each cert.

**Comment by mphilipps** [comment]
Ok, explicitly calling `--server letsencrypt --renew --force -d` works.

As I see it there are two bugs here.

1) The newly introduced one:  
The default CA when renewing a certificate should be the CA of the old certificate.

2) ` --cron                   Run cron job to renew all the certs.` ignores `--server`. Maybe I could use `--renew-all` instead? What is the difference?

**Comment by Neilpang** [comment]
>> The newly introduced one:
>> The default CA when renewing a certificate should be the CA of the old certificate.

This was fixed in 3.0.4.

>> --cron Run cron job to renew all the certs. ignores --server. Maybe I could use --renew-all instead? What is the difference?

Yes,  I'm fixing the "--renew-all" to support `--server`,   just wait please.

**Comment by dtugend** [comment]
> Can you please explain why you think you are wrong? I am seeing the same behavior here. Something in the last ~30 days broke and now all Certificates that were created using --server letsencrypt are being renewed as ZeroSSL, which fails due to the missing email account.

As Neil explaind, this was actually fixed in 3.0.4 and was an issue in 3.0.3, so I was wrong about 3.0.4 being broken, that's why I closed it.

It affects all certificates that were renewed during the broken 3.0.3 version(s) I think (I am not sure if more versions were effected), but it should not be more than 30 days as Neil said.

I fixed those manually with the -d option after scanning for all with grep in the folder that had ZeroSSL.

**Comment by Neilpang** [comment]
The `--server` option is supported by `--renew-all` command now.

you guys can try the `dev` branch:

```
acme.sh --upgrade -b dev


acme.sh --renew-all  --server  letsencrypt 
```

all the certs will change to use letsencrypt.

**Comment by mphilipps** [comment]
Thank you very much, just one question remaining - what is the difference betwene `--cron` and `--renew-all`?

**Comment by Neilpang** [comment]
@mphilipps   

1. `--cron` is dedicated for cronjob to use,  `renew-all` is for manual use.
2. `--cron` == `--upgrade` + `renewall`  as for now.   There could more differences in future.
3. `--cron` is designed to not accept another  commandline options,  for example: `--server` option is accepted by `renewall` but not accepted by `--cron`.

**Comment by mphilipps** [comment]
Ok.. so I should keep the `--cron` in my cronjob, but use the `renew-all` with `--server` once to manually fix them. I was going to put the `--server` option into the cronjob in the hope that it would prevent a similar issue in the future.

**Comment by Neilpang** [comment]
correct.   the cronjob should always look like:
```
34 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
```

It was just an entry to  "Repeat" the operations (re-issuing the certs) in the cronjob. 

while the other commands like "renew-all/renew/issue" are designed for manual operations.
