### ISSUE TITLE
"-----BEGIN PRIVATE KEY----"  vs "-----BEGIN RSA PRIVATE KEY----"

### ISSUE THREAD

**Issue by stokito** [acmesh-official/acme.sh#4094]
I noticed that Let'sEncrypt generates a `privkey.pem` with `-----BEGIN PRIVATE KEY----` but acme.sh generated `example.com.key` has `-----BEGIN RSA PRIVATE KEY----`. It looks like they both working the same but still I'm afraid that they may behave differently of may have different compatibility.
Could you clarify this?

**Comment by stokito** [comment]
thank you

**Comment by stokito** [comment]
I think that it would be much safer to generate the `BEGIN PRIVATE KEY` same as in the certbot. This may safe from some unexpected problems but also improves inseparability.

**Comment by Neilpang** [comment]
I'd like to keep the lagacy format, because we have to support some very old systems.
