### ISSUE TITLE
Hooks are not being executed in --cron mode.

### ISSUE THREAD

**Issue by MastaG** [acmesh-official/acme.sh#4098]
Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```
I've added the following line to my crontab:
```"/root/.acme.sh"/acme.sh --home "/root/.acme.sh" --cron --pre-hook "systemctl stop nginx"  --renew-hook /usr/local/sbin/certs_media.sh```

As you can see it should stop nginx before attempting to renew.
Then afterwards it runs a script "certs_media.sh" which will re-generate the keystores, put the certs into various places and restart nginx.

However none of this seems to work.
Nginx needs to be stopped first because it listens on port 80.
When I manually stop nginx, the renewal works just fine, only the --renew-hook is also not executed.

Any ideas?

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh/wiki/Using-pre-hook-post-hook-renew-hook-reloadcmd

**Comment by MastaG** [comment]
Thanks, so it seems the hooks are "saved" only when issuing the certificate for the first time.
Then they'll always be executed when running with the --cron flag.
This is a bit of a strange way to do things... instead of just parsing the hook flags everytime you run the script...
But hey.. I can live with it.
