### ISSUE TITLE
Disable notification for staging certificates

### ISSUE THREAD

**Issue by fcolista** [acmesh-official/acme.sh#4099]
Hi!
I've inquired Letsencrypt about disabling notification for staging certificate, as explained here:
https://community.letsencrypt.org/t/fake-email-for-staging-or-disable-staging-expiring-certs-email/178013/2

Since I use acme.sh also in a CI environment, what's the best way to avoid that I got notification in regards of staging certificates that are going to expire?
I see that there's a flag ```--notify-mode``` but I'm unsure if it's what I'm looking for.
Can I use a fake email address, or just not have an email at all?
Thanks.

**Comment by Neilpang** [comment]
The email is sent by letsencrypt CA.  it's not controlled by acme.sh

you can use a fake email.
