### ISSUE TITLE
dns_edgedns ignores saved credentials (does not call _readaccountconf_mutable)

### ISSUE THREAD

**Issue by rfdparker** [acmesh-official/acme.sh#4105]
Following initial certificate issuance with `dns_edgedns`, when Akamai Edge DNS credentials were passed as environment variable, these are saved in `~/.acme.sh/account.conf`. However automatic renewal with `acme.sh --cron` for such certificates fails because `dns_edgedns` does not read its credentials from `~/.acme.sh/account.conf` and complains they are missing.

Steps to reproduce
------------------

1. Issue a certificate using DNS alias mode with `dns_edgedns`
2. Notice `~/.acme.sh/account.conf` contains Akamai Edge DNS credentials (prefixed with `SAVED_`)
3. Wait for automatic renewal with `acme.sh --cron` (or perhaps force it to run early) and notice the renewal fails with messages such as `AKAMAI_ACCESS_TOKEN is missing`

Workaround
-----------------

I viewed another script in `dnsapi/` and saw `dnsapi/dns_azure.sh` calls `_readaccountconf_mutable` to set a default value for each of its credential variables before checking if they're missing.

Replicating in `dnsapi/dns_edgedns.sh` the same logic found in `dnsapi/dns_azure.sh` of using `_readaccountconf_mutable` to read 'default' values (from `~/.acme.sh/account.conf`) seems to resolve the issue. The below diff is against `v3.0.4`.

```diff
diff -ruN a/dnsapi/dns_edgedns.sh b/dnsapi/dns_edgedns.sh
--- a/dnsapi/dns_edgedns.sh     2022-05-06 11:06:37.000000000 +0100
+++ b/dnsapi/dns_edgedns.sh     2022-05-26 12:13:47.580941059 +0100
@@ -176,6 +176,7 @@
   _debug "GettingEdge DNS credentials"
   _log "$(printf "ACME DNSAPI Edge DNS version %s" ${ACME_EDGEDNS_VERSION})"
   args_missing=0
+  AKAMAI_ACCESS_TOKEN="${AKAMAI_ACCESS_TOKEN:-$(_readaccountconf_mutable AKAMAI_ACCESS_TOKEN)}"
   if [ -z "$AKAMAI_ACCESS_TOKEN" ]; then
     AKAMAI_ACCESS_TOKEN=""
     AKAMAI_CLIENT_TOKEN=""
@@ -184,6 +185,7 @@
     _err "AKAMAI_ACCESS_TOKEN is missing"
     args_missing=1
   fi
+  AKAMAI_CLIENT_TOKEN="${AKAMAI_CLIENT_TOKEN:-$(_readaccountconf_mutable AKAMAI_CLIENT_TOKEN)}"
   if [ -z "$AKAMAI_CLIENT_TOKEN" ]; then
     AKAMAI_ACCESS_TOKEN=""
     AKAMAI_CLIENT_TOKEN=""
@@ -192,6 +194,7 @@
     _err "AKAMAI_CLIENT_TOKEN is missing"
     args_missing=1
   fi
+  AKAMAI_HOST="${AKAMAI_HOST:-$(_readaccountconf_mutable AKAMAI_HOST)}"
   if [ -z "$AKAMAI_HOST" ]; then
     AKAMAI_ACCESS_TOKEN=""
     AKAMAI_CLIENT_TOKEN=""
@@ -200,6 +203,7 @@
     _err "AKAMAI_HOST is missing"
     args_missing=1
   fi
+  AKAMAI_CLIENT_SECRET="${AKAMAI_CLIENT_SECRET:-$(_readaccountconf_mutable AKAMAI_CLIENT_SECRET)}"
   if [ -z "$AKAMAI_CLIENT_SECRET" ]; then
     AKAMAI_ACCESS_TOKEN=""
     AKAMAI_CLIENT_TOKEN=""
```

**Comment by Neilpang** [comment]
fixed, thanks.
