### ISSUE TITLE
acme.sh does not respect --days when --valid-to is set

### ISSUE THREAD

**Issue by jongcs** [acmesh-official/acme.sh#4113]
I'm trying to use --days to make acme.sh renews a certificate that --valid-to is been set before it ever expires.
Here is my command:
`acme.sh --issue -d example.com --valid-to "+7d" --days 5 --dns dns_cf --server google`

This certificate was issued on 2022-05-30T11:02:31Z.
But the actual renew time set by acme.sh is today +7d, not today +5d.
<pre>
[Mon 30 May 2022 10:59:42 PM CST] Renew: 'example.com'
[Mon 30 May 2022 10:59:42 PM CST] Renew to Le_API=https://dv.acme-v02.api.pki.goog/directory
[Mon 30 May 2022 10:59:42 PM CST] Skip, Next renewal time is: 2022-06-06T11:00:48Z
[Mon 30 May 2022 10:59:42 PM CST] Add '--force' to force to renew.
<pre>

**Comment by Neilpang** [comment]
don't use `--days` the same time with `--valid-to`.  just  use one of them.

**Comment by numo68** [comment]
@Neilpang yes, I know that page. My question is related to the "If the lifetime is longer than one day, it will renew at *one day* before". Like the original poster I'd like to e.g. specify +30d validity, renewing 7 days before expiration. One day is too short, one hiccup anywhere and the certificate expires. Is there any way to specify both intervals? Thanks
