### ISSUE TITLE
删除后如何解除别名？

### ISSUE THREAD

**Issue by pipidaxian** [acmesh-official/acme.sh#4125]
我不需要acme了，于是我删除了/root/.acme.sh文件，但是此前通过alias acme.sh=~/.acme.sh/acme.sh注册的别名还在。每次sudo -i的时候都会提示-bash: /root/.acme.sh/acme.sh.env: No such file or directory
请问可以如何解除别名，让这个提示消失？

**Comment by Neilpang** [comment]
重新安装一遍. 
然后`acme.sh --uninstall`

然后在 删除 文件夹 /root/.acme.sh
