### ISSUE TITLE
Quad9 DNS is not resolving get.acme.sh

### ISSUE THREAD

**Issue by solracsf** [acmesh-official/acme.sh#4126]
```
~# dig A get.acme.sh @9.9.9.9

; <<>> DiG 9.16.1-Ubuntu <<>> A get.acme.sh @9.9.9.9
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 46737
;; flags: qr rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;get.acme.sh.                   IN      A

;; Query time: 0 msec
;; SERVER: 9.9.9.9#53(9.9.9.9)
;; WHEN: Sun Jun 05 09:18:32 CEST 2022
;; MSG SIZE  rcvd: 40
```

**Comment by solracsf** [comment]
I've contacted Quad9.

>Brian Wall (Quad9) 
>Jun 6, 2022, 02:11 UTC 
>Hello,
> 
>Thanks for contacting Quad9 support.
>
>This appears to be a false positive and will be removed from the blocklist of all global servers within 3 hours.
>
>Best regards,
>Brian

**Comment by Neilpang** [comment]
Thanks, but just curious, why did they block this domain?  Is there are rule?

**Comment by solracsf** [comment]
No idea. Feel free to reach them at https://www.quad9.net/support/contact

**Comment by Neilpang** [comment]
@jtabox  No, I didn't contact them ever.

**Comment by Neilpang** [comment]
I just sent a message to them, let's wait

**Comment by Neilpang** [comment]
they replied me quickly:

![image](https://github.com/acmesh-official/acme.sh/assets/8305679/ca1783db-c609-4239-92ab-997e6f152c30)

**Comment by Neilpang** [comment]
@jtabox  No,  I don't think so.  acme.sh was always pointing to  github since I ever registered this domain since 2016.

**Comment by Neilpang** [comment]
@jtabox   the ip address belongs to cloudflare, it seems that they marked cloudflare ipaddress by mistake.
