### ISSUE TITLE
I meet a problem when I use --issue --test

### ISSUE THREAD

**Issue by bruce2k** [acmesh-official/acme.sh#4127]
Hope you can help, it's probably something I am doing wrong :-)

I used install the CA key correctly 3 month ago, but recently I  met an error when i access my website the CA is expired. so I reinstall the website use the same domain name . when I execute the command "acme.sh --issue --server letsencrypt --test -d www.xxx.com -w /home/xxx/www/webpage --keylength ec-256"  I met a issue and install failed. the log as below.

Sat Jun  4 14:00:32 UTC 2022] Running cmd: issue
[Sat Jun  4 14:00:32 UTC 2022] _main_domain='www.xxxxx.com'
[Sat Jun  4 14:00:32 UTC 2022] _alt_domains='no'
[Sat Jun  4 14:00:32 UTC 2022] Using config home:/home/xxxxx/.acme.sh
[Sat Jun  4 14:00:32 UTC 2022] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Sat Jun  4 14:00:32 UTC 2022] DOMAIN_PATH='/home/xxxxx/.acme.sh/www.xxxxx.com_ecc'
[Sat Jun  4 14:00:32 UTC 2022] Le_NextRenewTime
[Sat Jun  4 14:00:32 UTC 2022] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Sat Jun  4 14:00:32 UTC 2022] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Sat Jun  4 14:00:32 UTC 2022] GET
[Sat Jun  4 14:00:32 UTC 2022] url='https://acme-v02.api.letsencrypt.org/directory'
[Sat Jun  4 14:00:32 UTC 2022] timeout=
[Sat Jun  4 14:00:32 UTC 2022] _CURL='curl --silent --dump-header /home/xxxxx/.acme.sh/http.header  -L '
[Sat Jun  4 14:00:33 UTC 2022] ret='0'
[Sat Jun  4 14:00:33 UTC 2022] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Sat Jun  4 14:00:33 UTC 2022] ACME_NEW_AUTHZ
[Sat Jun  4 14:00:33 UTC 2022] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Sat Jun  4 14:00:33 UTC 2022] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Sat Jun  4 14:00:33 UTC 2022] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Sat Jun  4 14:00:33 UTC 2022] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Sat Jun  4 14:00:33 UTC 2022] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Sat Jun  4 14:00:33 UTC 2022] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sat Jun  4 14:00:33 UTC 2022] _on_before_issue
[Sat Jun  4 14:00:33 UTC 2022] _chk_main_domain='www.xxxxx.com'
[Sat Jun  4 14:00:33 UTC 2022] _chk_alt_domains
[Sat Jun  4 14:00:33 UTC 2022] Le_LocalAddress
[Sat Jun  4 14:00:33 UTC 2022] d='www.xxxxx.com'
[Sat Jun  4 14:00:33 UTC 2022] Check for domain='www.xxxxx.com'
[Sat Jun  4 14:00:33 UTC 2022] _currentRoot='/home/xxxxx/www/webpage'
[Sat Jun  4 14:00:33 UTC 2022] d
[Sat Jun  4 14:00:33 UTC 2022] _saved_account_key_hash is not changed, skip register account.
[Sat Jun  4 14:00:33 UTC 2022] Read key length:ec-256
[Sat Jun  4 14:00:33 UTC 2022] _createcsr
[Sat Jun  4 14:00:33 UTC 2022] Single domain='www.xxxxx.com'
[Sat Jun  4 14:00:33 UTC 2022] Getting domain auth token for each domain
[Sat Jun  4 14:00:33 UTC 2022] d
[Sat Jun  4 14:00:33 UTC 2022] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Sat Jun  4 14:00:33 UTC 2022] payload='{"identifiers": [{"type":"dns","value":"www.xxxxx.com"}]}'
[Sat Jun  4 14:00:33 UTC 2022] RSA key
[Sat Jun  4 14:00:33 UTC 2022] HEAD
[Sat Jun  4 14:00:33 UTC 2022] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Sat Jun  4 14:00:33 UTC 2022] _CURL='curl --silent --dump-header /home/xxxxx/.acme.sh/http.header  -L  -I  '
[Sat Jun  4 14:00:33 UTC 2022] _ret='0'
[Sat Jun  4 14:00:33 UTC 2022] POST
[Sat Jun  4 14:00:33 UTC 2022] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Sat Jun  4 14:00:33 UTC 2022] _CURL='curl --silent --dump-header /home/xxxxx/.acme.sh/http.header  -L '
[Sat Jun  4 14:00:33 UTC 2022] _ret='0'
[Sat Jun  4 14:00:33 UTC 2022] code='201'
[Sat Jun  4 14:00:33 UTC 2022] Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/573881086/94742820726'
[Sat Jun  4 14:00:33 UTC 2022] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/573881086/94742820726'
[Sat Jun  4 14:00:33 UTC 2022] url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/116017898196'
[Sat Jun  4 14:00:33 UTC 2022] payload
[Sat Jun  4 14:00:33 UTC 2022] POST
[Sat Jun  4 14:00:33 UTC 2022] _post_url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/116017898196'
[Sat Jun  4 14:00:33 UTC 2022] _CURL='curl --silent --dump-header /home/xxxxx/.acme.sh/http.header  -L '
[Sat Jun  4 14:00:34 UTC 2022] _ret='0'
[Sat Jun  4 14:00:34 UTC 2022] code='200'
[Sat Jun  4 14:00:34 UTC 2022] d='www.xxxxx.com'
[Sat Jun  4 14:00:34 UTC 2022] Getting webroot for domain='www.xxxxx.com'
[Sat Jun  4 14:00:34 UTC 2022] _w='/home/xxxxx/www/webpage'
[Sat Jun  4 14:00:34 UTC 2022] _currentRoot='/home/xxxxx/www/webpage'
[Sat Jun  4 14:00:34 UTC 2022] entry='"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/116017898196/kX_vfg","token":"JpYWwya3dzjnQxjKhfzL4dY2zPdjsdGc1c69kwBNo>
[Sat Jun  4 14:00:34 UTC 2022] token='JpYWwya3dzjnQxjKhfzL4dY2zPdjsdGc1c69kwBNoxA'
[Sat Jun  4 14:00:34 UTC 2022] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/116017898196/kX_vfg'
[Sat Jun  4 14:00:34 UTC 2022] keyauthorization='JpYWwya3dzjnQxjKhfzL4dY2zPdjsdGc1c69kwBNoxA.6lSX0jCqVhyBWHXebvNayJ21IIbT0bIReHkj83iQYEY'
[Sat Jun  4 14:00:34 UTC 2022] dvlist='www.xxxxx.com#JpYWwya3dzjnQxjKhfzL4dY2zPdjsdGc1c69kwBNoxA.6lSX0jCqVhyBWHXebvNayJ21IIbT0bIReHkj83iQYEY#https://acme-v02.api.letsencrypt.org/acme/chall-v3/116017898>
[Sat Jun  4 14:00:34 UTC 2022] d
[Sat Jun  4 14:00:34 UTC 2022] vlist='www.xxxxx.com#JpYWwya3dzjnQxjKhfzL4dY2zPdjsdGc1c69kwBNoxA.6lSX0jCqVhyBWHXebvNayJ21IIbT0bIReHkj83iQYEY#https://acme-v02.api.letsencrypt.org/acme/chall-v3/1160178981>
[Sat Jun  4 14:00:34 UTC 2022] d='www.xxxxx.com'
[Sat Jun  4 14:00:34 UTC 2022] ok, let's start to verify
[Sat Jun  4 14:00:34 UTC 2022] Verifying: www.xxxxx.com
[Sat Jun  4 14:00:34 UTC 2022] d='www.xxxxx.com'
[Sat Jun  4 14:00:34 UTC 2022] keyauthorization='JpYWwya3dzjnQxjKhfzL4dY2zPdjsdGc1c69kwBNoxA.6lSX0jCqVhyBWHXebvNayJ21IIbT0bIReHkj83iQYEY'
[Sat Jun  4 14:00:34 UTC 2022] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/116017898196/kX_vfg'
[Sat Jun  4 14:00:34 UTC 2022] _currentRoot='/home/xxxxx/www/webpage'
[Sat Jun  4 14:00:34 UTC 2022] wellknown_path='/home/xxxxx/www/webpage/.well-known/acme-challenge'
[Sat Jun  4 14:00:34 UTC 2022] writing token:JpYWwya3dzjnQxjKhfzL4dY2zPdjsdGc1c69kwBNoxA to /home/xxxxx/www/webpage/.well-known/acme-challenge/JpYWwya3dzjnQxjKhfzL4dY2zPdjsdGc1c69kwBNoxA
[Sat Jun  4 14:00:34 UTC 2022] Changing owner/group of .well-known to xxxxx:xxxxx
[Sat Jun  4 14:00:34 UTC 2022] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/116017898196/kX_vfg'
[Sat Jun  4 14:00:34 UTC 2022] payload='{}'
[Sat Jun  4 14:00:34 UTC 2022] POST
[Sat Jun  4 14:00:34 UTC 2022] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/116017898196/kX_vfg'
[Sat Jun  4 14:00:34 UTC 2022] _CURL='curl --silent --dump-header /home/xxxxx/.acme.sh/http.header  -L '
[Sat Jun  4 14:00:34 UTC 2022] _ret='0'
[Sat Jun  4 14:00:34 UTC 2022] code='200'
[Sat Jun  4 14:00:34 UTC 2022] trigger validation code: 200
[Sat Jun  4 14:00:34 UTC 2022] Pending, The CA is processing your order, please just wait. (1/30)
[Sat Jun  4 14:00:34 UTC 2022] sleep 2 secs to verify again
[Sat Jun  4 14:00:37 UTC 2022] checking
[Sat Jun  4 14:00:37 UTC 2022] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/116017898196/kX_vfg'
[Sat Jun  4 14:00:37 UTC 2022] payload
[Sat Jun  4 14:00:37 UTC 2022] POST
[Sat Jun  4 14:00:37 UTC 2022] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/116017898196/kX_vfg'
[Sat Jun  4 14:00:37 UTC 2022] _CURL='curl --silent --dump-header /home/xxxxx/.acme.sh/http.header  -L '
[Sat Jun  4 14:00:37 UTC 2022] _ret='0'
[Sat Jun  4 14:00:37 UTC 2022] code='200'
[Sat Jun  4 14:00:37 UTC 2022] www.xxxxx.com:Verify error:184.169.221.97: Invalid response from http://www.xxxxx.com/.well-known/acme-challenge/JpYWwya3dzjnQxjKhfzL4dY2zPdjsdGc1c69kwBNoxA: 403
[Sat Jun  4 14:00:33 UTC 2022] payload
[Sat Jun  4 14:00:33 UTC 2022] POST
[Sat Jun  4 14:00:33 UTC 2022] _post_url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/116017898196'
[Sat Jun  4 14:00:33 UTC 2022] _CURL='curl --silent --dump-header /home/xxxxx/.acme.sh/http.header  -L '
[Sat Jun  4 14:00:34 UTC 2022] _ret='0'
[Sat Jun  4 14:00:34 UTC 2022] code='200'
[Sat Jun  4 14:00:34 UTC 2022] d='www.xxxxx.com'
[Sat Jun  4 14:00:34 UTC 2022] Getting webroot for domain='www.xxxxx.com'
[Sat Jun  4 14:00:34 UTC 2022] _w='/home/xxxxx/www/webpage'
[Sat Jun  4 14:00:34 UTC 2022] _currentRoot='/home/xxxxx/www/webpage'
[Sat Jun  4 14:00:34 UTC 2022] entry='"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/116017898196/kX_vfg","token":"JpYWwya3dzjnQxjKhfzL4dY2zPdjsdGc1c69kwBNo>
[Sat Jun  4 14:00:34 UTC 2022] token='JpYWwya3dzjnQxjKhfzL4dY2zPdjsdGc1c69kwBNoxA'
[Sat Jun  4 14:00:34 UTC 2022] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/116017898196/kX_vfg'
[Sat Jun  4 14:00:34 UTC 2022] keyauthorization='JpYWwya3dzjnQxjKhfzL4dY2zPdjsdGc1c69kwBNoxA.6lSX0jCqVhyBWHXebvNayJ21IIbT0bIReHkj83iQYEY'
[Sat Jun  4 14:00:34 UTC 2022] dvlist='www.xxxxx.com#JpYWwya3dzjnQxjKhfzL4dY2zPdjsdGc1c69kwBNoxA.6lSX0jCqVhyBWHXebvNayJ21IIbT0bIReHkj83iQYEY#https://acme-v02.api.letsencrypt.org/acme/chall-v3/116017898>
[Sat Jun  4 14:00:34 UTC 2022] d
[Sat Jun  4 14:00:34 UTC 2022] vlist='www.xxxxx.com#JpYWwya3dzjnQxjKhfzL4dY2zPdjsdGc1c69kwBNoxA.6lSX0jCqVhyBWHXebvNayJ21IIbT0bIReHkj83iQYEY#https://acme-v02.api.letsencrypt.org/acme/chall-v3/1160178981>
[Sat Jun  4 14:00:34 UTC 2022] d='www.xxxxx.com'
[Sat Jun  4 14:00:34 UTC 2022] ok, let's start to verify
[Sat Jun  4 14:00:34 UTC 2022] Verifying: www.xxxxx.com
[Sat Jun  4 14:00:34 UTC 2022] d='www.xxxxx.com'
[Sat Jun  4 14:00:34 UTC 2022] keyauthorization='JpYWwya3dzjnQxjKhfzL4dY2zPdjsdGc1c69kwBNoxA.6lSX0jCqVhyBWHXebvNayJ21IIbT0bIReHkj83iQYEY'
[Sat Jun  4 14:00:34 UTC 2022] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/116017898196/kX_vfg'
[Sat Jun  4 14:00:34 UTC 2022] _currentRoot='/home/xxxxx/www/webpage'
[Sat Jun  4 14:00:34 UTC 2022] wellknown_path='/home/xxxxx/www/webpage/.well-known/acme-challenge'
[Sat Jun  4 14:00:34 UTC 2022] writing token:JpYWwya3dzjnQxjKhfzL4dY2zPdjsdGc1c69kwBNoxA to /home/xxxxx/www/webpage/.well-known/acme-challenge/JpYWwya3dzjnQxjKhfzL4dY2zPdjsdGc1c69kwBNoxA
[Sat Jun  4 14:00:34 UTC 2022] Changing owner/group of .well-known to xxxxx:xxxxx
[Sat Jun  4 14:00:34 UTC 2022] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/116017898196/kX_vfg'
[Sat Jun  4 14:00:34 UTC 2022] payload='{}'
[Sat Jun  4 14:00:34 UTC 2022] POST
[Sat Jun  4 14:00:34 UTC 2022] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/116017898196/kX_vfg'
[Sat Jun  4 14:00:34 UTC 2022] _CURL='curl --silent --dump-header /home/xxxxx/.acme.sh/http.header  -L '
[Sat Jun  4 14:00:34 UTC 2022] _ret='0'
[Sat Jun  4 14:00:34 UTC 2022] code='200'
[Sat Jun  4 14:00:34 UTC 2022] trigger validation code: 200
[Sat Jun  4 14:00:34 UTC 2022] Pending, The CA is processing your order, please just wait. (1/30)
[Sat Jun  4 14:00:34 UTC 2022] sleep 2 secs to verify again
[Sat Jun  4 14:00:37 UTC 2022] checking
[Sat Jun  4 14:00:37 UTC 2022] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/116017898196/kX_vfg'
[Sat Jun  4 14:00:37 UTC 2022] payload
[Sat Jun  4 14:00:37 UTC 2022] POST
[Sat Jun  4 14:00:37 UTC 2022] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/116017898196/kX_vfg'
[Sat Jun  4 14:00:37 UTC 2022] _CURL='curl --silent --dump-header /home/xxxxx/.acme.sh/http.header  -L '
[Sat Jun  4 14:00:37 UTC 2022] _ret='0'
[Sat Jun  4 14:00:37 UTC 2022] code='200'
[Sat Jun  4 14:00:37 UTC 2022] www.xxxxx.com:Verify error:184.169.221.97: Invalid response from http://www.xxxxx.com/.well-known/acme-challenge/JpYWwya3dzjnQxjKhfzL4dY2zPdjsdGc1c69kwBNoxA: 403
[Sat Jun  4 14:00:37 UTC 2022] pid
[Sat Jun  4 14:00:37 UTC 2022] No need to restore nginx, skip.
[Sat Jun  4 14:00:37 UTC 2022] _clearupdns
[Sat Jun  4 14:00:37 UTC 2022] dns_entries
[Sat Jun  4 14:00:37 UTC 2022] skip dns.
[Sat Jun  4 14:00:37 UTC 2022] _on_issue_err
[Sat Jun  4 14:00:37 UTC 2022] Please check log file for more details: /home/xxxxx/.acme.sh/acme.sh.log
[Sat Jun  4 14:00:37 UTC 2022] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/116017898196/kX_vfg'
[Sat Jun  4 14:00:37 UTC 2022] payload='{}'
[Sat Jun  4 14:00:37 UTC 2022] POST
[Sat Jun  4 14:00:37 UTC 2022] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/116017898196/kX_vfg'
[Sat Jun  4 14:00:37 UTC 2022] _CURL='curl --silent --dump-header /home/xxxxx/.acme.sh/http.header  -L '
[Sat Jun  4 14:00:38 UTC 2022] _ret='0'
[Sat Jun  4 14:00:38 UTC 2022] code='400'

Thanks in advance.

**Comment by ShevT** [comment]
+1

**Comment by Neilpang** [comment]
The letsencrypt CA uses an expired root CA by default.
please issue the cert again with `preferred-chain`:

```
acme.sh --issue -d example.com     ................      --preferred-chain  isrg   
```
