### ISSUE TITLE
ZeroSSL timeout issue

### ISSUE THREAD

**Issue by ShepardEG** [acmesh-official/acme.sh#4132]
ZeroSSL again timeout. When they going to fix!?
Steps to reproduce
------------------
Issue domain with default settings
Debug log
-----------------

```
<!--
[Wed 08 Jun 2022 06:27:36 ] Processing, The CA is processing your order, please just wait. (28/30)
[Wed 08 Jun 2022 06:27:43 ] Processing, The CA is processing your order, please just wait. (29/30)
[Wed 08 Jun 2022 06:27:46 ] www.domain.com:Timeout
[Wed 08 Jun 2022 06:27:46 ] Please add '--debug' or '--log' to check more details.
-->

```

**Comment by Neilpang** [comment]
sometimes  it's  just an error of your configuration, but they just report "timeout" error. It's not an accurate error message.

check your configuration with letsencrypt testing server, they will tell you the correct error message:

```
acme.sh --issue   --test  -d example.com  ......
```

**Comment by ShepardEG** [comment]
I changed my server using --server letsencrypt and my domain certificate was correctly issued. Timeout with ZeroSSL and its happend already on my 4 servers @Neilpang

**Comment by ShepardEG** [comment]
I changed my server using --server letsencrypt and my domain certificate was correctly issued. I tried your test command and worked too. 

Here part of debug log for ZeroSSL. 

[Чт июн  9 14:06:11 2022] Sign error, wrong status
[Чт июн  9 14:06:11 2022] {"status":"invalid","expires":"2022-09-07T11:05:32Z","identifiers":[{"type":"dns","value":"test.domain.com"}],"authorizations":["https://acme.zerossl.com/v2/DV90/authz/g2E2ydadsdsa7J-Qtd-dYbQ"],"finalize":"https://acme.zerossl.com/v2/DV90/order/3vl7VadsasddasdsaBsZujSA/finalize"}
