### ISSUE TITLE
Feature request: Make live directory readable by ssl-cert group and symlink certs into /etc/ssl/private/

### ISSUE THREAD

**Issue by stokito** [acmesh-official/acme.sh#4133]
It would be great to do is to have the same dirs structure as Let'sEncrypt certbot produces. So that a path to a cert will be the same and users may change certbot/acme without re-configuring all programs.
Ideally certs should be just stored somewhere like /etc/ssl/ and a webserver may itself find it by domain.

I developing a homepage app for students and inexperienced users. And each additional configuration step is a pain for them and me to explain.
Currently I'll have to write two instructions for acme and certbot which will differs only in a path.

Please see my proposition here
https://github.com/certbot/certbot/issues/1425#issuecomment-1150116062

**Comment by Neilpang** [comment]
you can manually change the  permissions of the folder or the key/cert files.  it can belong to any group.
When acme.sh renews the certs,  the permisions will be kept as-is.

**Comment by stokito** [comment]
Thank you @Neilpang for the quick answer. The problem is that my app can't change the permissions and most of it's users can't ether simply because they aren't so experienced. Ideally I just wont them to install the app's package from UI and the acme.sh and everything can work automatically.
The app is working with it's own non root user and it can't access certs and change their permissions.
In the same time the issue is also about a single folder to store certs `/etc/ssl/private` that would be the same for other ACME clients i.e. certbot.
