### ISSUE TITLE
如何自动在更新证书前关闭占用端口的docker应用？

### ISSUE THREAD

**Issue by pipidaxian** [acmesh-official/acme.sh#4136]
由于80端口被一个docker应用占用（假如名字叫A），acme无法完成在crontab里的自动更新证书。
需要在crontab里加上什么，或者需要做别的什么，才能在更新证书前自动docker stop我的A应用，在新证书签发后再docker start该应用？
谢谢。

**Comment by Neilpang** [comment]
建议该用 dns api 模式, 活着 dns 别名模式 申请证书.  
https://github.com/acmesh-official/acme.sh/wiki/dnsapi
https://github.com/acmesh-official/acme.sh/wiki/DNS-alias-mode

然后再用 deploy docker hook 部署到你的容器里面:
https://github.com/acmesh-official/acme.sh/wiki/deploy-to-docker-containers

这样可以确保你的服务无中断.



如果你的 web 的 根目录已经 映射到主机上, 也可以使用 webroot 模式申请证书,  然后再部署.





另一个懒人方法是, 前端替换为我的 letsproxy 容器, 做反向代理, 可以自动处理证书问题.

https://github.com/Neilpang/letsproxy



最后, 非常不建议的方式, 如果你非要在申请证书之前, 和之后做点什么, 可以用 prehook 和posthook

https://github.com/acmesh-official/acme.sh/wiki/Using-pre-hook-post-hook-renew-hook-reloadcmd
