### ISSUE TITLE
申请续期之后浏览器浏览还显示之前的日期

### ISSUE THREAD

**Issue by SeongBrave** [acmesh-official/acme.sh#4141]
通过acme.sh --info -d *.com 查看证书信息，显示Le_NextRenewTimeStr 日期已经更新了，并且也重启了Nginx服务，但是浏览器访问还是显示之前的就日期，不知道我这边是哪块操作错了吗？

**Comment by Neilpang** [comment]
看一下 nginx 配置里面指向的 证书文件位置.

**Comment by hanyuwei70** [comment]
浏览器会保持之前的TLS连接，重启nginx并不会终止之前的TLS连接，所以浏览器F5还会显示之前的证书。完全关闭浏览器之后重试。
