### ISSUE TITLE
Clarification how the cmd in `--reloadcmd` is executed

### ISSUE THREAD

**Issue by timonson** [acmesh-official/acme.sh#4144]
My specified command with the `--reloadcmd` flag can't find an environment variable set by the linux user which it otherwise would find if I ran it as a single command in the shell. Is this intentional behavior and why? Is the command run in a `sudo su` environment?
Thanks!

```
acme.sh --install-cert -d example.com \
--cert-file      /path/to/certfile/in/apache/cert.pem  \
--key-file       /path/to/keyfile/in/apache/key.pem  \
--fullchain-file /path/to/fullchain/certfile/apache/fullchain.pem \
--reloadcmd     "custom command"
```

**Comment by Neilpang** [comment]
it depends on where the env variables are defined.
don't rely on the env  variables, unless you are an expert.

run your command in a  shell script, and  make the script as the `--reloadcmd`.

>> Is the command run in a sudo su environment?

No.
