### ISSUE TITLE
Incorrectly identifies running as root user installation

### ISSUE THREAD

**Issue by mangelozzi** [acmesh-official/acme.sh#4154]
Acme.sh version: v3.0.5
Debian bullseye

There are similar issues, but most have been closed.

I have an installation script that runs as sudo. It also sets up acme.sh.
In order for the script to install acme.sh not as root, it uses sudo to run a command as a different user, e.g.:
```
sudo -u michael ls -la
```
to execute the command `ls -la` as user `michael`

However acme.sh thinks I am running as root:
```
$ sudo -u michael acme.sh --issue -d example.com -w /var/www/example.com/public
It seems that you are using sudo, please read this link first:
https://github.com/acmesh-official/acme.sh/wiki/sudo
```

**Comment by Neilpang** [comment]
It seems that you are using sudo, please read this link first:
https://github.com/acmesh-official/acme.sh/wiki/sudo
