### ISSUE TITLE
No documentation on what the recommended 'Webroot mode' is

### ISSUE THREAD

**Issue by mangelozzi** [acmesh-official/acme.sh#4155]
The documents often refer to `webroot mode`, but `webroot mode` is never explained.

E.g. here:
https://github.com/acmesh-official/acme.sh#supported-modes

Is webroot mode when say you are using say Nginx, and you allow acme.sh to create dirs/files within your root dir, so the acme challenge can see them (Nginx serves up the files)?

I see there is a `--webroot` flag for the `issue` command, is this used in conjuction with your existing webserver? Or does it create its own webserver?

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh/wiki/How-to-issue-a-cert
