### ISSUE TITLE
When installing acme, alias acme.sh may not be executed successfully

### ISSUE THREAD

**Issue by himonster1** [acmesh-official/acme.sh#4162]
When installing acme, the step `alias acme.sh=~/.acme.sh/acme.sh` will not work, you need to execute alias `acme.sh=~/.acme.sh/acme.sh` manually once after installation to use acme.sh directly instead of `~/.acme.sh/acme. sh` to request a certificate

**Comment by Neilpang** [comment]
what is your OS version and bash version?

**Comment by Neilpang** [comment]
检查一下你的 `.bashrc`  和 `.bash_profile`  文件.
