### ISSUE TITLE
ZeroSSL (acme.sh --renew-all) Creates another certificate?

### ISSUE THREAD

**Issue by PaweltK** [acmesh-official/acme.sh#4167]
Hello,

I changed the CA server to ZeroSSL. Recently, information about an expiring certificate has started to come to me.
I have checked the certificates on the servers and they are OK.

I did "acme.sh --renew-all --force" and a new certificate for the same domain appeared in the zerossl console.
It looks like this: (the same domain is marked yellow)
![2022-07-03 215541](https://user-images.githubusercontent.com/50871237/177055430-fa7fa832-99d0-4f94-95b3-b68863040982.png)

I don't know if it's a mistake or if it's supposed to be like that.
Shouldn't a new certificate be added, and the old one revoked?

**Comment by Neilpang** [comment]
the old one is not revoked by default.
you can revoke it by `acme.sh --revoke ...... ` first before you renew the cert.
