### ISSUE TITLE
Certificate RSA 2048 bits (SHA256withRSA) instead of RSA 4096 bits (SHA256withRSA)

### ISSUE THREAD

**Issue by iz8mbw** [acmesh-official/acme.sh#4169]
Hello.
using latest version of acme.sh and I use it in order to generate Let's Encrypt Certificate using a CSR provided by me.
I have noticed that acme.sh receive/generate a RSA 2048 bits Certificate also if I ask for a RSA 4096 bits.

This is the command I execute:

`acme.sh --accountkeylength 4096 --email MyEmail --signcsr --csr /root/.acme.sh/files/myCSR.csr --nginx -d MyDomain -d '*.MyDomain' --yes-I-know-dns-manual-mode-enough-go-ahead-please --dns dns_cf --renew --keylength 4096 --force`

I used the command here https://gist.github.com/Hakky54/b30418b25215ad7d18f978bc0b448d81 in order to generate RSA (4096 bits) PrivateKey and after to generate CSR.

acme command is executed Successfully but the Certificate issued is RSA 2048 bits (SHA256withRSA) and not RSA 4096 bits (SHA256withRSA) as I requested, it's confirmed by https://www.ssllabs.com/ website.

Where I wrong?
Thanks.

**Comment by Neilpang** [comment]
1. don't use `--signcsr --csr /root/.acme.sh/files/myCSR.csr`.   it will use the specified csr, instead of generating a new csr with 4096bits
2. The `--nginx` mode can not can not work with wildcard domain `*.Mydomain.com`

**Comment by iz8mbw** [comment]
Hello @Neilpang 
Any news about this issue?
Just for your info, on another Linux machine with the old `certbot-auto` I was able to obtain RSA 4096 Certificates from Let's Encrypt via a CSR generated by me, this is the output from https://www.ssllabs.com/
![image](https://user-images.githubusercontent.com/3474082/177938838-14cffe0e-8c99-4e8c-ba60-408b6b6bded4.png)

And the way to generate CSR is the same that I'm trying to use with `acme.sh --signcsr --csr /root/.acme.sh/files/myCSR.csr` so I suppose there is some on acme.sh that should be addressed.
Many thanks for your support!
