### ISSUE TITLE
upgrade 和 auto-upgrade 会影响 自定义的 deploy 和 notify 吗？

### ISSUE THREAD

**Issue by amaoo** [acmesh-official/acme.sh#4177]
您好，冒昧打扰。
我在 acme.sh 的安装目录中的 deploy 和 notify 加了一些自定义文件。
请问 upgrade  和 auto-upgrade 时，会移除 我添加的文件吗？
传给 deploy  和 notify 的参数会变更吗？

**Comment by amaoo** [comment]
@Neilpang 
感谢您的回复。
另外问下 ，关于这个 [pull request](https://github.com/acmesh-official/acme.sh/pull/1866)
您是有其他什么考虑吗？

**Comment by Neilpang** [comment]
不需要 reopen.

只是这个变动比较大,  但是目前看来收益却不是很相当.
而且目前 pr 的code 有冲突. 所以比较为难.

**Comment by liu-zhao-ssoft** [comment]
了解了。

**Comment by amaoo** [comment]
@Neilpang 
您好，如果我使用了 **zerossl** 的订阅计划。
那我如何通过 **acme.sh** 申请一年和通配符的证书呢？

还有 除了 **export** ，还有没有其他往 **deploy** 传参数的方法呢？

**Comment by amaoo** [comment]
您好 ，除了 export ，还有没有其他往 deploy 传参数的方法吗？
在zerossl 注册账号之后，EAB 也配置了，但是 issuse 证书后确实没有在控制台看见申请成功的证书，有什么技巧吗？
如果我使用了 zerossl 的订阅计划。 如何通过 acme.sh 申请一年和通配符的证书呢？
