### ISSUE TITLE
How to revoke a certificate after uninstalling acme.sh?

### ISSUE THREAD

**Issue by lucky-beans** [acmesh-official/acme.sh#4191]
I thought that the certificate could be revoked in ZeroSSL's web panel, so I deleted acme.sh folder first. As a result, ZeroSSL said that it can only be revoked in acme.sh. Now it is very embarrassing. How can I revoke the certificate after deleting acme.sh?![image](https://user-images.githubusercontent.com/18460367/179363783-a38d3eba-39ba-47b9-abb3-f03697d17bc0.jpeg)

**Comment by Neilpang** [comment]
there is no way yet.

but you can just wait for 60 days. it will expired.
