### ISSUE TITLE
PANOS deploy-hook Commits Other Pending Changes

### ISSUE THREAD

**Issue by Hossy** [acmesh-official/acme.sh#4197]
Steps to reproduce
------------------
1. Log into PANOS as an admin and make changes, but don't commit.
2. Use deploy-hook as a DIFFERENT admin user to deploy cert to Palo.

**Result:** Pending change from admin in step 1 are committed to the firewall.

**Comment by sg1888** [comment]
@Hossy @Neilpang - Please close this issue.  It has been resolved In the latest release.  Thanks!
