### ISSUE TITLE
How to get a Haproxy certificate out of the resulting certificates

### ISSUE THREAD

**Issue by lmtr0** [acmesh-official/acme.sh#4205]
Hello there, 
I have successfully generated the certificates, however HAProxy seems to not accept them as valid certificates by either giving errors or the browser doesn't accept them.

I have found this two issues #633 and #157 and follow them and at first it seems to work and specifying the ca-file in the haproxy statement the ssl verification is solved, however the browser still doesn't accept them:
![image](https://user-images.githubusercontent.com/57605930/180830213-de802227-5d4e-4b16-9207-d356d487b678.png)

my `haproxy.cfg`:
```
defaults
  timeout client 10s
  timeout connect 5s
  timeout server 10s 
  timeout http-request 10s


frontend database
  bind :::80
  bind :::443 ssl verify required crt /root/.acme.sh/db.infra.higenku.com/cert.pem ca-file /root/.acme.sh/db.infra.higenku.com/ca.cer
  default_backend db_back

backend db_back
  server server1 127.0.0.1:5984
```
`/root/.acme.sh/db.infra.higenku.com/cert.pem` is generated with:
```
cat db.infra.higenku.com.key db.infra.higenku.com.cer fullchain.cer > cert.pem
```

**Comment by Neilpang** [comment]
did you ever try the deploy hook?

https://github.com/acmesh-official/acme.sh/wiki/deployhooks#10-deploy-the-cert-to-haproxy

**Comment by lmtr0** [comment]
yes I did, but it also didn't work

**Comment by lmtr0** [comment]
I use the certificate installed in the /etc/ssl however firefox refused to connect to the server saying the connection is insecure
