### ISSUE TITLE
acme.sh: tr -d using square brackets

### ISSUE THREAD

**Issue by Pugwash65** [acmesh-official/acme.sh#4234]
Hi,

In the _is_idn function the _tr -d_ command uses square brackets. This generates the following error:

    tr: tr: extra operand ‘y’
   Only one string may be given when deleting without squeezing repeats.
   Try 'tr --help' for more information.

The _tr_ command doesn't need square brackets around the character ranges.

The line:

  _idn_temp=$(printf "%s" "$_is_idn_d" | tr -d [0-9] | tr -d [a-z] | tr -d [A-Z] | tr -d '*.,-_')

May need to be:

  _idn_temp=$(printf "%s" "$_is_idn_d" | tr -d 0-9 | tr -d a-z | tr -d A-Z | tr -d '*.,-_')

Removing the brackets stops the error but I'm not sure if it breaks the function in the process as I wasn't sure what the intended
result should be.

**Comment by Neilpang** [comment]
try with the  latest `dev` code.

```
acme.sh --upgrade -b dev
```

**Comment by Pugwash65** [comment]
Great that's fixed it.

I'd done a _--upgrade_ but not with _-b dev_

Cheers.
