### ISSUE TITLE
--issue is not respecting --home and --cert-home setting

### ISSUE THREAD

**Issue by tom-hines** [acmesh-official/acme.sh#4237]
acme.sh --issue is not respecting my setting for --home and --cert-home.  I want everything in /acme but it's putting the certs in /root/.acme.sh

```
./acme.sh --install --home /acme --cert-home /acme/certs --accountemail "xxx@email.com"
```

```
acme.sh --test --issue -d example.com -d www.example.com -w /var/www
```
[Fri Aug 12 21:44:00 UTC 2022] Using ACME_DIRECTORY: https://acme-staging-v02.api.letsencrypt.org/directory
[Fri Aug 12 21:44:00 UTC 2022] Using CA: https://acme-staging-v02.api.letsencrypt.org/directory
[Fri Aug 12 21:44:00 UTC 2022] Create account key ok.
[Fri Aug 12 21:44:00 UTC 2022] Registering account: https://acme-staging-v02.api.letsencrypt.org/directory
[Fri Aug 12 21:44:00 UTC 2022] Registered
[Fri Aug 12 21:44:00 UTC 2022] ACCOUNT_THUMBPRINT='Mj0zy7fCQZNU62bhpYBNjw_j8zUTizWJjAz_2AlAUPk'
[Fri Aug 12 21:44:00 UTC 2022] Creating domain key
[Fri Aug 12 21:44:00 UTC 2022] **_The domain key is here: /root/.acme.sh/example.com/example.com.key_**
[Fri Aug 12 21:44:00 UTC 2022] Multi domain='DNS:example.com,DNS:www.example.com'
[Fri Aug 12 21:44:00 UTC 2022] Getting domain auth token for each domain
[Fri Aug 12 21:44:01 UTC 2022] Getting webroot for domain='example.com'
[Fri Aug 12 21:44:01 UTC 2022] Getting webroot for domain='www.example.com'
[Fri Aug 12 21:44:01 UTC 2022] Verifying: example.com
[Fri Aug 12 21:44:02 UTC 2022] Pending, The CA is processing your order, please just wait. (1/30)

```
# find /acme
/acme
/acme/acme.sh
/acme/acme.sh.env
/acme/account.conf
```

```
# find /root/.acme.sh/
/root/.acme.sh/
/root/.acme.sh/example.com
/root/.acme.sh/example.com/example.com.conf
/root/.acme.sh/example.com/example.com.key
/root/.acme.sh/example.com/example.com.csr.conf
/root/.acme.sh/example.com/example.com.csr
/root/.acme.sh/http.header
/root/.acme.sh/ca
/root/.acme.sh/ca/acme-staging-v02.api.letsencrypt.org
/root/.acme.sh/ca/acme-staging-v02.api.letsencrypt.org/directory
/root/.acme.sh/ca/acme-staging-v02.api.letsencrypt.org/directory/account.key
/root/.acme.sh/ca/acme-staging-v02.api.letsencrypt.org/directory/account.json
/root/.acme.sh/ca/acme-staging-v02.api.letsencrypt.org/directory/ca.conf
```

It works if I specify --home and --cert-home on the --issue command:

```
acme --test --issue --home /acme --cert-home /acme/certs -d example.com -d www.example.com -w /var/www
```
[Fri Aug 12 22:22:12 UTC 2022] Using ACME_DIRECTORY: https://acme-staging-v02.api.letsencrypt.org/directory
[Fri Aug 12 22:22:12 UTC 2022] Using CA: https://acme-staging-v02.api.letsencrypt.org/directory
[Fri Aug 12 22:22:13 UTC 2022] Create account key ok.
[Fri Aug 12 22:22:13 UTC 2022] Registering account: https://acme-staging-v02.api.letsencrypt.org/directory
[Fri Aug 12 22:22:13 UTC 2022] Registered
[Fri Aug 12 22:22:13 UTC 2022] ACCOUNT_THUMBPRINT='Qveb3cf7OxEBszIInmTH_VJuZtMPMhDj7kWjowTfcRk'
[Fri Aug 12 22:22:13 UTC 2022] Creating domain key
[Fri Aug 12 22:22:13 UTC 2022] **_The domain key is here: /acme/certs/example.com/example.com.key_**
[Fri Aug 12 22:22:13 UTC 2022] Multi domain='DNS:example.com,DNS:www.example.com'
[Fri Aug 12 22:22:13 UTC 2022] Getting domain auth token for each domain
[Fri Aug 12 22:22:14 UTC 2022] Getting webroot for domain='example.com'
[Fri Aug 12 22:22:14 UTC 2022] Getting webroot for domain='www.example.com'
[Fri Aug 12 22:22:14 UTC 2022] Verifying: example.com
[Fri Aug 12 22:22:14 UTC 2022] Pending, The CA is processing your order, please just wait. (1/30)

```
# acme.sh -v
https://github.com/acmesh-official/acme.sh
v3.0.5
```

**Comment by Neilpang** [comment]
did you install 2 copies of acme.sh ? 
I setup a new vm, and run exact the same commands you wrote,  but it was just working as expected.

All the files are in the specified `/acme` dir.

![image](https://user-images.githubusercontent.com/8305679/184463315-3a42912c-d6bb-44f2-b90c-143f7b77e557.png)


can you please show me
```
acme.sh --info

crontab -l

```

**Comment by tom-hines** [comment]
Thank you for the quick reply.  I should've mentioned that I'm doing this in a fresh docker container based on the nginx:1-alpine image.

The output of acme.sh --info is:

```
acme --info
LE_WORKING_DIR=/root/.acme.sh
LE_CONFIG_HOME=/root/.acme.sh
cat: can't open '/root/.acme.sh/account.conf': No such file or directory

```

Here's a video of the process:

[video](https://youtu.be/FIPlnK6J58o)

**Comment by Neilpang** [comment]
```
rm -rf /root/.acme.sh/
```
