### ISSUE TITLE
使用 --valid-to 参数且证书有效期小于 60 天时，证书仅会在过期时才续期

### ISSUE THREAD

**Issue by ZeroClover** [acmesh-official/acme.sh#4248]
使用 `--valid-to '+7d'`参数签发证书后，发现脚本设置的续期时间刚好是证书的到期时间。

使用 `--valid-to '+8d' --days 7` 参数指定续期时间比证书有效期提前 1 天，但查看配置文件看到续期时间仍然是证书的到期时间

**Comment by Neilpang** [comment]
不要把  `--days`  和 `--valid-to`  混用.
推荐使用 `--valid-to`,  它真正实现了协议.   `--days` 只是设定 renew 的日期, 并不改变 证书的有效期.

**Comment by ZeroClover** [comment]
@Neilpang 我的意思是我没法做到在证书过期之前让脚本自动续期证书。当我使用 --valid-to '+7d' 签发了证书后，证书的过期时间是 7 天，但脚本也只会在 7 天后才续期证书，这意味着一定会有服务中断的时间。

<img width="831" alt="image" src="https://user-images.githubusercontent.com/13190004/185019622-72c159fb-b4f7-4aa8-b779-8cd6a0198364.png">

<img width="570" alt="image" src="https://user-images.githubusercontent.com/13190004/185019694-97d0a8df-d373-4416-9cd6-a92b64406d85.png">

**Comment by Neilpang** [comment]
修了, 小于24小时的证书,会提前一小时更新,
否则 会提前一天更新.

**Comment by ZeroClover** [comment]
这个修复预计什么时候提交到主分支呢

**Comment by Neilpang** [comment]
已经 merged
