### ISSUE TITLE
NameSilo DNS bug

### ISSUE THREAD

**Issue by ashtarcommunications** [acmesh-official/acme.sh#4268]
Getting an error trying to issue DNS certs from NameSilo. Error says it can't find the domain.

That's because Line 113 of dns_namesilo.sh:
`if _contains "$response" "<domain>$host"; then`

is looking for the string `<domain>`, but the NameSilo API is now returning 
`
<domain expires="2023-02-26">test.com</domain>
`
The addition of the "expires" property is breaking the string match, so it fails to find the domain in the XML and aborts.

**Comment by Neilpang** [comment]
fixed,  can you please try again withe latest dev code:
```
acme.sh --upgrade -b dev
```

**Comment by SpriteOvO** [comment]
> fixed, can you please try again withe latest dev code:
> 
> ```
> acme.sh --upgrade -b dev
> ```

I have confirmed that it now works properly. Thanks!

**Comment by ashtarcommunications** [comment]
Appears to work for me as well, thank you!

**Comment by devzorg** [comment]
but wildcard still doesnt work 
```Unable to find domain specified.```

**Comment by SpriteOvO** [comment]
> but wildcard still doesnt work `Unable to find domain specified.` cause could n't find *.domain.com in retrieved list of domains
> 
> How to fix: _dnsapi/dns_namesilo.sh:107_ changed to `host=$(printf "%s" "$domain" | cut -d . -f $i-100 | sed 's/*.//g')`

@devzorg I used wildcards yesterday as well, no problem for me, can you post detailed log content here? (run it with `--debug 2`) These logs may contain sensitive information (API key and your domain name), please be careful to remove them before posting ;)
