### ISSUE TITLE
除了 export ，还有没有其他往 deploy 传参数的方法吗？

### ISSUE THREAD

**Issue by amaoo** [acmesh-official/acme.sh#4276]
您好 ，除了 export ，还有没有其他往 deploy 传参数的方法吗？
在zerossl 注册账号之后，EAB 也配置了，但是 issuse 证书后确实没有在控制台看见申请成功的证书，有什么技巧吗？
如果我使用了 zerossl 的订阅计划。 如何通过 acme.sh 申请一年和通配符的证书呢？

**Comment by Neilpang** [comment]
没有
没有
不清楚.
