### ISSUE TITLE
Frequent problem with acme.sh when DNS AAAA record exists

### ISSUE THREAD

**Issue by johnwwweissberg** [acmesh-official/acme.sh#4308]
This is not a bug but rather an annoying lack of information in the debug output.

As a webhost, I frequently install SSL certificates on our customer's behalf. I am frequently tripped up by this same problem:

I ask the customer to point the DNS "A" record for the domain name to our server. The customer does this correctly. Unbeknownst to me (and to the customer too), the DNS provider has automatically created a DNS "AAAA" record for the domain name. This "AAAA" record does NOT point to the IPv6 address of the server hosting the IPv4 address (The IPv4 and IPv6 addresses point to different servers).

When I use acme.sh to generate the SSL certificate, acme.sh fails. In reality, the IPv4 verification step passes but the IPv6 address points to the incorrect server so the IPv6 verification step fails.

When I check the contents of the 2 files used for verification  listed in the debug output, I become very confused because the files DO match:

/usr/local/lsws/Example/html/.well-known/acme-challenge/nBaIjt_HAnpBwqtPibHiPJaVT8gN9vGWiBGPtP8YBi8
http://carte-plastic.fr/.well-known/acme-challenge/nBaIjt_HAnpBwqtPibHiPJaVT8gN9vGWiBGPtP8YBi8

I frequently forget that there are, in reality 2 verification steps: IPv4 and IPv6.

It is only when I remember that I have been bitten by this IPv6 issue many times in the past that I remember that I need to have the customer delete the "AAAA" record from the DNS settings.

It would be very helpful to me if the debug output were to be enhanced to indicate whether it was the IPv4 or IPv6 verification step that failed.

-->

Steps to repeat:
Configure DNS "AAAA" record that does not correctly point to server hosting website
------------------

Debug output:
[Fri Sep  9 20:28:20 CEST 2022] carte-plastic.fr:Verify error:The key authorization file from the server did not match this challenge 
[Fri Sep  9 20:28:20 CEST 2022] Debug: get token url.
[Fri Sep  9 20:28:20 CEST 2022] GET
[Fri Sep  9 20:28:20 CEST 2022] url='http://carte-plastic.fr/.well-known/acme-challenge/nBaIjt_HAnpBwqtPibHiPJaVT8gN9vGWiBGPtP8YBi8'
[Fri Sep  9 20:28:20 CEST 2022] timeout=1
[Fri Sep  9 20:28:20 CEST 2022] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g  --connect-timeout 1'
nBaIjt_HAnpBwqtPibHiPJaVT8gN9vGWiBGPtP8YBi8.8psWENtLEv0rfGpwl7zdMZC5gzfbbsklSaZU1ocPlW4[Fri Sep  9 20:28:20 CEST 2022] ret='0'
[Fri Sep  9 20:28:20 CEST 2022] Debugging, skip removing: /usr/local/lsws/Example/html/.well-known/acme-challenge/nBaIjt_HAnpBwqtPibHiPJaVT8gN9vGWiBGPtP8YBi8
-----------------

```
/root/.acme.sh/acme.sh --issue --force --keylength ec-256 --debug -d carte-plastic.fr -d www.carte-plastic.fr --cert-file /etc/letsencrypt/live/carteplastic.printsafe.net/cert.pem --key-file /etc/letsencrypt/live/carteplastic.printsafe.net/privkey.pem --fullchain-file /etc/letsencrypt/live/carteplastic.printsafe.net/fullchain.pem -w /usr/local/lsws/Example/html
```

**Comment by Neilpang** [comment]
I think you can tell your customer not to set AAAA record  for  their domain .

**Comment by johnwwweissberg** [comment]
There are many domain registrar's that set the AAAA record automatically.
Many of our customers do not know they are set.

It would be nice if the acme script made it clear in the debug data that it
is the IPv6 verification that has failed.

**Comment by Neilpang** [comment]
The CA chooses how to validate the domain, either ipv4 or ipv6.  There is no way from the client side to know.
The error message was also returned from the CA. And different ca may return different error messages.  The error message is not part of the rfc8555.

I don't think there is anything we can do from the client side.

As I suggested,  you can make a popup window to the users to check/or disable the ipv6 address when they are about to use your service.
