### ISSUE TITLE
Can not find dns api hook for: dns_cf

### ISSUE THREAD

**Issue by ColinWoW** [acmesh-official/acme.sh#4336]
Steps to reproduce
------------------
When I run acme in openwrt, I get a error about "`Can not find dns api hook for: dns_cf`".
I have installed `acme`, `luci-app-acme` and `luci-i18n-acme-zh-cn`.openwrt.
And I find `dns_cf.sh` in `/usr/lib/client/dnsapi`.

Debug log
------------------
```
Thu Oct  6 01:03:20 2022 daemon.err run-acme[21338]: Can not find dns api hook for: dns_cf
Thu Oct  6 01:03:20 2022 daemon.info run-acme[21338]: You need to add the txt record manually.
```

**Comment by ColinWoW** [comment]
**Solved**
`acme.sh` find `dns_cf.sh` in `/usr/lib/dnsapi`.
So, just `cp -r /usr/lib/client/dnsapi /usr/lib/dnsapi` to solve the problem.

**Comment by ColinWoW** [comment]
**Solved**
`acme.sh` find `dns_cf.sh` in `/usr/lib/dnsapi`.
So, just `cp -r /usr/lib/client/dnsapi /usr/lib/dnsapi` to solve the problem.

**Comment by ColinWoW** [comment]
**Solved**
`acme.sh` find `dns_cf.sh` in `/usr/lib/dnsapi`.
So, just `cp -r /usr/lib/client/dnsapi /usr/lib/dnsapi` to solve the problem.

**Comment by ColinWoW** [comment]
**Solved**
`acme.sh` find `dns_cf.sh` in `/usr/lib/dnsapi`.
So, just run commond `cp -r /usr/lib/client/dnsapi /usr/lib/dnsapi` to solve the problem.

**Comment by joshenders** [comment]
Same error and I just had to install `acme-acmesh-dnsapi`
