### ISSUE TITLE
单域名解析到多台服务器，怎么更新证书

### ISSUE THREAD

**Issue by Codecaver** [acmesh-official/acme.sh#4343]
Steps to reproduce
------------------
1、解析一个域名 `example.com`到`1.1.1.1 `和 `1.1.1.2` 服务器

2、然后分别在`1.1.1.1`服务器和`1.1.1.2`服务器使用http方式验证域名
（1）在1.1.1.1服务器上申请证书：结果正常验证
` acme.sh  --issue  --server letsencrypt  -d example.com  -w  /usr/local/nginx/html/ `
（2） 在1.1.1.2 服务器上申请证书，验证失败，错误代码404
` acme.sh  --issue  --server letsencrypt  -d example.com  -w  /usr/local/nginx/html/ `

3、问题
在1.1.1.2服务器执行申请证书，letsencrypt 却访问 1.1.1.1 去验证 token，导致报错404

4、疑问
对于一个域名解析到多台服务器，应该怎么更新多台服务器的证书呢

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```
example.com :Verify error:During secondary validation: 1.1.1.2 : Invalid response from http://example.com/.well-known/acme-challenge/0qj5ot-K-O8GKca9jXw9SJDXCvb4WO4k3wrgYThnbrQ: 404

**Comment by Codecaver** [comment]
> Please upgrade to the latest code and try again first. Maybe it's already fixed. `acme.sh --upgrade` If it's still not working, please provide the log with `--debug 2`, otherwise, nobody can help you.

acme.sh --version
https://github.com/acmesh-official/acme.sh
v3.0.5

**Comment by reddyshyam** [comment]
> > Please upgrade to the latest code and try again first. Maybe it's already fixed. `acme.sh --upgrade` If it's still not working, please provide the log with `--debug 2`, otherwise, nobody can help you.
> 
> acme.sh --version https://github.com/acmesh-official/acme.sh v3.0.5

I don't see 3.0.5. Was it released and revoked?

**Comment by Codecaver** [comment]
> > > Please upgrade to the latest code and try again first. Maybe it's already fixed. `acme.sh --upgrade` If it's still not working, please provide the log with `--debug 2`, otherwise, nobody can help you.
> > 
> > 
> > acme.sh --version https://github.com/acmesh-official/acme.sh v3.0.5
> 
> I don't see 3.0.5. Was it released and revoked?

I have no idea，just use this command to install acme
`curl https://get.acme.sh | sh`

**Comment by Codecaver** [comment]
在letsencrypt 有说到证书可以重用。在部署多台web服务器时，是不是可以利用这个重用规则去快速部署其他web服务器，而不是重新 申请验证 证书
[https://letsencrypt.org/zh-cn/docs/integration-guide/#%E5%AD%98%E5%82%A8%E5%92%8C%E9%87%8D%E7%94%A8%E8%AF%81%E4%B9%A6%E5%92%8C%E5%AF%86%E9%92%A5](url)

**Comment by Neilpang** [comment]
在一台服务器上申请, 然后 通过 reloadcmd 或者 deploy/ssh  来部署到所有的服务器上.

或者通过 dns api 的方式可以在每一台服务器上申请
