### ISSUE TITLE
Changing DNS API key. Update account.conf?

### ISSUE THREAD

**Issue by spinitron** [acmesh-official/acme.sh#4351]
If I need to update the auth tokens for access to my DNS provider's API, do I simply edit `account.conf`?

**Comment by Neilpang** [comment]
Yes, correct.

**Comment by GrantGryczan** [comment]
@Neilpang I thought the `account.conf` location, its format, and the names of variables aren't guaranteed to be stable. Are you sure it's best practice to edit `account.conf`? I'm writing a script to update API keys automatically, so I need a reliable method.

**Comment by Neilpang** [comment]
@GrantGryczan   Sorry,  it's not recommended to edit the account.conf directly.  For most of the dns api,  if you use a new api keys to issue a new cert,  the previous-saved api keys should be replaced with the new one.

**Comment by GrantGryczan** [comment]
@Neilpang I'm not using new API keys to issue a new cert. I'm running the `--issue` command with the new API key, but I don't want it to issue a new cert if the cert doesn't need to be renewed. I just want `acme.sh` to save the new API key so it'll use it when it's ready to renew (via `cron`).

**Comment by Neilpang** [comment]
sorry, but you must issue the cert again to change the api key.  otherwise, you can edit the conf file, but it's not recommended to.
