### ISSUE TITLE
edit or update reloadcmd ?

### ISSUE THREAD

**Issue by ChR-iSz** [acmesh-official/acme.sh#4356]
Hello,

i have a typo in my reload command:

` acme.sh --install-cert   ...  --reloadcmd "systemctl reload ngiinx;" `

How can i edit the reloadcmd ? Exist a config ?

**Comment by Wzhahai** [comment]
Sorry, my friend.I was too busy just now. I hit the keyboard. Sorry

**Comment by Neilpang** [comment]
use `acme.sh --install-cert ....` again, with the correct name.
