### ISSUE TITLE
Create CSR error

### ISSUE THREAD

**Issue by fyymxb** [acmesh-official/acme.sh#4363]
My command is :
acme.sh --issue --server letsencrypt --test -d http://www.mydomain -w /home/fyym/www/webpage --keylength ec-256 --debug

The follows are debug infomation:

[Sun 23 Oct 2022 05:48:34 AM EDT] Using server: https://acme-v02.api.letsencrypt.org/directory
[Sun 23 Oct 2022 05:48:34 AM EDT] Running cmd: issue
[Sun 23 Oct 2022 05:48:34 AM EDT] _main_domain='http://www.mydomain'
[Sun 23 Oct 2022 05:48:34 AM EDT] _alt_domains='no'
[Sun 23 Oct 2022 05:48:34 AM EDT] Using config home:/home/fyym/.acme.sh
[Sun 23 Oct 2022 05:48:34 AM EDT] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Sun 23 Oct 2022 05:48:34 AM EDT] DOMAIN_PATH='/home/fyym/.acme.sh/http://www.mydomain_ecc'
[Sun 23 Oct 2022 05:48:34 AM EDT] Le_NextRenewTime
[Sun 23 Oct 2022 05:48:34 AM EDT] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Sun 23 Oct 2022 05:48:34 AM EDT] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Sun 23 Oct 2022 05:48:34 AM EDT] GET
[Sun 23 Oct 2022 05:48:34 AM EDT] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 23 Oct 2022 05:48:34 AM EDT] timeout=
[Sun 23 Oct 2022 05:48:34 AM EDT] _WGET='wget -q --content-on-error '
[Sun 23 Oct 2022 05:48:35 AM EDT] Using sed  -i
[Sun 23 Oct 2022 05:48:35 AM EDT] ret='0'
[Sun 23 Oct 2022 05:48:35 AM EDT] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Sun 23 Oct 2022 05:48:35 AM EDT] ACME_NEW_AUTHZ
[Sun 23 Oct 2022 05:48:35 AM EDT] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Sun 23 Oct 2022 05:48:35 AM EDT] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Sun 23 Oct 2022 05:48:35 AM EDT] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Sun 23 Oct 2022 05:48:35 AM EDT] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf'
[Sun 23 Oct 2022 05:48:35 AM EDT] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Sun 23 Oct 2022 05:48:35 AM EDT] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sun 23 Oct 2022 05:48:35 AM EDT] _on_before_issue
[Sun 23 Oct 2022 05:48:35 AM EDT] _chk_main_domain='http://www.mydomain'
[Sun 23 Oct 2022 05:48:35 AM EDT] _chk_alt_domains
[Sun 23 Oct 2022 05:48:35 AM EDT] Le_LocalAddress
[Sun 23 Oct 2022 05:48:35 AM EDT] d='http://www.mydomain'
[Sun 23 Oct 2022 05:48:35 AM EDT] Check for domain='http://www.mydomain'
[Sun 23 Oct 2022 05:48:35 AM EDT] _currentRoot='/home/fyym/www/webpage'
[Sun 23 Oct 2022 05:48:35 AM EDT] d
[Sun 23 Oct 2022 05:48:35 AM EDT] _saved_account_key_hash is not changed, skip register account.
[Sun 23 Oct 2022 05:48:35 AM EDT] Read key length:ec-256
[Sun 23 Oct 2022 05:48:35 AM EDT] _createcsr
[Sun 23 Oct 2022 05:48:35 AM EDT] Single domain='http://www.mydomain'
[Sun 23 Oct 2022 05:48:35 AM EDT] Create CSR error.
[Sun 23 Oct 2022 05:48:35 AM EDT] pid
[Sun 23 Oct 2022 05:48:35 AM EDT] No need to restore nginx, skip.
[Sun 23 Oct 2022 05:48:35 AM EDT] _clearupdns
[Sun 23 Oct 2022 05:48:35 AM EDT] dns_entries
[Sun 23 Oct 2022 05:48:35 AM EDT] skip dns.
[Sun 23 Oct 2022 05:48:35 AM EDT] _on_issue_err
[Sun 23 Oct 2022 05:48:35 AM EDT] Please check log file for more details: /home/fyym/.acme.sh/acme.sh.log
[Sun 23 Oct 2022 05:48:35 AM EDT] Diagnosis versions: 
openssl:openssl
OpenSSL 1.1.1d  10 Sep 2019
apache:
apache doesn't exist.
nginx:
nginx doesn't exist.
socat:
socat by Gerhard Rieger and contributors - see www.dest-unreach.org
socat version 1.7.3.2 on Nov 19 2017 13:56:10
   running on Linux version #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20), release 4.19.0-6-amd64, machine x86_64
features:
  #define WITH_STDIO 1
  #define WITH_FDNUM 1
  #define WITH_FILE 1
  #define WITH_CREAT 1
  #define WITH_GOPEN 1
  #define WITH_TERMIOS 1
  #define WITH_PIPE 1
  #define WITH_UNIX 1
  #define WITH_ABSTRACT_UNIXSOCKET 1
  #define WITH_IP4 1
  #define WITH_IP6 1
  #define WITH_RAWIP 1
  #define WITH_GENERICSOCKET 1
  #define WITH_INTERFACE 1
  #define WITH_TCP 1
  #define WITH_UDP 1
  #define WITH_SCTP 1
  #define WITH_LISTEN 1
  #define WITH_SOCKS4 1
  #define WITH_SOCKS4A 1
  #define WITH_PROXY 1
  #define WITH_SYSTEM 1
  #define WITH_EXEC 1
  #undef WITH_READLINE
  #define WITH_TUN 1
  #define WITH_PTY 1
  #define WITH_OPENSSL 1
  #undef WITH_FIPS
  #define WITH_LIBWRAP 1
  #define WITH_SYCLS 1
  #define WITH_FILAN 1
  #define WITH_RETRY 1
  #define WITH_MSGLEVEL 0 /*debug*/

**Comment by fyymxb** [comment]
acme.sh --issue --server letsencrypt --test -d http://www.mydomain -w /home/fyym/www/webpage --keylength ec-256 --debug 2

[Sun 23 Oct 2022 06:11:07 AM EDT] _selectServer try snames='zerossl.com,zerossl'
[Sun 23 Oct 2022 06:11:07 AM EDT] _selectServer try snames='letsencrypt.org,letsencrypt'
[Sun 23 Oct 2022 06:11:07 AM EDT] _selectServer match letsencrypt
[Sun 23 Oct 2022 06:11:08 AM EDT] Selected server: https://acme-v02.api.letsencrypt.org/directory
[Sun 23 Oct 2022 06:11:08 AM EDT] Lets find script dir.
[Sun 23 Oct 2022 06:11:08 AM EDT] _SCRIPT_='/home/fyym/.acme.sh/acme.sh'
[Sun 23 Oct 2022 06:11:08 AM EDT] _script='/home/fyym/.acme.sh/acme.sh'
[Sun 23 Oct 2022 06:11:08 AM EDT] _script_home='/home/fyym/.acme.sh'
[Sun 23 Oct 2022 06:11:08 AM EDT] Using config home:/home/fyym/.acme.sh
[Sun 23 Oct 2022 06:11:08 AM EDT] LE_WORKING_DIR='/home/fyym/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.5
[Sun 23 Oct 2022 06:11:08 AM EDT] Using server: https://acme-v02.api.letsencrypt.org/directory
[Sun 23 Oct 2022 06:11:08 AM EDT] Running cmd: issue
[Sun 23 Oct 2022 06:11:08 AM EDT] _main_domain='http://www.mydomain'
[Sun 23 Oct 2022 06:11:08 AM EDT] _alt_domains='no'
[Sun 23 Oct 2022 06:11:08 AM EDT] Using config home:/home/fyym/.acme.sh
[Sun 23 Oct 2022 06:11:08 AM EDT] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Sun 23 Oct 2022 06:11:08 AM EDT] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Sun 23 Oct 2022 06:11:08 AM EDT] _ACME_SERVER_PATH='directory'
[Sun 23 Oct 2022 06:11:08 AM EDT] DOMAIN_PATH='/home/fyym/.acme.sh/http://www.mydomain_ecc'
[Sun 23 Oct 2022 06:11:08 AM EDT] '/home/fyym/www/webpage' does not contain 'dns'
[Sun 23 Oct 2022 06:11:08 AM EDT] Le_NextRenewTime
[Sun 23 Oct 2022 06:11:08 AM EDT] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Sun 23 Oct 2022 06:11:08 AM EDT] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Sun 23 Oct 2022 06:11:08 AM EDT] GET
[Sun 23 Oct 2022 06:11:08 AM EDT] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 23 Oct 2022 06:11:08 AM EDT] timeout=
[Sun 23 Oct 2022 06:11:08 AM EDT] _WGET='wget -q -d  --content-on-error '
Setting --content-on-error (contentonerror) to 1
Setting --content-on-error (contentonerror) to 1
Setting --user-agent (useragent) to acme.sh/3.0.5 (https://github.com/acmesh-official/acme.sh)
Setting --user-agent (useragent) to acme.sh/3.0.5 (https://github.com/acmesh-official/acme.sh)
Setting --header (header) to
Setting --header (header) to
Setting --header (header) to
Setting --header (header) to
Setting --header (header) to
Setting --header (header) to
Setting --header (header) to
Setting --header (header) to
Setting --header (header) to
Setting --header (header) to
Setting --server-response (serverresponse) to 1
Setting --server-response (serverresponse) to 1
Setting --output-document (outputdocument) to -
Setting --output-document (outputdocument) to -
DEBUG output created by Wget 1.20.1 on linux-gnu.

Reading HSTS entries from /home/fyym/.wget-hsts
URI encoding = ‘UTF-8’
Certificates loaded: 128
Caching acme-v02.api.letsencrypt.org => 172.65.32.248 2606:4700:60:0:f53d:5624:85c7:3a2c
Created socket 3.
Releasing 0x000055988ec4b6c0 (new refcount 1).

---request begin---
GET /directory HTTP/1.1
User-Agent: acme.sh/3.0.5 (https://github.com/acmesh-official/acme.sh)
Accept: */*
Accept-Encoding: identity
Host: acme-v02.api.letsencrypt.org
Connection: Keep-Alive

---request end---

---response begin---
HTTP/1.1 200 OK
Server: nginx
Date: Sun, 23 Oct 2022 10:11:08 GMT
Content-Type: application/json
Content-Length: 659
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

---response end---
  HTTP/1.1 200 OK
  Server: nginx
  Date: Sun, 23 Oct 2022 10:11:08 GMT
  Content-Type: application/json
  Content-Length: 659
  Connection: keep-alive
  Cache-Control: public, max-age=0, no-cache
  X-Frame-Options: DENY
  Strict-Transport-Security: max-age=604800
Registered socket 3 for persistent reuse.
Parsed Strict-Transport-Security max-age = 604800, includeSubDomains = false
Updated HSTS host: acme-v02.api.letsencrypt.org:443 (max-age: 604800, includeSubdomains: false)
Saving HSTS entries to /home/fyym/.wget-hsts
[Sun 23 Oct 2022 06:11:08 AM EDT] options='/^[^ ][^ ]/d; /^ *$/d'
[Sun 23 Oct 2022 06:11:08 AM EDT] Using sed  -i
[Sun 23 Oct 2022 06:11:08 AM EDT] options='s/^  //g'
[Sun 23 Oct 2022 06:11:08 AM EDT] Using sed  -i
[Sun 23 Oct 2022 06:11:08 AM EDT] ret='0'
[Sun 23 Oct 2022 06:11:08 AM EDT] response='{
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "mMxCzn-z6Qc": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}'
[Sun 23 Oct 2022 06:11:08 AM EDT] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Sun 23 Oct 2022 06:11:08 AM EDT] ACME_NEW_AUTHZ
[Sun 23 Oct 2022 06:11:08 AM EDT] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Sun 23 Oct 2022 06:11:08 AM EDT] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Sun 23 Oct 2022 06:11:08 AM EDT] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Sun 23 Oct 2022 06:11:08 AM EDT] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf'
[Sun 23 Oct 2022 06:11:08 AM EDT] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Sun 23 Oct 2022 06:11:08 AM EDT] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sun 23 Oct 2022 06:11:08 AM EDT] _on_before_issue
[Sun 23 Oct 2022 06:11:08 AM EDT] _chk_main_domain='http://www.mydomain'
[Sun 23 Oct 2022 06:11:08 AM EDT] _chk_alt_domains
[Sun 23 Oct 2022 06:11:08 AM EDT] '/home/fyym/www/webpage' does not contain 'no'
[Sun 23 Oct 2022 06:11:08 AM EDT] Le_LocalAddress
[Sun 23 Oct 2022 06:11:08 AM EDT] d='http://www.mydomain'
[Sun 23 Oct 2022 06:11:08 AM EDT] Check for domain='http://www.mydomain'
[Sun 23 Oct 2022 06:11:08 AM EDT] _currentRoot='/home/fyym/www/webpage'
[Sun 23 Oct 2022 06:11:08 AM EDT] d
[Sun 23 Oct 2022 06:11:08 AM EDT] '/home/fyym/www/webpage' does not contain 'apache'
[Sun 23 Oct 2022 06:11:08 AM EDT] _saved_account_key_hash='O+Q03Ua/tY0Zn6trwIYoleZ50k4MK6L6yszrqS0qPWQ='
[Sun 23 Oct 2022 06:11:08 AM EDT] _saved_account_key_hash is not changed, skip register account.
[Sun 23 Oct 2022 06:11:08 AM EDT] Read key length:ec-256
[Sun 23 Oct 2022 06:11:08 AM EDT] _createcsr
[Sun 23 Oct 2022 06:11:08 AM EDT] domain='http://www.mydomain'
[Sun 23 Oct 2022 06:11:08 AM EDT] domainlist
[Sun 23 Oct 2022 06:11:08 AM EDT] csrkey='/home/fyym/.acme.sh/http://www.mydomain_ecc/http://www.mydomain.key'
[Sun 23 Oct 2022 06:11:08 AM EDT] csr='/home/fyym/.acme.sh/http://www.mydomain_ecc/http://www.mydomain.csr'
[Sun 23 Oct 2022 06:11:08 AM EDT] csrconf='/home/fyym/.acme.sh/http://www.mydomain_ecc/http://www.mydomain.csr.conf'
[Sun 23 Oct 2022 06:11:08 AM EDT] Single domain='http://www.mydomain'
[Sun 23 Oct 2022 06:11:08 AM EDT] seg='http://www'
[Sun 23 Oct 2022 06:11:08 AM EDT] _is_idn_d='http://www.mydomain'
[Sun 23 Oct 2022 06:11:08 AM EDT] _idn_temp
[Sun 23 Oct 2022 06:11:08 AM EDT] _is_idn_d='http://www.mydomain'
[Sun 23 Oct 2022 06:11:08 AM EDT] _idn_temp
[Sun 23 Oct 2022 06:11:08 AM EDT] _csr_cn='http://www.mydomain'
[Sun 23 Oct 2022 06:11:08 AM EDT] seg='http://www'
Error Loading request extension section v3_req
140669207778432:error:220A4076:X509 V3 routines:a2i_GENERAL_NAME:bad ip address:../crypto/x509v3/v3_alt.c:460:value=http://www.mydomain
140669207778432:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:../crypto/x509v3/v3_conf.c:47:name=subjectAltName, value=IP:http://www.mydomain
[Sun 23 Oct 2022 06:11:08 AM EDT] Create CSR error.
[Sun 23 Oct 2022 06:11:08 AM EDT] pid
[Sun 23 Oct 2022 06:11:08 AM EDT] No need to restore nginx, skip.
[Sun 23 Oct 2022 06:11:08 AM EDT] _clearupdns
[Sun 23 Oct 2022 06:11:08 AM EDT] dns_entries
[Sun 23 Oct 2022 06:11:08 AM EDT] skip dns.
[Sun 23 Oct 2022 06:11:08 AM EDT] _on_issue_err
[Sun 23 Oct 2022 06:11:08 AM EDT] Please check log file for more details: /home/fyym/.acme.sh/acme.sh.log
[Sun 23 Oct 2022 06:11:08 AM EDT] _chk_vlist
[Sun 23 Oct 2022 06:11:08 AM EDT] Diagnosis versions:
openssl:openssl
OpenSSL 1.1.1d  10 Sep 2019
apache:
apache doesn't exist.
nginx:
nginx doesn't exist.
socat:
socat by Gerhard Rieger and contributors - see www.dest-unreach.org
socat version 1.7.3.2 on Nov 19 2017 13:56:10
   running on Linux version #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20), release 4.19.0-6-amd64, machine x86_64
features:
  #define WITH_STDIO 1
  #define WITH_FDNUM 1
  #define WITH_FILE 1
  #define WITH_CREAT 1
  #define WITH_GOPEN 1
  #define WITH_TERMIOS 1
  #define WITH_PIPE 1
  #define WITH_UNIX 1
  #define WITH_ABSTRACT_UNIXSOCKET 1
  #define WITH_IP4 1
  #define WITH_IP6 1
  #define WITH_RAWIP 1
  #define WITH_GENERICSOCKET 1
  #define WITH_INTERFACE 1
  #define WITH_TCP 1
  #define WITH_UDP 1
  #define WITH_SCTP 1
  #define WITH_LISTEN 1
  #define WITH_SOCKS4 1
  #define WITH_SOCKS4A 1
  #define WITH_PROXY 1
  #define WITH_SYSTEM 1
  #define WITH_EXEC 1
  #undef WITH_READLINE
  #define WITH_TUN 1
  #define WITH_PTY 1
  #define WITH_OPENSSL 1
  #undef WITH_FIPS
  #define WITH_LIBWRAP 1
  #define WITH_SYCLS 1
  #define WITH_FILAN 1
  #define WITH_RETRY 1
  #define WITH_MSGLEVEL 0 /*debug*/

**Comment by Neilpang** [comment]
```
```

**Comment by Neilpang** [comment]
```
-d   www.mydomain
```
