### ISSUE TITLE
renew证书失败

### ISSUE THREAD

**Issue by zhuweitung** [acmesh-official/acme.sh#4376]
Steps to reproduce
------------------
到了自动renew的时间没有成功，于是手动执行renew命令，依旧失败
证书之前是dns模式生成的

Debug log
-----------------

```bash
acme.sh --renew --domain my.domain --ecc --force --debug 2
```
[acme.sh.log](https://github.com/acmesh-official/acme.sh/files/9895460/acme.sh.log)

**Comment by StrangePeanut** [comment]
Also having this issue. Tried `--server letsencrypt` to no avail.

**Comment by yuliu** [comment]
Let's Encrypt is undergoing a planned maintenance which may impact certificate issuances and renewals: https://letsencrypt.status.io/pages/maintenance/55957a99e800baa4470002da/635c31e78f4e1b052ef00991

> Our upstream network provider for High Assurance Datacenter 1 is performing network maintenance which may result in brief disruptions to production API availability and staging being unavailable.

Should retry later until success.

This was what I've experienced just now:
<details>
  <summary>Running log</summary>

[Sun 30 Oct 2022 09:49:07 PM +08] All success, let's return
[Sun 30 Oct 2022 09:49:07 PM +08] Verifying: XXXXX
[Sun 30 Oct 2022 09:49:08 PM +08] Pending, The CA is processing your order, please just wait. (1/30)
[Sun 30 Oct 2022 09:49:12 PM +08] Pending, The CA is processing your order, please just wait. (2/30)
[Sun 30 Oct 2022 09:49:15 PM +08] Pending, The CA is processing your order, please just wait. (3/30)
[Sun 30 Oct 2022 09:49:19 PM +08] Pending, The CA is processing your order, please just wait. (4/30)
[Sun 30 Oct 2022 09:49:23 PM +08] Pending, The CA is processing your order, please just wait. (5/30)
[Sun 30 Oct 2022 09:49:26 PM +08] Pending, The CA is processing your order, please just wait. (6/30)
[Sun 30 Oct 2022 09:49:30 PM +08] Pending, The CA is processing your order, please just wait. (7/30)
[Sun 30 Oct 2022 09:49:34 PM +08] Pending, The CA is processing your order, please just wait. (8/30)
[Sun 30 Oct 2022 09:49:37 PM +08] Pending, The CA is processing your order, please just wait. (9/30)
[Sun 30 Oct 2022 09:49:41 PM +08] Pending, The CA is processing your order, please just wait. (10/30)
[Sun 30 Oct 2022 09:49:45 PM +08] Pending, The CA is processing your order, please just wait. (11/30)
[Sun 30 Oct 2022 09:49:49 PM +08] Pending, The CA is processing your order, please just wait. (12/30)
[Sun 30 Oct 2022 09:49:52 PM +08] Pending, The CA is processing your order, please just wait. (13/30)
[Sun 30 Oct 2022 09:49:56 PM +08] Pending, The CA is processing your order, please just wait. (14/30)
[Sun 30 Oct 2022 09:50:00 PM +08] Pending, The CA is processing your order, please just wait. (15/30)
[Sun 30 Oct 2022 09:50:03 PM +08] Pending, The CA is processing your order, please just wait. (16/30)
[Sun 30 Oct 2022 09:50:07 PM +08] Pending, The CA is processing your order, please just wait. (17/30)
[Sun 30 Oct 2022 09:50:11 PM +08] Pending, The CA is processing your order, please just wait. (18/30)
[Sun 30 Oct 2022 09:50:15 PM +08] Pending, The CA is processing your order, please just wait. (19/30)
[Sun 30 Oct 2022 09:50:18 PM +08] Pending, The CA is processing your order, please just wait. (20/30)
[Sun 30 Oct 2022 09:50:22 PM +08] Pending, The CA is processing your order, please just wait. (21/30)
[Sun 30 Oct 2022 09:50:26 PM +08] Pending, The CA is processing your order, please just wait. (22/30)
[Sun 30 Oct 2022 09:50:30 PM +08] Pending, The CA is processing your order, please just wait. (23/30)
[Sun 30 Oct 2022 09:50:33 PM +08] Pending, The CA is processing your order, please just wait. (24/30)
[Sun 30 Oct 2022 09:50:37 PM +08] Success
[Sun 30 Oct 2022 09:50:37 PM +08] Verifying: *.XXXXX
[Sun 30 Oct 2022 09:50:38 PM +08] Pending, The CA is processing your order, please just wait. (1/30)
[Sun 30 Oct 2022 09:50:41 PM +08] Pending, The CA is processing your order, please just wait. (2/30)
[Sun 30 Oct 2022 09:50:45 PM +08] Pending, The CA is processing your order, please just wait. (3/30)
[Sun 30 Oct 2022 09:50:49 PM +08] Pending, The CA is processing your order, please just wait. (4/30)
[Sun 30 Oct 2022 09:50:52 PM +08] Pending, The CA is processing your order, please just wait. (5/30)
[Sun 30 Oct 2022 09:50:56 PM +08] Pending, The CA is processing your order, please just wait. (6/30)
[Sun 30 Oct 2022 09:51:00 PM +08] Pending, The CA is processing your order, please just wait. (7/30)
[Sun 30 Oct 2022 09:51:04 PM +08] Pending, The CA is processing your order, please just wait. (8/30)
[Sun 30 Oct 2022 09:51:07 PM +08] Pending, The CA is processing your order, please just wait. (9/30)
[Sun 30 Oct 2022 09:51:11 PM +08] Pending, The CA is processing your order, please just wait. (10/30)
[Sun 30 Oct 2022 09:51:15 PM +08] Pending, The CA is processing your order, please just wait. (11/30)
[Sun 30 Oct 2022 09:51:18 PM +08] Pending, The CA is processing your order, please just wait. (12/30)
[Sun 30 Oct 2022 09:51:22 PM +08] Pending, The CA is processing your order, please just wait. (13/30)
[Sun 30 Oct 2022 09:51:26 PM +08] Pending, The CA is processing your order, please just wait. (14/30)
[Sun 30 Oct 2022 09:51:30 PM +08] Pending, The CA is processing your order, please just wait. (15/30)
[Sun 30 Oct 2022 09:51:33 PM +08] Pending, The CA is processing your order, please just wait. (16/30)
[Sun 30 Oct 2022 09:51:37 PM +08] Pending, The CA is processing your order, please just wait. (17/30)
[Sun 30 Oct 2022 09:51:41 PM +08] Pending, The CA is processing your order, please just wait. (18/30)
[Sun 30 Oct 2022 09:51:44 PM +08] Pending, The CA is processing your order, please just wait. (19/30)
[Sun 30 Oct 2022 09:51:48 PM +08] Pending, The CA is processing your order, please just wait. (20/30)
[Sun 30 Oct 2022 09:51:52 PM +08] Pending, The CA is processing your order, please just wait. (21/30)
[Sun 30 Oct 2022 09:51:56 PM +08] Pending, The CA is processing your order, please just wait. (22/30)
[Sun 30 Oct 2022 09:51:59 PM +08] Pending, The CA is processing your order, please just wait. (23/30)
[Sun 30 Oct 2022 09:52:03 PM +08] Pending, The CA is processing your order, please just wait. (24/30)
[Sun 30 Oct 2022 09:52:07 PM +08] Success
[Sun 30 Oct 2022 09:52:07 PM +08] Verifying: XXXXX
[Sun 30 Oct 2022 09:52:08 PM +08] Pending, The CA is processing your order, please just wait. (1/30)
[Sun 30 Oct 2022 09:52:11 PM +08] Pending, The CA is processing your order, please just wait. (2/30)
[Sun 30 Oct 2022 09:52:15 PM +08] Pending, The CA is processing your order, please just wait. (3/30)
[Sun 30 Oct 2022 09:52:19 PM +08] Pending, The CA is processing your order, please just wait. (4/30)
[Sun 30 Oct 2022 09:52:22 PM +08] Pending, The CA is processing your order, please just wait. (5/30)
[Sun 30 Oct 2022 09:52:26 PM +08] Pending, The CA is processing your order, please just wait. (6/30)
[Sun 30 Oct 2022 09:52:30 PM +08] Pending, The CA is processing your order, please just wait. (7/30)
[Sun 30 Oct 2022 09:52:34 PM +08] Pending, The CA is processing your order, please just wait. (8/30)
[Sun 30 Oct 2022 09:52:37 PM +08] Pending, The CA is processing your order, please just wait. (9/30)
[Sun 30 Oct 2022 09:52:41 PM +08] Pending, The CA is processing your order, please just wait. (10/30)
[Sun 30 Oct 2022 09:52:45 PM +08] Pending, The CA is processing your order, please just wait. (11/30)
[Sun 30 Oct 2022 09:52:48 PM +08] Pending, The CA is processing your order, please just wait. (12/30)
[Sun 30 Oct 2022 09:52:52 PM +08] Pending, The CA is processing your order, please just wait. (13/30)
[Sun 30 Oct 2022 09:52:56 PM +08] Pending, The CA is processing your order, please just wait. (14/30)
[Sun 30 Oct 2022 09:53:00 PM +08] Pending, The CA is processing your order, please just wait. (15/30)
[Sun 30 Oct 2022 09:53:03 PM +08] Pending, The CA is processing your order, please just wait. (16/30)
[Sun 30 Oct 2022 09:53:07 PM +08] Pending, The CA is processing your order, please just wait. (17/30)
[Sun 30 Oct 2022 09:53:11 PM +08] Pending, The CA is processing your order, please just wait. (18/30)
[Sun 30 Oct 2022 09:53:14 PM +08] Pending, The CA is processing your order, please just wait. (19/30)
[Sun 30 Oct 2022 09:53:18 PM +08] Pending, The CA is processing your order, please just wait. (20/30)
[Sun 30 Oct 2022 09:53:22 PM +08] Pending, The CA is processing your order, please just wait. (21/30)
[Sun 30 Oct 2022 09:53:26 PM +08] Pending, The CA is processing your order, please just wait. (22/30)
[Sun 30 Oct 2022 09:53:29 PM +08] Pending, The CA is processing your order, please just wait. (23/30)
[Sun 30 Oct 2022 09:53:33 PM +08] Pending, The CA is processing your order, please just wait. (24/30)
[Sun 30 Oct 2022 09:53:37 PM +08] Success
[Sun 30 Oct 2022 09:53:37 PM +08] Verifying: *.XXXX
[Sun 30 Oct 2022 09:53:38 PM +08] Pending, The CA is processing your order, please just wait. (1/30)
[Sun 30 Oct 2022 09:53:41 PM +08] Pending, The CA is processing your order, please just wait. (2/30)
[Sun 30 Oct 2022 09:53:45 PM +08] Pending, The CA is processing your order, please just wait. (3/30)
[Sun 30 Oct 2022 09:53:49 PM +08] Pending, The CA is processing your order, please just wait. (4/30)
[Sun 30 Oct 2022 09:53:52 PM +08] Pending, The CA is processing your order, please just wait. (5/30)
[Sun 30 Oct 2022 09:53:56 PM +08] Pending, The CA is processing your order, please just wait. (6/30)
[Sun 30 Oct 2022 09:54:00 PM +08] Pending, The CA is processing your order, please just wait. (7/30)
[Sun 30 Oct 2022 09:54:04 PM +08] Pending, The CA is processing your order, please just wait. (8/30)
[Sun 30 Oct 2022 09:54:07 PM +08] Pending, The CA is processing your order, please just wait. (9/30)
[Sun 30 Oct 2022 09:54:11 PM +08] Pending, The CA is processing your order, please just wait. (10/30)
[Sun 30 Oct 2022 09:54:15 PM +08] Pending, The CA is processing your order, please just wait. (11/30)
[Sun 30 Oct 2022 09:54:18 PM +08] Pending, The CA is processing your order, please just wait. (12/30)
[Sun 30 Oct 2022 09:54:22 PM +08] Pending, The CA is processing your order, please just wait. (13/30)
[Sun 30 Oct 2022 09:54:26 PM +08] Pending, The CA is processing your order, please just wait. (14/30)
[Sun 30 Oct 2022 09:54:30 PM +08] Pending, The CA is processing your order, please just wait. (15/30)
[Sun 30 Oct 2022 09:54:33 PM +08] Pending, The CA is processing your order, please just wait. (16/30)
[Sun 30 Oct 2022 09:54:37 PM +08] Pending, The CA is processing your order, please just wait. (17/30)
[Sun 30 Oct 2022 09:54:41 PM +08] Pending, The CA is processing your order, please just wait. (18/30)
[Sun 30 Oct 2022 09:54:44 PM +08] Pending, The CA is processing your order, please just wait. (19/30)
[Sun 30 Oct 2022 09:54:48 PM +08] Pending, The CA is processing your order, please just wait. (20/30)
[Sun 30 Oct 2022 09:54:52 PM +08] Pending, The CA is processing your order, please just wait. (21/30)
[Sun 30 Oct 2022 09:54:56 PM +08] Pending, The CA is processing your order, please just wait. (22/30)
[Sun 30 Oct 2022 09:54:59 PM +08] Pending, The CA is processing your order, please just wait. (23/30)
[Sun 30 Oct 2022 09:55:03 PM +08] Pending, The CA is processing your order, please just wait. (24/30)
[Sun 30 Oct 2022 09:55:07 PM +08] Success
[Sun 30 Oct 2022 09:55:07 PM +08] Removing DNS records.
</details>

**Comment by Rid** [comment]
We're also seeing the same issue `Pending, The CA is processing your order, please just wait. (29/30)`

Is there any indication how long the outage will last?

**Comment by zhuweitung** [comment]
All 30 attempts with ZeroSSL failed.
```
[Sun Oct 30 22:10:51 CST 2022] Processing, The CA is processing your order, please just wait. (29/30)
[Sun Oct 30 22:10:56 CST 2022] xxx:Timeout
[Sun Oct 30 22:10:56 CST 2022] Removing DNS records.
```

**Comment by tcbbd** [comment]
https://isdown.app/integrations/hostinger/incidents/149881-ssl-setup-issues
Seems both Let's Encrypt and Zero SSL are down

**Comment by sinner-** [comment]
Same issue here on a fresh host using my standard ansible playbook which was working just a couple of days ago.

Working with `--server letsencrypt` now, but ZeroSSL not working.

```
{
  "changed": true,
  "cmd": [
    "/home/acmesh/.acme.sh/acme.sh",
    "--issue",
    "-d",
    "redacted.hostname",
    "-w",
    "/usr/share/nginx/html",
    "--pre-hook",
    "sudo systemctl start nginx",
    "--post-hook",
    "sudo systemctl stop nginx"
  ],
  "delta": "0:04:17.018144",
  "end": "2022-10-31 04:52:26.665042",
  "msg": "non-zero return code",
  "rc": 1,
  "start": "2022-10-31 04:48:09.646898",
  "stderr": "[Mon Oct 31 04:52:22 UTC 2022] redacted.hostname:Timeout\n[Mon Oct 31 04:52:22 UTC 2022] Please add '--debug' or '--log' to check more details.\n[Mon Oct 31 04:52:22 UTC 2022] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh",
  "stderr_lines": [
    "[Mon Oct 31 04:52:22 UTC 2022] redacted.hostname:Timeout",
    "[Mon Oct 31 04:52:22 UTC 2022] Please add '--debug' or '--log' to check more details.",
    "[Mon Oct 31 04:52:22 UTC 2022] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh"
  ],
  "stdout_lines": [
    "[Mon Oct 31 04:48:10 UTC 2022] Using CA: https://acme.zerossl.com/v2/DV90",
    "[Mon Oct 31 04:48:10 UTC 2022] Run pre hook:'sudo systemctl start nginx'",
    "[Mon Oct 31 04:48:10 UTC 2022] Create account key ok.",
    "[Mon Oct 31 04:48:10 UTC 2022] No EAB credentials found for ZeroSSL, let's get one",
    "[Mon Oct 31 04:48:16 UTC 2022] Registering account: https://acme.zerossl.com/v2/DV90",
    "[Mon Oct 31 04:48:17 UTC 2022] Could not get nonce, let's try again.",
    "[Mon Oct 31 04:48:20 UTC 2022] Could not get nonce, let's try again.",
    "[Mon Oct 31 04:48:23 UTC 2022] Could not get nonce, let's try again.",
    "[Mon Oct 31 04:48:26 UTC 2022] Could not get nonce, let's try again.",
    "[Mon Oct 31 04:48:29 UTC 2022] Could not get nonce, let's try again.",
    "[Mon Oct 31 04:48:32 UTC 2022] Could not get nonce, let's try again.",
    "[Mon Oct 31 04:48:36 UTC 2022] Could not get nonce, let's try again.",
    "[Mon Oct 31 04:48:39 UTC 2022] Could not get nonce, let's try again.",
    "[Mon Oct 31 04:48:42 UTC 2022] Could not get nonce, let's try again.",
    "[Mon Oct 31 04:48:45 UTC 2022] Could not get nonce, let's try again.",
    "[Mon Oct 31 04:48:48 UTC 2022] Could not get nonce, let's try again.",
    "[Mon Oct 31 04:48:51 UTC 2022] Could not get nonce, let's try again.",
    "[Mon Oct 31 04:48:54 UTC 2022] Could not get nonce, let's try again.",
    "[Mon Oct 31 04:49:02 UTC 2022] Registered",
    "[Mon Oct 31 04:49:02 UTC 2022] ACCOUNT_THUMBPRINT='REDACTED'",
    "[Mon Oct 31 04:49:02 UTC 2022] Creating domain key",
    "[Mon Oct 31 04:49:02 UTC 2022] The domain key is here: /home/acmesh/.acme.sh/redacted.hostname/redacted.hostname.key",
    "[Mon Oct 31 04:49:02 UTC 2022] Single domain='redacted.hostname'",
    "[Mon Oct 31 04:49:02 UTC 2022] Getting domain auth token for each domain",
    "[Mon Oct 31 04:49:05 UTC 2022] Getting webroot for domain='redacted.hostname'",
    "[Mon Oct 31 04:49:05 UTC 2022] Verifying: redacted.hostname",
    "[Mon Oct 31 04:49:08 UTC 2022] Processing, The CA is processing your order, please just wait. (1/30)",
    "[Mon Oct 31 04:49:15 UTC 2022] Processing, The CA is processing your order, please just wait. (2/30)",
    "[Mon Oct 31 04:49:34 UTC 2022] Processing, The CA is processing your order, please just wait. (3/30)",
    "[Mon Oct 31 04:49:39 UTC 2022] Processing, The CA is processing your order, please just wait. (4/30)",
    "[Mon Oct 31 04:49:46 UTC 2022] Processing, The CA is processing your order, please just wait. (5/30)",
    "[Mon Oct 31 04:49:51 UTC 2022] Processing, The CA is processing your order, please just wait. (6/30)",
    "[Mon Oct 31 04:49:56 UTC 2022] Processing, The CA is processing your order, please just wait. (7/30)",
    "[Mon Oct 31 04:50:01 UTC 2022] Processing, The CA is processing your order, please just wait. (8/30)",
    "[Mon Oct 31 04:50:12 UTC 2022] Processing, The CA is processing your order, please just wait. (9/30)",
    "[Mon Oct 31 04:50:26 UTC 2022] Processing, The CA is processing your order, please just wait. (10/30)",
    "[Mon Oct 31 04:50:39 UTC 2022] Processing, The CA is processing your order, please just wait. (11/30)",
    "[Mon Oct 31 04:50:44 UTC 2022] Processing, The CA is processing your order, please just wait. (12/30)",
    "[Mon Oct 31 04:50:58 UTC 2022] Processing, The CA is processing your order, please just wait. (13/30)",
    "[Mon Oct 31 04:51:11 UTC 2022] Processing, The CA is processing your order, please just wait. (14/30)",
    "[Mon Oct 31 04:51:16 UTC 2022] Processing, The CA is processing your order, please just wait. (15/30)",
    "[Mon Oct 31 04:51:20 UTC 2022] Processing, The CA is processing your order, please just wait. (16/30)",
    "[Mon Oct 31 04:51:23 UTC 2022] Processing, The CA is processing your order, please just wait. (17/30)",
    "[Mon Oct 31 04:51:30 UTC 2022] Processing, The CA is processing your order, please just wait. (18/30)",
    "[Mon Oct 31 04:51:33 UTC 2022] Processing, The CA is processing your order, please just wait. (19/30)",
    "[Mon Oct 31 04:51:38 UTC 2022] Processing, The CA is processing your order, please just wait. (20/30)",
    "[Mon Oct 31 04:51:42 UTC 2022] Processing, The CA is processing your order, please just wait. (21/30)",
    "[Mon Oct 31 04:51:45 UTC 2022] Processing, The CA is processing your order, please just wait. (22/30)",
    "[Mon Oct 31 04:51:48 UTC 2022] Processing, The CA is processing your order, please just wait. (23/30)",
    "[Mon Oct 31 04:51:52 UTC 2022] Processing, The CA is processing your order, please just wait. (24/30)",
    "[Mon Oct 31 04:51:56 UTC 2022] Processing, The CA is processing your order, please just wait. (25/30)",
    "[Mon Oct 31 04:52:02 UTC 2022] Processing, The CA is processing your order, please just wait. (26/30)",
    "[Mon Oct 31 04:52:07 UTC 2022] Processing, The CA is processing your order, please just wait. (27/30)",
    "[Mon Oct 31 04:52:10 UTC 2022] Processing, The CA is processing your order, please just wait. (28/30)",
    "[Mon Oct 31 04:52:13 UTC 2022] Processing, The CA is processing your order, please just wait. (29/30)",
    "[Mon Oct 31 04:52:22 UTC 2022] Run post hook:'sudo systemctl stop nginx'"
  ]
}
```

**Comment by StrangePeanut** [comment]
Can confirm that ZeroSSL is still unavailable but Let's Encrypt works now. Both ZeroSSL and Let's Encrypt were failing yesterday.

```shell
--set-default-ca --server letsencrypt
```

**Comment by sinner-** [comment]
@Neilpang I get this is not an `acme.sh` issue, but FYI I just tried and it is still failing.

**Comment by Neilpang** [comment]
@sinner-     Chaning the CA can solve the problem.
Sometimes, some of the CAs are just being maintaining/busy.
