### ISSUE TITLE
关于申请多个域名证书的问题

### ISSUE THREAD

**Issue by xiebruce** [acmesh-official/acme.sh#4388]
- 1、目前我知道的，如果我申请了`*.abc.com`证书并安装，那么它会每天都运行一次计划任务，这样证书到期后会自动更新；
- 2、但是如果我申请`*.abc.com`证书后，再申请`*.def.com`证书并安装，然后再申请`*.ghi.com`证书并安装；

问题：`*.abc.com`，`*.def.com`，`*.ghi.com`是三个不同的域名，它们的证书都会自动更新吗？因为无论我申请几个域名的证书，计划任务是只有一条命令的，我不确定这条命令是否能更新所有域名的证书，所以想问一下，谢谢！

**Comment by Neilpang** [comment]
会.


你可以手动执行一次试试:  
```
acme.sh   --cron
```

**Comment by xiebruce** [comment]
> 会.
> 
> 你可以手动执行一次试试:
> 
> ```
> acme.sh   --cron
> ```

好的，谢谢

**Comment by WordsWorthLess** [comment]
> 会.
> 
> 你可以手动执行一次试试:
> 
> ```
> acme.sh   --cron
> ```

请问大佬，如果我想通过Cloudflare的API Token来更新证书的话，不同的域名的zone id如何配置呢
