### ISSUE TITLE
wget read timeout 3 is too low

### ISSUE THREAD

**Issue by dlt-** [acmesh-official/acme.sh#4421]
We have experienced random issues with both LE and ZeroSSL causing weird _wget_out commnad not found -error.

The real reason seems to be too low --read-timeout value for wget HEAD request (when getting nonce)

      _WGET="$_WGET --read-timeout=3.0  --tries=2  "

I changed 3.0 to 10.0 and problem disappeared.

I suggest making this configurable via env variable or at least raising it.

**Comment by upr-kmd** [comment]
I did 2 tests on my WSL instances, and I got timeouts in test1 and "_wget_out: command not found" in test2.
[acme_test2.txt](https://github.com/acmesh-official/acme.sh/files/10258819/acme_test2.txt)
[acme_test1.txt](https://github.com/acmesh-official/acme.sh/files/10258820/acme_test1.txt)
I've modified my ACME script to increase --read-timeout to 6.0, but it didn't help.
