### ISSUE TITLE
华为云的参数怎么写啊 dns_api(dns_huaweicloud): Error getting token. 

### ISSUE THREAD

**Issue by qian9008** [acmesh-official/acme.sh#4426]
是这3个参数吗
我填了 出错无法添加解析
dns_api(dns_huaweicloud): Error getting token. 

dns_huaweicloud
export HUAWEICLOUD_Username="h1657"
export HUAWEICLOUD_Password="233"
export HUAWEICLOUD_DomainName="ack.com"

**Comment by DuanXDong** [comment]
![zh-cn_image_0000001467559457](https://user-images.githubusercontent.com/42064531/206630973-344fe37b-7555-48e1-81fa-0066bcc74e7a.png)
根据图片上一一对应，你写的HUAWEICLOUD_DomainName这个应该是不对的

**Comment by qian9008** [comment]
> ![zh-cn_image_0000001467559457](https://user-images.githubusercontent.com/42064531/206630973-344fe37b-7555-48e1-81fa-0066bcc74e7a.png) 根据图片上一一对应，你写的HUAWEICLOUD_DomainName这个应该是不对的


  | IAM User Name | hwc25416                      Account Name | hwc2451657 

  | IAM User ID | 0bbe1ff09900                      Account ID | 0bbe1fef72000
不是吧
DomainName=Account Name？？？？

**Comment by qian9008** [comment]
> ![zh-cn_image_0000001467559457](https://user-images.githubusercontent.com/42064531/206630973-344fe37b-7555-48e1-81fa-0066bcc74e7a.png) 根据图片上一一对应，你写的HUAWEICLOUD_DomainName这个应该是不对的

可以了 ，这参数名字真是 误导。DomainName=Account Name

**Comment by SakurajimaMaii** [comment]
Good job！

**Comment by newproplus** [comment]
我使用子账户登录,要在`统一身份认证服务`里面对`用户组`和`用户`进行授权,否则会出现报错 `dns_api(dns_huaweicloud): Error getting zone id.`

正确的配置值如下:

```sh
export HUAWEICLOUD_Username=子账户的用户名
export HUAWEICLOUD_Password=子账户的密码
export HUAWEICLOUD_DomainName=和上图一样(即帐号名)
```

看代码`https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_huaweicloud.sh`, 注释里有些有用的链接.

我想吐槽一下华为云,内容不想说.

**Comment by maye174** [comment]
如果主账户升为华为账户而不是华为云账户的话没办法获取到token，需要开个子账户，然后放权就可以了

**Comment by labolado** [comment]
> 我使用子账户登录,要在`统一身份认证服务`里面对`用户组`和`用户`进行授权,否则会出现报错 `dns_api(dns_huaweicloud): Error getting zone id.`
> 
> 正确的配置值如下:
> 
> ```shell
> export HUAWEICLOUD_Username=子账户的用户名
> export HUAWEICLOUD_Password=子账户的密码
> export HUAWEICLOUD_DomainName=和上图一样(即帐号名)
> ```
> 
> 看代码`https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_huaweicloud.sh`, 注释里有些有用的链接.
> 
> 我想吐槽一下华为云,内容不想说.

我用户都放到admin组了，还是报Error getting zone id的错误

**Comment by yanshibin** [comment]
> > 我使用子账户登录,要在`统一身份认证服务`里面对`用户组`和`用户`进行授权,否则会出现报错 `dns_api(dns_huaweicloud): Error getting zone id.`
> > 正确的配置值如下:
> > ```shell
> > export HUAWEICLOUD_Username=子账户的用户名
> > export HUAWEICLOUD_Password=子账户的密码
> > export HUAWEICLOUD_DomainName=和上图一样(即帐号名)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 看代码`https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_huaweicloud.sh`, 注释里有些有用的链接.
> > 我想吐槽一下华为云,内容不想说.
> 
> 我用户都放到admin组了，还是报Error getting zone id的错误

same issuing
