### ISSUE TITLE
[Wiki] A small error in the wiki about HiCA

### ISSUE THREAD

**Issue by DreamOfIce** [acmesh-official/acme.sh#4434]
There is an error in the wiki, and as I do not have editing rights, I can only raise an issue here:

This is the description of IDN prices from the HiCA website:
![Screenshot-of-HiCA-Official-Site](https://user-images.githubusercontent.com/80821706/207801981-383290ed-fe7f-4870-849a-788f791fa181.jpeg)
> [link](http://www1.hi.cn/en/docs/intro)

However, in the wiki this item says Yes:
![Wiki-CA](https://user-images.githubusercontent.com/80821706/207802848-75678c96-ce5b-4a34-b4ba-2f3477c6c481.jpeg)
> [link](https://github.com/acmesh-official/acme.sh/wiki/CA)

**Comment by Neilpang** [comment]
updated,  thanks.
