### ISSUE TITLE
Possible undefined behavoir regarding to RFC 8555

### ISSUE THREAD

**Issue by glatzert** [acmesh-official/acme.sh#4442]
As maintainer of an acme-server component, an issue has been brought to my attention, which seems to orgininate here:
https://github.com/acmesh-official/acme.sh/blob/master/acme.sh#L5032

The aforementioned line of code is responsible to request the current state of a challenge, which seems to be undefined behavior regarding to RFC8555. The RFC suggests, clients will use the authorization url to request the current state of the authorization process (https://www.rfc-editor.org/rfc/rfc8555#section-7.5.1).
The challenge url is used to signal, which challenge should be processed only - not to request the state of that particular challenge.

The original issue was raised here:  https://github.com/glatzert/ACME-Server-ADCS/issues/8 - it contains the debug log as well.

**Comment by Neilpang** [comment]
thanks for your info.  it's fixed now.
