### ISSUE TITLE
Error with Wildcards on Namecheap Web Servers

### ISSUE THREAD

**Issue by u2n** [acmesh-official/acme.sh#4461]
Many thanks for this awesome project, deployed in only a few minutes.

This on namecheap webhost (not domain registration) server. Worked fine with base domain alone:

`acme.sh --issue --webroot ~/public_html -d example.com --force`

But then found no TLDs were covered (mail., www., etc.) in _SSL/TLS Status_ of cpanel.

So tried similar example I found online:

`acme.sh --issue --webroot ~/public_html -d example.com -d *.example.com --staging`

Result:
```
Error, can not get domain token entry *.example.com for http-01
The supported validation types are: dns-01 , but you specified: http-01
```
Appending _--debug 2_ to the foregoing:

```
Lets find script dir.
_SCRIPT_='/home/username/.acme.sh/acme.sh'
_script='/home/username/.acme.sh/acme.sh'
_script_home='/home/username/.acme.sh'
Using config home:/home/username/.acme.sh
LE_WORKING_DIR='/home/username/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.5
Running cmd: issue
_main_domain='example.com'
_alt_domains='*.example.com'
Using config home:/home/username/.acme.sh
Using ACME_DIRECTORY: https://acme-staging-v02.api.letsencrypt.org/directory
ACME_DIRECTORY='https://acme-staging-v02.api.letsencrypt.org/directory'
_ACME_SERVER_HOST='acme-staging-v02.api.letsencrypt.org'
_ACME_SERVER_PATH='directory'
DOMAIN_PATH='/home/username/.acme.sh/example.com'
'/home/username/public_html' does not contain 'dns'
Le_NextRenewTime='1678317556'
_saved_domain='example.com'
_saved_alt='*.example.com'
_normized_saved_domains='*.example.com,example.com,'
_normized_domains='*.example.com,example.com,'
Domains not changed.
Skip, Next renewal time is: 2023-03-08T...Z
```
Can it be that wildcards are not supported in this situation? No worries if each TLD has to be listed separately on the command line, just wanted to be sure I'm using the script correctly.

**Comment by u2n** [comment]
The script was just installed:
```
Already uptodate!
[Sun Jan  8 20:05:09 EST 2023] Upgrade success!
```
And the output of --debug 2 is provided above.

**Comment by Zabadam** [comment]
I believe you mean subdomains--not TLDs. 
(TLD is top-level domain, the portion after the final period, like `example.COM` or `example.NET`; whereas subdomains are prepended before the base domain, like `subdomain1.example.com` and `sub2.example.com`.)

If the issue is verification, then you may pass each domain separately as [seen here](https://github.com/acmesh-official/acme.sh/wiki/How-to-issue-a-cert#3-multiple-domains-san-mode--hybrid-mode:~:text=3.%20Multiple%20domains%2C%20SAN%20mode%2C%20Hybrid%20mode).

**Comment by u2n** [comment]
@Zabadam, yes of course, corrected and thanks. Sometimes the fingers type faster than the brain can direct.

Doing one-per-line is also easy, just wanted to check if there were a wildcard one-liner, which would be even easier. Only scanned the wiki so extra thanks for finding the precise narrative that covers this.

After struggling with other methods, just can't say enough what an awesome project acme.sh is.

**Comment by flyingCrp** [comment]
i got the same error . i try 
``
acme.sh --issue \
-d 'domain.com' \
-d '*.domain.com' \
--dns dns_ali  \
--server letsencrypt \
--webroot /web/root/path
``
but i got  the below error 
```
Error, can not get domain token entry *.alis-test.top for http-01
The supported validation types are: dns-01 , but you specified: http-01
``

Any ideas on how to do this?

**Comment by u2n** [comment]
@flyingCrp, it appears you're trying the same command and getting the same result.

The script apparently does not parse wildcards, unless there's a particular syntax that must be used and we're not following it. Don't know for sure. Was hoping the developer(s) would clear this up.
