### ISSUE TITLE
Successful Cert Renewal - Possible to modify the email subject ?

### ISSUE THREAD

**Issue by marcoczen** [acmesh-official/acme.sh#4463]
Hi Team.

Acme is working great.

Small favour pls.

Is there any way we could  modify the subject of the email ( to add hostname or private ip of the server )
when the cert is renewed ? I use wildcard certs and so i need to identify which server's cert have been renewed.

Thanks.

**Comment by marcoczen** [comment]
Noted. Acme is working great. 

# acme.sh --upgrade

[Fri 13 Jan 2023 01:47:32 AM +08] Already uptodate!
[Fri 13 Jan 2023 01:47:32 AM +08] Upgrade success!


# acme.sh --debug 2
[Fri 13 Jan 2023 01:49:54 AM +08] Lets find script dir.
[Fri 13 Jan 2023 01:49:54 AM +08] _SCRIPT_='/root/.acme.sh/acme.sh'
[Fri 13 Jan 2023 01:49:54 AM +08] _script='/root/.acme.sh/acme.sh'
[Fri 13 Jan 2023 01:49:54 AM +08] _script_home='/root/.acme.sh'
[Fri 13 Jan 2023 01:49:54 AM +08] Using config home:/root/.acme.sh
[Fri 13 Jan 2023 01:49:54 AM +08] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.5
[Fri 13 Jan 2023 01:49:54 AM +08] Running cmd: 
[Fri 13 Jan 2023 01:49:54 AM +08] Using config home:/root/.acme.sh
[Fri 13 Jan 2023 01:49:54 AM +08] default_acme_server='https://acme.zerossl.com/v2/DV90'
[Fri 13 Jan 2023 01:49:54 AM +08] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Fri 13 Jan 2023 01:49:54 AM +08] _ACME_SERVER_HOST='acme.zerossl.com'
[Fri 13 Jan 2023 01:49:54 AM +08] _ACME_SERVER_PATH='v2/DV90'
https://github.com/acmesh-official/acme.sh
v3.0.5

**Comment by Neilpang** [comment]
Sure. I will add it later.

**Comment by marcoczen** [comment]
Wow ... Thanks.

Current Subject is ' Renew Success '.
Suggested New Subject ' Renew Success - Hostname my_server_hostname '.

Thanks.

**Comment by Neilpang** [comment]
fixed.

```
acme.sh --upgrade -b dev
```

The subjec will be like:  ` Renew Success   by youhostName` by default.

you can change the default host name:   
```
acme.sh  --set-notify  --notify-source "myhostname"
```

**Comment by marcoczen** [comment]
Thanks x 1000 - Subject shows the hostname now.
