### ISSUE TITLE
What is Verify error:"error":{

### ISSUE THREAD

**Issue by LuckyStar04** [acmesh-official/acme.sh#4474]
acme.sh is already latest version, and i keep getting this error:

```
[Fri Jan 27 13:39:46 UTC 2023] Using CA: https://acme.zerossl.com/v2/DV90
[Fri Jan 27 13:39:46 UTC 2023] Standalone mode.
[Fri Jan 27 13:39:46 UTC 2023] Single domain='techblogcore.top'
[Fri Jan 27 13:39:46 UTC 2023] Getting domain auth token for each domain
[Fri Jan 27 13:39:56 UTC 2023] Getting webroot for domain='techblogcore.top'
[Fri Jan 27 13:39:56 UTC 2023] Verifying: techblogcore.top
[Fri Jan 27 13:39:56 UTC 2023] Standalone mode server
[Fri Jan 27 13:40:00 UTC 2023] Processing, The CA is processing your order, please just wait. (1/30)
[Fri Jan 27 13:40:07 UTC 2023] techblogcore.top:Verify error:"error":{
[Fri Jan 27 13:40:07 UTC 2023] Please check log file for more details: /root/.acme.sh/acme.sh.log
```

with --debug 2 --log:

```
...
[Fri Jan 27 13:36:11 UTC 2023] POST
[Fri Jan 27 13:36:11 UTC 2023] _post_url='https://acme.zerossl.com/v2/DV90/chall/cu0cn6GPMRbHuHMHmhEoSg'
[Fri Jan 27 13:36:11 UTC 2023] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.TvFZDjjxHT  -g '
[Fri Jan 27 13:36:15 UTC 2023] _ret='0'
[Fri Jan 27 13:36:15 UTC 2023] code='200'
[Fri Jan 27 13:36:15 UTC 2023] techblogcore.top:Verify error:"error":{
[Fri Jan 27 13:36:15 UTC 2023] Debug: get token url.
[Fri Jan 27 13:36:15 UTC 2023] GET
[Fri Jan 27 13:36:15 UTC 2023] url='http://techblogcore.top/.well-known/acme-challenge/iRVNOjeYBYi46m0hM0NU0G4rcRPysc7nOnRokDYlafs'
[Fri Jan 27 13:36:15 UTC 2023] timeout=1
[Fri Jan 27 13:36:15 UTC 2023] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.TvFZDjjxHT  -g  --connect-timeout 1'
[Fri Jan 27 13:36:16 UTC 2023] ret='0'
[Fri Jan 27 13:36:16 UTC 2023] Skip for removelevel:
[Fri Jan 27 13:36:16 UTC 2023] pid='5578'
...
```

**Comment by daijinp** [comment]
Same question

**Comment by daijinp** [comment]
[Sun Jan 29 05:40:53 UTC 2023] code='200'
[Sun Jan 29 05:40:53 UTC 2023] original='{"type":"http-01","url":"https://acme.zerossl.com/v2/DV90/chall/ewuCCj70jzNLV4PFny5A9w","status":"invalid","error":{}     ,"token":"hGQm-bqtomaXm0bEKEWsJP66GXJoIyzokQrXu3hSKRA"}'
[Sun Jan 29 05:40:53 UTC 2023] response='{"type":"http-01","url":"https://acme.zerossl.com/v2/DV90/chall/ewuCCj70jzNLV4PFny5A9w","status":"invalid","error":{}     ,"token":"hGQm-bqtomaXm0bEKEWsJP66GXJoIyzokQrXu3hSKRA"}'
[Sun Jan 29 05:40:53 UTC 2023] original='{"type":"http-01","url":"https://acme.zerossl.com/v2/DV90/chall/ewuCCj70jzNLV4PFny5A9w","status":"invalid","error":{}     ,"token":"hGQm-bqtomaXm0bEKEWsJP66GXJoIyzokQrXu3hSKRA"}'
[Sun Jan 29 05:40:53 UTC 2023] response='{"type":"http-01","url":"https://acme.zerossl.com/v2/DV90/chall/ewuCCj70jzNLV4PFny5A9w","status":"invalid","error":{}     ,"token":"hGQm-bqtomaXm0bEKEWsJP66GXJoIyzokQrXu3hSKRA"}'
[Sun Jan 29 05:40:53 UTC 2023] status='invalid'
[Sun Jan 29 05:40:53 UTC 2023] error='"error":{'
[Sun Jan 29 05:40:53 UTC 2023] errordetail
[Sun Jan 29 05:40:53 UTC 2023] cc.jplpoc.tk:Verify error:"error":{
[Sun Jan 29 05:40:53 UTC 2023] Debug: get token url.
[Sun Jan 29 05:40:53 UTC 2023] GET
[Sun Jan 29 05:40:53 UTC 2023] url='http://cc.jplpoc.tk/.well-known/acme-challenge/hGQm-bqtomaXm0bEKEWsJP66GXJoIyzokQrXu3hSKRA'
[Sun Jan 29 05:40:53 UTC 2023] timeout=1
[Sun Jan 29 05:40:53 UTC 2023] Http already initialized.
[Sun Jan 29 05:40:53 UTC 2023] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.3ytPi0j9HT  -g  --connect-timeout 1'
[Sun Jan 29 05:40:54 UTC 2023] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 28
[Sun Jan 29 05:40:54 UTC 2023] Here is the curl dump log:
[Sun Jan 29 05:40:54 UTC 2023] == Info:   Trying 144.24.82.41:80...
== Info: TCP_NODELAY set
== Info: Connection timed out after 1000 milliseconds
== Info: Closing connection 0
[Sun Jan 29 05:40:54 UTC 2023] ret='28'
[Sun Jan 29 05:40:54 UTC 2023] Skip for removelevel:
[Sun Jan 29 05:40:54 UTC 2023] pid='28940'
2023/01/29 05:40:54 socat[28940] N socat_signal(): handling signal 15
2023/01/29 05:40:54 socat[28940] W exiting on signal 15
2023/01/29 05:40:54 socat[28940] N socat_signal(): finishing signal 15
2023/01/29 05:40:54 socat[28940] N exit(143)
[Sun Jan 29 05:40:54 UTC 2023] No need to restore nginx, skip.
[Sun Jan 29 05:40:54 UTC 2023] _clearupdns
[Sun Jan 29 05:40:54 UTC 2023] dns_entries
[Sun Jan 29 05:40:54 UTC 2023] skip dns.
[Sun Jan 29 05:40:54 UTC 2023] _on_issue_err
[Sun Jan 29 05:40:54 UTC 2023] Please check log file for more details: /root/.acme.sh/acme.sh.log
[Sun Jan 29 05:40:54 UTC 2023] _chk_vlist='cc.jplpoc.tk#hGQm-bqtomaXm0bEKEWsJP66GXJoIyzokQrXu3hSKRA.zIeOF9i8MRANIKRGL-WoHSV-1hKHgKPaXjKeShLyJ2g#https://acme.z     erossl.com/v2/DV90/chall/ewuCCj70jzNLV4PFny5A9w#http-01#no,'
[Sun Jan 29 05:40:54 UTC 2023] start to deactivate authz
[Sun Jan 29 05:40:54 UTC 2023] Trigger domain validation.
[Sun Jan 29 05:40:54 UTC 2023] _t_url='https://acme.zerossl.com/v2/DV90/chall/ewuCCj70jzNLV4PFny5A9w'
[Sun Jan 29 05:40:54 UTC 2023] _t_key_authz='hGQm-bqtomaXm0bEKEWsJP66GXJoIyzokQrXu3hSKRA.zIeOF9i8MRANIKRGL-WoHSV-1hKHgKPaXjKeShLyJ2g'
[Sun Jan 29 05:40:54 UTC 2023] _t_vtype
[Sun Jan 29 05:40:54 UTC 2023] url='https://acme.zerossl.com/v2/DV90/chall/ewuCCj70jzNLV4PFny5A9w'
[Sun Jan 29 05:40:54 UTC 2023] payload='{}'
[Sun Jan 29 05:40:54 UTC 2023] Use cached jwk for file: /root/.acme.sh/ca/acme.zerossl.com/v2/DV90/account.key
[Sun Jan 29 05:40:54 UTC 2023] Use _CACHED_NONCE='1AoqVpEfrse3SXlS4MHaRDpyvGZAetOIDzsnHpy2qfA'
[Sun Jan 29 05:40:54 UTC 2023] nonce='1AoqVpEfrse3SXlS4MHaRDpyvGZAetOIDzsnHpy2qfA'
[Sun Jan 29 05:40:54 UTC 2023] POST
[Sun Jan 29 05:40:54 UTC 2023] _post_url='https://acme.zerossl.com/v2/DV90/chall/ewuCCj70jzNLV4PFny5A9w'
[Sun Jan 29 05:40:54 UTC 2023] body='{"protected": "eyJub25jZSI6ICIxQW9xVnBFZnJzZTNTWGxTNE1IYVJEcHl2R1pBZXRPSUR6c25IcHkycWZBIiwgInVybCI6ICJodHRwczovL2FjbWUuem     Vyb3NzbC5jb20vdjIvRFY5MC9jaGFsbC9ld3VDQ2o3MGp6TkxWNFBGbnk1QTl3IiwgImFsZyI6ICJFUzI1NiIsICJraWQiOiAiaHR0cHM6Ly9hY21lLnplcm9zc2wuY29tL3YyL0RWOTAvYWNjb3VudC9iNXhh     LUplazBrNzhBWVd6dHhud0ZRIn0", "payload": "e30", "signature": "w7z4KszababEfYPUx71cd18cgSrscvIFP_XiPs4z-9r4LX8o5vbi7NWZjrQ4xp1oeo1IYuakISv08hfH9mvMtA"}'
[Sun Jan 29 05:40:54 UTC 2023] _postContentType='application/jose+json'
[Sun Jan 29 05:40:54 UTC 2023] Http already initialized.
[Sun Jan 29 05:40:54 UTC 2023] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.3ytPi0j9HT  -g '
[Sun Jan 29 05:40:57 UTC 2023] _ret='0'
[Sun Jan 29 05:40:57 UTC 2023] responseHeaders='HTTP/2 200
``

**Comment by daijinp** [comment]
After using  acme.sh --upgrade  to get the latest code

`[Sun Jan 29 05:40:53 UTC 2023] code='200'
[Sun Jan 29 05:40:53 UTC 2023] original='{"type":"http-01","url":"https://acme.zerossl.com/v2/DV90/chall/ewuCCj70jzNLV4PFny5A9w","status":"invalid","error":{}     ,"token":"hGQm-bqtomaXm0bEKEWsJP66GXJoIyzokQrXu3hSKRA"}'
[Sun Jan 29 05:40:53 UTC 2023] response='{"type":"http-01","url":"https://acme.zerossl.com/v2/DV90/chall/ewuCCj70jzNLV4PFny5A9w","status":"invalid","error":{}     ,"token":"hGQm-bqtomaXm0bEKEWsJP66GXJoIyzokQrXu3hSKRA"}'
[Sun Jan 29 05:40:53 UTC 2023] original='{"type":"http-01","url":"https://acme.zerossl.com/v2/DV90/chall/ewuCCj70jzNLV4PFny5A9w","status":"invalid","error":{}     ,"token":"hGQm-bqtomaXm0bEKEWsJP66GXJoIyzokQrXu3hSKRA"}'
[Sun Jan 29 05:40:53 UTC 2023] response='{"type":"http-01","url":"https://acme.zerossl.com/v2/DV90/chall/ewuCCj70jzNLV4PFny5A9w","status":"invalid","error":{}     ,"token":"hGQm-bqtomaXm0bEKEWsJP66GXJoIyzokQrXu3hSKRA"}'
[Sun Jan 29 05:40:53 UTC 2023] status='invalid'
[Sun Jan 29 05:40:53 UTC 2023] error='"error":{'
[Sun Jan 29 05:40:53 UTC 2023] errordetail
[Sun Jan 29 05:40:53 UTC 2023] cc.jplpoc.tk:Verify error:"error":{
[Sun Jan 29 05:40:53 UTC 2023] Debug: get token url.
[Sun Jan 29 05:40:53 UTC 2023] GET
[Sun Jan 29 05:40:53 UTC 2023] url='http://cc.jplpoc.tk/.well-known/acme-challenge/hGQm-bqtomaXm0bEKEWsJP66GXJoIyzokQrXu3hSKRA'
[Sun Jan 29 05:40:53 UTC 2023] timeout=1
[Sun Jan 29 05:40:53 UTC 2023] Http already initialized.
[Sun Jan 29 05:40:53 UTC 2023] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.3ytPi0j9HT  -g  --connect-timeout 1'
[Sun Jan 29 05:40:54 UTC 2023] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 28
[Sun Jan 29 05:40:54 UTC 2023] Here is the curl dump log:
[Sun Jan 29 05:40:54 UTC 2023] == Info:   Trying 144.24.82.41:80...
== Info: TCP_NODELAY set
== Info: Connection timed out after 1000 milliseconds
== Info: Closing connection 0
[Sun Jan 29 05:40:54 UTC 2023] ret='28'
[Sun Jan 29 05:40:54 UTC 2023] Skip for removelevel:
[Sun Jan 29 05:40:54 UTC 2023] pid='28940'
2023/01/29 05:40:54 socat[28940] N socat_signal(): handling signal 15
2023/01/29 05:40:54 socat[28940] W exiting on signal 15
2023/01/29 05:40:54 socat[28940] N socat_signal(): finishing signal 15
2023/01/29 05:40:54 socat[28940] N exit(143)
[Sun Jan 29 05:40:54 UTC 2023] No need to restore nginx, skip.
[Sun Jan 29 05:40:54 UTC 2023] _clearupdns
[Sun Jan 29 05:40:54 UTC 2023] dns_entries
[Sun Jan 29 05:40:54 UTC 2023] skip dns.
[Sun Jan 29 05:40:54 UTC 2023] _on_issue_err
[Sun Jan 29 05:40:54 UTC 2023] Please check log file for more details: /root/.acme.sh/acme.sh.log
[Sun Jan 29 05:40:54 UTC 2023] _chk_vlist='cc.jplpoc.tk#hGQm-bqtomaXm0bEKEWsJP66GXJoIyzokQrXu3hSKRA.zIeOF9i8MRANIKRGL-WoHSV-1hKHgKPaXjKeShLyJ2g#https://acme.z     erossl.com/v2/DV90/chall/ewuCCj70jzNLV4PFny5A9w#http-01#no,'
[Sun Jan 29 05:40:54 UTC 2023] start to deactivate authz
[Sun Jan 29 05:40:54 UTC 2023] Trigger domain validation.
[Sun Jan 29 05:40:54 UTC 2023] _t_url='https://acme.zerossl.com/v2/DV90/chall/ewuCCj70jzNLV4PFny5A9w'
[Sun Jan 29 05:40:54 UTC 2023] _t_key_authz='hGQm-bqtomaXm0bEKEWsJP66GXJoIyzokQrXu3hSKRA.zIeOF9i8MRANIKRGL-WoHSV-1hKHgKPaXjKeShLyJ2g'
[Sun Jan 29 05:40:54 UTC 2023] _t_vtype
[Sun Jan 29 05:40:54 UTC 2023] url='https://acme.zerossl.com/v2/DV90/chall/ewuCCj70jzNLV4PFny5A9w'
[Sun Jan 29 05:40:54 UTC 2023] payload='{}'
[Sun Jan 29 05:40:54 UTC 2023] Use cached jwk for file: /root/.acme.sh/ca/acme.zerossl.com/v2/DV90/account.key
[Sun Jan 29 05:40:54 UTC 2023] Use _CACHED_NONCE='1AoqVpEfrse3SXlS4MHaRDpyvGZAetOIDzsnHpy2qfA'
[Sun Jan 29 05:40:54 UTC 2023] nonce='1AoqVpEfrse3SXlS4MHaRDpyvGZAetOIDzsnHpy2qfA'
[Sun Jan 29 05:40:54 UTC 2023] POST
[Sun Jan 29 05:40:54 UTC 2023] _post_url='https://acme.zerossl.com/v2/DV90/chall/ewuCCj70jzNLV4PFny5A9w'
[Sun Jan 29 05:40:54 UTC 2023] body='{"protected": "eyJub25jZSI6ICIxQW9xVnBFZnJzZTNTWGxTNE1IYVJEcHl2R1pBZXRPSUR6c25IcHkycWZBIiwgInVybCI6ICJodHRwczovL2FjbWUuem     Vyb3NzbC5jb20vdjIvRFY5MC9jaGFsbC9ld3VDQ2o3MGp6TkxWNFBGbnk1QTl3IiwgImFsZyI6ICJFUzI1NiIsICJraWQiOiAiaHR0cHM6Ly9hY21lLnplcm9zc2wuY29tL3YyL0RWOTAvYWNjb3VudC9iNXhh     LUplazBrNzhBWVd6dHhud0ZRIn0", "payload": "e30", "signature": "w7z4KszababEfYPUx71cd18cgSrscvIFP_XiPs4z-9r4LX8o5vbi7NWZjrQ4xp1oeo1IYuakISv08hfH9mvMtA"}'
[Sun Jan 29 05:40:54 UTC 2023] _postContentType='application/jose+json'
[Sun Jan 29 05:40:54 UTC 2023] Http already initialized.
[Sun Jan 29 05:40:54 UTC 2023] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.3ytPi0j9HT  -g '
[Sun Jan 29 05:40:57 UTC 2023] _ret='0'
[Sun Jan 29 05:40:57 UTC 2023] responseHeaders='HTTP/2 200
`

**Comment by daijinp** [comment]
Sorry, there is a problem with my firewall configuration. Now it has been successfully used

**Comment by tcnf2008** [comment]
thanks,  I just had the same firewall configuration problem.

**Comment by jefflanglh** [comment]
我也遇到同样的问题
 I had the same problem

新的国内vps，安装os或者ubuntu系统都尝试过，均不行。同样的操作，同样的域名，海外vps则可以

It works in a us vps，but error in  china mainland vps

yum update -y #CentOS 命令
yum install -y curl #CentOS 命令
yum install -y socat #CentOS 命令
curl https://get.acme.sh/ | sh
~/.acme.sh/acme.sh --register-account -m xxxx[@xxxx](javascript:;).com
~/.acme.sh/acme.sh --issue -d mydomain.com --standalone
进行到这步时候

[2023年 02月 28日 星期二 23:50:09 CST] Using CA: https://acme.zerossl.com/v2/DV90

[2023年 02月 28日 星期二 23:50:09 CST] Standalone mode.
[2023年 02月 28日 星期二 23:50:09 CST] Creating domain key
[2023年 02月 28日 星期二 23:50:09 CST] The domain key is here: /root/.acme.sh/xxx(域名省去).com_ecc/xxx(域名省去).com.key
[2023年 02月 28日 星期二 23:50:09 CST] Single domain='xxx(域名省去).com'
[2023年 02月 28日 星期二 23:50:09 CST] Getting domain auth token for each domain
[2023年 02月 28日 星期二 23:50:15 CST] Getting webroot for domain='xxx(域名省去).com'
[2023年 02月 28日 星期二 23:50:15 CST] Verifying: xxx(域名省去).com
[2023年 02月 28日 星期二 23:50:15 CST] Standalone mode server
[2023年 02月 28日 星期二 23:50:18 CST] Processing The CA is processing your order please just wait. (1/30)
[2023年 02月 28日 星期二 23:50:23 CST] xxx(域名省去).com:Verify error:"error":{
[2023年 02月 28日 星期二 23:50:23 CST] Please add '--debug' or '--log' to check more details.
[2023年 02月 28日 星期二 23:50:23 CST] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh



 输入debug

[2023年 03月 01日 星期三 00:21:18 CST] xxx(域名省去).com:Verify error:"error":{
[2023年 03月 01日 星期三 00:21:18 CST] Debug: get token url.
[2023年 03月 01日 星期三 00:21:18 CST] GET
[2023年 03月 01日 星期三 00:21:18 CST] url='[http://xxx(域名省去).com/.well-known/acme-challenge/LaeLbf8HLv4qUNib3EQjRDrAIKZlTkumkS1oHJi-Pko](http://xinaozhou.com/.well-known/acme-challenge/LaeLbf8HLv4qUNib3EQjRDrAIKZlTkumkS1oHJi-Pko)'
[2023年 03月 01日 星期三 00:21:18 CST] timeout=1
[2023年 03月 01日 星期三 00:21:18 CST] _CURL='curl --silent --dump-header /root/.acme.sh/http.header -L -g --connect-timeout 1'
[2023年 03月 01日 星期三 00:21:20 CST] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 28

**Comment by jefflanglh** [comment]
If your VPS is in mainland china， the domain name server also needs to transfer back to Dnspod， otherwise, SSL won't work.
后来经过各种测试 发现国内服务器的域名证书，必须把域名也转回国内的DNS服务商（就是腾讯云的dnspod，freesslcn里面acme的配置命令就只有dns_dp一种，理论上用cloudflare命令就应该是dns_cf，这应该就是只能用dnspod或其他国内的服务商我猜）

所以国内vps装ssl证书，域名也必须转回国内，都需要实名认证 

目前测试就是这样 如果有其它意见欢迎留言

**Comment by ginamber** [comment]
> Sorry, there is a problem with my firewall configuration. Now it has been successfully used

that's the key problem!  thx!

**Comment by zhang-cuishan** [comment]
> firewall

I have been stop my firewall system, but it doesn't wor yet.

**Comment by zhang-cuishan** [comment]
> > Sorry, there is a problem with my firewall configuration. Now it has been successfully used
> 
> that's the key problem! thx!

I have been stop my firewall system, but it doesn't work yet.

**Comment by daanhan** [comment]
> Sorry, there is a problem with my firewall configuration. Now it has been successfully used

What's the problem? Can you descript it?
I am in the same situation, can not fix it now.

**Comment by kkureli** [comment]
any solution?

**Comment by Qinka** [comment]
I think the key to the error is ZeroSSL. I changed the server of ACME to Let's Encrypt, and then I succeeded.

I think:
```
response='{"type":"http-01","url":"https://acme.zerossl.com/v2/DV90/chall/ewuCCj70jzNLV4PFny5A9w","status":"invalid","error":{}     ,"token":"hGQm-bqtomaXm0bEKEWsJP66GXJoIyzokQrXu3hSKRA"}'
```
means ZeroSSL has a bug because Let's Encrypt doesn't.
