### ISSUE TITLE
OVH - libcurl error code 22 - this service does not exist

### ISSUE THREAD

**Issue by sudomax** [acmesh-official/acme.sh#4485]
Steps to reproduce
------------------

Debug log
-----------------

```
Using OVH endpoint: ovh-eu
[Wed Feb  1 21:24:20 UTC 2023] OVH_API='https://eu.api.ovh.com/1.0'
[Wed Feb  1 21:24:20 UTC 2023] Checking authentication
[Wed Feb  1 21:24:20 UTC 2023] domain
[Wed Feb  1 21:24:20 UTC 2023] GET
[Wed Feb  1 21:24:20 UTC 2023] url='https://eu.api.ovh.com/1.0/auth/time'
[Wed Feb  1 21:24:20 UTC 2023] timeout=30
[Wed Feb  1 21:24:20 UTC 2023] _CURL='curl --silent --dump-header /acme.sh/http.header  -L  --trace-ascii /tmp/tmp.Iui0mwRN3R  -g  --fail-with-body  --connect-timeout 30'
[Wed Feb  1 21:24:20 UTC 2023] ret='0'
[Wed Feb  1 21:24:20 UTC 2023] _ovh_p='[hidden](please add '--output-insecure' to see this value)'
[Wed Feb  1 21:24:20 UTC 2023] GET
[Wed Feb  1 21:24:20 UTC 2023] url='https://eu.api.ovh.com/1.0/domain'
[Wed Feb  1 21:24:20 UTC 2023] timeout=
[Wed Feb  1 21:24:20 UTC 2023] _CURL='curl --silent --dump-header /acme.sh/http.header  -L  --trace-ascii /tmp/tmp.Iui0mwRN3R  -g  --fail-with-body '
[Wed Feb  1 21:24:21 UTC 2023] ret='0'
[Wed Feb  1 21:24:21 UTC 2023] Consumer key is ok.
[Wed Feb  1 21:24:21 UTC 2023] First detect the root zone
[Wed Feb  1 21:24:21 UTC 2023] domain/zone/_acme-challenge.maxime-marechal.ovh
[Wed Feb  1 21:24:21 UTC 2023] GET
[Wed Feb  1 21:24:21 UTC 2023] url='https://eu.api.ovh.com/1.0/auth/time'
[Wed Feb  1 21:24:21 UTC 2023] timeout=30
[Wed Feb  1 21:24:21 UTC 2023] _CURL='curl --silent --dump-header /acme.sh/http.header  -L  --trace-ascii /tmp/tmp.Iui0mwRN3R  -g  --fail-with-body  --connect-timeout 30'
[Wed Feb  1 21:24:21 UTC 2023] ret='0'
[Wed Feb  1 21:24:21 UTC 2023] _ovh_p='[hidden](please add '--output-insecure' to see this value)'
[Wed Feb  1 21:24:21 UTC 2023] GET
[Wed Feb  1 21:24:21 UTC 2023] url='https://eu.api.ovh.com/1.0/domain/zone/_acme-challenge.maxime-marechal.ovh'
[Wed Feb  1 21:24:21 UTC 2023] timeout=
[Wed Feb  1 21:24:21 UTC 2023] _CURL='curl --silent --dump-header /acme.sh/http.header  -L  --trace-ascii /tmp/tmp.Iui0mwRN3R  -g  --fail-with-body '
[Wed Feb  1 21:24:21 UTC 2023] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 22
[Wed Feb  1 21:24:21 UTC 2023] ret='22'
[Wed Feb  1 21:24:21 UTC 2023] error {"message":"This service does not exist"}
[Wed Feb  1 21:24:21 UTC 2023] invalid domain
[Wed Feb  1 21:24:21 UTC 2023] Error add txt for domain:_acme-challenge.maxime-marechal.ovh
[Wed Feb  1 21:24:21 UTC 2023] _on_issue_err
```

**Comment by sudomax** [comment]
Already tried to upgrade and run again. Provided the --debug 2 snippet also

**Comment by jkohjk** [comment]
I encountered the same option. I found that --fail-with-body option causes bash to return error status. As a temporary workaround, comment out the block that sets --fail-with-body in acme.sh.

For acmesh developers, I found the code that checks for root domain relies on http error status but should still return bash success status. e.g. it checks for a.b.c.com, not found, then b.c.com, not found, then c.com is finally found. But the --fail-with-body options stops the loop after the first check, so top level domains will succeed but subdomains will fail.

**Comment by Neilpang** [comment]
fixed, please try again with `dev`

```
acme.sh  --upgrade -b dev
```

**Comment by beldred** [comment]
> acme.sh  --upgrade -b dev

Works after running the above to pull the dev changes.

**Comment by PMExtra** [comment]
@Neilpang I think we should explicitly allow the HTTP status code fail for these necessary cases, rather than implicitly ignore all status code fail.

**Comment by Neilpang** [comment]
@PMExtra   当初加这个选项是为啥? 我想不起来了.

**Comment by PMExtra** [comment]
@Neilpang 主要就是我们该不该认为 HTTP 4XX / 5XX 是失败，加了这个选项，curl 遇到 HTTP 4XX / 5XX 就会以非0值退出。否则，curl 会以 0 退出。

因为我的 deploy-hook/vault 希望能够判定 HTTP 4XX / 5XX 是 deploy 失败，所以我增加了这个参数。
对于其它接口，我认为同样的 4XX / 5XX 也应该被判定为失败而不是成功。

至于多次重试、多个URL需要fallback的场景，之前没考虑到会对这些场景产生副作用。但我认为一个高质量代码应该使用 `if ...` 来处理异常，或者用 `... || true` 来显式忽略异常。而不是直接让 curl 不抛出这类异常。

这个改动可能工作量不小，但我认为对于提升整体的代码质量和可靠性，这个改造是有必要的。

**Comment by PMExtra** [comment]
@Neilpang 4XX/5XX是否失败，取决于是否指定 `--fail` 或者 `--fail-with-body` 。两者的区别在于 `--fail` 遇到错误时返回非0并屏蔽 stdout ，而 `--fail-with-body` 会在返回非0但继续输出服务器返回的响应内容到标准输出。

对于 curl > 7.76 可以使用 --fail-with-body 以便输出更详细的错误信息。对于 curl <= 7.76 可以使用 --fail 或者 -f 简单的识别失败，但是无法获取具体的响应。
