### ISSUE TITLE
acme.sh: line 7975: --deploy: command not found

### ISSUE THREAD

**Issue by jenlampton** [acmesh-official/acme.sh#4499]
The Deploy command results in "command not found"  
Has `--deploy` been removed recently?

Steps to reproduce
------------------

1. Install the latest version of acme.sh
2. Issue a certificate (successfully) `acme.sh  --issue .....`
3. Attempt to deploy the certificate (unsuccessfully) `acme.sh  --deploy .....`

Debug log
-----------------
There is no debug log.
```
acme.sh  --deploy .....   --debug 2
> /home/username/.acme.sh/acme.sh: line 7975: --deploy: command not found
```
The error is the same with and without the `--debug 2` flag

Environment
------------------
I am attempting to deploy to an Apache server with cPanel on shared hosting, in this case the provider is NameCheap. 

References
------------
I have found several articles all recommending the use of the missing `--deploy` feature, as follows:
* Oct 5, 2022: https://www.ts-wiki.com/wiki/367/setup-free-let-s-encrypt-ssl-on-namecheap-by-using-acme-sh-in-cpanel 
* Sep 1 8, 2020: https://dev.to/atomar/let-s-encrypt-ssl-certificate-in-namecheap-autorenewal-verified-working-using-acme-sh-4m7i
* Jun 22, 2020: https://medium.com/@jonathanobise/how-to-setup-free-lets-encrypt-ssl-on-namecheap-using-acme-sh-in-cpanel-5a3d408071ba
* Feb 10, 2020: https://sito.express/en/2020/how-to/how-to-install-lets-encrypt-ssl-certificate-shared-server-acme-sh/

I did find one article from 2017 where someone had to write their own custom script to handle the deploy step:
* Feb 14, 2017 https://east.fm/posts/acme-sh-cpanel-a2hosting/index.html

**Comment by jenlampton** [comment]
I've already included that I was running the latest version, results of `acme.sh --upgrade` are
```
[Thu Feb  9 22:27:44 EST 2023] Already uptodate!
[Thu Feb  9 22:27:44 EST 2023] Upgrade success!
```

I've also already provided the "log", which does not exist, because the command was not found, and nothing was done, so nothing was logged.

**Comment by Neilpang** [comment]
No, its not removed.

![image](https://user-images.githubusercontent.com/8305679/218254955-148b0fdf-982f-4395-a06d-1357e35f4e92.png)

**Comment by jenlampton** [comment]
If there is another reason for the "command not found", and a recommended
solution, I'd love to hear about it.

**Comment by HRHDaniel** [comment]
@jenlampton can your provide the full command line with all the arguments you're passing, just mask sensitive values with *s, but it would be helpful to see the full command

**Comment by jenlampton** [comment]
Sure, this is the complete command:
```
.acme.sh/acme.sh —-deploy -d mydomain.com -d www.mydomain.com —-deploy-hook cpanel_uapi —-domain mydomain.com --domain www.mydomain.com
```

**Comment by HRHDaniel** [comment]
@jenlampton In the commands you just posted... the initial "-" in the "--" commands is not an actual "-".  When viewing it in your comment the first dash appears slightly longer than the second dash.  When I copy and paste your command into an editor and convert to hex, it's an extended value, not the "%2d" value like the second smaller dash.  Might be something with the way you are copying/pasting commands into your terminal, but I would suggest that you try again and manually type out the full command.
Also, "-d" is just a shorter alias for "--domain".  I don't think it hurts that you specified both, but it's redundant.

**Comment by jenlampton** [comment]
That was it! 
I tried again by typing `--deploy` manually, and it worked. 😄 
Thank you so much for spotting that!
