### ISSUE TITLE
error code 5510

### ISSUE THREAD

**Issue by garryde** [acmesh-official/acme.sh#4512]
Dears, I am using docker to deploy the certificate on Synology NAS, But I met an issue the error code is 5510.
I didn't find this code in the Synology API document, Is anyone met this issue?
Btw, I tried to mkdir '/acme.sh' in NAS, but the issue still exit.
```
[Sun Feb 19 17:58:21 UTC 2023] The domain 'DOMAIN' seems to have a ECC cert already, lets use ecc cert.
[Sun Feb 19 17:58:21 UTC 2023] Logging into localhost:5000
[Sun Feb 19 17:58:21 UTC 2023] Getting certificates in Synology DSM
[Sun Feb 19 17:58:21 UTC 2023] Generate form POST request
cat: /acme.sh/DOMAIN.com_ecc/garryde.com.cer: No such file or directory
cat: /acme.sh/DOMAIN.com_ecc/ca.cer: No such file or directory
[Sun Feb 19 17:58:21 UTC 2023] Upload certificate to the Synology DSM
[Sun Feb 19 17:58:21 UTC 2023] Unable to update certificate, error code {"error":{"code":5510},"success":false}
[Sun Feb 19 17:58:21 UTC 2023] Error deploy for domain:DOMAIN.com
[Sun Feb 19 17:58:21 UTC 2023] Deploy error.

```

**Comment by dmekhov** [comment]
I have the same issue, with the same error

> cat: /acme.sh/DOMAIN.com_ecc/DOMAIN.com.cer: No such file or directory
> cat: /acme.sh/DOMAIN.com_ecc/ca.cer: No such file or directory

but acme created only these files:

```
DOMAIN.com.conf
DOMAIN.com.csr
DOMAIN.com.csr.conf
DOMAIN.com.key
```

perhaps we should somehow tell to script to use these files instead of `cer`?

**Comment by HRHDaniel** [comment]
The synology_dsm script is attempting to upload a key, cert, and ca cert.  If you do not have all 3 of those in the domain folder, it looks like there was a problem during the certificate "issue".  Try to re issue the certificates and make sure that is successful before attempting to deploy.

**Comment by crane168** [comment]
![image](https://user-images.githubusercontent.com/26795319/222030466-950ff6dc-3f54-4b28-8978-58b7c692d9f0.png)
Now I also encounter this situation. It prompts that there is an Ecc certificate, but when copying the certificate, an error as shown in the picture is reported. I don't know what to do now. Please help me, thank you

**Comment by shancw96** [comment]
> ![image](https://user-images.githubusercontent.com/26795319/222030466-950ff6dc-3f54-4b28-8978-58b7c692d9f0.png) Now I also encounter this situation. It prompts that there is an Ecc certificate, but when copying the certificate, an error as shown in the picture is reported. I don't know what to do now. Please help me, thank you

i solved this problem by creating the folder manually
