### ISSUE TITLE
已经签发了ECC证书后无法再签发RSA证书？

### ISSUE THREAD

**Issue by jearton** [acmesh-official/acme.sh#4535]
Steps to reproduce
------------------

![image](https://user-images.githubusercontent.com/10370433/222892684-073e4f28-3c37-4b72-b84d-768c1a8b6f0c.png)

![image](https://user-images.githubusercontent.com/10370433/222893030-2d4dec39-4834-4536-8ab9-fdb722b50758.png)

我看了源码是这样写的，为啥不允许呢？

**Comment by Neilpang** [comment]
这是一个 bug  马上修

**Comment by Neilpang** [comment]
更新一下 最新版

```
acme.sh --upgrade
```
