### ISSUE TITLE
华为云国际版，可以申请证书，但不可更新

### ISSUE THREAD

**Issue by abuits** [acmesh-official/acme.sh#4549]
export HUAWEICLOUD_Username=<Your Username> # IAM Username
export HUAWEICLOUD_Password=<Your Password>
export HUAWEICLOUD_DomainName=<Your DomainName>

以上三个export HUAWEICLOUD值 已经按照文档正常填写

可以正常申请证书，但是发现没有自动更新证书，手动更新时报错：
dns_api(dns_huaweicloud): Error getting token.
重新填写三个export HUAWEICLOUD，更新成功。

**Comment by abuits** [comment]
更新时报错 dns_api(dns_huaweicloud): Error getting token.
重新填写三个export HUAWEICLOUD值后，更新成功。
是否申请后没有正确保存三个export HUAWEICLOUD值

**Comment by abuits** [comment]
https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_huaweicloud.sh
26行和77行是否有误?

**Comment by Neilpang** [comment]
fixed
