### ISSUE TITLE
The Yandex DNS API is no longer supported

### ISSUE THREAD

**Issue by WhiteAls** [acmesh-official/acme.sh#4555]
[The API will stop working on April 1, 2023. From March 24, the availability of the service will be limited.](https://web.archive.org/web/20231207063213/https://yandex.ru/dev/pdd/doc/about.html)
At the moment, the API is still working, but a large number of people will soon have issues updating certificates.
[A new version of the API for managing DNS records was released in February 2023.](https://yandex.ru/dev/api360/doc/ref/DomainDNSService.html)
I hope someone will pay attention to this issue and help with a pull request, as I'm not very proficient in Shell scripting 😓

**Comment by Stab1k** [comment]
The Mail for Domain API (pddimp.yandex.ru) is no longer available.

will it work?

**Comment by ProKn1fe** [comment]
I'm currently working of implement new yandex360 api. I have 20~ days before my certs will expire)

**Comment by NikitaCartes** [comment]
@ProKn1fe do you need some help with it?

**Comment by ProKn1fe** [comment]
Pull request #4599. Tested and worked in my personal environment.

**Comment by WhiteAls** [comment]
This issue will be resolved once pull request #5214 is merged.
