### ISSUE TITLE
How to globally disable public dns checks?

### ISSUE THREAD

**Issue by isuperwm** [acmesh-official/acme.sh#4558]
Hi,

I have already learned from [the official documentation](https://github.com/acmesh-official/acme.sh/wiki/dnscheck) that I can use `--dnssleep` to disable DNS detection. How can I do this globally?

Thanks a lot.

**Comment by Neilpang** [comment]
without  dns detectiong, how to wait till the txt records propgates?
Different dns providers may have different  dns sleep time.
So, please set the dns sleep time for each certs.
