### ISSUE TITLE
README : missing URL for Let'sEncrypt

### ISSUE THREAD

**Issue by fenugrec** [acmesh-official/acme.sh#4563]
https://github.com/acmesh-official/acme.sh/blob/cf3ff4c136f80aa55513c289b0da69243b4d264a/README.md?plain=1#L101

LE is the only provider without a clickable URL. 

Suggested fix
`[Let's Encrypt](https://letsencrypt.org/)`

**Comment by fenugrec** [comment]
Hi,
the master branch hasn't changed, was this fixed on a separate branch ?

**Comment by fenugrec** [comment]
Can we reopen. This has not changed

**Comment by Neilpang** [comment]
The other CA has a link to the wiki page, just because they need more instructions to use.
While for letsencrypt,  there is no need for a wiki page.
