### ISSUE TITLE
Using OPNsense option for DNS causes Cloudflare txt purging

### ISSUE THREAD

**Issue by MaxineBean** [acmesh-official/acme.sh#4570]
Steps to reproduce
------------------
Set up a certificate request using the OPNsense option for DNS. 

To reproduce: setup a DNS Challenge as below
![DNS Challange](https://user-images.githubusercontent.com/7060299/228599151-37103771-f3cf-4854-b0e5-2f3c3720668b.png)

setup a Certificate:
![Cert Options](https://user-images.githubusercontent.com/7060299/228599182-7e89e94e-b9da-45a9-9315-acf3cdda1cc8.png)

Issue / renew the certificate.
From there, you can see in the log the following messages:
![ACME Log](https://user-images.githubusercontent.com/7060299/228599243-a81c39e5-2d80-4072-9525-1bfc952ec77b.png)

Looking into the http.header file that gets generated you can see that it is set to Cloudflare
![http header file](https://user-images.githubusercontent.com/7060299/228599313-1f957608-621d-43d0-ae63-4f5e25e8e27a.png)

Even though the domain.conf file is setup correctly:
![domain conf file](https://user-images.githubusercontent.com/7060299/228599343-bac916e0-2907-4f67-8dfb-13579b5dc3fc.png)

Also, the txt records are added to the BIND zone setup, but not removed once the acme process fails. 
![BIND config](https://user-images.githubusercontent.com/7060299/228599423-37ce5d6b-0099-4558-8d86-90d5b962fad7.png)

Debug log
--------
NOTE: I truncated the log because otherwise, it would be a loop of the same thing over and over again until the process times out.

[Wed Mar 29 11:56:17 EDT 2023] _ret='0'
[Wed Mar 29 11:56:17 EDT 2023] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.yD6xPsZk '
[Wed Mar 29 11:56:17 EDT 2023] _post_url='https://cloudflare-dns.com/api/v1/purge?domain=_acme-challenge.exampledomain.com&type=TXT'
[Wed Mar 29 11:56:17 EDT 2023] POST
[Wed Mar 29 11:56:17 EDT 2023] Cloudflare purge TXT record for domain _acme-challenge.exampledomain.com
[Wed Mar 29 11:56:17 EDT 2023] _p_txtdomain='_acme-challenge.exampledomain.com'
[Wed Mar 29 11:56:17 EDT 2023] Not valid yet, let's wait 10 seconds and check next one.
[Wed Mar 29 11:56:17 EDT 2023] ret='0'
[Wed Mar 29 11:56:17 EDT 2023] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.yD6xPsZk '
[Wed Mar 29 11:56:17 EDT 2023] timeout=
[Wed Mar 29 11:56:17 EDT 2023] url='https://cloudflare-dns.com/dns-query?name=_acme-challenge.exampledomain.com&type=TXT'
[Wed Mar 29 11:56:17 EDT 2023] GET
[Wed Mar 29 11:56:17 EDT 2023] _c_txt='e2EwjI8kcGrxkVh3fVG4gDawBvldSRpKAUuXsGmTd1g'
[Wed Mar 29 11:56:17 EDT 2023] _c_aliasdomain='_acme-challenge.exampledomain.com'
[Wed Mar 29 11:56:17 EDT 2023] _c_txtdomain='_acme-challenge.exampledomain.com'
[Wed Mar 29 11:56:17 EDT 2023] Checking exampledomain.com for _acme-challenge.exampledomain.com
[Wed Mar 29 11:56:17 EDT 2023] d_api='/usr/local/share/examples/acme.sh/dnsapi/dns_opnsense.sh'
[Wed Mar 29 11:56:17 EDT 2023] txt='e2EwjI8kcGrxkVh3fVG4gDawBvldSRpKAUuXsGmTd1g'
[Wed Mar 29 11:56:17 EDT 2023] aliasDomain='_acme-challenge.exampledomain.com'
[Wed Mar 29 11:56:16 EDT 2023] txtdomain='_acme-challenge.exampledomain.com'
[Wed Mar 29 11:56:16 EDT 2023] d='exampledomain.com'
[Wed Mar 29 11:56:06 EDT 2023] _ret='0'
[Wed Mar 29 11:56:06 EDT 2023] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.yD6xPsZk '
[Wed Mar 29 11:56:06 EDT 2023] _post_url='https://cloudflare-dns.com/api/v1/purge?domain=_acme-challenge.exampledomain.com&type=TXT'
[Wed Mar 29 11:56:06 EDT 2023] POST
[Wed Mar 29 11:56:06 EDT 2023] Cloudflare purge TXT record for domain _acme-challenge.exampledomain.com
[Wed Mar 29 11:56:06 EDT 2023] _p_txtdomain='_acme-challenge.exampledomain.com'
[Wed Mar 29 11:56:06 EDT 2023] Not valid yet, let's wait 10 seconds and check next one.
[Wed Mar 29 11:56:06 EDT 2023] ret='0'
[Wed Mar 29 11:56:06 EDT 2023] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.yD6xPsZk '
[Wed Mar 29 11:56:06 EDT 2023] timeout=
[Wed Mar 29 11:56:06 EDT 2023] url='https://cloudflare-dns.com/dns-query?name=_acme-challenge.exampledomain.com&type=TXT'
[Wed Mar 29 11:56:06 EDT 2023] GET
[Wed Mar 29 11:56:06 EDT 2023] Use cloudflare doh server
[Wed Mar 29 11:56:06 EDT 2023] ret='0'
[Wed Mar 29 11:56:06 EDT 2023] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.yD6xPsZk --connect-timeout 1'
[Wed Mar 29 11:56:06 EDT 2023] timeout=1
[Wed Mar 29 11:56:06 EDT 2023] url='https://cloudflare-dns.com'
[Wed Mar 29 11:56:06 EDT 2023] GET
[Wed Mar 29 11:56:06 EDT 2023] Detect dns server first.
[Wed Mar 29 11:56:06 EDT 2023] _c_txt='C2KXN_BnGcYUcoeDN_OgcclUlzgGzockoAxJ_y9MyUg'
[Wed Mar 29 11:56:06 EDT 2023] _c_aliasdomain='_acme-challenge.exampledomain.com'
[Wed Mar 29 11:56:06 EDT 2023] _c_txtdomain='_acme-challenge.exampledomain.com'
[Wed Mar 29 11:56:06 EDT 2023] Checking exampledomain.com for _acme-challenge.exampledomain.com
[Wed Mar 29 11:56:06 EDT 2023] d_api='/usr/local/share/examples/acme.sh/dnsapi/dns_opnsense.sh'
[Wed Mar 29 11:56:06 EDT 2023] txt='C2KXN_BnGcYUcoeDN_OgcclUlzgGzockoAxJ_y9MyUg'
[Wed Mar 29 11:56:06 EDT 2023] aliasDomain='_acme-challenge.exampledomain.com'
[Wed Mar 29 11:56:06 EDT 2023] txtdomain='_acme-challenge.exampledomain.com'
[Wed Mar 29 11:56:06 EDT 2023] d='exampledomain.com'
[Wed Mar 29 11:56:06 EDT 2023] See: https://github.com/acmesh-official/acme.sh/wiki/dnscheck
[Wed Mar 29 11:56:06 EDT 2023] You can use '--dnssleep' to disable public dns checks.
[Wed Mar 29 11:55:46 EDT 2023] Let's check each DNS record now. Sleep 20 seconds first.
[Wed Mar 29 11:55:46 EDT 2023] The txt record is added: Success.
[Wed Mar 29 11:55:46 EDT 2023] Record created
[Wed Mar 29 11:55:46 EDT 2023] _ret='0'
[Wed Mar 29 11:55:45 EDT 2023] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.yD6xPsZk --insecure '
[Wed Mar 29 11:55:45 EDT 2023] _post_url='https://DN9rQLde6YyL8u1vLlR2vDhM2A%2bzeELBcWjaFg%2bDYQZdA:SqLhg9nC21Rm0y4wmThWzL9ZZwP0heqUGBrSlT%2b5JSxSaJlnvttKG5pJVo5RDJ0d4f5DiFlW%2b1wsnNNu@opnsense.exampledomaincom:443/api/bind/
[Wed Mar 29 11:55:45 EDT 2023] POST
[Wed Mar 29 11:55:45 EDT 2023] data='{}'
[Wed Mar 29 11:55:45 EDT 2023] _ret='0'
[Wed Mar 29 11:55:45 EDT 2023] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.yD6xPsZk --insecure '
[Wed Mar 29 11:55:45 EDT 2023] _post_url='https://DN9rQLde6YyL8u1vLlR2vDhM2A%2bzeELBcWjaFg%2bDYQZdA:SqLhg9nC21Rm0y4wmThWzL9ZZwP0heqUGBrSlT%2b5JSxSaJlnvttKG5pJVo5RDJ0d4f5DiFlW%2b1wsnNNu@opnsense.exampledomaincom:443/api/bind/
[Wed Mar 29 11:55:45 EDT 2023] POST
[Wed Mar 29 11:55:45 EDT 2023] data='{"record":{"enabled":"1","domain":"f4a79a9a-4ab2-41cb-b768-fdcfe7a9ad4d","name":"_acme-challenge","type":"TXT",ldSRpKAUuXsGmTd1g"}}'
[Wed Mar 29 11:55:45 EDT 2023] _acme-challenge.exampledomain.com{1} record not found
[Wed Mar 29 11:55:45 EDT 2023] ret='0'
[Wed Mar 29 11:55:45 EDT 2023] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.yD6xPsZk --insecure '
[Wed Mar 29 11:55:45 EDT 2023] timeout=
[Wed Mar 29 11:55:45 EDT 2023] url='https://DN9rQLde6YyL8u1vLlR2vDhM2A%2bzeELBcWjaFg%2bDYQZdA:SqLhg9nC21Rm0y4wmThWzL9ZZwP0heqUGBrSlT%2b5JSxSaJlnvttKG5pJVo5RDJ0d4f5DiFlW%2b1wsnNNu@opnsense.exampledomain.com:443api/bind/
[Wed Mar 29 11:55:45 EDT 2023] GET
[Wed Mar 29 11:55:45 EDT 2023] _domainid='f4a79a9a-4ab2-41cb-b768-fdcfe7a9ad4d'
[Wed Mar 29 11:55:45 EDT 2023] _host='_acme-challenge'
[Wed Mar 29 11:55:45 EDT 2023] _domain='exampledomain.com'
[Wed Mar 29 11:55:45 EDT 2023] id='f4a79a9a-4ab2-41cb-b768-fdcfe7a9ad4d'
[Wed Mar 29 11:55:45 EDT 2023] h='exampledomain.com'
[Wed Mar 29 11:55:45 EDT 2023] ret='0'
[Wed Mar 29 11:55:45 EDT 2023] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.yD6xPsZk --insecure '
[Wed Mar 29 11:55:45 EDT 2023] timeout=
[Wed Mar 29 11:55:45 EDT 2023] url='https://DN9rQLde6YyL8u1vLlR2vDhM2A%2bzeELBcWjaFg%2bDYQZdA:SqLhg9nC21Rm0y4wmThWzL9ZZwP0heqUGBrSlT%2b5JSxSaJlnvttKG5pJVo5RDJ0d4f5DiFlW%2b1wsnNNu@opnsense.exampledomain.com:443api/bind/
[Wed Mar 29 11:55:45 EDT 2023] GET
[Wed Mar 29 11:55:45 EDT 2023] Detect root zone
[Wed Mar 29 11:55:45 EDT 2023] Adding record _acme-challenge.exampledomain.com with challenge: e2EwjI8kcGrxkVh3fVG4gDawBvldSRpKAUuXsGmTd1g
[Wed Mar 29 11:55:45 EDT 2023] ret='0'
[Wed Mar 29 11:55:45 EDT 2023] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.yD6xPsZk --insecure '
[Wed Mar 29 11:55:45 EDT 2023] timeout=
[Wed Mar 29 11:55:45 EDT 2023] url='https://DN9rQLde6YyL8u1vLlR2vDhM2A%2bzeELBcWjaFg%2bDYQZdA:SqLhg9nC21Rm0y4wmThWzL9ZZwP0heqUGBrSlT%2b5JSxSaJlnvttKG5pJVo5RDJ0d4f5DiFlW%2b1wsnNNu@opnsense.exampledomain.com:443api/bind/
[Wed Mar 29 11:55:45 EDT 2023] GET
[Wed Mar 29 11:55:45 EDT 2023] Adding txt value: e2EwjI8kcGrxkVh3fVG4gDawBvldSRpKAUuXsGmTd1g for domain: _acme-challenge.exampledomain.com
[Wed Mar 29 11:55:45 EDT 2023] Found domain api file: /usr/local/share/examples/acme.sh/dnsapi/dns_opnsense.sh
[Wed Mar 29 11:55:45 EDT 2023] d_api='/usr/local/share/examples/acme.sh/dnsapi/dns_opnsense.sh'
[Wed Mar 29 11:55:45 EDT 2023] txt='e2EwjI8kcGrxkVh3fVG4gDawBvldSRpKAUuXsGmTd1g'
[Wed Mar 29 11:55:45 EDT 2023] txtdomain='_acme-challenge.exampledomain.com'
[Wed Mar 29 11:55:45 EDT 2023] _d_alias
[Wed Mar 29 11:55:45 EDT 2023] d='*.exampledomain.com'
[Wed Mar 29 11:55:44 EDT 2023] The txt record is added: Success.
[Wed Mar 29 11:55:44 EDT 2023] Record created
[Wed Mar 29 11:55:44 EDT 2023] _ret='0'
[Wed Mar 29 11:55:44 EDT 2023] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.yD6xPsZk --insecure '
[Wed Mar 29 11:55:44 EDT 2023] _post_url='https://DN9rQLde6YyL8u1vLlR2vDhM2A%2bzeELBcWjaFg%2bDYQZdA:SqLhg9nC21Rm0y4wmThWzL9ZZwP0heqUGBrSlT%2b5JSxSaJlnvttKG5pJVo5RDJ0d4f5DiFlW%2b1wsnNNu@opnsense.exampledomaincom:443/api/bind/
[Wed Mar 29 11:55:44 EDT 2023] POST
[Wed Mar 29 11:55:44 EDT 2023] data='{}'
[Wed Mar 29 11:55:44 EDT 2023] _ret='0'
[Wed Mar 29 11:55:44 EDT 2023] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.yD6xPsZk --insecure '
[Wed Mar 29 11:55:44 EDT 2023] _post_url='https://DN9rQLde6YyL8u1vLlR2vDhM2A%2bzeELBcWjaFg%2bDYQZdA:SqLhg9nC21Rm0y4wmThWzL9ZZwP0heqUGBrSlT%2b5JSxSaJlnvttKG5pJVo5RDJ0d4f5DiFlW%2b1wsnNNu@opnsense.exampledomaincom:443/api/bind/
[Wed Mar 29 11:55:44 EDT 2023] POST
[Wed Mar 29 11:55:44 EDT 2023] data='{"record":{"enabled":"1","domain":"f4a79a9a-4ab2-41cb-b768-fdcfe7a9ad4d","name":"_acme-challenge","type":"TXT",gGzockoAxJ_y9MyUg"}}'
[Wed Mar 29 11:55:44 EDT 2023] _acme-challenge.exampledomain.com{1} record not found
[Wed Mar 29 11:55:44 EDT 2023] ret='0'
[Wed Mar 29 11:55:44 EDT 2023] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.yD6xPsZk --insecure '
[Wed Mar 29 11:55:44 EDT 2023] timeout=
[Wed Mar 29 11:55:44 EDT 2023] url='https://DN9rQLde6YyL8u1vLlR2vDhM2A%2bzeELBcWjaFg%2bDYQZdA:SqLhg9nC21Rm0y4wmThWzL9ZZwP0heqUGBrSlT%2b5JSxSaJlnvttKG5pJVo5RDJ0d4f5DiFlW%2b1wsnNNu@opnsense.exampledomain.com:443api/bind/
[Wed Mar 29 11:55:44 EDT 2023] GET
[Wed Mar 29 11:55:44 EDT 2023] _domainid='f4a79a9a-4ab2-41cb-b768-fdcfe7a9ad4d'
[Wed Mar 29 11:55:44 EDT 2023] _host='_acme-challenge'
[Wed Mar 29 11:55:44 EDT 2023] _domain='exampledomain.com'
[Wed Mar 29 11:55:44 EDT 2023] id='f4a79a9a-4ab2-41cb-b768-fdcfe7a9ad4d'
[Wed Mar 29 11:55:44 EDT 2023] h='exampledomain.com'
[Wed Mar 29 11:55:44 EDT 2023] ret='0'
[Wed Mar 29 11:55:44 EDT 2023] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.yD6xPsZk --insecure '
[Wed Mar 29 11:55:44 EDT 2023] timeout=
[Wed Mar 29 11:55:44 EDT 2023] url='https://DN9rQLde6YyL8u1vLlR2vDhM2A%2bzeELBcWjaFg%2bDYQZdA:SqLhg9nC21Rm0y4wmThWzL9ZZwP0heqUGBrSlT%2b5JSxSaJlnvttKG5pJVo5RDJ0d4f5DiFlW%2b1wsnNNu@opnsense.exampledomain.com:443api/bind/
[Wed Mar 29 11:55:44 EDT 2023] GET
[Wed Mar 29 11:55:44 EDT 2023] Detect root zone
[Wed Mar 29 11:55:44 EDT 2023] Adding record _acme-challenge.exampledomain.com with challenge: C2KXN_BnGcYUcoeDN_OgcclUlzgGzockoAxJ_y9MyUg
[Wed Mar 29 11:55:44 EDT 2023] ret='0'
[Wed Mar 29 11:55:44 EDT 2023] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.yD6xPsZk --insecure '
[Wed Mar 29 11:55:43 EDT 2023] timeout=
[Wed Mar 29 11:55:43 EDT 2023] url='https://DN9rQLde6YyL8u1vLlR2vDhM2A%2bzeELBcWjaFg%2bDYQZdA:SqLhg9nC21Rm0y4wmThWzL9ZZwP0heqUGBrSlT%2b5JSxSaJlnvttKG5pJVo5RDJ0d4f5DiFlW%2b1wsnNNu@opnsense.exampledomain.com:443api/bind/
[Wed Mar 29 11:55:43 EDT 2023] GET
[Wed Mar 29 11:55:43 EDT 2023] Adding txt value: C2KXN_BnGcYUcoeDN_OgcclUlzgGzockoAxJ_y9MyUg for domain: _acme-challenge.exampledomain.com
[Wed Mar 29 11:55:43 EDT 2023] Found domain api file: /usr/local/share/examples/acme.sh/dnsapi/dns_opnsense.sh
[Wed Mar 29 11:55:43 EDT 2023] d_api='/usr/local/share/examples/acme.sh/dnsapi/dns_opnsense.sh'
[Wed Mar 29 11:55:43 EDT 2023] txt='C2KXN_BnGcYUcoeDN_OgcclUlzgGzockoAxJ_y9MyUg'
[Wed Mar 29 11:55:43 EDT 2023] txtdomain='_acme-challenge.exampledomain.com'
[Wed Mar 29 11:55:43 EDT 2023] _d_alias
[Wed Mar 29 11:55:43 EDT 2023] d='exampledomain.com'
[Wed Mar 29 11:55:43 EDT 2023] vlist='exampledomain.com#OtY8HVDS5OpO_4v08Gu3dLO5USotOVjiS-ZnmPNNBsE.JzvY4SIBvmcgJ3b1HKx-bhsCZBWWbOr0oBE4v8I5SNk#https://acme-staging-v02.api.01764/OwtLEg#dns-01#dns_opnsense,*exampledomain.com#-iACSzbStea1q-agoBRg2n5FdjbxDHkHvmQesH2h_O4.JzvY4SIBvmcgJ3b1HKx-bhsCZBWWbOr0oBE4v8I5SNk#https://acme-staging-v02.api.01754/erw0Sg#dns-01#dns_opnsense,'
[Wed Mar 29 11:55:43 EDT 2023] d
[Wed Mar 29 11:55:43 EDT 2023] dvlist='*.exampledomain.com#-iACSzbStea1q-agoBRg2n5FdjbxDHkHvmQesH2h_O4.JzvY4SIBvmcgJ3b1HKx-bhsCZBWWbOr0oBE4v8I5SNk#https://acme-staging-v02.api.01754/erw0Sg#dns-01#dns_opnsense'
[Wed Mar 29 11:55:43 EDT 2023] keyauthorization='-iACSzbStea1q-agoBRg2n5FdjbxDHkHvmQesH2h_O4.JzvY4SIBvmcgJ3b1HKx-bhsCZBWWbOr0oBE4v8I5SNk'
[Wed Mar 29 11:55:43 EDT 2023] uri='https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/5924301754/erw0Sg'
[Wed Mar 29 11:55:43 EDT 2023] token='-iACSzbStea1q-agoBRg2n5FdjbxDHkHvmQesH2h_O4'
[Wed Mar 29 11:55:43 EDT 2023] entry='"type":"dns-01","status":"pending","url":"https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/5924301754/erw0Sg",bxDHkHvmQesH2h_O4"'
[Wed Mar 29 11:55:43 EDT 2023] _currentRoot='dns_opnsense'
[Wed Mar 29 11:55:43 EDT 2023] _w='dns_opnsense'
[Wed Mar 29 11:55:43 EDT 2023] Getting webroot for domain='*.exampledomain.com'
[Wed Mar 29 11:55:43 EDT 2023] d='*.exampledomain.com'
[Wed Mar 29 11:55:43 EDT 2023] dvlist='exampledomain.com#OtY8HVDS5OpO_4v08Gu3dLO5USotOVjiS-ZnmPNNBsE.JzvY4SIBvmcgJ3b1HKx-bhsCZBWWbOr0oBE4v8I5SNk#https://acme-staging-v02.api.01764/OwtLEg#dns-01#dns_opnsense'
[Wed Mar 29 11:55:43 EDT 2023] keyauthorization='OtY8HVDS5OpO_4v08Gu3dLO5USotOVjiS-ZnmPNNBsE.JzvY4SIBvmcgJ3b1HKx-bhsCZBWWbOr0oBE4v8I5SNk'
[Wed Mar 29 11:55:43 EDT 2023] uri='https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/5924301764/OwtLEg'
[Wed Mar 29 11:55:43 EDT 2023] token='OtY8HVDS5OpO_4v08Gu3dLO5USotOVjiS-ZnmPNNBsE'
[Wed Mar 29 11:55:43 EDT 2023] entry='"type":"dns-01","status":"pending","url":"https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/5924301764/OwtLEg",otOVjiS-ZnmPNNBsE"'
[Wed Mar 29 11:55:43 EDT 2023] _currentRoot='dns_opnsense'
[Wed Mar 29 11:55:43 EDT 2023] _w='dns_opnsense'
[Wed Mar 29 11:55:43 EDT 2023] Getting webroot for domain='exampledomain.com'
[Wed Mar 29 11:55:43 EDT 2023] d='exampledomain.com'
[Wed Mar 29 11:55:43 EDT 2023] code='200'
[Wed Mar 29 11:55:43 EDT 2023] _ret='0'
[Wed Mar 29 11:55:43 EDT 2023] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.yD6xPsZk '
[Wed Mar 29 11:55:43 EDT 2023] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/5924301764'
[Wed Mar 29 11:55:43 EDT 2023] POST
[Wed Mar 29 11:55:43 EDT 2023] payload
[Wed Mar 29 11:55:43 EDT 2023] url='https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/5924301764'
[Wed Mar 29 11:55:43 EDT 2023] code='200'
[Wed Mar 29 11:55:43 EDT 2023] _ret='0'
[Wed Mar 29 11:55:43 EDT 2023] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.yD6xPsZk '
[Wed Mar 29 11:55:43 EDT 2023] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/5924301754'
[Wed Mar 29 11:55:42 EDT 2023] POST
[Wed Mar 29 11:55:42 EDT 2023] payload
[Wed Mar 29 11:55:42 EDT 2023] url='https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/5924301754'
[Wed Mar 29 11:55:42 EDT 2023] Le_OrderFinalize='https://acme-staging-v02.api.letsencrypt.org/acme/finalize/95588264/8007584344'
[Wed Mar 29 11:55:42 EDT 2023] Le_LinkOrder='https://acme-staging-v02.api.letsencrypt.org/acme/order/95588264/8007584344'
[Wed Mar 29 11:55:42 EDT 2023] code='201'
[Wed Mar 29 11:55:42 EDT 2023] _ret='0'
[Wed Mar 29 11:55:42 EDT 2023] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.yD6xPsZk '
[Wed Mar 29 11:55:42 EDT 2023] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/new-order'
[Wed Mar 29 11:55:42 EDT 2023] POST
[Wed Mar 29 11:55:42 EDT 2023] _ret='0'
[Wed Mar 29 11:55:42 EDT 2023] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.yD6xPsZk -I '
[Wed Mar 29 11:55:42 EDT 2023] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce'
[Wed Mar 29 11:55:42 EDT 2023] HEAD
[Wed Mar 29 11:55:41 EDT 2023] RSA key
[Wed Mar 29 11:55:41 EDT 2023] payload='{"identifiers": [{"type":"dns","value":"exampledomain.com"},{"type":"dns","value":"*.exampledomain.com"}]}'
[Wed Mar 29 11:55:41 EDT 2023] url='https://acme-staging-v02.api.letsencrypt.org/acme/new-order'
[Wed Mar 29 11:55:41 EDT 2023] d
[Wed Mar 29 11:55:41 EDT 2023] d='*.exampledomain.com'
[Wed Mar 29 11:55:41 EDT 2023] Getting domain auth token for each domain
[Wed Mar 29 11:55:41 EDT 2023] Multi domain='DNS:exampledomain.com,DNS:*.exampledomain.com'
[Wed Mar 29 11:55:41 EDT 2023] _createcsr
[Wed Mar 29 11:55:41 EDT 2023] Read key length:4096
[Wed Mar 29 11:55:41 EDT 2023] _saved_account_key_hash is not changed, skip register account.
[Wed Mar 29 11:55:41 EDT 2023] d
[Wed Mar 29 11:55:41 EDT 2023] _currentRoot='dns_opnsense'
[Wed Mar 29 11:55:41 EDT 2023] Check for domain='*.exampledomain.com'
[Wed Mar 29 11:55:41 EDT 2023] d='*.exampledomain.com'
[Wed Mar 29 11:55:41 EDT 2023] _currentRoot='dns_opnsense'
[Wed Mar 29 11:55:41 EDT 2023] Check for domain='exampledomain.com'
[Wed Mar 29 11:55:41 EDT 2023] d='exampledomain.com'
[Wed Mar 29 11:55:41 EDT 2023] Le_LocalAddress
[Wed Mar 29 11:55:41 EDT 2023] _chk_alt_domains='*.exampledomain.com'
[Wed Mar 29 11:55:41 EDT 2023] _chk_main_domain='exampledomain.com'
[Wed Mar 29 11:55:41 EDT 2023] _on_before_issue
[Wed Mar 29 11:55:41 EDT 2023] Using CA: https://acme-staging-v02.api.letsencrypt.org/directory
[Wed Mar 29 11:55:41 EDT 2023] ACME_NEW_NONCE='https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce'
[Wed Mar 29 11:55:41 EDT 2023] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf'
[Wed Mar 29 11:55:41 EDT 2023] ACME_REVOKE_CERT='https://acme-staging-v02.api.letsencrypt.org/acme/revoke-cert'
[Wed Mar 29 11:55:41 EDT 2023] ACME_NEW_ACCOUNT='https://acme-staging-v02.api.letsencrypt.org/acme/new-acct'
[Wed Mar 29 11:55:41 EDT 2023] ACME_NEW_ORDER='https://acme-staging-v02.api.letsencrypt.org/acme/new-order'
[Wed Mar 29 11:55:41 EDT 2023] ACME_NEW_AUTHZ
[Wed Mar 29 11:55:41 EDT 2023] ACME_KEY_CHANGE='https://acme-staging-v02.api.letsencrypt.org/acme/key-change'
[Wed Mar 29 11:55:41 EDT 2023] ret='0'
[Wed Mar 29 11:55:40 EDT 2023] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header -L --trace-ascii /tmp/tmp.RDowbdiB '
[Wed Mar 29 11:55:40 EDT 2023] timeout=
[Wed Mar 29 11:55:40 EDT 2023] url='https://acme-staging-v02.api.letsencrypt.org/directory'
[Wed Mar 29 11:55:40 EDT 2023] GET
[Wed Mar 29 11:55:40 EDT 2023] _init api for server: https://acme-staging-v02.api.letsencrypt.org/directory
[Wed Mar 29 11:55:40 EDT 2023] Using ACME_DIRECTORY: https://acme-staging-v02.api.letsencrypt.org/directory
[Wed Mar 29 11:55:40 EDT 2023] Le_NextRenewTime
[Wed Mar 29 11:55:40 EDT 2023] DOMAIN_PATH='/var/etc/acme-client/home/exampledomain.com'
[Wed Mar 29 11:55:40 EDT 2023] ACME_DIRECTORY='https://acme-staging-v02.api.letsencrypt.org/directory'
[Wed Mar 29 11:55:40 EDT 2023] Using config home:/var/etc/acme-client/home
[Wed Mar 29 11:55:40 EDT 2023] _alt_domains='*.exampledomain.com'
[Wed Mar 29 11:55:40 EDT 2023] _main_domain='exampledomain.com'
[Wed Mar 29 11:55:40 EDT 2023] Running cmd: issue
[Wed Mar 29 11:55:40 EDT 2023] Using server: https://acme-staging-v02.api.letsencrypt.org/directory

**Comment by Neilpang** [comment]
add a `--dnssleep  60` parameter to avoid using cloudflare.
