### ISSUE TITLE
How do I use docker deploy hook for multiple containers/domains.

### ISSUE THREAD

**Issue by nbish11** [acmesh-official/acme.sh#4589]
As it says in title. The documentation isn't very clear on whether or not this is possible.

**Comment by oeiber** [comment]
Same issue here. Docker hook seems only to deploy to one container. As I can see in the debug log, the array returned to docker.sh includes all containers containing the tag.

**Comment by Neilpang** [comment]
it's not supported yet.

**Comment by rea1shane** [comment]
@Neilpang Can we support it?

**Comment by Neilpang** [comment]
@rea1shane  可以起多个 acme.sh 的 container,  每一个对应一个证书.    每一个acme.sh 的container 里面, 其实就一个crond进程, 开销很小.
