### ISSUE TITLE
我该如何在一台服务器上自动更新并安装多个域名证书？

### ISSUE THREAD

**Issue by wang745125665** [acmesh-official/acme.sh#4600]
我尝试了，写两个install-cert ，但是他只执行了后面的那个，所以acme可以支持同时安装两个不同的域名证书吗

Steps to reproduce
------------------
/root/.acme.sh/acme.sh --install-cert -d *.comet.example.com \
--key-file       /home/www/files/acme/comet.example.com.key.pem  \
--fullchain-file /home/www/files/acme/comet.example.com.cert.pem \
--install-cert -d *.example.com \
--key-file       /home/www/files/acme/example.com.key.pem  \
--fullchain-file /home/www/files/acme/example.com.cert.pem \
--reloadcmd     "docker restart web_server"  --debug 2

Debug log
-----------------

[Mon Apr 17 11:58:08 CST 2023] Lets find script dir.
[Mon Apr 17 11:58:08 CST 2023] _SCRIPT_='/root/.acme.sh/acme.sh'
[Mon Apr 17 11:58:08 CST 2023] _script='/root/.acme.sh/acme.sh'
[Mon Apr 17 11:58:08 CST 2023] _script_home='/root/.acme.sh'
[Mon Apr 17 11:58:08 CST 2023] Using config home:/root/.acme.sh
[Mon Apr 17 11:58:08 CST 2023] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.6
[Mon Apr 17 11:58:08 CST 2023] Running cmd: installcert
[Mon Apr 17 11:58:08 CST 2023] Using config home:/root/.acme.sh
[Mon Apr 17 11:58:08 CST 2023] default_acme_server
[Mon Apr 17 11:58:08 CST 2023] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Mon Apr 17 11:58:08 CST 2023] _ACME_SERVER_HOST='acme.zerossl.com'
[Mon Apr 17 11:58:08 CST 2023] _ACME_SERVER_PATH='v2/DV90'
[Mon Apr 17 11:58:08 CST 2023] DOMAIN_PATH='/root/.acme.sh/*.comet.example.com'
[Mon Apr 17 11:58:08 CST 2023] Installing key to: /home/www/files/acme/example.com.key.pem
[Mon Apr 17 11:58:08 CST 2023] Installing full chain to: /home/www/files/acme/example.com.cert.pem
[Mon Apr 17 11:58:08 CST 2023] Run reload cmd: docker restart web_server
web_server
[Mon Apr 17 11:58:18 CST 2023] Reload success

**Comment by Neilpang** [comment]
目前只能保存最后一次 installcert.

想要执行多个任务, 可以 自己写一个 脚本,  然后通过 `reloadcmd` 来执行.

```
acme.sh --install-cert  -d xxxxxx   --reloadcmd  /path/to/my/reload.sh
```
