### ISSUE TITLE
DNS OVH - Add txt record error

### ISSUE THREAD

**Issue by RafalHo** [acmesh-official/acme.sh#4601]
Hello,

I launched acme.sh in docker on my Synology with the command: acme.sh --issue -d '*.mydomain.org' --dns dns_ovh --server letsencrypt
Unfortunately, I get this message:
```
[Mon Apr 17 15:04:47 UTC 2023] Using OVH endpoint: ovh-eu
[Mon Apr 17 15:04:47 UTC 2023] Checking authentication
[Mon Apr 17 15:04:47 UTC 2023] Consumer key is ok.
[Mon Apr 17 15:04:48 UTC 2023] Adding record
[Mon Apr 17 15:04:48 UTC 2023] Add txt record error.
[Mon Apr 17 15:04:48 UTC 2023] Error add txt for domain:_acme-challenge.mydomain.org
```

I have purchased a domain at OVH, redirected to my IP - it works flawlessly. I wanted to use acme.sh to generate a wildcard certificate.
I generated API access data for OVH using `https://api.ovh.com/createToken/?GET=/domain/zone/*&POST=/domain/zone/*&PUT=/domain/zone/*&DELETE=/domain/ zone/*/record/*`

Can anyone suggest where is the error?

**Comment by RafalHo** [comment]
[Mon Apr 17 15:12:50 UTC 2023] Using server: https://acme-v02.api.letsencrypt.org/directory
[Mon Apr 17 15:12:50 UTC 2023] Running cmd: issue
[Mon Apr 17 15:12:50 UTC 2023] _main_domain='*.mydomain.org'
[Mon Apr 17 15:12:50 UTC 2023] _alt_domains='no'
[Mon Apr 17 15:12:50 UTC 2023] Using config home:/acme.sh
[Mon Apr 17 15:12:50 UTC 2023] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mon Apr 17 15:12:50 UTC 2023] DOMAIN_PATH='/acme.sh/*.mydomain.org_ecc'
[Mon Apr 17 15:12:50 UTC 2023] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Mon Apr 17 15:12:50 UTC 2023] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Mon Apr 17 15:12:50 UTC 2023] GET
[Mon Apr 17 15:12:50 UTC 2023] url='https://acme-v02.api.letsencrypt.org/directory'
[Mon Apr 17 15:12:50 UTC 2023] timeout=
[Mon Apr 17 15:12:50 UTC 2023] _CURL='curl --silent --dump-header /acme.sh/http.header  -L  --trace-ascii /tmp/tmp.hRZyxSchMF  -g '
[Mon Apr 17 15:12:50 UTC 2023] ret='0'
[Mon Apr 17 15:12:50 UTC 2023] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Mon Apr 17 15:12:50 UTC 2023] ACME_NEW_AUTHZ
[Mon Apr 17 15:12:50 UTC 2023] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Mon Apr 17 15:12:50 UTC 2023] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Mon Apr 17 15:12:50 UTC 2023] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Mon Apr 17 15:12:50 UTC 2023] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf'
[Mon Apr 17 15:12:50 UTC 2023] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Mon Apr 17 15:12:50 UTC 2023] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Mon Apr 17 15:12:50 UTC 2023] _on_before_issue
[Mon Apr 17 15:12:50 UTC 2023] _chk_main_domain='*.mydomain.org'
[Mon Apr 17 15:12:50 UTC 2023] _chk_alt_domains
[Mon Apr 17 15:12:50 UTC 2023] Le_LocalAddress
[Mon Apr 17 15:12:50 UTC 2023] d='*.mydomain.org'
[Mon Apr 17 15:12:50 UTC 2023] Check for domain='*.mydomain.org'
[Mon Apr 17 15:12:50 UTC 2023] _currentRoot='dns_ovh'
[Mon Apr 17 15:12:50 UTC 2023] d
[Mon Apr 17 15:12:50 UTC 2023] config file is empty, can not read CA_KEY_HASH
[Mon Apr 17 15:12:50 UTC 2023] Using config home:/acme.sh
[Mon Apr 17 15:12:50 UTC 2023] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mon Apr 17 15:12:50 UTC 2023] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Mon Apr 17 15:12:50 UTC 2023] length='ec-256'
[Mon Apr 17 15:12:50 UTC 2023] Using config home:/acme.sh
[Mon Apr 17 15:12:50 UTC 2023] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mon Apr 17 15:12:50 UTC 2023] Use length 256
[Mon Apr 17 15:12:50 UTC 2023] Using ec name: prime256v1
[Mon Apr 17 15:12:50 UTC 2023] Create account key ok.
[Mon Apr 17 15:12:51 UTC 2023] EC key
[Mon Apr 17 15:12:51 UTC 2023] config file is empty, can not read CA_EAB_KEY_ID
[Mon Apr 17 15:12:51 UTC 2023] config file is empty, can not read CA_EAB_HMAC_KEY
[Mon Apr 17 15:12:51 UTC 2023] config file is empty, can not read CA_EMAIL
[Mon Apr 17 15:12:51 UTC 2023] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Mon Apr 17 15:12:51 UTC 2023] url='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Mon Apr 17 15:12:51 UTC 2023] payload='{"termsOfServiceAgreed": true}'
[Mon Apr 17 15:12:51 UTC 2023] HEAD
[Mon Apr 17 15:12:51 UTC 2023] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Mon Apr 17 15:12:51 UTC 2023] _CURL='curl --silent --dump-header /acme.sh/http.header  -L  --trace-ascii /tmp/tmp.0CJZqtWmlP  -g  -I  '
[Mon Apr 17 15:12:51 UTC 2023] _ret='0'
[Mon Apr 17 15:12:51 UTC 2023] POST
[Mon Apr 17 15:12:51 UTC 2023] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Mon Apr 17 15:12:51 UTC 2023] _CURL='curl --silent --dump-header /acme.sh/http.header  -L  --trace-ascii /tmp/tmp.0CJZqtWmlP  -g '
[Mon Apr 17 15:12:52 UTC 2023] _ret='0'
[Mon Apr 17 15:12:52 UTC 2023] code='201'
[Mon Apr 17 15:12:52 UTC 2023] Registered
[Mon Apr 17 15:12:52 UTC 2023] _accUri='https://acme-v02.api.letsencrypt.org/acme/acct/1065849617'
[Mon Apr 17 15:12:52 UTC 2023] Calc CA_KEY_HASH='RKucdTgTeBmJpfuvDIhK7foLERJd42Y+8Ho5dAh3m2Q='
[Mon Apr 17 15:12:52 UTC 2023] ACCOUNT_THUMBPRINT='Yodind5uCLb1ElBDZIJxeZ0YrO94liBLRZlsIz7TLHc'
[Mon Apr 17 15:12:52 UTC 2023] Read key length:2048
[Mon Apr 17 15:12:52 UTC 2023] Creating domain key
[Mon Apr 17 15:12:52 UTC 2023] Using config home:/acme.sh
[Mon Apr 17 15:12:52 UTC 2023] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mon Apr 17 15:12:52 UTC 2023] Use length 256
[Mon Apr 17 15:12:52 UTC 2023] Using ec name: prime256v1
[Mon Apr 17 15:12:52 UTC 2023] The domain key is here: [1;32m/acme.sh/*.mydomain.org_ecc/*.mydomain.org.key[0m
[Mon Apr 17 15:12:52 UTC 2023] _createcsr
[Mon Apr 17 15:12:52 UTC 2023] Single domain='*.mydomain.org'
[Mon Apr 17 15:12:52 UTC 2023] Getting domain auth token for each domain
[Mon Apr 17 15:12:52 UTC 2023] d
[Mon Apr 17 15:12:52 UTC 2023] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Mon Apr 17 15:12:52 UTC 2023] payload='{"identifiers": [{"type":"dns","value":"*.mydomain.org"}]}'
[Mon Apr 17 15:12:52 UTC 2023] POST
[Mon Apr 17 15:12:52 UTC 2023] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Mon Apr 17 15:12:52 UTC 2023] _CURL='curl --silent --dump-header /acme.sh/http.header  -L  --trace-ascii /tmp/tmp.0CJZqtWmlP  -g '
[Mon Apr 17 15:12:53 UTC 2023] _ret='0'
[Mon Apr 17 15:12:53 UTC 2023] code='201'
[Mon Apr 17 15:12:53 UTC 2023] Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/1065849617/176746796497'
[Mon Apr 17 15:12:53 UTC 2023] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/1065849617/176746796497'
[Mon Apr 17 15:12:53 UTC 2023] url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/220221193457'
[Mon Apr 17 15:12:53 UTC 2023] payload
[Mon Apr 17 15:12:53 UTC 2023] POST
[Mon Apr 17 15:12:53 UTC 2023] _post_url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/220221193457'
[Mon Apr 17 15:12:53 UTC 2023] _CURL='curl --silent --dump-header /acme.sh/http.header  -L  --trace-ascii /tmp/tmp.0CJZqtWmlP  -g '
[Mon Apr 17 15:12:54 UTC 2023] _ret='0'
[Mon Apr 17 15:12:54 UTC 2023] code='200'
[Mon Apr 17 15:12:54 UTC 2023] d='*.mydomain.org'
[Mon Apr 17 15:12:54 UTC 2023] Getting webroot for domain='*.mydomain.org'
[Mon Apr 17 15:12:54 UTC 2023] _w='dns_ovh'
[Mon Apr 17 15:12:54 UTC 2023] _currentRoot='dns_ovh'
[Mon Apr 17 15:12:54 UTC 2023] entry='"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/220221193457/vzcywg","token":"LIw4wJXBmlIkCrKHdd2ic3gs4bIl-qH-gy0D6sNEMiU"'
[Mon Apr 17 15:12:54 UTC 2023] token='LIw4wJXBmlIkCrKHdd2ic3gs4bIl-qH-gy0D6sNEMiU'
[Mon Apr 17 15:12:54 UTC 2023] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/220221193457/vzcywg'
[Mon Apr 17 15:12:54 UTC 2023] keyauthorization='LIw4wJXBmlIkCrKHdd2ic3gs4bIl-qH-gy0D6sNEMiU.Yodind5uCLb1ElBDZIJxeZ0YrO94liBLRZlsIz7TLHc'
[Mon Apr 17 15:12:54 UTC 2023] dvlist='*.mydomain.org#LIw4wJXBmlIkCrKHdd2ic3gs4bIl-qH-gy0D6sNEMiU.Yodind5uCLb1ElBDZIJxeZ0YrO94liBLRZlsIz7TLHc#https://acme-v02.api.letsencrypt.org/acme/chall-v3/220221193457/vzcywg#dns-01#dns_ovh'
[Mon Apr 17 15:12:54 UTC 2023] d
[Mon Apr 17 15:12:54 UTC 2023] vlist='*.mydomain.org#LIw4wJXBmlIkCrKHdd2ic3gs4bIl-qH-gy0D6sNEMiU.Yodind5uCLb1ElBDZIJxeZ0YrO94liBLRZlsIz7TLHc#https://acme-v02.api.letsencrypt.org/acme/chall-v3/220221193457/vzcywg#dns-01#dns_ovh,'
[Mon Apr 17 15:12:54 UTC 2023] d='*.mydomain.org'
[Mon Apr 17 15:12:54 UTC 2023] _d_alias
[Mon Apr 17 15:12:54 UTC 2023] txtdomain='_acme-challenge.mydomain.org'
[Mon Apr 17 15:12:54 UTC 2023] txt='ZH9BhJLedb7UQYkQxPoZ7EKm3CFhfrpTYgnEe6xlFKI'
[Mon Apr 17 15:12:54 UTC 2023] d_api='/root/.acme.sh/dnsapi/dns_ovh.sh'
[Mon Apr 17 15:12:54 UTC 2023] Found domain api file: /root/.acme.sh/dnsapi/dns_ovh.sh
[Mon Apr 17 15:12:54 UTC 2023] Adding txt value: ZH9BhJLedb7UQYkQxPoZ7EKm3CFhfrpTYgnEe6xlFKI for domain:  _acme-challenge.mydomain.org
[Mon Apr 17 15:12:54 UTC 2023] Using OVH endpoint: ovh-eu
[Mon Apr 17 15:12:54 UTC 2023] OVH_API='https://eu.api.ovh.com/1.0'
[Mon Apr 17 15:12:54 UTC 2023] Checking authentication
[Mon Apr 17 15:12:54 UTC 2023] domain
[Mon Apr 17 15:12:54 UTC 2023] GET
[Mon Apr 17 15:12:54 UTC 2023] url='https://eu.api.ovh.com/1.0/auth/time'
[Mon Apr 17 15:12:54 UTC 2023] timeout=30
[Mon Apr 17 15:12:54 UTC 2023] _CURL='curl --silent --dump-header /acme.sh/http.header  -L  --trace-ascii /tmp/tmp.0CJZqtWmlP  -g  --connect-timeout 30'
[Mon Apr 17 15:12:54 UTC 2023] ret='0'
[Mon Apr 17 15:12:54 UTC 2023] _ovh_p='[hidden](please add '--output-insecure' to see this value)'
[Mon Apr 17 15:12:54 UTC 2023] GET
[Mon Apr 17 15:12:54 UTC 2023] url='https://eu.api.ovh.com/1.0/domain'
[Mon Apr 17 15:12:54 UTC 2023] timeout=
[Mon Apr 17 15:12:54 UTC 2023] _CURL='curl --silent --dump-header /acme.sh/http.header  -L  --trace-ascii /tmp/tmp.0CJZqtWmlP  -g '
[Mon Apr 17 15:12:54 UTC 2023] ret='0'
[Mon Apr 17 15:12:54 UTC 2023] Consumer key is ok.
[Mon Apr 17 15:12:54 UTC 2023] First detect the root zone
[Mon Apr 17 15:12:54 UTC 2023] domain/zone/_acme-challenge.mydomain.org
[Mon Apr 17 15:12:54 UTC 2023] GET
[Mon Apr 17 15:12:54 UTC 2023] url='https://eu.api.ovh.com/1.0/auth/time'
[Mon Apr 17 15:12:54 UTC 2023] timeout=30
[Mon Apr 17 15:12:54 UTC 2023] _CURL='curl --silent --dump-header /acme.sh/http.header  -L  --trace-ascii /tmp/tmp.0CJZqtWmlP  -g  --connect-timeout 30'
[Mon Apr 17 15:12:55 UTC 2023] ret='0'
[Mon Apr 17 15:12:55 UTC 2023] _ovh_p='[hidden](please add '--output-insecure' to see this value)'
[Mon Apr 17 15:12:55 UTC 2023] GET
[Mon Apr 17 15:12:55 UTC 2023] url='https://eu.api.ovh.com/1.0/domain/zone/_acme-challenge.mydomain.org'
[Mon Apr 17 15:12:55 UTC 2023] timeout=
[Mon Apr 17 15:12:55 UTC 2023] _CURL='curl --silent --dump-header /acme.sh/http.header  -L  --trace-ascii /tmp/tmp.0CJZqtWmlP  -g '
[Mon Apr 17 15:12:55 UTC 2023] ret='0'
[Mon Apr 17 15:12:55 UTC 2023] _sub_domain='_acme-challenge'
[Mon Apr 17 15:12:55 UTC 2023] _domain='_acme-challenge.mydomain.org'
[Mon Apr 17 15:12:55 UTC 2023] Adding record
[Mon Apr 17 15:12:55 UTC 2023] domain/zone/_acme-challenge.mydomain.org/record
[Mon Apr 17 15:12:55 UTC 2023] GET
[Mon Apr 17 15:12:55 UTC 2023] url='https://eu.api.ovh.com/1.0/auth/time'
[Mon Apr 17 15:12:55 UTC 2023] timeout=30
[Mon Apr 17 15:12:55 UTC 2023] _CURL='curl --silent --dump-header /acme.sh/http.header  -L  --trace-ascii /tmp/tmp.0CJZqtWmlP  -g  --connect-timeout 30'
[Mon Apr 17 15:12:55 UTC 2023] ret='0'
[Mon Apr 17 15:12:55 UTC 2023] _ovh_p='[hidden](please add '--output-insecure' to see this value)'
[Mon Apr 17 15:12:55 UTC 2023] data='{"fieldType":"TXT","subDomain":"_acme-challenge","target":"ZH9BhJLedb7UQYkQxPoZ7EKm3CFhfrpTYgnEe6xlFKI","ttl":60}'
[Mon Apr 17 15:12:55 UTC 2023] POST
[Mon Apr 17 15:12:55 UTC 2023] _post_url='https://eu.api.ovh.com/1.0/domain/zone/_acme-challenge.mydomain.org/record'
[Mon Apr 17 15:12:55 UTC 2023] _CURL='curl --silent --dump-header /acme.sh/http.header  -L  --trace-ascii /tmp/tmp.0CJZqtWmlP  -g '
[Mon Apr 17 15:12:55 UTC 2023] _ret='0'
[Mon Apr 17 15:12:55 UTC 2023] Add txt record error.
[Mon Apr 17 15:12:55 UTC 2023] Error add txt for domain:_acme-challenge.mydomain.org
[Mon Apr 17 15:12:55 UTC 2023] _on_issue_err
[Mon Apr 17 15:12:55 UTC 2023] Please check log file for more details: /acme.sh/acme.sh.log
[Mon Apr 17 15:12:55 UTC 2023] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/220221193457/vzcywg'
[Mon Apr 17 15:12:55 UTC 2023] payload='{}'
[Mon Apr 17 15:12:55 UTC 2023] POST
[Mon Apr 17 15:12:55 UTC 2023] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/220221193457/vzcywg'
[Mon Apr 17 15:12:55 UTC 2023] _CURL='curl --silent --dump-header /acme.sh/http.header  -L  --trace-ascii /tmp/tmp.0CJZqtWmlP  -g '
[Mon Apr 17 15:12:56 UTC 2023] _ret='0'
[Mon Apr 17 15:12:56 UTC 2023] code='200'
[Mon Apr 17 15:12:56 UTC 2023] Diagnosis versions: 
openssl:openssl
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)
apache:
apache doesn't exist.
nginx:
nginx doesn't exist.
socat:
socat by Gerhard Rieger and contributors - see www.dest-unreach.org
socat version 1.7.4.4 on 31 Oct 2022 04:42:14
   running on Linux version #42962 SMP Tue Jan 31 23:19:16 CST 2023, release 4.4.180+, machine x86_64
features:
  #define WITH_STDIO 1
  #define WITH_FDNUM 1
  #define WITH_FILE 1
  #define WITH_CREAT 1
  #define WITH_GOPEN 1
  #define WITH_TERMIOS 1
  #define WITH_PIPE 1
  #define WITH_UNIX 1
  #define WITH_ABSTRACT_UNIXSOCKET 1
  #define WITH_IP4 1
  #define WITH_IP6 1
  #define WITH_RAWIP 1
  #define WITH_GENERICSOCKET 1
  #define WITH_INTERFACE 1
  #define WITH_TCP 1
  #define WITH_UDP 1
  #define WITH_SCTP 1
  #define WITH_LISTEN 1
  #define WITH_SOCKS4 1
  #define WITH_SOCKS4A 1
  #define WITH_VSOCK 1
  #define WITH_PROXY 1
  #define WITH_SYSTEM 1
  #define WITH_EXEC 1
  #define WITH_READLINE 1
  #define WITH_TUN 1
  #define WITH_PTY 1
  #define WITH_OPENSSL 1
  #undef WITH_FIPS
  #undef WITH_LIBWRAP
  #define WITH_SYCLS 1
  #define WITH_FILAN 1
  #define WITH_RETRY 1
  #define WITH_MSGLEVEL 0 /*debug*/
[Mon Apr 17 15:12:56 UTC 2023] pid
[Mon Apr 17 15:12:56 UTC 2023] No need to restore nginx, skip.
[Mon Apr 17 15:12:56 UTC 2023] _clearupdns
[Mon Apr 17 15:12:56 UTC 2023] dns_entries
[Mon Apr 17 15:12:56 UTC 2023] skip dns.

**Comment by barnumbirr** [comment]
Issue confirmed on my end as well. Seems the creation of the validation `TXT` record fails, which makes LE certificate creation fail.

**Comment by daweedm** [comment]
> setup described here again

I had the same issue, recreating the application/token solved the problem. It seems to be related to the OVH API, as if the apps expires (even if I'm pretty sure that I've selected "Unlimited" the first time I've created the app)
