### ISSUE TITLE
Remove extra slash from Leaseweb DNS script.

### ISSUE THREAD

**Issue by tmaniac** [acmesh-official/acme.sh#4604]
https://github.com/acmesh-official/acme.sh/blob/cf3ff4c136f80aa55513c289b0da69243b4d264a/dnsapi/dns_leaseweb.sh#L9

The trailing slash on line 9 breaks the DNS challenge to Leaseweb.

When i remove the slash everything works without problem.
(Since i'm no coder or anything i figured i'll just report it here)

**Comment by Neilpang** [comment]
fixed, try again.

```
acme.sh --upgrade -b dev
```
