### ISSUE TITLE
deploy\docker.sh can't work with curl 8.0.1

### ISSUE THREAD

**Issue by github-neo** [acmesh-official/acme.sh#4612]
### `deploy\docker.sh` can't work with curl 8.0.1
The **curl** in the latest Docker image of `neilpang/acme.sh` is **8.0.1**, but the method `_check_curl_version()` in `deploy\docker.sh` can't work with **curl 8.0.1** and always fail with error.

**Root cause:** the method `_check_curl_version()` checks `if [ "$_major$_minor" -lt "740" ];`, but "80" (`$_major$_minor`) is less than "740".
Need to fix the pattern in `_check_curl_version()` for compatible with curl 8.* and higher version.

Steps to reproduce
------------------
Deploy certs from a Docker container to another container:
docker exec acme.sh --deploy --debug 3 --log-level 2 --syslog 7 --log --deploy-hook docker -d ******

Debug log
-----------------
```
[Sat Apr 22 13:36:08 UTC 2023] curl exists=0
[Sat Apr 22 13:36:08 UTC 2023] _cversion='8.0.1'
[Sat Apr 22 13:36:08 UTC 2023] _major='8'
[Sat Apr 22 13:36:08 UTC 2023] _minor='0'
[Sat Apr 22 13:36:08 UTC 2023] curl v8.0.1 doesn't support unit socket
[Sat Apr 22 13:36:08 UTC 2023] Please upgrade to curl 7.40 or later.
[Sat Apr 22 13:36:08 UTC 2023] Error deploy for ******
[Sat Apr 22 13:36:08 UTC 2023] Deploy error.
```

**Comment by Neilpang** [comment]
fixed, try again.

```
acme.sh --upgrade -b dev
```

**Comment by github-neo** [comment]
> fixed, try again.
> 
> ```
> acme.sh --upgrade -b dev
> ```
neilpang/acme.sh:**dev** is working now, thank you very much for fixing so quickly!

**Comment by StrangePeanut** [comment]
I can confirm that the issue is addressed on the dev branch, thanks!

**Comment by publicarray** [comment]
@Neilpang thanks for your work, I just ran into the same issue. Can we have a release that includes this fix?
