### ISSUE TITLE
i have two questions to ask the author...

### ISSUE THREAD

**Issue by 251189810** [acmesh-official/acme.sh#4618]
1. at first use to register, it necessary for ZeroSSL to fill in EAB credentials information?
2. so far, does SSL.com support wildcard certificate to issue( i want to use wildcard... )?

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA

https://github.com/acmesh-official/acme.sh/wiki/CA

**Comment by 251189810** [comment]
Thanks^_^

**Comment by 251189810** [comment]
> https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA
> 
> https://github.com/acmesh-official/acme.sh/wiki/CA

Thanks ^_^
