### ISSUE TITLE
Roadmap of next release?

### ISSUE THREAD

**Issue by MarkusKu** [acmesh-official/acme.sh#4624]
I am using acme.sh via a packaged plugin in OpnSense. The policy of the maintainer is to only update the package with new releases of acme.sh. It's been a while since the last release of acme.sh. What is the roadmap? 

My personal interest is in using the google-domains API. It is in the code for a while now but there is no release yet available with this API.
---Markus

Ref: https://github.com/opnsense/plugins/issues/3408#issuecomment-1522417385

**Comment by nmiller0113** [comment]
I'm also interested in this for the exact same reason :)

**Comment by MarkusKu** [comment]
Any news on a new release?

**Comment by nmiller0113** [comment]
I'm very curious what might be holding it up.

**Comment by nmiller0113** [comment]
@MarkusKu, I just found https://github.com/acmesh-official/acmetest, and I see that testing is still being done. That's probably what they're waiting to pass before the next release.

**Comment by MarkusKu** [comment]
@nmiller0113 You might be right. However, I think there are some regressions too. We'll see...

**Comment by Neilpang** [comment]
it will be in a few days.  there are a few bugs need to be fixed.

**Comment by nmiller0113** [comment]
Thanks for the update @Neilpang!

**Comment by ctomkow** [comment]
Thanks for the update as well @Neilpang!. I stumbled across this looking for google domains support in OpnSense as well. Cheers.

**Comment by nmiller0113** [comment]
> it will be in a few days. there are a few bugs need to be fixed.

Hi @Neilpang, just checking in to see if we're getting close now that it's been a couple of weeks. Thanks!

**Comment by nmiller0113** [comment]
I guess it's not as close as previously expected. I'll cross my fingers that it's soon :)

**Comment by ThomasLamprecht** [comment]
3.0.6 was already released 5 days ago:
https://github.com/acmesh-official/acme.sh/releases/tag/3.0.6

While the release only talks about fixing a security issue, the tag was done from the master branch and includes  all current commits:
https://github.com/acmesh-official/acme.sh/commits/3.0.6

**Comment by nmiller0113** [comment]
Thanks @ThomasLamprecht! You're right, I completely missed that.
