### ISSUE TITLE
Verify error:"error":{

### ISSUE THREAD

**Issue by timonson** [acmesh-official/acme.sh#4631]
Hello,

I am not able to find a solution for the following error and would be glad to get some help.

Thank you!

Steps to reproduce
------------------
`$HOME/.acme.sh/acme.sh --issue --debug -d smtp.zaubrik.com --standalone`

Debug log
----------------- 
[Thu May 11 12:29:51 UTC 2023] ok, let's start to verify
[Thu May 11 12:29:51 UTC 2023] Verifying: smtp.zaubrik.com
[Thu May 11 12:29:51 UTC 2023] d='smtp.zaubrik.com'
[Thu May 11 12:29:51 UTC 2023] keyauthorization='Ey6EchrqFQWMlHGmGmSJel6G-p2iEhWZ5F9v0W_Bz_8.KKYrcx8XO-ZN7ba67FtKjBAHNGdpOlZBQ3Zm6cn3IlY'
[Thu May 11 12:29:51 UTC 2023] uri='https://acme.zerossl.com/v2/DV90/chall/V9g1vI5CILf9j3qh-QU3Mw'
[Thu May 11 12:29:51 UTC 2023] _currentRoot='no'
[Thu May 11 12:29:51 UTC 2023] Standalone mode server
[Thu May 11 12:29:51 UTC 2023] content='Ey6EchrqFQWMlHGmGmSJel6G-p2iEhWZ5F9v0W_Bz_8.KKYrcx8XO-ZN7ba67FtKjBAHNGdpOlZBQ3Zm6cn3IlY'
[Thu May 11 12:29:51 UTC 2023] ncaddr
[Thu May 11 12:29:51 UTC 2023] startserver: 1140507
[Thu May 11 12:29:51 UTC 2023] Le_HTTPPort='80'
[Thu May 11 12:29:51 UTC 2023] Le_Listen_V4
[Thu May 11 12:29:51 UTC 2023] Le_Listen_V6
[Thu May 11 12:29:51 UTC 2023] _content_len='87'
[Thu May 11 12:29:51 UTC 2023] _NC='socat TCP-LISTEN:80,crlf,reuseaddr,fork'
[Thu May 11 12:29:52 UTC 2023] serverproc='1141427'
[Thu May 11 12:29:52 UTC 2023] url='https://acme.zerossl.com/v2/DV90/chall/V9g1vI5CILf9j3qh-QU3Mw'
[Thu May 11 12:29:52 UTC 2023] payload='{}'
[Thu May 11 12:29:52 UTC 2023] POST
[Thu May 11 12:29:52 UTC 2023] _post_url='https://acme.zerossl.com/v2/DV90/chall/V9g1vI5CILf9j3qh-QU3Mw'
[Thu May 11 12:29:52 UTC 2023] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  -g '
[Thu May 11 12:29:52 UTC 2023] _ret='0'
[Thu May 11 12:29:52 UTC 2023] code='200'
[Thu May 11 12:29:52 UTC 2023] trigger validation code: 200
[Thu May 11 12:29:52 UTC 2023] Processing, The CA is processing your order, please just wait. (1/30)
[Thu May 11 12:29:52 UTC 2023] sleep 2 secs to verify again
[Thu May 11 12:29:55 UTC 2023] checking
[Thu May 11 12:29:55 UTC 2023] url='https://acme.zerossl.com/v2/DV90/chall/V9g1vI5CILf9j3qh-QU3Mw'
[Thu May 11 12:29:55 UTC 2023] payload
[Thu May 11 12:29:56 UTC 2023] POST
[Thu May 11 12:29:56 UTC 2023] _post_url='https://acme.zerossl.com/v2/DV90/chall/V9g1vI5CILf9j3qh-QU3Mw'
[Thu May 11 12:29:56 UTC 2023] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  -g '
[Thu May 11 12:29:56 UTC 2023] _ret='0'
[Thu May 11 12:29:56 UTC 2023] code='200'
[Thu May 11 12:29:56 UTC 2023] smtp.zaubrik.com:Verify error:"error":{
[Thu May 11 12:29:56 UTC 2023] Debug: get token url.
[Thu May 11 12:29:56 UTC 2023] GET
[Thu May 11 12:29:56 UTC 2023] url='http://smtp.zaubrik.com/.well-known/acme-challenge/Ey6EchrqFQWMlHGmGmSJel6G-p2iEhWZ5F9v0W_Bz_8'
[Thu May 11 12:29:56 UTC 2023] timeout=1
[Thu May 11 12:29:56 UTC 2023] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  -g  --connect-timeout 1'
[Thu May 11 12:29:56 UTC 2023] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 7
[Thu May 11 12:29:56 UTC 2023] ret='7'
[Thu May 11 12:29:56 UTC 2023] Skip for removelevel:
[Thu May 11 12:29:56 UTC 2023] pid='1141427'
[Thu May 11 12:29:56 UTC 2023] No need to restore nginx, skip.
[Thu May 11 12:29:56 UTC 2023] _clearupdns
[Thu May 11 12:29:56 UTC 2023] dns_entries
[Thu May 11 12:29:56 UTC 2023] skip dns.
[Thu May 11 12:29:56 UTC 2023] _on_issue_err
[Thu May 11 12:29:56 UTC 2023] Please add '--debug' or '--log' to check more details.
[Thu May 11 12:29:56 UTC 2023] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Thu May 11 12:29:56 UTC 2023] url='https://acme.zerossl.com/v2/DV90/chall/V9g1vI5CILf9j3qh-QU3Mw'
[Thu May 11 12:29:56 UTC 2023] payload='{}'
[Thu May 11 12:29:56 UTC 2023] POST
[Thu May 11 12:29:56 UTC 2023] _post_url='https://acme.zerossl.com/v2/DV90/chall/V9g1vI5CILf9j3qh-QU3Mw'
[Thu May 11 12:29:56 UTC 2023] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header  -L  -g '
[Thu May 11 12:29:57 UTC 2023] _ret='0'
[Thu May 11 12:29:57 UTC 2023] code='200'
[Thu May 11 12:29:57 UTC 2023] Diagnosis versions: 
openssl:openssl
OpenSSL 1.1.1f  31 Mar 2020
apache:
apache doesn't exist.
nginx:
nginx doesn't exist.
socat:
socat by Gerhard Rieger and contributors - see www.dest-unreach.org
socat version 1.7.3.3 on Oct 26 2019 17:42:04
   running on Linux version #26~20.04.1-Ubuntu SMP Sat Oct 15 03:22:07 UTC 2022, release 5.15.0-1022-aws, machine x86_64

```
acme.sh  --issue .....   --debug 2
```

**Comment by timonson** [comment]
Does anybody have an idea?

**Comment by StiviiK** [comment]
Your server refuses the connection to `url='http://smtp.zaubrik.com/.well-known/acme-challenge/Ey6EchrqFQWMlHGmGmSJel6G-p2iEhWZ5F9v0W_Bz_8'`. 

```
[Thu May 11 12:29:56 UTC 2023] GET
[Thu May 11 12:29:56 UTC 2023] url='http://smtp.zaubrik.com/.well-known/acme-challenge/Ey6EchrqFQWMlHGmGmSJel6G-p2iEhWZ5F9v0W_Bz_8'
[Thu May 11 12:29:56 UTC 2023] timeout=1
[Thu May 11 12:29:56 UTC 2023] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header -L -g --connect-timeout 1'
[Thu May 11 12:29:56 UTC 2023] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 7
```

**Comment by fatpandaria** [comment]
> Your server refuses the connection to `url='http://smtp.zaubrik.com/.well-known/acme-challenge/Ey6EchrqFQWMlHGmGmSJel6G-p2iEhWZ5F9v0W_Bz_8'`.
> 
> ```
> [Thu May 11 12:29:56 UTC 2023] GET
> [Thu May 11 12:29:56 UTC 2023] url='http://smtp.zaubrik.com/.well-known/acme-challenge/Ey6EchrqFQWMlHGmGmSJel6G-p2iEhWZ5F9v0W_Bz_8'
> [Thu May 11 12:29:56 UTC 2023] timeout=1
> [Thu May 11 12:29:56 UTC 2023] _CURL='curl --silent --dump-header /home/ubuntu/.acme.sh/http.header -L -g --connect-timeout 1'
> [Thu May 11 12:29:56 UTC 2023] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 7
> ```

got the same error, but i did make it several times before;what could be the reason?

**Comment by timonson** [comment]
Thanks, stupid routing error.

**Comment by jzhao-30** [comment]
> Thanks, stupid routing error.

Same question, how can you solve it?

**Comment by wangfeng35** [comment]
> turning down the firewall while app



> Thanks, stupid routing error.

How to solve?

**Comment by jzhao-30** [comment]
> Thank you for your replying! It has been solved! Really appreciate!!!!!!!!

**Comment by wangfeng35** [comment]
> > Thank you for your replying! It has been solved! Really appreciate!!!!!!!!

I met the same question (Verify error). The firewall rules are deleted. I don't know what's wrong.
May I ask how you solve it?
