### ISSUE TITLE
Issuing a certificate from another host

### ISSUE THREAD

**Issue by leonardorame** [acmesh-official/acme.sh#4638]
Hi, for some reason the server pointed by the domain can't reach some sites, including letsencrypt.org, but it can be reached from the outside.

To clarify this, all incoming connection works, Apache is serving sites without issues, but this server cannot connect to other sites from outside the local network.

So, until the networking guys fix the issue I wonder if I can update the expired certificate from another computer where I can reach letsencrypt.com. I did try without success, because aparently Let's Encrypt, at validation time tries to reach the production host (the pointed by the domain).

**Comment by Neilpang** [comment]
if you control the domain, you can use the dns mode.
