### ISSUE TITLE
Note: you can use "$@" instead of eval "$@" for logging

### ISSUE THREAD

**Issue by andychu** [acmesh-official/acme.sh#4666]
I noticed #4659  and the commit to remove the `_exec` wrapper:

https://github.com/acmesh-official/acme.sh/commit/327e2fb0a4bdbe4b75339e1cad6d20bda29318d6

If you want to restore that logging functionality, you can simply remove the `eval`

```
_execute_or_log() {
  "$@"  2>>logfile      # run the command $1 with args $2 $3 ... 
}

_execute_or_log nginx -t   # no quotes !!!


_execute_or_log 'shell | chars > are $(ok)'   # will not be evaluated as shell

```

FWIW this blog post about arrays is somewhat related, you can generalize `"$@"` to `"${a[@]}"`

[Thirteen Incorrect Ways and Two Awkward Ways to Use Arrays](https://www.oilshell.org/blog/2016/11/06.html)  (written by me)

**Comment by Neilpang** [comment]
thanks.  it's just for error messages. removing it is no harm.
