### ISSUE TITLE
Line 620 Want to escape a single quote? echo 'This is how it'\''s

### ISSUE THREAD

**Issue by Pierre-Gronau-ndaal** [acmesh-official/acme.sh#4667]
Line 620
      printf '\'"$(printf "%o" "$(_math "$ic" \* 16 + $jc)")""%s"
              ^-- [SC1003](https://www.shellcheck.net/wiki/SC1003) (info): Want to escape a single quote? echo 'This is how it'\''s done'.

--> https://www.shellcheck.net/wiki/SC1003

Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

**Comment by Neilpang** [comment]
no,  it's to print escaped hex number as string.
