### ISSUE TITLE
Is it possible for the SSH deploy hook to run a command before copying files?

### ISSUE THREAD

**Issue by richardpowellus** [acmesh-official/acme.sh#4674]
I think this is more of a feature request than a bug, because I don't believe there's a way to do what I'm looking for.

I was planning on using the SSH deploy hook to copy my certs to a pikvm device. By default, the filesystem on the pikvm is in read-only mode. So, when deploying files to the device, I need to run a command before the files are actually copied over SSH that will enable rw mode.

I know there is an option DEPLOY_SSH_REMOTE_CMD that will run a command after the files are copied over. This is great because it allows me to put the filesystem back to read only mode and restart nginx. However, I need an option to run a command before the files are copied as well.

**Comment by richardpowellus** [comment]
> Please upgrade to the latest code and try again first. Maybe it's already fixed. `acme.sh --upgrade` If it's still not working, please provide the log with `--debug 2`, otherwise, nobody can help you.

Again, this is not a bug. It's a feature request.

**Comment by Neilpang** [comment]
just  copy to a temp folder on the remote machine first.
and do whatever you want with your "DEPLOY_SSH_REMOTE_CMD"
