### ISSUE TITLE
How to change a reload-cmd Command

### ISSUE THREAD

**Issue by germebl** [acmesh-official/acme.sh#4682]
Hey,

i just created a bunch of ssl certificates and installed them to their directorys. But i had a typo within my reload cmd command.

I know its saved within the `~/.acme.sh/domainfolder\domain.conf` as `Le_ReloadCmd=`. But it is Base64 encoded.

Does i just need to encode my command to base64 and set it between `__ACME_BASE64__START_` and `__ACME_BASE64__END_` ?

**Comment by germebl** [comment]
I think the bot does not understanded that correct :D

**Comment by Neilpang** [comment]
please run the `--install-cert` command again with the new reloadcmd.  it will replace the previous one.
