### ISSUE TITLE
Remove/change '*' on wildcard domains directories/files

### ISSUE THREAD

**Issue by fawzibr** [acmesh-official/acme.sh#4688]
Having directories/files named '*.mydomain.com' is kind of a pain. Would it be possible to have an option to change the certificate files/directories with an option in account.conf, something like:

```
AUTO_UPGRADE='1'
DEFAULT_ACME_SERVER='https://acme-v02.api.letsencrypt.org/directory'
LOG_FILE='/acme.sh/acme.sh.log'
# replace '*' with <string> when creating certificate files/directories 
REPLACE_WILDCARD=<string>
```

So if we used "REPLACE_WILDCARD=wildcard" then the files will be "wildcard.mydomain.com" instead of "*.mydomain.com"

Another option (don't know if this is possible), can we have more than one domain in a certificate? For example if have mydomain.com and *.mydomain.com,  can they both be packaged into the mydomain.com certificate?

**Comment by stokito** [comment]
One cert may have multiple domains.
The main domain like example.com is written to CN field and all others like `*.example.com` or `mail.example.com ` are written to extended ASN field.
So if the first domain was the *.example.com then the cert files will have it in a path.
This is actually a bug and should be changed. We shouldn't allow the wildcard domain to be first.
