### ISSUE TITLE
请问3.0.6是不是默认申请ecc证书了? 而不是默认申请RSA证书?

### ISSUE THREAD

**Issue by cym1102** [acmesh-official/acme.sh#4695]
如果我想申请rsa证书, 请问该加什么参数?

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh

![image](https://github.com/acmesh-official/acme.sh/assets/8305679/a2b58ff6-f0dd-493e-a851-c4a0d0fd38ef)
