### ISSUE TITLE
Verify error:"error":{

### ISSUE THREAD

**Issue by alidaf** [acmesh-official/acme.sh#4697]
I am trying to set up certificates for 2 domains and both give the error `Verify error:"error":{` when requesting a certificate. There are no further details in the log file. This is a fresh install using git on a Synology NAS.

**Comment by Ramalama2** [comment]
i dont know who decided to use zerossl as default ca....
zerossl never worked here, on none of my servers, it waits here forever for "order is processing" and retryes forever in a loop.

Where letsencrypt always works without any issues.
Dunno how much they paid, but its the worst free CA ive ever seen.

**Comment by sg1888** [comment]
I believe ZeroSSL sponsors the project (or has hired Neil), which is why they’re default.   Unfortunately ZeroSSL is slow and their servers seem to have random errors.   

Until ZeroSSL fixes their server issues, LetsEncrypt is the way to go.  The only time I’ve had issues with LE is when I’ve hit the rate limit (5+ requests for the same domain name within 48 hours).

**Comment by Ramalama2** [comment]
> I believe ZeroSSL sponsors the project (or has hired Neil), which is why they’re default. Unfortunately ZeroSSL is slow and their servers seem to have random errors.
> 
> Until ZeroSSL fixes their server issues, LetsEncrypt is the way to go. The only time I’ve had issues with LE is when I’ve hit the rate limit (5+ requests for the same domain name within 48 hours).

the only time i had issues with LE, is when i was either stupid or hitted the rate limit like you xD

I mean Neil has to live from something, so i understand him, but there are 860 open issues, i believe ~700 of them are purely ZeroSSL related xD

**Comment by alidaf** [comment]
> I mean Neil has to live from something, so i understand him, but there are 860 open issues, i believe ~700 of them are purely ZeroSSL related xD

Ouch. At the end of the day, we have the options to choose, and what Neil has created has been a massive enabler for many. I was so frustrated by the Synology limitations on renewals and lack of wildcard certificates and this has allowed me to bypass it all. Kudos to him and anyone else that has contributed and I hope that his collaboration with ZeroSSL is fruitful for him.

I hadn't realised that I'd left this open, so with this comment I'll close this issue. I don't think there is enough information for a proper diagnosis of the cause, and there is a workaround and probably other related issues that will be better detailed.
