### ISSUE TITLE
Synology NAS Guide update to certificate renewal

### ISSUE THREAD

**Issue by alidaf** [acmesh-official/acme.sh#4709]
Following the guide mostly works, apart from the 2-factor authentication, which is still waiting for release.

However, I also found that in order to configure certificate renewal I needed to add a --force to the task schedule script.
Without it, I would receive an email with the comments:

`[Date] Skip, Next renewal time is: 2023-09-17T10:58:20Z`
`[Date] Add '--force' to force to renew.`

I simply modified the script to

`# renew certificates `
`/usr/local/share/acme.sh/acme.sh --cron --force --home /usr/local/share/acme.sh/`

and it works.

Note: running the script to "fix a broken environment after an upgrade had no effect"

**Comment by Eagle3386** [comment]
@alidaf nope, you got it wrong regarding `--force`.
Moreover, using that argument, you're forcing renewal way too frequently (probably each week) instead of each 60-90 days only.

Lastly, 2FA works well & the wiki was updated yesterday to reflect the deploy hook changes as well.
