### ISSUE TITLE
Can not find the hook file for aws_ses

### ISSUE THREAD

**Issue by bhatguru** [acmesh-official/acme.sh#4715]
As per the following documentation we can use the AWS SES for notification, i have configured the credentials in command line as suggested, while registering the hook getting below error.
https://github.com/acmesh-official/acme.sh/wiki/notify

Also i have checked for aws_ses hook file in following [location](https://github.com/acmesh-official/acme.sh/tree/master/notify), don't see the aws_ses file, is it something that is yet to be implemented? can someone please confirm.

Steps to reproduce
------------------
acme.sh --set-notify  --notify-hook aws_ses

Debug log
-----------------
acme.sh --set-notify  --notify-hook aws_ses
[Fri Jul 28 12:06:25 IST 2023] Set notify hook to: aws_ses
[Fri Jul 28 12:06:25 IST 2023] Sending via: aws_ses
[Fri Jul 28 12:06:25 IST 2023] Can not find the hook file for aws_ses

```
acme.sh  --issue .....   --debug 2
```

**Comment by bhatguru** [comment]
Please find the debug 2 logs for the same, using the latest version already, it is still not working

acme.sh --upgrade
[Fri Jul 28 12:23:07 IST 2023] Already uptodate!
[Fri Jul 28 12:23:07 IST 2023] Upgrade success!

Debug Log
---------------
acme.sh --set-notify  --notify-hook aws_ses --debug 2
[Fri Jul 28 12:23:34 IST 2023] Lets find script dir.
[Fri Jul 28 12:23:34 IST 2023] _SCRIPT_='/home/ubuntu/myacme/acme.sh'
[Fri Jul 28 12:23:34 IST 2023] _script='/home/ubuntu/myacme/acme.sh'
[Fri Jul 28 12:23:34 IST 2023] _script_home='/home/ubuntu/myacme'
[Fri Jul 28 12:23:34 IST 2023] Using config home:/home/ubuntu/myacme/data
[Fri Jul 28 12:23:34 IST 2023] LE_WORKING_DIR='/home/ubuntu/myacme'
https://github.com/acmesh-official/acme.sh
v3.0.6
[Fri Jul 28 12:23:34 IST 2023] Running cmd: setnotify
[Fri Jul 28 12:23:34 IST 2023] Using config home:/home/ubuntu/myacme/data
[Fri Jul 28 12:23:34 IST 2023] default_acme_server
[Fri Jul 28 12:23:34 IST 2023] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Fri Jul 28 12:23:34 IST 2023] _ACME_SERVER_HOST='acme.zerossl.com'
[Fri Jul 28 12:23:34 IST 2023] _ACME_SERVER_PATH='v2/DV90'
[Fri Jul 28 12:23:34 IST 2023] Set notify hook to: aws_ses
[Fri Jul 28 12:23:34 IST 2023] Sending via: aws_ses
[Fri Jul 28 12:23:34 IST 2023] Found  for aws_ses
[Fri Jul 28 12:23:34 IST 2023] Can not find the hook file for aws_ses

**Comment by Neilpang** [comment]
upgrade to the latest code, it's there now.
```
acme.sh --upgrade 
```
