### ISSUE TITLE
求教时差问题怎么处理？

### ISSUE THREAD

**Issue by jasonziai** [acmesh-official/acme.sh#4730]
根据网上搜索结果，自己初步判断是时区的缘故时间不同步造成证书不能成功申请。设备为标准东八区时间，看log里的是UTC标准时间，相差8小时。已尝试将设备时间改为UTC时间，结果依旧不成功，报错也完全相同，请大神帮忙看看。

_d_alias
txtdomain='_acme-challenge.xxx.xxx.com'
txt='Z82pemY_-CXuw0zHxk1nQ8tEeibM9CgInd1MVZYMDds'
d_api='/usr/lib/acme/client/dnsapi/dns_ali.sh'
Found domain api file: /usr/lib/acme/client/dnsapi/dns_ali.sh
Adding txt value: Z82pemY_-CXuw0zHxk1nQ8tEeibM9CgInd1MVZYMDds for domain:  _acme-challenge.xxx.xxx.com
First detect the root zone
GET
url='https://alidns.aliyuncs.com/?AccessKeyId=********************&Action=DescribeDomainRecords&DomainName=xxx.xxx.com&Format=json&SignatureMethod=HMAC-SHA1&SignatureNonce=1691679724&SignatureVersion=1.0&Timestamp=2023-08-10T15%3A02%3A04Z&Version=2015-01-09&Signature=QT5Op7Ok62D3hBhCSDk%2Bm5p1F1o%3D'
timeout=
_CURL='curl --silent --dump-header /etc/acme/http.header  -L  -g '
ret='0'
GET
url='https://alidns.aliyuncs.com/?AccessKeyId=********************&Action=DescribeDomainRecords&DomainName=xxx.xxx.com&Format=json&SignatureMethod=HMAC-SHA1&SignatureNonce=1691679726&SignatureVersion=1.0&Timestamp=2023-08-10T15%3A02%3A06Z&Version=2015-01-09&Signature=ZJMFbKN8YG8twkHOUTUcTlpqHuI%3D'
timeout=
_CURL='curl --silent --dump-header /etc/acme/http.header  -L  -g '
ret='0'
GET
url='https://alidns.aliyuncs.com/?AccessKeyId=********************&Action=DescribeDomainRecords&DomainName=win&Format=json&SignatureMethod=HMAC-SHA1&SignatureNonce=1691679728&SignatureVersion=1.0&Timestamp=2023-08-10T15%3A02%3A08Z&Version=2015-01-09&Signature=FMGR5JG%2FJNQwV8hfDrQDpgXwv7U%3D'
timeout=
_CURL='curl --silent --dump-header /etc/acme/http.header  -L  -g '
ret='0'
Error add txt for domain:_acme-challenge.xxx.xxx.com
_on_issue_err
Please add '--debug' or '--log' to check more details.
See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh

_ret='0'
code='200'

**Comment by yeohreet** [comment]
解决了么，我也是遇到了这个问题。
