### ISSUE TITLE
DNS API: Update A record for DDNS 

### ISSUE THREAD

**Issue by stokito** [acmesh-official/acme.sh#4739]
The DSN API scripts can update a TXT record of a domain.
They are works great and stable.
It should be easy to add another function to update A/AAA records too.
 
For example a request to DuckDNS to update a TXT record:

    https://www.duckdns.org/update?domains=example.duckdns.org&token=TOKEN&txt=SOMETXT

And here is a request to update A record:

    https://www.duckdns.org/update?domains=example.duckdns.org&token=TOKEN&ip=NEWIP

The difference only in one param so it would be easy to implement.

Then the same scripts can be used to implement Dynamic DNS (DDNS). This will make a lot of things easier.
The DDNS is especially important for self hosting users who  have a public but not static IP.

Currently in OpenWrt the DDNS scripts are written and supported badly. For example to use CloudFlare you need to make some manual steps. I proposed to switch instead to use the acme.sh dns api scripts instead https://github.com/openwrt/luci/issues/6417

Please tell if you'll accept a PR with support of updating IP records.

**Comment by Neilpang** [comment]
It's not necessary for ACME,  and changing A record can be much more dangerous than TXT records.
We have nearly <200 dns providers supported,  who can maintain so many dns providers to support A records, which is not used in ACME, and could never be tested here?

**Comment by stokito** [comment]
Well, you right. Generally speaking I need a lightweight Lexicon but in shell.
Instead it would be better to put effort to standardize DNS APIs and ask DNS providers to use it.
