### ISSUE TITLE
unrecognized option '--conf-path=[^ ]* ' for nginx config

### ISSUE THREAD

**Issue by Nirzak** [acmesh-official/acme.sh#4746]
Steps to reproduce
------------------
Just try to install a certificate using acme.sh on ubuntu 22.
Debug log
-----------------
[Sun Aug 20 18:52:04 UTC 2023] Nginx mode for domain:zaksb.nirzak.codes
grep: unrecognized option '--conf-path=[^ ]* '
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
[Sun Aug 20 18:52:04 UTC 2023] Can not find nginx conf.
[Sun Aug 20 18:52:04 UTC 2023] Please add '--debug' or '--log' to check more details.
[Sun Aug 20 18:52:04 UTC 2023] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Sun Aug 20 18:52:05] ERROR     Certificate could not be issued.

Additional Info
-----------------
The following code may have the issue.
NGINX_CONF="$(nginx -V 2>&1 | _egrep_o "--conf-path=[^ ]* " | tr -d " ")"

No escape parameter is used in the egrep pattern. If I modify the pattern like as the following then the code works.
` _egrep_o "\-\-conf-path=[^ ]* "`

I can make a pull request if you want. Thanks.

```
acme.sh  --issue .....   --debug 2
```

**Comment by tpedretti** [comment]
Same problem in #4725 I would say do a pull request for the fix and submit it, as my issue has been open for 3 weeks now and nothing. The problem started in 3.0.7, if you downgrade to 3.0.6 it works.

**Comment by Nirzak** [comment]
> 

Thanks created a pull request for this. Hope they will merge and fix the issue.

**Comment by victorxys** [comment]
> 

Excuse me may I ask how to downgrade to 3.0.6? I did't find any answer from google
