### ISSUE TITLE
Issues renewing a certificate 

### ISSUE THREAD

**Issue by felicemassaro** [acmesh-official/acme.sh#4752]
I am trying to renew a certificate as following:

./acme.sh --renew -d mywebsite.africa_ecc --cert-home /etc/nginx/ssl/mywebsite.africa_ecc/ --force
[Tue Aug 22 04:27:13 SAST 2023] Renew: 'mywebsite.africa_ecc'
[Tue Aug 22 04:27:13 SAST 2023] 'mywebsite.africa_ecc' is not an issued domain, skip.

I am not sure about how to resolve the issue. The certificate will expire in a couple of weeks. acme.sh is updated.

**Comment by felicemassaro** [comment]
Sorry for that. Are it is:

./acme.sh --renew --debug 2 -d mywebsite.africa_ecc --cert-home /etc/nginx/ssl/mywebsite.africa_ecc/ --force
[Tue Aug 22 05:17:46 SAST 2023] _is_idn_d='mywebsite.africa_ecc'
[Tue Aug 22 05:17:46 SAST 2023] _idn_temp
[Tue Aug 22 05:17:46 SAST 2023] Lets find script dir.
[Tue Aug 22 05:17:46 SAST 2023] _SCRIPT_='./acme.sh'
[Tue Aug 22 05:17:46 SAST 2023] _script='/home/felice/.acme.sh/acme.sh'
[Tue Aug 22 05:17:46 SAST 2023] _script_home='/home/felice/.acme.sh'
[Tue Aug 22 05:17:46 SAST 2023] Using config home:/home/felice/.acme.sh
[Tue Aug 22 05:17:46 SAST 2023] LE_WORKING_DIR='/home/felice/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.7
[Tue Aug 22 05:17:46 SAST 2023] Running cmd: renew
[Tue Aug 22 05:17:46 SAST 2023] _renewServer
[Tue Aug 22 05:17:46 SAST 2023] Using config home:/home/felice/.acme.sh
[Tue Aug 22 05:17:46 SAST 2023] default_acme_server
[Tue Aug 22 05:17:46 SAST 2023] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Tue Aug 22 05:17:46 SAST 2023] _ACME_SERVER_HOST='acme.zerossl.com'
[Tue Aug 22 05:17:46 SAST 2023] _ACME_SERVER_PATH='v2/DV90'
[Tue Aug 22 05:17:46 SAST 2023] DOMAIN_PATH='/etc/nginx/ssl/mywebsite.africa_ecc//mywebsite.africa_ecc'
[Tue Aug 22 05:17:46 SAST 2023] Renew: 'mywebsite.africa_ecc'
[Tue Aug 22 05:17:46 SAST 2023] 'mywebsite.africa_ecc' is not an issued domain, skip.

**Comment by FarrelF** [comment]
Try using `/etc/nginx/ssl` on `--cert-home` argument instead of `/etc/nginx/ssl/mywebsite.africa_ecc/`

**Comment by felicemassaro** [comment]
**Nope.**  It didn't work:
~/.acme.sh$ ./acme.sh --renew --debug 2 -d mywebsite.africa_ecc --cert-home /etc/nginx/ssl --force
[Tue Aug 22 13:15:21 SAST 2023] _is_idn_d='mywebsite.africa_ecc'
[Tue Aug 22 13:15:21 SAST 2023] _idn_temp
[Tue Aug 22 13:15:21 SAST 2023] Lets find script dir.
[Tue Aug 22 13:15:21 SAST 2023] _SCRIPT_='./acme.sh'
[Tue Aug 22 13:15:21 SAST 2023] _script='/home/felice/.acme.sh/acme.sh'
[Tue Aug 22 13:15:21 SAST 2023] _script_home='/home/felice/.acme.sh'
[Tue Aug 22 13:15:21 SAST 2023] Using config home:/home/felice/.acme.sh
[Tue Aug 22 13:15:21 SAST 2023] LE_WORKING_DIR='/home/felice/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.7
[Tue Aug 22 13:15:21 SAST 2023] Running cmd: renew
[Tue Aug 22 13:15:21 SAST 2023] _renewServer
[Tue Aug 22 13:15:21 SAST 2023] Using config home:/home/felice/.acme.sh
[Tue Aug 22 13:15:21 SAST 2023] default_acme_server
[Tue Aug 22 13:15:21 SAST 2023] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Tue Aug 22 13:15:21 SAST 2023] _ACME_SERVER_HOST='acme.zerossl.com'
[Tue Aug 22 13:15:21 SAST 2023] _ACME_SERVER_PATH='v2/DV90'
[Tue Aug 22 13:15:21 SAST 2023] DOMAIN_PATH='/etc/nginx/ssl/mywebsite.africa_ecc'
[Tue Aug 22 13:15:21 SAST 2023] Renew: 'mywebsite.africa_ecc'
[Tue Aug 22 13:15:21 SAST 2023] 'mywebsite.africa_ecc' is not an issued domain, skip.

**Comment by FarrelF** [comment]
Maybe this is because you're using `-d mywebsite.africa_ecc` which is not a domain name, because there is a `_ecc` suffix?
  
If you want to renew ECC Certificate, you can try using `-d mywebsite.africa --ecc` argument instead of `-d mywebsite.africa_ecc` after `--renew`.

**Comment by felicemassaro** [comment]
Thanks for helping. I tried with the command you suggested. I get this output:

`acme.sh --renew --debug 2 -d mywebsite.africa --ecc --cert-home /etc/nginx/ssl --force
[Tue Aug 22 13:33:53 SAST 2023] _is_idn_d='mywebsite.africa'
[Tue Aug 22 13:33:53 SAST 2023] _idn_temp
[Tue Aug 22 13:33:53 SAST 2023] Lets find script dir.
[Tue Aug 22 13:33:53 SAST 2023] _SCRIPT_='/home/felice/.acme.sh/acme.sh'
[Tue Aug 22 13:33:53 SAST 2023] _script='/home/felice/.acme.sh/acme.sh'
[Tue Aug 22 13:33:53 SAST 2023] _script_home='/home/felice/.acme.sh'
[Tue Aug 22 13:33:53 SAST 2023] Using config home:/home/felice/.acme.sh
[Tue Aug 22 13:33:53 SAST 2023] LE_WORKING_DIR='/home/felice/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.7
[Tue Aug 22 13:33:53 SAST 2023] Running cmd: renew
[Tue Aug 22 13:33:53 SAST 2023] _renewServer
[Tue Aug 22 13:33:53 SAST 2023] Using config home:/home/felice/.acme.sh
[Tue Aug 22 13:33:53 SAST 2023] default_acme_server
[Tue Aug 22 13:33:53 SAST 2023] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Tue Aug 22 13:33:53 SAST 2023] _ACME_SERVER_HOST='acme.zerossl.com'
[Tue Aug 22 13:33:53 SAST 2023] _ACME_SERVER_PATH='v2/DV90'
[Tue Aug 22 13:33:53 SAST 2023] DOMAIN_PATH='/etc/nginx/ssl/mywebsite.africa_ecc'
[Tue Aug 22 13:33:53 SAST 2023] Renew: 'mywebsite.africa'
[Tue Aug 22 13:33:53 SAST 2023] Le_API='https://acme.zerossl.com/v2/DV90'
[Tue Aug 22 13:33:53 SAST 2023] Renew to Le_API=https://acme.zerossl.com/v2/DV90
[Tue Aug 22 13:33:53 SAST 2023] initpath again.
[Tue Aug 22 13:33:53 SAST 2023] Using config home:/home/felice/.acme.sh
[Tue Aug 22 13:33:53 SAST 2023] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Tue Aug 22 13:33:53 SAST 2023] _ACME_SERVER_HOST='acme.zerossl.com'
[Tue Aug 22 13:33:53 SAST 2023] _ACME_SERVER_PATH='v2/DV90'
[Tue Aug 22 13:33:53 SAST 2023] _main_domain='mywebsite.africa'
[Tue Aug 22 13:33:53 SAST 2023] _alt_domains='no'
[Tue Aug 22 13:33:53 SAST 2023] '/var/www/html' does not contain 'dns'
[Tue Aug 22 13:33:53 SAST 2023] '/var/www/html' does not contain 'dns'
[Tue Aug 22 13:33:53 SAST 2023] Le_NextRenewTime='1690790824'
[Tue Aug 22 13:33:53 SAST 2023] Using ACME_DIRECTORY: https://acme.zerossl.com/v2/DV90
[Tue Aug 22 13:33:53 SAST 2023] _init api for server: https://acme.zerossl.com/v2/DV90
[Tue Aug 22 13:33:53 SAST 2023] GET
[Tue Aug 22 13:33:53 SAST 2023] url='https://acme.zerossl.com/v2/DV90'
[Tue Aug 22 13:33:53 SAST 2023] timeout=
[Tue Aug 22 13:33:53 SAST 2023] _CURL='curl --silent --dump-header /home/felice/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.ChPycRbmHF  -g '
[Tue Aug 22 13:33:57 SAST 2023] ret='0'
[Tue Aug 22 13:33:57 SAST 2023] response='{
  "newNonce": "https://acme.zerossl.com/v2/DV90/newNonce",
  "newAccount": "https://acme.zerossl.com/v2/DV90/newAccount",
  "newOrder": "https://acme.zerossl.com/v2/DV90/newOrder",
  "revokeCert": "https://acme.zerossl.com/v2/DV90/revokeCert",
  "keyChange": "https://acme.zerossl.com/v2/DV90/keyChange",
  "meta": {
    "termsOfService": "https://secure.trust-provider.com/repository/docs/Legacy/20230516_Certificate_Subscriber_Agreement_v_2_6_click.pdf",
    "website": "https://zerossl.com",
    "caaIdentities": ["sectigo.com", "trust-provider.com", "usertrust.com", "comodoca.com", "comodo.com"],
    "externalAccountRequired": true
  }
}'
[Tue Aug 22 13:33:57 SAST 2023] ACME_KEY_CHANGE='https://acme.zerossl.com/v2/DV90/keyChange'
[Tue Aug 22 13:33:57 SAST 2023] ACME_NEW_AUTHZ
[Tue Aug 22 13:33:57 SAST 2023] ACME_NEW_ORDER='https://acme.zerossl.com/v2/DV90/newOrder'
[Tue Aug 22 13:33:57 SAST 2023] ACME_NEW_ACCOUNT='https://acme.zerossl.com/v2/DV90/newAccount'
[Tue Aug 22 13:33:57 SAST 2023] ACME_REVOKE_CERT='https://acme.zerossl.com/v2/DV90/revokeCert'
[Tue Aug 22 13:33:57 SAST 2023] ACME_AGREEMENT='https://secure.trust-provider.com/repository/docs/Legacy/20230516_Certificate_Subscriber_Agreement_v_2_6_click.pdf'
[Tue Aug 22 13:33:57 SAST 2023] ACME_NEW_NONCE='https://acme.zerossl.com/v2/DV90/newNonce'
[Tue Aug 22 13:33:57 SAST 2023] Using CA: https://acme.zerossl.com/v2/DV90
[Tue Aug 22 13:33:57 SAST 2023] _on_before_issue
[Tue Aug 22 13:33:57 SAST 2023] _chk_main_domain='mywebsite.africa'
[Tue Aug 22 13:33:57 SAST 2023] _chk_alt_domains
[Tue Aug 22 13:33:57 SAST 2023] '/var/www/html' does not contain 'no'
[Tue Aug 22 13:33:57 SAST 2023] Le_LocalAddress
[Tue Aug 22 13:33:57 SAST 2023] d='mywebsite.africa'
[Tue Aug 22 13:33:57 SAST 2023] Check for domain='mywebsite.africa'
[Tue Aug 22 13:33:57 SAST 2023] _currentRoot='/var/www/html'
[Tue Aug 22 13:33:57 SAST 2023] d
[Tue Aug 22 13:33:57 SAST 2023] '/var/www/html' does not contain 'apache'
[Tue Aug 22 13:33:57 SAST 2023] config file is empty, can not read CA_KEY_HASH
[Tue Aug 22 13:33:57 SAST 2023] _saved_account_key_hash
[Tue Aug 22 13:33:57 SAST 2023] Using config home:/home/felice/.acme.sh
[Tue Aug 22 13:33:57 SAST 2023] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Tue Aug 22 13:33:57 SAST 2023] _ACME_SERVER_HOST='acme.zerossl.com'
[Tue Aug 22 13:33:57 SAST 2023] _ACME_SERVER_PATH='v2/DV90'
[Tue Aug 22 13:33:57 SAST 2023] _init api for server: https://acme.zerossl.com/v2/DV90
[Tue Aug 22 13:33:57 SAST 2023] length='ec-256'
[Tue Aug 22 13:33:57 SAST 2023] Using config home:/home/felice/.acme.sh
[Tue Aug 22 13:33:57 SAST 2023] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Tue Aug 22 13:33:57 SAST 2023] _ACME_SERVER_HOST='acme.zerossl.com'
[Tue Aug 22 13:33:57 SAST 2023] _ACME_SERVER_PATH='v2/DV90'
[Tue Aug 22 13:33:57 SAST 2023] _createkey for file:/home/felice/.acme.sh/ca/acme.zerossl.com/v2/DV90/account.key
[Tue Aug 22 13:33:57 SAST 2023] Use length 256
[Tue Aug 22 13:33:57 SAST 2023] Using ec name: prime256v1
[Tue Aug 22 13:33:57 SAST 2023] Create account key ok.
[Tue Aug 22 13:33:57 SAST 2023] EC key
[Tue Aug 22 13:33:57 SAST 2023] config file is empty, can not read CA_EAB_KEY_ID
[Tue Aug 22 13:33:57 SAST 2023] config file is empty, can not read CA_EAB_HMAC_KEY
[Tue Aug 22 13:33:57 SAST 2023] config file is empty, can not read CA_EMAIL
[Tue Aug 22 13:33:57 SAST 2023] No EAB credentials found for ZeroSSL, let's get one
[Tue Aug 22 13:33:57 SAST 2023] acme.sh is using ZeroSSL as default CA now.
[Tue Aug 22 13:33:57 SAST 2023] Please update your account with an email address first.
[Tue Aug 22 13:33:57 SAST 2023] acme.sh --register-account -m my@example.com
[Tue Aug 22 13:33:57 SAST 2023] See: https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA
[Tue Aug 22 13:33:57 SAST 2023] _on_issue_err
[Tue Aug 22 13:33:57 SAST 2023] Please add '--debug' or '--log' to check more details.
[Tue Aug 22 13:33:57 SAST 2023] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Tue Aug 22 13:33:57 SAST 2023] _chk_vlist
[Tue Aug 22 13:33:57 SAST 2023] '/var/www/html' does not contain 'dns'
[Tue Aug 22 13:33:57 SAST 2023] socat doesn't exist.
[Tue Aug 22 13:33:57 SAST 2023] Diagnosis versions: 
openssl:openssl
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
apache:
apache doesn't exist.
nginx:
nginx version: nginx/1.18.0 (Ubuntu)
built with OpenSSL 3.0.2 15 Mar 2022
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -ffile-prefix-map=/build/nginx-zctdR4/nginx-1.18.0=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-compat --with-debug --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --add-dynamic-module=/build/nginx-zctdR4/nginx-1.18.0/debian/modules/http-geoip2 --with-http_addition_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_sub_module
socat:

`

**Comment by felicemassaro** [comment]
Finally I came right. The firewall was also blocking port 80 as well as nginx  and after resolving these last issues and registering the ZeroSSL Account, the command:
_acme.sh --renew --debug 2 -d mywebsite.africa --ecc --cert-home /etc/nginx/ssl --force_
worked fine and I finally got a "Cert success."

Thanks for helping. Really appreciated
