### ISSUE TITLE
Check syntax for --install-cert on macOS with apache2

### ISSUE THREAD

**Issue by quartermarsh** [acmesh-official/acme.sh#4770]
Hi there,

I have (finally) issued a zerossl cert (ecc) as root user so the cert file is in /var/root/acme.sh/. My first attempt to install the cert broke apache ^_^ so, this time I thought I’d check my syntax with you before I attemped the install to apache. 

Following the example in the readme this is what I’ve come up with:

`./acme.sh/acme.sh --install-cert --ecc -d quartermarsh.org --cert-file /private/etc/apache2/ssl/cert.pem --key-file /private/etc/apache2/ssl/key.pem --fullchain-file /private/etc/apache2/ssl/fullchain.pem --reloadcmd "apachectl restart"`

As you can see I’ve created an ssl folder in the apache user folder and I believe this command will find the correct files in the root folder and create .pem files in that ssl folder for use in the apache main config etc. I also assume that I should do this as su since the cert was issued as su. 

One other thing I’m wondering about is the reloadcmd. Obviously it can’t use sudo but will a simple 'restart' command work or should I use 'force-reload' (which is a command that I can’t find any macOS references for). Another option might be ` apachectl graceful`? ¯\_(ツ)_/¯ 

Thanks for your help :)

**Comment by quartermarsh** [comment]
It looks like 'restart' is the closest darwin equivalent to 'force-reload'. ( see: sudo apachectl -h)

**Comment by quartermarsh** [comment]
So, that command installed the .pem files correctly in the apache2/ssl folder but gave a cryptic message on the reloadcmd: ` Reload error for :` with nothing after the `:`. Actually, it’s not cryptic, it just requires root.

That’s probably because I used a bit of a hack to get the command to run. It required root and I had been having trouble getting the command to run at root, so I changed the permissions on the acme.sh root folder and copied the files into the user apache2 directory. That worked for the cert files but not the reloadcmd. I subsequently noticed that my root shell was bash while my user shell is zsh, which explains the 'command not found' issue on the root shell. That is a mess I’d rather not tackle just now.

At this point I have to ask if there’s another way to set up a cron job for the certificate reissue?

Thanks again, in advance.

**Comment by quartermarsh** [comment]
@Neilpang Sorry to ping you on this but could you look at this cronjob and let me know if it would work for certificate renewal:

0 0 * * * "/Users/mini/.acme.sh"/acme.sh --cron --home "/Users/mini/.acme.sh"

I’ll add here the output of the --install command which worked to install the certs:

```
mini@Minis-Mac-mini ~ % acme.sh --install-cert --ecc -d quartermarsh.org --cert-file /private/etc/apache2/ssl/cert.pem --key-file /private/etc/apache2/ssl/key.pem --fullchain-file /private/etc/apache2/ssl/fullchain.pem --reloadcmd "apachectl restart"
[Thu 31 Aug 2023 09:27:23 PDT] Installing cert to: /private/etc/apache2/ssl/cert.pem
[Thu 31 Aug 2023 09:27:23 PDT] Installing key to: /private/etc/apache2/ssl/key.pem
[Thu 31 Aug 2023 09:27:23 PDT] Installing full chain to: /private/etc/apache2/ssl/fullchain.pem
[Thu 31 Aug 2023 09:27:23 PDT] Run reload cmd: apachectl restart
This operation requires root.
[Thu 31 Aug 2023 09:27:24 PDT] Reload error for :
mini@Minis-Mac-mini ~ % 

```

It seems like a horrible hack to me (see above). Perhaps I should be getting my root bash profile sorted and running the whole command as root. I’m still not certain that would properly restart apache.

**Comment by Neilpang** [comment]
you should configure to use "sudo xxxxxx apachectl xxxx xxxx restart" command without needing your password.
