### ISSUE TITLE
Ability to restart docker container

### ISSUE THREAD

**Issue by oeiber** [acmesh-official/acme.sh#4795]
Hi,
using deploy hook with nginx and docker works fine. But I have also a self written application, which runs in a node container. The application runs in foreground without service. 
Is there a way to restart the entire container after refreshing the certificate?

thank you!

**Comment by oeiber** [comment]
found a workaround: installing docker-cli within acme.sh container. a small shellscript executs nginx reload and also restarting my node container. is it possible to ship the acme.sh container with docker-cli preinstalled?

**Comment by maffe** [comment]
The wiki [shows how to deploy to containers](https://github.com/acmesh-official/acme.sh/wiki/deploy-to-docker-containers) but it’s also possible to [restart containers without giving access to the Docker socket](https://stackoverflow.com/questions/59035543/how-to-execute-command-from-one-docker-container-to-another/78123322#78123322).
