### ISSUE TITLE
How to apply for a certificate using ZeroSSL API Key

### ISSUE THREAD

**Issue by 1trapcode** [acmesh-official/acme.sh#4806]
[https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA](url)
I checked this document. 
But I didn’t see any documentation on using ZeroSSL API Key. (not EAB)

![image](https://github.com/acmesh-official/acme.sh/assets/118535944/b7c081d9-5704-4e01-9dfb-37e88dce3fb4)
ZeroSSL official description supports acme.sh

waiting for reply
thanks :)

**Comment by July-NetEase** [comment]
i have met same problem,  has any idea ?

**Comment by Neilpang** [comment]
we don't support the REST api. 
We just support the EAB key via the ACME api.
