### ISSUE TITLE
Synology DSM API path regex is wrong

### ISSUE THREAD

**Issue by winromulus** [acmesh-official/acme.sh#4808]
Summary: The issue first appeared in [this PR](https://github.com/acmesh-official/acme.sh/pull/4728/files) due to an invalid regex when looking up the API path.

Steps to reproduce
------------------
Try to deploy any certificate to Synology DSM

Debug log
-----------------
Contains sensitive data. Result is a 404 in curl output.

**Comment by essamm63** [comment]
I've found that the issue is that in synology_dsm.sh line 94 is not setting the api_path correctly.
Replacing line 94 of synology_dsm.sh with a jq expression works and seems to be more reliable:
`  api_path=$(echo "$response" | jq -r '.data."SYNO.API.Auth".path')`
