### ISSUE TITLE
Allow to use custom friendly name as CN when SAN is used

### ISSUE THREAD

**Issue by mvelbaum** [acmesh-official/acme.sh#4813]
Suppose I generate multiple certs that contain subdomains 

* a.domain.com
* b.domain.com, c.domain.com
* *.sub1.domain.com, *.sub2.domain.com

It seems that the first domain will be used as the `CN` of the cert, and also as input to commands such as `acme.sh --install-cert -d <domain>`. Since the CN is ignored when SANs are used, is it possible to explicitly use a friendly name for the `CN` when generating the certs so that:

1. Subfolders with certs at `$HOME/.acme.sh/<CN name>` use the friendly name
2. Doing  `acme.sh --install-cert -d <CN name>` is now easier to use, especially when using wildcard domains.

This is basically certbot's [`--cert-name`](https://eff-certbot.readthedocs.io/en/stable/using.html#managing-certificates) feature.

**Comment by Neilpang** [comment]
we have a `--cert-home` too.
https://github.com/acmesh-official/acme.sh/wiki/How-to-install#4-advanced-installation

but it's the home folder for all the certs.

**Comment by mvelbaum** [comment]
I'm not sure why you closed the issue as `--cert-home` is not at all like `--cert-name`. The latter allows you to pick a name PER generated cert, and not for the parent folder.

**Comment by TheWiresharkGuy** [comment]
I also would like to have a customised folder name for my wildcard cert like `star.mydomain.tld` instead of `*.mydomain.tld`
