### ISSUE TITLE
群晖更新后无法使用密码更新证书，开启二次验证后也不行

### ISSUE THREAD

**Issue by gujiangjiang** [acmesh-official/acme.sh#4816]
弄了几个小时，各种组合都尝试过，就是不行，明明设置了SYNO_Device_ID，在Docker的环境里设置也不行，在sh里面设置也不行，怎么设置都不行，一直提示需要SYNO_Device_ID，莫名其妙的人要疯了

<img width="782" alt="QQ20231002-020222@2x" src="https://github.com/acmesh-official/acme.sh/assets/13273955/d2c1f8e4-33a7-4c20-9b74-511fc1478d29">

日志里明明有SYNO_Device_ID，为什么登录还是提示
If two-factor authentication is enabled for the user, set SYNO_Device_ID.

这个SYNO_Device_ID到底要怎么设置才行？Wiki里面也没写，issue翻了一下有人讨论，但是没看懂是怎么弄，说是自动获取，怎么自动获取，浏览器提取的did不行么？

**Comment by gujiangjiang** [comment]
<img width="990" alt="image" src="https://github.com/acmesh-official/acme.sh/assets/13273955/dbfa461b-ce05-4f4b-9e9a-2f782796ff72">

**Comment by gujiangjiang** [comment]
<img width="1176" alt="image" src="https://github.com/acmesh-official/acme.sh/assets/13273955/e76e2185-c633-4f1b-bb8a-71934c4f2282">

**Comment by gujiangjiang** [comment]
<img width="1174" alt="image" src="https://github.com/acmesh-official/acme.sh/assets/13273955/34bcba09-ffed-41b8-a5bb-91c27864282c">

**Comment by jerrell851** [comment]
> Please upgrade to the latest code and try again first. Maybe it's already fixed. `acme.sh --upgrade` If it's still not working, please provide the log with `--debug 2`, otherwise, nobody can help you.
------------------------------------------------------------------------
See Debug 2 logs
------------------------------------------------------------------------
/ # acme.sh --version
https://github.com/acmesh-official/acme.sh
v3.0.7

/ # acme.sh --upgrade
[Fri Oct 13 05:54:14 UTC 2023] Already uptodate!
[Fri Oct 13 05:54:14 UTC 2023] Upgrade success!

/ # acme.sh --deploy --insecure -d "xxx.com" -d "*.xxx.com" --deploy-hook synology_dsm --debug 2
[Fri Oct 13 05:54:49 UTC 2023] Lets find script dir.
[Fri Oct 13 05:54:49 UTC 2023] _SCRIPT_='/usr/local/bin/acme.sh'
[Fri Oct 13 05:54:49 UTC 2023] _script='/root/.acme.sh/acme.sh'
[Fri Oct 13 05:54:49 UTC 2023] _script_home='/root/.acme.sh'
[Fri Oct 13 05:54:49 UTC 2023] Using default home:/root/.acme.sh
[Fri Oct 13 05:54:49 UTC 2023] Using config home:/acme.sh
[Fri Oct 13 05:54:49 UTC 2023] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.7
[Fri Oct 13 05:54:49 UTC 2023] Running cmd: deploy
[Fri Oct 13 05:54:49 UTC 2023] Using config home:/acme.sh
[Fri Oct 13 05:54:49 UTC 2023] default_acme_server
[Fri Oct 13 05:54:49 UTC 2023] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Fri Oct 13 05:54:49 UTC 2023] _ACME_SERVER_HOST='acme.zerossl.com'
[Fri Oct 13 05:54:49 UTC 2023] _ACME_SERVER_PATH='v2/DV90'
[Fri Oct 13 05:54:49 UTC 2023] DOMAIN_PATH='/acme.sh/xxx.com'
[Fri Oct 13 05:54:49 UTC 2023] DOMAIN_CONF='/acme.sh/xxx.com/xxx.com.conf'
[Fri Oct 13 05:54:49 UTC 2023] _deployApi='/root/.acme.sh/deploy/synology_dsm.sh'
[Fri Oct 13 05:54:49 UTC 2023] _cdomain='xxx.com'
[Fri Oct 13 05:54:49 UTC 2023] SYNO_Username='admin'
[Fri Oct 13 05:54:49 UTC 2023] SYNO_Password='[hidden]'
[Fri Oct 13 05:54:49 UTC 2023] SYNO_Create
[Fri Oct 13 05:54:49 UTC 2023] SYNO_Device_Name
[Fri Oct 13 05:54:49 UTC 2023] SYNO_Device_ID
[Fri Oct 13 05:54:49 UTC 2023] SYNO_Scheme='https'
[Fri Oct 13 05:54:49 UTC 2023] SYNO_Hostname='dsm.xxx.com'
[Fri Oct 13 05:54:49 UTC 2023] SYNO_Port='5501'
[Fri Oct 13 05:54:49 UTC 2023] trim quotation marks
[Fri Oct 13 05:54:49 UTC 2023] SYNO_Certificate
[Fri Oct 13 05:54:49 UTC 2023] _base_url='https://dsm.xxx.com:5501'
[Fri Oct 13 05:54:49 UTC 2023] Getting API version
[Fri Oct 13 05:54:49 UTC 2023] GET
[Fri Oct 13 05:54:49 UTC 2023] url='https://dsm.xxx.com:5501/webapi/query.cgi?api=SYNO.API.Info&version=1&method=query&query=SYNO.API.Auth'
[Fri Oct 13 05:54:49 UTC 2023] timeout=
[Fri Oct 13 05:54:49 UTC 2023] _CURL='curl --silent --dump-header /acme.sh/http.header  -L  --trace-ascii /tmp/tmp.1AzpaEOW6k  -g  --insecure  '
[Fri Oct 13 05:54:49 UTC 2023] ret='0'
[Fri Oct 13 05:54:49 UTC 2023] Logging into dsm.xxx.com:5501
[Fri Oct 13 05:54:49 UTC 2023] WARNING: Usage of SYNO_TOTP_SECRET is deprecated!
[Fri Oct 13 05:54:49 UTC 2023]          See synology_dsm.sh script or ACME.sh Wiki page for details:
[Fri Oct 13 05:54:49 UTC 2023]          https://github.com/acmesh-official/acme.sh/wiki/Synology-NAS-Guide
[Fri Oct 13 05:54:49 UTC 2023] POST
[Fri Oct 13 05:54:49 UTC 2023] _post_url='https://dsm.xxx.com:5501/webapi/auth.cgi?enable_syno_token=yes'
[Fri Oct 13 05:54:49 UTC 2023] body='method=login&account=admin&passwd=[hidden]&api=SYNO.API.Auth&version=7&enable_syno_token=yes&otp_code=686919&device_name=certrenewal&device_id='
[Fri Oct 13 05:54:49 UTC 2023] _postContentType
[Fri Oct 13 05:54:49 UTC 2023] _CURL='curl --silent --dump-header /acme.sh/http.header  -L  --trace-ascii /tmp/tmp.q9tG2ybG0v  -g  --insecure  '
[Fri Oct 13 05:54:55 UTC 2023] _ret='0'
[Fri Oct 13 05:54:55 UTC 2023] Session ID
[Fri Oct 13 05:54:55 UTC 2023] SynoToken
[Fri Oct 13 05:54:55 UTC 2023] Unable to authenticate to https://dsm.xxx.com:5501 - check your username & password.
[Fri Oct 13 05:54:55 UTC 2023] If two-factor authentication is enabled for the user, set SYNO_Device_ID.
[Fri Oct 13 05:54:55 UTC 2023] Error deploy for domain:xxx.com
[Fri Oct 13 05:54:55 UTC 2023] Deploy error.
/ #

**Comment by CoOlaRlL** [comment]
登录设置下去除重定向到https，更改协议端口，增加DID，去除SYNO_Create=1，总之就是在导入环境里找找问题

**Comment by gujiangjiang** [comment]
@CoOlaRlL 
非常感谢您的帮助，我又多次尝试了，发现了问题所在，就是那个域名，默认的是localhost，我改成本地的IP地址也不行，127也不行，但是改成DDNS的域名反而就成功了，我怀疑是不是那个DID是根据域名来的，也就是通过域名登录群晖获取的DID只能在域名登录的情况下才能使用，用localhost登录配合域名登录下获取的DID无法登录

**Comment by gujiangjiang** [comment]
进一步测试了，发现与获取的DID无关，DID是通用的，无论是IP还是域名获取的DID都是没问题的，但是我测试下来，就是IP和localhost不行，用域名是可以的，不知道什么情况，ip:5001或者localhost:5001也不行，但是域名:5001却没问题，非常奇怪的问题。。。DID是同一个
