### ISSUE TITLE
egrep: warning: egrep is obsolescent; using grep -E

### ISSUE THREAD

**Issue by incognico** [acmesh-official/acme.sh#4835]
Getting a lot of warnings when using acme.sh now: `egrep: warning: egrep is obsolescent; using grep -E`. Maybe consider changing `egrep` to `grep -E`?

**Comment by Neilpang** [comment]
what OS do you use?

**Comment by incognico** [comment]
> what OS do you use?

Arch Linux. Probably happens since some recent update.

**Comment by cerealconyogurt** [comment]
I just upgraded the code today I then when I renewed my certs I've got same warning message. The certs were renewed but the warning messages were there.
