### ISSUE TITLE
Please remove wget install way

### ISSUE THREAD

**Issue by jmzwcn** [acmesh-official/acme.sh#4862]
Please remove the following:

wget -O -  https://get.acme.sh | sh -s email=my@example.com

Actually  It is wrong. ACME reqiure "curl".

**Comment by jmzwcn** [comment]
This is serious mistake for user with wget but NO curl. For instance, all env based alpine.

**Comment by Neilpang** [comment]
https://get.acme.sh/
在安装时都判断过, 有curl 就用 curl.  没有就用wget. 
我在一个新虚机中试了, 只有安装有wget 时,  完全没问题.

如果你遇到问题,  具体说问题, 正常汇报.

**Comment by jmzwcn** [comment]
You could use nginx:alpine-slim for a try.
