### ISSUE TITLE
群晖DSM 7.1.1-42962 Update 6 部署证书提示If two-factor authentication is enabled for the user, set SYNO_Device_ID.

### ISSUE THREAD

**Issue by wolfcdd** [acmesh-official/acme.sh#4868]
过程：

> 之前通过PR #4646的dsm deploy脚本成功部署，只是最后提示 “Restarting HTTP services failed”；于是更新到最新版本，想再一次验证是否可以成功。结果还是未成功，但是从debug信息中可以看到SYNO_Device_ID是正常的。

版本：

> 
> root@xxx:~# acme.sh -v
> https://github.com/acmesh-official/acme.sh
> v3.0.7
> 

报错详情：

> root@xxx:~# acme.sh --deploy --home /volume1/cert/syno-acme/acme.sh -d "aaa.com" --deploy-hook synology_dsm
> [Sat Nov 11 14:44:12 CST 2023] The domain 'aaa.com' seems to have a ECC cert already, lets use ecc cert.
> [Sat Nov 11 14:44:13 CST 2023] Logging into 10.0.0.22:5000
> [Sat Nov 11 14:44:13 CST 2023] Unable to authenticate to http://10.0.0.22:5000 - check your username & password.
> [Sat Nov 11 14:44:13 CST 2023] If two-factor authentication is enabled for the user, set SYNO_Device_ID.
> [Sat Nov 11 14:44:13 CST 2023] Error deploy for domain:hems.top
> [Sat Nov 11 14:44:13 CST 2023] Deploy error.
> 

debug -2 信息：

> [Sat Nov 11 15:13:45 CST 2023] Lets find script dir.
> [Sat Nov 11 15:13:45 CST 2023] _SCRIPT_='/volume1/cert/syno-acme/acme.sh/acme.sh'
> [Sat Nov 11 15:13:45 CST 2023] _script='/volume1/cert/syno-acme/acme.sh/acme.sh'
> [Sat Nov 11 15:13:45 CST 2023] _script_home='/volume1/cert/syno-acme/acme.sh'
> [Sat Nov 11 15:13:45 CST 2023] Using config home:/volume1/cert/syno-acme/acme.sh
> [Sat Nov 11 15:13:45 CST 2023] LE_WORKING_DIR='/volume1/cert/syno-acme/acme.sh'
> [Sat Nov 11 15:13:45 CST 2023] Running cmd: deploy
> [Sat Nov 11 15:13:45 CST 2023] Using config home:/volume1/cert/syno-acme/acme.sh
> [Sat Nov 11 15:13:45 CST 2023] default_acme_server
> [Sat Nov 11 15:13:45 CST 2023] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
> [Sat Nov 11 15:13:45 CST 2023] _ACME_SERVER_HOST='acme.zerossl.com'
> [Sat Nov 11 15:13:45 CST 2023] _ACME_SERVER_PATH='v2/DV90'
> [Sat Nov 11 15:13:45 CST 2023] DOMAIN_PATH='/volume1/cert/syno-acme/acme.sh/aaa.com_ecc'
> [Sat Nov 11 15:13:45 CST 2023] DOMAIN_CONF='/volume1/cert/syno-acme/acme.sh/aaa.com_ecc/aaa.com.conf'
> [Sat Nov 11 15:13:45 CST 2023] _deployApi='/volume1/cert/syno-acme/acme.sh/deploy/synology_dsm.sh'
> [Sat Nov 11 15:13:45 CST 2023] _cdomain='aaa.com'
> [Sat Nov 11 15:13:45 CST 2023] SYNO_Username='admin'
> [Sat Nov 11 15:13:45 CST 2023] SYNO_Password='[hidden](please add '--output-insecure' to see this value)'
> [Sat Nov 11 15:13:45 CST 2023] SYNO_Create
> [Sat Nov 11 15:13:45 CST 2023] SYNO_Device_Name='CertRenewal'
> [Sat Nov 11 15:13:45 CST 2023] SYNO_Device_ID='[hidden](please add '--output-insecure' to see this value)'
> [Sat Nov 11 15:13:45 CST 2023] SYNO_Scheme='http'
> [Sat Nov 11 15:13:45 CST 2023] SYNO_Hostname='10.0.0.22'
> [Sat Nov 11 15:13:45 CST 2023] SYNO_Port='5000'
> [Sat Nov 11 15:13:45 CST 2023] SYNO_Certificate
> [Sat Nov 11 15:13:45 CST 2023] _base_url='http://10.0.0.22:5000'
> [Sat Nov 11 15:13:45 CST 2023] Getting API version
> [Sat Nov 11 15:13:45 CST 2023] GET
> [Sat Nov 11 15:13:45 CST 2023] url='http://10.0.0.22:5000/webapi/query.cgi?api=SYNO.API.Info&amp;version=1&amp;method=query&amp;query=SYNO.API.Auth'
> [Sat Nov 11 15:13:45 CST 2023] timeout=
> [Sat Nov 11 15:13:45 CST 2023] _CURL='curl --silent --dump-header /volume1/cert/syno-acme/acme.sh/http.header  -L  --trace-ascii /tmp/tmp.QD1HRBpPwt  -g '
> [Sat Nov 11 15:13:45 CST 2023] ret='0'
> [Sat Nov 11 15:13:45 CST 2023] GET
> [Sat Nov 11 15:13:45 CST 2023] url='http://10.0.0.22:5000/webapi/entry.cgi?api=SYNO.API.Auth&amp;version=7&amp;method=login&amp;format=sid&amp;account=admin&amp;passwd=Wolf2064&amp;enable_syno_token=yes&amp;device_name=CertRenewal&amp;device_id=-6s3tNbMgLrunWlvKMI0N7Ptu7DziwSwx6H0zfVLRSiNskbtYRXjXxzda7p9NsLmLgAcPfbaWoqFhlmDY3LPTg'
> [Sat Nov 11 15:13:45 CST 2023] timeout=
> [Sat Nov 11 15:13:45 CST 2023] _CURL='curl --silent --dump-header /volume1/cert/syno-acme/acme.sh/http.header  -L  --trace-ascii /tmp/tmp.55YHlaF9DM  -g '
> [Sat Nov 11 15:13:45 CST 2023] ret='0'
> [Sat Nov 11 15:13:45 CST 2023] Session ID
> [Sat Nov 11 15:13:45 CST 2023] SynoToken
> [Sat Nov 11 15:13:45 CST 2023] Unable to authenticate to http://10.0.0.22:5000 - check your username &amp; password.
> [Sat Nov 11 15:13:45 CST 2023] If two-factor authentication is enabled for the user, set SYNO_Device_ID.
> [Sat Nov 11 15:13:45 CST 2023] Error deploy for domain:aaa.com
> [Sat Nov 11 15:13:45 CST 2023] Deploy error.
> 

尝试过排错（未成功）：

> 1、https://github.com/acmesh-official/acme.sh/issues/4721
> 2、将hostname恢复成默认的localhost
> 3、将SYNO开头的所有环境变量重新export

**Comment by ninetian** [comment]
提示的问题是用户名或密码错误

先把系统的缓存清理掉
然后 debug模式

返回的
http://10.0.0.22:5000/webapi/entry.cgi?api=SYNO.API.Auth&amp;version=7&amp;method=login&amp;format=sid&amp;account=admin&amp;passwd=hide&amp;enable_syno_token=yes&amp;device_name=CertRenewal&amp;device_id=-6s3tNbMgLrunWlvKMI0N7Ptu7DziwSwx6H0zfVLRSiNskbtYRXjXxzda7p9NsLmLgAcPfbaWoqFhlmDY3L

你COPY到浏览器打开 看下返回什么信息
如果也是登录错误 可能是你IP/API权限没开，也可能是开了2步验证

一点一点的DEBUG

**Comment by wolfcdd** [comment]
已解决。
通过remove，先移除，再清空对应文件夹，重新issue 重新deploy即可

**Comment by Subdue0** [comment]
> 已解决。 通过remove，先移除，再清空对应文件夹，重新issue 重新deploy即可

能详细说说吗？我和你遇到一样的问题。
