### ISSUE TITLE
acme.sh --signcsr command is failing with status invalid

### ISSUE THREAD

**Issue by serajdarak1335** [acmesh-official/acme.sh#4901]
The acme.sh --signcsr command is failing with status invalid when we run it. Please help....

The ACME command is -
acme.sh --signcsr --csr api.MYDOMAIN.csr -w api.MYDOMAIN -d api.MYDOMAIN --dns dns_azure --server zerossl --force --debug 2

Closing this because it's a duplication of #4911

**Comment by Neilpang** [comment]
remove `-d api.MYDOMAIN` from the commandline.

**Comment by serajdarak1335** [comment]
I tried without the -d option and its still the same.

Looking at the logs, i notice the expiry date is set to 30 days and in ZeroSSL site there are 2 options for expiry date - 90 days and 1 year. I guess the ACME script is defaulting it to 30 days. I've checked the documentation for ACME i cannot see how to set the Expiry Date. Can you help? 

[Thu Dec  7 20:22:56 GMT 2023] original='{"identifier":{"type":"dns","value":"api.ocp10.azure.dso.digital.mod.uk"},"status":"invalid","expires":"2024-01-06T20:22:57Z","challenges":[{"type":"http-01","url":"https://acme.zerossl.com/v2/DV90/ch

**Comment by serajdarak1335** [comment]
Closing this because it's a duplication of https://github.com/acmesh-official/acme.sh/issues/4911
