### ISSUE TITLE
How is this an improvement over certbot ?

### ISSUE THREAD

**Issue by jult** [acmesh-official/acme.sh#4912]
I run this command;

`certbot certonly --key-type ecdsa --dns-cloudflare --dns-cloudflare-credentials ~/my_api_creds --dns-cloudflare-propagation-seconds 60 -d my.domain.net,domain.org,*.domain.org,domain.nl,*.domain.nl etc.`

and I'm done. This is actually shorter, more concise, than with acme.sh, so what's the big deal?
It's even using the expected /etc/letsencrypt storage format, which, honestly, is more logical than the way monsieur Pang does it, but hey, could be me. I just don't understand why users keep pointing me to acme as it being better somehow than certbot. Which it just isn't,

**Comment by Neilpang** [comment]
your command can be more simplified with acme.sh:

```
acme.sh  --issue  -d my.domain.net,domain.org,*.domain.org,domain.nl,*.domain.nl    --dns  dns_cf
```
