### ISSUE TITLE
wiki license ?

### ISSUE THREAD

**Issue by kapouer** [acmesh-official/acme.sh#4917]
Hi,

I just realized I edited the wiki. My goal was to submit a PR, not directly edit it.
The idea was that the wiki itself, being distributed from [another git repository](https://github.com/acmesh-official/acme.sh.wiki), needed to have a copyright/license info declared.

**Comment by kapouer** [comment]
Also the main README.md, or the ./acme.sh file, should contain line with
Copyright 2016-2023, Neilpang <www@neilpang.com>
or something similar, like
Copyright  2016-2023, acme.sh contributors

**Comment by Neilpang** [comment]
I think it's the same license as the main repo.

**Comment by kapouer** [comment]
Well, the problem is that since it's a different repo, it should have its own license documented somewhere, like what I added yesterday.
