### ISSUE TITLE
Can not init api for: https://acme.zerossl.com/v2/DV90

### ISSUE THREAD

**Issue by avvjunk** [acmesh-official/acme.sh#4919]
Whatever I do, I always get the following error:
Can not init api for: https://acme.zerossl.com/v2/DV90

When I try to used letsencrypt instead of zerossl I get:
Can not init api for: https://acme-v02.api.letsencrypt.org/directory

Steps to reproduce
acme.sh --register-account -m example@gmail.com --debug 3
acme.sh --register-account -m example@gmail.com --debug 3 --server letsencrypt

acme.sh --version
https://github.com/acmesh-official/acme.sh
v3.0.8

OS: Ubuntu 22.04.3 LTS

wget https://acme.zerossl.com/v2/DV90 or wget https://acme-v02.api.letsencrypt.org/directory can access both urls without issues (the json files are downloaded)

I also tried these instructions using EAB credentials with the same result: https://superuser.com/questions/1660425/how-to-automaticly-renew-zerossl-certificate

zerossl had issues with their api over the last couple of these, but these issues seem to be resolved. I have been able to create EAB credentials and, like mentioned, accessing the urls with wget has been no problem.

Debug log
-----------------
acme.sh --register-account -m example@gmail.com --debug 3
[di 19 dec 2023 13:36:37 CET] /home/example/.acme.sh/acme.sh:_exists:534 readlink exists=0
[di 19 dec 2023 13:36:37 CET] /home/example/.acme.sh/acme.sh:_exists:534 dirname exists=0
[di 19 dec 2023 13:36:37 CET] /home/example/.acme.sh/acme.sh:__initHome:2645 Lets find script dir.
[di 19 dec 2023 13:36:37 CET] /home/example/.acme.sh/acme.sh:__initHome:2646 _SCRIPT_='/home/example/.acme.sh/acme.sh'
[di 19 dec 2023 13:36:37 CET] /home/example/.acme.sh/acme.sh:__initHome:2648 _script='/home/example/.acme.sh/acme.sh'
[di 19 dec 2023 13:36:37 CET] acme.sh:__initHome:2650                  _script_home='/home/example/.acme.sh'
[di 19 dec 2023 13:36:37 CET] acme.sh:__initHome:2677                  Using config home:/home/example/.acme.sh
[di 19 dec 2023 13:36:37 CET] acme.sh:__initHome:2691                  ACCOUNT_CONF_PATH='/home/example/.acme.sh/account.conf'
[di 19 dec 2023 13:36:37 CET] acme.sh:_process:7842                    LE_WORKING_DIR='/home/example/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.8
[di 19 dec 2023 13:36:37 CET] acme.sh:_process:7850                    Running cmd: registeraccount
[di 19 dec 2023 13:36:37 CET] acme.sh:__initHome:2677                  Using config home:/home/example/.acme.sh
[di 19 dec 2023 13:36:37 CET] acme.sh:__initHome:2691                  ACCOUNT_CONF_PATH='/home/example/.acme.sh/account.conf'
[di 19 dec 2023 13:36:37 CET] acme.sh:_initpath:2807                   default_acme_server
[di 19 dec 2023 13:36:37 CET] acme.sh:_initpath:2816                   ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[di 19 dec 2023 13:36:37 CET] acme.sh:_initpath:2818                   _ACME_SERVER_HOST='acme.zerossl.com'
[di 19 dec 2023 13:36:37 CET] acme.sh:_initpath:2821                   _ACME_SERVER_PATH='v2/DV90'
[di 19 dec 2023 13:36:37 CET] acme.sh:_initpath:2828                   CA_CONF='/home/example/.acme.sh/ca/acme.zerossl.com/v2/DV90/ca.conf'
[di 19 dec 2023 13:36:37 CET] acme.sh:__initHome:2677                  Using config home:/home/example/.acme.sh
[di 19 dec 2023 13:36:37 CET] acme.sh:__initHome:2691                  ACCOUNT_CONF_PATH='/home/example/.acme.sh/account.conf'
[di 19 dec 2023 13:36:37 CET] acme.sh:_initpath:2816                   ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[di 19 dec 2023 13:36:37 CET] acme.sh:_initpath:2818                   _ACME_SERVER_HOST='acme.zerossl.com'
[di 19 dec 2023 13:36:37 CET] acme.sh:_initpath:2821                   _ACME_SERVER_PATH='v2/DV90'
[di 19 dec 2023 13:36:37 CET] acme.sh:_initpath:2828                   CA_CONF='/home/example/.acme.sh/ca/acme.zerossl.com/v2/DV90/ca.conf'
[di 19 dec 2023 13:36:37 CET] acme.sh:_regAccount:3684                 _regAccount
[di 19 dec 2023 13:36:37 CET] acme.sh:_initAPI:2714                    _init api for server: https://acme.zerossl.com/v2/DV90
[di 19 dec 2023 13:36:37 CET] acme.sh:_get:2038                        GET
[di 19 dec 2023 13:36:37 CET] acme.sh:_get:2042                        url='https://acme.zerossl.com/v2/DV90'
[di 19 dec 2023 13:36:37 CET] acme.sh:_get:2043                        timeout=
[di 19 dec 2023 13:36:37 CET] acme.sh:_exists:534                      curl exists=0
[di 19 dec 2023 13:36:37 CET] acme.sh:_exists:534                      mktemp exists=0
[di 19 dec 2023 13:36:38 CET] acme.sh:_exists:534                      wget exists=0
[di 19 dec 2023 13:36:38 CET] acme.sh:_get:2055                        _CURL='curl --silent --dump-header /home/example/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.9cp4mbvRWm  -g '
[di 19 dec 2023 13:36:38 CET] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 23
[di 19 dec 2023 13:36:38 CET] Here is the curl dump log:
[di 19 dec 2023 13:36:38 CET] 
[di 19 dec 2023 13:36:38 CET] acme.sh:_get:2107                        ret='23'
[di 19 dec 2023 13:36:38 CET] acme.sh:_initAPI:2723                    response
[di 19 dec 2023 13:36:38 CET] Can not init api for: https://acme.zerossl.com/v2/DV90.

**Comment by Neilpang** [comment]
```
[di 19 dec 2023 13:36:38 CET] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 23
[di 19 dec 2023 13:36:38 CET] Here is the curl dump log:
```

![image](https://github.com/acmesh-official/acme.sh/assets/8305679/1d9c3786-ac55-41fa-bb66-76ee8b974a9a)

**Comment by avvjunk** [comment]
@Neilpang 

I noticed this error too, but I have no idea how to debug this further. Could you give me any hint on what I should look for? Like write permissions on the file system (because of "An error occurred when writing received data to a local file")

I have no idea what to do? I willing to invest time and effort, but I currently just completely stuck.
