### ISSUE TITLE
Stateless and TLS-ALPN-01

### ISSUE THREAD

**Issue by flobernd** [acmesh-official/acme.sh#4926]
Hi there,

is it possible to use `stateless` mode with a `TLS-ALPN-01` challenge? I tried:

```bash
acme.sh --config-home /var/lib/acme --issue -d DOMAIN --stateless --alpn --keylength ec-256
```

But it seems like `HTTP-01` is used:

```
Error, can not get domain token "type":"http-01","url":"https://acme.zerossl.com/v2/DV90/chall/<redacted>","status":"invalid","error":{
```

Am I'm doing it wrong or does `acme.sh` currently not support that scenario?

**Comment by flobernd** [comment]
I'm using the latest version and the relevant log line is already included in my issue comment.

**Comment by jueduizone** [comment]
you can try to use Let's encrypt CA, run the command:
`acme.sh --set-default-ca  --server  letsencrypt`

**Comment by flobernd** [comment]
@jueduizone Thanks for your reply, but I don't see how this would help me unless LE would be using 'stateless' and 'http-alpn-01' by default. Is that the case?

I would like to handle both, challenge- and application-traffic, on port 443, if possible. In addition, stateless mode is a hard requirement for my usecase.

**Comment by Neilpang** [comment]
>> does acme.sh currently not support that scenario?

No.

**Comment by flobernd** [comment]
@Neilpang Thanks for answering. Are there any plans to implement this functionality in the future and/or would you accept a PR for that?

**Comment by Neilpang** [comment]
how about this:
https://github.com/acmesh-official/acme.sh/wiki/TLS-ALPN-without-downtime
