### ISSUE TITLE
How to use multiple API for different DNS provider to issue SAN certificate?

### ISSUE THREAD

**Issue by VSKUMBHANI** [acmesh-official/acme.sh#4942]
### SAN certificate for multiple domains to different DNS provider.
I have 2 domains and I want to issue single certificate (SAN) for custom subdomains. I'm able to issue the certificate for single subdomain if I use individual API but not able to issue the certificate for second subdomain due to API is different for this.

So is there anyway to issue SAN certificate for multiple domains to different DNS provider?

**Comment by VSKUMBHANI** [comment]
v3.0.7 is installed.

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh/wiki/How-to-issue-a-cert#3-multiple-domains-san-mode--hybrid-mode

**Comment by VSKUMBHANI** [comment]
@Neilpang I used the same method as described in KB, but command export cPanel_Apitoken, cPanel_Username not saved the data in account.conf file for one domain. If I run it for 1st domain then it will overwrite to 2nd domain's Apitoken and Username. My both domain are in cPanel but authentication are different.

Is there anything missing to save the data?
