### ISSUE TITLE
Issues with 3 of my domain wildcard certificates where as to all others work fine. Please help.

### ISSUE THREAD

**Issue by mrlerch** [acmesh-official/acme.sh#4951]
Steps to reproduce

### my script that used to work each and every time, and still kind of works, but produces errors for 3 of the domains.
echo "Getting group cert for *.germcan.com" 
/root/.acme.sh/acme.sh $1 --renew -d germcan.com -d '*.germcan.com' -d accesspanel.com -d '*.accesspanel.com' -d accesspanel.net -d '*.accesspanel.net' -d lerchdesign.com -d '*.lerchdesign.com' -d lerchdesign.de -d '*.lerchdesign.de' -d lerchdesign.net -d '*.lerchdesign.net' -d lerchdesign.us -d '*.lerchdesign.us' -d ppsdoors.com -d '*.ppsdoors.com' -d proproductssales.com -d '*.proproductssales.com' -d proproductssales.net -d '*.proproductssales.net' -d proproductssales.one -d '*.proproductssales.one' -d propro.us -d '*.propro.us' -d pps.one -d '*.pps.one' -d sachwin.com -d '*.sachwin.com' --dns dns_gd | grep 'Cert success.' &> /dev/null

echo "Getting individual certs"

echo "Getting cert for *.accesspanel.com" 
/root/.acme.sh/acme.sh $1 --renew --debug 2 -d accesspanel.com -d '*.accesspanel.com' --dns dns_gd | grep 'Cert success.' &> /dev/null
echo "Getting cert for *.accesspanel.net"
/root/.acme.sh/acme.sh $1 --renew --debug 2 -d accesspanel.net -d '*.accesspanel.net' --dns dns_gd | grep 'Cert success.' &> /dev/null
echo "Getting cert for *.lerchdesign.com"
/root/.acme.sh/acme.sh $1 --renew -d lerchdesign.com -d '*.lerchdesign.com' --dns dns_gd | grep 'Cert success.' &> /dev/null
echo "Getting cert for *.lerchdesign.de"
/root/.acme.sh/acme.sh $1 --renew -d lerchdesign.de -d '*.lerchdesign.de' --dns dns_gd | grep 'Cert success.' &> /dev/null
echo "Getting cert for *.lerchdesign.net"
/root/.acme.sh/acme.sh $1 --renew -d lerchdesign.net -d '*.lerchdesign.net' --dns dns_gd | grep 'Cert success.' &> /dev/null
echo "Getting cert for *.lerchdesign.us"
/root/.acme.sh/acme.sh $1 --renew --debug 2 -d lerchdesign.us -d '*.lerchdesign.us' --dns dns_gd | grep 'Cert success.' &> /dev/null
echo "Getting cert for *.ppsdoors.com"
/root/.acme.sh/acme.sh $1 --renew -d ppsdoors.com -d '*.ppsdoors.com' --dns dns_gd | grep 'Cert success.' &> /dev/null
echo "Getting cert for *.proproductssales.com"
/root/.acme.sh/acme.sh $1 --renew -d proproductssales.com -d '*.proproductssales.com' --dns dns_gd | grep 'Cert success.' &> /dev/null
echo "Getting cert for *.proproductssales.net"
/root/.acme.sh/acme.sh $1 --renew -d proproductssales.net -d '*.proproductssales.net' --dns dns_gd | grep 'Cert success.' &> /dev/null
echo "Getting cert for *.proproductssales.one"
/root/.acme.sh/acme.sh $1 --renew -d proproductssales.one -d '*.proproductssales.one' --dns dns_gd | grep 'Cert success.' &> /dev/null
echo "Getting cert for *.propro.us"
/root/.acme.sh/acme.sh $1 --renew -d propro.us -d '*.propro.us' --dns dns_gd | grep 'Cert success.' &> /dev/null
echo "Getting cert for *.pps.one"
/root/.acme.sh/acme.sh $1 --renew -d pps.one -d '*.pps.one' --dns dns_gd | grep 'Cert success.' &> /dev/null
echo "Getting cert for *.sachwin.com"
/root/.acme.sh/acme.sh $1 --renew -d sachwin.com -d '*.sachwin.com' --dns dns_gd | grep 'Cert success.' &> /dev/null
echo "Done getting certs."

###This produces this:
Getting group cert for *.germcan.com
Getting individual certs
Getting cert for *.accesspanel.com
[Mon Jan 15 09:45:06 PST 2024] Error, can not get domain token "type":"dns-01","url":"https://acme.zerossl.com/v2/DV90/chall/jiYGolffkUURJIVji4GwzQ","status":"invalid","error":{
[Mon Jan 15 09:45:06 PST 2024] Please check log file for more details: /root/.acme.sh/acme.sh.log
Getting cert for *.accesspanel.net
Getting cert for *.lerchdesign.com
[Mon Jan 15 09:46:16 PST 2024] Error, can not get domain token "type":"dns-01","url":"https://acme.zerossl.com/v2/DV90/chall/MEb1FCUdBtM5DWF8-JmNVg","status":"invalid","error":{
[Mon Jan 15 09:46:16 PST 2024] Please check log file for more details: /root/.acme.sh/acme.sh.log
Getting cert for *.lerchdesign.de
Getting cert for *.lerchdesign.net
Getting cert for *.lerchdesign.us
[Mon Jan 15 09:47:59 PST 2024] Error, can not get domain token "type":"dns-01","url":"https://acme.zerossl.com/v2/DV90/chall/hYCG68D5sSN8JZFTO5A5iw","status":"invalid","error":{
[Mon Jan 15 09:47:59 PST 2024] Please check log file for more details: /root/.acme.sh/acme.sh.log
Getting cert for *.ppsdoors.com
Getting cert for *.proproductssales.com
Getting cert for *.proproductssales.net
Getting cert for *.proproductssales.one
Getting cert for *.propro.us
Getting cert for *.pps.one
Getting cert for *.sachwin.com
Done getting certs.

------------------

Debug log

See attached.
[debug.log](https://github.com/acmesh-official/acme.sh/files/13942705/debug.log)

-----------------

```
acme.sh  --issue .....   --debug 2
```

**Comment by mrlerch** [comment]
Did that already prior!On Jan 15, 2024, at 12:08 PM, github-actions[bot] ***@***.***> wrote:﻿
Please upgrade to the latest code and try again first. Maybe it's already fixed.              acme.sh --upgrade              If it's still not working, please provide the log with --debug 2, otherwise, nobody can help you.

**Comment by dnessett** [comment]
I have the same problem. I have attached a file with -debug 2 output
[Cert renewal failure -debug 2 output.txt](https://github.com/acmesh-official/acme.sh/files/14048223/Cert.renewal.failure.-debug.2.output.txt)

**Comment by mrlerch** [comment]
So, I think I "fixed" it ... kind of. 
1. I went into /root/.acme.sh/ and renamed the domain folders I was having problems with
2. I ran the command for each one of the problem domains:
/root/.acme.sh/acme.sh --issue -d domainname.com s -d '*.domainname.com' --dns dns_gd

This created a new certificate for each of the domains in question, but.....

I saw that it put it into folders like domain1.com_ecc, domain2.com_ecc, ....

What gives? Why? No clue. I want directories like domain1.com, domain2.com, just like all the others.

3. So I dug into the /root/.acme.sh/acme.sh script and found the following lines:

ECC_SEP="_"
ECC_SUFFIX="${ECC_SEP}ecc"

And changed them to:

ECC_SEP=""
ECC_SUFFIX="${ECC_SEP}"

4. I deleted the 3 domain folders (domain1.com_ecc, domain2.com_ecc, etc) and re-ran the commands from earlier for each one of the domains:

/root/.acme.sh/acme.sh --issue -d domain1.com s -d '*.domain1.com' --dns dns_gd
/root/.acme.sh/acme.sh --issue -d domain2.com s -d '*.domain2.com' --dns dns_gd
etc.

5. Success. Now I got 3 folders: domain1.com, domain2.com, domain3.com and the certificates in it.
6. Then I ran the renewal script which would use the following command:
/root/.acme.sh/acme.sh --renew -d domain1.com s -d '*.domain1.com' --dns dns_gd
Worked, no error.
7. Then I ran the renewal script and added --force:
/root/.acme.sh/acme.sh --renew --force -d domain1.com s -d '*.domain1.com' --dns dns_gd

and that worked too without error.

So it is working again. But of course I will have to edit the acme.sh script again the next time I update it. Not sure why it puts the _ecc after the domain folder. Don't know what triggers this. That's a new one for me. But at least I solved my errors and got it working again for now.

I emailed the author of acme.sh, but no reply.

**Comment by labiloute** [comment]
I run exactly the same issue.
For unknown reason I've got an error, only a few domains works, other get :
Error, can not get domain token "type":"http-01","url":"https://acme.zerossl.com/v2/DV90/chall/ifa_d7QcYbpjgjPDzJ2R2sxsA","status":"invalid","error":{

**Comment by mrlerch** [comment]
[labiloute], try what I did as outlined above. Maybe it will work for you as well. We still need to get the script author to address the _ecc suffix issue and what causes that and how to go about it without me changing the script. Maybe [Neilpang](https://github.com/Neilpang/Neilpang) can have a look and let us know? Thanks.

**Comment by Neilpang** [comment]
the `_ecc` suffix means it's a ECDSA cert.
don't change any of the code,  don't rely on the path.
use the 'install-cert' command to copy the cert/key to anywhere you want.
https://github.com/acmesh-official/acme.sh?tab=readme-ov-file#3-install-the-cert-to-apachenginx-etc

**Comment by mrlerch** [comment]
Yea, not running Apache or NginX!What's my alternative?Martin 
On Feb 6, 2024, at 7:41 PM, neil ***@***.***> wrote:﻿
the _ecc suffix means it's a ECDSA cert.
don't change any of the code,  don't rely on the path.
use the 'install-cert' command to copy the cert/key to anywhere you want.
https://github.com/acmesh-official/acme.sh?tab=readme-ov-file#3-install-the-cert-to-apachenginx-etc

**Comment by Neilpang** [comment]
![image](https://github.com/acmesh-official/acme.sh/assets/8305679/e8e4598d-bc02-46ce-8a15-319817bc4332)

**Comment by labiloute** [comment]
IMO it was not related to the ecc, because the cert, ecc or not, wasn't generated at all.
I worked around this issue with another approach
