### ISSUE TITLE
About web server and auto renew cert (by default) question .

### ISSUE THREAD

**Issue by carasha** [acmesh-official/acme.sh#4955]
I use CentOS **httpd** as web server .

If i excuted only 2 commands below :

First command :
`acme.sh --issue -d abc.com -w /home/abc`

Second command :
`acme.sh --install-cert -d abc.com --cert-file /etc/httpd/ssl/abc.com/cert.pem --key-file /etc/httpd/ssl/abc.com/key.pem --fullchain-file /etc/httpd/ssl/abc.com/fullchain.pem --reloadcmd "service httpd force-reload"`

then , will these 2 commands auto renew the following 3 files every 60 days without any extra setting ???

/etc/httpd/ssl/abc.com/cert.pem
/etc/httpd/ssl/abc.com/key.pem
/etc/httpd/ssl/abc.com/fullchain.pem

**Comment by Neilpang** [comment]
yes, totally correct.
