### ISSUE TITLE
Linode DNS Pagination Bug "Domain does not exist"

### ISSUE THREAD

**Issue by sabey** [acmesh-official/acme.sh#4956]
Linode DNS will return `Domain does not exist.` if the domain does not exist in the first page of results.

My domain is contained on page 2 of 3 and only the first page is checked.
`curl -H "Authorization: Bearer TOKEN" https://api.linode.com/v4/domains`
```
{
    "data": [],
    "page": 1,
    "pages": 3,
    "results": 245
}
```

Changing the `GET` URL to `https://api.linode.com/v4/domains?page_size=500` resolves _my_ issue but does not resolve the pagination issue.

`dnsapi/dns_linode_v4.sh`
```
_get_root() {
  domain=$1
  i=2
  p=1

  if _rest GET "?page_size=500"; then
```

**Comment by vmmello** [comment]
Another option would be to make the API query return only the desired domain (instead of listing all domains and going through the results):

```bash
_get_root() {
  domain="$1"
  #...
  # line 135 below:
  if _H4="X-Filter: {\"domain:\":\"$domain\"}" _rest GET; then
```

I think this way it fixes the pagination issue.

Can you test?

**Comment by sabey** [comment]
> Another option would be to make the API query return only the desired domain (instead of listing all domains and going through the results):
> 
> ```shell
> _get_root() {
>   domain="$1"
>   #...
>   # line 135 below:
>   if _H4="X-Filter: {\"domain:\":\"$domain\"}" _rest GET; then
> ```
> 
> I think this way it fixes the pagination issue.
> 
> Can you test?

didn't work unfortunately

`response='{"errors": [{"reason": "Cannot filter on domain:", "field": "X-Filter"}]}'`

**Comment by vmmello** [comment]
Ops, sorry. There's a typo in the line I wrote. There's an invalid extra ':' character in the filter.

The correct one is:
```bash
if _H4="X-Filter: {\"domain\":\"$domain\"}" _rest GET; then
```

The reasoning of the above is, whenever you run on command line:
```
curl -s -H 'X-Filter: {"domain":"a-domain-on-linode.com"}' -H "Authorization: Bearer $linode_token" https://api.linode.com/v4/domains
```
it will return just the desired domain.

Can you please try again?

**Comment by sabey** [comment]
> Ops, sorry. There's a typo in the line I wrote. There's an invalid extra ':' character in the filter.
> 
> The correct one is:
> 
> ```shell
> if _H4="X-Filter: {\"domain\":\"$domain\"}" _rest GET; then
> ```
> 
> The reasoning of the above is, whenever you run on command line:
> 
> ```
> curl -s -H 'X-Filter: {"domain":"a-domain-on-linode.com"}' -H "Authorization: Bearer $linode_token" https://api.linode.com/v4/domains
> ```
> 
> it will return just the desired domain.
> 
> Can you please try again?

good catch, although `$domain` does not seem to work as it includes acme `_acme-challenge.domain.tld`

although I hardcoded it to `domain.tld` and it worked

```shell
_get_root() {
  domain=$1
  i=2
  p=1

  _debug domain $domain

  domainfix=$(printf "%s" "$domain" | cut -d . -f $i-100)
  _debug domainfix $domainfix

  if _H4="X-Filter: {\"domain\":\"$domainfix\"}" _rest GET; then
```

**Comment by vmmello** [comment]
Ok.

Though reading the code again, this would work only for third level records. For higher level records, e.g. `4th.3rd.domain.tld` it'd wrongly filter for `3rd.domain.tld` as the hosted domain, what would return an empty response and the `while` loop after it would never match a domain.

For it to work in all cases the `_rest GET` part needs to be moved within the `while` loop, and a few other adjustments to the logic. It's not difficult to implement, though it requires a bit of attention.
