### ISSUE TITLE
Stateless in ZeroSSL does not match expected behavior

### ISSUE THREAD

**Issue by Windyo** [acmesh-official/acme.sh#4957]
Steps to reproduce
------------------
- acme.sh register_account using letsencrypt
- setup webserver to answer the challenge
- it works
- acme.sh register_account zerossl
- edit webserver answer to add new account thumbprint
- errors out with domain key error.

Debug log
-----------------

```
[Mon Jan 22 11:18:15 UTC 2024] Error, can not get domain token "type":"http-01","url":"https://acme.zerossl.com/v2/DV90/chall/hgcjhgchgfcxgfhcgf","status":"invalid","error":{
[Mon Jan 22 11:18:15 UTC 2024] pid
[Mon Jan 22 11:18:15 UTC 2024] No need to restore nginx, skip.
[Mon Jan 22 11:18:15 UTC 2024] _clearupdns
[Mon Jan 22 11:18:15 UTC 2024] dns_entries
[Mon Jan 22 11:18:15 UTC 2024] skip dns.
[Mon Jan 22 11:18:15 UTC 2024] _on_issue_err
[Mon Jan 22 11:18:15 UTC 2024] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Mon Jan 22 11:18:15 UTC 2024] _chk_vlist
[Mon Jan 22 11:18:15 UTC 2024] Diagnosis versions:
openssl:openssl
OpenSSL 3.1.4 24 Oct 2023 (Library: OpenSSL 3.1.4 24 Oct 2023)
```

Requested fix
-----------------
either update wiki (https://github.com/acmesh-official/acme.sh/wiki/Stateless-Mode) or have acme.sh handle both situations in the same way

**Comment by Windyo** [comment]
Exact command run was
`./acme.sh  -d my.domain.se --issue --stateless --cert-file /etc/nginx/certs/my.domain.se/my.domain.se.crt --key-file /etc/nginx/certs/my.domain.se/my.domain.se.key --ca-file /etc/nginx/certs/my.domain.se/my.domain.se.chain.pem --debug 2"`

Exact fixed command was `./acme.sh  -d my.domain.se --issue --stateless --cert-file /etc/nginx/certs/my.domain.se/my.domain.se.crt --key-file /etc/nginx/certs/my.domain.se/my.domain.se.key --ca-file /etc/nginx/certs/my.domain.se/my.domain.se.chain.pem --server letsencrypt --debug 2"`

no other changes apart from having the server answer the thumbprint.

**Comment by Neilpang** [comment]
It's a temp error of zerossl. you can try again later.
