### ISSUE TITLE
ZeroSSL sent 504 errors

### ISSUE THREAD

**Issue by starverdiyev** [acmesh-official/acme.sh#4964]
Hello!

Since yesterday ZeroSSL sent 504 errors:

`<head><title>504 Gateway Time-out</title></head> 
`
Anybody know what happened?

**Comment by TheWiresharkGuy** [comment]
> Hello!
> 
> Since yesterday ZeroSSL sent 504 errors:
> 
> `<head><title>504 Gateway Time-out</title></head> ` Anybody know what happened?

Hi, same problem for me (https://status.zerossl.com/8200003)

**Comment by starverdiyev** [comment]
> https://status.zerossl.com/8200003

No problems on status page:(

**Comment by Neilpang** [comment]
please report the issues to zerossl support.
