### ISSUE TITLE
How to add Organization and OU info to my certificate

### ISSUE THREAD

**Issue by MMMMMoris** [acmesh-official/acme.sh#5002]
Steps to reproduce
------------------
It is no bug, but a question of mine. Perhaps a feature to be realized.
How to add Organization and OU info to my certificate ?
Here is the picture

![image](https://github.com/acmesh-official/acme.sh/assets/63332824/dcd654a9-8fe3-4444-87f3-0330d7bd13fb)

Debug log
-----------------

### No debug log, everything works fine.
Just need some support for adding info such as  Organization and OU info to my certificate.

**Comment by MMMMMoris** [comment]
> Please upgrade to the latest code and try again first. Maybe it's already fixed. `acme.sh --upgrade` If it's still not working, please provide the log with `--debug 2`, otherwise, nobody can help you.

NOT A BUG ISSUE.

**Comment by hebbet** [comment]
with Let's encrypt that is not possible:

https://community.letsencrypt.org/t/organization-o-and-organizational-unit-ou-in-field-issued-to/5236

**Comment by Neilpang** [comment]
ACME protocol can only issue DV cert,   not OV or EV.
