### ISSUE TITLE
PfSense and Acme

### ISSUE THREAD

**Issue by marcoczen** [acmesh-official/acme.sh#5017]
Hi.

Acme has been working great on my home servers - Ubuntu and OpenSuse machines.
These servers are behind a PfSense firewall. 

Is there a acme script that can run in PfSense with DNS validation / ZeroSSL

Thanks.

**Comment by marcoczen** [comment]
Hi. Nothing is wrong with acme on my servers. I just want to use it in a pfsense fwall. Pls consider.

**Comment by Neilpang** [comment]
why not try it first?
