### ISSUE TITLE
Synology NAS deploy documentation confusion

### ISSUE THREAD

**Issue by cirrusflyer** [acmesh-official/acme.sh#5019]
Listed here:

https://github.com/acmesh-official/acme.sh/wiki/Synology-NAS-Guide

These instructions state:

"(Recommend) Deploy with auto created temp admin user" and using "export SYNO_USE_TEMP_ADMIN=1"

This file is used with latest version which doesn't include the code:

https://github.com/acmesh-official/acme.sh/blob/master/deploy/synology_dsm.sh

This file seems to include the code necessary for what's described in guide above:

https://git.jasuit.com/jh163888/acme.sh/src/commit/c7f6f20c9d4ae05a5ce366d8f3f62cd3eb1b1710/deploy/synology_dsm.sh

**Comment by cirrusflyer** [comment]
I have upgraded to latest version.  Running with debug 2 doesn't apply to what I'm reporting here.

**Comment by stkevintan** [comment]
The feature which documentation describes does exist: https://github.com/acmesh-official/acme.sh/pull/4706 
However, it still lies in the `dev` branch and isn't merged to `master` yet:
https://github.com/acmesh-official/acme.sh/compare/master...dev

Hi, @cirrusflyer  Do we have any plan to update the master with dev updates?

**Comment by cirrusflyer** [comment]
Thanks.  That's too bad.  I was looking forward to testing the temp admin feature.

**Comment by Neilpang** [comment]
merged

**Comment by cirrusflyer** [comment]
Thanks!

What are the "built-in tools" and where do I get them?

(Recommend) Deploy with auto created temp admin user
If you installed acme.sh in DSM, we recommend you to try automatic temp user auth method to deploy (DSM should already have required built-in tools, we will let you know if not):

**Comment by cmatte** [comment]
Hey @cirrusflyer I faced the same blocker for the tools error, you are also probably running acme.sh in a docker/VM container, you need to scrap all that, install acme.sh in a permanent folder of your choice keeping the --nocron option as DSM does not seem to have crontab, and then run renewals and deployments regularly through "Task Scheduler".

**Comment by elmimmo** [comment]
> and you then run renewals and deployments regularly through "Task Scheduler".

If I am not mistaken, `synouser` and `synogroup`, which [acme.sh seems to depend on to create temp admin user](https://github.com/acmesh-official/acme.sh/blob/f981c782bb38015f4778913e9c3db26b57dde4e8/deploy/synology_dsm.sh#L74C63-L74C78), must be executed by `root`. Therefore, if acme.sh is ran without `sudo`, it will complain about `Missing required tools to creat temp admin user`, even though it actually means that the user has no permissions to execute those.

I guess that means that one cannot run renewals and deployments through "Task Scheduler" unless the task is assigned to `root`, which I am not totally confortable with. I had rather it be a dedicated user in the `administrators` group, with acme.sh and its config files residing in that user’s Home folder.
