### ISSUE TITLE
Typo in wiki

### ISSUE THREAD

**Issue by filol** [acmesh-official/acme.sh#5027]
Here : https://github.com/acmesh-official/acme.sh/wiki/Synology-NAS-Guide#deploy-with-existing-admin-user
You talk about `SYNO_DeviceID` but the real name is `SYNO_Device_ID`

![image](https://github.com/acmesh-official/acme.sh/assets/9217516/c80d6e70-61e8-4fc0-98b1-129693393154)

**Comment by scruel** [comment]
Wiki contains some pre-released things, you shall close this issue and wait the update.

**Comment by danbernier** [comment]
@filol is there any reason not to edit the wiki yourself? I seem to have rights to it.

**Comment by scruel** [comment]
> @filol is there any reason not to edit the wiki yourself? I seem to have rights to it.

Can you read the wiki carefully before let yourself or encourage others doing so??

**Comment by danbernier** [comment]
> Could you read the wiki carefully before let yourself or encourage others doing so??

So it sounds like there *is* a reason not to edit the wiki? I scanned the wiki but didn't see anything in there that looked like it might address this - for instance, it's not in the [Code of Conduct](https://github.com/acmesh-official/acme.sh/wiki/Code-of-conduct), which addresses style guidelines.

**Comment by Neilpang** [comment]
The  wiki is open to everyone to edit for now.

(Sometimes it's damaged by someone evil, so I could disable editing for some time.  this didn't happen for months)

**Comment by scruel** [comment]
> So it sounds like there *is* a reason not to edit the wiki?

Yeap, search "warning"

**Comment by danbernier** [comment]
So it sounds like @filol could make that wiki edit on their own. Thanks for that info & context, @Neilpang.
