### ISSUE TITLE
Gcore DNS API not working, "$" character is removed from the account.conf

### ISSUE THREAD

**Issue by kristoftorok** [acmesh-official/acme.sh#5067]
Cannot issue certificates with Gcore DNS because the token is always invalid.  
When exporting the variable, there is a "$" character that for some reason disappears from account.conf after the issue command:

Exporting the token: 

![image](https://github.com/acmesh-official/acme.sh/assets/55440418/2b2e5a37-bdba-454a-bacf-6623b2021657)

After `acme.sh  --issue ...` the contents of the account.conf:

![image](https://github.com/acmesh-official/acme.sh/assets/55440418/02817f7c-4af9-4b65-aa96-a060e9899b45)

I have tried manually editing account.conf to add the '$' character to the variable, but it is still removed after running the issue command.

Steps to reproduce
------------------
Try to issue any certificate with the Gcore DNS API

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```
[Mon Mar 25 20:40:27 UTC 2024] _CURL='curl --silent --dump-header /home/user/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.fjHO8fQGwC  -g '
[Mon Mar 25 20:40:27 UTC 2024] ret='0'
[Mon Mar 25 20:40:27 UTC 2024] response='{"error":"invalid or expired permanent token"}'
[Mon Mar 25 20:40:27 UTC 2024] h='cloud'
[Mon Mar 25 20:40:27 UTC 2024] zones/cloud
[Mon Mar 25 20:40:27 UTC 2024] GET

**Comment by libDarkstreet** [comment]
So I tried several things.

First I tried to escape the "$" character: `123\$abc`, it doesn't work,
Then I encoded the token in base64 and decoded it in use, it doesn't work either.

The problem must be here somewhere because the G-core interface says the token was never used.

**Comment by libDarkstreet** [comment]
So during export, the character escaping worked and I was able to generate the certificate. The "$" character is also in account.conf now.

![image](https://github.com/acmesh-official/acme.sh/assets/55440418/88d0f00b-810d-4e60-a9b9-b5f07a3ec6d3)


But it only works the first time, after the second issue command, the same problem occurs as before. The "$" character will be deleted from account.conf and the token will be invalid.

**Comment by moechs** [comment]
+1

**Comment by danryd-ungapped** [comment]
+1

**Comment by Neilpang** [comment]
try again with `dev`

```
acme.sh  --upgrade -b dev
```
