### ISSUE TITLE
GoDaddy Instructions Can Be Updated

### ISSUE THREAD

**Issue by johnnyshankman** [acmesh-official/acme.sh#5071]
On Let's Encrypt it claims this is hard to do: https://letsencrypt.org/docs/godaddy/

But I've made this work in 4 steps https://gist.github.com/johnnyshankman/e838792e28b2a51d9e34d65726f56431

We should update the site/readme.

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh/wiki/dnsapi#dns_gd
