### ISSUE TITLE
If a domain name is on two servers, how should the variable be written?

### ISSUE THREAD

**Issue by 692568516** [acmesh-official/acme.sh#5074]
If a domain name is on two servers, how should the variable be written? If the variable is executed directly, the test will overwrite the first one.
export DEPLOY_SSH_USER=
export DEPLOY_SSH_SERVER=

acme.sh --deploy -d aa.com --deploy-hook ssh

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh/wiki/deployhooks

```
https://github.com/acmesh-official/acme.sh/wiki/deployhooks
```

**Comment by 692568516** [comment]
Thank you, but in this case, DEPLOY_SSH_KEYFILE, DEPLOY_SSH_FULLCHAIN, DEPLOY_SSH_REMOTE_CMD, etc. must be the same. If these variables are also different and the same domain name certificate is used, is this situation currently supported?
