### ISSUE TITLE
revoke old certificates

### ISSUE THREAD

**Issue by PaweltK** [acmesh-official/acme.sh#5076]
Hello,

Can acme.sh save old certificates?
I use zerossl and I would like to revoke old certificates like this:
https://help.zerossl.com/hc/en-us/articles/900005244486-Revoking-Certificates-Issued-via-ACME

In the zerossl dashboard I have:
Issued [View All (14)
**Expired [View All (129)**
If I revoke old certificates, should the number be reduced?

**Comment by Neilpang** [comment]
>> If I revoke old certificates, should the number be reduced?

NO.
