### ISSUE TITLE
[contribution] Convert LE account data from certbot to acme.sh

### ISSUE THREAD

**Issue by maddes-b** [acmesh-official/acme.sh#5080]
Just out of curiosity I wrote a script to convert the LE account data from certbot to acme.sh:
https://github.com/maddes-b/linux-stuff/tree/main/acme.sh

Maybe this can be added to the wiki for those who are interested.

**Comment by Neilpang** [comment]
you can edit the wiki:
https://github.com/acmesh-official/acme.sh/wiki

**Comment by maddes-b** [comment]
Updated wiki.

**Comment by maddes-b** [comment]
@Neilpang https://github.com/acmesh-official/acme.sh/wiki/How-to-install
