### ISSUE TITLE
Received a lot of unfriendly requests when cert success

### ISSUE THREAD

**Issue by BLCheung** [acmesh-official/acme.sh#5093]
In an instant, a large number of unfriendly requests were received. What the hack this project doing in behind?

cert success
![WechatIMG874](https://pic.superbed.cc/item/661ed112f989f2fb97f0f946.png)

few second receive a lot request ! ! ! they are all looking for my domain (same domain)
![WechatIMG875](https://pic.superbed.cc/item/661ed112f989f2fb97f0f94f.png)
![WechatIMG876](https://pic.superbed.cc/item/661ed112f989f2fb97f0f956.png)

What are they doing?
![WechatIMG878](https://pic.superbed.cc/item/661ed112f989f2fb97f0f95d.png)
![WechatIMG878](https://pic.superbed.cc/item/661ed112f989f2fb97f0f964.png)

careful everybody

**Comment by Neilpang** [comment]
没点常识的别来随便发言.  
代码都在那, 你怀疑啥自己看看不就知道了.
没常识.
