### ISSUE TITLE
请问如何生成 windows iis 用的pfx文件？

### ISSUE THREAD

**Issue by zhans1099** [acmesh-official/acme.sh#5144]
我用了先生成nginx用的pem和用key然后用openssl将pem和key生成 pfx但是导入的时候一直提示密码
我用openssl导出时输入的密码 或者设置为不需要密码均不可
请问应该如何操作？

**Comment by webprofusion-chrisc** [comment]
You can set a password then use that when you import the PFX into the machine certificate store, or you could just use https://certifytheweb.com (which I develop) on Windows as it has native PFX and IIS support, there are also other command line based clients on Windows if you prefer. https://acmeclients.com/

**Comment by Neilpang** [comment]
```
acme.sh  --topkcs   -d xxxx ......
```
