### ISSUE TITLE
During secondary validation: no valid A records found

### ISSUE THREAD

**Issue by malemodel** [acmesh-official/acme.sh#5160]
hi all...

i couldn't find anything online with clear answer for the issue below... 

it looks like domains with expired certificates keep sending back this below when an attempt is made to call acme with --renew.  it's the second time it happens in about a month for 2 different domains that have expired certificates. renewing domains that are still within the expiration date is not an issue... 

`mydomain.com :Verify error:During secondary validation: no valid A records found for mydomain.com; no valid AAAA records found for mydomain.com`

dig clearly returns the A record which hasn't changed in years...

i would like to know how to resolve the "secondary validation" issue...

thanks... 

Steps to reproduce
------------------

acme.sh --debug --renew -d mydomain.com

Debug log
----------------

Wed May 29 17:18:33 UTC 2024] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/357072665122/_peAsQ'
[Wed May 29 17:18:33 UTC 2024] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L '
[Wed May 29 17:18:33 UTC 2024] _ret='0'
[Wed May 29 17:18:33 UTC 2024] code='200'
[Wed May 29 17:18:33 UTC 2024] mydomain.com:Verify error:During secondary validation: no valid A records found for mydomain.com; no valid AAAA records found for mydomain.com
[Wed May 29 17:18:33 UTC 2024] Debug: get token url.
-

**Comment by malemodel** [comment]
in addition...  i see the "challenge" files and their contents written under .well-known/acme-challenge/...  so that part works. it's not that those are missing. currently have 5 - one for each attempt to renew the certificate.

**Comment by malemodel** [comment]
well?! any ideas?

**Comment by malemodel** [comment]
thanks to webprofusion-chrisc the issue was resolved. temporarily. 

the main issue still remains.

webprofusion-chrisc explained replying to my post in discussions " Let's Encrypt recently started checking http challenge responses from more countries (mainly europe and singapore I think)". that sounds amazing if your domain is supposed to be available in those parts of the world. but if it is meant to be restricted to, let's say, the us, the whole automation for certificate renewal fails and eventually the site that needs it's certificate renewed becomes inaccessible.

a suggestion: when renewing a certificate adding the option of --no-geo-check (or similar) to avoid breaking automated certificate updates for domains that are supposed to be available to only certain parts of the world.

**Comment by Neilpang** [comment]
if your domain has no website enabled,  please don't use webroot mode,  use the dns mode instead.

**Comment by malemodel** [comment]
> if your domain has no website enabled, please don't use webroot mode, use the dns mode instead.

the domains do have websites. which are not meant to be accessible from outside the us. webroot is much easier to automate than dns specially when those are promotional site that don't last more than a few months. we have many clients and sites/domains come and go with an automated issuance/renewal in place. now it's all broken cause "Let's Encrypt recently started checking http challenge responses from more countries (mainly europe and singapore I think)"

**Comment by webprofusion-chrisc** [comment]
If you require geoblocking but still want to use http/webroot validation It's best to use a web application firewall (a content aware firewall that can interpret and filter http traffic) and allow http `/.well-known/acme-challenge/` requests - geographic filtering on IP is no longer sufficient and this issue will eventually affect all ACME CAs, not just Let's Encrypt.
