### ISSUE TITLE
Feature: Please allow redefining github api URL for upgrades when behind proxy

### ISSUE THREAD

**Issue by ILikePhysics** [acmesh-official/acme.sh#5170]
I am currently running acme.sh on VMs that cannot access the internet. For install packages and installation file, they need to go through a Nexus repository.

For auto-upgrade to work, I would need to be able to redefine the github api url using a env variable in order to go through my nexus proxy server.

For instance,

```
_hash_url="https://api.github.com/repos/acmesh-official/$PROJECT_NAME/git/refs/$_hash_path"
```

Could be changed to:
```
ACME_SOURCE_URL=https://api.github.com/repos/acmesh-official
_hash_url="$ACME_SOURCE_URL/$PROJECT_NAME/git/refs/$_hash_path"
```

I would then be able to redefine this env variable as such:
```
ACME_SOURCE_URL=https://nexus.internal/repository/acme.sh
```
My nexus server repository would be configured as follow:
```
https://nexus.internal/repository/acme.sh -> https://api.github.com/repos/acmesh-official
```

**Comment by Neilpang** [comment]
I just added `PROJECT_API` for you.

please upgrade to the latest dev branch code and try again.

**Comment by ILikePhysics** [comment]
Thanks, will try it out whenever I have a chance and let you know!

**Comment by ILikePhysics** [comment]
I have tried to work with the `PROJECT_API` env variable but it turned out to be very difficult to define `PROJECT_API` while keeping the `$PROJECT_NAME` and `$_hash_path` variables intact in it, so it can be used by your script as is.

I have tried many combination of syntax when adding the export to either `/etc/environment` or `/etc/profile`, but regardless of what I do, the $ is escaped in env variable and the acme.sh scripts does not replace it with the values.

For instance,  

In `/etc/profile`
```
export PROJECT_API='https://myrepo.local/repository/raw_github_usercontent/repos/acmesh-official/$PROJECT_NAME/git/refs/$_hash_path'
```
```
~# export
[...]
PROJECT_API="https://myrepo.local/repository/raw_github_usercontent/repos/acmesh-official/\$PROJECT_NAME/git/refs/\$_hash_path"
[...]

~# acme.sh --upgrade --debug 2
[...]
[Mon Jun 24 12:29:45 UTC 2024] url='https://myrepo.local/repository/raw_github_usercontent/repos/acmesh-official/$PROJECT_NAME/git/refs/$_hash_path/acme.sh/git/refs/heads/master'
[...]
```
For some reason, the variables are appended at the end instead of replacing the actual variables.

I am manually trying to set the env variable in /etc/profile because my utlimate goal is to define it through an Ansible script.

If that is not possible, I think just being able to redefine `api.github.com` with PROJECT_API would be easier, instead of the whole URL (and its variables).

**Comment by ILikePhysics** [comment]
Something like this would be perfect:

```shell
_getRepoHash() {
  _hash_path=$1
  shift
  _github_api=${GITHUB_API:-https://api.github.com}
  _hash_url="${PROJECT_API:-$_github_api/repos/acmesh-official}/$PROJECT_NAME/git/refs/$_hash_path"
  _get $_hash_url | tr -d "\r\n" | tr '{},' '\n\n\n' | grep '"sha":' | cut -d '"' -f 4
}
```

PROJECT_API could stay to support other use cases.

**Comment by ILikePhysics** [comment]
@Neilpang Thanks, that is exactly what I need.
