### ISSUE TITLE
Unable to find certificate: "" and  is not set.

### ISSUE THREAD

**Issue by NeckBozia** [acmesh-official/acme.sh#5179]
Steps to reproduce
------------------
docker中运行acme，SYNO_Certificate参数设置为”“，定时运行脚本
```
bash /volume1/docker/Acme/cert-up-docker.sh >>/volume1/docker/Acme/log.txt 2>&1
```
更新证书时报错 Unable to find certificate: "" and  is not set.
此报错可稳定复现且未作任何配置改动

Debug log
-----------------
[Tue Jun 18 11:52:32 UTC 2024] Your cert is in: /acme.sh/aaa.wang_ecc/aaa.wang.cer
[Tue Jun 18 11:52:32 UTC 2024] Your cert key is in: /acme.sh/aaa.wang_ecc/aaa.wang.key
[Tue Jun 18 11:52:32 UTC 2024] The intermediate CA cert is in: /acme.sh/aaa.wang_ecc/ca.cer
[Tue Jun 18 11:52:32 UTC 2024] And the full chain certs is there: /acme.sh/aaa.wang_ecc/fullchain.cer
[Tue Jun 18 11:52:32 UTC 2024] The domain 'aaa.wang' seems to have a ECC cert already, lets use ecc cert.
[Tue Jun 18 11:52:33 UTC 2024] Logging into localhost:5000...
[Tue Jun 18 11:52:33 UTC 2024] Getting certificates in Synology DSM...
[Tue Jun 18 11:52:34 UTC 2024] Unable to find certificate: "" and  is not set.
[Tue Jun 18 11:52:34 UTC 2024] Error deploy for domain:aaa.wang
[Tue Jun 18 11:52:34 UTC 2024] Deploy error.

**Comment by sloganlau** [comment]
I have the same issue with the latest image version(20240430)
If set SYNO_Create=my domain, cer can be deployed with a new one instead of renew.
加了这个变量后能上传，但是会新建一个，而不是替换原来的

**Comment by sloganlau** [comment]
> I have the same issue with the latest image version(20240430) If set SYNO_Create=my domain, cer can be deployed with a new one instead of renew. 加了这个变量后能上传，但是会新建一个，而不是替换原来的

change the default cer's desc from blank to ""

**Comment by zzzdy110** [comment]
解决了吗 我也是这样 一模一样

**Comment by sloganlau** [comment]
> 解决了吗 我也是这样 一模一样

https://post.smzdm.com/p/akl2glrk/  添加描述""

**Comment by postal9120** [comment]
export SYNO_CERTIFICATE=""
- to replace a specific cert by its **description**
试试双引号里填群晖证书设置页的描述内容，比如群晖里证书描述是aaa.com，就在SSH里执行一次
export SYNO_CERTIFICATE="aaa.com"，然后再运行部署看看能否成功。
![dsm](https://github.com/user-attachments/assets/2cc743c3-36fa-48f2-851c-0afc236e5d8c)

**Comment by Brian099** [comment]
me too, dsm7.2.1, seems api response nothing when check cer desc

**Comment by NeckBozia** [comment]
Solved according to https://post.smzdm.com/p/akl2glrk/ 添加描述""

**Comment by Brian099** [comment]
tested with  "" and a name

**Comment by Brian099** [comment]
if set create 1, it will create a new cert with empty desc, if no set, it will said like above, found no match cert

**Comment by Brian099** [comment]
solved, thanks.

update more than one domain for Synology:

# 群晖登陆http端口
port="xxxx"
# 要更新的域名列表
domains=("域名1" "域名2")

# acme路径
ACME_local="path/to/acme"

# DNS提供商 dns_dp,dns_ali
DNS_server="dns_dp"

# DNSpod 信息
DP_Id="xxx"
DP_Key="xxx"

# Ali DNS信息
Ali_Key="xxx"
Ali_Secret="xxx"

#####################
# 以下为程序代码，不懂勿动 #
#####################

if [ "$DNS_server" == "dns_dp" ]; then
    export DP_Id="${DP_Id}"
    export DP_Key="${DP_Key}"
elif [ "$DNS_server" == "dns_ali" ]; then
    export Ali_Key="${Ali_Key}"
    export Ali_Secret="${Ali_Secret}"
fi

# 生成随机邮箱
generate_random_email() {
    local random_str=$(head /dev/urandom | tr -dc a-z0-9 | head -c 8)
    echo "${random_str}@163.com"
}
email=$(generate_random_email)

# 切换目录
cd "${ACME_local}"

# 注册CA
if [ ! -d "./ca" ]; then
    ./acme.sh --register-account -m "${email}" --server zerossl --home .
fi

# 循环处理每个域名
for domain in "${domains[@]}"; do
    echo "正在处理域名: ${domain}"
	echo "证书申请中..."
	
    # 删除旧的证书文件
    if [ -d "${domain}" ]; then
        echo "检测到旧目录 ${domain}，正在删除..."
        rm -rf "${domain}"
        echo "旧目录已删除"
    fi

    # 创建独立的目录
    mkdir -p "${domain}"
	cp -rf ca "${domain}"
	
	echo "证书申请中..."
    # 申请证书，指定独立的 home 目录
    ./acme.sh --issue --dns ${DNS_server} -d "${domain}" --home "${domain}"
	echo "证书申请成功！"
	
	# 写入登陆信息
	cat <<EOF > "./${domain}/account.conf"
	SYNO_USE_TEMP_ADMIN=1
	SYNO_CREATE=1
	SYNO_PORT=${port}
	SYNO_CERTIFICATE="${domain}"
	EOF
	echo "登陆信息已保存！"
	
	# 重命名证书目录名
    mv "${domain}/${domain}_ecc" "${domain}/${domain}"
	
    echo "已为 ${domain} 整理好所需文件！"
	echo "正在为 ${domain} 更新证书到系统..."
    # 更新证书，指定独立的 home 目录
    ./acme.sh --deploy --home "${domain}" --deploy-hook synology_dsm -d "${domain}"
    echo "域名 ${domain} 的证书已更新完成"
done
