### ISSUE TITLE
Cannot issue on godaddy for *.subdomain.domain

### ISSUE THREAD

**Issue by Tom-CDA** [acmesh-official/acme.sh#5181]
Hi,

I've been using acme.sh for a long while now, and it always worked. My certificate setup is for:

- mydomain.com
- *.mydomain.com
- *.mysubdomain.mydomain.com

I'm using the dns api for godaddy (which seems to still work for me?). For the first two domains, it succeeds in adding a TXT, but for the subdomain it fails.

[acme.sh.log](https://github.com/user-attachments/files/15910690/acme.sh.log)

Relevant section:

[Thu Jun 20 09:31:11 CEST 2024] Adding txt value: xPk8fcrkRTPmoZwHGE7adH64UyUXWCnvDthVthW5nF8 for domain:  _acme-challenge.mysubdomain.mydomain.com
[Thu Jun 20 09:31:11 CEST 2024] First detect the root zone
[Thu Jun 20 09:31:11 CEST 2024] domains/mysubdomain.mydomain.com
[Thu Jun 20 09:31:11 CEST 2024] GET
[Thu Jun 20 09:31:11 CEST 2024] url='https://api.godaddy.com/v1/domains/mysubdomain.mydomain.com'
[Thu Jun 20 09:31:11 CEST 2024] timeout=
[Thu Jun 20 09:31:11 CEST 2024] Http already initialized.
[Thu Jun 20 09:31:11 CEST 2024] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.3AGDcWUoWh  -g '
[Thu Jun 20 09:31:11 CEST 2024] ret='0'
[Thu Jun 20 09:31:11 CEST 2024] response='{"code":"ACCESS_DENIED","message":"Authenticated user is not allowed access"}'
[Thu Jun 20 09:31:11 CEST 2024] _sub_domain='_acme-challenge'
[Thu Jun 20 09:31:11 CEST 2024] _domain='mysubdomain.mydomain.com'
[Thu Jun 20 09:31:11 CEST 2024] Getting existing records
[Thu Jun 20 09:31:11 CEST 2024] domains/mysubdomain.mydomain.com/records/TXT/_acme-challenge
[Thu Jun 20 09:31:11 CEST 2024] GET
[Thu Jun 20 09:31:11 CEST 2024] url='https://api.godaddy.com/v1/domains/mysubdomain.mydomain.com/records/TXT/_acme-challenge'
[Thu Jun 20 09:31:11 CEST 2024] timeout=
[Thu Jun 20 09:31:11 CEST 2024] Http already initialized.
[Thu Jun 20 09:31:11 CEST 2024] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.3AGDcWUoWh  -g '
[Thu Jun 20 09:31:11 CEST 2024] ret='0'
[Thu Jun 20 09:31:11 CEST 2024] response='{"code":"UNKNOWN_DOMAIN","message":"The given domain is not registered, or does not have a zone file"}'

But since this has always worked, I don't know what the issue is.

![q0OBhYFU7L](https://github.com/acmesh-official/acme.sh/assets/111568954/9e1d36ba-a22e-4fb7-b7d3-b9e878614fac)

My godaddy configuration for my domain and subdomain.

Can you shed a light on what could be happening?
Best regards!

**Comment by wuxue107** [comment]
I encountered the same problem

**Comment by webprofusion-chrisc** [comment]
It's not a bug. GoDaddy changed their API so only customers with 10+ domains can use it, speak to their support.

**Comment by webprofusion-chrisc** [comment]
@Tom-CDA my first guess would be cached validation for the domain variation that's working (cached on the CA side, and it will expire), I've not heard of the API working only for the primary domain _acme-challenge record, I guess it's possible but I doubt it.

**Comment by FlexServ** [comment]
Having similar issues. Weird thing is tho ...when using the Let's Encrypt staging ACME v2 server it's working just fine.

**Comment by webprofusion-chrisc** [comment]
@FlexServ the question there would be are you doing any TXT updates at all when it works? Most likely your previous validations against staging are cached by LE. I believe they cache successful validations for 30 days, so it's _possible_ for you to fire off a new order and complete it without needing to complete any domain validations. Until they expire.

**Comment by webprofusion-chrisc** [comment]
@Tom-CDA that's interesting! It does sounds like they will allow it to update `_acme-challenge` but not `_acme-challenge.www` etc, if that's the case you may be able to at least get a wildcard. Unfortunately for me I need the option to list zones via the API, which probably won't work. They really need to update their documentation.
