### ISSUE TITLE
socat error

### ISSUE THREAD

**Issue by RO55INGER** [acmesh-official/acme.sh#5189]
I am trying to use acme.sh in standalone mode on my Ubuntu 22.04 box but I do get connection refused errors when letsencrypt tries to reach the server on port 80. The port ist open and nothing else is running on that port.

From what I found in the debug logs I think this is an issue with socat. Acme.sh calls socat with the following command: socat -4 TCP-LISTEN:80,crlf,reuseaddr,fork

This does not seem to work, socat does not listen on port 80 and thus the the validation fails. When I try the socat command directly from the prompt I get this error: socat[440044] E exactly 2 addresses required (there are 1); use option "-h" for help

Is this some kind of issue with socat? I am on version 1.7.4.1. Any help is greatly appreciated!

Thanks,
RO55

**Comment by ILikePhysics** [comment]
Do you run acme.sh as root or non-root?
If you installed with a non-root user, you have to give permission to your acme user to open a port in the lower port range (1024 and below).

`sudo setcap 'cap_net_bind_service=+ep' /usr/bin/socat`

**Comment by RO55INGER** [comment]
> Do you run acme.sh as root or non-root? If you installed with a non-root user, you have to give permission to socat to open a port in the lower port range (1023 and below).
> 
> `sudo setcap 'cap_net_bind_service=+ep' /usr/bin/socat`

Yes, that did the trick! Thank you so much!

**Comment by alexeyp0708** [comment]
I had the same problem. I spent a lot of time figuring this out.   
Solution from @[ILikePhysics](https://github.com/ILikePhysics) is perfect.  
I would like this to be mentioned in the documentation on the initial page of README.md
