### ISSUE TITLE
Deploy synology_dsm.sh - Error 109 (was succeed 2 months ago)

### ISSUE THREAD

**Issue by LordDarkneo** [acmesh-official/acme.sh#5191]
Hello all! 

I just realized that my certificate has not been newed few weeks ago. After checking the logs, I saw a deployment issue:

> Getting certificates in Synology DSM...
> POST
> _post_url='http://192.168.1.100:5000/webapi/entry.cgi'
> _CURL='curl --silent --dump-header /acme.sh/http.header  -L  -g '
> _ret='0'
> escaped_certificate='Certificat LE pour domaine OVH'
> Failed to fetch certificate info with error: 119, please try again or contact Synology to learn more.
> Error deploy for domain:mydomain.ovh
> Deploy error.
> Return code: 1
> Error renew mydomain.ovh.
> _error_level='1'
> _set_level='2'
> The NOTIFY_HOOK is empty, just return.
> ===End cron===

I checked the synology_dsm.sh file, and the issue seems to be here:

```
  _info "Getting certificates in Synology DSM..."
  response=$(_post "api=SYNO.Core.Certificate.CRT&method=list&version=1&_sid=$sid" "$_base_url/webapi/entry.cgi")
  _debug3 response "$response"
  escaped_certificate="$(printf "%s" "$SYNO_CERTIFICATE" | sed 's/\([].*^$[]\)/\\\1/g;s/"/\\\\"/g')"
  _debug escaped_certificate "$escaped_certificate"
  id=$(echo "$response" | sed -n "s/.*\"desc\":\"$escaped_certificate\",\"id\":\"\([^\"]*\).*/\1/p")
  _debug2 id "$id"

  error_code=$(echo "$response" | grep '"error":' | grep -o '"code":[0-9]*' | grep -o '[0-9]*')
  _debug2 error_code "$error_code"
  if [ -n "$error_code" ]; then
    if [ "$error_code" -eq 105 ]; then
      _err "Current user is not administrator and does not have sufficient permission for deploying."
    else
      _err "Failed to fetch certificate info with error: $error_code, please try again or contact Synology to learn more."
    fi
    _temp_admin_cleanup "$SYNO_USE_TEMP_ADMIN" "$SYNO_USERNAME"
    return 1
  fi
```

I saw there has been a modification on this file 2 month ago... What's surprising is that I normally configured the acme not to be updated automatically.... So I do not understand why I received the updates. 

Thanks in advance for your help (I am a real beginner in Docker... So if some can tell me how to download the certificates so I'll update them manually with the DSM interface).

FYI: the Acme is running on a docker (neilpang one) on a Synology. Previous logs in mid april were:

> Getting certificates in Synology DSM
> POST
> _post_url='http://192.168.1.100:5000/webapi/entry.cgi'
> _CURL='curl --silent --dump-header /acme.sh/http.header  -L  -g '
> _ret='0'
> escaped_certificate='Certificat LE pour domaine OVH'
> Generate form POST request
> Upload certificate to the Synology DSM
> POST
> _post_url='http://192.168.1.100:5000/webapi/entry.cgi?api=SYNO.Core.Certificate&method=import&version=1&SynoToken=xxxxx
> _CURL='curl --silent --dump-header /acme.sh/http.header  -L  -g '
> _ret='0'
> Restarting HTTP services succeeded
> GET
> url='http://192.168.1.100:5000/webapi/auth.cgi?api=SYNO.API.Auth&version=6&method=logout&_sid=xxxxx
> timeout=
> _CURL='curl --silent --dump-header /acme.sh/http.header  -L  -g '
> ret='0'
> Success
> Return code: 0
> _error_level='2'
> _set_level='2'
> The NOTIFY_HOOK is empty, just return.
> ===End cron===

**Comment by scruel** [comment]
According to the official doc of Login Web API, 119 means "Invalid session", don't know how it can happen, and since either you can't reproduce this issue, we won't be able to identify the reason to help.

**Comment by nillebor** [comment]
You need 2FA for the Synology-ACME-Admin-User?
Try once without 2FA or delete the device ID and re-enter the TOP.
Have you installed ACME natively on Diskstation or in Docker?

I think it's a 2FA problem.

**Comment by LordDarkneo** [comment]
Well 2FA is needed when you activate it on your Synology, I dont think it relates to the admin account.
But as said it was working previously with the exact same configuration, and worked when I only published the certificate.. So seem to be a impossible issue to reproduce... (I forgot to close this case... Sorry for that)

**Comment by nillebor** [comment]
Don't just give up.
Did you acme.sh natively installed or in docker?

Required for the import acme.sh a user account with administrator rights, not without the admin or adminuser. It is best to test the import without 2FA. There should be no $ sign in password. If this works, you can test the 2FA again. The 2FA has often caused problems in the near past.

Giving up and not using acme is not an option ;)

**Comment by LordDarkneo** [comment]
> Don't just give up. Did you acme.sh natively installed or in docker?
> 
> Required for the import acme.sh a user account with administrator rights, not without the admin or adminuser. It is best to test the import without 2FA. There should be no $ sign in password. If this works, you can test the 2FA again. The 2FA has often caused problems in the near past.
> 
> Giving up and not using acme is not an option ;)

Yes the acme is on docker so no rights problem.
And point is only publication failed on the renewal. So I sshed on the docker and used the command to only publish the certificate (as they were already downloaded on the docker), and it worked perfectly without any modification on the deploy sh file.

So I do not give up using acme, I just give up investigating this issue 😅

**Comment by nillebor** [comment]
Do you use acme as a deamon? With this, the update works automatically, without an extra task or command. I have already set up acme on the DS for many users, and they have been running for over 2 years without any problems. There were only problems with 2FA.

How did you install acme ssh/task or compose? How was the order?

Install via Docker/Container Manager (task not needet by deamon - its wrong)
https://www.christosgeo.com/2022/02/03/renew-lets-encrypt-certificates-on-synology-using-acme-sh/

**Comment by spendist** [comment]
## try my script. here: 
[https://github.com/acmesh-official/acme.sh/issues/5254](url)
