### ISSUE TITLE
Cron job for certificate renewal

### ISSUE THREAD

**Issue by Zeni241** [acmesh-official/acme.sh#5198]
I have successfully installed SAN as well as wildcard SSL certificate for my domain as root user following this site (https://github.com/acmesh-official/acme.sh/blob/master/README.md). 
The problem is that every time I have to manually renew the certificates. 
I have created a cron job using command crontab –e from root folder as a root user. 
My entry is as bellow: 
`0 0 * * */root/.acme.sh/ acme.sh --renew -d mydomain.con --force && /root/ systemctl restart nginx &&  echo "SSL certigicate renewed at $(date )" >> /root/ sslrenewalhistory.txt;`
But this is not working. I don’t know where I am wrong.

**Comment by Neilpang** [comment]
please use the default cronjob:

```
acme.sh  --installcronjob
```
