### ISSUE TITLE
Only RSA or EC key is supported

### ISSUE THREAD

**Issue by CO2-mc** [acmesh-official/acme.sh#5201]
How can I solve this problem?

[Mon Jul  8 13:35:53 CST 2024] Lets find script dir.
[Mon Jul  8 13:35:53 CST 2024] _SCRIPT_='/root/.acme.sh/acme.sh'
[Mon Jul  8 13:35:53 CST 2024] _script='/root/.acme.sh/acme.sh'
[Mon Jul  8 13:35:53 CST 2024] _script_home='/root/.acme.sh'
[Mon Jul  8 13:35:53 CST 2024] Using default home:/root/.acme.sh
[Mon Jul  8 13:35:53 CST 2024] Using config home:/root/.acme.sh
[Mon Jul  8 13:35:53 CST 2024] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.8
[Mon Jul  8 13:35:53 CST 2024] Running cmd: issue
[Mon Jul  8 13:35:53 CST 2024] _main_domain='example.com'
[Mon Jul  8 13:35:53 CST 2024] _alt_domains='no'
[Mon Jul  8 13:35:53 CST 2024] Using config home:/root/.acme.sh
[Mon Jul  8 13:35:53 CST 2024] default_acme_server='https://acme-v02.api.letsencrypt.org/directory'
[Mon Jul  8 13:35:53 CST 2024] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mon Jul  8 13:35:53 CST 2024] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Mon Jul  8 13:35:53 CST 2024] _ACME_SERVER_PATH='directory'
[Mon Jul  8 13:35:53 CST 2024] DOMAIN_PATH='/root/.acme.sh/example.com_ecc'
[Mon Jul  8 13:35:53 CST 2024] 'dns_cf' does not contain 'dns'
[Mon Jul  8 13:35:53 CST 2024] Le_NextRenewTime
[Mon Jul  8 13:35:53 CST 2024] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Mon Jul  8 13:35:53 CST 2024] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Mon Jul  8 13:35:53 CST 2024] GET
[Mon Jul  8 13:35:53 CST 2024] url='https://acme-v02.api.letsencrypt.org/directory'
[Mon Jul  8 13:35:53 CST 2024] timeout=
[Mon Jul  8 13:35:53 CST 2024] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.bMndLI  -g '
[Mon Jul  8 13:35:54 CST 2024] ret='0'
[Mon Jul  8 13:35:54 CST 2024] response='{
  "KKXxZC4o1VI": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-03/renewalInfo",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}'
[Mon Jul  8 13:35:54 CST 2024] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Mon Jul  8 13:35:54 CST 2024] ACME_NEW_AUTHZ
[Mon Jul  8 13:35:54 CST 2024] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Mon Jul  8 13:35:54 CST 2024] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Mon Jul  8 13:35:54 CST 2024] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Mon Jul  8 13:35:54 CST 2024] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf'
[Mon Jul  8 13:35:54 CST 2024] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Mon Jul  8 13:35:54 CST 2024] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Mon Jul  8 13:35:54 CST 2024] _on_before_issue
[Mon Jul  8 13:35:54 CST 2024] _chk_main_domain='example.com'
[Mon Jul  8 13:35:54 CST 2024] _chk_alt_domains
[Mon Jul  8 13:35:54 CST 2024] 'dns_cf' does not contain 'no'
[Mon Jul  8 13:35:54 CST 2024] Le_LocalAddress
[Mon Jul  8 13:35:54 CST 2024] d='example.com'
[Mon Jul  8 13:35:54 CST 2024] Check for domain='example.com'
[Mon Jul  8 13:35:54 CST 2024] _currentRoot='dns_cf'
[Mon Jul  8 13:35:54 CST 2024] d
[Mon Jul  8 13:35:54 CST 2024] 'dns_cf' does not contain 'apache'
[Mon Jul  8 13:35:54 CST 2024] config file is empty, can not read CA_KEY_HASH
[Mon Jul  8 13:35:54 CST 2024] _saved_account_key_hash
[Mon Jul  8 13:35:54 CST 2024] Using config home:/root/.acme.sh
[Mon Jul  8 13:35:54 CST 2024] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mon Jul  8 13:35:55 CST 2024] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Mon Jul  8 13:35:55 CST 2024] _ACME_SERVER_PATH='directory'
[Mon Jul  8 13:35:55 CST 2024] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Mon Jul  8 13:35:55 CST 2024] Only RSA or EC key is supported. keyfile=/root/.acme.sh/ca/acme-v02.api.letsencrypt.org/directory/account.key
[Mon Jul  8 13:35:55 CST 2024] 
[Mon Jul  8 13:35:55 CST 2024] _on_issue_err
[Mon Jul  8 13:35:55 CST 2024] Please check log file for more details: /root/.acme.sh/acme.sh.log
[Mon Jul  8 13:35:55 CST 2024] _chk_vlist
[Mon Jul  8 13:35:55 CST 2024] Diagnosis versions: 
openssl:openssl
FATAL: Startup failure (dev note: apps_startup()) for openssl
28BBCF1D7F7F0000:error:12800067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:118:filename(/usr/lib/engines-3/devcrypto.so): Error loading shared library /usr/lib/engines-3/devcrypto.so: No such file or directory
28BBCF1D7F7F0000:error:12800067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:147:
28BBCF1D7F7F0000:error:13000084:engine routines:dynamic_load:dso not found:crypto/engine/eng_dyn.c:438:
28BBCF1D7F7F0000:error:13000074:engine routines:ENGINE_by_id:no such engine:crypto/engine/eng_list.c:471:id=devcrypto
28BBCF1D7F7F0000:error:13000066:engine routines:int_engine_configure:engine configuration error:crypto/engine/eng_cnf.c:139:section=devcrypto_sect, name=default_algorithms, value=ALL
28BBCF1D7F7F0000:error:0700006D:configuration file routines:module_run:module initialization error:crypto/conf/conf_mod.c:277:module=engines, value=engines_sect retcode=-1      
apache:
apache doesn't exist.
nginx:
nginx version: nginx/1.21.3 (x86_64-pc-linux-gnu)
built with OpenSSL 3.0.13 30 Jan 2024 (running with OpenSSL 3.3.1 4 Jun 2024)
TLS SNI support enabled
configure arguments: --target=x86_64-openwrt-linux --host=x86_64-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix= --program-suffix= --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls --crossbuild=Linux::x86_64 --prefix=/usr --conf-path=/etc/nginx/nginx.conf --with-http_ssl_module --with-http_gzip_static_module --add-module=/op/lede/x86_64/build_dir/target-x86_64_musl/nginx-ssl/nginx-1.21.3/nginx-naxsi/naxsi_src --with-ipv6 --add-module=/op/lede/x86_64/build_dir/target-x86_64_musl/nginx-ssl/nginx-1.21.3/nginx-ubus-module --with-http_v2_module --add-module=/op/lede/x86_64/build_dir/target-x86_64_musl/nginx-ssl/nginx-1.21.3/nginx-headers-more --error-log-path=stderr --pid-path=/var/run/nginx.pid --lock-path=/var/lock/nginx.lock --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/body --http-proxy-temp-path=/var/lib/nginx/proxy --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --with-cc=x86_64-openwrt-linux-musl-gcc --with-cc-opt='-I/op/lede/x86_64/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/op/lede/x86_64/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/op/lede/x86_64/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/op/lede/x86_64/build_dir/target-x86_64_musl/nginx-ssl/nginx-1.21.3=nginx-1.21.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -fvisibility=hidden -ffunction-sections -fdata-sections -DNGX_LUA_NO_BY_LUA_BLOCK' --with-ld-opt='-L/op/lede/x86_64/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/op/lede/x86_64/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -znow -zrelro -Wl,--gc-sections' --without-http_upstream_zone_module
socat:
socat by Gerhard Rieger and contributors - see www.dest-unreach.org
socat version 1.8.0.0 on 05 Jul 2024 08:05:58
   running on Linux version #0 SMP PREEMPT_DYNAMIC Sat Jul  6 15:05:37 2024, release 6.1.96, machine x86_64
features:
  #define WITH_HELP 1
  #define WITH_STATS 1
  #define WITH_STDIO 1
  #define WITH_FDNUM 1
  #define WITH_FILE 1
  #define WITH_CREAT 1
  #define WITH_GOPEN 1
  #define WITH_TERMIOS 1
  #define WITH_PIPE 1
  #define WITH_SOCKETPAIR 1
  #define WITH_UNIX 1
  #define WITH_ABSTRACT_UNIXSOCKET 1
  #define WITH_IP4 1
  #define WITH_IP6 1
  #define WITH_RAWIP 1
  #define WITH_GENERICSOCKET 1
  #define WITH_INTERFACE 1
  #define WITH_TCP 1
  #define WITH_UDP 1
  #define WITH_SCTP 1
  #define WITH_DCCP 1
  #define WITH_UDPLITE 1
  #define WITH_LISTEN 1
  #define WITH_POSIXMQ 1
  #define WITH_SOCKS4 1
  #define WITH_SOCKS4A 1
  #define WITH_SOCKS5 1
  #define WITH_VSOCK 1
  #define WITH_NAMESPACES 1
  #define WITH_PROXY 1
  #define WITH_SYSTEM 1
  #define WITH_SHELL 1
  #define WITH_EXEC 1
  #undef WITH_READLINE
  #define WITH_TUN 1
  #define WITH_PTY 1
  #undef WITH_OPENSSL
  #undef WITH_FIPS
  #undef WITH_LIBWRAP
  #define WITH_SYCLS 1
  #define WITH_FILAN 1
  #define WITH_RETRY 1
  #define WITH_MSGLEVEL 0 /*debug*/
  #define WITH_DEFAULT_IPV 0

**Comment by webprofusion-chrisc** [comment]
Sounds like https://github.com/acmesh-official/acme.sh/issues/146

**Comment by CO2-mc** [comment]
> Sounds like #146

I removed account.key, and it didnt work.

[Tue Jul  9 12:35:02 CST 2024] Lets find script dir.
[Tue Jul  9 12:35:02 CST 2024] _SCRIPT_='/root/.acme.sh/acme.sh'
[Tue Jul  9 12:35:02 CST 2024] _script='/root/.acme.sh/acme.sh'
[Tue Jul  9 12:35:02 CST 2024] _script_home='/root/.acme.sh'
[Tue Jul  9 12:35:02 CST 2024] Using default home:/root/.acme.sh
[Tue Jul  9 12:35:02 CST 2024] Using config home:/root/.acme.sh
[Tue Jul  9 12:35:02 CST 2024] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.8
[Tue Jul  9 12:35:02 CST 2024] Running cmd: issue
[Tue Jul  9 12:35:02 CST 2024] _main_domain='example.com'
[Tue Jul  9 12:35:02 CST 2024] _alt_domains='no'
[Tue Jul  9 12:35:02 CST 2024] Using config home:/root/.acme.sh
[Tue Jul  9 12:35:02 CST 2024] default_acme_server='https://acme-v02.api.letsencrypt.org/directory'
[Tue Jul  9 12:35:02 CST 2024] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Tue Jul  9 12:35:02 CST 2024] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Tue Jul  9 12:35:02 CST 2024] _ACME_SERVER_PATH='directory'
[Tue Jul  9 12:35:02 CST 2024] DOMAIN_PATH='/root/.acme.sh/example.com_ecc'
[Tue Jul  9 12:35:02 CST 2024] 'dns_cf' does not contain 'dns'
[Tue Jul  9 12:35:02 CST 2024] Le_NextRenewTime
[Tue Jul  9 12:35:02 CST 2024] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Tue Jul  9 12:35:02 CST 2024] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Tue Jul  9 12:35:02 CST 2024] GET
[Tue Jul  9 12:35:02 CST 2024] url='https://acme-v02.api.letsencrypt.org/directory'
[Tue Jul  9 12:35:02 CST 2024] timeout=
[Tue Jul  9 12:35:02 CST 2024] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.DhbpEF  -g '
[Tue Jul  9 12:35:03 CST 2024] ret='0'
[Tue Jul  9 12:35:03 CST 2024] response='{
  "JQh73pILRBU": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-03/renewalInfo",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}'
[Tue Jul  9 12:35:03 CST 2024] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Tue Jul  9 12:35:03 CST 2024] ACME_NEW_AUTHZ
[Tue Jul  9 12:35:03 CST 2024] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Tue Jul  9 12:35:03 CST 2024] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Tue Jul  9 12:35:03 CST 2024] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Tue Jul  9 12:35:03 CST 2024] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf'
[Tue Jul  9 12:35:03 CST 2024] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Tue Jul  9 12:35:03 CST 2024] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Tue Jul  9 12:35:03 CST 2024] _on_before_issue
[Tue Jul  9 12:35:03 CST 2024] _chk_main_domain='example.com'
[Tue Jul  9 12:35:03 CST 2024] _chk_alt_domains
[Tue Jul  9 12:35:03 CST 2024] 'dns_cf' does not contain 'no'
[Tue Jul  9 12:35:03 CST 2024] Le_LocalAddress
[Tue Jul  9 12:35:03 CST 2024] d='example.com'
[Tue Jul  9 12:35:03 CST 2024] Check for domain='example.com'
[Tue Jul  9 12:35:03 CST 2024] _currentRoot='dns_cf'
[Tue Jul  9 12:35:03 CST 2024] d
[Tue Jul  9 12:35:03 CST 2024] 'dns_cf' does not contain 'apache'
[Tue Jul  9 12:35:03 CST 2024] config file is empty, can not read CA_KEY_HASH
[Tue Jul  9 12:35:03 CST 2024] _saved_account_key_hash
[Tue Jul  9 12:35:03 CST 2024] Using config home:/root/.acme.sh
[Tue Jul  9 12:35:03 CST 2024] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Tue Jul  9 12:35:03 CST 2024] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Tue Jul  9 12:35:03 CST 2024] _ACME_SERVER_PATH='directory'
[Tue Jul  9 12:35:03 CST 2024] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Tue Jul  9 12:35:03 CST 2024] length='ec-256'
[Tue Jul  9 12:35:03 CST 2024] Using config home:/root/.acme.sh
[Tue Jul  9 12:35:03 CST 2024] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Tue Jul  9 12:35:03 CST 2024] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Tue Jul  9 12:35:03 CST 2024] _ACME_SERVER_PATH='directory'
[Tue Jul  9 12:35:03 CST 2024] _createkey for file:/root/.acme.sh/ca/acme-v02.api.letsencrypt.org/directory/account.key
[Tue Jul  9 12:35:03 CST 2024] Use length 256
[Tue Jul  9 12:35:04 CST 2024] Using ec name: prime256v1
[Tue Jul  9 12:35:04 CST 2024] error ecc key name: prime256v1
[Tue Jul  9 12:35:04 CST 2024] Create account key error.
[Tue Jul  9 12:35:04 CST 2024] Create account key error.
[Tue Jul  9 12:35:04 CST 2024] _on_issue_err
[Tue Jul  9 12:35:04 CST 2024] Please check log file for more details: /root/.acme.sh/acme.sh.log
[Tue Jul  9 12:35:04 CST 2024] _chk_vlist
[Tue Jul  9 12:35:04 CST 2024] Diagnosis versions: 
openssl:openssl
FATAL: Startup failure (dev note: apps_startup()) for openssl
28BB30CB977F0000:error:12800067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:118:filename(/usr/lib/engines-3/devcrypto.so): Error loading shared library /usr/lib/engines-3/devcrypto.so: No such file or directory
28BB30CB977F0000:error:12800067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:147:
28BB30CB977F0000:error:13000084:engine routines:dynamic_load:dso not found:crypto/engine/eng_dyn.c:438:
28BB30CB977F0000:error:13000074:engine routines:ENGINE_by_id:no such engine:crypto/engine/eng_list.c:471:id=devcrypto
28BB30CB977F0000:error:13000066:engine routines:int_engine_configure:engine configuration error:crypto/engine/eng_cnf.c:139:section=devcrypto_sect, name=default_algorithms, value=ALL
28BB30CB977F0000:error:0700006D:configuration file routines:module_run:module initialization error:crypto/conf/conf_mod.c:277:module=engines, value=engines_sect retcode=-1      
apache:
apache doesn't exist.
nginx:
nginx version: nginx/1.21.3 (x86_64-pc-linux-gnu)
built with OpenSSL 3.0.13 30 Jan 2024 (running with OpenSSL 3.3.1 4 Jun 2024)
TLS SNI support enabled
configure arguments: --target=x86_64-openwrt-linux --host=x86_64-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix= --program-suffix= --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls --crossbuild=Linux::x86_64 --prefix=/usr --conf-path=/etc/nginx/nginx.conf --with-http_ssl_module --with-http_gzip_static_module --add-module=/op/lede/x86_64/build_dir/target-x86_64_musl/nginx-ssl/nginx-1.21.3/nginx-naxsi/naxsi_src --with-ipv6 --add-module=/op/lede/x86_64/build_dir/target-x86_64_musl/nginx-ssl/nginx-1.21.3/nginx-ubus-module --with-http_v2_module --add-module=/op/lede/x86_64/build_dir/target-x86_64_musl/nginx-ssl/nginx-1.21.3/nginx-headers-more --error-log-path=stderr --pid-path=/var/run/nginx.pid --lock-path=/var/lock/nginx.lock --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/body --http-proxy-temp-path=/var/lib/nginx/proxy --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --with-cc=x86_64-openwrt-linux-musl-gcc --with-cc-opt='-I/op/lede/x86_64/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/op/lede/x86_64/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/op/lede/x86_64/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/op/lede/x86_64/build_dir/target-x86_64_musl/nginx-ssl/nginx-1.21.3=nginx-1.21.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -fvisibility=hidden -ffunction-sections -fdata-sections -DNGX_LUA_NO_BY_LUA_BLOCK' --with-ld-opt='-L/op/lede/x86_64/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/op/lede/x86_64/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -znow -zrelro -Wl,--gc-sections' --without-http_upstream_zone_module
socat:
socat by Gerhard Rieger and contributors - see www.dest-unreach.org
socat version 1.8.0.0 on 05 Jul 2024 08:05:58
   running on Linux version #0 SMP PREEMPT_DYNAMIC Sat Jul  6 15:05:37 2024, release 6.1.96, machine x86_64
features:
  #define WITH_HELP 1
  #define WITH_STATS 1
  #define WITH_STDIO 1
  #define WITH_FDNUM 1
  #define WITH_FILE 1
  #define WITH_CREAT 1
  #define WITH_GOPEN 1
  #define WITH_TERMIOS 1
  #define WITH_PIPE 1
  #define WITH_SOCKETPAIR 1
  #define WITH_UNIX 1
  #define WITH_ABSTRACT_UNIXSOCKET 1
  #define WITH_IP4 1
  #define WITH_IP6 1
  #define WITH_RAWIP 1
  #define WITH_GENERICSOCKET 1
  #define WITH_INTERFACE 1
  #define WITH_TCP 1
  #define WITH_UDP 1
  #define WITH_SCTP 1
  #define WITH_DCCP 1
  #define WITH_UDPLITE 1
  #define WITH_LISTEN 1
  #define WITH_POSIXMQ 1
  #define WITH_SOCKS4 1
  #define WITH_SOCKS4A 1
  #define WITH_SOCKS5 1
  #define WITH_VSOCK 1
  #define WITH_NAMESPACES 1
  #define WITH_PROXY 1
  #define WITH_SYSTEM 1
  #define WITH_SHELL 1
  #define WITH_EXEC 1
  #undef WITH_READLINE
  #define WITH_TUN 1
  #define WITH_PTY 1
  #undef WITH_OPENSSL
  #undef WITH_FIPS
  #undef WITH_LIBWRAP
  #define WITH_SYCLS 1
  #define WITH_FILAN 1
  #define WITH_RETRY 1
  #define WITH_MSGLEVEL 0 /*debug*/
  #define WITH_DEFAULT_IPV 0
