### ISSUE TITLE
请问支持天翼云域名的自动集成吗？

### ISSUE THREAD

**Issue by wangweiye01** [acmesh-official/acme.sh#5225]
请问支持天翼云域名的自动集成吗？

**Comment by spendist** [comment]
如果天翼云 域名支持API 调用的话，也支持的， 只是要参考其他 dnsapi 写一个脚本而已，放在  dnsapi 目录中即可。

**Comment by Neilpang** [comment]
建议使用别名模式：
https://github.com/acmesh-official/acme.sh/wiki/DNS-alias-mode
