### ISSUE TITLE
Deploy hook pure-ftpd implemented?

### ISSUE THREAD

**Issue by centminmod** [acmesh-official/acme.sh#5232]
I searched the repo to see if a deploy hook was ever implemented for pure-ftpd and came across https://github.com/acmesh-official/acme.sh/blob/0f61e9c15ec6485f29ee5da73d1759b962a9bc9d/deploy/pureftpd.sh#L10

But was this ever implemented ?

**Comment by Neilpang** [comment]
not yet.
