### ISSUE TITLE
pkcs12(pfx)格式无法支持Plex Media Server自定义证书

### ISSUE THREAD

**Issue by xlszzck** [acmesh-official/acme.sh#5234]
生成的其他证书，已经成功部署在群晖的DSM7系统上。
但是，通过命令`acme.sh  --toPkcs  -d www.abc.com  --password xxx`转换的证书无法使用
通过浏览器访问私有的域名 https://www.abc.com:32400/ 访问plex主页时，会报错
”_你的连接不是专用连接
攻击者可能试图从 www.abc.com 窃取你的信息(例如，密码、消息或信用卡)。
net::ERR_CERT_COMMON_NAME_INVALID_“

Plex Media Server中的自定义证书，配置项：
![QQ20240802-142633](https://github.com/user-attachments/assets/91c07781-6e6e-40bd-8b2a-eff14fb80476)

通过查询，发现Plex Media Server对于自定义证书的要求
1、使用 .P12格式，并由AES-256加密算法生成
2、对转换证书的要求：证书文件必须符合 X.509编码，可用OpenSSL转换

**Comment by GraysonSmith** [comment]
我实测可以使用，DSM7.1的系统，生成的pfx文件，可能是你生成证书后没有重启plex？

**Comment by kilvn** [comment]
搞定了，tmd   要给755权限

```sh
chmod 755 domain.pfx
```

参考：https://www.bilibili.com/opus/811823762093637637

**Comment by xlszzck** [comment]
> 我也遇到了
> 
> acme.sh --to-pkcs12 -d 域名 --password 密码
> 
> plex后台配置好后重启plex和楼主一样的报错 证书签发信息 Subject: *.58114b08b7f44ec58217219096360fd7.plex.direct

请问你用是.pfx还是.p12文件啊？

**Comment by kilvn** [comment]
> > 我也遇到了
> > 
> > acme.sh --to-pkcs12 -d 域名 --password 密码
> > 
> > plex后台配置好后重启plex和楼主一样的报错 证书签发信息 Subject: *.58114b08b7f44ec58217219096360fd7.plex.direct
> 
> 请问你用是.pfx还是.p12文件啊？
> @kilvn 

chmod命令有写，pfx

**Comment by xlszzck** [comment]
> > > 我也遇到了
> > > acme.sh --to-pkcs12 -d 域名 --password 密码
> > > plex后台配置好后重启plex和楼主一样的报错 证书签发信息 Subject: *.58114b08b7f44ec58217219096360fd7.plex.direct
> > 
> > 
> > 请问你用是.pfx还是.p12文件啊？
> > [@kilvn](https://github.com/kilvn)
> 
> chmod命令有写，pfx

试了这个方法，群晖自带的“任务计划”，电脑SSH连接操作都试了
发现还是同样报错，正在排查问题……
