### ISSUE TITLE
README.md: Cron entry example

### ISSUE THREAD

**Issue by fwt-dot-fr-gnss** [acmesh-official/acme.sh#5250]
in README.md
it seems to have an issue:
Cron entry example:
0 0 * * * "/home/user/.acme.sh"/acme.sh --cron --home "/home/user/.acme.sh" > /dev/null
the second " is not at the correct place:
0 0 * * * "/home/user/.acme.sh/acme.sh" --cron --home "/home/user/.acme.sh" > /dev/null

**Comment by fwt-dot-fr-gnss** [comment]
My remarq is on the readme,md only

**Comment by Neilpang** [comment]
that's intensional
