### ISSUE TITLE
DNS domain validation TXT record ADD succeeds, but validation with cloudflare DNS never succeeds

### ISSUE THREAD

**Issue by lifeboy** [acmesh-official/acme.sh#5260]
cloudflare dns test doesn't respond, how do we remove this test?

This is latest version on acme.sh.  I am busy testing a change to the MIAB script, which now passes, but then the test for the new TXT record with cloudflare fails.  I have not been able to figure out how to remove this test for the code.  

```
./acme.sh  --issue  --domain 'fw.fast.za.net' --dns 'dns_miab' --home '/tmp/acme/Primary/' --accountconf '/home/roland/accountconf.conf'
[Thu 22 Aug 2024 13:34:37 SAST] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Thu 22 Aug 2024 13:34:37 SAST] Single domain='fw.fast.za.net'
[Thu 22 Aug 2024 13:34:40 SAST] Getting webroot for domain='fw.fast.za.net'
[Thu 22 Aug 2024 13:34:40 SAST] Adding TXT value: CjmVolIkVLf75vlJb08jHzPbypv8WT0knFKjd4xfa4A for domain: _acme-challenge.fw.fast.za.net
[Thu 22 Aug 2024 13:34:40 SAST] Using miab challenge add
[Thu 22 Aug 2024 13:34:44 SAST] Successfully created the txt record
[Thu 22 Aug 2024 13:34:44 SAST] The TXT record has been successfully added.
[Thu 22 Aug 2024 13:34:44 SAST] Let's check each DNS record now. Sleeping for 20 seconds first.
[Thu 22 Aug 2024 13:35:05 SAST] You can use '--dnssleep' to disable public dns checks.
[Thu 22 Aug 2024 13:35:05 SAST] See: https://github.com/acmesh-official/acme.sh/wiki/dnscheck
[Thu 22 Aug 2024 13:35:05 SAST] Checking fw.fast.za.net for _acme-challenge.fw.fast.za.net
[Thu 22 Aug 2024 13:35:06 SAST] Not valid yet, let's wait for 10 seconds then check the next one.

```

Before I ran the above I tried `--dnssleep 300` which seemed promising, but despite having to wait 5 minutes, it still fails after that.  The wiki indicates that the test for existence will be skipped, but it isn't.

```
./acme.sh  --issue  --domain 'fw.fast.za.net' --dns 'dns_miab' --home '/tmp/acme/Primary/' --accountconf '/home/roland/accountconf.conf' --dnssleep 300
[Wed 21 Aug 2024 20:39:25 SAST] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Wed 21 Aug 2024 20:39:25 SAST] Single domain='fw.fast.za.net'
[Wed 21 Aug 2024 20:39:29 SAST] Getting webroot for domain='fw.fast.za.net'
[Wed 21 Aug 2024 20:39:29 SAST] Adding TXT value: z09GLmoJ3Co8UJWg9zI_RUZ_Q0d5iDSnZ8UvzV0bfAc for domain: _acme-challenge.fw.fast.za.net
[Wed 21 Aug 2024 20:39:29 SAST] Using miab challenge add
[Wed 21 Aug 2024 20:39:30 SAST] Successfully created the txt record
[Wed 21 Aug 2024 20:39:30 SAST] The TXT record has been successfully added.
[Wed 21 Aug 2024 20:39:30 SAST] Sleeping for 300 seconds to wait for the the TXT records to take effect
[Wed 21 Aug 2024 20:44:32 SAST] Verifying: fw.fast.za.net
[Wed 21 Aug 2024 20:44:33 SAST] Pending. The CA is processing your order, please wait. (1/30)
[Wed 21 Aug 2024 20:44:37 SAST] fw.fast.za.net: Invalid status. Verification error details: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.fw.fast.za.net - check that a DNS record exists for this domain
[Wed 21 Aug 2024 20:44:37 SAST] Removing DNS records.
[Wed 21 Aug 2024 20:44:37 SAST] Removing txt: z09GLmoJ3Co8UJWg9zI_RUZ_Q0d5iDSnZ8UvzV0bfAc for domain: _acme-challenge.fw.fast.za.net
[Wed 21 Aug 2024 20:44:37 SAST] Using miab challenge delete
[Wed 21 Aug 2024 20:44:39 SAST] Successfully removed the txt record
[Wed 21 Aug 2024 20:44:39 SAST] Successfully removed
[Wed 21 Aug 2024 20:44:39 SAST] Please check log file for more details: /tmp/acme/Primary/acme_issuecert.log

```

I tried setting --dnssleep 0, which prevents the waiting period.

```
./acme.sh  --issue  --domain 'fw.fast.za.net' --dns 'dns_miab' --home '/tmp/acme/Primary/' --accountconf '/home/roland/accountconf.conf' --dnssleep 0
[Thu 22 Aug 2024 14:17:08 SAST] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Thu 22 Aug 2024 14:17:09 SAST] Single domain='fw.fast.za.net'
[Thu 22 Aug 2024 14:17:12 SAST] Getting webroot for domain='fw.fast.za.net'
[Thu 22 Aug 2024 14:17:12 SAST] Adding TXT value: m4iMy2RlqcIKdnyBSO0xec8SHs1twXFd1hAy7YJp3sQ for domain: _acme-challenge.fw.fast.za.net
[Thu 22 Aug 2024 14:17:12 SAST] Using miab challenge add
[Thu 22 Aug 2024 14:17:14 SAST] Successfully created the txt record
[Thu 22 Aug 2024 14:17:14 SAST] The TXT record has been successfully added.
[Thu 22 Aug 2024 14:17:14 SAST] Sleeping for 0 seconds to wait for the the TXT records to take effect
[Thu 22 Aug 2024 14:17:15 SAST] Verifying: fw.fast.za.net
[Thu 22 Aug 2024 14:17:16 SAST] Pending. The CA is processing your order, please wait. (1/30)
[Thu 22 Aug 2024 14:17:20 SAST] fw.fast.za.net: Invalid status. Verification error details: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.fw.fast.za.net - check that a DNS record exists for this domain
[Thu 22 Aug 2024 14:17:20 SAST] Removing DNS records.
[Thu 22 Aug 2024 14:17:20 SAST] Removing txt: m4iMy2RlqcIKdnyBSO0xec8SHs1twXFd1hAy7YJp3sQ for domain: _acme-challenge.fw.fast.za.net
[Thu 22 Aug 2024 14:17:20 SAST] Using miab challenge delete
[Thu 22 Aug 2024 14:17:22 SAST] Successfully removed the txt record
[Thu 22 Aug 2024 14:17:22 SAST] Successfully removed
[Thu 22 Aug 2024 14:17:22 SAST] Please check log file for more details: /tmp/acme/Primary/acme_issuecert.log

```
I still get a validation error.  The log shows this (actual credentials removed):

```
[acme_issuecert-cleaned.log](https://github.com/user-attachments/files/16710496/acme_issuecert-cleaned.log)

**Comment by lifeboy** [comment]
I have rerun the script with `--debug 2` ...
[output.txt](https://github.com/user-attachments/files/16710666/output.txt)

**Comment by WhiteAls** [comment]
Unfortunately, you cannot "remove" the DNS test. Instead, you have a couple of options:

1. **Change the DNS Provider**: You can export the `DOH_USE` variable to select a different DNS provider for testing. Use `1` for Cloudflare, `2` for Google, `3` for Aliyun, and `4` for DNSPod.

2. **Use `dnssleep`**: You can continue using the `dnssleep` option to extend the waiting period. If you’ve tried `dnssleep 300` (5 minutes) and it's still failing, it might be necessary to increase this wait time even further.

From the debug logs, it seems like the Let’s Encrypt server isn’t finding the required DNS records for your domain. This could be due to:

- **DNS Record Propagation**: The DNS records might not have propagated fully yet. Increasing the `dnssleep` time might help.

- **Incorrect DNS Records**: There could be an issue with how the DNS records are being set by the MIAB script. Ensure that the script is correctly configuring the records and that they are accurate.

Review your MIAB script and ensure it’s correctly handling the DNS records. If the records are correct but propagation is slow, increasing `dnssleep` is your best bet.

**Comment by lifeboy** [comment]
> Unfortunately, you cannot "remove" the DNS test. Instead, you have a couple of options:
> 
> 1. **Change the DNS Provider**: You can export the `DOH_USE` variable to select a different DNS provider for testing. Use `1` for Cloudflare, `2` for Google, `3` for Aliyun, and `4` for DNSPod.

After some test, it turns out Google almost immediately resolves the new record, but CloudFlare doesn't.  I created a test record "_testrecord.fast.za.net" about 15 minutes ago (it's still there), and it's the same case.  Google is fine with it, Cloudflare not.

> 2. **Use `dnssleep`**: You can continue using the `dnssleep` option to extend the waiting period. If you’ve tried `dnssleep 300` (5 minutes) and it's still failing, it might be necessary to increase this wait time even further.
> 
> From the debug logs, it seems like the Let’s Encrypt server isn’t finding the required DNS records for your domain. This could be due to:
> 
> * **DNS Record Propagation**: The DNS records might not have propagated fully yet. Increasing the `dnssleep` time might help.
> * **Incorrect DNS Records**: There could be an issue with how the DNS records are being set by the MIAB script. Ensure that the script is correctly configuring the records and that they are accurate.

When I "export DOH_USE=2" (to select Google as default), without using dnssleep, it takes about 30 seconds for the script to continue, but then the Let's Encrypt server doesn't find the DNS record.  

Not sure how to address that.  The record created by MIAB seems to be quite correct.  After all, it's just a simple TXT record.
In the end I may have to abandon DNS-01 type authentication for Let's Encrypt.

I have opened a ticket with LE support for this [over here](https://community.letsencrypt.org/t/why-doesnt-les-dns-find-my-txt-record-when-google-dns-does/224601).

> Review your MIAB script and ensure it’s correctly handling the DNS records. If the records are correct but propagation is slow, increasing `dnssleep` is your best bet.

the MIAB script creates the record and the acme.sh script validates it when use google dns, but then LE dns fails, as I indicated above.

**Comment by lifeboy** [comment]
I received a response from LE support and it seems there are stale records still at namecheap, where this domain was previously hosted.  I have requested them to remove these records, which should fix the problem.  I will close this ticket once the test completes.

**Comment by lifeboy** [comment]
The DNS records were removed by NameCheap and since the changes ver propagated, the test now works!
