### ISSUE TITLE
[Development] How to ignore status of domain and force DNS validation for testing?

### ISSUE THREAD

**Issue by maddes-b** [acmesh-official/acme.sh#5266]
I am currently developing a DNS API script.
When testing, then the DNS API script is not executed due to the domain/s being already "valid".
Even revoking the cert does not force a new DNS validation.
I have tried `--issue --force` and `--renew --force` but with no success.
I always use `--server letsencrypt_test`.

certbot since 0.40 always triggers a validation when doing a `--dry-run` (see [here](https://community.letsencrypt.org/t/force-new-dns-validation/119539/3)).-

Is there something similar in `acme.sh`?

**Comment by maddes-b** [comment]
Bot reply doesn't apply.
Still open.

**Comment by WhiteAls** [comment]
`./acme.sh --deactivate --staging -d your.domain -d *.your.domain`
https://github.com/acmesh-official/acme.sh/blob/1d59d43286103daf7a91e5c47f1be18eef707844/acme.sh#L6929

**Comment by maddes-b** [comment]
Will try it out.
The deesctiption "Deactivate the domain authz, professional use." is misleading.
Thanks.

**Comment by maddes-b** [comment]
Works. Thanks @WhiteAls

**Comment by maddes-b** [comment]
I updated the DNS API developer guide with that information.
