### ISSUE TITLE
Unable to update certificate, got error response: {"error":{"code":5514},"success":false}.

### ISSUE THREAD

**Issue by xysgx** [acmesh-official/acme.sh#5279]
Unable to update certificate, got error response: {"error":{"code":5514},"success":false}.

code:5514 How to solve?

**Comment by ZeroDeng01** [comment]
> Unable to update certificate, got error response: {"error":{"code":5514},"success":false}.
> 
> code:5514 How to solve?

你这个问题解决了吗
