### ISSUE TITLE
How to issue a cert with an existing private key

### ISSUE THREAD

**Issue by ChaojuWang** [acmesh-official/acme.sh#5283]
The default process generates a random key to issue a new cert. How to issue a cert with an existing private key?
Thanks.

**Comment by ninetian** [comment]
If you want to issue a certificate, you must create a CSR (Certificate Signing Request)  first . When creating a CSR, you will receive two files: file.csr (the certificate signing request file) and file.key (the private key file).

The CSR file is submitted to a CA (Certificate Authority) to request a new certificate. Once the CSR is submitted, the CA will issue a new certificate (usually in .crt format), which will pair with the local private key for use.

If you already have an existing private key, you can simply submit the existing CSR file to the CA to get a new certificate.
the private key not update

https://github.com/acmesh-official/acme.sh/wiki/Issue-a-cert-from-existing-CSR#2-issue-a-cert-from-the-csr

**Comment by ChaojuWang** [comment]
> If you want to issue a certificate, you must create a CSR (Certificate Signing Request) first . When creating a CSR, you will receive two files: file.csr (the certificate signing request file) and file.key (the private key file).
> 
> The CSR file is submitted to a CA (Certificate Authority) to request a new certificate. Once the CSR is submitted, the CA will issue a new certificate (usually in .crt format), which will pair with the local private key for use.
> 
> If you already have an existing private key, you can simply submit the existing CSR file to the CA to get a new certificate. the private key not update
> 
> https://github.com/acmesh-official/acme.sh/wiki/Issue-a-cert-from-existing-CSR#2-issue-a-cert-from-the-csr

Solved, many thanks

**Comment by ChaojuWang** [comment]
BTW
Generate CSR with existing private key by
```
acme.sh --create-csr --domain <domain.tld> [--domain <domain2.tld> ...] [--ecc]
```
or
```
openssl req -new -key keyfile -out csrfile
```
