### ISSUE TITLE
Create pfx for Windows Server 2016

### ISSUE THREAD

**Issue by digi74** [acmesh-official/acme.sh#5312]
I would like to have a certificate issued for Windows Server 2016.
```
./acme.sh --to-pkcs12 --password 'myPass123' --domain name.domain.net
```

If I use the following command, the import works on a Windows Server 2019, but not Windows Server 2016. 

The openSSL command offers the --legacy switch for this.
```
openssl pkcs12 -export -legacy -out name.domain.net.pfx -inkey name.domain.net.key -in name.domain.net.cer -certfile ca.cer -password pass:myPass123
```
Is there a solution here that I could use directly for the acme.sh command?
If this does not work, how should a script be called after the renew?
Above all, how do I get to the domain name as a variable in the script?

Thanks for a helpful tip!

ps. acme.sh is up2date

**Comment by webprofusion-chrisc** [comment]
You could modify your current acme.sh to just include `--legacy` but really this would need some kind of legacy pkcs12 command line option added to `acme.sh`.

Alternatively there are several acme clients designed specifically for Windows which handle PFX (and common windows deployment scenarios). I develop https://certifytheweb.com

**Comment by Neilpang** [comment]
you can use `--reload-cmd /path/to/my/convert.sh`  to convert the format by yourself.
