### ISSUE TITLE
FreeBSD error 500 in _push function

### ISSUE THREAD

**Issue by lifeboy** [acmesh-official/acme.sh#5314]
On the line below a call to the _post function is made:

[response="$(_post "$_data" "$_url" "" "$_httpmethod")"](https://github.com/acmesh-official/acme.sh/blob/eaf11009d1d93513e6a3d3a962bc6efbd3a2803b/dnsapi/dns_miab.sh#L191C5-L191C59)

When dns_miab.sh calls this function to add a DNS TXT record, **_the record is added_**, but then an error 500 is returned as the result.

```
<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

```

The values that are send are:

```
_data='value=SIdD-sTETybs3eYn6egBxaKuKzePgmP_87Kd9_KVF3w&ttl=300'
_api_path='custom/_acme-challenge.fw.fast.za.net/txt'
_url='https://box2.gtahardware.co.za/admin/dns/custom/_acme-challenge.fw.fast.za.net/txt'
_httpmethod='POST'
_CURL='curl --silent --dump-header /tmp/acme/Primary/http.header  -L  --trace-ascii /tmp/tmp.wfpfHdYxMH  -g '
USER_AGENT='acme.sh/3.0.8 (https://github.com/acmesh-official/acme.sh)'

```

I have gone through the code in the _post function, but my knowledge of shell scripting is not advanced enough to figure out why this error occurs.  An HTTP error 500 is a server error, so it's not clear what client side input causes this error.

Maybe testing this script against a FreeBSD server in github will show the problem?  I just don't know how to do that.  Some help would be great please.

Update:  The line on which the call is made seems to be this one:

[1965  response="$($_CURL --user-agent "$USER_AGENT" -X $httpmethod -H "$_H1" -H "$_H2" -H "$_H3" -H "$_H4" -H "$_H5" --data "$body" "$_post_url")"](https://github.com/acmesh-official/acme.sh/blob/eaf11009d1d93513e6a3d3a962bc6efbd3a2803b/acme.sh#L1965)

I'm not sure though.  Is there a way to step through a script like this line by line to see what happens?

Update: I have constructed the curl command from the code and values dumped by _debug to be:

`curl --silent --dump-header /tmp/acme/Primary/http.header xMH -g --user-agent "acme.sh/3.0.8 (https://github.com/acmesh-official/acme.sh)" -X POST -H "Authorization: Basic cm9sYW5kQGd0YWhhcmR3YXJlLmNvLnphOlJnaWF2Z2YyQA==" -H "" -H "" -H "" -H "" --data "body='value=WKckOXT22_p-CMXl6BB869QS5f-gmySQHy4ibzumY6g&ttl=300'" "https://box2.gtahardware.co.za/admin/dns/custom/_acme-challenge.fw.fast.za.net/txt"`

The response then is: `No value for the record provided.`

I think I may be missing the actual line of code that is executed...

[acme_issuecert.log](https://github.com/user-attachments/files/17242066/acme_issuecert.log)

**Comment by lifeboy** [comment]
These test where done with VER=3.1.0 and the error still occurs.  I have added the debug log for completeness sake.

**Comment by lifeboy** [comment]
I see the curl command below also generates a log file.

`_CURL='curl --silent --dump-header /tmp/acme/Primary/http.header  -L  --trace-ascii /tmp/tmp.tUiz1QnRbP  -g '`

I have attached the file for reference and I don't see an error in the response.
[tmp.tUiz1QnRbP.log](https://github.com/user-attachments/files/17243916/tmp.tUiz1QnRbP.log)

**Comment by lifeboy** [comment]
I eventually successfully captured the output of the acme.sh script with `set -x` in the script so provide details.  The file is attached.
[logfile.log](https://github.com/user-attachments/files/17244189/logfile.log)

**Comment by sylecn** [comment]
From your log, I see you are running acme.sh 3.0.8, which has the bug. it's fixed in 3.0.9

3.1.0 is not tagged/released at the moment. I don't know what does VER=3.1.0 mean.

see https://github.com/acmesh-official/acme.sh/commit/02fb40c5074cd0b069e0be408b6c740491858552

it's a quoting issue.

**Comment by sylecn** [comment]
Hold on, I see master has version string 3.1.0.

From [logfile.log](https://github.com/user-attachments/files/17244189/logfile.log), the curl call looks alright. Maybe it's server side issue.

**Comment by lifeboy** [comment]
> 3.1.0 is not tagged/released at the moment. I don't know what does VER=3.1.0 mean.

As I explained, I did "acme.sh --update" and the latest version was downloaded being 3.1.0.

In the installed version (3.1.0) this is the code.

```
dns_miab_add() {
  fulldomain=$1
  txtvalue=$2
  _info "Using miab challenge add"
  _debug fulldomain "$fulldomain"
  _debug txtvalue "$txtvalue"

```

So that's not the problem as you suggested.

**Comment by lifeboy** [comment]
As a test I used some different servers to check if the error is with the LE server, but both staging and production as well as BuyPass staging servers give no different result.

**Comment by lifeboy** [comment]
I have found this problem:

from using `set -x` I can see the call to add the DNS TXT record is this:

`curl --silent --dump-header /tmp/acme/Primary/http.header -L --trace-ascii /tmp/tmp.lCLRnhRX91 -g --user-agent 'acme.sh/3.1.0 (https://github.com/acmesh-official/acme.sh)' -X POST -H 'Authorization: Basic cm9sYW5kQGd0YWhhcmR3YXJlLmNvLnphOlJnaWF2Z2YyQA==' -H '' -H '' -H '' -H '' --data 'value=wHHEicR4juWvW3rBLgpCc7Ec7IvzFN0EMD_0VuPFqWI&ttl=300' https://box2.gtahardware.co.za/admin/dns/custom/_acme-challenge.fw-1b.fast.za.net/txt
`

That gives the error 500 error from the MAIB DNS server.

If I remove the empty additional -H '' options, the record is added correctly without an error 500.

`curl --silent --dump-header /tmp/acme/Primary/http.header -L --trace-ascii /tmp/tmp.lCLRnhRX91 -g --user-agent 'acme.sh/3.1.0 (https://github.com/acmesh-official/acme.sh)' -X POST -H 'Authorization: Basic cm9sYW5kQGd0YWhhcmR3YXJlLmNvLnphOlJnaWF2Z2YyQA=='  --data 'value=wHHEicR4juWvW3rBLgpCc7Ec7IvzFN0EMD_0VuPFqWI&ttl=300' https://box2.gtahardware.co.za/admin/dns/custom/_acme-challenge.fw-1b.fast.za.net/txt`

work fine!

So now I will have to figure out how to remove these empty -H '' options from the _post fiction...

**Comment by lifeboy** [comment]
It turns out that when I did manual API calls to the MIAB DNS server I also got error 500's.  So I reran the MIAB setup and let it update and viola! the problem was solved.

I have learned a lot about how to debug a shell script in the process though!
