### ISSUE TITLE
Support Certificate Transparency

### ISSUE THREAD

**Issue by Neilpang** [acmesh-official/acme.sh#55]
I'm thinking about if there is a way for us to submit the Certificate Transparency.

**Comment by lucasRolff** [comment]
LetsEncrypt does it by default it seems according to https://letsencrypt.org/certificates/

**Comment by lucasRolff** [comment]
As an example, a certificate generated with your script: https://crt.sh/?q=files.optimizer.io or https://crt.sh/?q=paste.lucasrolff.com

**Comment by gloomy-ghost** [comment]
@lucasRolff LetsEncrypt doesn't embed SCTs into certificates or OCSP responses, so webmasters have to submit their certificates to CT servers again in order to acquire SCTs.

**Comment by chinkung** [comment]
Do you have a plan to implement acme.sh to submit and acquire SCT from the CT server ?

There is no ETA on letsencrypt side: https://github.com/letsencrypt/boulder/issues/2244

**Comment by WordlessEcho** [comment]
> If we provide SCTs, it would be via OCSP, definitely not by X.509v3 extension.
[Will you support Certificate Transparency? - Let’s Encrypt Community Support](https://community.letsencrypt.org/t/will-you-support-certificate-transparency/222/2)

> In this case, the CA simultaneously issues the certificate to the log server and the server operator. The server operator then makes an OCSP query to the CA, and the CA responds with the SCT, which the server can include in an OCSP extension during the TLS handshake.
[How Certificate Transparency Works - Certificate Transparency](http://www.certificate-transparency.org/how-ct-works)

**Comment by WordlessEcho** [comment]
> Embed SCT receipts in certificates
> - ETA: February, 2018
>
> https://letsencrypt.org/upcoming-features/

**Comment by FernandoMiguel** [comment]
just one more month till the end of Q1...
I really want this!

**Comment by WordlessEcho** [comment]
Let's Encrypt will handle CTs by itself now. Close this issue anyway.
