### ISSUE TITLE
[LIVESTREAM]!] Northern Ireland Open 2024 LIVE STreams Free ON TV Channel 27 October 2024

### ISSUE THREAD

**Issue by escapistue** [acmesh-official/acme.sh#5942]
THE Northern Ireland Open is heading to the final - with world No 1 Judd Trump meeting reigning World Champion Kyren Wilson.

[CLICK HERE TO WATCH LIVE STREAM NOW](https://tvchannelpass.live/allsports)

[CLICK HERE TO WATCH LIVE STREAM NOW](https://tvchannelpass.live/allsports)
[CLICK HERE TO WATCH LIVE STREAM NOW](https://tvchannelpass.live/allsports)

[CLICK HERE TO WATCH LIVE STREAM NOW](https://tvchannelpass.live/allsports)

Belfast hosts the second Home Nations Series event of the season after September's English Open.

Sign up for the Sport newsletter

Email address
Sign up
Your info will be used in accordance with our Privacy Policy

Judd Trump will defend his crown against Kyren Wilson
1
Judd Trump will defend his crown against Kyren WilsonCredit: Getty
Neil Robertson was victorious in Brentwood, beating Wu Yize 9-7 in a breathtaking final.

The Aussie star is leading the way for the huge £150,000 BetVictor bonus, with three Home Nations events still to play.

Judd Trump is the reigning Northern Ireland Open champion after he claimed the Alex Higgins Trophy for a fourth time by beating Chris Wakelin 9-3 in last year's final.

The World No1 returns in 2024 as part of a star-studded line-up, but snooker icon Ronnie O'Sullivan withdrew late on Sunday night and will miss a third successive tournament because of medical reasons.

READ MORE IN SNOOKER

ROCKET PLAN Ronnie O'Sullivan launches 'perfect' new side hustle after retirement hints

CLOUD NINE-BALL I was banned from my local snooker hall after a FIGHT - I'm now pool champ
LIVE: NORTHERN IRELAND OPEN LATEST

Rocket hasn't played since his shock defeat to He Guoqiang in the first round of the English Open in September.

When is the Northern Ireland Open 2024?
The final rounds of the Northern Ireland Open 2024 begin on Sunday, October 20.
The tournament will run until Sunday, October 27.
The final starts at 12pm.
Waterfront Hall in Belfast will host.
What TV channel is the Northern Ireland Open 2024 on and can it be live streamed?
The Northern Ireland Open will be broadcast live on Eurosport.
Customers can live stream all the action via the discovery+ app/website.
Alternatively, SunSport's live blog will provide day-to-day coverage of the huge tournament in Belfast.

**Comment by jacobharris3** [comment]
fdgd
