### ISSUE TITLE
Truenas deploy doesn't works with version 24.10

### ISSUE THREAD

**Issue by M0NsTeRRR** [acmesh-official/acme.sh#6088]
Steps to reproduce
------------------
Truenas SCALE version 24.10 and use the truenas deploy script.

Debug log
-----------------
/home/admin/.acme.sh/deploy/truenas.sh: line 128: [: : integer expression expected
Unable to set WebDAV certificate
Error deploying for domain: nas.unicornafk.fr
Error encountered while deploying.

```
 ./acme.sh --issue --dns dns_pdns -d nas.unicornafk.fr --ca-bundle ../ca.crt --dnssleep 30 --insecure -d nas.unicornafk.fr --deploy --deploy-hook truenas
```

**Comment by peterlewis** [comment]
Is this broken again for anyone else—now—or just me?

@M0NsTeRRR?

**Comment by M0NsTeRRR** [comment]
What do you mean by broken, any logs ? and you should open a new issue

**Comment by peterlewis** [comment]
Yes, I plan to, but still troubleshooting at the moment. Issue is that newly-generated certs are appearing to have been successfully imported to TrueNAS, but don't appear in the GUI.

I'll open an issue tomorrow, hopefully, once I've confirmed it's related to `truenas.sh`.
