### ISSUE TITLE
acme.sh doesn't respect --reloadcmd and forces sudo

### ISSUE THREAD

**Issue by d3im** [acmesh-official/acme.sh#6112]
Steps to reproduce
------------------
acme.sh --cron --reloadcmd 'doas systemctl reload-or-restart nginx.service'

acme.sh log says:
...
Running reload cmd: sudo /etc/init.d/nginx reload
...

**Comment by d3im** [comment]
Valid for actual version and 3.0.9 also:
acme.sh -v
https://github.com/acmesh-official/acme.sh
v3.1.0

Searched acme.sh file and didn't found where default command comes from and why is not used command supplied by argument. In debug log are some private informations :/

**Comment by Neilpang** [comment]
`--reloadcmd` can only used with `--issue`

**Comment by wbedard** [comment]
> `--reloadcmd` can only used with `--issue`

Sorry if I misunderstood your post.  Did you mean that "--reloadcmd" could only be used alongside "--install-cert", as shown in the examples for Apache, Nginx, etc.?  I do understand that the "--issue" command has to precede using "--install-cert" but your comment leads me to think that there's a workflow where I can run both "--issue" and "--reloadcmd" at the same time.

**Comment by Neilpang** [comment]
yes,   it can only be used with `--issue`  or `--install-cert`
Otherwise,  it would be just ignored.

**Comment by d3im** [comment]
Sorry for potential bothering. I'm just curious where the command comes from. Trying to search in acme.sh script and system files but can't figure it out. Thanks.
