### ISSUE TITLE
创建证书时报错

### ISSUE THREAD

**Issue by adintr** [acmesh-official/acme.sh#6129]
[Wed Dec  4 11:55:21 CST 2024] _is_idn_d='adintr.com'
[Wed Dec  4 11:55:21 CST 2024] _idn_temp
[Wed Dec  4 11:55:21 CST 2024] _is_idn_d='www.adintr.com'
[Wed Dec  4 11:55:21 CST 2024] _idn_temp
[Wed Dec  4 11:55:21 CST 2024] Lets find script dir.
[Wed Dec  4 11:55:21 CST 2024] _SCRIPT_='/home/adie/.acme.sh/acme.sh'
[Wed Dec  4 11:55:21 CST 2024] _script='/home/adie/.acme.sh/acme.sh'
[Wed Dec  4 11:55:21 CST 2024] _script_home='/home/adie/.acme.sh'
[Wed Dec  4 11:55:21 CST 2024] Using config home:/home/adie/.acme.sh
[Wed Dec  4 11:55:21 CST 2024] LE_WORKING_DIR='/home/adie/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.5
[Wed Dec  4 11:55:21 CST 2024] Running cmd: issue
[Wed Dec  4 11:55:21 CST 2024] _main_domain='adintr.com'
[Wed Dec  4 11:55:21 CST 2024] _alt_domains='www.adintr.com'
[Wed Dec  4 11:55:21 CST 2024] Using config home:/home/adie/.acme.sh
[Wed Dec  4 11:55:21 CST 2024] default_acme_server
[Wed Dec  4 11:55:21 CST 2024] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Wed Dec  4 11:55:21 CST 2024] _ACME_SERVER_HOST='acme.zerossl.com'
[Wed Dec  4 11:55:21 CST 2024] _ACME_SERVER_PATH='v2/DV90'
[Wed Dec  4 11:55:21 CST 2024] DOMAIN_PATH='/home/adie/.acme.sh/adintr.com'
[Wed Dec  4 11:55:21 CST 2024] '/srv/myweb/apps/sites/adie/templates' does not contain 'dns'
[Wed Dec  4 11:55:21 CST 2024] Le_NextRenewTime
[Wed Dec  4 11:55:21 CST 2024] Using ACME_DIRECTORY: https://acme.zerossl.com/v2/DV90
[Wed Dec  4 11:55:21 CST 2024] _init api for server: https://acme.zerossl.com/v2/DV90
[Wed Dec  4 11:55:21 CST 2024] GET
[Wed Dec  4 11:55:21 CST 2024] url='https://acme.zerossl.com/v2/DV90'
[Wed Dec  4 11:55:21 CST 2024] timeout=
[Wed Dec  4 11:55:21 CST 2024] _CURL='curl --silent --dump-header /home/adie/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.fkKdn4FU6r '
[Wed Dec  4 11:55:22 CST 2024] ret='0'
[Wed Dec  4 11:55:22 CST 2024] response='{
  "newNonce": "https://acme.zerossl.com/v2/DV90/newNonce",
  "newAccount": "https://acme.zerossl.com/v2/DV90/newAccount",
  "newOrder": "https://acme.zerossl.com/v2/DV90/newOrder",
  "revokeCert": "https://acme.zerossl.com/v2/DV90/revokeCert",
  "renewalInfo": "https://ari.trust-provider.com/renewalInfo",
  "keyChange": "https://acme.zerossl.com/v2/DV90/keyChange",
  "meta": {
    "termsOfService": "https://www.sectigo.com/uploads/files/Certificate-Subscriber-Agreement-2.7-click.pdf",
    "website": "https://zerossl.com",
    "caaIdentities": ["sectigo.com", "trust-provider.com", "usertrust.com", "comodoca.com", "comodo.com"],
    "externalAccountRequired": true
  }
}'
[Wed Dec  4 11:55:22 CST 2024] ACME_KEY_CHANGE='https://acme.zerossl.com/v2/DV90/keyChange'
[Wed Dec  4 11:55:22 CST 2024] ACME_NEW_AUTHZ
[Wed Dec  4 11:55:22 CST 2024] ACME_NEW_ORDER='https://acme.zerossl.com/v2/DV90/newOrder'
[Wed Dec  4 11:55:22 CST 2024] ACME_NEW_ACCOUNT='https://acme.zerossl.com/v2/DV90/newAccount'
[Wed Dec  4 11:55:22 CST 2024] ACME_REVOKE_CERT='https://acme.zerossl.com/v2/DV90/revokeCert'
[Wed Dec  4 11:55:22 CST 2024] ACME_AGREEMENT='https://www.sectigo.com/uploads/files/Certificate-Subscriber-Agreement-2.7-click.pdf'
[Wed Dec  4 11:55:22 CST 2024] ACME_NEW_NONCE='https://acme.zerossl.com/v2/DV90/newNonce'
[Wed Dec  4 11:55:22 CST 2024] Using CA: https://acme.zerossl.com/v2/DV90
[Wed Dec  4 11:55:22 CST 2024] _on_before_issue
[Wed Dec  4 11:55:22 CST 2024] _chk_main_domain='adintr.com'
[Wed Dec  4 11:55:22 CST 2024] _chk_alt_domains='www.adintr.com'
[Wed Dec  4 11:55:22 CST 2024] '/srv/myweb/apps/sites/adie/templates' does not contain 'no'
[Wed Dec  4 11:55:22 CST 2024] Le_LocalAddress
[Wed Dec  4 11:55:22 CST 2024] d='adintr.com'
[Wed Dec  4 11:55:22 CST 2024] Check for domain='adintr.com'
[Wed Dec  4 11:55:22 CST 2024] _currentRoot='/srv/myweb/apps/sites/adie/templates'
[Wed Dec  4 11:55:22 CST 2024] d='www.adintr.com'
[Wed Dec  4 11:55:22 CST 2024] Check for domain='www.adintr.com'
[Wed Dec  4 11:55:22 CST 2024] _currentRoot='/srv/myweb/apps/sites/adie/templates'
[Wed Dec  4 11:55:22 CST 2024] d
[Wed Dec  4 11:55:22 CST 2024] '/srv/myweb/apps/sites/adie/templates' does not contain 'apache'
[Wed Dec  4 11:55:22 CST 2024] _saved_account_key_hash
[Wed Dec  4 11:55:22 CST 2024] Using config home:/home/adie/.acme.sh
[Wed Dec  4 11:55:22 CST 2024] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Wed Dec  4 11:55:22 CST 2024] _ACME_SERVER_HOST='acme.zerossl.com'
[Wed Dec  4 11:55:22 CST 2024] _ACME_SERVER_PATH='v2/DV90'
[Wed Dec  4 11:55:22 CST 2024] _init api for server: https://acme.zerossl.com/v2/DV90
[Wed Dec  4 11:55:22 CST 2024] RSA key
Usage: _hmac hashalg secret [outputhex]
[Wed Dec  4 11:55:22 CST 2024] Registering account: https://acme.zerossl.com/v2/DV90
[Wed Dec  4 11:55:22 CST 2024] url='https://acme.zerossl.com/v2/DV90/newAccount'
[Wed Dec  4 11:55:22 CST 2024] payload='{"contact": ["mailto:emui@163.com"], "termsOfServiceAgreed": true,"externalAccountBinding":{"protected":"eyJhbGciOiJIUzI1NiIsImtpZCI6ImhnaVJWZFNiaFpGb0tRb0MyV3FIWkEiLCJ1cmwiOiJodHRwczovL2FjbWUuemVyb3NzbC5jb20vdjIvRFY5MC9uZXdBY2NvdW50In0", "payload":"eyJlIjogIkFRQUIiLCAia3R5IjogIlJTQSIsICJuIjogInRiWjZkcDEwb1lLY2hTYWNnaVZTeDBLNWEyTFNTeEp4SVZvSENhb3VKNTQ4NFM1X1JPSjdlbUtHc3hPS204M2VhcXltNWZwMHZvT3ljSjVudHVDNG0xbEp0VXh3dXZEQ21pa3R4cTkzZmNkTUJVV2hWcGZyc3hvOHRPTG1iZzRhY1hLbmhrdFNQVXJvOGFiSGNLeVZPYWctUnZfSTh1MFJPdWdteGVUellETElTODhIOExieHpVSnRDbEpUQW9xMnNrR2xXcjR3cEdEX0xuNENxREpmM1ViUGdra3dobGNCbkNRZ2VzNUw0d00xel9zenZJdkJBaXJMcVlYNWM5VjdtUTcyWnpldS1GdVd4TFpnNzFma04zRlpiTERzRjBmTDB4TzNlRzRtVThBUUMtSE4zYTdNcmN6UzBMYkQ5SDU4WDFYUm5VWkZCZnhVZVdMeUpqdVl0dyJ9", "signature":""}}'
[Wed Dec  4 11:55:23 CST 2024] Use cached jwk for file: /home/adie/.acme.sh/ca/acme.zerossl.com/v2/DV90/account.key
[Wed Dec  4 11:55:23 CST 2024] Get nonce with HEAD. ACME_NEW_NONCE='https://acme.zerossl.com/v2/DV90/newNonce'
[Wed Dec  4 11:55:23 CST 2024] HEAD
[Wed Dec  4 11:55:23 CST 2024] _post_url='https://acme.zerossl.com/v2/DV90/newNonce'
[Wed Dec  4 11:55:23 CST 2024] body
[Wed Dec  4 11:55:23 CST 2024] _postContentType='application/jose+json'
[Wed Dec  4 11:55:23 CST 2024] _CURL='curl --silent --dump-header /home/adie/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.GzOlCC4NAf  -I  '
[Wed Dec  4 11:55:24 CST 2024] _ret='0'
[Wed Dec  4 11:55:24 CST 2024] _headers='HTTP/2 200
server: nginx
date: Wed, 04 Dec 2024 03:55:24 GMT
content-type: application/octet-stream
replay-nonce: jj38YXsEcGbUTIb9Hsu8uexn4yCAp20vgvuOsSFD55o
cache-control: max-age=0, no-cache, no-store
access-control-allow-origin: *
link: <https://acme.zerossl.com/v2/DV90>;rel="index"
strict-transport-security: max-age=15724800; includeSubDomains
'
[Wed Dec  4 11:55:24 CST 2024] _CACHED_NONCE='jj38YXsEcGbUTIb9Hsu8uexn4yCAp20vgvuOsSFD55o'
[Wed Dec  4 11:55:24 CST 2024] nonce='jj38YXsEcGbUTIb9Hsu8uexn4yCAp20vgvuOsSFD55o'
[Wed Dec  4 11:55:24 CST 2024] POST
[Wed Dec  4 11:55:24 CST 2024] _post_url='https://acme.zerossl.com/v2/DV90/newAccount'
[Wed Dec  4 11:55:24 CST 2024] body='{"protected": "eyJub25jZSI6ICJqajM4WVhzRWNHYlVUSWI5SHN1OHVleG40eUNBcDIwdmd2dU9zU0ZENTVvIiwgInVybCI6ICJodHRwczovL2FjbWUuemVyb3NzbC5jb20vdjIvRFY5MC9uZXdBY2NvdW50IiwgImFsZyI6ICJSUzI1NiIsICJqd2siOiB7ImUiOiAiQVFBQiIsICJrdHkiOiAiUlNBIiwgIm4iOiAidGJaNmRwMTBvWUtjaFNhY2dpVlN4MEs1YTJMU1N4SnhJVm9IQ2FvdUo1NDg0UzVfUk9KN2VtS0dzeE9LbTgzZWFxeW01ZnAwdm9PeWNKNW50dUM0bTFsSnRVeHd1dkRDbWlrdHhxOTNmY2RNQlVXaFZwZnJzeG84dE9MbWJnNGFjWEtuaGt0U1BVcm84YWJIY0t5Vk9hZy1Sdl9JOHUwUk91Z214ZVR6WURMSVM4OEg4TGJ4elVKdENsSlRBb3Eyc2tHbFdyNHdwR0RfTG40Q3FESmYzVWJQZ2trd2hsY0JuQ1FnZXM1TDR3TTF6X3N6dkl2QkFpckxxWVg1YzlWN21RNzJaemV1LUZ1V3hMWmc3MWZrTjNGWmJMRHNGMGZMMHhPM2VHNG1VOEFRQy1ITjNhN01yY3pTMExiRDlINThYMVhSblVaRkJmeFVlV0x5Smp1WXR3In19", "payload": "eyJjb250YWN0IjogWyJtYWlsdG86ZW11aUAxNjMuY29tIl0sICJ0ZXJtc09mU2VydmljZUFncmVlZCI6IHRydWUsImV4dGVybmFsQWNjb3VudEJpbmRpbmciOnsicHJvdGVjdGVkIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJbXRwWkNJNkltaG5hVkpXWkZOaWFGcEdiMHRSYjBNeVYzRklXa0VpTENKMWNtd2lPaUpvZEhSd2N6b3ZMMkZqYldVdWVtVnliM056YkM1amIyMHZkakl2UkZZNU1DOXVaWGRCWTJOdmRXNTBJbjAiLCAicGF5bG9hZCI6ImV5SmxJam9nSWtGUlFVSWlMQ0FpYTNSNUlqb2dJbEpUUVNJc0lDSnVJam9nSW5SaVdqWmtjREV3YjFsTFkyaFRZV05uYVZaVGVEQkxOV0V5VEZOVGVFcDRTVlp2U0VOaGIzVktOVFE0TkZNMVgxSlBTamRsYlV0SGMzaFBTMjA0TTJWaGNYbHROV1p3TUhadlQzbGpTalZ1ZEhWRE5HMHhiRXAwVlhoM2RYWkVRMjFwYTNSNGNUa3pabU5rVFVKVlYyaFdjR1p5YzNodk9IUlBURzFpWnpSaFkxaExibWhyZEZOUVZYSnZPR0ZpU0dOTGVWWlBZV2N0VW5aZlNUaDFNRkpQZFdkdGVHVlVlbGxFVEVsVE9EaElPRXhpZUhwVlNuUkRiRXBVUVc5eE1uTnJSMnhYY2pSM2NFZEVYMHh1TkVOeFJFcG1NMVZpVUdkcmEzZG9iR05DYmtOUloyVnpOVXcwZDAweGVsOXplblpKZGtKQmFYSk1jVmxZTldNNVZqZHRVVGN5V25wbGRTMUdkVmQ0VEZwbk56Rm1hMDR6UmxwaVRFUnpSakJtVERCNFR6TmxSelJ0VlRoQlVVTXRTRTR6WVRkTmNtTjZVekJNWWtRNVNEVTRXREZZVW01VldrWkNabmhWWlZkTWVVcHFkVmwwZHlKOSIsICJzaWduYXR1cmUiOiIifX0", "signature": "n74T2E1gc8mA0CSb2pFqd_xHL4d0s5Revoix9MvV24utvbQ5hc8BjDv0jK_Ke2RKvZ6qJ0lU2YDYNUnG52oPlgEKNjetNV-2HNjij3cXxGzQmmESuRAGkCOGku9HfRM7WvD4bhlgghKh4NQGNTnOyP2Ss7JeumpLGskQ_RLDoPxUz0BEfGbr1E815EAXlR3OUZ-TfDJY4CNdJ30B8-4QuTJlPy2Ap6pCb-DOl6ToBGjH5NDQaRRvifzwoVbaV3KFY1udybDsHRCl1NW0IYD-lFjTFw-obCGDQRc69q2pyBA3Dk4xC6K3607XsKPwVS3nj_bunsqjjE9muPfNmavJXA"}'
[Wed Dec  4 11:55:24 CST 2024] _postContentType='application/jose+json'
[Wed Dec  4 11:55:24 CST 2024] Http already initialized.
[Wed Dec  4 11:55:24 CST 2024] _CURL='curl --silent --dump-header /home/adie/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.GzOlCC4NAf '
[Wed Dec  4 11:55:26 CST 2024] _ret='0'
[Wed Dec  4 11:55:26 CST 2024] responseHeaders='HTTP/2 400
server: nginx
date: Wed, 04 Dec 2024 03:55:26 GMT
content-type: application/problem+json
content-length: 132
replay-nonce: uAr_aHr2HFtxDhj_wjmfNSELJg_eAI8QxmZ-Pq8QjdY
cache-control: max-age=0, no-cache, no-store
access-control-allow-origin: *
link: <https://acme.zerossl.com/v2/DV90>;rel="index"
strict-transport-security: max-age=15724800; includeSubDomains
'
[Wed Dec  4 11:55:26 CST 2024] code='400'
[Wed Dec  4 11:55:26 CST 2024] original='{"type":"urn:ietf:params:acme:error:malformed","status":400,"detail":"[External Account Binding] The JWS Signature MUST be present"}'
[Wed Dec  4 11:55:26 CST 2024] response='{"type":"urn:ietf:params:acme:error:malformed","status":400,"detail":"[External Account Binding] The JWS Signature MUST be present"}'
[Wed Dec  4 11:55:26 CST 2024] Register account Error: {"type":"urn:ietf:params:acme:error:malformed","status":400,"detail":"[External Account Binding] The JWS Signature MUST be present"}
[Wed Dec  4 11:55:26 CST 2024] _on_issue_err
[Wed Dec  4 11:55:26 CST 2024] Please add '--debug' or '--log' to check more details.
[Wed Dec  4 11:55:26 CST 2024] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Wed Dec  4 11:55:26 CST 2024] _chk_vlist
[Wed Dec  4 11:55:26 CST 2024] socat doesn't exist.
[Wed Dec  4 11:55:26 CST 2024] Diagnosis versions:
openssl:openssl
OpenSSL 1.0.1e-fips 11 Feb 2013
apache:
apache doesn't exist.
nginx:
nginx doesn't exist.
socat:

**Comment by adintr** [comment]
更新后没报错了, 感谢

**Comment by xl316913** [comment]
Last login: Sun Jul  5 15:50:54 2026 from 112.97.54.205
root@mail:~# acme.sh --upgrade
[Sun Jul  5 04:16:38 PM UTC 2026] Already up to date!
[Sun Jul  5 04:16:38 PM UTC 2026] Upgrade successful!
root@mail:~# ~/.acme.sh/acme.sh  --issue  -d mail.d3hui.top  --webroot  /var/www/html
[Sun Jul  5 04:17:03 PM UTC 2026] Using CA: https://acme.zerossl.com/v2/DV90
[Sun Jul  5 04:17:03 PM UTC 2026] Single domain='mail.d3hui.top'
[Sun Jul  5 04:17:06 PM UTC 2026] Getting webroot for domain='mail.d3hui.top'
[Sun Jul  5 04:17:06 PM UTC 2026] Verifying: mail.d3hui.top
[Sun Jul  5 04:17:08 PM UTC 2026] Processing. The CA is processing your order, please wait. (1/30)
[Sun Jul  5 04:17:12 PM UTC 2026] The retryafter=86400 value is too large (> 600), will not retry anymore.
[Sun Jul  5 04:17:12 PM UTC 2026] Please add '--debug' or '--log' to see more information.
[Sun Jul  5 04:17:12 PM UTC 2026] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
root@mail:~#

**Comment by xl316913** [comment]
我也是 Last login: Sun Jul  5 15:50:54 2026 from 112.97.54.205
root@mail:~# acme.sh --upgrade
[Sun Jul  5 04:16:38 PM UTC 2026] Already up to date!
[Sun Jul  5 04:16:38 PM UTC 2026] Upgrade successful!
root@mail:~# ~/.acme.sh/acme.sh  --issue  -d mail.d3hui.top  --webroot  /var/www/html
[Sun Jul  5 04:17:03 PM UTC 2026] Using CA: https://acme.zerossl.com/v2/DV90
[Sun Jul  5 04:17:03 PM UTC 2026] Single domain='mail.d3hui.top'
[Sun Jul  5 04:17:06 PM UTC 2026] Getting webroot for domain='mail.d3hui.top'
[Sun Jul  5 04:17:06 PM UTC 2026] Verifying: mail.d3hui.top
[Sun Jul  5 04:17:08 PM UTC 2026] Processing. The CA is processing your order, please wait. (1/30)
[Sun Jul  5 04:17:12 PM UTC 2026] The retryafter=86400 value is too large (> 600), will not retry anymore.
[Sun Jul  5 04:17:12 PM UTC 2026] Please add '--debug' or '--log' to see more information.
[Sun Jul  5 04:17:12 PM UTC 2026] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
root@mail:~#
