### ISSUE TITLE
[HELP]大佬们帮帮忙看这是什么问题？获取证书成功了，但是部署失败，我也不知道debug2调试信息对不对……

### ISSUE THREAD

**Issue by eirakezhao** [acmesh-official/acme.sh#6133]
本人非程序员也不懂代码，只是想定时更新SSL证书，但现在搞不明白到底哪里出问题了……
用的是DOCKER版的ACME.SH，因为用SSH模式连群晖后，好不容易配置了py环境用curl获取了acme.sh安装包，但是又装不上cron和crontab所以总是安装失败，因为注册表被污染的缘故，只能用SSH PUSH了大佬的DOCKER镜像，然后参考着网上的教程一步一步的设置了脚本和计划任务。终于成功获得了证书但总是卡在了最后一步上……
下面是log信息，看上去像是访问本地5000端口部署证书失败，具体的看不懂……

[Thu Dec  5 10:34:46 UTC 2024] _selectServer try snames='zerossl.com,zerossl'
[Thu Dec  5 10:34:46 UTC 2024] _selectServer try snames='letsencrypt.org,letsencrypt'
[Thu Dec  5 10:34:46 UTC 2024] _selectServer match letsencrypt
[Thu Dec  5 10:34:46 UTC 2024] Selected server: https://acme-v02.api.letsencrypt.org/directory
[Thu Dec  5 10:34:46 UTC 2024] Let's find the script directory.
[Thu Dec  5 10:34:46 UTC 2024] _SCRIPT_='/usr/local/bin/acme.sh'
[Thu Dec  5 10:34:46 UTC 2024] _script='/root/.acme.sh/acme.sh'
[Thu Dec  5 10:34:46 UTC 2024] _script_home='/root/.acme.sh'
[Thu Dec  5 10:34:46 UTC 2024] Using default home: /root/.acme.sh
[Thu Dec  5 10:34:46 UTC 2024] Using config home: /acme.sh
https://github.com/acmesh-official/acme.sh
v3.1.0
[Thu Dec  5 10:34:46 UTC 2024] LE_WORKING_DIR='/root/.acme.sh'
[Thu Dec  5 10:34:46 UTC 2024] Using server: https://acme-v02.api.letsencrypt.org/directory
[Thu Dec  5 10:34:46 UTC 2024] Running cmd: issue
[Thu Dec  5 10:34:46 UTC 2024] _main_domain='worldbest.vip'
[Thu Dec  5 10:34:46 UTC 2024] _alt_domains='*.worldbest.vip'
[Thu Dec  5 10:34:46 UTC 2024] Using config home: /acme.sh
[Thu Dec  5 10:34:46 UTC 2024] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Thu Dec  5 10:34:46 UTC 2024] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Thu Dec  5 10:34:46 UTC 2024] _ACME_SERVER_PATH='directory'
[Thu Dec  5 10:34:46 UTC 2024] DOMAIN_PATH='/acme.sh/worldbest.vip_ecc'
[Thu Dec  5 10:34:46 UTC 2024] 'dns_dp' does not contain 'dns'
[Thu Dec  5 10:34:46 UTC 2024] Le_NextRenewTime='1738233470'
[Thu Dec  5 10:34:46 UTC 2024] _saved_domain='worldbest.vip'
[Thu Dec  5 10:34:46 UTC 2024] _saved_alt='*.worldbest.vip'
[Thu Dec  5 10:34:46 UTC 2024] _normized_saved_domains='*.worldbest.vip,worldbest.vip,'
[Thu Dec  5 10:34:46 UTC 2024] _normized_domains='*.worldbest.vip,worldbest.vip,'
[Thu Dec  5 10:34:46 UTC 2024] Domains not changed.
[Thu Dec  5 10:34:46 UTC 2024] Skipping. Next renewal time is: 2025-01-30T10:37:50Z
[Thu Dec  5 10:34:46 UTC 2024] Add '--force' to force renewal.
[Thu Dec  5 10:34:46 UTC 2024] The domain 'worldbest.vip' seems to already have an ECC cert, let's use it.
[Thu Dec  5 10:34:47 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 7
[Thu Dec  5 10:34:47 UTC 2024] Logging into localhost:5000...
[Thu Dec  5 10:34:47 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 7
[Thu Dec  5 10:34:47 UTC 2024] Unable to authenticate to http://localhost:5000, you may report this by providing full log with '--debug 3'.
[Thu Dec  5 10:34:47 UTC 2024] Error deploying for domain: worldbest.vip
[Thu Dec  5 10:34:47 UTC 2024] Error encountered while deploying.

**Comment by BozhanL** [comment]
你 docker 网络是`bridge`吗？
试试改成`host`，或者用环境变量`SYNO_HOSTNAME`指定地址。

**Comment by eirakezhao** [comment]
> 你 docker 网络是`bridge`吗？ 试试改成`host`，或者用环境变量`SYNO_HOSTNAME`指定地址。

是HOST没错，我再手动加上环境变量试一试。

**Comment by eirakezhao** [comment]
> 你 docker 网络是`bridge`吗？ 试试改成`host`，或者用环境变量`SYNO_HOSTNAME`指定地址。

还是不行，增加了变量SYNO_HOSTNAME 内容是loaclhost，但还是报错。

[Thu Dec 19 08:08:03 UTC 2024] Domains not changed.
[Thu Dec 19 08:08:03 UTC 2024] Skipping. Next renewal time is: 2025-01-30T10:37:50Z
[Thu Dec 19 08:08:03 UTC 2024] Add '--force' to force renewal.
[Thu Dec 19 08:08:03 UTC 2024] The domain 'worldbest.vip' seems to already have an ECC cert, let's use it.
[Thu Dec 19 08:08:03 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 7
[Thu Dec 19 08:08:03 UTC 2024] Logging into localhost:5000...
[Thu Dec 19 08:08:03 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 7
[Thu Dec 19 08:08:03 UTC 2024] Unable to authenticate to http://localhost:5000, you may report this by providing full log with '--debug 3'.
[Thu Dec 19 08:08:03 UTC 2024] Error deploying for domain: worldbest.vip
[Thu Dec 19 08:08:04 UTC 2024] Error encountered while depl

**Comment by BozhanL** [comment]
试试其他的IP地址。例如，你在电脑上访问的地址

**Comment by eirakezhao** [comment]
> 试试其他的IP地址。例如，你在电脑上访问的地址

好，目前我是在公司远程访问，配置环境的话应该是内网环境，变量SYNO_HOSTNAME指定内网NAS访问地址，我再试试。

**Comment by eirakezhao** [comment]
> 试试其他的IP地址。例如，你在电脑上访问的地址

换成本地IP依旧不行，脚本配置和DOCKER变量中我都已经改成了本地IP和端口。
SYNO_Hostname="192.168.3.3" # Specify if not using on localhost
SYNO_Scheme="http"
SYNO_Port="8851"

但不知道为什么脚本依旧访问的是5000端口，虽然5000端口也打开了，但脚本还是失败。
[Thu Dec 19 12:22:59 UTC 2024] Domains not changed.
[Thu Dec 19 12:22:59 UTC 2024] Skipping. Next renewal time is: 2025-01-30T10:37:50Z
[Thu Dec 19 12:22:59 UTC 2024] Add '--force' to force renewal.
[Thu Dec 19 12:22:59 UTC 2024] The domain 'worldbest.vip' seems to already have an ECC cert, let's use it.
[Thu Dec 19 12:23:00 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 7
[Thu Dec 19 12:23:00 UTC 2024] Logging into 192.168.3.3:5000...
[Thu Dec 19 12:23:00 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 7
[Thu Dec 19 12:23:00 UTC 2024] Unable to authenticate to http://192.168.3.3:5000, you may report this by providing full log with '--debug 3'.
[Thu Dec 19 12:23:00 UTC 2024] Error deploying for domain: worldbest.vip
[Thu Dec 19 12:23:00 UTC 2024] Error encountered while deploying.

**Comment by eirakezhao** [comment]
我在脚本和DOCKER中新增变量SYNO_Port改为我使用的登录端口8851，但LOG依旧显示访问的是5000……
是不是这个脚本默认只能通过5000执行？需要我把登录端口全都换回去？

**Comment by eirakezhao** [comment]
何其生草……我在控制面板中把登录端口换成5000，然后脚本就执行成功了……
但是为啥脚本的登录端口改不了啊……这样很麻烦耶……
[Thu Dec 19 15:21:55 UTC 2024] Domains not changed.
[Thu Dec 19 15:21:55 UTC 2024] Skipping. Next renewal time is: 2025-01-30T10:37:50Z
[Thu Dec 19 15:21:55 UTC 2024] Add '--force' to force renewal.
[Thu Dec 19 15:21:55 UTC 2024] The domain 'worldbest.vip' seems to already have an ECC cert, let's use it.
[Thu Dec 19 15:21:56 UTC 2024] Logging into 192.168.3.3:5000...
[Thu Dec 19 15:21:57 UTC 2024] Getting certificates in Synology DSM...
[Thu Dec 19 15:21:57 UTC 2024] Generating form POST request...
[Thu Dec 19 15:21:57 UTC 2024] Upload certificate to the Synology DSM.
[Thu Dec 19 15:22:20 UTC 2024] Restart HTTP services succeeded.
[Thu Dec 19 15:22:20 UTC 2024] Success

**Comment by Chi11-H** [comment]
> 本人非程序员也不懂代码，只是想定时更新SSL证书，但现在搞不明白到底哪里出问题了…… 用的是DOCKER版的ACME.SH，因为用SSH模式连群晖后，好不容易配置了py环境用curl获取了acme.sh安装包，但是又装不上cron和crontab所以总是安装失败，因为注册表被污染的缘故，只能用SSH PUSH了大佬的DOCKER镜像，然后参考着网上的教程一步一步的设置了脚本和计划任务。终于成功获得了证书但总是卡在了最后一步上…… 下面是log信息，看上去像是访问本地5000端口部署证书失败，具体的看不懂……
> 
> [Thu Dec 5 10:34:46 UTC 2024] _selectServer try snames='zerossl.com,zerossl' [Thu Dec 5 10:34:46 UTC 2024] _selectServer try snames='letsencrypt.org,letsencrypt' [Thu Dec 5 10:34:46 UTC 2024] _selectServer match letsencrypt [Thu Dec 5 10:34:46 UTC 2024] Selected server: https://acme-v02.api.letsencrypt.org/directory [Thu Dec 5 10:34:46 UTC 2024] Let's find the script directory. [Thu Dec 5 10:34:46 UTC 2024] _SCRIPT_='/usr/local/bin/acme.sh' [Thu Dec 5 10:34:46 UTC 2024] _script='/root/.acme.sh/acme.sh' [Thu Dec 5 10:34:46 UTC 2024] _script_home='/root/.acme.sh' [Thu Dec 5 10:34:46 UTC 2024] Using default home: /root/.acme.sh [Thu Dec 5 10:34:46 UTC 2024] Using config home: /acme.sh https://github.com/acmesh-official/acme.sh v3.1.0 [Thu Dec 5 10:34:46 UTC 2024] LE_WORKING_DIR='/root/.acme.sh' [Thu Dec 5 10:34:46 UTC 2024] Using server: https://acme-v02.api.letsencrypt.org/directory [Thu Dec 5 10:34:46 UTC 2024] Running cmd: issue [Thu Dec 5 10:34:46 UTC 2024] _main_domain='worldbest.vip' [Thu Dec 5 10:34:46 UTC 2024] _alt_domains='_.worldbest.vip' [Thu Dec 5 10:34:46 UTC 2024] Using config home: /acme.sh [Thu Dec 5 10:34:46 UTC 2024] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory' [Thu Dec 5 10:34:46 UTC 2024] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org' [Thu Dec 5 10:34:46 UTC 2024] _ACME_SERVER_PATH='directory' [Thu Dec 5 10:34:46 UTC 2024] DOMAIN_PATH='/acme.sh/worldbest.vip_ecc' [Thu Dec 5 10:34:46 UTC 2024] 'dns_dp' does not contain 'dns' [Thu Dec 5 10:34:46 UTC 2024] Le_NextRenewTime='1738233470' [Thu Dec 5 10:34:46 UTC 2024] _saved_domain='worldbest.vip' [Thu Dec 5 10:34:46 UTC 2024] _saved_alt='_.worldbest.vip' [Thu Dec 5 10:34:46 UTC 2024] _normized_saved_domains='_.worldbest.vip,worldbest.vip,' [Thu Dec 5 10:34:46 UTC 2024] _normized_domains='_.worldbest.vip,worldbest.vip,' [Thu Dec 5 10:34:46 UTC 2024] Domains not changed. [Thu Dec 5 10:34:46 UTC 2024] Skipping. Next renewal time is: 2025-01-30T10:37:50Z [Thu Dec 5 10:34:46 UTC 2024] Add '--force' to force renewal. [Thu Dec 5 10:34:46 UTC 2024] The domain 'worldbest.vip' seems to already have an ECC cert, let's use it. [Thu Dec 5 10:34:47 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 7 [Thu Dec 5 10:34:47 UTC 2024] Logging into localhost:5000... [Thu Dec 5 10:34:47 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 7 [Thu Dec 5 10:34:47 UTC 2024] Unable to authenticate to http://localhost:5000, you may report this by providing full log with '--debug 3'. [Thu Dec 5 10:34:47 UTC 2024] Error deploying for domain: worldbest.vip [Thu Dec 5 10:34:47 UTC 2024] Error encountered while deploying.

# 下面三个环境变量改成大写
SYNOHostname="**SYNO_HOSTNAME**=${SYNO_Hostname}"
SYNOScheme="**SYNO_SCHEME**=${SYNO_Scheme}"
SYNOPort="**SYNO_PORT**=${SYNO_Port}"
