### ISSUE TITLE
Signing failed. Could not get Le_LinkCert

### ISSUE THREAD

**Issue by EverSpring** [acmesh-official/acme.sh#6137]
* acme version: v3.1.0
* command: `acme.sh --issue -d domain.com --dns dns_dp --server https://acme.freessl.cn/v2/DV90/directory/xxxxx --debug 2`
* detail log:
>>
[Fri Dec  6 23:42:04 CST 2024] _selectServer try snames='zerossl.com,zerossl'
[Fri Dec  6 23:42:04 CST 2024] _selectServer try snames='letsencrypt.org,letsencrypt'
[Fri Dec  6 23:42:04 CST 2024] _selectServer try snames='letsencrypt.org_test,letsencrypt_test,letsencrypttest'
[Fri Dec  6 23:42:04 CST 2024] _selectServer try snames='buypass.com,buypass'
[Fri Dec  6 23:42:04 CST 2024] _selectServer try snames='buypass.com_test,buypass_test,buypasstest'
[Fri Dec  6 23:42:04 CST 2024] _selectServer try snames='ssl.com,sslcom'
[Fri Dec  6 23:42:04 CST 2024] _selectServer try snames='google.com,google'
[Fri Dec  6 23:42:04 CST 2024] _selectServer try snames='google.com_test,googletest,google_test'
[Fri Dec  6 23:42:04 CST 2024] Let's find the script directory.
[Fri Dec  6 23:42:04 CST 2024] _SCRIPT_='/root/.acme.sh/acme.sh'
[Fri Dec  6 23:42:04 CST 2024] _script='/root/.acme.sh/acme.sh'
[Fri Dec  6 23:42:04 CST 2024] _script_home='/root/.acme.sh'
[Fri Dec  6 23:42:04 CST 2024] Using config home: /root/.acme.sh
[Fri Dec  6 23:42:04 CST 2024] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.1.0
[Fri Dec  6 23:42:04 CST 2024] Using server: https://acme.freessl.cn/v2/DV90/directory/xxxx
[Fri Dec  6 23:42:04 CST 2024] Running cmd: issue
[Fri Dec  6 23:42:04 CST 2024] _main_domain='mydomain.com'
[Fri Dec  6 23:42:04 CST 2024] _alt_domains='no'
[Fri Dec  6 23:42:04 CST 2024] Using config home: /root/.acme.sh
[Fri Dec  6 23:42:04 CST 2024] ACME_DIRECTORY='https://acme.freessl.cn/v2/DV90/directory/xxxx'
[Fri Dec  6 23:42:04 CST 2024] _ACME_SERVER_HOST='acme.freessl.cn'
[Fri Dec  6 23:42:04 CST 2024] _ACME_SERVER_PATH='v2/DV90/directory/xxxx'
[Fri Dec  6 23:42:04 CST 2024] DOMAIN_PATH='/root/.acme.sh/mydomain.com_ecc'
[Fri Dec  6 23:42:04 CST 2024] 'dns_dp' does not contain 'dns'
[Fri Dec  6 23:42:04 CST 2024] Le_NextRenewTime
[Fri Dec  6 23:42:04 CST 2024] Using ACME_DIRECTORY: https://acme.freessl.cn/v2/DV90/directory/xxxx
[Fri Dec  6 23:42:04 CST 2024] _init API for server: https://acme.freessl.cn/v2/DV90/directory/xxxx
[Fri Dec  6 23:42:04 CST 2024] GET
[Fri Dec  6 23:42:04 CST 2024] url='https://acme.freessl.cn/v2/DV90/directory/xxxx'
[Fri Dec  6 23:42:04 CST 2024] timeout=
[Fri Dec  6 23:42:04 CST 2024] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.86YOaUpq68  -g '
[Fri Dec  6 23:42:04 CST 2024] ret='0'
[Fri Dec  6 23:42:04 CST 2024] response='{
    "newAccount": "https://acme.freessl.cn/v2/DV90/new-account/xxxx",
    "newOrder": "https://acme.freessl.cn/v2/DV90/new-order/xxxx",
    "revokeCert": "https://acme.freessl.cn/v2/DV90/revoke-cert/xxxx",
    "keyChange": "https://acme.freessl.cn/v2/DV90/key-change/xxxx",
    "newNonce": "https://acme.freessl.cn/v2/DV90/new-nonce/xxxx",
    "meta": {
        "caaIdentities": [
            "sectigo.com",
            "trust-provider.com",
            "usertrust.com",
            "comodoca.com",
            "comodo.com"
        ],
        "externalAccountRequired": false,
        "termsOfService": "https://secure.trust-provider.com/repository/docs/Legacy/20201020_Certificate_Subscriber_Agreement_v_2_4_click.pdf"
    }
}'
[Fri Dec  6 23:42:04 CST 2024] ACME_KEY_CHANGE='https://acme.freessl.cn/v2/DV90/key-change/xxxx'
[Fri Dec  6 23:42:04 CST 2024] ACME_NEW_AUTHZ
[Fri Dec  6 23:42:04 CST 2024] ACME_NEW_ORDER='https://acme.freessl.cn/v2/DV90/new-order/xxxx'
[Fri Dec  6 23:42:04 CST 2024] ACME_NEW_ACCOUNT='https://acme.freessl.cn/v2/DV90/new-account/xxxx'
[Fri Dec  6 23:42:04 CST 2024] ACME_REVOKE_CERT='https://acme.freessl.cn/v2/DV90/revoke-cert/xxxx'
[Fri Dec  6 23:42:04 CST 2024] ACME_AGREEMENT='https://secure.trust-provider.com/repository/docs/Legacy/20201020_Certificate_Subscriber_Agreement_v_2_4_click.pdf'
[Fri Dec  6 23:42:04 CST 2024] ACME_NEW_NONCE='https://acme.freessl.cn/v2/DV90/new-nonce/xxxx'
[Fri Dec  6 23:42:04 CST 2024] Using CA: https://acme.freessl.cn/v2/DV90/directory/xxxx
[Fri Dec  6 23:42:04 CST 2024] _on_before_issue
[Fri Dec  6 23:42:04 CST 2024] _chk_main_domain='mydomain.com'
[Fri Dec  6 23:42:04 CST 2024] _chk_alt_domains
[Fri Dec  6 23:42:04 CST 2024] 'dns_dp' does not contain 'no'
[Fri Dec  6 23:42:04 CST 2024] Le_LocalAddress
[Fri Dec  6 23:42:04 CST 2024] d='mydomain.com'
[Fri Dec  6 23:42:04 CST 2024] Checking for domain='mydomain.com'
[Fri Dec  6 23:42:04 CST 2024] _currentRoot='dns_dp'
[Fri Dec  6 23:42:04 CST 2024] d
[Fri Dec  6 23:42:04 CST 2024] 'dns_dp' does not contain 'apache'
[Fri Dec  6 23:42:04 CST 2024] _saved_account_key_hash='mY7dvPTjbJWlky7o6yePJV/ek62dKPp/zmwLsnvOh9o='
[Fri Dec  6 23:42:05 CST 2024] _saved_account_key_hash was not changed, skipping account registration.
[Fri Dec  6 23:42:05 CST 2024] Read key length: ec-256
[Fri Dec  6 23:42:05 CST 2024] _createcsr
[Fri Dec  6 23:42:05 CST 2024] domain='mydomain.com'
[Fri Dec  6 23:42:05 CST 2024] domainlist
[Fri Dec  6 23:42:05 CST 2024] csrkey='/root/.acme.sh/mydomain.com_ecc/mydomain.com.key'
[Fri Dec  6 23:42:05 CST 2024] csr='/root/.acme.sh/mydomain.com_ecc/mydomain.com.csr'
[Fri Dec  6 23:42:05 CST 2024] csrconf='/root/.acme.sh/mydomain.com_ecc/mydomain.com.csr.conf'
[Fri Dec  6 23:42:05 CST 2024] Single domain='mydomain.com'
[Fri Dec  6 23:42:05 CST 2024] seg='card'
[Fri Dec  6 23:42:05 CST 2024] _is_idn_d='mydomain.com'
[Fri Dec  6 23:42:05 CST 2024] _idn_temp
[Fri Dec  6 23:42:05 CST 2024] _is_idn_d='mydomain.com'
[Fri Dec  6 23:42:05 CST 2024] _idn_temp
[Fri Dec  6 23:42:05 CST 2024] _csr_cn='mydomain.com'
[Fri Dec  6 23:42:05 CST 2024] seg='card'
[Fri Dec  6 23:42:05 CST 2024] Getting domain auth token for each domain
[Fri Dec  6 23:42:05 CST 2024] seg='card'
[Fri Dec  6 23:42:05 CST 2024] _is_idn_d='mydomain.com'
[Fri Dec  6 23:42:05 CST 2024] _idn_temp
[Fri Dec  6 23:42:05 CST 2024] d
[Fri Dec  6 23:42:05 CST 2024] _identifiers='{"type":"dns","value":"mydomain.com"}'
[Fri Dec  6 23:42:05 CST 2024] _notBefore
[Fri Dec  6 23:42:05 CST 2024] _notAfter
[Fri Dec  6 23:42:05 CST 2024] STEP 1, Ordering a Certificate
...................................................................................
[Fri Dec  6 23:50:13 CST 2024] =======Sending Signed Request=======
[Fri Dec  6 23:50:13 CST 2024] url='https://acme.freessl.cn/v2/DV90/order/xxxx/54048/667880'
[Fri Dec  6 23:50:13 CST 2024] payload
[Fri Dec  6 23:50:13 CST 2024] Use cached jwk for file: /root/.acme.sh/ca/acme.freessl.cn/v2/DV90/directory/xxxx/account.key
[Fri Dec  6 23:50:13 CST 2024] Use _CACHED_NONCE='YxD9XyGDCGAGHd8hSH6Xlx7Xxevs-5RHz7e0_QuPNBo'
[Fri Dec  6 23:50:13 CST 2024] nonce='YxD9XyGDCGAGHd8hSH6Xlx7Xxevs-5RHz7e0_QuPNBo'
[Fri Dec  6 23:50:13 CST 2024] POST
[Fri Dec  6 23:50:13 CST 2024] _post_url='https://acme.freessl.cn/v2/DV90/order/xxxx/54048/667880'
[Fri Dec  6 23:50:13 CST 2024] body='{"protected": "eyJub25jZSI6ICJZeEQ5WHlHRENHQUdIZDhoU0g2WGx4N1h4ZXZzLTVSSHo3ZTBfUXVQTkJvIiwgInVybCI6ICJodHRwczovL2FjbWUuZnJlZXNzbC5jbi92Mi9EVjkwL29yZGVyLzJyZGcydHZxd3dqaXl3dTR6MzN6LzU0MDQ4LzY2Nzg4MCIsICJhbGciOiAiRVMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS5mcmVlc3NsLmNuL3YyL0RWOTAvYWNjb3VudC8ycmRnMnR2cXd3aml5d3U0ejMzei81NDA0OCJ9", "payload": "", "signature": "CnrsV3Yl1cRGoccEaCjm7rJyEDshxTnYu7FaCR16FUDFBAOttXlbsHu7k6PmlQtDUvSF10oon8ydzFtHRixXWQ"}'
[Fri Dec  6 23:50:13 CST 2024] _postContentType='application/jose+json'
[Fri Dec  6 23:50:13 CST 2024] Http already initialized.
[Fri Dec  6 23:50:13 CST 2024] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.JvxJmqvDjm  -g '
[Fri Dec  6 23:50:13 CST 2024] _ret='0'
[Fri Dec  6 23:50:13 CST 2024] responseHeaders='HTTP/1.1 200 OK
Date: Fri, 06 Dec 2024 15:50:13 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 293
Connection: keep-alive
Server: nginx/1.20.1
Cache-Control: no-store
Link: <https://acme.freessl.cn/v2/DV90/directory/xxxx>;rel="index"
Replay-Nonce: FvG3zfpq2rLLaid2RArsHbs0ONHPzXfBS_QRfA_mFt8
Retry-After: 15
X-Trace-Id: c52e64123c1de8087c5f6af950d0c278
X-Via: 1.1 wzhdx62:10 (Cdn Cache Server V2.0)
x-ws-request-id: 67531d35_PS-WNZ-01GUT71_24761-57082
'
[Fri Dec  6 23:50:13 CST 2024] code='200'
[Fri Dec  6 23:50:13 CST 2024] original='{"status":"processing","expires":"2025-03-06T15:07:18Z","identifiers":[{"type":"dns","value":"mydomain.com"}],"authorizations":["https://acme.freessl.cn/v2/DV90/authz/xxxx/903525"],"finalize":"https://acme.freessl.cn/v2/DV90/finalize/xxxx/54048/667880"}'
[Fri Dec  6 23:50:13 CST 2024] response='{"status":"processing","expires":"2025-03-06T15:07:18Z","identifiers":[{"type":"dns","value":"mydomain.com"}],"authorizations":["https://acme.freessl.cn/v2/DV90/authz/xxxx/903525"],"finalize":"https://acme.freessl.cn/v2/DV90/finalize/xxxx/54048/667880"}'
**[Fri Dec  6 23:50:13 CST 2024] Signing failed. Could not get Le_LinkCert, and stopped retrying after reaching the retry limit.
[Fri Dec  6 23:50:13 CST 2024] {"status":"processing","expires":"2025-03-06T15:07:18Z","identifiers":[{"type":"dns","value":"mydomain.com"}],"authorizations":["https://acme.freessl.cn/v2/DV90/authz/xxxx/903525"],"finalize":"https://acme.freessl.cn/v2/DV90/finalize/xxxx/54048/667880"}**
[Fri Dec  6 23:50:13 CST 2024] _on_issue_err

* I tried:
`curl https://acme.freessl.cn/v2/DV90/authz/xxxx/903525`, `curl https://acme.freessl.cn/v2/DV90/finalize/xxxx/54048/667880` ,but 404 page not found

**Thank you again for your contribution.**

**Comment by EverSpring** [comment]
> Please upgrade to the latest code and try again first. Maybe it's already fixed. `acme.sh --upgrade` If it's still not working, please provide the log with `--debug 2`, otherwise, nobody can help you.

1. It is the latest version.
2. The above log is printed through --debug 2.

**Comment by xiaobai-beer** [comment]
------------------------------ Let's Encrypt merlin addon by sadog -------------------------------

【2024年12月27日 22:11:41】: 开始为www.lwllt.cn申请证书！
【2024年12月27日 22:11:41】: 证书申请过程可能会持续3分钟，请不要关闭或刷新本网页！
【2024年12月27日 22:11:41】: 使用Aliyun dns接口申请证书...
[Fri Dec 27 22:11:49 CST 2024] Create account key ok.
[Fri Dec 27 22:11:49 CST 2024] Registering account
[Fri Dec 27 22:11:52 CST 2024] Registered
[Fri Dec 27 22:11:52 CST 2024] ACCOUNT_THUMBPRINT='YbXusKcU71abuuW-qwco5wIvLnGfZw2hnPzj0K1WSLI'
[Fri Dec 27 22:11:52 CST 2024] Creating domain key
[Fri Dec 27 22:11:53 CST 2024] The domain key is here: /koolshare/acme/www.lwllt.cn/www.lwllt.cn.key
[Fri Dec 27 22:11:53 CST 2024] Single domain='www.lwllt.cn'
[Fri Dec 27 22:11:53 CST 2024] Getting domain auth token for each domain
[Fri Dec 27 22:11:57 CST 2024] Getting webroot for domain='www.lwllt.cn'
[Fri Dec 27 22:11:58 CST 2024] Adding txt value: o9sb9ZYA5XcMCYkEY02LT19DJkAL_0An9VWgf93uaDM for domain:  _acme-challenge.www.lwllt.cn
[Fri Dec 27 22:12:05 CST 2024] The txt record is added: Success.
[Fri Dec 27 22:12:05 CST 2024] Let's check each dns records now. Sleep 20 seconds first.
[Fri Dec 27 22:12:26 CST 2024] Checking www.lwllt.cn for _acme-challenge.www.lwllt.cn
[Fri Dec 27 22:16:55 CST 2024] Please refer to https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html for error code: 4
[Fri Dec 27 22:16:55 CST 2024] Not valid yet, let's wait 10 seconds and check next one.
[Fri Dec 27 22:16:55 CST 2024] Please refer to https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html for error code: 4
[Fri Dec 27 22:17:05 CST 2024] Let's wait 10 seconds and check again.
[Fri Dec 27 22:17:15 CST 2024] Checking www.lwllt.cn for _acme-challenge.www.lwllt.cn
[Fri Dec 27 22:21:44 CST 2024] Please refer to https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html for error code: 4
[Fri Dec 27 22:21:44 CST 2024] Not valid yet, let's wait 10 seconds and check next one.
[Fri Dec 27 22:21:45 CST 2024] Please refer to https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html for error code: 4
[Fri Dec 27 22:21:55 CST 2024] Let's wait 10 seconds and check again.
[Fri Dec 27 22:22:05 CST 2024] Checking www.lwllt.cn for _acme-challenge.www.lwllt.cn
[Fri Dec 27 22:26:37 CST 2024] Please refer to https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html for error code: 4
[Fri Dec 27 22:26:37 CST 2024] Not valid yet, let's wait 10 seconds and check next one.
[Fri Dec 27 22:26:43 CST 2024] Please refer to https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html for error code: 4
[Fri Dec 27 22:26:53 CST 2024] Let's wait 10 seconds and check again.
[Fri Dec 27 22:27:03 CST 2024] Checking www.lwllt.cn for _acme-challenge.www.lwllt.cn
[Fri Dec 27 22:31:38 CST 2024] Please refer to https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html for error code: 4
[Fri Dec 27 22:31:38 CST 2024] Not valid yet, let's wait 10 seconds and check next one.
[Fri Dec 27 22:31:38 CST 2024] Please refer to https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html for error code: 4
[Fri Dec 27 22:31:48 CST 2024] Let's wait 10 seconds and check again.
[Fri Dec 27 22:31:58 CST 2024] Checking www.lwllt.cn for _acme-challenge.www.lwllt.cn
[Fri Dec 27 22:36:27 CST 2024] Please refer to https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html for error code: 4
[Fri Dec 27 22:36:27 CST 2024] Not valid yet, let's wait 10 seconds and check next one.
[Fri Dec 27 22:36:28 CST 2024] Please refer to https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html for error code: 4
[Fri Dec 27 22:36:38 CST 2024] Let's wait 10 seconds and check again.
[Fri Dec 27 22:36:48 CST 2024] Timed out waiting for DNS.
[Fri Dec 27 22:36:48 CST 2024] check dns error.
[Fri Dec 27 22:36:48 CST 2024] Please add '--debug' or '--log' to check more details.
[Fri Dec 27 22:36:48 CST 2024] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Fri Dec 27 22:36:48 CST 2024] Removing DNS records.
[Fri Dec 27 22:36:48 CST 2024] Removing txt: o9sb9ZYA5XcMCYkEY02LT19DJkAL_0An9VWgf93uaDM for domain: _acme-challenge.www.lwllt.cn
[Fri Dec 27 22:36:57 CST 2024] Removed: Success
【2024年12月27日 22:36:57】: 证书申请失败，请检查插件配置、域名等是否正确！！
【2024年12月27日 22:36:57】: 清理相关残留并关闭插件！！

**Comment by xiaobai-beer** [comment]
这是我的问题 一直报代码4  也不知道咋回事

**Comment by Neilpang** [comment]
加上  `--dnssleep 60`
