### ISSUE TITLE
Does not handle a path with spaces correctly when using --webroot

### ISSUE THREAD

**Issue by alienmindbender** [acmesh-official/acme.sh#6138]
A webroot path with a space gets wrongly split up due to missing quotes at the three `` for ventry in $ventries; do`` loops.
Quoting ``"$ventries"``resolves this issue.

Another issue - proabably related to this (otherwise somebody should have stumpled upon that already) - is a malfomed url string:
``url='https://acme.zerossl.com/v2/DV90/authz/MDSG3E7lE72Y3gmzu0_itA '``.

I made previously a false assumption here, that this is also due to an unquoted string. This is not the case.
Trimming the whitespace with ``url=$(printf "$1" | xargs)`` seems to do the trick

**Comment by Neilpang** [comment]
we can not support this case.
please don't include space in the path
