### ISSUE TITLE
申请证书DNS匹配异常

### ISSUE THREAD

**Issue by 692568516** [acmesh-official/acme.sh#6167]
当前版本3.0.8，之前一直正常，最近不知道为什么异常

1、一个顶级域名下申请两个泛域名证书，如果先申请*.monitor.baidu.com 就会导致第二步申请的*.baidu.com 证书错误，dns变为DNS:baidu.com,DNS:monitor.baidu.com

2、如果先申请*.baidu.com 然后在申请*.monitor.baidu.com 就没问题

./acme.sh --issue --dns dns_dp -d monitor.baidu.com -d *.monitor.baidu.com  --force   --keylength 4096  
[Fri Dec 20 14:32:16 CST 2024] The domain key is here: /root/.acme.sh/monitor.baidu.com/monitor.baidu.com.key
[Fri Dec 20 14:32:16 CST 2024] Multi domain='DNS:monitor.baidu.com,DNS:*.monitor.baidu.com'

./acme.sh --issue --dns dns_dp -d baidu.com -d *.baidu.com  --force --server letsencrypt  --keylength 4096
[Fri Dec 20 14:32:43 CST 2024] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Fri Dec 20 14:32:43 CST 2024] Creating domain key
[Fri Dec 20 14:32:44 CST 2024] The domain key is here: /root/.acme.sh/baidu.com/baidu.com.key
[Fri Dec 20 14:32:44 CST 2024] Multi domain='DNS:baidu.com,DNS:monitor.baidu.com'

3、而如果在*前面增加转义则正常
./acme.sh --issue --dns dns_dp -d baidu.com -d \*.baidu.com  --force   --keylength 4096  
[Fri Dec 20 14:34:40 CST 2024] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Fri Dec 20 14:34:40 CST 2024] Multi domain='DNS:baidu.com,DNS:*.baidu.com'
[Fri Dec 20 14:34:40 CST 2024] Getting domain auth token for each domain
[Fri Dec 20 14:34:44 CST 2024] Getting webroot for domain='baidu.com'
[Fri Dec 20 14:34:44 CST 2024] Getting webroot for domain='*.baidu.com'

**Comment by 692568516** [comment]
如果在泛域名的※前面增加转义符则会正常

**Comment by 692568516** [comment]
更新到最新版本也是一样的情况，和https://github.com/acmesh-official/acme.sh/issues/4507 一样，bash下执行会有改问题，zsh下正常

**Comment by Neilpang** [comment]
使用 单引号 包裹域名

**Comment by Neilpang** [comment]
![image](https://github.com/user-attachments/assets/2a76ddde-0f7a-4918-8e8f-104dadfa1548)
