### ISSUE TITLE
Add generation of ca chain for OCSP

### ISSUE THREAD

**Issue by fblz** [acmesh-official/acme.sh#656]
I am currently trying to set up OCSP stapling with nginx. Therefore I want to pass the ca chain to the [ssl_trusted_certificate](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_trusted_certificate) option. The default letsencrypt client seems to generate the needed file, but I can not find one in the acme.sh directory. Is it possible to add generation of this file?

**Comment by Tntdruid** [comment]
mine are in /root/.acme.sh/mydomain.tld/ca.cer

**Comment by chinkung** [comment]
From [ssl_trusted_certificate](https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_trusted_certificate) document

> For verification to work, the certificate of the server certificate issuer, the root certificate, and all intermediate certificates should be configured as trusted using the ssl_trusted_certificate directive.

I think **ca.cer** contains only Intermediate certificate WITHOUT root certificate

**Comment by gemini00** [comment]
any update on this issue?

Thank you.

**Comment by Neilpang** [comment]
>> I think ca.cer contains only Intermediate certificate(s) WITHOUT root certificate

There is no need to contain the  ROOT cert.

And including the ROOT cert will never increase the trust of a cert:

1.  if the ROOT cert is already in the client machine cert store,   we don't need to include it.
2.  otherwise, the ROOT cert is no more than a self-signed cert from the client's perspective,  the client would never simply trust selft signed cert.

**Comment by fblz** [comment]
According to the nginx documentation for [ssl_stapling_verify](https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_stapling_verify), there should be a file that contains the root cert.
This has nothing to do with client trust, but with ocsp stapling. As you can read in the documentation of [ssl_trusted_certificate](https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_trusted_certificate) this is not even send to the client.

**Comment by Neilpang** [comment]
As there is no way in ACME protocol to get the Root cert,  we can not get it.

On the other hand,  in the OCSP response message of letsencrypt responder, there is no "Certificate" contained, so, you don't need to enable " ssl_stapling_verify". 
Just set :
```
ssl_stapling on;
```

It's working for me.

**Comment by Neilpang** [comment]
@fblz
