### ISSUE TITLE
Support  automatic issue hook for Lighttpd?

### ISSUE THREAD

**Issue by LexiconCode** [acmesh-official/acme.sh#687]
Would you consider supporting  a automatic issue hook for Lighttpd.

**Comment by Neilpang** [comment]
do you mean automatic issue hook ?  just like we are supporting like `--apache` and `--nginx` ?

**Comment by LexiconCode** [comment]
Yes

**Comment by Neilpang** [comment]
give me some time.

**Comment by Tntdruid** [comment]
Any update on this?

**Comment by Neilpang** [comment]
@Tntdruid 
Sorry, I don't have time recently.

**Comment by Deses** [comment]
+1 on this request, please. :)
