### ISSUE TITLE
Feature-Request: install option to generate file with full chain + private key

### ISSUE THREAD

**Issue by MarcusWolschon** [acmesh-official/acme.sh#793]
CourierMTA, lighthttps, haproxy,... and other mail servers require a .pem file that contains not only the certificate but also the private key in the same file.
acme.sh --install 
only allows the options:
  --cert-file                       After issue/renew, the cert will be copied to this path.
  --key-file                        After issue/renew, the key will be copied to this path.
  --ca-file                         After issue/renew, the intermediate cert will be copied to this path.
  --fullchain-file                  After issue/renew, the fullchain cert will be copied to this path.
I request a feature
  --fullchain_and_key-file                   After issue/renew, the fullchain cert and the key will be copied to this path.

**Comment by Neilpang** [comment]
you can combine the files by yourself in `reloadcmd`.

**Comment by MarcusWolschon** [comment]
Thanks. I did not think of this possible workaround to solve the imediate issue

**Comment by yastupin** [comment]
Just for the record, because I found this issue looking for direct haproxy support too, `--reloadcmd` can be used without installing key and fullchain first:

```
acme.sh \
  --install-cert \
  -d dom.tld \
  --reloadcmd \
    "cat \$CERT_KEY_PATH \$CERT_FULLCHAIN_PATH >/etc/haproxy/certs/dom.tld && \
    service haproxy restart"
```

**Comment by d4tocchini** [comment]
Until #4581 is accepted, here's how to use the HAProxy deploy hook to update certificates without haproxy restart & without root access: [Letsencrypt integration with HAProxy and acme.sh](https://github.com/haproxy/wiki/wiki/Letsencrypt-integration-with-HAProxy-and-acme.sh)
