### ISSUE TITLE
CNAME challenge support

### ISSUE THREAD

**Issue by candlerb** [acmesh-official/acme.sh#957]
Suppose you want to use the DNS-01 challenge without opening up your whole domain or domains to dynamic DNS updates.

Letsencrypt supports the following way of working:

~~~
# Statically added CNAME
_acme-challenge.www.example.com.  CNAME  _acme-challenge.www.example.com.acme.example.net.

# Dynamically added TXT record
_acme-challenge.www.example.com.acme.example.net.  TXT "xxxxxx"
~~~

It would be nice to have support for this.  One way would be via configuration: maybe as simple as

~~~
DNS_SUFFIX=acme.example.net
...
txtdomain="_acme-challenge.$d${DNS_SUFFIX+.}${DNS_SUFFIX}"
~~~

A configuration-free way would be via checking explicitly for a CNAME:

~~~
txtdomain="_acme-challenge.$d"
cname="$(dig +short "$txtdomain" CNAME)"
if [ -n "$cname" ]; then
  txtdomain="${cname%.}"
fi
~~~

**Comment by Neilpang** [comment]
we supported alias mode:
https://github.com/acmesh-official/acme.sh/wiki/DNS-alias-mode
